### ISSUE TITLE
BinAuth Option

### ISSUE THREAD

**Issue by laksa19** [openNDS/openNDS#100]
How to set BinAuth can't be use if the username already authenticated, until client logout?

**Comment by bluewavenet** [comment]
@laksa19 
Note: BinAuth username/password authentication is deprecated.
What version of openNDS are you using and on what operating system?
Can you explain what you are trying to do?

**Comment by laksa19** [comment]
I am using version 5.2.0 of OpenWrt
I want to try, if the username has been used to log in by client A and is still connected to wifi, then that username cannot be used by client B, C or D until client A logs out.

**Comment by bluewavenet** [comment]
@laksa19 

> I am using version 5.2.0 of OpenWrt

Can I assume you mean openNDS v5.2.0 on OpenWrt 19.07.xx?

Note my previous statement:
**BinAuth username/password authentication is deprecated.**

In the current version of openNDS (v8.0.0), the example files for username/password login are no longer supplied.
Instead, the functionality is provided by Preauth.

**If you are working on ongoing development, I suggest you upgrade.** 

openNDS v8.0.0 works fine on OpenWrt 19.07.x and the version in the upcoming OpenWrt 2x.x.x will be at least openNDS v8.0.0
The upgrade is simple and I can give instructions if needed.

> .....then that username cannot be used by client B, C or D until client A logs out.

The best way would be to parse the log file for user A login and then check if there is a user A deauth. Then decide if auth is allowed.

openNDS v5.2.0 does not have the **logout** page that is included in v8.0.0, you would have to wait for client A to timeout.

**Comment by laksa19** [comment]
Thank you for the answer
