### ISSUE TITLE
opkg-command not found

### ISSUE THREAD

**Issue by tobiaskastl** [openNDS/openNDS#101]
Hello!

I am currently trying to upgrade from NDS to openNDS and I got the advice from @bluewavenet to remove the existing libmicrohttpd-dev and nodogsplash. I was able to remove lib with apt-get remove - but when I try to "opkg remove nodogsplash", I get the following error:
"-bash: opkg: command not found"
Is there another way to uninstall nodogsplash?

**Comment by minhng99** [comment]
`opkg` is an OpenWRT command, you seem to be running Ubuntu/Debian which doesn't have `nodogsplash` in their repo

**Comment by bluewavenet** [comment]
@tobiaskastl 
Yes, as @minhng99 says, opkg is an OpenWrt specific command. It is similar to Debian's apt command.

**Nodogsplash does not install itself correctly on generic Linux so you have to manually remove it.**
These commands should do it:
```
rm -R /etc/nodogsplash
rm /usr/bin/ndsctl
rm /usr/bin/nodogsplash
```

**Comment by tobiaskastl** [comment]
@minhng99 @bluewavenet Thanks, going to try that!

**Comment by tobiaskastl** [comment]
Sorry to interrupt again, I just want to make sure I am doing nothing wrong. I removed NDS and libmicrohttpd - 
1. Do I just need to follow those steps on _"https://opennds.readthedocs.io/en/stable/compile.html"_? 
2. _"First, create a working directory and cd into it."_ - like, create a new directory called openNDS or is navigating to /etc enough?
3. Do I also need to _"sudo rm /usr/local/lib/libmicrohttpd*"_, although I just uninstalled the libmicrohttpd?
Would be great if you could answer me those questions - as I said, I don't want to ruin something =)

![image](https://user-images.githubusercontent.com/72079975/105888400-367dfd80-600d-11eb-8f0d-0772b43aa6ba.png)

**Comment by bluewavenet** [comment]
@tobiaskastl 

> Do I just need to follow those steps on "https://opennds.readthedocs.io/en/stable/compile.html"?

Yes

> "First, create a working directory and cd into it." - like, create a new directory called openNDS or is navigating to /etc enough?

You need to create a working directory just for this. /opennds would be perfect.

**Make sure you download the LATEST versions of openNDS and libmicrohttpd**

> Do I also need to "sudo rm /usr/local/lib/libmicrohttpd*"

Quite possibly even after the apt-get remove. Do it to be safe.

**Comment by tobiaskastl** [comment]
Hey, sorry for annoying again..

What is meant by "./configure --disable-https"? Should I just start with the command beneath - "make"? If I type "configure --disable-https", I get "configure: command not found".

Thanks in advance

**Comment by bluewavenet** [comment]
@tobiaskastl 
You must type in exactly:
```
./configure --disable-https
make
sudo rm /usr/local/lib/libmicrohttpd*
sudo make install
sudo rm /etc/ld.so.cache
sudo ldconfig -v
cd ..
```

The "dot slash" in front of the word "configure" is the syntax for telling the Bash script interpreter to run the script "configure".

The "--disable-https" is the required option for the "configure" script

"make" is the Linux command to compile, or "make" the executable software from the source files and should not be run as root, which is why it is not preceded by "sudo".
