### ISSUE TITLE
Failed to start openNDS Captive Portal

### ISSUE THREAD

**Issue by tobiaskastl** [openNDS/openNDS#102]
Hello everyone!

I just downloaded _"libmicrohttpd-0.9.72.tar.gz"_ and _"opennds/tar.gz/v8.0.0"_ on my raspberry. There were no problems while installing (I haven't seen any). As I try to start the captive portal by typing _"sudo systemctl start opennds"_, it's not even loading for a second. _"sudo systemctl status opennds"_ returns _"Failed to start openNDS Captive Portal"_, with those messages:

`
opennds.service: Service RestartSec=100ms expired, scheduling restart.
`
`
opennds.service: Scheduling restart job, restart counter is at 5.
`
`
Stopped openNDS Captive Portal.
`
`
opennds.service: Start request repeated too quickly.
`
`
opennds.service: Failed with result 'exit-code'.
`
`
Failed to start openNDS Captive Portal.
`

I already tried "sudo journalctl -e", but none of the 1001 lines have anything to do with openNDS. I also look into the .conf-file, but did not notice anything weird. Anyone got an idea? :|

**Comment by bluewavenet** [comment]
@tobiaskastl 
The most likely reasons for this to happen are:
1. Failure to install correctly
2. Failure to configure the host network correctly as a router.

Please show the the output of:
`sudo systemctl status opennds`

It should look similar to this output I get here on a test system running on OpenSuse:
```
rob@linux-fak2:~> sudo systemctl status opennds
● opennds.service - openNDS Captive Portal
   Loaded: loaded (/etc/systemd/system/opennds.service; disabled; vendor preset: disabled)
   Active: active (running) since Wed 2021-01-27 20:07:01 GMT; 25s ago
  Process: 7057 ExecStart=/usr/bin/opennds $OPTIONS (code=exited, status=0/SUCCESS)
 Main PID: 7058 (opennds)
    Tasks: 4 (limit: 4915)
   CGroup: /system.slice/opennds.service
           └─7058 /usr/bin/opennds

Jan 27 20:07:02 linux-fak2 opennds[7057]: [5][Wed Jan 27 20:07:02 2021][7058](src/util.c:236) Attempting to Bind to interface: wlan0
Jan 27 20:07:03 linux-fak2 opennds[7057]: [5][Wed Jan 27 20:07:03 2021][7058](src/main.c:395) Interface wlan0 is up
Jan 27 20:07:03 linux-fak2 opennds[7057]: [5][Wed Jan 27 20:07:03 2021][7058](src/main.c:410) Interface wlan0 is at 10.248.5.115 (74:de:2b:b1:70:33)
Jan 27 20:07:03 linux-fak2 opennds[7057]: [5][Wed Jan 27 20:07:03 2021][7058](src/main.c:450) Created web server on 10.248.5.115:2050
Jan 27 20:07:03 linux-fak2 opennds[7057]: [5][Wed Jan 27 20:07:03 2021][7058](src/main.c:460) Click to Continue option is Enabled.
Jan 27 20:07:03 linux-fak2 opennds[7057]: [5][Wed Jan 27 20:07:03 2021][7058](src/main.c:472) Preauth is Enabled - Overiding FAS configuration.
Jan 27 20:07:03 linux-fak2 opennds[7057]: [5][Wed Jan 27 20:07:03 2021][7058](src/main.c:585) FAS URL is http://10.248.5.115:2050/opennds_preauth/
Jan 27 20:07:03 linux-fak2 opennds[7057]: [5][Wed Jan 27 20:07:03 2021][7058](src/main.c:657) Forwarding Authentication is Enabled.
Jan 27 20:07:04 linux-fak2 opennds[7057]: [5][Wed Jan 27 20:07:04 2021][7058](src/fw_iptables.c:375) Initializing firewall rules

```

**Comment by bluewavenet** [comment]
@tobiaskastl 
If journalctl is genuinely not showing any output from opennds, then, I am pretty sure that either:
1. It is starting without error
2. The opennds executable is missing

**Comment by bluewavenet** [comment]
@tobiaskastl 
Run the command:
`opennds`

Then show any output here

**Comment by bluewavenet** [comment]
Check you have met the network configuration prerequisites:
https://opennds.readthedocs.io/en/stable/install.html#prerequisites

**Comment by bluewavenet** [comment]
@tobiaskastl 
A bug has been found but I am not sure if it is the cause of your issue.

Try adding the following line to your opennds.conf file (if it is not already there):
`gatewayfqdn status.client`

**Comment by bluewavenet** [comment]
@tobiaskastl 
The Rpi is a good general purpose IoT/SBC, but it does not have the hardware to be a good router.
Because of this, it is very important to look very closely at the openNDS prerequisites as it is very easy to get it wrong especially if you are new to routing configurations.
Having said this, the above mentioned bug is probably the cause of the failure to start.

**Comment by tobiaskastl** [comment]
Gonna have a look soon, thanks a lot! Quite busy with school atm

**Comment by tobiaskastl** [comment]
Hey @bluewavenet ! I just tried your commands and simply typing "opennds" returns "libmicrohttpd is out of date, please upgrade to version 0.9.71 or higher" - but I downloaded "0.9.72.tar.gz". Should I uninstall this version and install the .71? 

> Try adding the following line to your opennds.conf file (if it is not already there):
> `gatewayfqdn status.client`

Yep, that line was already there.

> Because of this, it is very important to look very closely at the openNDS prerequisites as it is very easy to get it wrong >especially if you are new to routing configurations.

I think it should work fine - it worked with NDS and I strictly followed a tutorial. If the different version from libmicro won't work, I'm gonna check it again.

Although: quick question to this topic. I read the following: 

_-i 'network interface' : The packet is only checked if it is the defined network interface | -o 'network interface' : The packet is only checked if it is sent via the defined network interface._ 

The tutorial I followed had an iptable-command where it said "-o eth0". Doesn't the eth0-interface receive packets or have i mistunderstood something? Shouldn't it be "-i eth0"? If I work with "-o", shouldn't it be 'wlan0' - my network, which my clients connect to? Maybe a stupid question, just wondering.

**Comment by tobiaskastl** [comment]
How can I check, which version of "libmicrohttpd" is installed? I have the tar.gz and the unpacked folder in my opennds-directory, could that create an error? Or should I just execute the commands from "https://opennds.readthedocs.io/en/stable/compile.html" again?

**Comment by bluewavenet** [comment]
@tobiaskastl 
It sounds like you still have the old version installed.
You must do ALL the libmicrohttpd installation parts from the documentation.

The `sudo ldconfig -v` is VERY important.

> -i 'network interface' : The packet is only checked if it is the defined network interface | -o 'network interface' : The packet is only checked if it is sent via the defined network interface.

This makes no sense out of context - I have no idea what it means.

> The tutorial I followed...

Most of the Rpi "Tutorials" I have seen people use are either very out of date or totally wrong - sorry.

> 'wlan0' - my network, which my clients connect to?

Yes, the wireless interface will be the one clients connect to and the one openNDS binds to.

eth0 will be the "WAN", connected to an Internet feed (eg your ISP router).

**Comment by tobiaskastl** [comment]
Hey - I just tried to remove libmicrohttpd-dev by using _apt-get remove_ and I got "libmicrohttpd is not installed" as an answer. I haven't gotten any errors during the installation tho - can I somehow check which version is installed? I'm going to try to download 0.9.71 now, I don't know why it's not working..

**Comment by tobiaskastl** [comment]
Hey, I fixed the problem by setting _use_outdated_mhd_ to "1". This issue is solved now, but I don't really understand how I can authenticate my phone now. 

If I type "172.16.0.3:2050", I get to "Network Authentication Required - Refresh / Portal Login". If I hit "Portal Login", it tries to connect to "detectportal.firefox.com" (as described in the docs - Captive Portal Detection) - but it can't (obviously, because it's not connected via lan to my internet; reason below). 

Should this button authenticate my device? If so, can I somehow avoid using wifi to authenticate my device? I have no internet connection where my access point is being used later - would it be possible to somehow simulate a WAN?

Can I use the openNDS CP to grant access to some ports only? I know, the CP works by detecting port 80 requests - which is about using it as a router - but I only need it for granting my users access to 172.16.0.3:3000 and 172.16.0.3:5000. If that does not make any sense, I can explain my situation with more details.

**Comment by bluewavenet** [comment]
@tobiaskastl 

> I fixed the problem by setting use_outdated_mhd to "1"

I am guessing this is most likely due to compiling openNDS with the old version of MHD installed and only updating to the latest version afterwards. The compiler uses microhttpd.h and at compile time would have found the old version.
If my guess is correct, then you might get away with it, or possibly see issues later.... not sure without looking in detail at the code. 
I would suggest removing both MHD and openNDS and starting again - just to be safe.

> If I type "172.16.0.3:2050", I get to "Network Authentication Required

This shows openNDS is so far working as designed.

> I don't really understand how I can authenticate my phone

For the captive portal to automatically open on client devices (eg your phone) then you must either:
 1. Have an active Internet connection to allow client devices to resolve DNS, or;
 2. Enable Dnsmasq offline mode
 
This is discussed elsewhere in detail, but if you need help please open a new issue for "Enabling Offline Working"

> Can I use the openNDS CP to grant access to some ports only?

Yes, but get it working in offline mode first - in other words, one step at a time - this will help in your understanding of how it all fits together.

**Comment by bluewavenet** [comment]
@tobiaskastl 

> I can explain my situation with more details.

This would be sensible.

**Comment by tobiaskastl** [comment]
Thanks, gonna try to get dnsmasq to run offline.

Alright, where do I start.. My boss introduced me into his new project - a raspberry pi 3b+ with an IoT-gateway and some sensors implemented. This "measuring device" can measure for example temperature, pressure, etc. On port 3000, there is a visual presentation of each sensor (called "Grafana") and on port 5000, there is a REST-API with the possibility to configure, if the sensor should be active (and measure data) or if it's not active.

His idea was to create a hotspot without wifi-access / access-point / offline network - however you want to call it. It should be possible to connect to the hotspot with your mobile phone, open an app and be able to configure the "activity" of the sensors (I'm not responsible for the app; just for the hotspot + access). That's already done; the access point is up and running with no connection to the internet. 

Another task is to have this hotspot secured in some way - it should not be possible for everyone to connect to the AP. The hotspot has a wpa2-passphrase (simple hotspot password), but it should have more security. My task was to do some research and implement a solution.

That's why I thought of a captive portal. The user connects to the access point, but has no access to port 3000 and 5000 yet (browser -> 172.16.0.3:3000 -> access rejected because I set an iptable-command to block it). After this user authenticates himself on the captive portal, the access should be granted (so the user can either access the ports in the browser or the app has access to the REST-API). The information of the connected user is also saved somewhere on the pi (if this information is useful in any way).

I hope I made my situation more clear - and thanks for the huge support @bluewavenet ! Really did not expect someone to waste their time to help a noob like me that much.

**Comment by bluewavenet** [comment]
@tobiaskastl 

> try to get dnsmasq to run offline

**Hint**: From a closed issue:
For offline working you must configure dnsmasq to return a public ip address ie NOT a private (RFC1918) address.
eg:
address:/#/123.123.123.123
It does not matter what it is as long as it is not a private address. It does not matter if there is something live at that address either, as, of course, you are offline.

The reason for requiring a public ip address is simple:
An increasing number of vendor CPD implementations implement their own DNS Rebind protection by discarding upstream RFC1918 responses to their own CPD FQDN. The result is that such CPD implementations will not trigger the splash page.

**Comment by bluewavenet** [comment]
@tobiaskastl 

> a hotspot without wifi-access

I assume you mean  "_without wifi-access to the Internet_"

> browser -> 172.16.0.3:3000 -> access rejected because I set an iptable-command to block it

It is important to to allow openNDS to configure its own firewall settings as it adds its rules to the top of the chain. Part of openNDS is a "firewall manager".
