### ISSUE TITLE
Dnsmasq enable offline working

### ISSUE THREAD

**Issue by tobiaskastl** [openNDS/openNDS#105]
Hey,

as @bluewavenet noted in my last issue (#102), I'm currently working on enabling "offline dnsmasq". I kind of followed https://docs.lando.dev/guides/offline-dev.html#mac-specific-instructions and that's the content of my dnsmasq.conf:

`
interface=wlan0
`
`
dhcp-range=172.16.0.30, 172.16.0.40, 12h
`
`
address=/tfap/127.0.0.1
`
`
expand-hosts
`
`
domain=tfap
`

Before I tried that, I had "server=8.8.8.8" for forwarding dns-requests to Google DNS. But after "deactivating" this line and a restart, I still have the old server in my settings (it's in german, but should be easy to understand):

![20d3c1ac-3a82-4e4a-860e-ef45c7024996](https://user-images.githubusercontent.com/72079975/106933656-77ff5e80-6719-11eb-85b6-fc898d3db688.jpg)

I created the file _tfap_ with the content "nameserver 127.0.0.1" in "/etc/resolver". Shouldn't I get 127.0.0.1 in the section "DNS"? I feel like I forgot to mention the path to this file somewhere - how should it work without declaring where my "offline dns address" is located? Or have I misunderstood something?

**Comment by bluewavenet** [comment]
@tobiaskastl 
Unfortunately the link you have followed has **_no relevance_** to Offline Mode of openNDS.

You should configure Dnsmasq to provide DHCP as normal and DNS as normal, but you do not need to configure a forwarder.

Then add to /etc/dnsmasq.conf, the single line:
` address:/#/123.123.123.123`

Then restart everything. Now when you connect your phone, it will attempt to resolve the ip address of its CPD detection URL and get 123.123.123.123

CPD* (a service that runs on your phone) will then attempt to open `http://123.123.123.123:80` thus triggering the portal page from openNDS.
(*) CPD (Captive Portal Detection).
Please Read: https://opennds.readthedocs.io/en/stable/howitworks.html#captive-portal-detection-cpd

Once you get this working we can move on to allowing access to your local web server(s).

**Comment by tobiaskastl** [comment]
Thanks @bluewavenet ! Instead of the ":" behind _address_, a "=" worked for me! I now get the notification to log in to this network - awesome! I guess I should create a new issue if I'm stuck at accessing my ports? In fact: is there anything special I need to watch out for?
