### ISSUE TITLE
Failed to start openNDS Captive Portal

### ISSUE THREAD

**Issue by KamikoAoi** [openNDS/openNDS#106]
openNDS fails to start after boot / after being run manually

Running on a Rasberry pi3b
After following the instructions to set It up on general linux devices

I have not edited anything outside the openNDS GatewayInterface

Incase there is another better solution to my use case:

I'm trying to get a captive where a simple store is setup, was using nodogsplash without issues but I need to use php and a database to manage the site and to store the purchases (just for making orders rather then paying online), the sites just for a school project so the reason may seem weird but I thought I'd be fun to mess around with

Hoping to make it so users can click on the network on their phone and automatically be shown the site without needing to go to a ip etc, captive portals seemed to be the way to go

I'd perfer if I could make it so the captive portal would open automatically even when the pi does not have wifi but I couldn't get this working with nodogsplash and I'm not sure if I'd be able to here either, worst case its connected via ethernet (as it is now) and I just dont authenticate users so they dont have access to the network

After running systemctl status opennds.service:

```
Loaded: loaded (etc/systemd/system/opennds.service; enabled: vendor present: enabled)
Active: failed (Result: exit-code) since DATE-HERE: 4s ago
Process: 1472 ExecStart=/usr/bin/opennds $OPTIONS (code=exited, status=0/SUCCESS)
Main PID: 1473 (code=exited, status=1/FAILURE)

rasberrypi systemd[1]: opennds.service: Service RestartSec=100ms expired, scheduling restart 
rasberrypi systemd[1]: opennds.service: Scheduled restart job, restart counter is at 5
rasberrypi systemd[1]: Stopped openNDS Captive Portal 
rasberrypi systemd[1]: opennds.service: Start request repeated too quickly.
rasberrypi systemd[1]: opennds.service: Failed with result 'exit-code' 
rasberrypi systemd[1]: Failed to start openNDS Captive Portal
```
(I apologize if there is any typos, typed that manually on the android github app since its running off of a pi3 b so I cant copy the text and send it easily)

I've tried changing the GatewayInterface to eth0 as well as wlan0 and the issue happens on both, not sure if it's a issue with that but it was worth a shot.

**Comment by KamikoAoi** [comment]
Ah just read down in closed and seen that there is a similar issue explained, sorry about that didnt show up indexed in google.

**Comment by bluewavenet** [comment]
@KamikoAoi 
Assuming you are runnning opennds v8.0.0, make sure you have the following line in your opennds.conf file:
`gatewayfqdn status.client`

Also make sure you have downloaded, compiled and installed libmicrohttpd version 0.9.71 or later.

Gatewayinterface is the network interface that openNDS binds to and the interface clients will attach to.

> I'd prefer if I could make it so the captive portal would open automatically even when the pi does not have wifi

I am sure you mean the pi does not have **_Internet_**

Running without Internet is called "Offline mode".
This is achieved by a special configuration in Dnsmasq.

See #105

**Comment by KamikoAoi** [comment]
Ah yes it seems like a version issue, when installing a newer version of libmicrohttpd do I need to uninstall the old version somehow or do I just follow the steps to install it with a newer version and itll override what it needs to itself 

And yes I meant internet, oops

**Comment by bluewavenet** [comment]
If you used apt to install the ancient version of libmicrohttpd-dev in the Deb repository, then you must uninstall first.

Please also read and follow the documentation at:
https://opennds.readthedocs.io/en/stable/compile.html#linux-unix-compile-in-place-on-target-hardware

The pi zero w has more than enough ram, however, like all current Rpi models, it does not make a very good router due to the very limited open source support fro the Broadcom wireless chip.
Personally, I would instead recommend one of the many low cost OpenWrt supported routers for a Captive Portal solution.

**Comment by bluewavenet** [comment]
@KamikoAoi 
If you have any further questions either reopen this or start a new issue.
