### ISSUE TITLE
Error in Firewall-Rules (ports)

### ISSUE THREAD

**Issue by tobiaskastl** [openNDS/openNDS#108]
Hey!

My captive portal is working, but now I'm stuck again. A detailed description of my situation can be found here: #102 

I thought I'd just put _FirewallRule allow tcp port 3000_ and _FirewallRule allow tcp port 5000_ under the heading "FirewallRuleSet authenticated-users". I did not touch "preauthenticated-users" or "users-to-router" at all.

When opennds is running (and I haven't clicked "Continue" yet), I can't connect to :3000 or :5000 - nice. But after clicking "Continue", I get the following "error" on my pi (I have "sudo opennds" running):

`
iptables: Bad rule (does a matching rule exist in that chain?).
`

-> Not as far as I know :/ My iptables-file looks like this:

![iptables](https://user-images.githubusercontent.com/72079975/107147524-d7927f80-694e-11eb-8e31-9977934dff11.jpg)

What did I do wrong?

**Comment by bluewavenet** [comment]
@tobiaskastl 

> "sudo opennds"

You should NOT do this. openNDS probably will not initialise properly and you will most likely see many problems associated with it.

> My iptables-file....

This is a very hacky way of saving/restoring iptables settings. I know it seems to be used in the Rpi world, but the proper way in Linux would be to use the firewalld service. Perhaps this is not available under RaspberryOS?
Anyway, if you need to use this make sure openNDS is not running when you save and restore before openNDS starts, otherwise - much trouble could ensue.

> iptables: Bad rule (does a matching rule exist in that chain?)

This is probably just informational. It is difficult to tell if you are starting openNDS from the command line.

> I thought I'd just put FirewallRule allow tcp port 3000 and FirewallRule allow tcp port 5000 under the heading "FirewallRuleSet authenticated-users"

The default rule for authenticated users is "allow all", so I don't think anything needs to be added.

**Comment by tobiaskastl** [comment]
Alright, gonna see if the firewalld-service is available.

Is the right way to start opennds _sudo service opennds start_?

Do I need to block e.g. port 3000 "by hand"? Or does opennds do this automatically? (the commented line in the *filter table)

**Comment by bluewavenet** [comment]
@tobiaskastl 

> Alright, gonna see if the firewalld-service is available.

Don't let me send you off at a tangent :-D
xtables save will do the job, you just have to make sure it restores the iptables before openNDS starts up as well as ensure the restore does not contain any entries from a previous instance of openNDS.

**Comment by bluewavenet** [comment]
@tobiaskastl 

> Is the right way to start opennds sudo service opennds start?

Yes - It will initialise correctly and run in the background.

> Do I need to block e.g. port 3000 "by hand"?

No - For preauthenticated users, openNDS allows only rules in "users to router" and "preauthenticated users"

**Comment by bluewavenet** [comment]
@tobiaskastl 
Something quite unrelated to the issue and a bit intolerant of me, but could you use the phrase "going to" instead of the slang "gonna"?
The latter makes my brain itch :-D Sorry

**Comment by tobiaskastl** [comment]
@bluewavenet 

> Something quite unrelated to the issue and a bit intolerant of me, but could you use the phrase "going to" instead of the slang "gonna"?

Excuse me, won't happen again ^^

> Don't let me send you off at a tangent :-D
> xtables save will do the job, you just have to make sure it restores the iptables before openNDS starts up as well as ensure the restore does not contain any entries from a previous instance of openNDS.

No worries, I'm just experimenting with some alternatives.

**Comment by tobiaskastl** [comment]
@bluewavenet 
Alright, I think I will stick with xtables - I have never worked with FirewallD and I don't really know how to configure those settings.

>make sure it restores the iptables before openNDS starts up 

Because of "iptables-restore < /etc/network/iptables" in _/etc/rc.local_, the iptable-commands should be loaded when my pi is booting. 

I need to start hostapd, dnsmasq and opennds manually (because the pi is read-only and I need to mount it first) - is there a bypass to solve this problem? Like, write a script that starts the services by just typing a command in the console or so?

>ensure the restore does not contain any entries from a previous instance of openNDS

How exactly can I ensure that? If I type "sudo iptables -L -n -v", no entry is associated with openNDS.

>>"sudo opennds"

>You should NOT do this.

Is there any other way to see what is happening - real time?

**Comment by bluewavenet** [comment]
@tobiaskastl 

While you are developing, one time only, do:
`sudo systemctl disable opennds`

Then reboot.
Then manually do `sudo systemctl start opennds` when you want it to start.

`sudo systemctl status opennds` will show you what is going on.

**Comment by tobiaskastl** [comment]
@bluewavenet 

> While you are developing, one time only, do:
> `sudo systemctl disable opennds`

I managed to fix that, thanks. 

But when I enter "sudo ndsctl status", I get my state of my connected phone:

First preauthenticated and (after pressing "Continue") authenticated - so it _should_ work. 

I still have no access to port 3000 nor 5000 - do you have any idea why?

**Comment by bluewavenet** [comment]
@tobiaskastl 
If you stop opennds, do you get access?

**Comment by tobiaskastl** [comment]
@bluewavenet Yes - I just tried that.

**Comment by bluewavenet** [comment]
@tobiaskastl 
Do you still have the following in opennds.conf?
```
FirewallRuleSet authenticated-users {
  FirewallRule allow all
}
```

**Comment by tobiaskastl** [comment]
@bluewavenet 
Yes, only this line.

**Comment by tobiaskastl** [comment]
@bluewavenet 
I really don't know why it's not working - could there be a problem with permissions? Do you think that granting 777 to my openNDS-directory would make any sense?

**Comment by bluewavenet** [comment]
@tobiaskastl 

> my openNDS-directory

You mean where you downloaded it to and where you ran make?
That won't make any difference. Remember you finally ran `sudo make install`

Are you sure you have not manually added iptables rules to block the two sites? You did at one stage. Are these now in your iptables restore?

**Comment by tobiaskastl** [comment]
@bluewavenet 

I just noticed that there are two different types of saving / restoring the iptables - one with ">" and one with "<". Since I can't remember that I used "iptables-save > /etc/network/iptables" to really save them (I just restored them in /etc/rc.local), I tried to execute that command: _Permission denied_

I got that information from:
https://www.thomas-krenn.com/en/wiki/Saving_Iptables_Firewall_Rules_Permanently

And it seems like some other people had this problem too:
https://unix.stackexchange.com/questions/345212/permission-denied-when-saving-iptable-rules-in-debian-8

It won't change anything about my problem with the non-accessible ports, but I thought I'd want this to be done right. Can I just enter "XaviEE86" 's lines without worrying about "destroying" something?

**Comment by tobiaskastl** [comment]
I just tried "sudo iptables-save | sudo tee /etc/network/iptables" and I got the content of the file - I don't know if it worked.

Since you mentioned the "iptables-restore" - isn't that just a command to restore the iptable-entries after booting?

I also tried to replace _iptables_ with _nftables_ a few weeks ago, since I heard that nftables is newer and better - but there are also the "block"-commands were commented (I deleted them).

> Are you sure you have not manually added iptables rules to block the two sites?
I'm pretty sure that there are no rules left that could block them. I have access to the sites (when openNDS is not running) after all.

**Comment by bluewavenet** [comment]
@tobiaskastl 
Ah! This is a bug. It is very much an edge case. Normally it is done the other way round ie access is granted in users to router typically for granting access to a FAS. However it is only "users to router" that grants access to services on the router.

As a test, try setting:
```
login_option_enabled 0
fasport 3000
```
Making sure any faspath entry is commented out.

Then restart openNDS and connect a client.
This should redirect the client directly to port 3000.

I have tries this here and it works. So should work for you.
Now I need to fix the bug ;-)

**Comment by tobiaskastl** [comment]
@bluewavenet Alright, I added those lines to my _opennds.conf_ and yep, I get redirected to port 3000 - awesome!

What about port 5000? Can I simply add another "fasport 5000"? Or is it only possible to have one port enabled?

You mentioned a bug - I guess there is no possibility to have the "real method" to authenticate yet, right? (Connect to hotspot - no access to ports; accept on the captive portal - access to ports)

**Comment by tobiaskastl** [comment]
@bluewavenet Is there any way to support your work by donating to the project or something? It's really kind of you to assist a newbie like me and I'd like to thank you for all of your invested time!

**Comment by bluewavenet** [comment]
@tobiaskastl 
It isn't a bug as such, it is because when a client tries to access the router at a specific port and the port is not in the "users to router" section then it is denied even if authenticated. Instead of denying, the firewall should return to the rule chain.
I'm looking at implementing an enhancement....

**Comment by bluewavenet** [comment]
@tobiaskastl 
You can support the project by continuing to use it and becoming less of a newbie (as you are doing) and more of a seasoned user. Then you can find more bugs as well as recommend it to others :-D

**Comment by tobiaskastl** [comment]
@bluewavenet Alright!

>Instead of denying, the firewall should return to the rule chain.

Is there anything I can do to solve this myself? The solution doesn't have to be "pretty" at all.

**Comment by bluewavenet** [comment]
@tobiaskastl 
Done. Quite an easy to implement enhancement - just one line of code. I'm testing it at the moment in case it breaks something else and will push to master soon if all is good.

**Comment by tobiaskastl** [comment]
@bluewavenet Alright, awesome!

**Comment by bluewavenet** [comment]
@tobiaskastl 
Try recompiling from master:
https://github.com/openNDS/openNDS/archive/master.zip
Please test and comment ;-)

**Comment by tobiaskastl** [comment]
@bluewavenet Uhm.. what exactly should I do now? A step by step guide would be awesome - just install the link you just sent me?

**Comment by bluewavenet** [comment]
@tobiaskastl 
Download the zip and unzip into a suitable folder.
Then follow the openNDS compilation instructions, skipping the libmicrohttpd part as you already have the correct version of that. 
eg:
Make a backup of /etc/opennds/opennds.conf
Unzip the downloaded zip into a new folder, say opennds-8.0.1beta, then do

```
cd openNDS-8.0.1beta
make
sudo make install
sudo systemctl enable opennds
sudo systemctl start opennds

```

**Comment by tobiaskastl** [comment]
@bluewavenet Alright, I'm going to try that now. Thanks!

**Comment by bluewavenet** [comment]
@tobiaskastl 
You should probably first do:
```
sudo systemctl stop opennds
sudo systemctl disable opennds
```

**Comment by tobiaskastl** [comment]
@bluewavenet Awesome, it works as expected!

I would like to thank you for every minute you spent on my problem! It's unreal, thank you very much! If there is anything else I can do other than keep supporting - like donating - let me know! I'm really grateful for everything =)

**Comment by bluewavenet** [comment]
@tobiaskastl 
It would be much appreciated if you could donate some of your time doing testing the various possibilities of openNDS outside your current project..... It would also be good experience for you.

**Comment by tobiaskastl** [comment]
@bluewavenet 
Going to see what I can do! My focus is on my final exam in about 3 months for now. Thanks for everything :)

**Comment by bluewavenet** [comment]
@tobiaskastl 
Good luck!

**Comment by bluewavenet** [comment]
@tobiaskastl 
openNDS v8.0.1 release will be available soon. Probably a good idea to upgrade when it comes out.
