### ISSUE TITLE
loop while trying to access

### ISSUE THREAD

**Issue by richyxi** [openNDS/openNDS#109]
Hi! 
Im having some issues while im trying to connect. Basically when i send the 'GET' request with all the parameters, the url http://192.168.8.1:2050/opennds_auth response with a 307 code and it redirects me with a new FAS, i have seen the logs at the 3 debugger level, and i dont see the 'invalid token' log, it just looks like the process which do the hid, the query strings and then the fas start again when send the request

Here are the logs: https://pastebin.com/ziCQ9Nqt
** its a little clear there than passing details here :p

set up:
nds: 8.0.0
openwrt: 19.07
router: gl.inet mango

My config:
config opennds
        option enabled '1'
        option fwhook_enabled '1'
        option gatewayinterface 'br-lan'
        option gatewayfqdn 'status.client'
        option maxclients '250'
        option preauthidletimeout '30'
        option sessiontimeout '1200'
        option checkinterval '60'
        option uploadrate '0'
        option downloadrate '0'
        option ratecheckwindow '2'
        option uploadquota '0'
        option downloadquota '0'
        list authenticated_users 'allow all'
        list users_to_router 'allow tcp port 53'
        list users_to_router 'allow udp port 53'
        list users_to_router 'allow udp port 67'
        list users_to_router 'allow tcp port 22'
        list users_to_router 'allow tcp port 23'
        list users_to_router 'allow tcp port 80'
        list users_to_router 'allow tcp port 443'
        option fasremoteip '35.173.69.207'
        option fasport '80'
        option fasremotefqdn 'innerout.pythonanywhere.com'
        option fas_secure_enabled '2'
        option gatewayname 'zitla-cumbres-1-America/Monterrey'
        option faskey 'FASKEY'
        option binauth '/root/run.sh'
        option redirecturl 'https://www.google.com/'
        option authidletimeout '22'
        option use_outdated_mhd '1'
        option debuglevel '3'

dev console:
![Captura de pantalla de 2021-02-08 23-31-35](https://user-images.githubusercontent.com/47098907/107320193-e029a980-6a65-11eb-928c-52ec29e6ff85.png)

Thanks in advance and have a great day!

**Comment by bluewavenet** [comment]
@richyxi 

From your logs:
`Tue Feb  9 04:10:16 2021 daemon.debug opennds[25063]: redirect_url after binauth deny: http://connectivity-check.ubuntu.com/
`

This shows your binauth script is denying access (by returning exit code > 0
When this happens, openNDS re-calls FAS so the client can try logging in again but as you are not passing any custom data to binauth there will be no difference and the client will fail again.

You have not shared your run.sh, but you should look in there for the problem ...
For a quick test you could try the default binauth script by changing option binauth to:
`option binauth '/usr/lib/opennds/binauth_log.sh'`

**Comment by bluewavenet** [comment]
@richyxi 

Looking at your config:
 1. option redirecturl has been deprecated for some time and will be ignored entirely in v8.0.0
 2. Make sure you have also upgraded libmicrohttpd. In openNDS v8.0.0, there is no guarantee that option "use_outdated_mhd" will work successfully. Random crashes or a complete failure to start are the most common outcomes. You need libmicrohttpd v 0.9.71 or above (downloadable from OpenWrt Snapshots).

**Comment by richyxi** [comment]
it was indeed the binauth script, it had the #!/bin/bash shebang, mainly bc i was prototyping in a raspian env. 
i read in docs that for my openwrt version it needs the latest version of libmicrohttpd  so i already installed it, in case of any misbehavior will be posted

also, quick question for general purpose
i have noticed that on some devices, functions like fetch() in js will work but not in some cases, is there a documentation about the browser engine of these CPD and its limitations?. based on my experience with captive portals theres a lot of with social login which involve oauth and a redirection to its login page(js function for fb for eg.) so its a little tricky

thanks a lot for your help!

**Comment by bluewavenet** [comment]
@richyxi 
Consider that a Captive Portal is a "Man in the Middle Attack Engine".
An unscrupulous person could easily set up a captive portal to pretend it is something else entirely and as such is potentially a very high security risk. For this reason just about all up to date implementations of CPD have restrictions on what is possible, particularly where downloading and running external code from unknown sources is concerned.
In addition, most implementations of CPD are proprietary code from the individual vendors. No vendor wants to be in the news as the one that can be attacked so all of them work hard to protect their customers.   

> is there a documentation about the browser engine of these CPD and its limitations?

No, for the reasons mentioned above.
