### ISSUE TITLE
BinAuth and fas_secure_enabled = 3 ?

### ISSUE THREAD

**Issue by monelgordillo** [openNDS/openNDS#11]
Is BinAuth and fas_secure_enabled = 3 still not compatible?  I noticed the comment in the documentation but wanted to double-check.  *crossing fingers*

**Comment by bluewavenet** [comment]
@monelgordillo 
I'm actually working on this now :-D
The problem is because level 3 uses a different mechanism for NDS authentication - fairly easy to implement a binauth/level 3 support mode - coming soon.
_[beware the wizardry of the crossed monelgordillo fingers]_

**Comment by monelgordillo** [comment]
> @monelgordillo
> I'm actually working on this now :-D
> The problem is because level 3 uses a different mechanism for NDS authentication - fairly easy to implement a binauth/level 3 support mode - coming soon.
> _[beware the wizardry of the crossed monelgordillo fingers]_

Excellent. 👍

**Comment by bluewavenet** [comment]
@monelgordillo 
Implemented in v5.1.0beta ;-)

**Comment by bluewavenet** [comment]
@monelgordillo 
Version 5.1.0 is now released.
https://github.com/openNDS/openNDS/releases/tag/v5.1.0
