### ISSUE TITLE
Changing name of preauth script does not work.

### ISSUE THREAD

**Issue by mk248** [openNDS/openNDS#113]
OpenNDS on OpenWrt will always call `/usr/lib/opennds/login.sh`, ignoring the `option preauth` in the configuration.  I think this results from the code related to interaction with `login_option_enabled` around line 483 in main.c.  If legacy splash is going to be removed, I would suggest removing this interaction entirely and making `login_option_enabled` simply a parameter that is passed to the preauth script.

**Comment by bluewavenet** [comment]
@mk248 
A good find, thanks.
Fixed and tested, will push to master soon.

**Comment by bluewavenet** [comment]
@mk248 
Fixed with PR #114 

Was this the issue you wanted to talk about?

**Comment by mk248** [comment]
No. There's a serious vulnerability that allows anyone connected to the
hotspot to execute arbitrary code on the router, but I did not want to post
it publicly.
