### ISSUE TITLE
Data usage limit?

### ISSUE THREAD

**Issue by monelgordillo** [openNDS/openNDS#12]
Howdy,

I noticed that example #2 for BinAuth has session_length for limiting internet access based on time/seconds.  

Is there something available for limiting internet access based on GB, instead of time?  For example, a client device download/upload 2 GB worth of data for however long he/she wants.

Thank you, in advance.

**Comment by bluewavenet** [comment]
@monelgordillo 
There are _currently_ no plans to add built in quota functionality as the standard tools and API provided by openNDS provide the ability to produce custom solutions to this requirement without requiring any openNDS code modifications.
I am sure you will ask for some hints....
eg "You could use the json output of ndsctl to monitor client data usage"

**Comment by bluewavenet** [comment]
@monelgordillo 
Version 5.1.0 is now released and it includes data volume and data rate quotas.
https://github.com/openNDS/openNDS/releases/tag/v5.1.0

I did say there were _"currently"_ no plans. 5 weeks is a long time ;-)
