### ISSUE TITLE
openNDS only works when the pi is connected to my router

### ISSUE THREAD

**Issue by tobiaskastl** [openNDS/openNDS#120]
Hey!

In order to download packages on my pi, I connected it with a lan-cable to my router and disabled my static ip-address by "commenting out" the ip-configuration in "/etc/network/interfaces" (reboot -> pi gets new ip address from my router -> internet-access).

I now realised that my openNDS only works when the lan-cable is connected (although I have the static IP-address active).

When I start the openNDS-service and check with "systemctl status opennds", I get the error "Job for dnsmasq.service failed because the control process exited with error code. See "systemctl status opennds.service" and "journalctl -xe" for details"

-> When the pi is **connected** to my router with a cable, I somehow sometimes get the error, but it doesn't matter - the CPD triggers and everything works fine.
-> When the pi is **not** connected to my router with a cable, the error always triggers, while the CPD does not trigger.

The problem is that I want my raspberry to be working where-ever I want; it shouldn't be "bound" next to my router.

The strange thing is: there is no specific explanation what's failing when I enter look at the status of dnsmasq.

This is my config of dnsmasq:

interface=wlan0
dhcp-range=172.16.0.30,172.16.0.80,12h
address=/#/123.123.123.123

I just tried "sudo systemctl restart networking" and "sudo systemctl status networking" and I get the following:

![image](https://user-images.githubusercontent.com/72079975/108632180-dba1bf80-746d-11eb-8889-58d944f0b63e.png)

First status in the picture: dnsmasq
Second status in the picture: networking

I requested an "apt-get upgrade" and "apt-get update" about a few days ago, because the error was already present and I thought that an update might solve it (which did not work). Any idea where the problem could be?

**Comment by bluewavenet** [comment]
@tobiaskastl 

> In order to download packages on my pi, I connected it with a lan-cable to my router and disabled my static ip-address by "commenting out" the ip-configuration in "/etc/network/interfaces" (reboot -> pi gets new ip address from my router -> internet-access).

This statement tells all!

A fundamental requirement for openNDS is that it MUST be running on a device configured as an IPv4 router.
ie 
 * The device must have two network interfaces
 * The first interface (usually wireless) configured as a stand alone local area network with its own dhcp and its own dns
 * The first interface ip address subnet MUST be different to that used by any Internet connection ie your ISP router's lan
 * This first interface must also be the default gateway for its stand alone local area network (lan)
 * This first interface must masquerade its private address to the second interface using network address translation (nat) 
 * The second interface (usually ethernet) must be the upstream Internet connection or wide area network (wan)
 * The second interface must be configured as a dhcp client to obtain an upstream ip address, dns and gateway information.
 
For offline operation, the Dnasmasq configuration is modified as previously discussed, ie by adding:
` address=/#/123.123.123.123`

For online use this line must be removed.
A restart is required when changing between online and offline

**Comment by tobiaskastl** [comment]
@bluewavenet 
Right, but is there any way to simulate a second interface? So there is an eth0-connection, but the cable is not really plugged in?

Can I add, like, an "eth0" configuration where I configured "wlan0"?

**Comment by bluewavenet** [comment]
@tobiaskastl 
Which model rpi do you have?
They all have 2 interfaces apart from the zero I think.

For the captive portal to work the interface that openNDS is bound to MUST be the default gateway of the network that clients are attaching to (as well as hosting DNS and DHCP for use by the clients).

**Comment by bluewavenet** [comment]
@tobiaskastl 

> When the pi is connected to my router with a cable

So you do have an ethernet port.....

**Comment by tobiaskastl** [comment]
@bluewavenet I have the raspberry pi 3b+. 

> For the captive portal to work the interface that openNDS is bound to MUST be the default gateway of the network that clients are attaching to (as well as hosting DNS and DHCP for use by the clients).

My wlan0, right?

> So you do have an ethernet port.....

Yes, I have an ethernet port.

**Comment by bluewavenet** [comment]
@tobiaskastl 
You will have to do some research, rather than try my patience Grrrr! :-D
Try searching for something like "configuring an rpi as a router". 
eg
https://www.raspberrypi.org/documentation/configuration/wireless/access-point-routed.md

**Comment by tobiaskastl** [comment]
@bluewavenet Alright, going to see what I can do ;)

**Comment by tobiaskastl** [comment]
@bluewavenet Sorry for asking again, but could something like this work?

https://unix.stackexchange.com/questions/152331/how-can-i-create-a-virtual-ethernet-interface-on-a-machine-without-a-physical-ad

You probably have an eye for that - if you have the time to check this link real quick.

**Comment by bluewavenet** [comment]
@tobiaskastl 

> could something like this work?

Probably. But why do this when you have a real ethernet interface.
If configured correctly as a router, when in offline mode, opennds will work with or without a connection to the Internet.
In online mode, it will work only with a connection.
So configured as I am suggesting, the normal state will be "offline"
When you need to do maintenance, plug in the feed, and switch to "online".
A much simpler setup in my opinion.

**Comment by tobiaskastl** [comment]
@bluewavenet I'm not sure if I understand you correctly..

> If configured correctly as a router, when in offline mode, opennds will work with or without a connection to the Internet.

Do I understand this right?
Offline = _**no**_ lan-cable **plugged in**; pi has a static ip address from _/etc/network/interfaces_; openNDS works
Online = lan-cable **plugged in**; pi gets ip address from the router for internet-access (to download packages etc;) - openNDS won't work

> Normal state will be "offline"
> When you need to do maintenance, plug in the feed, and switch to "online".

Are you suggesting me to add a configuration for eth0, just as I did for wlan0 (see picture below; something like that)? 

![image](https://user-images.githubusercontent.com/72079975/108847033-7f5ead00-75df-11eb-92e1-be9a2d755c2a.png)

> plug in the feed and switch to "online"

Do you mean by commenting out the configuration?
(Just as I'm currently doing it with the static ip of the pi? As I mentioned in the initial comment of this post, _commenting out the ip-configuration in "/etc/network/interfaces"_)

Sorry if I'm completely lost by now 😅

**Comment by bluewavenet** [comment]
@tobiaskastl 
Mmm ;-) Yes, a bit lost.

To repeat what I said earlier:
A fundamental requirement for openNDS is that it MUST be running on a device configured as an IPv4 router.
ie 
 * The device must have two network interfaces
 * The first interface (usually wireless) configured as a stand alone local area network with its own dhcp and its own dns
 * The first interface ip address subnet MUST be different to that used by any Internet connection ie your ISP router's lan
 * This first interface must also be the default gateway for its stand alone local area network (lan)
 * This first interface must masquerade its private address to the second interface using network address translation (nat) 
 * The second interface (usually ethernet) must be the upstream Internet connection or wide area network (wan)
 * The second interface must be configured as a dhcp client to obtain an upstream ip address, dns and gateway information.

The "first interface", wlan0, will be set up in AP mode, run DHCP and DNS servers (ie Dnsmasq) and be the default gateway of its own ip address subnet.

The "second interface", eth0, will be set up as a DHCP client. This means it will obtain its ip configuration from whatever it is connected to - this means it will become a member of a completely separate ip subnet (the subnet of your ISP router)

Network Address Translation (nat) will connect the first interface to the second. This means packets arriving at wlan0 will have their source address (eg the ip address of your phone), changed to the address of eth0 before being forwarded onto the ISP router and the Internet.

With the cable unplugged, packets sent to the Internet will go nowhere.

As I also previously stated:
For offline operation, the Dnsmasq configuration is modified as previously discussed, ie by adding:
address=/#/123.123.123.123

For online use this line must be removed.
A restart is required when changing between online and offline.

**Comment by tobiaskastl** [comment]
@bluewavenet Thanks for the detailed information! Works now, thanks a lot!

**Comment by bluewavenet** [comment]
@tobiaskastl 
It would be very useful if ypu could share your network config for the benefit of others if you would not mind ;)

**Comment by tobiaskastl** [comment]
Sure.

I changed from "auto" to "allow-hotplug", because I couldn't boot with "auto":
"A start job is running for Raise network interfaces".

![network-config](https://user-images.githubusercontent.com/72079975/109048822-d0ea6300-76d7-11eb-8690-b773cfe8736e.png)
