### ISSUE TITLE
disable web server

### ISSUE THREAD

**Issue by laimermic** [openNDS/openNDS#123]
A quick Question: How do i disable the own web server from openNDS and use my own (lighttpd)?

Needs FAS its own port
or can i use the web servers port?
I thought everything required for FAS gets passed by the web server

**Comment by bluewavenet** [comment]
@laimermic 
The MHD (libmicrohttpd) web server is a fundamental part of the workings of the captive portal and cannot be disabled.
 * Every client is redirected to MHD by the client's own CPD, where it does a 307 temporary redirect to FAS, wherever it is located.
 * MHD  serves error 511 and the client status pages to the client when required
 * MHD provides authentication and deauthentication urls for FAS to use


FAS can be:
 * Also served by MHD
 * A local web server on its own port
 * A web server on an other device in the local network
 * A web server on a remote network (eg the Internet)

In your case, Lighttpd would be configured to use its own ip port (this must not be the same as MHD).

I would recommend you read the FAS documentation at:
https://opennds.readthedocs.io/en/stable/fas.html#forwarding-authentication-service-fas

Finally note that openNDS v8.1.1 was released this week, so I recommend you upgrade if you have not done so already.
