### ISSUE TITLE
Move services to another partition

### ISSUE THREAD

**Issue by tobiaskastl** [openNDS/openNDS#124]
Hello again =)

I don't really know where I should ask this question, so I thought I'd ask here.

(My **/etc** - partition is mounted **read-only**)

For my small project, I am using the services _hostapd_, _dnsmasq_ and _openNDS_. While _hostapd_ starts after booting, _dnsmasq_ can't run with a "read-only filesystem". And therefore, since _openNDS_ needs _dnsmasq_ to run, _openNDS_ is not working aswell.

Currently, I need to mount the partition by typing "sudo mount -o remount, rw /" and "sudo mount -o remount, rw /boot" so my services (especially _dnsmasq_) run(s). I would like to change that-> every service should run after booting without needing to type some mount-commands in the console.

I know that the partition /data is writable - can I somehow move the whole service to this partition? Just moving the config-files doesn't seem right - any ideas?

**Comment by sicelo** [comment]
What OS are you running this on?

**Comment by tobiaskastl** [comment]
@sicelo Typing "uname -o" returns _GNU/Linux_. I don't know if that helps.

**Comment by bluewavenet** [comment]
@tobiaskastl 

> My /etc - partition is mounted read-only

/etc should just be a folder, not a partition.
I have a pi zero w here for test purposes and a standard boot with the latest raspberry os lite gives a /etc folder as r/w for root.
openNDS starts up with no problems.
As @sicelo  asks, what OS are you using?

You might have a corrupted SD memory card - this can result in the storage mounting as read only.......
From memory, I think the format is ext4, so you should try using the fsck utility to try fixing the corruption.

**Comment by tobiaskastl** [comment]
@bluewavenet Sorry, I made a mistake. I meant that the root-partition is read-only mounted.

The storage should not be corrupted. When I received the pi, it came with this information:

_The root partition is mounted read-only, if you want to install something you have to change the mount:_
_sudo mount -o remount,rw /_

**Comment by bluewavenet** [comment]
@tobiaskastl 
In that case this is not an issue with openNDS. I suggest you contact the supplier of the pi.
openNDS only requires read/write access when installing and when you make configuration changes so once you have finished configuring there should not be a problem.

**Comment by tobiaskastl** [comment]
@bluewavenet 

> openNDS only requires read/write access when installing

That's why I wrote this:

> I don't really know where I should ask this question, so I thought I'd ask here.

It's more about dnsmasq - I was curious if there was a simply answer to this problem.

Do you know why exactly dnsmasq needs a writable filesystem? Is the information of the user stored in any file? Would editing the permission with chmod for those files solve the problem?

**Comment by bluewavenet** [comment]
@tobiaskastl 

> Do you know why exactly dnsmasq needs a writable filesystem?

It doesn't - writable only needed when configuring. It caches data in /run in Debian and that is a "ramdisk".

**Comment by tobiaskastl** [comment]
@bluewavenet Oh.
I thought it needs one because I get "cannot open or create lease file /var/lib/misc/dnsmasq.leases: Read-only file system" when I type "sudo systemctl status dnsmasq".

**Comment by tobiaskastl** [comment]
When I enter /var/lib/misc, there is a file dnsmasq.leases with my mac-addresses. Can't I just edit the permissions for this file? 😅

**Comment by bluewavenet** [comment]
@tobiaskastl 
I'm not sure but I think /var is an alias for /run and as I said that is a ramdisk (tmpfs) to prevent flash wear that would otherwise occur on the SD card.
Root must have R/W access for DHCP to work as Dnsmasq normally runs as root...

Given that you previously installed opennds and dnsmasq, you must have remounted as R/W for the install.
This must be a completely locked down system not intended to be configured as anything else than a device connected to an existing local area network.

As I said earlier, this is not an opennds issue. You should ask the people who originally supplied the device.

**Comment by tobiaskastl** [comment]
@bluewavenet Thanks for the answer, I guess I will ask the supplier for an idea.

Would it be possible to permanently remount a partition? So I'd never have to manually mount again?

**Comment by sicelo** [comment]
You would need to look into `/etc/fstab` or whatever other facility your
OS uses. However you would probably need to first find out why they
decided to mount it `ro` for you.

Good luck :)

**Comment by bluewavenet** [comment]
@tobiaskastl 

> Would it be possible to permanently remount a partition? 

Yes, pretty standard stuff, but you need to understand why it is set up as it is.

**Comment by bluewavenet** [comment]
@tobiaskastl 
Please feel free to comment here if you have further questions on this issue.

**Comment by tobiaskastl** [comment]
@bluewavenet @sicelo I actually have one.

I got in contact with the supplier of the pi and he "allowed" me to change the pi to a writable one. He also mentioned "/etc/fstab".

Now I would like to ask, which factors I would have to change in order to achieve a writable pi after boot:

![fstab](https://user-images.githubusercontent.com/72079975/110677615-a7e8c880-81d5-11eb-930e-94f85d25d8fa.png)

Both "ro" - entries to "rw" in PARTUUID=...-01 and -02?

**Comment by sicelo** [comment]
Yes, just -02
Pun: learn a little fstab - it won't stab you ;-))

**Comment by tobiaskastl** [comment]
@sicelo Alright, thanks!

;)
