### ISSUE TITLE
No Token with FAS on openWRT

### ISSUE THREAD

**Issue by iTommix** [openNDS/openNDS#125]
@bluewavenet 

I have installed version 8.1.1, along with MHD 0.9.71 on openWRT

If i connect to my FAS there is no token submitted to the page. I have an debug output of all variables are submitted, and the Value of token is (null). See the Screenshot.

If i try to authenticate, is see in logread:

Thu Mar 4 09:50:35 2021 daemon.info dnsmasq-dhcp[6930]: DHCPREQUEST(br-lan) 192.168.1.215 a2:48:7e:b1:3b:3d
Thu Mar 4 09:50:35 2021 daemon.info dnsmasq-dhcp[6930]: DHCPACK(br-lan) 192.168.1.215 a2:48:7e:b1:3b:3d
Thu Mar 4 09:50:43 2021 daemon.warn opennds[6712]: Token is invalid
Thu Mar 4 09:50:43 2021 kern.info kernel: [ 7386.879809] MHD-single[6774]: segfault at 0 ip 08054743 sp b7e9ae60 error 4 in opennds[804a000+f000]
Thu Mar 4 09:50:48 2021 daemon.notice opennds[7172]: openNDS Version 8.1.1
Thu Mar 4 09:50:48 2021 daemon.notice opennds[7172]: Attempting to Bind to interface: br-lan

and it looks like opennds restarts. Whats your opinion?

![IMG_7199](https://user-images.githubusercontent.com/22579516/109955455-cd139d80-7ce2-11eb-961f-b437a9f76362.jpeg)

**Comment by bluewavenet** [comment]
@iTommix 
Please show the output of:
`uci show opennds`

**Comment by iTommix** [comment]
@bluewavenet 

opennds.@opennds[0]=opennds
opennds.@opennds[0].enabled='1'
opennds.@opennds[0].debuglevel='1'
opennds.@opennds[0].fwhook_enabled='1'
opennds.@opennds[0].gatewayinterface='br-lan'
opennds.@opennds[0].gatewayname='OpenWrt openNDS'
opennds.@opennds[0].gatewayfqdn='status.client'
opennds.@opennds[0].maxclients='250'
opennds.@opennds[0].preauthidletimeout='30'
opennds.@opennds[0].authidletimeout='120'
opennds.@opennds[0].sessiontimeout='1200'
opennds.@opennds[0].checkinterval='60'
opennds.@opennds[0].uploadrate='0'
opennds.@opennds[0].downloadrate='0'
opennds.@opennds[0].ratecheckwindow='2'
opennds.@opennds[0].uploadquota='0'
opennds.@opennds[0].downloadquota='0'
opennds.@opennds[0].binauth='/root/iptables.sh'
opennds.@opennds[0].fasport='80'
opennds.@opennds[0].fasremotefqdn='domain.com'
opennds.@opennds[0].fasremoteip='my.ip.add.ress'
opennds.@opennds[0].faspath='/wifi/login.php'
opennds.@opennds[0].faskey='1234567890'
opennds.@opennds[0].fas_secure_enabled='2'
opennds.@opennds[0].authenticated_users='block to 192.168.178.0/24' 'allow all'
opennds.@opennds[0].users_to_router='allow tcp port 53' 'allow udp port 53' 'allow udp port 67' 'allow tcp port 22' 'allow tcp port 23' 'allow tcp port 80' 'allow tcp port 443'

**Comment by bluewavenet** [comment]
@iTommix 
Ah yes, I remember this. Check these points:
 * fas_secure_enabled='2' does not use the legacy token, it must return rhid, the "return hash id", calculated using the shared secret faskey (see the fas-hid.php example)
 * Previously you had your binauth script restarting opennds via a restart of fw3 - presumably you still have this in place...

It is interesting though that MHD seems to be segfaulting, but before we look at that we need to check out the above points.

**Comment by iTommix** [comment]
> fas_secure_enabled='2' does not use the legacy token, it must return rhid, the "return hash id", calculated using the shared secret faskey (see the fas-hid.php example)

Strange... because i didn't changed the configuration there between v5. and v8.

You mean this:

`if ($name == "hid") {$hid=$value;}`

i Try.

>Previously you had your binauth script restarting opennds via a restart of fw3 - presumably you still have this in place...

No. i commented it out.

**Comment by iTommix** [comment]
This is how i calculate the token:

1. Get the hid

`if ($name == "hid") {$hid=$value;}`

2. Hashing hid + key

`$tok=hash('sha256', $hid.$key);`

Result:

Thu Mar  4 13:25:25 2021 daemon.warn opennds[7249]: Token is invalid

**Comment by bluewavenet** [comment]
@iTommix 
The title of this issue is "No Token with FAS on openWRT".
FAS does not receive the legacy token, instead it receives hid, the "hashed id".
`hash('sha256', $hid.$key);` calculates rhid. The example code should really call it $rhid to prevent confusion I guess.

What is "10: (null)" in your image?

I guess it is restarting because MHD is segfaulting. Immediately after openNDS sees the token is invalid, it will call the binauth script. 

If you disable binauth, does opennds still restart?

**Comment by iTommix** [comment]
@bluewavenet 

>The title of this issue is "No Token with FAS on openWRT".

Of course, because openNDS tells me that the Token is invalid, because i dont get one ;)

>The example code should really call it $rhid to prevent confusion I guess.

I took it from your example. Look at line 151 in fas-hid.php

Even it's now hashed hid+key, the GET-Variable still is "tok", yes?

>What is "10: (null)" in your image?

Well, there was the token in v5.x. Instead of (null) there was "tok=xxxxxx". This is how i debugged that in the past and now:

`foreach($dec_r as $key => $value) {
      echo '<h1>'.$key.' : '.$value.'</h1><br>';
}`

This is in my binauth right now:

#!/bin/sh

METHOD="$1"
MAC="$2"

case "$METHOD" in
  auth_client)
    #iptables -I zone_lan_forward 2 -m mac --mac-source "$MAC" -d 192.168.178.0/24 -m comment --comment "!fw3: GUEST" -j zone_wan_dest_REJECT
    #printf "iptables -I zone_lan_forward 2 -m mac --mac-source $MAC -d 192.168.178.0/24 -m comment --comment '!fw3: GUEST' -j zone_wan_dest_REJECT\n" >> /etc/firewall.user
    #/etc/init.d/firewall restart
    echo 86400 0 0
    exit 0
    ;;
  client_auth|client_deauth|idle_deauth|timeout_deauth|ndsctl_auth|ndsctl_deauth|shutdown_deauth)
    INGOING_BYTES="$3"
    OUTGOING_BYTES="$4"
    SESSION_START="$5"
    SESSION_END="$6"
    # client_auth: Client authenticated via this script.
    # client_deauth: Client deauthenticated by the client via splash page.
    # idle_deauth: Client was deauthenticated because of inactivity.
    # timeout_deauth: Client was deauthenticated because the session timed out.
    # ndsctl_auth: Client was authenticated by the ndsctl tool.
    # ndsctl_deauth: Client was deauthenticated by the ndsctl tool.
    # shutdown_deauth: Client was deauthenticated by Nodogsplash terminating.
    ;;
esac

As you can see... no restart of iptables anymore.. i disabled it

Version: 8.1.1
Uptime: 7s
Gateway Name: OpenWrt openNDS
Managed interface: br-lan
Managed IP range: 0.0.0.0/0
Server listening: http://192.168.1.1:2050
Binauth: Disabled
Preauth: Disabled

but the result is the same: segfault on MHD and restart of openNDS

**Comment by bluewavenet** [comment]
@iTommix 
I wanted you to test with binauth disabled to eliminate that as a cause.

What is your php code that displays the "10 : (null)" ?

My test system here with fas-hid.php works fine. Can you test by uploading fas-hid.php?

I suspect you have an error that is sending an invalid parameter ( causing the "10 : (null)" ).
This in turn possibly exposing a bug in opennds that results in MHD segfaulting.
It would be helpful if you could run my suggested tests.
ie 
1. binauth disabled, then test
2. upload fas-hid.php, then test

**Comment by iTommix** [comment]
@bluewavenet 

>I wanted you to test with binauth disabled to eliminate that as a cause.

The last test (look at my last Post) was with binauth **disabled**.

>What is your php code that displays the "10 : (null)" ?

Look my last Post:

`foreach($dec_r as $key => $value) { echo '<h1>'.$key.' : '.$value.'</h1><br>'; }`

where `$dec_r` is the decrypted parameter `fas` (`$_GET["fas"]`)

>I suspect you have an error that is sending an invalid parameter ( causing the "10 : (null)" ).

No, that are the parameter comes from openNDS to FAS (to my PHP-Script).

>Can you test by uploading fas-hid.php?

Of course. I'll tell you the result.

**Comment by bluewavenet** [comment]
@iTommix 
Ah!!
Sorry, I'm being stupid...
It should of course be `fas_secure_enabled='1'` in the config for fas-hid... :-D

**Comment by iTommix** [comment]
@bluewavenet 

It's really weird:

I tested your script, and my iPhone tells me `could not find the site` after clicking on `Agree the Terms`-Button.

I debugged your url in the submit-form ($authaction on thankyou_page) and its `http:///opennds_auth/`, what means the variable `$gatewayaddress` is empty.

Digging a bit deeper, you decrypt the $fas with `$decoded=base64_decode($fas);` but the result is'nt decrypted (i echoed on the page). I guess you missing `openssl_decrypt`

**Comment by bluewavenet** [comment]
@iTommix 
We both repied at almost the same time! **fas_secure_enabled='1'** for fas-hid.

**Comment by bluewavenet** [comment]
@iTommix 
This does not explain why MHD was segfaulting.....

**Comment by iTommix** [comment]
@bluewavenet 
> We both replied at almost the same time! **fas_secure_enabled='1'** for fas-hid.

It works even with fas_secure_enabled='2' if you add

$iv=$_GET['iv'];
$cipher="AES-256-CBC";
$decoded=openssl_decrypt(base64_decode($fas), $cipher, $key, 0, $iv );

The result then is:

Thu Mar  4 16:00:45 2021 daemon.info opennds[9185]: Our host: 192.168.1.1:2050 Requested host: 192.168.1.1:2050
Thu Mar  4 16:00:45 2021 daemon.notice opennds[9185]: Authenticating 192.168.1.215 a2:48:7e:b1:3b:3d
Thu Mar  4 16:00:45 2021 daemon.info opennds[9185]: auth_change_state > authenticated - download_rate [0] upload_rate [0]
Thu Mar  4 16:00:45 2021 daemon.info opennds[9185]: An authenticated client is requesting: host [192.168.1.1:2050] url [/images/splash.jpg]
Thu Mar  4 16:00:45 2021 daemon.info opennds[9185]: Our host: 192.168.1.1:2050 Requested host: 192.168.1.1:2050

**Seems authenticated.**

**Comment by bluewavenet** [comment]
@iTommix 
That is basically the difference between fas-hid  and fas-aes

fas-hid is designed for devices with limited resources ie small iot devices. It does not need php-cli  and php-openssl  for opennds.

**Comment by iTommix** [comment]
@bluewavenet 

Ok, at the end i ask myself why openNDS tells me the token is invalid, because i generate it like you do, and submit it like you do:

`$key="1234567890";`
    $cipher="AES-256-CBC";
    if (isset($_GET['fas']) and isset($_GET['iv']))  {
        $string=$_GET['fas'];
        $iv=$_GET['iv'];
        $decrypted=openssl_decrypt( base64_decode( $string ), $cipher, $key, 0, $iv );
        $dec_r=explode(", ",$decrypted);
        foreach ($dec_r as $dec) {
            list($name,$value)=explode("=",$dec);
            if ($name == "clientip") {$clientip=$value;}
            if ($name == "clientmac") {$clientmac=$value;}
            if ($name == "gatewayname") {$gatewayname=$value;}
            if ($name == "tok") {$tok=$value;}
            if ($name == "gatewayaddress") {$gatewayaddress=$value;}
            if ($name == "authdir") {$authdir=$value;}
            if ($name == "originurl") {$originurl=$value;}
            if ($name == "clientif") {$clientif=$value;}
            `if ($name == "hid") {$hid=$value;}`
        }
       ` $tok=hash('sha256', $hid.$key); `

and the form is:

```
<form method="get" action="http://'.$gatewayaddress.'/'.$authdir.'/" id="form">
            <input type="hidden" name="tok" id="tok" value="'.$tok.'">
        </form>
```

without using `custom` and `redir` fields.

**Comment by iTommix** [comment]
@bluewavenet 

This is after i log in. Could it be that openNDS wants me redirect to any page after login, but the page doesnt exist? Remember, i dont use the `redir` option in the form. 

Thu Mar  4 16:30:22 2021 daemon.debug opennds[13110]: access: GET /opennds_auth/
Thu Mar  4 16:30:22 2021 daemon.debug opennds[13110]: SIGCHLD handler: Trying to reap a child
Thu Mar  4 16:30:22 2021 daemon.debug opennds[13110]: SIGCHLD handler: waitpid(): No child exists now.
Thu Mar  4 16:30:22 2021 daemon.debug opennds[13110]: preauthenticated: host [192.168.1.1:2050] url [/opennds_auth/]
Thu Mar  4 16:30:22 2021 daemon.debug opennds[13110]: config->preauthdir: [ opennds_preauth ], config->gw_fqdn: [ status.client ]
Thu Mar  4 16:30:22 2021 daemon.debug opennds[13110]: config->gw_address: [ 192.168.1.1:2050 ], config->gw_ip: [ 192.168.1.1 ]
Thu Mar  4 16:30:22 2021 daemon.debug opennds[13110]: url is [ /opennds_auth/ ], checking for [ opennds_preauth ]
Thu Mar  4 16:30:22 2021 daemon.debug opennds[13110]: url is [ /opennds_auth/ ], checking for [ opennds_deny ]
Thu Mar  4 16:30:22 2021 daemon.debug opennds[13110]: preauthenticated: Requested Host is [ 192.168.1.1:2050 ]
Thu Mar  4 16:30:22 2021 daemon.debug opennds[13110]: preauthenticated: Requested url is [ /opennds_auth/ ]
Thu Mar  4 16:30:22 2021 daemon.debug opennds[13110]: preauthenticated: Gateway Address is [ 192.168.1.1:2050 ]
Thu Mar  4 16:30:22 2021 daemon.debug opennds[13110]: preauthenticated: Gateway Port is [ 2050 ]
Thu Mar  4 16:30:22 2021 daemon.debug opennds[13110]: preauthenticated: FAS is enabled
Thu Mar  4 16:30:22 2021 daemon.debug opennds[13110]: preauthenticated: NDS port ID is [ :2050 ]
Thu Mar  4 16:30:22 2021 daemon.debug opennds[13110]: preauthenticated: NDS port ID search result is [ :2050 ]
Thu Mar  4 16:30:22 2021 daemon.debug opennds[13110]: url is [ /opennds_auth/ ], checking for [ opennds_auth ]
Thu Mar  4 16:30:22 2021 daemon.debug opennds[13110]: preauthenticated: splash.css or authdir detected
Thu Mar  4 16:30:22 2021 daemon.info opennds[13110]: Our host: 192.168.1.1:2050 Requested host: 192.168.1.1:2050
Thu Mar  4 16:30:22 2021 daemon.debug opennds[13110]: url is [ /opennds_auth/ ], checking for [ opennds_auth ]
Thu Mar  4 16:30:22 2021 daemon.debug opennds[13110]: authdir url detected: /opennds_auth/
Thu Mar  4 16:30:22 2021 daemon.debug opennds[13110]: url is [ /opennds_auth/ ], checking for [ opennds_auth ]
Thu Mar  4 16:30:22 2021 daemon.debug opennds[13110]: client->token=0f3a50ad tok=9ab1e05f497364f7b1dc8640e20b7d45de6ac20582407e2bcb4857a8a1599175
Thu Mar  4 16:30:22 2021 daemon.debug opennds[13110]: Executing command: printf '0f3a50ad' | sha256sum | awk -F' ' '{printf $1}'

**Comment by bluewavenet** [comment]
@iTommix 

> Ok, at the end i ask myself why openNDS tells me the token is invalid

Because you were running your own version of fas-hid but had fas_secure_enabled='2' (should have been ='1')

> It works ... with fas_secure_enabled='2' if you add
> 
> $iv=$_GET['iv'];
> $cipher="AES-256-CBC";
> $decoded=openssl_decrypt(base64_decode($fas), $cipher, $key, 0, $iv );

Exactly! This effectively converts to fas-aes.

> Seems authenticated.

Yes indeed ;-)

> without using ..... redir field..

redir is required for the final "landing page". Without it you will probably get a page not found error or similar.

**Comment by bluewavenet** [comment]
@iTommix 

> Could it be that openNDS wants me redirect to a.. page after login, but the page doesn't exist? Remember, i don't use the redir option in the form.

If redir is not supplied, then yes, the client browser will have a difficult job finding "redir". (redir is normally the url  the client originally requested).

The fas-hid (and fas-aes) landing page is set up to be the final page displayed in the login sequence. It has a button to go to the originally requested url, but many client CPD implementations will only briefly display this landing page, if at all.
A desktop browser CPD (eg that built into Firefox) will however display the page and allow the client to click the button.

**Comment by iTommix** [comment]
@bluewavenet 

First of all thank you for assist me. Everything works now as expected. Because of your hint

`list authenticated_users 'block to 192.168.178.0/24'`

i dont have to deal with iptables. Trusted users (handled by mac-addresses) got access to internet/intranet, while authenticated users (handled by login and voucher) only internet.

**Comment by bluewavenet** [comment]
@iTommix 
Excellent ;-)
