### ISSUE TITLE
connected clients

### ISSUE THREAD

**Issue by huhas12** [openNDS/openNDS#129]
Where are the clients logged?
Is there any way to get login data?

**Comment by bluewavenet** [comment]
@huhas12 
Assuming you are using the current version ie openNDS v8.1.1, the default logs can be found at:
`/tmp/ndslog/ndslog.log`
or
`/run/ndslog/ndslog.log`
or
`/var/ndslog/ndslog.log`

It depends on the mount point of the operating system tmpfs.

**Comment by huhas12** [comment]
> @huhas12
> Assuming you are using the current version ie openNDS v8.1.1, the default logs can be found at:
> `/tmp/ndslog/ndslog.log`
> or
> `/run/ndslog/ndslog.log`
> or
> `/var/ndslog/ndslog.log`
> 
> It depends on the mount point of the operating system tmpfs.

ok found it! is it possible to access the log file via http or download it with wget?

**Comment by bluewavenet** [comment]
@huhas12 

> is it possible to access the log file via http or download it with wget?

The log is in a Linux filesystem, so yes as long as you set something up to give you access. This is completely up to you.

However, depending what you want to achieve, there are many options. For example if you want to access the logs remotely via the Internet, then an Internet hosted FAS server would be a very simple solution.
