### ISSUE TITLE
how to setup radius server configs for w.r.t AAA(Authentication, Authorisation, Accounting) in openNDS...

### ISSUE THREAD

**Issue by bharathkspot** [openNDS/openNDS#130]
Hello, 
I need understand about the Radius server configs settings that can be done via opennds config and radius.sh script and have searched a lot for the config options for accounting, not found yet.

any help will be appreciated.

thanks in advance............!!!!!!!!!!

**Comment by bluewavenet** [comment]
@bharathkspot 

> Radius server configs settings that can be done via opennds config and radius.sh script

There is no built in support in openNDS for radius. However there is nothing to stop a custom FAS communicating with a Radius server, but this would have to be developed by you for your project. As far as I am aware, this has been done by some people using Freeradius but I have no details.

I would suggest though that you carefully consider if Radius is the correct way forward. Radius is in my opinion a "legacy" system and there are much better and easier ways of providing "AAA". Of course if you are required to use a legacy corporate radius database - it can be done.

**Comment by bharathkspot** [comment]
Thank you for the quick reply Rob White. I will look into it.


[cid:34d3b8e5-9d40-47b6-bd0d-8d877f8f90e4]

Bharath G K

Senior Software Engineer

Mobile: +91 9902281398

kloudspot.com<https://kloudspot.com/>

________________________________

**Comment by bharathkspot** [comment]
Hello RobWhite, 

Apologies for the late reply, since i was trying to config the FAS in different forms by following the and  https://github.com/openNDS/openNDS/issues/7  am not seeing any accounting activities are running or didn't get clarity on how FAS can be used along with BinAuth or Preauth, 

it will be helpful if u provide some preconfigured files or links that i can follow.....

initially i am not interested to remote FAS setup, i want try it on local device first(along with OpenNDS).

Thanks in advance.

**Comment by bharathkspot** [comment]
@bluewavenet 
below are the logs for ur reference

 1576 root      1440 S    /usr/bin/opennds -c /tmp/etc/opennds_cfg01995c.conf -f -s
 1976 root      1080 R    grep nds
root@OpenAp-400270:/etc/opennds# service opennds stop
root@OpenAp-400270:/etc/opennds# ps | grep nds
 2131 root      1080 S    grep nds
root@OpenAp-400270:/etc/opennds# /usr/bin/opennds -c /tmp/etc/opennds_cfg01995c.conf -f -s
[5][Mon Mar 29 07:37:01 2021][2132](src/main.c:639) openNDS Version 5.1.0 

[3][Mon Mar 29 07:37:01 2021][2132](src/main.c:284) libmicrohttpd is out of date, please upgrade to version 0.9.69 or higher
[5][Mon Mar 29 07:37:01 2021][2132](src/util.c:235) Attempting to Bind to interface: br-lan
[5][Mon Mar 29 07:37:01 2021][2132](src/main.c:320) Interface br-lan is up
[5][Mon Mar 29 07:37:01 2021][2132](src/main.c:335) Interface br-lan is at 192.168.1.1 (20:85:93:40:02:70)
[5][Mon Mar 29 07:37:01 2021][2132](src/main.c:375) Created web server on 192.168.1.1:2050
[5][Mon Mar 29 07:37:01 2021][2132](src/main.c:438) sha256sum provider is available
[5][Mon Mar 29 07:37:01 2021][2132](src/main.c:500) FAS URL is http://192.168.1.1:2080/www/myfas/fas-hid.php

[5][Mon Mar 29 07:37:01 2021][2132](src/main.c:572) Forwarding Authentication is Enabled.

[5][Mon Mar 29 07:37:01 2021][2132](src/main.c:577) Binauth is Enabled.

[5][Mon Mar 29 07:37:01 2021][2132](src/fw_iptables.c:374) Initializing firewall rules

**Comment by bluewavenet** [comment]
@bharathkspot 

> [I] am not seeing any accounting configs are running

This is correct. As I mentioned earlier, openNDS does not have built in support for accounting services. Instead it provides the tools for you to add the service of your choice.

> [I] didn't get clarity on how FAS can be used along with BinAuth or Preauth
 
To clarify:
 * FAS (Forward Authentication Service) is the API that allows customisation of openNDS.
 * FAS will be code that can run remotely on the Internet, remotely on another local device, or locally on the openNDS device. 
 * PreAuth is a special local FAS that uses the openNDS built in web server.
 * BinAuth is a post authentication processor, most often used for providing local logging services when the FAS server is remote.

Hints for your use case:
login.sh is the default PreAuth script (found in /etc/libs/opennds).
Look in login.sh. The functions login_form() and name_email_login() can be simply modified to collect the desired client information and validate against any accessible authentication service (eg radius).

**Comment by bluewavenet** [comment]
@bharathkspot 

> openNDS Version 5.1.0

This is very outdated. I suggest you use the current 8.1.1 version (from OpenWrt snapshots or OpenWrt 21.2).

> libmicrohttpd is out of date, please upgrade to version 0.9.69 or higher

As above. Both openNDS and libmicrohttpd snapshot versions are stable and compatible with OpenWrt 19.07.x

**Comment by bharathkspot** [comment]
sure, tnq for the quick reply, i will check with latest version and let u know the results.


[cid:0b4b10f3-d63e-49ec-bb8d-c98cab6f9976]

Bharath G K

Senior Software Engineer

Mobile: +91 9902281398

kloudspot.com<https://kloudspot.com/>

________________________________

**Comment by bharathkspot** [comment]
Hello @bluewavenet ,

I am able to install the new openNDS version 8.1.1 and libmicrohttpd 0.9.71 and both are working fine and can be seen in attached logs too.

**question 1:** do u have any idea how can i confirm that AAA is working, since am not getting/seeing any Authentication confirmation against some prelisted databse or something. now for mode2 its just taking the username and email address keeping in the /tmp/ndslog/*. 

questoin2: do you have any ida how can i control the Authorization for particualr actions w.r.t to particualr username, emailid or MACaddress??

question3: where can be the accounting information will be stored..? is there any configs update to be done for storing it in particular db or something?

FYI: as of now i can see the user details in the splsh screen as attached in the screenshot. such as
![Screenshot from 2021-03-29 18-11-55](https://user-images.githubusercontent.com/81303982/112950242-b2084200-9157-11eb-93b0-17d8606fa13e.png)
IP address: 192.168.1.174
MAC address: 74:78:27:03:03:b7
Interfaces being used by this client: br-lan
Session Start: Tue Mar 30 06:44:49 UTC 2021
Session End: Wed Mar 31 02:44:49 UTC 2021
Last Active: Tue Mar 30 06:44:55 UTC 2021
Upload Rate Limit: Unlimited Kb/s
Download Rate Limit: Unlimited Kb/s
Upload Quota: Unlimited KBytes
Download Quota: Unlimited KBytes
Uploaded This Session: 49 KBytes
Downloaded This Session: 2085 KBytes
Average Upload Rate This Session: 66.47 Kb/s
Average Download Rate This Session: 2780.01 Kb/s




Any ipputs or suggestions are accepted and appreciated highly.

Thanks in advance.

**Comment by bluewavenet** [comment]
@bharathkspot 

> question 1: do u have any idea how can i confirm that AAA is working, since am not getting/seeing any Authentication confirmation against some prelisted databse or something.

As I mentioned earlier, twice in fact, openNDS does not have built in support for accounting services. Instead it provides the tools for you to add the service of your choice.

> now for mode2 its just taking the username and email address keeping in the /tmp/ndslog/*.

Correct. It is up to you to do something with the information.

> question3: where can be the accounting information will be stored..? is there any configs update to be done for storing it in particular db or something?

As a software engineer, you will have to develop something, find some open source code to use, or licence some proprietary code. openNDS only provides the tools to enable development. I am however happy to give you _some guidance_ on how to do it.

> FYI: as of now i can see the user details in the splsh screen as attached in the screenshot.

This is the client status screen, available to clients. The url defaults to `http://status.client` and can be changed in the config (see "option gatewayfqdn")
The main purpose is to allow clients to monitor their quota consumption, as well as provide a "Logout" button.

**Comment by bharathkspot** [comment]
thank you @bluewavenet,
w.r.t my previous question 3

_question3: where can be the accounting information will be stored..? is there any configs update to be done for storing it in particular db or something?

As a software engineer, you will have to develop something, find some open source code to use, or licence some proprietary code. openNDS only provides the tools to enable development. I am however happy to give you some guidance on how to do it._


can iexpect any suggestions/guidance from u for setting up FAS for accounting...

**Comment by bluewavenet** [comment]
@bharathkspot 

> can i expect any suggestions/guidance from u for setting up FAS for accounting...

That is what I said.

Here is a hint from login.sh:
```
name_email_login() {
	# In this example, we check that both the username and email address fields have been filled in.
	# If not then serve the initial page, again if necessary.
	# We are not doing any specific validation here, but here is the place to do it if you need to.
	#
	# Note if only one of username or email address fields is entered then that value will be preserved
	# and displayed on the page when it is re-served.
	#
	# The client is required to accept the terms of service.

	if [ ! -z "$username" ] && [ ! -z "$emailaddress" ]; then
		thankyou_page
		footer
	fi

	login_form
	footer
}

```
You can see it checks if the user has entered username and email address.
It could also check the values entered against a database of some kind.

**Comment by bharathkspot** [comment]
Hello @bluewavenet ,

I was trying/working with FAS, so thought of checking with the default config values first. i have set the confgis as below
 uci show opennds
opennds.@opennds[0]=opennds
opennds.@opennds[0].enabled='1'
opennds.@opennds[0].fwhook_enabled='1'
opennds.@opennds[0].login_option_enabled='0'
opennds.@opennds[0].use_outdated_mhd='1'
opennds.@opennds[0].unescape_callback_enabled='0'
opennds.@opennds[0].gatewayinterface='br-lan'
opennds.@opennds[0].gatewayname='OpenWrt openNDS'
opennds.@opennds[0].maxclients='250'
opennds.@opennds[0].preauthidletimeout='30'
opennds.@opennds[0].authidletimeout='120'
opennds.@opennds[0].sessiontimeout='1200'
opennds.@opennds[0].checkinterval='60'
opennds.@opennds[0].uploadrate='0'
opennds.@opennds[0].downloadrate='0'
opennds.@opennds[0].ratecheckwindow='2'
opennds.@opennds[0].uploadquota='0'
opennds.@opennds[0].downloadquota='0'
opennds.@opennds[0].fasport='80'
opennds.@opennds[0].fasremotefqdn='onboard-wifi.net'
opennds.@opennds[0].fasremoteip='46.32.240.41'
opennds.@opennds[0].authenticated_users='allow all'
opennds.@opennds[0].users_to_router='allow tcp port 53' 'allow udp port 53' 'allow udp port 67' 'allow tcp port 22' 'allow tcp port 23' 'allow tcp port 80' 'allow tcp port 443'


when i tried to access 192.168.1.1 it will redirect to the splash page as expected, 
![Screenshot from 2021-04-07 16-20-11](https://user-images.githubusercontent.com/81303982/113855011-288eea80-97bd-11eb-85c6-629c5f79016f.png)

and once clicked on 'portal login' it will redirect to 
![Screenshot from 2021-04-07 16-22-19](https://user-images.githubusercontent.com/81303982/113855269-7ad00b80-97bd-11eb-89fd-f18236c2b412.png)   

but after that am not able to to access the internet via the interface where i am conneted from router from captive portal, 

the same thign am facing with 'blue-wave.net' too, once i reached the page, not able to access the internet as expected from the openNDS,

anyideas or anything am missing out, plz let me know

thank you in advance................

**Comment by bluewavenet** [comment]
@bharathkspot 
**This has nothing to do with setting up a radius server!**
Don't worry though, we can help.
First, you need to go back to basics on how openNDS works (or any captive portal for that matter).

The two config entries:
```
opennds.@openNDS[0].fasremotefqdn='onboard-wifi.net'
opennds.@openNDS[0].fasremoteip='46.32.240.41'
```
are provided only as examples in the config and not intended to be actual functional examples.
The config you have is trying to redirect to a remote FAS on the website `http://onboard-wifi.net/`, this of course does not exist.

You need to decide if you want to run a local or remote FAS and as a result need to add the dependencies required for a remote or independent FAS.

> when i tried to access 192.168.1.1 it will redirect to the splash page as expected,

What you are seeing here is **NOT** the splash page, but the error 501 page served by openNDS. **_A client should never need to access the openNDS server directly_**. All client devices (including desktop computers) have a background process running to detect if a captive portal is present and trigger the portal login when required. (ok it might be disabled on some desktops but is also active in most browsers eg Chrome and Firefox). This process is Captive Portal Detection (CPD). It is a standard, and is part of the network manager of the device operating system as well as being a built-in function of all mainstream browsers.

You must decide to use one of the following:
1. FAS using the built in web server of openNDS (the default)
2. FAS using an independent web server with php support on the openNDS router
3. FAS using a web server with php support on another "server" device on the local network
4. FAS using a web server with php support hosted somewhere on the Internet

To get a better understanding of all this, I suggest that first you read the documentation at:
https://opennds.readthedocs.io

Then if needed, open a new issue asking for help with the basics.

**Comment by bharathkspot** [comment]
yeah @bluewavenet ,

u r absolutely correct the CPD running in background on desktop(ubuntu) able to triggerportl login and shown me this  as hotspot login as shown on top of the snapshot, and further if want to access the internet, what am suppose to do, and further i ll open new issue for the topics which are other than RADIUS server, actually currently am not looking into the RADIUS server configs since i want to config with FAS as u suggested in prev question.

![Screenshot from 2021-04-07 17-40-06](https://user-images.githubusercontent.com/81303982/113864532-9ee51a00-97c8-11eb-9846-681d3e9d966c.png)

**Comment by bluewavenet** [comment]
@bharathkspot 
You are seeing this "Hotspot Login" page as you have openNDS configured to redirect to `http://onboard-wifi.net/ `
This web site though, is not configured as a FAS server so you are seeing the site "home page".

I would suggest I help you set up a remote FAS using one of the supplied php script files. This will clarify the concepts in your mind. I remember well, a few years ago, when I was trying to get my head round it. It is actually much simpler than you might expect.

Please open a new issue entitled "A Guide to Setting Up a Remote FAS" or something similar.
We can go into detail of getting it working and it will serve well as a guide for others too ;-)

**Comment by bharathkspot** [comment]
sure thanks for the quick reply @bluewavenet , i have already opened the issue https://github.com/openNDS/openNDS/issues/141   and now i renamed the issue as A Guide to Setting Up a Remote FAS
