### ISSUE TITLE
Set Firewallrule on OpenNDS: how ? 

### ISSUE THREAD

**Issue by doremifajb** [openNDS/openNDS#131]
Hello,

I am trying to do a very simple and presumably common thing: 1. I would like to set up guest access to the internet, where they can access to the internet by simply agreeing to the terms of use, and 2. I would like to block the guests from doing something bad to the network.  I managed to do No.1 using openNDS: I set up a VLAN for the guests and a captive portal with the terms of use shows up just for them, the others don't get it. I managed it by looking at https://opennds.readthedocs.io/en/stable/customize.html
using "uci set ...." etc. 

Now, I would like to set up No.2, which seems to be common: to set up so that the guests cannot access the main network, the device, etc. I set on the router (OpenWRT) Firewall rules, but it seems that the chain for the OpenNDS comes automatically on the top of the firewall rules, and it allows guests to do  everything as if they were on a usual network. I figured that I had to configure something inside OpenNDS and looked at the documentation as well as this page: https://github.com/opennds/opennds/blob/master/resources/opennds.conf

and added lines like 
FirewallRuleSet preauthenticated-users {  
FirewallRule block tcp port 22                   
}                                                
FirewallRuleSet authenticated-users {
FirewallRule block to 192.168.0.0/16               
FirewallRule block to 10.0.0.0/8  
}  

directly to /etc/config/opennds, using vi. But then as I tiped "uci commit opennds", it says that these lines are wrong. The other lines look also different, like
list users_to_router 'allow tcp port 443'
	option gatewayiprange '192.168.2.1/24'
	option gatewayinterface 'br-LAN_guest'

I don't know how I'm supposed to enter Firewallrule properly. I looked at "binauth" and "preauth" chapters of the documentation but couldn't figure out if it's relevant to what I need. I would appreciate very much if you could please let me know how/where I'm supposed to write/enter these lines.

**Comment by bluewavenet** [comment]
@doremifajb 
Could you state:
1. what operating system you are running openNDS on 
2. what version of openNDS you are running
3. what router model you are running openNDS on

You seem to be mixing up OpenWrt UCI configuration with generic Linux configuration.

> I set up a VLAN for the guests

Is this vlan to separate two "lan" ethernet ports on the router, or is it to share a single ethernet cable for guest and non-guest access points? Either way, the two networks must be separate ip subnets.

> I would like to block the guests from doing something bad to the network

Could you be more specific with the requirement?

**Comment by doremifajb** [comment]
Thank you very much for the reply! 
1. I have Fritzbox 4020 with OpenWRT 19.07.7. My PC is Mac OS 10.12.6, I'm using Terminal. 
2. OpenNDS is 5.2.0-1. 
3.  Fritzbox 4020. 

As for VLANs, for now I just have one VLAN/Port, only so that I can check if the things are working more easily.  I have three interfaces (as in OpenWRT->Network->Interfaces), with IP Ranges xxx.yyy.1.1, xxx.yyy.2.1 and xxx.yyy.3.1. The each of three VLANs belong to each of them, and I want Captive portal for xxx.yyy.2.1: I managed to set it up successfully, using the guidance in customize.html. 

Once I manage to set the firewall rules for VLANs properly, I plan to make a trunk port and send it to the APs and associate three SSID with them: one admin, one guest-1 with captive protal, one guest-2 without. 

Yes I don't know much about the difference between OpenWrt UCI configuration with generic Linux configuration, I only know that OpenWRT doesn't know all the commands: it knows ls,  cd, mv, vi etc,  but it didn't know ftp. 

I don't want that  guest-1 has an access to UI of the router or SSH to it, and any other hosts. I suppose it will be taken care of by blocking access to  192.168.0.0/16 and 10.0.0.0/8, as suggested in openndf.conf. If there is anything appropriate/desired which I am not aware of, I would do that, too. Right now I can be on guest-1 net and can do ssh to the router, (even before I click "I agree" to the terms of use) and access the UI of the OpenWRT. (Of course password is asked)

Client isolation within guests-1 will be taken care of by Unifi-controller, so is among guests-2 (though I set them differently because of captive portal)  
For guests-2 I can set the traffic rules on Firewall directly on OpenWRT because it has nothing to do with OpenNDS, but for guest-1, it seems like I have to do that inside OpenNDS. Is that right ? 

Then I didn't know how to enter FirewallRuleSet etc properly, and where, if not /etc/config/opennds. I'm pretty confused as to why "uci show opennds" gives a bunch of lines looking like opennds.@opennds[0]... , where as when I do "more opennds" or "vi opennds", lines like "option..... "list....." are there. I looked at 
https://github.com/openNDS/openNDS/issues/7
and it looked like the lines like FirewallRuleSet authenticated-users { are just typed on the config file so I edited the file (using vi), but seems it was wrong.... 

I appreciate your help very much !

**Comment by bluewavenet** [comment]
@doremifajb 
You have a few problems here ;-)

I think you are making this over complex, at least initially.

But first some fundamentals:
1.  OpenWrt comes in its default form as a stripped down Linux distribution designed for running on devices that more often than not have very restricted resources (compared to a Linux desktop or server). Only the bare minimum of packages are pre-installed. Everything else has to be installed as needed (using the opkg utility or the Luci webUI). You need to do some serious self teaching/tinkering to get up to speed...
2. UCI is the Unified Configuration Utility and it is used for managing the configuration of (almost all) packages. It can manage package configurations without needing an editor, from the command line and from within script files. You can use an editor (eg vi) to change configs, but this is not necessary. Packages that also have "generic" linux versions will also have some sort of config file. For example openNDS on OpenSuse or Debian has /etc/opennds/opennds.conf with a unique format of its own. On OpenWrt however, openNDS uses /etc/config/opennds as its UCI format config file. The /etc/opennds/opennds.conf does not exist or is ignored if it does.

Consider VLANs as a way of providing infrastructure, and for the moment ignore them and get the basic captive portal functionality working. For this there are numerous options.

Firstly though, can you confirm:
 * You want to have 3 SSIDs, admin, guest1 and guest2 corresponding to three LAN interfaces
 * You want admin, guest1 and guest2 interfaces to each have their own unique ip subnet.
 * You want guest1 to have the captive portal login and also have no access to the router.
 * You want guest2 to have no access to the router, but have no restriction on Internet access.
 * Admin can do anything.

**Comment by doremifajb** [comment]
Thank you very much for your reply and your instructions ! So basically I should stick with using UCI, and I shouldn't edit opennds using vi, because it's not formatted to be modified that way. 

And yes to 5 points you wanted me to confirm. And the captive portal is working as I want in the sense that  it shows up for guest1, namely  xxx.yyy.2.1, and doesn't for admin and guest2. 

In addition, I want that guests1 and guests 2 have no access to the other networks, can't even ping whatever is connected.

**Comment by bluewavenet** [comment]
@doremifajb 
You can use an editor if you wish but you must comply with the "unified" standard format of uci config files and not use the format that particular package might use if it was to be running under generic Linux and not Openwrt.

**Comment by bluewavenet** [comment]
@doremifajb 
Putting aside vlans and openNDS for the moment. one way of starting is to set up the router with the 3 ip subnets, each on its own ethernet port, all routing with nat to the wan port. You can then create 3 virtual wireless interfaces and bridge one to each ethernet port.
This will serve as an exercise to get you up to speed in configuring OpenWrt.
Hint - you will use the OpenWrt switch configuration to separate the ethernet lan ports. 
Once this is working correctly, _**and only then**_, you can move on to firewall settings and binding openNDS to one of the bridge interfaces.

**Comment by doremifajb** [comment]
Thanks a lot for the quick reply ! 
I have never heard of Virtual "wireless" interfaces, and I'm  not sure if Unifi controller understands it.... it understands VLAN and one can assign SSID to a VLAN over web-interface on AP. 
Or, does the story with VLAN come in after I create virtual wireless interfaces ?  

 So far I created three interfaces with three separate IP ranges, three VLAN for three interfaces, and three LAN-ports, each got each one of VLAN. 
Captive portal is activated for LAN-2 Port (Guest-2), namely xxx.yyy.2.1/24 range. So far is working, in the sense that "the terms of use" shows up only when I'm connected to LAN-2 Port.  Should I redo the whole thing using virtual wireless interfaces ?

**Comment by bluewavenet** [comment]
@doremifajb 
Typically you will start with the actual wireless interface as wlan0 for example. you can give this an ssid eg "mywifi1"
You can then create a virtual wireless interface wlan0-1 and give it ssdi "mywifi2".

These wireless interfaces can then be bridged to to local area networks eg
LAN1 (with an ip subnet of its own) <bridging ethernet lan port 1 to wlan0>
LAN2 (with an ip subnet of its own) <bridging ethernet lan port 2 to wlan0-1>
etc
Perhaps you have done this already...
How are you connecting to the captive portal network? WiFi or ethernet?

**Comment by doremifajb** [comment]
Thank you for your reply ! I just barely started with Virtual WLAN according to your hints.... I still don't find any Tab where you can create a virtual wireless interface.... I just created an interface "WLAN_normal" with the admin IP range and linked with the interface "radio0network1". But in the tab of the switch, all what I see is VLAN and I don't see how I can connect this interface with a LAN port without using VLAN....  


Otherwise,  I am connecting with captive portal via ethernet for now: actually I do more or less everything with ethernet because I don't plan on using Wifi on this router directly: it's usually off.   But before I set the openNDS for the guests1 only, it did work on all the networks over ethernet, and also for wifi on the router itself (it just has one SSID associated with admin network.) 

I thought what I plan to do is not so far from "normal": most people want home-network and just one guest-network, so two VLANs, one with captive portal one without, I want just three, instead of two. I don't really understand why OpenNDS is not set up to do it easily.... perhaps I should stick with the captive Portal from Unifi and buy a raspberry pi to keep the controller running.... (it's a requirement for a captive portal of Unifi)

**Comment by bluewavenet** [comment]
@doremifajb 
What you plan to do is very common indeed and is **VERY** easy to do.
Your problem is you are totally overthinking this with vlans and seem to have little or no knowledge of how routers work.
You at first said you were editing config files, but now you are mentioning "I still don't find any Tab where you can create a virtual wireless interface" so presumably you are using the Luci web UI.

I have been trying to get you to go back to basics in the first instance but you do not want to listen.

Sure, you can use soft vlans to trunk feed to multiple access points on separate ip subnets using a single ethernet cable - but move on to that later if you feel the need.

Your Fritzbox 4020 has a four port switch - ie 4 ethernet lan ports. 
Configure one of these as default gateway for the guest1 subnet.
Configure another one as the default gateway for the guest2 subnet.
Configure  the remaining two as the default gateway for the admin subnet.
Route all three subnets, using NAT to the WAN port.
Bind openNDS to the interface you have set up for the guest1 subnet.

Finally, if you want to use the local wireless, bridge it to one and one only of the ethernet subnets.
If you want local wireless access to all three subnets you will have to create two new "virtual" wireless networks and bridge appropriately.

Creating virtual wireless interfaces in any Linux distro is fairly straightforward, but in OpenWrt provision is specifically provided to make it VERY easy.

**Comment by doremifajb** [comment]
Sorry, if you say it's easy, I will believe you and will give it a try. Especially if you say that I am going to need it later anyway. 
When I changed something on OpenNDS, I use command lines because there seems to be nothing else (other than the installation itself, which I did over OpenWRT LuciUI), and concrete instructions were given on-line so far, but I have never done anything on OpenWRT itself outside of UI.

**Comment by SohailAsghar236** [comment]
Hi. I have installed the openNDS service on my OpenWRT router and I have created a splash.html page on a virtual Ubuntu server machine to act as a FAS server. Now I have added the IP of this VM in config file for openNDS and tried to connect to internet on this router but I get internet without any blockage. I need a kind of guide on how to set it up. Can you please help me with @bluewavenet ?

**Comment by bluewavenet** [comment]
@SohailAsghar236 
Your problem is totally unrelated to this thread.
Please open your own issue...
