### ISSUE TITLE
Opennds restart without loosing active clients sessions

### ISSUE THREAD

**Issue by xes** [openNDS/openNDS#132]
How is possible to restart the service without loosing all active clients?
Is it possible to save all the active sessions and restore them at start (tokens.. upload/download data) ?

**Comment by bluewavenet** [comment]
@xes 
This is not supported as it would necessitate using local non volatile storage for dynamic data. As the target hardware for openNDS is normally router class devices with nor/nand etc storage, this would cause rapid wear to the storage chips so is not a built in function.

It can be done using a custom FAS with remote storage or even local usb/ssd type storage, but this would be up to the individual project to develop.
