### ISSUE TITLE
Difference between Splash-Page and Landing-Page

### ISSUE THREAD

**Issue by tobiaskastl** [openNDS/openNDS#134]
Hello!

What is the main-difference between a splash-page and a landing-page? Is there an exact definition of both?

**Comment by bluewavenet** [comment]
@tobiaskastl 
The term "Splash Page" is an artefact originating from the very early days of wireless "WiFi", where a user trying to browse to a web page would instead see the unexpected "surprise" result of a page of information about the network the user was trying to use. **The surprise page was "Splashed" to the user** when attempting to view any web page (https did not exist back then).
  
Time moved on - technology evolved - and now CPD on the client device checks for a captive portal and if detected it enables display of the portal dialogue without the user having to open a browser first.

Typically a client will now see:
1. A **Login** page
2. A **Welcome** page with information/advertising
3. A **Landing** page with further information - _but this may or may not be seen_ as the CPD will often, depending on implementation, deliberately close.

If the word "splash" is to be used these days, it should more properly be seen in the phrase "portal splash page sequence".

I hope this answers your question ;-)

**Comment by tobiaskastl** [comment]
Awesome, thanks!
