### ISSUE TITLE
Old openNDS-surface

### ISSUE THREAD

**Issue by tobiaskastl** [openNDS/openNDS#135]
Hello!

I would like to compare the "old" (basic) surface of the openNDS-captive-portal with my updated one, but I haven't saved any screenshots of it before I had adapted it - and I would rather like to keep my current version.

I haven't found any pictures of the running application in the documentation - are there any? If not, is there any possibility to gather some, without implementing the whole project again?

The website is created with the shell-script, isn't it? Does this only work on specific operating systems, or could I also generate the websites on my pc?

Any advice on how to retrieve some pictures of the surface would be great.

**Comment by bluewavenet** [comment]
@tobiaskastl 
I don't remember what you actually did, but did you create a modified version of /usr/lib/opennds/login.sh?

If you did, then save your modified login.sh then temporarily replace it with the version in the unpacked download you used for compiling openNDS.
It will be in the folder forward_authentication_service/PreAuth.
Copy and mark it a executable then connect with a client.

Similarly if you used one of the php examples....
Let me know how it works.

**Comment by tobiaskastl** [comment]
@bluewavenet I guess this is the way, thanks!

> Similarly if you used one of the php examples....

I don't think I edited a lot in terms of php, I primarily focused on changing the style. 

> Let me know **how** it works.

To be honest, I don't quite understand your demand. Do you mean what I changed in terms to skip that extra page I asked about in #112? Or if I managed to implement bootstrap? 

Or am I completely misinterpreting the meaning of your demand and you just want to make sure that I solved the initial problem (the topic of this thread)? 😅

**Comment by bluewavenet** [comment]
@tobiaskastl 

> demand

Language, language, it's all in language, lol
pmsl :-D

I was hoping you would let me know if you managed to take screen shots of the original login screen.

**Comment by bluewavenet** [comment]
@tobiaskastl 
https://www.dictionary.com/e/acronyms/pmsl/

**Comment by tobiaskastl** [comment]
@bluewavenet Ahh, I see. My bad 😆 

Will inform you asap :-)

**Comment by tobiaskastl** [comment]
@bluewavenet Hm, I think I made a mistake somewhere. When I connect to my AP, the CPD activates, but no splash-page is shown (just white-screen).

**Comment by tobiaskastl** [comment]
Changing it back to my newer login.sh makes it work again - uh..

**Comment by tobiaskastl** [comment]
Picture 1 shows the error I get when I have the "old" login.sh -> login.sh: 67: Bad substitution

When I compare the files (the old one and the working one) and I focus on line 67, you can see, that there is literally no difference (left side is "old" one, right side is working one)

Any idea? @bluewavenet 

![not_working1](https://user-images.githubusercontent.com/72079975/112903729-3622e100-90e8-11eb-9984-61ee4b820dce.png)
![not_working2](https://user-images.githubusercontent.com/72079975/112903740-38853b00-90e8-11eb-99d1-981a6cee5fe2.png)

**Comment by bluewavenet** [comment]
@tobiaskastl 
Ah yes! I forgot you are running on Raspbian.
Change the very first line from:
`#!/bin/sh`
to
`#!/bin/bash`

This is explained in the comments of the first few lines. As you are just copying the file, you have to make the change manually. The "make install" part of compiling/installing normally does this for you.

It is a shame you did not compare the entire two files ;-)

**Comment by tobiaskastl** [comment]
@bluewavenet It worked, thanks! Had to change the following things:

- load the old login.sh & rename / save my updated one
- change `#!/bin/sh` to `#!/bin/bash` in that file
- load the old splash.css & rename / save my updated one
- change the `login_option_enabled` from mine (3) to any other one (1) in `opennds.conf`

And I guess that's it, thanks! To be honest, I thought until this moment that the line `#!/bin/sh` or `#!/bin/bash` are just some random comments, so I ignored them ^^ Thanks for your help & time!

**Comment by bluewavenet** [comment]
@tobiaskastl 
https://en.wikipedia.org/wiki/Shebang_(Unix)
