### ISSUE TITLE
login.sh name_email_login relaunch

### ISSUE THREAD

**Issue by laoshaw** [openNDS/openNDS#138]
if username and/or emailaddress are blank, the initial page will be re-served. I assume it's login_from() the function.

who is recalling login_form() again and again assuming I intentionally leave username blank? the only caller of login_form is name_email_login, so I assume someone is recalling name_email_login, which is login.sh, I could not find anywhere how the logic works, i.e. for a failed login_form submit, how is it re-serving the initial page(i.e. login_form)?

I want to add a limit of attempts and unsure how to achieve that as I could not figure out how the flow works.

**Comment by bluewavenet** [comment]
@laoshaw 
name_email_login() is doing the check and recalling login_form()

You will have to check and increment a counter in name_email() and pass it in the login_form() as a hidden field, calling it "retry_count" for example.
Add this this new retry_count variable to fasvarlist so it gets retrieved on each reentry by parse_variables()

**Comment by bluewavenet** [comment]
@laoshaw 
Ask here if you need any more hints on this issue.
