### ISSUE TITLE
Is it possible append additional variables to BinAuth?

### ISSUE THREAD

**Issue by aleatorio12** [openNDS/openNDS#14]
Hello,

Reading the docs I understand additional variables can't passed back more than than username and password. When I send an addional variable to NDS/openNDS to authenticated from FAS Remote Server it can't be used in BinAuth. 

Let's say 'user_id' is a GET parameter returned from FAS Remote Server. Logging all parameters, I can't see it anywhere but when a parameter called 'username' or 'password' is passed, this is shown in the log.

Thanks for the helpful.

**Comment by bluewavenet** [comment]
@aleatorio12 
Can you explain in more detail what you are trying to do?

Generally a FAS would do its own logging, thus leaving "username" and "password" as unused variables from the viewpoint of BinAuth. This means a FAS could make use of these variables and embed any information you like into them.

**Comment by aleatorio12** [comment]
Hi @bluewavenet! What a great job you are doing with NDS/OpenNDS.

On the server that uses the FAS, there is a backend that is in charge of performing the authentication. Internally, a token (different from the one provided by NDS) is used, which is subsequently sent to NDS to be transferred to BinAuth.

After this, it is sent back to the server to obtain the timeout dynamically. The NDS internal log is used for informational purposes only, not for storing sensitive information.

In the HTML file (like splash) there is a field called 'token_id' which is sent as hidden to NDS along with the 'redir' and 'tok' fields after successful authentication.

Seeing the arguments that are sent to the BinAuth script from NDS there is no such argument. I did this by redirecting the output of `$*` and `$#` in bash to the log file in /tmp/binauth.log. Only the MAC address, redirection, IP, username, password among others are the parameters that are shown but not 'token_id'

I currently use the 'password' field to send this data, but would it be possible to add more custom fields for sending useful information to BinAuth beyond just 2 fields ('username' and 'password') or use custom names for these fields?

Thank U!

**Comment by bluewavenet** [comment]
@aleatorio12 
The short answer is YES.
This is already scheduled for the next release.
I will be in the form of a single custom field of maximum length 256 bytes.
It will be sent from FAS in the final  opennds_auth form as:
`<input type=\"hidden\" name=\"custom\" value=\"$custom\">`

You will be able to embed numerous sub fields in this, up to the maximum of 256 bytes, being truncated thereafter.

What operating system and hardware are you using? Some testing would be useful ;-)

**Comment by aleatorio12** [comment]
@bluewavenet 

What good news. I will be on the lookout for the next release. It would be useful to send information from the FAS to OpenNDS, beyond the username and password.

I currently use a server with Debian 10.x 64 bit with 1GB of RAM :) If I can help, I will gladly do it

A little off topic, documentation is helpful but sometimes needs a little more information

**Comment by bluewavenet** [comment]
@aleatorio12 
This is now implemented in v5.1.0beta, with a new release coming as soon as I update the documentation! :-D

**Comment by bluewavenet** [comment]
@aleatorio12 
Version 5.1.0 is now released.
https://github.com/openNDS/openNDS/releases/tag/v5.1.0
