### ISSUE TITLE
add user-email or username into ndsctl json

### ISSUE THREAD

**Issue by laoshaw** [openNDS/openNDS#140]
how to pass information from login.sh, in this case username, and/or user-email into `ndsctl json` output, this way I can have client's IP, MAC, Interface, etc along with its possible username/email at one place instead of search ndslog.

**Comment by bluewavenet** [comment]
@laoshaw 
openNDS does not know or care about client login details, it is only concerned that FAS (or PreAuth) has verified the client and requested authentication to allow Internet access.

Client verification details could somehow be obtained by openNDS (eg by parsing the log files!) and be passed to the json client output - but this would be specific to a particular login type (in this case one of the default modes).

The 

> client's IP, MAC, Interface, etc along with its possible username/email

 are all available in one place - **the log file!**

Searching the log file is very easy (Hint: grep, awk).

**Comment by laoshaw** [comment]
ok then. Thanks for the quick reply.
