### ISSUE TITLE
Need some input about what are the arguments OpenNDS will accepts from the webserver or the captive portal login...

### ISSUE THREAD

**Issue by bharathkspot** [openNDS/openNDS#142]
As i mentioned we are trying to replace the default fasremotefqdn and fasremoteip and faspath to redirect the splash page and get the required input for openNDS to authenticate and serve internet.

can anyone help me to understnd the format of input which openNDS will accept/understand from the hotspot login page or cutomsplash pages.

since i have some rough idea by lookig at the debug msgs understood that openNDS will expect MAC, IP, client token....etc but i want to know what  kind of format/protocol/packets its expecting.

any suggestion will be accepted and appreciated highly.

thank you  in advance.....

**Comment by bluewavenet** [comment]
see #141

**Comment by bharathkspot** [comment]
thank you very much for quick reply i ll go through it and let u know

**Comment by dpbatman24** [comment]
Just wanted to have a glimse about how the opennds works using external FAS server.
By referring  the link **https://opennds.readthedocs.io/en/stable/fas.html**
Have configured the opennds:
root@OpenAp-40026c:/# uci show opennds
opennds.@opennds[0]=opennds
opennds.@opennds[0].enabled='1'
opennds.@opennds[0].fwhook_enabled='1'
opennds.@opennds[0].login_option_enabled='0'
opennds.@opennds[0].use_outdated_mhd='1'
opennds.@opennds[0].unescape_callback_enabled='0'
opennds.@opennds[0].webroot='/etc/opennds/htdocs'
opennds.@opennds[0].statuspage='status.html'
opennds.@opennds[0].splashpage='splash_sitewide.html'
opennds.@opennds[0].binauth='/usr/lib/opennds/binauth_sitewide.sh'
opennds.@opennds[0].gatewayinterface='br-lan'
opennds.@opennds[0].gatewayname='OpenWrt openNDS'
opennds.@opennds[0].maxclients='250'
opennds.@opennds[0].sessiontimeout='1200'
opennds.@opennds[0].uploadrate='0'
opennds.@opennds[0].downloadrate='0'
opennds.@opennds[0].ratecheckwindow='2'
opennds.@opennds[0].uploadquota='4096'
opennds.@opennds[0].downloadquota='4096'
**opennds.@opennds[0].fasport='80'
opennds.@opennds[0].fasremotefqdn='blue-wave.net'
opennds.@opennds[0].fasremoteip='46.32.240.41'
opennds.@opennds[0].faspath='/nds/fas-hid.php'
opennds.@opennds[0].faskey='1234567890'
opennds.@opennds[0].fas_secure_enabled='1'**
opennds.@opennds[0].authenticated_users='allow all'
opennds.@opennds[0].users_to_router='allow tcp port 53' 'allow udp port 53' 'allow udp port 67' 'allow tcp port 22' 'allow tcp port 23' 'allow tcp port 80' 'allow tcp port 443'
I am able to redirect to splash page. But the client is not getting internet.
Please can you help, what exactly is missing ??

![Screenshot from 2021-04-08 10-58-36](https://user-images.githubusercontent.com/77356294/113973542-1e6ef980-985a-11eb-9b43-495d0c5a4bd4.png)
![Screenshot from 2021-04-08 10-58-48](https://user-images.githubusercontent.com/77356294/113973551-20d15380-985a-11eb-9c97-952ff38e2995.png)
![Screenshot from 2021-04-08 10-58-52](https://user-images.githubusercontent.com/77356294/113973556-22028080-985a-11eb-89d3-63e0c98092be.png)
