### ISSUE TITLE
FAS Question.

### ISSUE THREAD

**Issue by Ethan-Yami** [openNDS/openNDS#146]
Dear Rob White,

   Sorry to bother you. I have a question to ask you, I'm confused that a Router use FAS to authtication. but what if a FAS application has more servers (IPs or CDN) and one FQDN(One domain name) , How do I set up the fasremotefqdn and fasremoteip?
  Could you please tell me.
  Many thanks.

**Comment by bluewavenet** [comment]
@Ethan-Yami 
The openNDS options "fasremoteip" and "fasremotefqdn" are intended for use in supporting a remote FAS hosted on the very common "shared hosting" service as supplied by most hosting companies for SME business web sites.

Large corporate web sites are usually hosted very differently eg Facebook, Google etc. In this case a single FQDN can have very many IP addresses, all of which link to, usually, a distributed database with load balancing, cacheing and proxying technologies playing a significant role.

Currently openNDS does not directly support this type of hosting. It could do so fairly easily by dynamically resolving IP addresses from the FQDN at each client connection. Much of the firewall code that would be required to enable this is already in place for the openNDS Walled Garden functionality. But as CDN use is a very small use case compared with all the other possibilities, it is quite far down in the list of development priorities at least for now ;-)

The loading on a FAS server is very low, so using CDN does not give any useful advantage in most cases.
In addition, it is usually very difficult to justify the additional cost.

Having said all this, it is actually on the unpublished project TODO list..... no timescale however.

**Comment by Ethan-Yami** [comment]
@bluewavenet 
Hi Rob White, I think we have fixed this issues already. Because there's a Walled Garden function to help, we can set up a FQDN into it. there's one thing We only need to do that it's very simple. we can have this opion "fasremoteip" to two more IP addresses. That's all. 

By the way,In my case(I think there're lot of common cases), Front-end page (UI) which include javascript,html,css will publish onto a CDN node(at most have two or three servers ip that's all) or two more servers.  Backend system application will provide REST API endpoiont to serve Front-end page.

 So,this option "fasremoteip" function has done already, In my opinions ,we can use a "," comma or ";" semicolon to sperate two more IP addresses.  and then we can reuse the function to serve two more servers.


  How about that?

Any idea please let know, Thanks

 Ethan

**Comment by Ethan-Yami** [comment]
And I remember Ubiquity network Unifi Controller has the same feature using two more input  boxes to support more static IP addresses, But Unifi Controller  does not have the Walled Garden function.

**Comment by bluewavenet** [comment]
@Ethan-Yami 
openNDS clients access a remote FAS using fasremotefqdn if it is set. fasremoteip is added to an internal walled garden.

This means that if you add fasremotefqdn to the actual configurable Walled Garden list, then fasremoteip effectively becomes redundant (you still have to set it to a valid ip though).

Now, clients will resolve one of the FAS's CDN ip addresses, allocated in a DNS round robin fashion. This is how, externally, a CDN is accessed.

There may be a few edge cases that pop up but essentially this should work. 
I have not been able to test this as a CDN just for testing is far too expensive at least where I am located!

Adding this functionality as a standard config option is what is on the project TODO list I mentioned.

> Front-end page (UI) which include javascript,html,css

**This is likely problematic** as clients trigger the portal using their built in CPD. The defacto standard for mobile CPD is, for security reasons, to prohibit downloading linked files (eg javascript, css) and to prohibit execution of anything more than basic html5 javascript.

A captive portal is in many ways indistinguishable from a "man in the middle" attack, so a device CPD will protect the device in this way. If you are testing on a desktop system with the Os CPD disabled, you might not notice this, so be aware.

**Comment by Ethan-Yami** [comment]
@bluewavenet

 OK, I got it.

 And thank you for your reminding me of the CPD issue. I will set the "faspath" as a directory of the CND node(Apache| Nginx web server), such as "/portal/guest/" | "/portal/initial" then put a "index.html" file in it. I ganna test it .


Thanks for your answering my questions

Ethan

**Comment by bluewavenet** [comment]
@Ethan-Yami 
Let me know if your tests work!
