### ISSUE TITLE
Captive portal (CPD) on a Firewalla box?

### ISSUE THREAD

**Issue by kalilearner** [openNDS/openNDS#147]
I've seen your thorough guidance, grateful if you could please guide.

I am looking for a way for OpenNDS to provide user authentication in Firewalla box (https://firewalla.com). Considering its a firewalla with one interface, how do I make it work? So there's one Router, an ISP provided device providing IP Addresses and Internet facility. Firewalla is a device configured on one of the router ports.

**Comment by bluewavenet** [comment]
@kalilearner 
I know nothing about Firewalla other than what is on their web site.
openNDS requires to be run on a router, running a compatible form of Linux. If that Linux is not OpenWrt, then the router needs the resources to compile openNDS in place.
Please see:
https://opennds.readthedocs.io/en/stable/install.html

> Considering its a firewalla with one interface, how do I make it work?

Given that the Firewalla is running a proprietary firmware/operating system and it has a single interface, the simple answer is NO, it cannot work.
