### ISSUE TITLE
Using OpenNDS to use captive portal without internet to redirect to a php file in my apache server.

### ISSUE THREAD

**Issue by thelonelyextrovert** [openNDS/openNDS#15]
I am very new to raspberry pi and captive portals. OpenNDS doesn't seem to work offline and I have set fasport to 8000 and my apache is also on port 8000. What changes do I have to make to the config file? I ran openNDS on my rpi3 by typing "sudo opennds", is this right? Sorry if the question seems dumb

**Comment by bluewavenet** [comment]
@thelonelyextrovert 
Captive portals (CPs) are triggered by the client. The client detects the portal using its captive portal detection function (CPD). CPD relies on a functioning DNS to work. If the CP is offline, CPD will not trigger the CP. This is expected and normal.

> I ran openNDS on my rpi3 by typing "sudo opennds, is this right?"

Not really, bur it will work. OpenNDS is designed to be run as a service and not as an application. Can I assume you are running Raspbian? The Rpi does not make a very good router, and OpenNDS is a service to dynamically control the firewall on a router, so perhaps not a very good choice for a production system, but fine for R&D I guess. 

Can you share some details of what you are trying to achieve?

**Comment by bluewavenet** [comment]
Closing for now. Please comment here if you have any questions on this issue.
