### ISSUE TITLE
Office365 users

### ISSUE THREAD

**Issue by Kolenmi** [openNDS/openNDS#152]
Hello, can we use OpеnNDS for Office365 users in WiFi Business Network? 
The idea is to use the page [https://login.microsoftonline.com](url)
With this way, We would avoid using the Radius authorization server.
Best regards

**Comment by sicelo** [comment]
Yes, you potentially can. However, you will need to develop the FAS side on your own, and interact with the Microsoft cloud via any login/SSO APIs they have for this purpose.

In effect, openNDS is the thing your users connect to and ask to be authenticated, but it only authenticates your users when given an instruction to do so by 'something' else ... in this case, by your FAS application, which will in turn interact with Microsoft APIs to get that 'approval' :-)

**Comment by Kolenmi** [comment]
Thank you for your prompt response.
