### ISSUE TITLE
Can I view the captive portal in software only?

### ISSUE THREAD

**Issue by KazuyaIshihara** [openNDS/openNDS#16]
I'm trying to create a CaptivePortal using Squid or Nginx and OpenNDS.
Is this kind of configuration possible? How should I set up OpenNDS, if possible?

`[WiFi Router(already setup proxy settings)] -> [Proxy Server (Squid or nginx) + OpenNDS Server] -> [Outside Network] `

Best regards.

**Comment by aleatorio12** [comment]
Hello!

What exactly is what you want to do?
OpenNDS has built in a web server. Do you want a more complex solution? What is the proxy's purpose?

**Comment by bluewavenet** [comment]
@KazuyaIshihara 

> Can I view the captive portal in software only?

Do you mean you want to run everything on a single device? If so then yes.

However the use of a proxy will defeat the CPD trigger of any captive portal splash page.
In addition it is not possible to sensibly proxy https traffic - the bulk of web site traffic these days. These two points will make any use of a proxy quite useless in most situations.

As @aleatorio12 says, openNDS has its own built in web server. But it can also be configured to use any other web server you choose, particularly useful if you want to write in a high level scripting language such as PHP, Python etc.

**Comment by KazuyaIshihara** [comment]
I used a Wifi router (OpenWRT or Raspberry Pi + WiFi adapter) to successfully display the Captive Portal on a smartphone using this access point.

However, my goal is to have the installed access point display the CaptivePortal with some configuration (e.g. proxy, VPN, DNS, routing, etc.) without installing OpenNDS.

As you say, I set up a proxy server and tried it, but I couldn't display OpenNDS.

Is it possible to set this up?

**Comment by KazuyaIshihara** [comment]
> However, my goal is to have the access point display the CaptivePortal with some configuration (e.g. proxy, VPN, DNS, routing, etc.) without installing OpenNDS.

It means to install OpenNDS on the server that is the destination of the configuration value.
I'm sorry I'm not good at English.

**Comment by aleatorio12** [comment]
Do you want your users to have the settings automatically, ej. Proxy or VPN?

As I see, you want that your Main Router redirects the traffic from your users to a VPN or Proxy after successfull registration. If you want to redirect the traffic to a VPN, I think you can use the OpenNDS Server with some other stuffs like VPN. You can do a bridge connection between OpenNDS and the VPN network and after the users are succesffully registred, their traffic will be redirect to the VPN.

Not problem for your English, same here!

**Comment by bluewavenet** [comment]
Oops - closed accidentally!
@KazuyaIshihara 
Have you made any progress

**Comment by KazuyaIshihara** [comment]
Thank you.
I have a question for you because there is a behavior that I tried many times and could not do.

1. When a user connected to the access point opens the Https page with a smart phone or other device Can I view the captive portal page?

As shown in the video, I am able to view it when the device connects to wifi and after de-authenticating it.
https://streamable.com/e8o2mo
https://streamable.com/j2fwx6

2.  Can I view the captive portal as shown in the configuration diagram?
https://imgur.com/laEqnNT

Best regards.

**Comment by bluewavenet** [comment]
@KazuyaIshihara 
It would be better if you could post the files here.

> When a user connected to the access point opens the Https page with a smart phone or other device Can I view the captive portal page?

The portal page (your FAS server's login page) should always be accessible. If an authenticated client goes back to the portal page and "logs in" again, they will just get the status message "You are already logged in".
![laEqnNT](https://user-images.githubusercontent.com/13632068/84741258-b7b8e080-afa6-11ea-9d43-8b03d79bb848.png)

> Can I view the captive portal as shown in the configuration diagram?

No. OpenNDS MUST be on the wifi router as it has to capture attempted port 80 access by every client CPD as the device connects..

**Comment by bluewavenet** [comment]
@KazuyaIshihara 
I assume your second video shows a **DEAUTHENTICATED** client accessing the remote FAS login page _**directly.**_
Attempting to log in here will fail.
For a successful login, the FAS login page **_must_** be triggered by the client CPD.

**Comment by KazuyaIshihara** [comment]
The second video doesn't directly access my FAS page. I guess CPD was triggered when I pressed the browser’s "reload" button.
The tab opening in Chrome that is showing an error is a wikipedia page with https.
Do you know if CPD is triggered when you press the browser’s “reload” button?
I was able to confirm that it works on Android only.

**Comment by bluewavenet** [comment]
@KazuyaIshihara 

>  Do you know if CPD is triggered when you press the browser’s “reload” button?

No, it is not. CPD is triggered when the client establishes a network connection, or at a re-detect interval. The re-detect interval varies from vendor to vendor. iOS, as far as I am aware never retests. On Android it can vary. Samsung Android seems to be around 10 minutes but I am not sure.
You have to force a CPD re-detect by disconnecting and reconnecting.

For example, duplicate your test to the point you are getting the error on Wikipedia. Then disconnect from the WiFi. Re-connect. CPD should be triggered and pop up the splash page.

**Comment by bluewavenet** [comment]
@KazuyaIshihara 
Post here if you are still having problems. We can re-open the issue if necessary.
