### ISSUE TITLE
Roaming network 

### ISSUE THREAD

**Issue by Ethan-Yami** [openNDS/openNDS#164]
Hello Sir. 
  Sorry to bother you again here.
 
  Right now I have to consult you for roaming netowrk question. If I deploy two more routers with the same Wi-Fi name in a shop . and the verification has been passed by a user in one of these routers. When this user switch to another routers, What will be happened?
  1. This user will be verified again.
  2. This user can continuely use the Internet without a verification.

My question is that if this user switch to another one of the routers,then will be verified again. Do we have a method  to let this user can continuely use the Internet without any interruption?

Could you please give me an advise in your spare time.

 Many thanks.

**Comment by bluewavenet** [comment]
@Ethan-Yami 
If you have multiple venues all using the same remote FAS, with a common user database, it depends on what you program into your FAS.
For example a logged in client moving location could be given a welcome page with a continue instead of having to go through the whole process.
It is entirely up to you to decide what to program into your FAS.

**Comment by Ethan-Yami** [comment]
Yes ,I got your point.
But I think I'm not clear to let you know about this situation. 
For an example here.

 There are more then 10 routers deploey in a LAN with same Wi-Fi SSID in a large mall .

 If I (as a user) passed the verifation at first time , then I don't need to verify or see any interrution at second time or thrid time. Just like mobile network, I can feel nothing.  I don't need to care about I move to a new routers from the old one.

Am I clear sir?

Thank you for your answer.

**Comment by bluewavenet** [comment]
@Ethan-Yami 

> There are more then 10 routers [deployed] in a LAN with same Wi-Fi SSID in a large mall .

Sorry, it is not clear at all...

I will make some guesses based on my personal experience of shopping malls and you **tell me the closest match**:
1. Shopping mall has an Internet feed provided by the mall management or owners
    * The mall is cabled with ethernet to all the individual shops
    * You have installed, or want to install an openNDS  router at each shop
2. Shopping mall has no provided Internet infrastructure
    * The shop has provided its own Internet feed (or you provisioned it for them)
    * You have installed, or want to install an openNDS router at each shop
