### ISSUE TITLE
Ability to authenticate client before it's appeared in the "client list"

### ISSUE THREAD

**Issue by minhng99** [openNDS/openNDS#167]
Hi, I'm trying to do a captive portal system that has the ability to roam between entirely different AP running separated opennds instance but having some issue while using `ndsctl auth [mac]`
For example, I have a syslog here:
```
## 1. HOSTAPD associated
hu May 27 06:00:51 2021 daemon.info hostapd: wlan1: STA 7c:2a:db:8c:56:e7 IEEE 802.11: authenticated
Thu May 27 06:00:51 2021 daemon.notice hostapd: wlan1: STA-OPMODE-N_SS-CHANGED 7c:2a:db:8c:56:e7 2
Thu May 27 06:00:51 2021 daemon.info hostapd: wlan1: STA 7c:2a:db:8c:56:e7 IEEE 802.11: associated (aid 3)
Thu May 27 06:00:51 2021 daemon.notice hostapd: wlan1: AP-STA-CONNECTED 7c:2a:db:8c:56:e7
Thu May 27 06:00:51 2021 daemon.info hostapd: wlan1: STA 7c:2a:db:8c:56:e7 RADIUS: starting accounting session 7699DE68B96E9D0D

## 2. DHCP request
Thu May 27 06:00:51 2021 daemon.info dnsmasq-dhcp[3054]: DHCPREQUEST(br-lan) 10.15.99.206 7c:2a:db:8c:56:e7
Thu May 27 06:00:51 2021 daemon.info dnsmasq-dhcp[3054]: DHCPNAK(br-lan) 10.15.99.206 7c:2a:db:8c:56:e7 wrong address
Thu May 27 06:00:51 2021 daemon.info dnsmasq-dhcp[3054]: DHCPDISCOVER(br-lan) 7c:2a:db:8c:56:e7
Thu May 27 06:00:51 2021 daemon.info dnsmasq-dhcp[3054]: DHCPOFFER(br-lan) 10.15.99.195 7c:2a:db:8c:56:e7
Thu May 27 06:00:51 2021 daemon.info dnsmasq-dhcp[3054]: DHCPREQUEST(br-lan) 10.15.99.195 7c:2a:db:8c:56:e7
Thu May 27 06:00:51 2021 daemon.info dnsmasq-dhcp[3054]: DHCPACK(br-lan) 10.15.99.195 7c:2a:db:8c:56:e7

## 3. Custom dnsmasq-script being triggered
Thu May 27 06:00:51 2021 user.notice dnsmasq-auto-authenticate: Found client 7c:2a:db:8c:56:e7 is roaming, ndsctl auth....
Thu May 27 06:00:51 2021 user.notice dnsmasq-auto-authenticate: ndsctl: Failed to authenticate client 7c:2a:db:8c:56:e7.

## 4. opennds Add the new client to its client list
Thu May 27 06:00:52 2021 daemon.debug opennds[2290]: access: GET /generate_204
Thu May 27 06:00:52 2021 daemon.debug opennds[2290]: Locking client list
Thu May 27 06:00:52 2021 daemon.debug opennds[2290]: Client list locked
Thu May 27 06:00:52 2021 daemon.notice opennds[2290]: Adding 10.15.99.195 7c:2a:db:8c:56:e7 token fb200408 to client list
Thu May 27 06:00:52 2021 daemon.debug opennds[2290]: Unlocking client list
Thu May 27 06:00:52 2021 daemon.debug opennds[2290]: Client list unlocked
Thu May 27 06:00:52 2021 daemon.debug opennds[2290]: url: /generate_204

```
You can see that I'm using a dnsmasq hook script which will go to check a centralized database to see if this specific MAC address has already authenticated on another AP or not, the database replied that the MAC has authenticated and the script continues to call `ndsctl auth 7c:2a:db:8c:56:e7` but it's failed because the client `7c:2a:db:8c:56:e7` is not in the opennds client list.

I think it would be better to have a way to authenticate a client before it even appears in the list so it will have a smooth roaming experience and doesn't trigger a captive portal pop-up... or a feature which I could add a client manually into the list.

I know about the `trust` feature but I only want to authenticate the client in a temporary manner and still deauth automatically after its `sessiontimeout` has reached.

**Comment by bluewavenet** [comment]
@minhng99 

> a way to authenticate a client before it even appears in the list ...... I know about the trust feature 

I have implemented something similar for a customer. 
I used an extension to authmon using `nsdctl trust` and `ndsctl untrust`
All quotas on the "roamed to" gateway, as well as session timeout were reset to the values first set on initial login, but this could be made more sophisticated.

I have considered making the syntax of `ndsctl trust` the same as `ndsctl auth`. Would this be a time to revisit this?

**Comment by minhng99** [comment]
I think it just needs the `auth` function to add the client MAC into the list if it doesn't exist and then set it to `Authenticated`, I don't think this behavior change would affect anything negatively.

**Comment by bluewavenet** [comment]
@minhng99 
Yes, maybe, I need to think through it a bit more.
Sounds very useful - If it was a modified `ndsctl auth` then a very small change to the level 3 FAS and maybe a small change in authmon would enable transparent roaming ;-)

A new config option "roaming_group" ........

**Comment by bluewavenet** [comment]
@minhng99 
Giving this a little thought:
Max clients and DHCP ip address availability will be concerns with every gateway in the roaming group potentially having to support the total of all the clients connecting to the gateway group.... - easily solved with a large subnet but this would have to be part of the setup, rather than functionality built into openNDS.

**Comment by bluewavenet** [comment]
@minhng99 
New in v9.1.0 (release very soon) is `option allow_preemptive_authentication`
This was required for other situations particularly where IoT type devices are required to have full quota support, **_but I think it is also what you are looking for here._**

`option allow_preemptive_authentication '1'` enables `ndsctl auth [client_mac] [quota_values]`
This will work as long as the client device mac address is in the arp table.
