### ISSUE TITLE
OpenNDS version 9.0.0-1: length of the text

### ISSUE THREAD

**Issue by doremifajb** [openNDS/openNDS#176]
Hello !	
I have  OpenNDS 5.2.0-1 installed on OpenWRT 19.07 on Fritzbox 4020, I use splash.html with my own text for the terms of use, and am completely happy with it. So I wanted to set up the same thing for my Raspberry Pi 4B with OpenWRT 21.02.  I installed OpenNDS, then realized that the version is now 9.0.0-1 and legacy click-and-connect splash.html is no longer supported. 
So I tried to make it as close as possible to my splash.html.  I did the following: 

1. in theme_click-to-continue-basic.sh, in the beginning of # functions:                                                                                  
                                                                                              
```
generate_splash_sequence() {                                                                  
#       click_to_continue                                                                     
thankyou_page                                                                                 
}      
```         

So that one has to click the button "Connect" only once in order to access to the internet. 

2. Inserted my lengthy terms of use under thankyou_page so that it's right there. I used a bunch of <p> etc, so that it would look ok. Commented out read_terms so that the button will not show up. 

The text did show up nicely, but strangely, was cut off at the middle of a sentence ! I was putting small chunks in echo " xxxxxx ", in case echo has a limitation on length. It did cover a great length of the text, but when there a just a few more paragraphs to cover, it got cut out. 

Is there a limitation as to how long the text is supposed to be in this setting ? If so, is there a way to eliminate the limit ? 

I would appreciate your info !!

**Comment by bluewavenet** [comment]
@doremifajb 
A single web page is limited to 10240 bytes and this cannot be changed.

If you are using all this for your terms of service then in practice nobody will read it anyway.

It would be far better to have a very short summary on the thankyou page, then reinstate the ToS button and have multiple pages of your Terms so the Lawyers amongst your clients can spend many happy hours reading it :-D

**Comment by doremifajb** [comment]
Thank you very much for your explanation ! OK, I will separate the terms of use, as you prescribed. Yeah, it's a lengthy thing, one purpose of making it visible right away was to give the users an impression that we are very conscious about legal issues, but, as a matter of fact, well, nobody cares;; 

Now I realized that my signs like '#', p with brackets, are gone from my first post;; (Can't make it appear!)

**Comment by bluewavenet** [comment]
@doremifajb 
FYI - openNDS v9.1.1 is now released.
It has a new option:
`option max_page_size`

This is the solution to your original request.
It is useful to increase this value if larger Themespec pages are required, or decrease this value if a target legacy router is short of ram.

It is still much preferable from a user experience point of view to split up large amounts of text though.

**Comment by doremifajb** [comment]
Wow, thank you so much for letting me know about it ! It's going to make it closer to splash.html, which was easy to use.

**Comment by bluewavenet** [comment]
@doremifajb 
Actually the page size also effected the legacy splash.html even back in the NoDogSplash days.
At least now it can be changed from the default.

**Comment by doremifajb** [comment]
Interesting... I just checked the size of my splash.html, it's 59781 (bits? bytes ? I did `ls -lag`, the size of the original splash is  2479 with this unit), and as I get on the guest-net, the entire text shows up, either in pop-up window or in the browser. I installed OpenNDS in mid-March. 

I haven't got to rewriting opennds on the new router with newer version. I suppose I should type like

`uci set opennds.@opennds[0].max_page_size="the size I need"`

In what kind of format should I give the size ? Just the figure, like, 60000 ?

**Comment by bluewavenet** [comment]
@doremifajb 
Actually you are correct, the legacy splash page size was dynamically calculated! That was a change made way back in NoDogSplash 3.0.x I think. The problem with this was if the router ran out of memory to allocate it was a fatal error. Not a problem with an RPi though!

`uci set opennds.@opennds[0].max_page_size="the size I need"`
Yes

max_page_size is the maximum page size in bytes that the MHD can serve to a client.
In openNDS 9.0.0 it was hard wired as 10kB (kilobytes) ie 10240 Bytes

In v5.0.0 of both openNDS and NoDogSplash it was hardcoded to 4kB (except when serving splash.html)

A page of html to serve will consist of headers + inline-css + body 

In the case of the legacy splash this would have been headers + inline.css +splash.html +template-variables

Linked css (eg splash.css) does not count as the browser requests it separately.

> In what kind of format should I give the size ? Just the figure, like, 60000 ?

Yes

**Comment by doremifajb** [comment]
Thank you for the info and the instruction ! Now I tried to update OpenNDS, but it does not appear in the list of updates. (Luci software) Should I uninstall and install again, or is there another way to update it ?

**Comment by bluewavenet** [comment]
@doremifajb 
Assuming you are still on Rpi on 20.02, then when you tried, the OpenWrt build system had probably not yet got round to that architecture.

Try again now:
```
opkg update
opkg install opennds
```
Alternatively in luci click the Update List button then continue.

**Comment by doremifajb** [comment]
Yeah I'm on Rpi on 21.02. Just to make sure, I did install OpenNDS 9.0.0-1 on it (using luci), and set it up with chopped up terms of use, I wanted to update it to v9.1.1. `opkg install opennds ` sounds like a new install, I worry that the files I edited might disappear after that.... 

I just discovered that my `/usr/lib/opennds` is gone and thus `theme_click-to-continue-basic.sh` is also gone ! It seems these things are not saved when one makes a backup of the whole thing....(I installed OpenWRT on this SD card 100 times, as I attempted to expand the partition size for softwares, in the end I gave it up.)  Sigh. All the more, I'm glad that you made the option max_page_size: I don't have to chop the text up again. Next time I will have to make a disk image of an important backup.

**Comment by doremifajb** [comment]
Now I installed OpenNDS v9.1.1. from scratch, and did

`uci set opennds.@opennds[0].max_page_size='100000'`

Then, the captive portal stopped working: it doesn't show up at all, either automatically or typing the IP address.  I didn't change anything yet on theme_click-to-continue-basic.sh. I removed max_page_size, then it's working again.... 

Perhaps you could support splash.html again ?? Or is there some sort of security issue ? It was really easy and nice, besides, I already have the file.

**Comment by bluewavenet** [comment]
@doremifajb 

> `uci set opennds.@opennds[0].max_page_size='100000'`

That's huge! I would suggest this is very user unfriendly. However it _should_ work.
More of an oversight on my behalf than a bug, but the maximum size possible is currently 64KB.
This will be changed/corrected though.

> Perhaps you could support splash.html again ??

It is supported - in NoDogSplash, however, there is little difference between editing html in splash.html and editing it in the ThemeSpec file (apart from this current issue!).

The legacy templated splash.html was very inflexible but is good for resource restricted IoT devices and legacy routers.

A RPi is not in this class in any way whatsoever, but if legacy splash does what you want then that's fine.

**Comment by doremifajb** [comment]
Thank you for your reply ! Now I changed the value from 100000 to 64000, it's working :) I put 100000 just to be on the safe side, because small differences in format etc might take extra byte. But if my splash.html was 59781 Bytes, 64K should be enough, I think.  

I'm not sure if I want to learn nodogdplash...  For now I'm happy with OpenNDS :) Thank you very much for all your work !

**Comment by doremifajb** [comment]
I'm done with editing theme_click-to-continue-basic.sh. Now, perhaps I should have asked before, the main difficulty comparing with splash.html is that I have to ssh and edit the .sh file with vi with html source code, with `&auml;`for ä etc,  I write resp. paste about 15 lines at a time and check that captive portal page appears correctly (if I make a mistake in syntax, the other page with "portal login" shows up). Is that what everybody else is also doing ? Or is there a cleverer way of doing it ? I first tried to edit .sh file locally and scp'ed to RasPi,  but then I suppose I made a mistake, it didn't work, and was impossible to find out what I did wrong. 
With splash.html I could just write locally, using a html editor, then just scp to the router.

**Comment by bluewavenet** [comment]
@doremifajb 
Some hints:
1. install openssh-sftp-server and use something like Filezilla to transfer files, or mount the Rpi file system on your PC, easy if your PC is running Linux ;-)
2. In the ThemeSpec file you can include separate html files instead of having inline code.

Example of including an html file:

In theme_click-to-continue-basic.sh, you will find function `display_terms()`
The "terms of service" text is split up into sections, eg:
```
	#Privacy
	echo "
		<b style=\"color:red;\">Privacy.</b><br>
		<b>
			By logging in to the system, you grant your permission for this system to store any data you provide for
			the purposes of logging in, along with the networking parameters of your device that the system requires to function.<br>
			All information is stored for your convenience and for the protection of both yourself and us.<br>
			All information collected by this system is stored in a secure manner and is not accessible by third parties.<br>
			In return, we grant you FREE Internet access.
		</b><hr>
	"
```

Replace this with:
```
	#Privacy
        privacy=$(cat "/usr/lib/opennds/privacy.htm")
	echo "$privacy"

```
Finally place your new privacy.htm file at /usr/lib/opennds/ using Filezilla or whatever method you want to use.

**Comment by doremifajb** [comment]
Wow, that's easy enough ! I should have asked before working. But next time I know better :) Thank you so much !

**Comment by bluewavenet** [comment]
@doremifajb 
I'll close this again for now, let me know if you have any more problems with it.
Note: Just to confuse you a little: Version 9.2.0 is released ;-)
It will be in the package feeds in a day or so.
