### ISSUE TITLE
v.9.0.0. what should I suggest the guests if the captive portal doesn't show up right away?

### ISSUE THREAD

**Issue by doremifajb** [openNDS/openNDS#177]
Hello again:) 
I managed to edit theme_click-to-continue-basic.sh in order to have a captive portal with the terms of use as I like, so I tested how it looks like. With Firefox and Safari I had the result as I wanted. But Opera doesn't seem to have a good detect-portal. (Note that I'm connected using LAN, that might be making it a bit worse) Now, with splash.html on v.5, I made a sign for the guests (a piece of paper on the wall) that they should type in 192.168.2.1 if the captive portal does not show up automatically. As long as I tested, it always worked, also with Opera, and I got no complaint, so I think it's been working well with all kind of devices. 

But with v9 on Opera, the following page shows up as I typed 192.168.2.1, or 192.168.2.1:2050
![auth-required](https://user-images.githubusercontent.com/81316206/122106969-da304480-ce1a-11eb-8d86-59fb6208c55b.png)
If I click "Portal Login", then I do get to the captive portal, so it's not bad, but I don't know which file I need in order to edit this page so that I can make "Portal Login" in German. Could you tell me where that is, and what's the name of it ? 

And now I was clicking various things around to see what happens (like refresh, etc), then things like this
![status](https://user-images.githubusercontent.com/81316206/122107213-211e3a00-ce1b-11eb-920b-2e3300f42fbf.png)
or sometimes this: different color as the first one ! 

![auth-required_white](https://user-images.githubusercontent.com/81316206/122109912-2fba2080-ce1e-11eb-982c-7bd3e12a1ba6.png)

shows up. 
I think if I edit the file for the first one and remove "refresh" button, then one cannot get to these two pages, so the matter will be probably settled, but I don't want the page like this "status" to come up when the guests click things around in any way... 
And the easiest would be if I know the address to give them so that the right captive portal just shows up... is there such an address ?  

I appreciate your help!

Another thing to mention is (independent of the above issue), with 
`    Your device originally requested <b>$originurl</b>
                        <br>
                        Click or tap Continue to go to there.
                </p>     
                <form>
                        <input type=\"button\" VALUE=\"Continue\" onClick=\"loca
                </form>`
it looks like I always end up in http://detectportal.firefox.com/success.txt?  whatever page I tried to open first. I don't really need this function, so I simply erased it, but I just wanted to let you know :)

**Comment by bluewavenet** [comment]
@doremifajb 
Accessing the portal ip address directly has always been invalid since the beggining of NoDogSplash. 
_However it did work as you found out_ but this was purely a matter of luck and the result of a bug that in some circumstances could result in a crash.
This was fixed in openNDS and a Client Status page was introduced.

- If the client is not authenticated they get the RFC 6585 Error 511 - Network Authentication Required.
- If the client is authenticated they get their "account" status including data usage, data rates, session end times etc., along with the ability to log out.

The Client Status page should normally be accessed by entering http://status.client in the browser.
This FQDN can be changed via a config option eg http://login.page
`option gatewayfqdn 'login.seite'`

All operating systems (Linux, Windows, macOS, iOS, Android etc.) have captive portal detection (CPD), and all browsers do, (including Opera I am pretty sure). Not all browsers have it switched on by default though. Even the Facebook mobile app has its own CPD.

CPD is a standard, so much so that is is very unusual for it not to be present.

I would recommend that you check the Opera configuration options.

> I always end up in http://detectportal.firefox.com/success.txt

That is because you are using http://status.client or attempting to access the portal ip address directly.

The Client Status page can be edited, but the Error 511 page cannot.

In a future version, it would be possible to include a config option to add alternate language text to the 511 page...
**_Convince me I need to add it ;-D_**

The Status page is generated by the /usr/lib/opennds/client_params.sh script. You will see the html towards the end of the script.

**Comment by doremifajb** [comment]
Thank you very much for your reply ! 
> Accessing the portal ip address directly has always been invalid since the beggining of NoDogSplash.

I didn't know that ;; But I think it's convenient to have an address to access the login-page. When I google "captive portal not showing hotel", there are a lot of people who are having this problem. Those are at least the people who think that there is something wrong with their device. The others just think that Wi-Fi of the hotel is not working. (That was the case as we had a commercial wifi provider for our guesthouse: one of the reasons why I decided to cancel their service.) 

Now, I tried to look at http://status.client. It seems to be linked to the login page of luci. So when I'm on Admin-net, Luci page (under the address http://status.client/cgi-bin/luci/) shows up, and when I'm on guest-net, I get Error 404 - Not Found (because luci-access is blocked by firewall), regardless of whether I'm authenticated or not. 

The page  "Error 511 - Network Authentication Required" shows up if I type 192.168.2.1.  Now I see, if I'm authenticated, and type the same IP address again, then I get the status page. 

Could it be that, status.client is set as an alias to 192.168.1.1, which would then do the job as you described if the interface of OpenNDS  was for this subnet, but since I have a different subnet for the guests, the IP address 192.168.2.1 does the job as you intended for status.client ? In other words, in some configuration file, the interface is still default, and is not automatically synchronized with /etc/config/opennds, where I set the interface to be something else (eth11) ? 
  
I think probably for the same reason, I don't get to see http://login.page     

> In a future version, it would be possible to include a config option to add alternate language text to the 511 page...
> **_Convince me I need to add it ;-D_**

Yeah, that would be nice :) Please ^2 ! 
Till then, I am going to put on the sign that they should access 192.168.2.1 and click on "Portal Login" if the login window doesn't show up.  (But I'm not going to put the new router up so quickly anyway... I want to install a few more things...perhaps your new version comes before I'm done with it.  For now FB4020 with OpenNDS v5 with splash.html is still there:)

**Comment by bluewavenet** [comment]
@doremifajb 

> When I google "captive portal not showing hotel", there are a lot of people who are having this problem

There have been a number of "secure your mobile" apps that force all web access to https on port 443.
These apps are misplaced, it is just vendors taking advantage of the FUD (Fear Uncertainty and Doubt) that hits the headlines frequently. This of course completely breaks the client's built in secure means of detecting if it is online (its CPD).
Then the users subject to the FUD complain the hotel/guesthouse/airport/etc wifi does not work.

There are other reasons for a client to be unable to use a captive portal, usually due to the client user installing some unnecessary security enhancement.

> Now, I tried to look at http://status.client. It seems to be linked to the login page of luci

It is not linked. openNDS by default blocks luci.
If you still want to use luci then it is best to change the port it uses (in the uhttp config)

> Could it be that, status.client is set as an alias to 192.168.1.1 

It is not an alias, it is a DNS entry.
The ip address that the gateway FQDN resolves to should be that of the openNDS gateway.
By default this will be br-lan.
What it is for your system depends very much on your configuration.

From what you say, you seem to have two separate routed subdomains, one for admin (192.168.1.1) and one for guests (192.168.2.1)
**What interfaces are these subnets bound to?**

**If you ping status.client, what ip address does it resolve to?**

Check the /etc/hosts file to make sure the entry for status.client is the openNDS address. It is possible that you have ended up with multiple entries after initial config attempts you may have tried.

> I don't get to see http://login.page

You will only get login.page if you set gatewayfqdn to login.page and then you will not get status.client

> I am going to put on the sign that they should access 192.168.2.1

**Try: onboard-wifi.net or gnome.org** instead of an ip address

**Comment by doremifajb** [comment]
Thank you very much for your explanation ! Now I understood what's going on better.  

status.client was indeed resolved to 192.168.2.1, as it should be: that's the address range of the interface I set OpenNDS on. (Interface: eth11) I was confused that as an association to 192.168.1.1 (br-lan) because it called up luci while I'm on admin-Net, and that's the address I usually use in order to get into luci. But actually, when I'm on admin-net, 192.168.2.1 does also call up luci, too. I had forgotten about it. So status.client indeed had nothing to do with 192.168.1.1. 

Now I tried around more, in the end it was the browsing history and cache of Opera that was screwing all up. I erased it, then now I do get "Network authentication required" page by typing status.client. (even though it still doesn't do auto-detect)  I think it's just my Opera being a bit crazy (recently it suddenly started to refuse to access UI of Fritzbox for no reason, so I had to open Firefox), I'm going to assume that it will work OK for the others. 
So I am going to post "type status.client and click "portal login if the captive portal doesn't show up automatically" on the wall. 

As for fdqn, 
option gatewayfqdn 'login.seite' 
means
uci set opennds.@opennds[0].gatewayfqdn='login.seite'
and if I do it, then in the file /etc/hosts 
192.168.2.1 login.seite
instead of 192.168.2.1 status.client  is going to show up, and then login.seite is going to do the job that status.client used to do. Is it right ? 

And, your suggestion
Try: onboard-wifi.net or gnome.org instead of an ip address
means that I may put these addresses instead of status.client in above procedure if I wanted, right? 

So in principle, giving out a raw/bare IP address is somewhat discouraged ?  

I think login.page looks easy and nice, I'm going to go for it.

**Comment by doremifajb** [comment]
P.s, just tried as I understood it, it seems to be working, I think I understood correctly. However, I hit login.page on Opera (after making sure that my PC has a right IP address), then the page "login.page refused to connect." shows up. I reloaded it a couple of times, the same thing. But, I just let it stay and did something else (outside of the computer) for 2-3 minutes, then the captive portal did show up !! 

I tried with the raw IP address, 192.168.2.1, then the captive portal came right away. So somehow the name resolution seems very slow....

**Comment by bluewavenet** [comment]
@doremifajb 
It is normal for a router to provide DNS services for client devices connecting to it.
A captive portal running on a router will normally block everything external for clients including direct access to external DNS.
A device configured manually with an external DNS, by default, will not be able to use its CPD to pop up a login page.

The only way for such a device to login is to do what you are doing.

**My guess is this is how you have configured your PC.**

My response to people who are afraid of using a local DNS or DNS proxy, should not try to use a network with a captive portal either. This is another example of one those unnecessary "security addons" I mentioned earlier.

**Comment by doremifajb** [comment]
Thank you for the reply ! I looked at my configuration on the laptop, it says DNS server is 192.168.1.1 (or, 2.1, if I'm connected on guest-net), so I don't think I have done anything particular to my laptop. 
But it's good to know that specifying DNS server on the computer causes this kind of problem. Thanks for the info ! (I was almost going to do that on someone else's PC, as her PC was getting "DNS server not responding", while mine on the same network was doing fine. But I just changed DNS server on the router to the one from cisco instead of ISP, then it worked, and got a bit faster.) 

Now I did further experiment: as I mentioned above, I had done
uci set opennds.@opennds[0].gatewayfqdn='login.page'

then /etc/hosts included 192.168.2.1 login.page. 

I realized that, not only on Opera, but also on Firefox, it does not work ! Namely, I don't get to any of these pages for captive portal when I give "login.page". But when I delete this line with gatewayfqdn, then it came back to status.client, and with this address, it works on firefox and opera ! 

So it looks like uci set opennds.@opennds[0].gatewayfqdn='login.page' 

is not completely replacing status.client with login.page as I had thought. Did I misunderstand something ?

**Comment by bluewavenet** [comment]
@doremifajb 
You may well be suffering from browser caching problems.
However it would be useful perhaps to show the outputs of:
```
uci show opennds
uci show network
uci show wireless
uci show dhcp
cat /etc/hosts
```

**Comment by doremifajb** [comment]
here: 
`opennds.@opennds[0].enabled='1'
opennds.@opennds[0].fwhook_enabled='1'
opennds.@opennds[0].maxclients='250'
opennds.@opennds[0].authenticated_users='block to 192.168.0.0/16' 'allow tcp port 53' 'allow udp port 53' 'allow tcp port 22' 'allow tcp port 80' 'allow tcp port 443'
opennds.@opennds[0].users_to_router='allow tcp port 53' 'allow udp port 53' 'allow udp port 67'
opennds.@opennds[0].gatewayinterface='eth0.11'
opennds.@opennds[0].use_outdated_mhd='1'
opennds.@opennds[0].unescape_callback_enabled='0'
opennds.@opennds[0].gatewayname='OpenWrt openNDS'
opennds.@opennds[0].preauthidletimeout='30'
opennds.@opennds[0].authidletimeout='120'
opennds.@opennds[0].checkinterval='60'
opennds.@opennds[0].uploadrate='0'
opennds.@opennds[0].downloadrate='0'
opennds.@opennds[0].ratecheckwindow='2'
opennds.@opennds[0].downloadquota='0'
opennds.@opennds[0].sessiontimeout='5'
opennds.@opennds[0].preauthenticated_users='drop tcp port 22'
opennds.@opennds[0].uploadquota='0'
opennds.@opennds[0].login_option_enabled='1'`

Note that sessiontimeout is set short so that I can test without waiting. 

uci show network:
`network.lan.proto='static'
network.lan.ipaddr='192.168.1.1'
network.lan.netmask='255.255.255.0'
network.lan.ip6assign='60'
network.lan.device='eth0.16'
network.WAN=interface
network.WAN.proto='dhcp'
network.WAN.device='eth0.123'
network.guest=interface
network.guest.proto='static'
network.guest.device='eth0.11'
network.guest.ipaddr='192.168.2.1'
network.guest.netmask='255.255.255.0'
network.students=interface
network.students.proto='static'
network.students.device='eth0.15'
network.students.ipaddr='192.168.3.1'
network.students.netmask='255.255.255.0'
network.lan12admin=interface
network.lan12admin.proto='static'
network.lan12admin.device='eth0.12'
network.lan12admin.ipaddr='192.168.4.1'
network.lan12admin.netmask='255.255.255.0'`

I'm not using wifi for the router (I haven't managed to activate it: it's Raspberry pi and it's complicated) 

uci show dhcp:
`dhcp.wan=dhcp
dhcp.wan.interface='wan'
dhcp.wan.ignore='1'
dhcp.odhcpd=odhcpd
dhcp.odhcpd.maindhcp='0'
dhcp.odhcpd.leasefile='/tmp/hosts/odhcpd'
dhcp.odhcpd.leasetrigger='/usr/sbin/odhcpd-update'
dhcp.odhcpd.loglevel='4'
dhcp.guest=dhcp
dhcp.guest.interface='guest'
dhcp.guest.start='100'
dhcp.guest.limit='150'
dhcp.guest.leasetime='4h'
dhcp.students=dhcp
dhcp.students.interface='students'
dhcp.students.start='100'
dhcp.students.limit='150'
dhcp.students.leasetime='4h'
dhcp.lan12admin=dhcp
dhcp.lan12admin.interface='lan12admin'
dhcp.lan12admin.start='100'
dhcp.lan12admin.limit='150'
dhcp.lan12admin.leasetime='12h'`

`oot@OpenWrt:/etc/config# cat /etc/hosts
127.0.0.1 localhost

::1     localhost ip6-localhost ip6-loopback
ff02::1 ip6-allnodes
ff02::2 ip6-allrouters
192.168.2.1 status.client 
`

Thanks a lot in advance for checking things out !

**Comment by bluewavenet** [comment]
@doremifajb 
I formatted your output.
Hint - use these tools:
![githubpostingtools](https://user-images.githubusercontent.com/13632068/122527987-c3087700-d013-11eb-8db9-961d7e09215f.png)

**Comment by bluewavenet** [comment]
@doremifajb 

> it's Raspberry pi 

No wonder you are having problems. RPi makes a terrible router. A wifi interface with very limited open source driver support and only a single ethernet port.....

**Comment by bluewavenet** [comment]
@doremifajb 
`opennds.@opennds[0].preauthenticated_users='drop tcp port 22'` is invalid.

**Comment by bluewavenet** [comment]
@doremifajb 
`dhcp.odhcpd=odhcpd`

You are not using dnsmasq. This explains a lot.

**Comment by doremifajb** [comment]
Thank you for your comments !

> @doremifajb
> `dhcp.odhcpd=odhcpd`
> 
> You are not using dnsmasq. This explains a lot.

I don' know.... I checked on luci under DHCP and DNS, I don't see anything about dnsmasq. (I do everything with luci unless it has to be with cli) 

 This
`opennds.@opennds[0].preauthenticated_users='drop tcp port 22'`

I think it was there when I installed OpenNDS v9. My uci show opennds from Fritzbox 4020 (OpenNDS v5) is
`opennds.@opennds[0]=opennds
opennds.@opennds[0].enabled='1'
opennds.@opennds[0].fwhook_enabled='1'
opennds.@opennds[0].login_option_enabled='0'
opennds.@opennds[0].use_outdated_mhd='1'
opennds.@opennds[0].unescape_callback_enabled='0'
opennds.@opennds[0].gatewayname='OpenWrt openNDS'
opennds.@opennds[0].maxclients='250'
opennds.@opennds[0].preauthidletimeout='30'
opennds.@opennds[0].checkinterval='60'
opennds.@opennds[0].uploadrate='0'
opennds.@opennds[0].downloadrate='0'
opennds.@opennds[0].ratecheckwindow='2'
opennds.@opennds[0].uploadquota='0'
opennds.@opennds[0].downloadquota='0'
opennds.@opennds[0].users_to_router='allow tcp port 53' 'allow udp port 53' 'allow udp port 67'
opennds.@opennds[0].gatewayinterface='br-LAN_guest'
opennds.@opennds[0].authenticated_users='block to 192.168.0.0/16' 'allow tcp port 53' 'allow udp port 53' 'allow tcp port 22' 'allow tcp port 80' 'allow tcp port 443'
opennds.@opennds[0].sessiontimeout='0'
opennds.@opennds[0].authidletimeout='1440'`

I just copied what I set by myself to the new router, but there are a few more lines in v.9, I didn't do anything with them. 

As for Raspi, yeah, I had hoped that wifi would work more easily, but actually I don't need it, as long as I don't mess up the port. If I do, then I can reinstall OpenWRT on the SD card again. So I'm not going to put a lot of energy for it. With FB4020 it was very important because it has no reset-button. With both rooters, APs are in another building and the routers in a dark basement where nobody is around, so wifi isn't that important. This only one ethernet port thing was at first intimidating, but it wasn't that bad. I needed something with better CPU and RAM for my VDSL 100, to replace FB4020.
