### ISSUE TITLE
ndsctl returned 0 when failed to authenticate client

### ISSUE THREAD

**Issue by minhng99** [openNDS/openNDS#178]
Hi, I think we can improve this part a little bit: https://github.com/openNDS/openNDS/blob/master/src/ndsctl.c#L418

![image](https://user-images.githubusercontent.com/14113155/122514233-cdd40380-d035-11eb-9fbd-78adac1d860d.png)

I would like to know about the result after running the auth command but when failed it still returns 0... maybe we can have a table of returned code showing the failed reason? It would be much better this way compared to grepping the stdout.

**Comment by bluewavenet** [comment]
@minhng99 
Yes, it always returns 0 - an oversight that has been in the code forever.....
Current return codes (that are not sent) are:
 * 0 - ok
 * 1 - failed
 * 2 - abnormal reply
 * 3 - error reading socket

**Comment by bluewavenet** [comment]
@minhng99 
It should read:
```
	ret = ndsctl_do(socket, arg, args);
	fclose(fd);
	remove(lockfile);
	free(lockfile);
	free(socket);
	return ret;
```

**Comment by bluewavenet** [comment]
@minhng99 
I made the above changes, tested and added to v9.1.0 (not yet pushed to Github)
Now for example:
`ndsctl auth 00:00:00:00:00:00`
returns 1

**Comment by bluewavenet** [comment]
@minhng99 
Updated return codes:
 * 0 - ok
 * 1 - failed
 * 2 - abnormal reply
 * 3 - error reading socket
 * 4 - ndsctl is locked by another process

**Comment by minhng99** [comment]
Yeah it's good now
btw could you create the v9.1.0 release so I can point my openwrt package feed directly to your repo?

thanks!

**Comment by bluewavenet** [comment]
@minhng99 
Return codes now extended further:

 * 0 - ok
 * 1 - failed
 * 2 - abnormal reply
 * 3 - error reading socket
 * 4 - ndsctl is locked by another process
 * 5 - unable to open lock file
 * 6 - persistent critical error

**Comment by bluewavenet** [comment]
@minhng99 

> could you create the v9.1.0 release 

It is in final pre release testing focusing on generic Linux, currently OpenSuse and Debian.
All it has turned up is a few compiler warnings and one instance of an ash/bash portability issue (not that this effects you).
Next is a documentation update followed by official release.

**Comment by minhng99** [comment]
yeah, I've deployed it on ~50 AP for testing, it's working fine but for some reason, I'm getting a lot of syslog telling `ndsctl is locked`, it's fine after retrying the command though

**Comment by bluewavenet** [comment]
@minhng99 
Are you using latest master? (there have been a few pushes in the last couple of days)
I would only expect to see locked messages in exceptional circumstances on a very busy system.
Perhaps this is a consequence of your roaming setup.
Yes, checking the return code and retrying as required is essential.

Perhaps the locked warning messages to syslog should be suppressed.

I am about to push an ndsctl testing script to https://github.com/openNDS/openNDS/tree/master/testing
This will stress test openNDS and allow router performance estimates to be calculated.

Testing on a gl-inet b1300 (ipq40xx), it can handle a sustained rate of 3 "ndsctl auth" per second with no problems.
To get to this rate (10,800 attempted authentications per hour!), it will have to be VERY busy.

**Comment by minhng99** [comment]
No, I've build the branch 9.1.0 which is on the commit a5c739586b532e8da014a480b7eb1c4fe4fa7d7c
My system weren't that busy, at most there's only 1 or 2 people authenticating every 10s or so... but its strange that I'm getting that

**Comment by bluewavenet** [comment]
@minhng99 
Well yes, statistically you will potentially get some lock errors even on the quietest of systems..
Approximately how many are you getting?

Compared to the B1300, I just tested on a Raspberry Pi Zero W with its Debian variant.
It can barely manage a rate of 1 ndsctl call per second.

It will be interesting to see what your hardware manages.

**Comment by minhng99** [comment]
It's very inconsistent, some devices only got 1 or 2 but some other seems to be locked up most of the time

![image](https://user-images.githubusercontent.com/14113155/123505644-cde48c80-d64f-11eb-88d6-5fcfe30286aa.png)
![image](https://user-images.githubusercontent.com/14113155/123505660-d9d04e80-d64f-11eb-9566-7acbae3aa293.png)

**Comment by bluewavenet** [comment]
@minhng99 
Testing script is now in master

**Comment by minhng99** [comment]
I've just tried it and it's only getting consistently busy on the 11 running instance... it's not always locked up and still have some passed
![image](https://user-images.githubusercontent.com/14113155/123508271-de036880-d65d-11eb-841a-14891bc19d11.png)
![image](https://user-images.githubusercontent.com/14113155/123508289-f5425600-d65d-11eb-82b8-be66398f6ac9.png)
![image](https://user-images.githubusercontent.com/14113155/123508308-17d46f00-d65e-11eb-90a4-4026d7dbee23.png)

**Comment by bluewavenet** [comment]
@minhng99 

> it's only getting consistently busy on the 11 running instance

11 concurrent terminal sessions? Looks like it is coping well!
How many sessions before you **_start_** to get significant numbers of busy returns?

If at the level is it is mostly locked, the queue will be at the point of growing exponentially, at which point it will most likely run out of memory or crash if left running long enough.

Presumably if you stop the tests before bad things happen it is recovering completely.

I have suppressed the syslog messages. These were occurring regardless of debuglevel setting on openNDS and are unnecessary.

**Comment by minhng99** [comment]
It gets busy every second according to syslog when it got to 11 parallel sessions, it still seems to be fine on 10 sessions, only busy once per 3 seconds or so
![image](https://user-images.githubusercontent.com/14113155/123508893-a991ab80-d661-11eb-9517-8a3937a9145d.png)

**Comment by bluewavenet** [comment]
@minhng99 
This all looks good - thanks for doing the test.

In your live system, how often is it occurring?

**Comment by minhng99** [comment]
on a closer look, it seems like the old version that I was running on production (7.0.1) producing the same frequency of lock error as this new 9.1.0 version, I think this is the result of my dnsmasq script hook which is being called every time a client doing something with the DHCP request thus potentially called ndsctl nearly at the same moment... 

Yeah, I think it's just my system, nothing to worry about

**Comment by bluewavenet** [comment]
@minhng99 
The new version of locking uses C library lockf()
Previously it was possible to end up with a deadlock with everything hanging, albeit unlikely.
