### ISSUE TITLE
Error complie OpenNDS v5.0.1 release  in debian 

### ISSUE THREAD

**Issue by xabierseixo** [openNDS/openNDS#18]
When compile OpenNDS v5.0.1 release  in debian, i have a error whith teh name of de package:
 
dpkg-source: error: source package name 'openNDS' is illegal: character 'N' not allowed

**Comment by bluewavenet** [comment]
@xabierseixo 
Very odd. I am aware of a few people who say they have compiled on Raspbian and not reported this.
Can you look more closely to see if you can see the reason you are getting this?

**Comment by xabierseixo** [comment]
OK, these are the steps I follow to compile openNDS, and erros:

Download code:

- git clone https://github.com/opennds/opennds.git- cd opennds
- make

First erros:

cc -O2 -g -Wall -Isrc -c src / auth.c -o src / auth.o
cc -O2 -g -Wall -Isrc -c src / client_list.c -o src / client_list.o
cc -O2 -g -Wall -Isrc -c src / commandline.c -o src / commandline.o
cc -O2 -g -Wall -Isrc -c src / conf.c -o src / conf.o
cc -O2 -g -Wall -Isrc -c src / debug.c -o src / debug.o
cc -O2 -g -Wall -Isrc -c src / fw_iptables.c -o src / fw_iptables.o
cc -O2 -g -Wall -Isrc -c src / main.c -o src / main.o
src / main.c: 66: 10: fatal error: microhttpd.h: No such file or directory
#include <microhttpd.h>

- Solution:
apt-get install libmicrohttpd-dev

- resolv dependences:
libmicrohttpd-dev and libmicrohttpd12


- Execute make: correctly ->

- Create deb package:
make deb

- Error:
dpkg-source --before-build.
dpkg-source: error: source package name 'openNDS' is illegal: character 'N'
not allowed
dpkg-buildpackage: error: dpkg-source --before-build. subprocess returned
exit status 255
make: *** [Makefile: 95: deb] Error 255

- Solution:
find. -type f -print0 | xargs -0 sed -i 's / openNDS / opennds / g'

- Compile correctly
- install the package:
dpkg -i opennds_5.0.1-1_armhf.deb

- Run opennds and error:

$: opennds
[5] [Tue Jun 09 00:28:50 2020] [11974] (src / main.c: 640) opennds Version
5.0.2beta

[3] [Tue Jun 09 00:28:50 2020] [11974] (src / main.c: 284) libmicrohttpd is
out of date, please upgrade to version 0.9.69 or higher
[3] [Tue Jun 09 00:28:50 2020] [11974] (src / main.c: 287) exiting ...:


-- Solution???
System:
Distributor ID: Raspbian
Description: Raspbian GNU/Linux 10 (buster)
Release: 10
Codename: buster

- The same problem in a computer




O luns, 8 de xuño de 2020 ás 21:32, Rob White (<notifications@github.com>)
escribiu:

**Comment by bluewavenet** [comment]
@xabierseixo 

> [3] [Tue Jun 09 00:28:50 2020] [11974] (src / main.c: 284) libmicrohttpd is out of date, please upgrade to version 0.9.69 or higher [3] [Tue Jun 09 00:28:50 2020] [11974] (src / main.c: 287) exiting ...:

See your issue #19

**Comment by bluewavenet** [comment]
v5.1.0 release is now available
https://github.com/openNDS/openNDS/releases/tag/v5.1.0
