### ISSUE TITLE
It is not possible to compile in debian (or raspbian)

### ISSUE THREAD

**Issue by xabierseixo** [openNDS/openNDS#19]
openNDS depends on libmicrohttpd (> 0.9.62) and libmicrohttpd-dev (> = 0.9.51), so it is not possible to compile in Debian

**Comment by bluewavenet** [comment]
@xabierseixo I am not aware of libmicrohttpd-dev and openNDS should not require it.
If you have libmicrohttpd (MHD) earlier than 0.9.69, openNDS will not start by default as earlier versions can corrupt data in some circumstances. However there is a config option to force openNDS to use earlier versions.
On Debian variants this is:
`use_outdated_mhd 1 `

You can however download the source code for the latest version of MHD and compile it your self. After installing this you can then set:
`use_outdated_mhd 0 `

**Comment by frnhr** [comment]
Perhaps update the docs at https://opennds.readthedocs.io/en/v5.0.0/install.html#debian where is says:

> Requirements beside Debian tools are:
>
>  * libmicrohttpd-dev (>= 0.9.51) [avaiable in stretch]

-----

BTW, compiling libmicrohttpd-dev on a Raspberry Pi failed for me. Gave up when `./configure` threw errors.

So forced to use `use_outdated_mhd 1`. Thanks for including the option! 👍

**Comment by bluewavenet** [comment]
@frnhr 
Yes indeed, the documentation does need some work. In some places it has inherited quite a lot from very old versions... Obviously libmicrohttpd-dev was once required or at least specified for some reason. The whole section on compiling needs a rework.

**Comment by bluewavenet** [comment]
@xabierseixo @frnhr 
Version 5.1.0 is now released.
https://github.com/openNDS/openNDS/releases/tag/v5.1.0

Please try the procedure in the updated documentation - hopefully improved. I have tested here on OpenSuse x86-64. Some feedback on how it works with Debian would be welcome. ;-)
https://opennds.readthedocs.io/en/stable/compile.html

**Comment by bluewavenet** [comment]
@xabierseixo @frnhr 
Please post here if you are still having problems and we can re-open this issue if necessary.
