### ISSUE TITLE
walled garden seems not work at http

### ISSUE THREAD

**Issue by z0y1** [openNDS/openNDS#199]
with openDNS

curl -I -L http://apple.com
```
HTTP/1.1 403 Forbidden
Connection: close
Content-Length: 93
Content-Type: text/html; charset=utf-8
Date: Wed, 11 Aug 2021 11:39:06 GMT
```

widthout openDNS
curl -I -L http://apple.com
```
HTTP/1.1 301 Redirect
Date: Wed, 11 Aug 2021 11:38:50 GMT
Connection: keep-alive
Via: http/1.1 hkhkg1-edge-bx-015.ts.apple.com (ApacheTrafficServer/8.1.2)
Server: ATS/8.1.2
Cache-Control: no-store
Location: https://www.apple.com/
Content-Type: text/html
Content-Language: en
CDNUUID: d4d09cee-f75a-4a2a-9763-30e782805fd9-7421565645
X-Cache: none
Content-Length: 304

HTTP/2 200
server: Apple
content-type: text/html; charset=UTF-8
x-frame-options: SAMEORIGIN
x-xss-protection: 1; mode=block
accept-ranges: bytes
x-content-type-options: nosniff
strict-transport-security: max-age=31536000; includeSubdomains
content-security-policy: default-src 'self' blob: *.akamaized.net *.apple.com *.apple-mapkit.com *.cdn-apple.com *.organicfruitapps.com; child-src blob: embed.music.apple.com embed.podcasts.apple.com www.apple.com www.instagram.com platform.twitter.com www.youtube-nocookie.com; img-src 'unsafe-inline' data: blob: *.apple.com *.apple-mapkit.com *.cdn-apple.com *.mzstatic.com; script-src 'unsafe-inline' 'unsafe-eval' blob: *.apple.com *.apple-mapkit.com www.instagram.com platform.twitter.com; style-src 'unsafe-inline' *.apple.com
content-length: 73191
cache-control: max-age=321
expires: Wed, 11 Aug 2021 11:44:11 GMT
date: Wed, 11 Aug 2021 11:38:50 GMT
x-cache: TCP_HIT from a221-194-137-108.deploy.akamaitechnologies.com (AkamaiGHost/10.4.4-34529956) (-)
set-cookie: geo=CN; path=/; domain=.apple.com
```

https work fine with opennds
curl -I -L https://apple.com
```
HTTP/1.1 301 Redirect
Date: Wed, 11 Aug 2021 11:39:04 GMT
Connection: keep-alive
Via: http/1.1 hkhkg1-edge-bx-019.ts.apple.com (ApacheTrafficServer/8.1.2)
Server: ATS/8.1.2
Cache-Control: no-store
Location: https://www.apple.com/
Content-Type: text/html
Content-Language: en
CDNUUID: 675602c5-eced-4568-b152-09381f3da445-7350072484
X-Cache: none
Content-Length: 304

HTTP/2 200
server: Apple
content-type: text/html; charset=UTF-8
x-frame-options: SAMEORIGIN
x-xss-protection: 1; mode=block
accept-ranges: bytes
x-content-type-options: nosniff
strict-transport-security: max-age=31536000; includeSubdomains
content-security-policy: default-src 'self' blob: *.akamaized.net *.apple.com *.apple-mapkit.com *.cdn-apple.com *.organicfruitapps.com; child-src blob: embed.music.apple.com embed.podcasts.apple.com www.apple.com www.instagram.com platform.twitter.com www.youtube-nocookie.com; img-src 'unsafe-inline' data: blob: *.apple.com *.apple-mapkit.com *.cdn-apple.com *.mzstatic.com; script-src 'unsafe-inline' 'unsafe-eval' blob: *.apple.com *.apple-mapkit.com www.instagram.com platform.twitter.com; style-src 'unsafe-inline' *.apple.com
content-length: 73191
cache-control: max-age=211
expires: Wed, 11 Aug 2021 11:42:36 GMT
date: Wed, 11 Aug 2021 11:39:05 GMT
x-cache: TCP_HIT from a221-194-158-69.deploy.akamaitechnologies.com (AkamaiGHost/10.4.4-34529956) (-)
set-cookie: geo=CN; path=/; domain=.apple.com
```

my environment:
ndsctl status:
```
==================
openNDS Status
====
Version: 9.2.0
Uptime: 8s
Gateway Name: [ openNDS ]
Gateway FQDN: [ status.client ]
Managed interface: br-lan
MHD Server [ version 0.9.73 ] listening on: http://192.168.13.1:2050
Maximum Html Page size is [ 10240 ] Bytes
Preemptive Authentication is Disabled
Binauth: Disabled
Preauth Script: /usr/lib/opennds/libopennds.sh
FAS: Secure Level 1, URL: http://192.168.13.1:2050/opennds_preauth/
Client Check Interval: 60s
Rate Check Window: 2 check intervals (120s)
Preauthenticated Client Idle Timeout: 30m
Authenticated Client Idle Timeout: 120m
Download rate limit (default per client): no limit
Upload rate limit (default per client): no limit
Download quota (default per client): no limit
Upload quota (default per client): no limit
Total download: 13 kByte; avg: 13.33 kbit/s
Total upload: 20 kByte; avg: 20.78 kbit/s
====
Client authentications since start: 0
Current clients: 1

Client 0
  IP: 192.168.13.128 MAC: 14:f6:d8:40:b4:d8
  Last Activity: Wed Aug 11 19:38:44 2021 (5s ago)
  Session Start: -
  Session End:   -
  Token: e02b1a91
  State: Preauthenticated
  Upload rate limit: not set
  Download rate limit: not set
  Upload quota: not set
  Download quota: not set
  Upload this session: 0 kB; Session avg: 0.00 kb/s
  Download this session: 0 kB; Session avg: 0.00 kb/s

====
Blocked MAC addresses: none
Allowed MAC addresses: N/A
Trusted MAC addresses: none
Walled Garden FQDNs:
  apple.com
Walled Garden Ports:
  80
  443
========
```

ipset list
```
Name: walledgarden
Type: hash:ip
Revision: 4
Header: family inet hashsize 1024 maxelem 65536
Size in memory: 296
References: 4
Number of entries: 2
Members:
17.253.144.10
221.194.155.186

```

iptables
```
Chain ndsNET (1 references)
target     prot opt source               destination
ACCEPT     tcp  --  anywhere             anywhere             tcp dpt:https match-set walledgarden dst
ACCEPT     tcp  --  anywhere             anywhere             tcp dpt:www match-set walledgarden dst
DROP       all  --  anywhere             anywhere             mark match 0x10000/0x30000
DROP       all  --  anywhere             anywhere             ctstate INVALID
TCPMSS     tcp  --  anywhere             anywhere             tcp flags:SYN,RST/SYN TCPMSS clamp to PMTU
ACCEPT     all  --  anywhere             anywhere             mark match 0x20000/0x30000
ndsAUT     all  --  anywhere             anywhere             mark match 0x30000/0x30000
ACCEPT     tcp  --  anywhere             anywhere             tcp dpt:www match-set walledgarden dst
ACCEPT     tcp  --  anywhere             anywhere             tcp dpt:https match-set walledgarden dst
REJECT     all  --  anywhere             anywhere             reject-with icmp-port-unreachable
```

config file just add the following tow lines:
```
        list walledgarden_fqdn_list 'apple.com'
        list walledgarden_port_list '443 80'
```

did i miss some walled garden config params?

**Comment by bluewavenet** [comment]
@z0y1 
As you can see from your output of `ipset list`, it is actually working.

However, the website at apple.com does an immediate canonical link to `https://www.apple.com.`
I discovered this by testing.
When a newly connected, but not authenticated device tries to access `http://apple.com` with your setup, openNDS will correctly generate a 403 error. However if that device directly accesses `https://apple.com` then the website will be allowed due to the ipset.

This is fortunate (or is it by design?), as all Apple device CPD implementations use `http://captive.apple.com/hotspot-detect.html ` as the capture detection url which is of course added to the ipset for the fqdn "apple.com", meaning ALL Apple devices would be blocked from automatically detecting the captive portal.

If you want everyone accessing your portal to be able to, for example, click a link to apple.com before authenticating, then only configure port 443. `http://apple.com` will then correctly trigger your portal login page.

**Comment by bluewavenet** [comment]
@z0y1 

```
openNDS Status
====
Version: 9.2.0
```
I would suggest it would be sensible to upgrade to v9.3.0 which is the latest version.

**Comment by z0y1** [comment]
thank you for the answer, in fact I have tried many other domains , not only apple.com, both of them have the same issue.
any way I'll try v9.3.0~

**Comment by bluewavenet** [comment]
@z0y1 

> I have tried many other domains , not only apple.com, both of them have the same issue

You are absolutely correct. I did some in depth testing today and in fact port 80 is always redirected to the portal, regardless of any walled garden port 80 setting. This was implemented some years ago for the reasons I mentioned (ie ipset could prevent CPD from functioning).

I have written a patch to enable this. But should we? I suppose suitable warnings could be put in the default config file and the documentation.

Should this be enabled? Let me know your view..

**Comment by z0y1** [comment]
Thank you for the time on depth testing. My point of view is "Walled Garden" means users can access those sites direct, http or https, 80 or 443.

 "https://opennds.readthedocs.io/en/stable/walledgarden.html"  
![image](https://user-images.githubusercontent.com/1248666/129455323-c15e4ea5-b1e7-491e-bec2-8264f0682452.png)
I think "certain web sites" should not only means https sites but also http sites。

**Comment by bluewavenet** [comment]
@z0y1 
I (think) I agree port 80 should be allowed, however enabling it in the Walled garden for apple.com, google.com, baidu.com, samsung.com, gnome.org to name but a few WILL break CPD for many devices.

As I said, I have a patch to enable this. I will do some acceptance testing with the patch and if all is well will push to Github and merge with master.

**Comment by z0y1** [comment]
That's awesome~, I really appreciate for your help.

**Comment by bluewavenet** [comment]
@z0y1 
I think I will add a warning message to syslog as well.

Are you compiling from source? If so I will push to beta and you can test it for me ;-)

**Comment by bluewavenet** [comment]
@z0y1 
I'll be happy with a new config option something like "enable_walled_garden_port_80", defaulting to disabled.

**Comment by bluewavenet** [comment]
@z0y1 
I decided to go with just a port 80 warning. So if port 80 is allowed implicitly or by default, a warning message is printed into the syslog.
We can do the config option later if this causes problems.
The changes are now merged with master. The next release will probably be fairly soon.
