### ISSUE TITLE
Firewall traffic rules in OpenNDS and OpenWRT

### ISSUE THREAD

**Issue by doremifajb** [openNDS/openNDS#200]
Hello ! 

This is still a continuation of the previous issue I started:
https://github.com/openNDS/openNDS/issues/195

but the portal is working well, and now my question is purely "other things", so I thought it's a good point to start a new issue, regarding `opennds.@opennds[0].authenticated_users`

>     * **Unless you want to be authoritarian then you should allow all.**
>       block to 192.168.0.0/16 is invalid as it blocks 192.168.x.x which includes the ip gateway.

The destination of `authenticated_users ` is WAN, so if the openWRT Router is behind an ISP router and if I want to block access from the guests to the ISP router and anything connected directly to it, I will have to put something like `block to 192.168.0.0/16` for authenticated_users, right ? (e.g. my ISP router would probably have 192.168.178.1).

But if I put this line, then `authenticated_users` will be activated to block everything (as I understood from the manual), so I will have to write down everything that should be allowed. Wouldn't that be a huge list ? Or should I just not have this line, then the default would be passthrough, then I should set whatever on OpenWRT ? I.e. unless one wants to have different post-authentication rules for the interface on OpenNDS from the rules for the zone it belongs to, one should just let openNDS passthough the authenticated_users (i.e. not have that line) and set what you want on openWRT ? 

Another thing is, with multiple interfaces, one can access to luci at 192.168.1.1, or 192.168.2.1 or 192.168.3.1 and so on. Is that all taken care of by users_to_router ? Namely, if you set  `users_to_router='allow tcp port 53' 'allow udp port 53' 'allow udp port 67'` then the only allowed things are DNS and DHCP, luci access under all these addresses will be blocked, even if "forward" is not rejected ? (i.e. in my case, 192.168.2.1 belongs to eth0.11 which got OpenNDS, the other two belong to other zones respectively) 

I will appreciate your advice !!

**Comment by bluewavenet** [comment]
@doremifajb 
Access control for authenticated users is almost always set to "allow all" with very few people needing to set anything else.
However, prior to version 9.3.0, access control for authenticated users had some bugs, or more to be precise some legacy code from NoDogsplash that did not work correctly, particularly with respect to passthrough to the operating system firewall.

See the v9.3.0 documentation at:
https://opennds.readthedocs.io/en/stable/config.html#access-control-for-authenticated-users

> with multiple interfaces, one can access to luci at 192.168.1.1, or 192.168.2.1 or 192.168.3.1 and so on.

This is expected and is the default. Restricting luci to specific subnets is done in the uhttp config and is nothing to do with openNDS.
(Hint: you need to specifically set the uhttpd listen_http address).

**Comment by doremifajb** [comment]
Thank you for the reply ! Then I will just set allow all (it's still planning: it's about next year). I suppose that's what you set for the hotel wifi in your diagram you gave me with three routers and VoIP, then it's good for me. 

As for my second question, I think I didn't formulate it well .. my OpenNDS is for eth0.11 with 192.168.2.1/24. Now, in general (if I don't restrict anything), there are possibility of opening luci at 192.168.n.1, where n=1, 2, 3, because I have all these three subnets. My question was, suppose I want eth0.11 client not to be able to access luci at 192.168.n.1, where n=1, 3, is it taken care of by users_to_router (i.e. firewall with destination as device input), or is it a part of forwarding because the address belongs to another subnet ? (i.e. it should be taken care of by OpenWRT) 
Right now, when I'm on eth0.11, I can't access to luci through any of 192.168.n.1 (which I intended, so it's good.) My authenticated users is allow all, users_to_router is the three things for DNS, DHCP, and on OpenWRT I have 
input: reject, output: accept, forward: reject, and then exceptions for DNS and DHCP. I am not very sure which one contributes blockage of luci for eth0.11.

**Comment by bluewavenet** [comment]
@doremifajb 
I will state it clearly - passthrough to the OpenWrt firewall **DOES NOT WORK** for versions of **openNDS LESS than 9.3.0**.

This is fixed in v9.3.0 with the introduction of "passthrough".
For example:
`list authenticated_users 'allow all'` allows everything but **_DOES NOT chain_** to the OpenWrt firewall.
`list authenticated_users 'passthrough all'` allows everything and **_DOES chain_** to the OpenWrt firewall.

**Access to Luci**
This is controlled by the web server used by OpenWrt for Luci, uhttpd, as I hinted above.
By default Luci is available on all lan interfaces (see the output of `uci show uhttpd` )
By default uhttpd binds to all lan ip interfaces.
You will see `uhttpd.main.listen_http='0.0.0.0:80'` in the output of `uci show uhttpd`
You could replace the 0.0.0.0 with the ip of the router's address on the admin network to bind only to that interface.

**In addition**, on the openNDS interface, you can choose to not allow access to port 80 on the router as you have found out.

**Comment by doremifajb** [comment]
Thank you very much for your explanation ! I understood it now better :)
