### ISSUE TITLE
Install on OpenWRT 19.07.8

### ISSUE THREAD

**Issue by 0l4y4** [openNDS/openNDS#203]
Hi!

I want to install openNDS in my TL-WDR3600 router with OpenWrt 19.07.8 firmware version. When I read your documentation, you say:

**_To install on 19.7.x or lower, download libmicrohttpd-no-ssl_0.9.71-1 or higher_** 	

But I don't found it! I have found version:0.9.62-3 here:

[https://openwrt.org/packages/pkgdata/libmicrohttpd-no-ssl](url)

Is it valid?

Thank you

**Comment by openwrtdiy** [comment]
https://github.com/openwrt/packages/tree/master/libs/libmicrohttpd
https://github.com/openwrt/packages/tree/openwrt-19.07/libs/libmicrohttpd
https://github.com/openwrt/routing/tree/master/opennds
https://github.com/openwrt/routing/tree/openwrt-19.07/opennds

Before compiling OpenWrt-19.07.8 and OpenNDS, directly replace libmicrohttpd/Makefile and opennds/Makefile

**Comment by 0l4y4** [comment]
Thanks @openwrtdiy!

It would be easier if I could do it on my OS directly. Is the only way?

**Comment by bluewavenet** [comment]
@0l4y4 
Yes there is a very much easier way.
Download libmicrohttpd-no-ssl and opennds directly from openwrt downloads snapshot.
Despite being snapshot, the packages there are actually the latest stable versions.

Goto:
https://downloads.openwrt.org/snapshots/packages/

Then select the folder for the architecture of your router.
Here you will see various folders. We are interested in "packages" and "routing"

Select the packages folder and download libmicrohttpd-no-ssl_0.9.73-1_xxxxxxx.ipk
where xxxxxxxx is the architecture you selected.

Select the "routing" folder and download opennds_9.3.0-1_xxxxxxx.ipk

Now transfer both these files to /tmp on your router (using scp or similar)

Login to a terminal session on your router.

Do:
```
cd /tmp
opkg install libmicrohttpd-no-ssl_0.9.73-1_xxxxxxx.ipk --force-reinstall
opkg install opennds_9.3.0-1_xxxxxxx.ipk --force-reinstall
```
of course replacing the "xxxxxxx" with the architecture name.

You can also use the wget command on the router instead of downloading using your computer browser.
I can send the wget commands if you let me know the model of router you are using.

**Comment by 0l4y4** [comment]
@bluewavenet thank you very much! I'm happy for reading it!

I wrote the model of my router in the first post, TL-WDR3600 and It architecture is "Atheros AR9344 rev 2"

**Comment by bluewavenet** [comment]
@0l4y4 
Ah! Yes, sorry, I just read that ;-)
It is mips_24kc 
So replace xxxxxxx with mips_24kc

**Comment by bluewavenet** [comment]
@0l4y4 
I could give you the wget commands, but doing it by downloading to your computer then copying to the router is more instructive for beginners...

**Comment by 0l4y4** [comment]
@bluewavenet 
Don't worry, I know about Linux OS. It is done! Thank's!

**Comment by bluewavenet** [comment]
@0l4y4 
There are a lot of student projects using openNDS, so I am never too sure of the level people are at :-D

**Comment by bluewavenet** [comment]
@0l4y4 
Is it running?
`logread -e opennds`
and
`ndsctl status`
give useful info.

**Comment by 0l4y4** [comment]
> `There are a lot of student projects using openNDS, so I am never too sure of the level people are at :-D`

It is normal, I am a sysadmin but I have to tell you that I know very little about PHP, so I am afraid that I will open more posts about this type of question.


> `logread -e opennds`

Tue Aug 24 19:34:10 2021 daemon.notice opennds[4170]: openNDS Version 9.3.0 is in startup
Tue Aug 24 19:34:12 2021 daemon.notice opennds[4170]: MHD version is 0.9.73
Tue Aug 24 19:34:12 2021 daemon.notice opennds[4170]: Attempting to Bind to interface: br-lan
Tue Aug 24 19:34:12 2021 daemon.notice opennds[4170]: Interface br-lan is up
Tue Aug 24 19:34:12 2021 daemon.notice opennds[4170]: Interface br-lan is at 192.168.1.1 (e8:94:f6:d4:2a:e4)
Tue Aug 24 19:34:12 2021 daemon.notice opennds[4170]: Upstream gateway [ 192.168.0.1 ] via interface [ eth0.2 ] is online
Tue Aug 24 19:34:12 2021 daemon.notice opennds[4170]: Created web server on 192.168.1.1:2050
Tue Aug 24 19:34:12 2021 daemon.notice opennds[4170]: Maximum Html Page size is [ 10240 ] Bytes
Tue Aug 24 19:34:12 2021 daemon.notice opennds[4170]: Socket access at /tmp/ndsctl.sock
Tue Aug 24 19:34:12 2021 daemon.notice opennds[4170]: Click to Continue option is Enabled.
Tue Aug 24 19:34:12 2021 daemon.notice opennds[4170]: Preauth is Enabled - Overiding FAS configuration.
Tue Aug 24 19:34:12 2021 daemon.notice opennds[4170]: sha256sum provider is available
Tue Aug 24 19:34:12 2021 daemon.notice opennds[4170]: FAS URL is http://192.168.1.1:2050/opennds_preauth/
Tue Aug 24 19:34:12 2021 daemon.notice opennds[4170]: Forwarding Authentication is Enabled.
Tue Aug 24 19:34:12 2021 daemon.notice opennds[4170]: Initializing firewall rules
Tue Aug 24 19:34:13 2021 daemon.notice opennds[4170]: openNDS is now running.
Tue Aug 24 19:34:50 2021 daemon.notice opennds[4170]: Adding 192.168.1.241 a4:4c:c8:7e:57:aa token 670bae67 to client list
Tue Aug 24 19:35:01 2021 daemon.notice opennds[4170]: Authenticating 192.168.1.241 a4:4c:c8:7e:57:aa

> `ndsctl status`  

==================
openNDS Status
====
Version: 9.3.0
Uptime: 7m 33s
Gateway Name: [ openNDS ]
Gateway FQDN: [ status.client ]
Managed interface: br-lan
Upstream gateway [ 192.168.0.1 ] via interface [ eth0.2 ] is online
MHD Server [ version 0.9.73 ] listening on: http://192.168.1.1:2050
Maximum Html Page size is [ 10240 ] Bytes
Preemptive Authentication is Disabled
Binauth: Disabled
Preauth Script: /usr/lib/opennds/libopennds.sh
FAS: Secure Level 1, URL: http://192.168.1.1:2050/opennds_preauth/
Client Check Interval: 60s
Rate Check Window: 2 check intervals (120s)
root@OpenWrt:/tmp# ndsctl status
==================
openNDS Status
====
Version: 9.3.0
Uptime: 7m 37s
Gateway Name: [ openNDS ]
Gateway FQDN: [ status.client ]
Managed interface: br-lan
Upstream gateway [ 192.168.0.1 ] via interface [ eth0.2 ] is online
MHD Server [ version 0.9.73 ] listening on: http://192.168.1.1:2050
Maximum Html Page size is [ 10240 ] Bytes
Preemptive Authentication is Disabled
Binauth: Disabled
Preauth Script: /usr/lib/opennds/libopennds.sh
FAS: Secure Level 1, URL: http://192.168.1.1:2050/opennds_preauth/
Client Check Interval: 60s
Rate Check Window: 2 check intervals (120s)
Preauthenticated Client Idle Timeout: 30m
Authenticated Client Idle Timeout: 120m
Download rate limit (default per client): no limit
Upload rate limit (default per client): no limit
Download quota (default per client): no limit
Upload quota (default per client): no limit
Total download: 656 kByte; avg: 11.48 kbit/s
Total upload: 233 kByte; avg: 4.08 kbit/s
====
Client authentications since start: 1
Current clients: 1

Client 0
  IP: 192.168.1.241 MAC: a4:4c:c8:7e:57:aa
  Last Activity: Tue Aug 24 19:41:49 2021 (0s ago)
  Session Start: Tue Aug 24 19:35:01 2021 (6m 48s ago)
  Session End:   Wed Aug 25 15:35:01 2021 (19h 53m 12s left)
  Token: 670bae67
  State: Authenticated
  Upload rate limit: not set
  Download rate limit: not set
  Upload quota: not set
  Download quota: not set
  Upload this session: 194 kB; Session avg: 3.81 kb/s
  Download this session: 601 kB; Session avg: 11.79 kb/s

====
Blocked MAC addresses: none
Allowed MAC addresses: N/A
Trusted MAC addresses: none
Walled Garden FQDNs: none
Walled Garden Ports: none
========

**Comment by bluewavenet** [comment]
@0l4y4 

> It is normal, I am a sysadmin but I have to tell you that I know very little about PHP, so I am afraid that I will open more posts about this type of question.

No problem at all.
Your WDR3600 only has 8MB flash?
If so you will not be able to run a local php FAS - not enough room.
Dynamic ThemeSpec splash page sequences ( the default mode) are all written in Busybox ASH, so this is not a problem if you want to keep everything local.
If you want a remote FAS, you can use a mode that does not need php locally.
So you have lots of options.
The up to date documentation for v9.3.0 is here:
https://opennds.readthedocs.io/en/stable/

**Comment by bluewavenet** [comment]
@0l4y4 
FYI - You can use the "insert code" text box menu option here on Github (the <>  option)

eg.

==================
openNDS Status
====
Version: 9.3.1beta

becomes:
```
==================
openNDS Status
====
Version: 9.3.1beta
```

**Comment by 0l4y4** [comment]
> @0l4y4
> 
> > It is normal, I am a sysadmin but I have to tell you that I know very little about PHP, so I am afraid that I will open more posts about this type of question.
> 
> No problem at all.
> Your WDR3600 only has 8MB flash?
> If so you will not be able to run a local php FAS - not enough room.
> Dynamic ThemeSpec splash page sequences ( the default mode) are all written in Busybox ASH, so this is not a problem if you want to keep everything local.
> If you want a remote FAS, you can use a mode that does not need php locally.
> So you have lots of options.
> The up to date documentation for v9.3.0 is here:
> https://opennds.readthedocs.io/en/stable/

I was thinking about external https server but I have a concept doubts. I know that validation and authentication are different things but I don't know how I have to program my https for reporting to openNDS is sucessfull because I don't know how it works. 
In this moment I am studying the Authmon daemon, I think It can help me

**Comment by bluewavenet** [comment]
@0l4y4 
To run an external https FAS openNDS requires a local install of php-cli.
I don't think your WDR3600 has enough flash memory to install this.

To discuss this more it would be better to open a new issue.

**Comment by bluewavenet** [comment]
@0l4y4 
For an https FAS example, see:
https://opennds.readthedocs.io/en/stable/fas.html#example-script-file-fas-aes-https-php
