### ISSUE TITLE
How openNDS works?

### ISSUE THREAD

**Issue by 0l4y4** [openNDS/openNDS#204]
Hello!

What's the function for informing to openNDS the user has been logged in an externarl HTTPS server in fas-aes-https.php? 

Thanks

**Comment by bluewavenet** [comment]
@0l4y4 
On the remote https FAS (where fas-aes-https.php is running) when a client is verified, the FAS adds the client information to a list.

Back on the openNDS router, the authmon daemon periodically asks the remote FAS for the list of clients to authenticate.

Authmon effectively opens a NAT traversing inbound channel for the remote FAS to inform openNDS of clients that have been successfully verified.

**Comment by bluewavenet** [comment]
@0l4y4 
Here is clip from fas-aes-https.php:
```
#############################################################################################################
#
# Send The Auth List when requested by openNDS
#
# When a client was verified, their parameters were added to the "auth list"
# The auth list is sent to NDS when it authmon requests it.
#
# auth_get:
#
# value "list" sends the list and deletes each client entry that it finds
#
# value "view" just sends the list, this is the default value for authmon and allows upstream processing here
#
#############################################################################################################

```

**Comment by 0l4y4** [comment]
@bluewavenet 

I'm just looking at this part of the code. I'm studying this with calm because I would like to integrated it with social login in the future, but step by step. 

I would like to talk about an example:

I have an HTTPS server with fas-aes-https.php for default, then one user enter it name and mail and the client information is added to a list. 

What information has the list?

**Comment by bluewavenet** [comment]
@0l4y4 

> What information has the list?

This is found in `function authenticate_page()`

```
	# Construct the client authentication string or "log"
	# Note: override values set earlier if required, for example by testing clientif 
	$log="$rhid $sessionlength $uploadrate $downloadrate $uploadquota $downloadquota ".rawurlencode($custom)."\n";

	$logfile="$logpath"."$gwname/$rhid";

	if (!file_exists($logfile)) {
		file_put_contents("$logfile", "$log");
	}

	echo "Waiting for link to establish....<br>";
```
