### ISSUE TITLE
Router recommended

### ISSUE THREAD

**Issue by 0l4y4** [openNDS/openNDS#205]
I was trying to install openNDS (mode FAS external on Internet) on openWRT installed on TL-WDR3600 but the memory ROM is not enought for installing php7-cli and php7-mod-openssl.

I know about RPI but I would like to do it on router device. Do you know the cheapest recommendation?

Cheers!

**Comment by bluewavenet** [comment]
@0l4y4 
Of course it depends on numerous things like how many people will be using the system, the bandwidth of the Internet feed etc.
However a GL-INET MT300N-V2 handles a couple of hundred users in a shopping mall for example. At ~$20 it is a bargain. Sure it might struggle if everyone tries to stream video but then that is what volume and rate quotas are for.

**Comment by 0l4y4** [comment]
@bluewavenet 

The goal is something smaller. I like your recommendation! Thanks

**Comment by bluewavenet** [comment]
@0l4y4 
The recommended minimum is 16/128 MB.
If you wanted to implement much more **local** content in a FAS then obviously larger than 16/128 would possibly be needed.
Also if you have a lot of clients all with rate limiting, a faster cpu might help, but all of this is down to a sizing choice depending on the detail of your requirement.
My suggested level of hardware does surprisingly well and at the very least is a good starting point being cheap enough to replace with something more powerful later if required.

**Comment by bluewavenet** [comment]
@Scyllaly 
Yes indeed, any device supported by OpenWrt, and in the case of x86, generic Linux works fine.
However an x86 board will usually be ~10 times the cost of a simple mini-router. It all depends on your requirements.

**Comment by 0l4y4** [comment]
@bluewavenet 
Do you know this model (GL-AR300M Series Mini Smart Router)?

**Comment by bluewavenet** [comment]
@0l4y4 
Yes it is quite good but the external antennas (on the "ext" version) are not very effective so not worth it.
The gl-mt300n-v2 is better in all respects, getting greater coverage without external antennas then the ar300m does with.
The mt300n-v2 is also significantly cheaper!
The only advantage of the ar300m is the NAND flash (128MB) but this is not needed for a captive portal solution even with a separate local FAS. The NAND flash comes with its own problems too, as you can end up booting from the wrong firmware when you least expect it (it also has 16MB NOR onboard with its own firmware).
