### ISSUE TITLE
openNDS https FAS not working

### ISSUE THREAD

**Issue by 0l4y4** [openNDS/openNDS#207]
Hello!

I have installed openWRT on RPI 3B+. I have configured the WAN throght Wi-Fi access and the LAN throught  RJ45. Also, I have a web server https://wsecurity.es like a example and I have configured openNDS following all steps of **_"Example Script File fas-aes-https.php"_** and all it's working. Nevertheless, when I connect my laptop to the LAN network, CPD is ok, from my web server but I enter my name and mail and accept the terms I don't have access to Internet.

Here the logs:

```root@OpenWrt:~# logread -e opennds

Thu Aug 26 11:13:11 2021 daemon.notice opennds[6120]: openNDS Version 9.3.0 is in startup
```
```root@OpenWrt:~# ndsctl status
==================
openNDS Status
====
Version: 9.3.0
Uptime: 30m 18s
Gateway Name: [ openNDS ]
Gateway FQDN: [ status.client ]
Managed interface: br-lan
Upstream gateway [ 192.168.43.1 ] via interface [ wlan0 ] is online
MHD Server [ version 0.9.73 ] listening on: http://192.168.1.1:2050
Maximum Html Page size is [ 10240 ] Bytes
Preemptive Authentication is Disabled
Binauth: Disabled
Preauth: Disabled
FAS: Secure Level 3, URL: https://wsecurity.es:443/nds/fas-aes-https.php
Client Check Interval: 60s
Rate Check Window: 2 check intervals (120s)
Preauthenticated Client Idle Timeout: 30m
Authenticated Client Idle Timeout: 120m
Download rate limit (default per client): no limit
Upload rate limit (default per client): no limit
Download quota (default per client): no limit
Upload quota (default per client): no limit
Total download: 699 kByte; avg: 3.08 kbit/s
Total upload: 197 kByte; avg: 0.87 kbit/s
====
Client authentications since start: 0
Current clients: 1

Client 0
  IP: 192.168.1.148 MAC: a4:4c:c8:ea:88:b6
  Last Activity: Thu Aug 26 11:15:53 2021 (27m 36s ago)
  Session Start: -
  Session End:   -
  Token: aa188d4a
  State: Preauthenticated
  Upload rate limit: not set
  Download rate limit: not set
  Upload quota: not set
  Download quota: not set
  Upload this session: 0 kB; Session avg: 0.00 kb/s
  Download this session: 0 kB; Session avg: 0.00 kb/s

====
Blocked MAC addresses: none
Allowed MAC addresses: N/A
Trusted MAC addresses: none
Walled Garden FQDNs: none
Walled Garden Ports: none
========```

**Comment by bluewavenet** [comment]
@0l4y4 
Both clients are showing `State: Preauthenticated`
This means authmon is not receiving authentication request from FAS. If it was logread would show something like:
```
Sat Aug 28 09:29:19 2021 daemon.notice opennds[1960]: Adding 10.27.5.115 74:de:2b:b1:70:33 token 88e7de77 to client list
Sat Aug 28 09:29:23 2021 daemon.info opennds[1960]: : authmon - authentication parameters 7498419b4d3ca97b11c29254f0c4913b6583e25708d4c90fa0fc086d1920dfb5 0 0 0 0 0 Optional%20Custom%20data%20for%20BinAuth
Sat Aug 28 09:29:23 2021 daemon.notice opennds[1960]: Authenticating 10.27.5.115 74:de:2b:b1:70:33
```

Most likely this is an issue with the configuration of your web server in that PHP is not able to write to the same folder that the PHP script resides:
`FAS: Secure Level 3, URL: https://wsecurity.es:443/nds/fas-aes-https.php`
Check on your FAS server in the nds folder. You should see a sub folder with a long encoded name (the sha256 hash of gatewayname - openNDS according to your ndsctl status output).
So the folder should be:
03c569832021445052095039160a4c5210b6d7ca17fbd6df4c81aba1e909c374

If this does not exist, you will need to set the access rights for PHP so that it can create it and write files into it.

**Comment by 0l4y4** [comment]
@bluewavenet 
Indeed, the problem was permissions on that folder. I have the folder and it seems that it has progressed to the next problem... 
```
Waiting for link to establish...
**********
**********
**********

The portal has time out
You may have to turn your WiFi off and on to reconnect.

Click or tap Continue to try again.
```

**Comment by 0l4y4** [comment]
@bluewavenet 
I am checking the permissions of the folder created with the name of the token, because with my normal user I have not been able to access. When checking its content with root there is nothing, could this be the problem?

**Comment by bluewavenet** [comment]
@0l4y4 
Did you copy the fas_aes_https.php from /etc/opennds/ on your mt300n-v2?

**Comment by bluewavenet** [comment]
@0l4y4 
Test against my server, change to the following in your config:
```
	option fasremotefqdn 'blue-wave.net'
	option fasremoteip '46.32.240.41'
	option fasport '443'
	option faspath '/fas2/fas-aes-https.php'
```
This is the v3.1.0 version and works fine for me. If it works for you then we will know the problem is on your server.

**Comment by 0l4y4** [comment]
@bluewavenet 

On my mt300n-v2 I have changed (/etc/config/opennds):
```
option fasremotefqdn 'wsecurity.es'
option fasremoteip '20.43.62.168'
option fasport '443'
option faspath '/nds/fas-aes-https.php'
option fas_secure_enabled '3'
option faskey '1234567890'
```
On my server fas-aes-https.php is for default.

Done!
```
	option fasremotefqdn 'blue-wave.net'
	option fasremoteip '46.32.240.41'
	option fasport '443'
	option faspath '/fas2/fas-aes-https.php'
```

**Comment by 0l4y4** [comment]
```
Página web no disponible

No ha sido posible cargar la página web http://blue-wave.net:443/fas2/fas-aes-https.php?fas=aGlkPWQzYzUyZGE1YWY1MGI0ZDM5N2EzNzdjZjE0NzhmZGRjODU4OGQ2NGIxZjlkMjhhNWYxN2IxOWZlNjg4YmQ2NDUsIGNsaWVudGlwPTE5Mi4xNjguMS4xMTUsIGNsaWVudG1hYz04ZTpkZjpkODo1MDo0NjowYywgZ2F0ZXdheW5hbWU9b3Blbk5EUywgdmVyc2lvbj05LjMuMCwgZ2F0ZXdheWFkZHJlc3M9MTkyLjE2OC4xLjE6MjA1MCwgZ2F0ZXdheW1hYz05NDo4MzpjNDowYjpmZTo2Mywgb3JpZ2ludXJsPWh0dHAlM2ElMmYlMmZjb25uZWN0aXZpdHljaGVjay5nc3RhdGljLmNvbSUyZmdlbmVyYXRlXzIwNCwgY2xpZW50aWY9d2xhbjAsIHRoZW1lc3BlYz0obnVsbCksIChudWxsKShudWxsKShudWxsKShudWxsKQ== porque:
net::ERR_EMPTY_RESPONSE
```

**Comment by 0l4y4** [comment]
I have the same problem with your configuration

**Comment by bluewavenet** [comment]
@0l4y4 
I tried your FAS server configuration and it works perfectly.
Screenshot:
![Screenshot from 2021-08-28 21-16-26](https://user-images.githubusercontent.com/13632068/131230133-3d7d42f1-b06a-4d42-b320-bc496890b182.png)

Check the log on your server - in the nds/ndslog folder.

Summary:
 * Your server works with my install of openNDS (happens to be v9.3.1beta, but nothing to do with this has changed)
 * Your server does not work with your install of openNDS v9.3.0
 * My server works with my install of openNDS
 * My server does not work with your install of openNDS

It looks very much like there is something wrong with your install of openNDS.

Please show the output of:
`uci show opennds`
and also:
`ps | grep authmon.ps`

**Comment by bluewavenet** [comment]
@0l4y4 
You can test if openNDS is working by doing:
```
uci set opennds.@opennds[0].login_option_enabled='2'
service opennds restart
```

This will return to your original config on a reboot or if you do:
```
uci set opennds.@opennds[0].login_option_enabled='0'
service opennds restart
```
If you do `uci commit opennds` any changes will be saved after reboot.

**Comment by 0l4y4** [comment]
```
<?php exit(0); ?>
2021-08-28 20:15:04, fas-aes-https, %24BlueWave%20Captive%20Portal, rob, rob@blue-wave.net, 10.27.5.115, 74:de:2b:b1:70:33, wlan0, Mozilla/5.0 (X11; Linux x86_64; rv:78.0) Gecko/20100101 Firefox/78.0, http://detectportal.firefox.com/success.txt
```

```
root@OpenWrt:~# uci show opennds
opennds.@opennds[0]=opennds
opennds.@opennds[0].enabled='1'
opennds.@opennds[0].fwhook_enabled='1'
opennds.@opennds[0].maxclients='250'
opennds.@opennds[0].users_to_router='allow tcp port 53' 'allow udp port 53' 'allow udp port 67' 'allow tcp port 22' 'allow tcp port 80' 'allow tcp port 443'
opennds.@opennds[0].fasport='443'
opennds.@opennds[0].faspath='/fas2/fas-aes-https.php'
opennds.@opennds[0].fas_secure_enabled='3'
opennds.@opennds[0].faskey='1234567890'
opennds.@opennds[0].fasremoteip='46.32.240.41'
opennds.@opennds[0].fasremotefqdn='blue-wave.net'
```
```
root@OpenWrt:~# ps |grep authmon.sh
 9921 root      1228 S    /bin/sh /usr/lib/opennds/authmon.sh https://blue-wave.net:443/fas2/fas-aes-https.php dcf9a0cb8f0f5fbe465
12626 root      1212 S    grep authmon.sh
```

**Comment by 0l4y4** [comment]
> You can test if openNDS is working by doing:
> 
> ```
> uci set opennds.@opennds[0].login_option_enabled='2'
> service opennds restart
> ```
With this option it works perfectly

**Comment by bluewavenet** [comment]
@0l4y4 

>`2021-08-28 20:15:04, fas-aes-https, %24BlueWave%20Captive%20Portal, rob, rob@blue-wave.net, 10.27.5.115, 74:de:2b:b1:70:33, wlan0, Mozilla/5.0 (X11; Linux x86_64; rv:78.0) Gecko/20100101 Firefox/78.0, http://detectportal.firefox.com/success.txt'

This is me logging in to your FAS server, so nothing obvious wrong with it and I had full Internet access.

` 9921 root      1228 S    /bin/sh /usr/lib/opennds/authmon.sh https://blue-wave.net:443/fas2/fas-aes-https.php dcf9a0cb8f0f5fbe465`

This shows authmon is running on your openNDS router - ok so far.

`uci show opennds ......`

This looks ok.  You do not have an authenticated_users entry which means openNDS will default to passthrough all.
Any downstream iptables rules will be activated, if present (ie the OpenWrt firewall). This should not prevent authentication though.

Perhaps you should start again, reflash, reinstall openNDS and check if it works correctly in default click to continue mode.

**Comment by bluewavenet** [comment]
@0l4y4 
Just seen your last post.

> With this option it works perfectly

That is good. Perhaps though reflash again etc as I said. The problem must be on your router somewhere.....

**Comment by bluewavenet** [comment]
@0l4y4 
Some debug options when configured for an external https FAS, first set debuglevel.
`ndsctl debuglevel 2`

Attempt to login a client -  then do:
`logread -e authmon`

**Comment by bluewavenet** [comment]
@0l4y4 
When configured to use your server and using the above debug options, I get:
```
Sun Aug 29 11:27:07 2021 daemon.info opennds[26636]: Explicitly killing the authmon daemon
Sun Aug 29 11:27:08 2021 daemon.info opennds[28822]: authmon pid is: 28980
Sun Aug 29 11:28:21 2021 daemon.info opennds[28822]: : authmon - authentication parameters a9ef78724be8f2a99066db3023be955471430dc1eee6e48b4810e8839c60d468 0 0 0 0 0 Optional%20Custom%20data%20for%20BinAuth
```
The first entry is openNDS ensuring any previous authmon daemon is killed before starting a new one.
The second entry is confirming the new authmon instance has started.
The last one is me being authenticated by authmon.

You should now have more log entries on your server from me.

**Comment by 0l4y4** [comment]
@bluewavenet 
> Perhaps you should start again, reflash, reinstall openNDS and check if it works correctly in default click to continue mode.

I have started again, I have reflashed and it works correctly in default click to continue mode but I've followed all the steps in FAS https mode and I still have the same problem.

**Comment by 0l4y4** [comment]
```
root@OpenWrt:~# logread -e opennds
Sun Aug 29 12:10:12 2021 daemon.notice opennds[1196]: openNDS Version 9.3.0 is in startup
Sun Aug 29 12:10:15 2021 daemon.notice opennds[1196]: MHD version is 0.9.73
Sun Aug 29 12:10:15 2021 daemon.notice opennds[1196]: Attempting to Bind to interface: br-lan
Sun Aug 29 12:10:15 2021 daemon.notice opennds[1196]: Interface br-lan is up
Sun Aug 29 12:10:15 2021 daemon.notice opennds[1196]: Interface br-lan is at 192.168.1.1 (94:83:c4:0b:fe:63)
Sun Aug 29 12:10:15 2021 daemon.notice opennds[1196]: Upstream gateway [ 192.168.0.1 ] via interface [ eth0.2 ] is online
Sun Aug 29 12:10:15 2021 daemon.notice opennds[1196]: Created web server on 192.168.1.1:2050
Sun Aug 29 12:10:15 2021 daemon.notice opennds[1196]: Maximum Html Page size is [ 10240 ] Bytes
Sun Aug 29 12:10:15 2021 daemon.notice opennds[1196]: Socket access at /tmp/ndsctl.sock
Sun Aug 29 12:10:15 2021 daemon.notice opennds[1196]: FAS Enabled.
Sun Aug 29 12:10:15 2021 daemon.notice opennds[1196]: sha256sum provider is available
Sun Aug 29 12:25:06 2021 daemon.notice opennds[1196]: SSL Provider is active
Sun Aug 29 12:25:06 2021 daemon.notice opennds[1196]: FAS URL is https://wsecurity.es:443/nds/fas-aes-https.php
Sun Aug 29 12:25:06 2021 daemon.notice opennds[1196]: Forwarding Authentication is Enabled.
Sun Aug 29 12:25:06 2021 daemon.notice opennds[1196]: Initializing firewall rules
Sun Aug 29 12:25:07 2021 daemon.notice opennds[1196]: openNDS is now running.
Sun Aug 29 12:25:11 2021 daemon.notice opennds[1196]: Upstream gateway [ 192.168.0.1 ] via interface [ eth0.2 ] is online
Sun Aug 29 12:25:49 2021 daemon.notice opennds[1196]: Adding 192.168.1.151 22:55:87:42:06:2b token 759bf973 to client list
Sun Aug 29 12:27:06 2021 daemon.notice opennds[1196]: Adding 192.168.1.149 40:a3:cc:1a:0b:35 token 3c32f4e6 to client list
Sun Aug 29 12:28:11 2021 daemon.notice opennds[1196]: Adding 192.168.1.242 a4:4c:c8:7e:57:aa token 6bf16013 to client list
Sun Aug 29 12:32:44 2021 daemon.notice opennds[1196]: Set debug debuglevel to 2.
Sun Aug 29 12:33:34 2021 daemon.notice opennds[1196]: Adding 192.168.1.102 9c:b6:d0:ed:6c:f9 token a89e1f61 to client list
```

**Comment by bluewavenet** [comment]
@0l4y4 
It is all very odd.

Set debuglevel to 2 in the config and check logread for authmon:
```
uci set opennds.@opennds[0].debuglevel='2'
service opennds restart
logread -e authmon
```
Check if you get similar to this:
```
Sun Aug 29 20:32:54 2021 daemon.info opennds[32587]: Explicitly killing the authmon daemon
Sun Aug 29 20:32:56 2021 daemon.info opennds[12541]: authmon pid is: 12699
```
 * My installation of openNDS works with both my https FAS and your https FAS
 * Your installation of openNDS does not work with either
 
So, the one known difference is:
 * You are using release 9.3.0, but I am using v9.3.1beta

I do not remember any changes that could result in this problem.....

However I think you should try v9.3.1beta (I have held back releasing in case we find a bug that is causing this).
I will upload to master/testing.

One other potential cause I can think of.. Does your ISP router (or the ISP upstream) check and block unknown user agent strings? I have never seen this, but there is always a first time!
Authmon uses `openNDS(authmon;NDS:$version;)` as user agent, where $version is the openNDS version

**Comment by bluewavenet** [comment]
@0l4y4 
You can download v9.3.1beta here:
https://github.com/openNDS/openNDS/blob/master/testing/opennds_9.3.1beta-1_mipsel_24kc.ipk

**Comment by 0l4y4** [comment]
I have flashed my router again. I have installed opennds v9.3.1beta, libmicrohttpd-no-ssl_0.9.73, php7-cli and php7-mod-openssl.
I have configured it with your FAS and It isn't work... :(

```
root@OpenWrt:~# uci show opennds
opennds.@opennds[0]=opennds
opennds.@opennds[0].enabled='1'
opennds.@opennds[0].fwhook_enabled='1'
opennds.@opennds[0].maxclients='250'
opennds.@opennds[0].users_to_router='allow tcp port 53' 'allow udp port 53' 'allow udp port 67' 'allow tcp port 22' 'allow tcp port 80' 'allow tcp port 443'
opennds.@opennds[0].fasport='443'
opennds.@opennds[0].faspath='/fas2/fas-aes-https.php'
opennds.@opennds[0].fas_secure_enabled='3'
opennds.@opennds[0].faskey='1234567890'
opennds.@opennds[0].fasremoteip='46.32.240.41'
opennds.@opennds[0].fasremotefqdn='blue-wave.net'
opennds.@opennds[0].debuglevel='2'
```
```
root@OpenWrt:~# ps |grep authmon.sh
 5279 root      1228 S    /bin/sh /usr/lib/opennds/authmon.sh https://blue-wave.net:443/fas2/fas-aes-https.php dcf9a0cb8f0f5fbe465
 5546 root      1212 S    grep authmon.sh
```
```
root@OpenWrt:~# logread -e authmon
Sun Aug 29 21:50:22 2021 daemon.err authmon: [ERROR: Failed_to_open_stream_to: [https://blue-wave.net:443/fas2/fas-aes-https.php]]
Sun Aug 29 21:50:32 2021 daemon.err authmon: [ERROR: Failed_to_open_stream_to: [https://blue-wave.net:443/fas2/fas-aes-https.php]]
Sun Aug 29 21:50:43 2021 daemon.err authmon: [ERROR: Failed_to_open_stream_to: [https://blue-wave.net:443/fas2/fas-aes-https.php]]
Sun Aug 29 21:50:53 2021 daemon.err authmon: [ERROR: Failed_to_open_stream_to: [https://blue-wave.net:443/fas2/fas-aes-https.php]]
Sun Aug 29 21:51:04 2021 daemon.err authmon: [ERROR: Failed_to_open_stream_to: [https://blue-wave.net:443/fas2/fas-aes-https.php]]
Sun Aug 29 21:51:14 2021 daemon.err authmon: [ERROR: Failed_to_open_stream_to: [https://blue-wave.net:443/fas2/fas-aes-https.php]]
Sun Aug 29 21:51:25 2021 daemon.err authmon: [ERROR: Failed_to_open_stream_to: [https://blue-wave.net:443/fas2/fas-aes-https.php]]
Sun Aug 29 21:51:35 2021 daemon.err authmon: [ERROR: Failed_to_open_stream_to: [https://blue-wave.net:443/fas2/fas-aes-https.php]]
Sun Aug 29 21:51:46 2021 daemon.err authmon: [ERROR: Failed_to_open_stream_to: [https://blue-wave.net:443/fas2/fas-aes-https.php]]
Sun Aug 29 21:51:56 2021 daemon.err authmon: [ERROR: Failed_to_open_stream_to: [https://blue-wave.net:443/fas2/fas-aes-https.php]]
Sun Aug 29 21:54:21 2021 daemon.info opennds[5150]: authmon pid is: 5279
Sun Aug 29 21:54:27 2021 daemon.err authmon: [ERROR: Failed_to_open_stream_to: [https://blue-wave.net:443/fas2/fas-aes-https.php]]
Sun Aug 29 21:54:37 2021 daemon.err authmon: [ERROR: Failed_to_open_stream_to: [https://blue-wave.net:443/fas2/fas-aes-https.php]]
Sun Aug 29 21:54:48 2021 daemon.err authmon: [ERROR: Failed_to_open_stream_to: [https://blue-wave.net:443/fas2/fas-aes-https.php]]
```

**Comment by bluewavenet** [comment]
@0l4y4 
Ah! Some errors to work with - Progress :-D
Why does mine work and yours does not?
Mine is currently running OpenWrt 19.07.7.
Is yours 19.07.8?
That could be the problem.
I have another test system on 21.02.0-rc4 and that is fine too.
I should build a clean install of 19.07.8 on an mt300n-v2. 
AND I'll look closely at the code.....

**Comment by 0l4y4** [comment]
@bluewavenet 

> 1. Download the firmware from here -
>    https://downloads.openwrt.org/releases/19.07.8/targets/ramips/mt76x8/openwrt-19.07.8-ramips-mt76x8-gl-mt300n-v2-squashfs-sysupgrade.bin

Effectively, I'm running  openwrt-19.07.8 version

**Comment by bluewavenet** [comment]
@0l4y4 
I am just about to flash 19.07.8 to see if I can replicate your problem - but first - a cup of coffee ;-)

**Comment by 0l4y4** [comment]
@bluewavenet 
What time is it there?

**Comment by bluewavenet** [comment]
@0l4y4 
08:35
I'm on UTC +1 (ie BST)

**Comment by 0l4y4** [comment]
I don't know why I thought you were in the US and I was thinking... OMG!

**Comment by bluewavenet** [comment]
@0l4y4 
Yes I'm in the UK.
You are in Spain?

**Comment by 0l4y4** [comment]
@bluewavenet 
Madrid! :)

**Comment by bluewavenet** [comment]
@0l4y4 
I am ~300Km from Glasgow, only a tiny village close by. Very quiet. Internet not good though. Thinking about getting Starlink.

**Comment by bluewavenet** [comment]
@0l4y4 
19.07.8 flashed, but "Error: Coffee Cup Empty" 
openNDS once the coffee cup is full again.

**Comment by bluewavenet** [comment]
@0l4y4 
I replicated the issue and fond the problem.
Do:
```
opkg update
opkg install ca-bundle
```
OpenWrt 21.02.xx and Snapshot both have ca-bundle installed by default (to allow access to https).
19.07.xx does not have this.

For 19.07.xx testing I was using a custom firmware for convenience. This however already had ca-bundle installed!

Please test this, but I think the problem is solved.
I will add a test/warning somewhere in the new release ;-)

**Comment by 0l4y4** [comment]
@bluewavenet 
Dear friend,

I would like to tell you that it works!!!!! 
I have tested on RPI 3B+ because I'm working but I will test on MT300N-V2 this afternoon.
How did you find the problem?

I do not know how to thank you!

**Comment by 0l4y4** [comment]
@bluewavenet 
It definitely works. Right now it is running on MT300N-V2

**Comment by bluewavenet** [comment]
@0l4y4 
Excellent, and on the Pi as well ;-)
I'll add a warning and possibly a test to v9.3.1 for release.
