### ISSUE TITLE
FAS Level 0 doesn't include tok in the query string

### ISSUE THREAD

**Issue by MaxFangX** [openNDS/openNDS#210]
Hi! I've been hacking on OpenNDS and am trying to get a level 0 security auth flow working in combination with a webserver running on the router.

I've tried two approaches to this:

### Approach 1: Default config, FAS disabled, just run the webserver on the router

I spun up a basic PHP webserver using the steps below:
```bash
# Install server prerequisites
opkg update
opkg install php7-cli php7-cgi

# Create php web root and enter it
cd /root
mkdir -p php
cd php

# Create basic file
cat index.html
<html>
  <head></head>
  <body>
    <h3>PHP webserver is working</h3>
  </body>
</html>

# Start the PHP webserver at port 2080
php-cli -S 0.0.0.0:2080
```

However, the webserver is not reachable unless I add the following to my config, which also enables FAS:
```bash
# Configure
uci set opennds.@opennds[0].fasport='2080'
service opennds restart

# Webserver is now accessible at 192.168.2.1:2080
```

If I remove `fasport='2080'` from my config, the webserver is no longer accessible from my device connected to the network. This is true regardless of whether the user is authenticated or not.
```bash
uci delete opennds.@opennds[0].fasport
service opennds restart
```

So, I proceeded to see if I could make the auth flow work with a level 0 FAS.

### Approach 2: Serve the splash page containing `tok` from the Level 0 FAS

Since I managed to at least get a webserver running and accessible on the router, I figured the webserver could serve the splash page and accept `tok` in the query string so that the user can include it in their GET request to `/opennds_auth` when they click "Continue". The ["Example FAS Query strings"](https://opennds.readthedocs.io/en/stable/fas.html#example-fas-query-strings) section in the docs mentions that `tok` is included in the string, but this is the cURL of the request the user makes to my FAS when preauthenticated:

```bash
curl 'http://192.168.2.1:2080/?clientip=192.168.2.150&gatewayname=OpenWrt%20openNDS&redir=http%3a%2f%2f192.168.2.1%2f' \
  -H 'Connection: keep-alive' \
  -H 'Upgrade-Insecure-Requests: 1' \
  -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.114 Safari/537.36' \
  -H 'Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9' \
  -H 'Sec-GPC: 1' \
  -H 'Accept-Language: en-US,en;q=0.9' \
  --compressed \
  --insecure
```

As you can see it includes query parameters `clientip`, `gatewayname`, and `redir`, but no `tok`.

How can I receive `tok` in the query string, or how can I allow the user to authenticate with the other information available to the `FAS`?

### Full config

Here's the full output of `uci show opennds` - perhaps there is something wrong with the rest of the config?
```text
opennds.@opennds[0]=opennds
opennds.@opennds[0].enabled='1'
opennds.@opennds[0].fwhook_enabled='1'
opennds.@opennds[0].login_option_enabled='0'
opennds.@opennds[0].use_outdated_mhd='1'
opennds.@opennds[0].unescape_callback_enabled='0'
opennds.@opennds[0].gatewayinterface='br-lan'
opennds.@opennds[0].gatewayname='OpenWrt openNDS'
opennds.@opennds[0].maxclients='250'
opennds.@opennds[0].preauthidletimeout='30'
opennds.@opennds[0].authidletimeout='120'
opennds.@opennds[0].checkinterval='60'
opennds.@opennds[0].uploadrate='0'
opennds.@opennds[0].downloadrate='0'
opennds.@opennds[0].ratecheckwindow='2'
opennds.@opennds[0].uploadquota='0'
opennds.@opennds[0].downloadquota='0'
opennds.@opennds[0].authenticated_users='allow all'
opennds.@opennds[0].users_to_router='allow tcp port 53' 'allow udp port 53' 'allow udp port 67' 'allow tcp port 22' 'allow tcp port 23' 'allow tcp port 80' 'allow tcp port 443'
opennds.@opennds[0].sessiontimeout='0'
opennds.@opennds[0].webroot='/root/frontend/build'
opennds.@opennds[0].fasport='2080'
```

I am running OpenNDS 5.2.0.

### Notes

One possible workaround is that when the FAS receives a level 0 query string, it can call `ndsctl status`, parse for the client whose IP matches `clientip`, grab the associated `Token`, then render that in the html so the user can include it in their `GET` request to `/opennds_auth`. But this feels like it is way more complicated than it is supposed to be - implementing a Level 1 FAS would probably be easier. Would appreciate any insight into this issue.

**Comment by MaxFangX** [comment]
**Update:** I was able to get Approach 1 working with:
```bash
uci delete opennds.@opennds[0].fasport
uci add_list opennds.@opennds[0].users_to_router='allow tcp port 2080'
```

I'll leave this issue open so you can have track it in case the lack of `tok` in the query string is an actual bug, otherwise feel free to close 🎉

**Comment by bluewavenet** [comment]
@MaxFangX 

> I am running OpenNDS 5.2.0.

The current release is v9.3.0. with v9.3.1 coming very soon.

I am assuming you are running on OpenWrt 19.07.x, where openNDS version 5.2.0 is the default.
You can download openNDS from the OpenWrt 21.03 packages repository along with the required updated version of MHD (libmicrohttpd). Both of these can be run on OpenWrt 19.07.xx.

It is not possible, without a lot of work, to backport 9.x.x to OpenWrt 19.07.xx, as the MHD API has changed.
I strongly suggest you upgrade to the latest version before continuing as 5.2.0 is very outdated.

> I've been hacking on OpenNDS and am trying to get a level 0 security auth flow working in combination with a webserver running on the router.

"level 0" or its full name "fas_secure_enabled", is a FAS configuration

> Approach 1: Default config, FAS disabled, just run the webserver on the router

openNDS already runs its own webserver. Enable the splash page by setting login_option_enabled to 1
It makes no sense to disable FAS, in fact in later versions FAS is always enabled. 

> Approach 2: Serve the splash page containing tok from the Level 0 FAS
> ...
> ...
> As you can see it includes query parameters clientip, gatewayname, and redir, but no tok.

In all versions tok is included at level 0 but anyone can very simply bypass openNDS.
From v9.3.1 onwards, level 0 is deprecated and will eventually be removed.
Perhaps you found a bug in 5.x.x... It will not be fixed as it is so old and outdated.

> How can I receive tok in the query string

Upgrade to v9.3.0, it works there.

> Update: I was able to get Approach 1 working with:
> ..
> uci add_list opennds.@opennds[0].users_to_router='allow tcp port 2080'

Yes, congratulations, you manually configured what enabling FAS does automatically.

I would suggest that before "hacking", it would be sensible to read the documentation:
https://opennds.readthedocs.io

**Comment by MaxFangX** [comment]
Ah, using such an old version explains it... I've spent a lot of time reading the docs but have had a lot of trouble getting things to work.

Will update to OpenWrt 21.03 and openNDS 9.x.x, thanks for the quick response.

**Comment by bluewavenet** [comment]
You do not have to reflash to 21.03, just download openNDS and MHD from 21.03 packages repository.
