### ISSUE TITLE
Is there a gateway heartbeat report like wifidog?

### ISSUE THREAD

**Issue by Scyllaly** [openNDS/openNDS#213]
Hi
By reading the document, I didn't find that there was a request (task) for the gateway to report the heartbeat in FAS when FAS deployed on a remote server.

I want to monitor whether the gateway is online and how long it is online. When offline, I can send an email alarm to inform the administrator

**Comment by bluewavenet** [comment]
@Scyllaly 
There is no specific heartbeat, however:
At level 3, the authmon daemon polls the remote FAS with a post-request(view), at a rate determined by loopinterval (default 10 seconds).
It would be a simple matter for the FAS to log the time each poll is received and take action as appropriate.

In a commercial or corporate environment where a single remote FAS handles multiple openNDS venues, level 3 will usually be implemented. This type of environment is also the type that requires "admin" alarms to facilitate proactive support.

Levels less than than 3 are either for stand alone captive portals, or for external FAS working with openNDS installed on resource limited legacy hardware.

**Comment by Scyllaly** [comment]
got it ! THX!
it's so kind of you
