### ISSUE TITLE
missing default params in fas_secure_enable mode 1

### ISSUE THREAD

**Issue by Scyllaly** [openNDS/openNDS#214]
When i tested in different `fas_secure_enable` mode , 
I found some different default params, i am not sure it is missing or not. (I have been read the document. 😢 )

##### `fas_secure_enable`  mode
-  `0` 
```
http://192.168.1.1:2050/opennds_auth/?clientip=192.168.1.220
&gatewayname=openNDS
&tok=ed347edb
&redir=http%3a%2f%2fwww.msftconnecttest.com%2fredirect
```

- `1` (base64 decode)
```
hid=889b02e7cc28165abf0fd0fee0793e90179303b5532045a4cbdbf289da290eb9
&clientip=192.168.1.220
&clientmac=74:12:b3:2a:46:ad
&gatewayname=openNDS
&version=9.3.0
&gatewayaddress=192.168.1.1:2050
&gatewaymac=00:f1:f3:1a:c2:76
&originurl=http%3a%2f%2fwww.msftconnecttest.com%2fredirect
&clientif=br-lan
&themespec=(null)&(null)(null)(null)(null)
```

- `2` (openssl decrypted)
```
hid=2b3f665199dd954b7e8c830d264c180216bcda78704937d4c796a7badc4c7531
&clientip=192.168.1.220
&clientmac=74:12:b3:2a:46:ad
&gatewayname=openNDS
&version=9.3.0
&gatewayaddress=192.168.1.1:2050
&gatewaymac=00:f1:f3:1a:c2:76
&authdir=opennds_auth
&originurl=http%3a%2f%2fwww.msftconnecttest.com%2fredirect
&clientif=br-lan
&themespec=(null)&(null)(null)(null)(null)
```

- `3` (openssl decrypted)
```
hid=10dd0acc584b83bcf0e8f7e570ce098785053cd311f939d1b7e3825020525fe7
&clientip=192.168.1.220
&clientmac=74:12:b3:2a:46:ad
&gatewayname=openNDS
&version=9.3.0
&gatewayaddress=192.168.1.1:2050
&gatewaymac=00:f1:f3:1a:c2:76
&authdir=opennds_auth
&originurl=http%3a%2f%2fedge.microsoft.com%2fcaptiveportal%2fgenerate_204
&clientif=br-lan
&themespec=(null)&(null)(null)(null)(null)
```

- Question 1: Can the parameters be consistent, such as those under mode 0
- Question 2: under mode 0, it seems lost params `authdir`
- Question 3: under mode 1 & 2 & 3, can set the params `themespec` to be `null` (i think it should not be empty, because when ...build url ...empty params wont be build in)
- Question 4: after params `themespec`, you can see `&(null)(null)(null)(null)`, i guess it must be some params???

Be grateful @_@

**Comment by bluewavenet** [comment]
@Scyllaly 

> Question 1: Can the parameters be consistent, such as those under mode 0

No. The levels are all different. Level 0 is very insecure and allows the captive portal to be bypassed with very little effort. Level 0 is also deprecated and will be removed in future versions. No fixes will be made to Level 0 if problems are found.

> Question 2: under mode 0, it seems lost params authdir

This made it slightly more difficult to bypass the captive portal. However Level 0 is deprecated.

> Question 3: under mode 1 & 2 & 3, can set the params themespec to be null (i think it should not be empty, because when ...build url ...empty params wont be build in)

Themespec only applies if option login_option_enabled is > 0, which overrides any FAS settings and uses the openNDS built in web server for a stand alone captive portal.
If login_option_enabled = 0, then any Themespec options are ignored. External FAS support for Themespec may be added in the future.

> Question 4: after params themespec, you can see &(null)(null)(null)(null)

External FAS support for Themespec may be added in the future.

**Comment by Scyllaly** [comment]
@bluewavenet 

Sorry , i type wrong word.

Question 2: under mode 1, it seems lost params `authdir` (not mode 0)

**Comment by bluewavenet** [comment]
@Scyllaly 
A quick summary:
 * Level 3 does not use authdir, so it could actually be removed. 
 * The level 2 query string is encrypted so authdir can be safely passed.
 * The level 1 query string is not encrypted so authdir could be discovered, making attempts to bypass a little easier, so it is not included.
Authdir is currently hard coded in the level 1 fas-hid.php example.

**Comment by bluewavenet** [comment]
@Scyllaly 

> Where i can set the authdir value in config? 

This was deprecated some considerable time ago and has since been removed.

**Comment by bluewavenet** [comment]
@Scyllaly 

> maybe the authdir can append to param gatewayaddress

No. You would use fas_custom_parameters_list
See:
https://opennds.readthedocs.io/en/stable/customparams.html#custom-parameters

**Comment by Scyllaly** [comment]
thx!!!! i got it!
kind of u
