### ISSUE TITLE
Wrong usage of pthread_kill() -> should be pthread_cancel() instead

### ISSUE THREAD

**Issue by T-X** [openNDS/openNDS#216]
I sometimes run into the issue that termination_handler() is not running until the 'debug(LOG_NOTICE, "Exiting...");' and instead I get a line "Killed" on the console. Seemingly right after the 'pthread_kill(tid_client_check, SIGKILL);'. If I add a "sleep(5)" right after the pthread_kill() I can enforce the too early "Killed" termination.

Man pthread_kill() says:

> Signal dispositions are process-wide: if a signal handler is installed, the handler will be invoked in the thread _thread_, but if the disposition of the signal is "stop", "continue", or "terminate", this action will affect the whole process.

So it seems to me that there is a race condition: The client_check script will receive the SIGKILL but the thread will then not just kill itself - instead it kill the whole process. And sometimes we are lucky, that the thread is not handling SIGKILL fast enough and that termination_handler() is able to finish before this.

What should be used instead is pthread_cancel(), it seems. With a subsequent pthread_join() to wait for its cancellation to finish.

**Comment by T-X** [comment]
Btw. I also checked if removing the 'sa.sa_flags = SA_RESTART;' (and adding a memset to zero sa first) did not seem to make a difference the pthread_kill() behaviour.

And it might make sense to consider adding a 'memset(sa, 0, sizeof(sa))' before using it, as sa.sigaction and sa.sa_restorer might be left uninitialized on some architectures. Currently seems okay with sigaction() here, but always makes me a bit nervous and its unsafe if "struct sigaction" were extended at some point.

All this was tested on OpenWrt 19.07 in an x86 VM, with openNDS linked to musl 1.1.24.

**Comment by bluewavenet** [comment]
@T-X 
This bit of code dates back to who_knows_when in the original NoDogSplash code or even earlier, as far as I can see.

> 	/* XXX Hack
> 	 * Aparently pthread_cond_timedwait under openwrt prevents signals (and therefore
> 	 * termination handler) from happening so we need to explicitly kill the threads
> 	 * that use that
> 	 */
> 

Does this even still apply? Do we need to do the pthread_kill/cancel?

**Comment by T-X** [comment]
Hi, seems you're right. Neither the client_check thread nor the ndsctl thread have registered any signal handler for themselves as far as I can tell. So they wouldn't do any cleanup on their own when receiving a pthread_kill() or pthread_cancel().

I removed the pthread_kill() in termination_handler() in my tests and the termination_handler() seems to be called and exit just fine on OpenWrt 19.07 with musl 1.1.24. So that approach sounds good to me too!

**Comment by T-X** [comment]
I'm also wondering if the pthread_cond_timedwai() is really needed in thread_client_timeout_check(). According to here:

https://www.man7.org/linux/man-pages/man3/sleep.3.html

> sleep() causes the calling **thread** to sleep

So generally it should be thread safe. With a small exception for SIGCHLD on Linux according to the manpage. But not sure at the moment if that would be relevant for openNDS.

**Comment by bluewavenet** [comment]
@T-X 
I've taken out the pthread_kill(), generally tidied up and tested. All good.
This will be incorporated into the next release (looks like it will be v9.4.0)

**Comment by bluewavenet** [comment]
@T-X 
Thanks!
