### ISSUE TITLE
Encrypted information

### ISSUE THREAD

**Issue by 0l4y4** [openNDS/openNDS#217]
Hi!

Once users authenticate and access the internet, does opennds encrypt the communications in any way?

**Comment by Scyllaly** [comment]
it depends on your config option `fas_secure_enable` 's value.
actually , i can't fully understand what you mean, u means opennds commuicate to remote server ?

**Comment by 0l4y4** [comment]
@Scyllaly 
I want to mean when I have authenticated, could I monitor LAN network traffic or is it encrypted? or denied by firewall rules

**Comment by bluewavenet** [comment]
@0l4y4 

> Once users authenticate and access the internet, does opennds encrypt the communications in any way?

Once a user is authenticated, openNDS is no longer involved in client to Internet communications.
So the answer to your question is "No" ;o)

> could I monitor LAN network traffic?

openNDS already monitors the quantity and rates of data usage by individual clients.

As a client user you can look at the `http://status.client` page.

As an administrator, the output of `ndsctl status` gives you the information for all clients.

If you want to monitor remotely, you will have to implement some form of VPN tunnel to get to it.

If you want to view what clients are accessing, or even monitor their actual data, this is illegal in most countries eg in EU see GDPR

**Comment by 0l4y4** [comment]
@bluewavenet 
Ok but if I have 2 devices authenticated (smartphone and laptop) could I attack my smartphone from my laptop?

**Comment by bluewavenet** [comment]
@0l4y4 

> if I have 2 devices authenticated (smartphone and laptop) could I attack my smartphone from my laptop?

Yes, you could, but Apple and Android smart devices are very resilient. Most likely, the worst you could do is a denial of service attack and that would bung up the wireless for everyone 8-]

Now that `authenticated_users passthrough` is fixed, you can use the OpenWrt firewall to isolate clients.
However, in my experience, local client to client attacks are very rare, in fact I have never been aware of one.

Conversely, client to client communications are very common, particularly where business guests at hotels are concerned - Dropbox and SyncThing fast local file sync being very common. And of course there is gaming....

**Comment by bluewavenet** [comment]
@0l4y4 
Reopen if you need to ;-)
