### ISSUE TITLE
About fas-aes-https Questions

### ISSUE THREAD

**Issue by Scyllaly** [openNDS/openNDS#219]
#### opennds config
```
root@OpenWrt:~# uci show opennds
opennds.@opennds[0]=opennds
opennds.@opennds[0].enabled='1'
opennds.@opennds[0].fwhook_enabled='1'
opennds.@opennds[0].login_option_enabled='0'
opennds.@opennds[0].gatewayfqdn='status.client'
opennds.@opennds[0].maxclients='250'
opennds.@opennds[0].preauthidletimeout='10'
opennds.@opennds[0].authidletimeout='15'
opennds.@opennds[0].sessiontimeout='10'
opennds.@opennds[0].binauth='/usr/lib/opennds/binauth_log.sh'
opennds.@opennds[0].fasport='443'
opennds.@opennds[0].fasremotefqdn='opennds.lan'
opennds.@opennds[0].fasremoteip='159.xxx.xxx.xxx'
opennds.@opennds[0].faspath='/fas-aes-https.php'
opennds.@opennds[0].faskey='1234567890'
opennds.@opennds[0].fas_secure_enabled='3'
opennds.@opennds[0].users_to_router='allow tcp port 53' 'allow udp port 53' 'allow udp port 67' 'allow tcp port 22' 'allow tcp port 80' 'allow tcp port 443'
```

#### Questions
1. I try to connect to openwrt by my pc, i found that authmon will send post `($_POST['auth_get'] == 'view')`
```
* 7084394cf723e57173ee7ec818f1f872ab7235693fc954085114ecd9908532a5%200%200%200%200%200%20Optional%2520Custom%2520data%2520for%2520BinAuth
```
Can u explain what is that means , esp `%200%200%200%200%200%20Optional%2520Custom%2520data%2520for%2520BinAuth`

and it will send the post data as the same time like this:
```
  'auth_get' => 'view',
  'gatewayhash' => 'dcf9a0cb8f0f5fbe46548fb485ff3df4ac26dbce994e128a56dd96496eab9b7f',
  'payload' => 'KiA3MDg0Mzk0Y2Y3MjNlNTcxNzNlZTdlYzgxOGYxZjg3MmFiNzIzNTY5M2ZjOTU0MDg1MTE0ZWNkOTkwODUzMmE1',
)
```

when i decode the `payload` by `base64decode`, i get the text `* 7084394cf723e57173ee7ec818f1f872ab7235693fc954085114ecd9908532a5`

I dont know what is the text `7084394cf723e57173ee7ec818f1f872ab7235693fc954085114ecd9908532a5`, client hash??
can i identity which device by this text?? how can i ?

**Comment by Scyllaly** [comment]
Question 3:  in `fas-aes-https.php`  line 156 (if ($_POST["auth_get"] == "clear") ) , how can i occur `clear` status 
Question 3:  in `fas-aes-https.php`  line 171 (if ($_POST["auth_get"] == "list") ) , how can i occur `list` status

**Comment by bluewavenet** [comment]
@Scyllaly 
`7084394cf723e57173ee7ec818f1f872ab7235693fc954085114ecd9908532a5` is the client rhid.
The client rhid is constructed using the pre-shared key and is what openNDS uses to authenticate the client (with its own knowledge of the pre shared key).

`%200%200%200%200%200%20Optional%2520Custom%2520data%2520for%2520BinAuth`

This is the raw html entity encoded authentication string for openNDS. Decoded it reads:
`0 0 0 0 0` followed by a custom string to be sent to BinAuth for local post authentication processing, typically local logging.
Refer to fas-aes-https.php, function **authenticate_page()**

> can i identity which device by this text?? how can i ?

Client details are stored in the FAS log - see fas-aes-https.php **function write_log()**

> Question 2: in fas-aes-https.php line 156 (if ($_POST["auth_get"] == "clear") ) , how can i occur clear status

Restart openNDS.

>  Question 3: in fas-aes-https.php line 171 (if ($_POST["auth_get"] == "list") ) , how can i occur list status

You cannot. This is redundant code from earlier versions. It has been retained for possible future use.

**Comment by Scyllaly** [comment]
@bluewavenet I got it . Thank u .
More questions:
Question 4: in fas-aes-https.php line 205 `$authlist=$authlist." ".rawurlencode(trim($clientauth[0]));`
Such data is obtained through the breakpoint. It seems that authmon does not authenticate(the text `[auth_get]-view-none:` is identification mark)：
```
[auth_get]-view-none:* 055d8a01fd4a04a63040f49e6ac3594848c8b81b2bf5641fd65b00003d181bd4%200%200%200%200%200 996b8a1c21448bdfb2ad84e9389de2a99a7e3c1c5773becf70acf17d88b2a391%200%200%200%200%200
```

There is my php code
```
case 'view': // Client auth process
                    if ($acklist != "none") { // device auth
                        $acklist_r = explode("\n", $acklist); // mutli device identity by \n
                        foreach ($acklist_r as $client) {
                            $client = ltrim($client, "* ");
                            if ($client != "") {
                                if (file_exists(storage_path('logs/' . "$gatewayhash/$client"))) {
                                    unlink(storage_path('logs/' . "$gatewayhash/$client"));
                                }
                            }
                        }

                        info('auth_get-view:' . var_export($acklist_r, true));

                        return response()->make('ack');
                    } else { // get devices which wait for auth 
                        $auth_list = scandir(storage_path('logs/' . $gatewayhash));
                        array_shift($auth_list); // remove .
                        array_shift($auth_list); // remove ..
                        foreach ($auth_list as $client) {
                            $clientauth = file(storage_path('logs/' . "$gatewayhash/$client"));
                            $authlist = $authlist . " " . rawurlencode(trim($clientauth[0])); // contact the data to authmon
                        }

                        info('auth_get-view-none:' . trim("$authlist"));

                        return response()->make(trim("$authlist"));
                    }
```

**Comment by bluewavenet** [comment]
@Scyllaly 

> Such data is obtained through the breakpoint.

What is the breakpoint? I don't know what you mean.

> in fas-aes-https.php line 205 $authlist=$authlist." ".rawurlencode(trim($clientauth[0]));

This is building the authlist from the FAS database of verified and waiting clients. This is then sent to authmon for authentication processing.
