### ISSUE TITLE
Monitor customer traffic

### ISSUE THREAD

**Issue by 0l4y4** [openNDS/openNDS#221]
Hi!
Does openNDS have an option to monitor customer traffic? 

In case the answer is no, do you recommend any tools?

Thanks

**Comment by bluewavenet** [comment]
@0l4y4 
openNDS monitors traffic volumes and data rates for every client but nothing else. This is what is preferred for a trusted captive portal.
However some clients may abuse the system. OpenWrt Luci provides useful real time monitoring of traffic.
Login to Luci and select Status/Real Time Graphs/Connections then click the Enable DNS Lookups.
Scroll down and view traffic types with source and destination.

**Comment by bluewavenet** [comment]
@0l4y4 
On OpenWrt 19.xx you must install ssl support for Luci:
```
opkg update
opkg install luci-ssl
service uhttpd restart
```
Luci will then be available at https://[gatewayfqdn]
eg https://status.client https://login.page etc

**Comment by 0l4y4** [comment]
But if you wanted to go one step further and monitor:
```
- The pages visited;
- Connection sessions;
- The device used for the connection;
- Language;
- The operating system;
- The browser that was used.
```

**Comment by bluewavenet** [comment]
@0l4y4 

> - The device used for the connection;
> - The operating system;
> - The browser that was used.
> 

See mac and user-agent in the FAS logs...

Luci (using command line tools), will give you sites visited and connections.

Pages visited takes you very much into the realm of GDPR/Privacy violations unless you are very careful.
