### ISSUE TITLE
Debian builds

### ISSUE THREAD

**Issue by MarkVallevand** [openNDS/openNDS#222]
Will debian builds be fixed?

**Comment by bluewavenet** [comment]
@MarkVallevand 
Debian builds were broken in NoDogSplash at the time of the split and the broken remains were removed from openNDS.
The main focus is OpenWrt, so for generic Linux compiling in place works well and is tested on Debian and OpenSuse.
Feel free to submit a PR if you would like to reinstate it.

**Comment by MarkVallevand** [comment]
Debian builds work for me in NDS.  With a little effort, I forced a debian build for openNDS, but it’s ugly.  The openNDS build in-place for Ubuntu 18 works.  But, with the focus on OpenWRT, I suspect that some things won’t work.  Looking at the code, the Walled Garden feature is something that might not work in plain old Linux.  

 

Mark K Vallevand

Unisys | 651-635-7708 | ***@***.*** ***@***.***>  

 

 <http://www.unisys.com/> 

 

THIS COMMUNICATION MAY CONTAIN CONFIDENTIAL AND/OR OTHERWISE PROPRIETARY MATERIAL and is for use only by the intended recipient. If you received this in error, please contact the sender and delete the e-mail and its attachments from all devices.

 <http://www.linkedin.com/company/unisys>    <http://twitter.com/unisyscorp>   <http://www.youtube.com/theunisyschannel>  <http://www.facebook.com/unisyscorp>  <https://vimeo.com/unisys>  <http://blogs.unisys.com/> 

 

Outside of a dog, a book is man’s best friend.

Inside of a dog, it’s too dark to read.

-           Groucho

**Comment by bluewavenet** [comment]
@MarkVallevand 

> plain old Linux.

Depends on what you mean.

I personally run testing on OpenSuse, currently Leap 15.3 and never had problems. Walled garden no problem either ( dnsmasq is a prerequisite).  One production system on a Dell blade running OpenSuse Leap 15.2
I also test on various flavours of Debian in the run up to a release. All are compiled in place of course and I have not found anything that does not work so far.

**Comment by MarkVallevand** [comment]
We use dnsmasq in a different way.  It looks like one of the scripts is looking for /etc/dnsmasq.conf and on our system it won’t be there.

 

But, I haven’t tried it, so I might be wrong.

 

Mark K Vallevand

Unisys | 651-635-7708 | ***@***.*** ***@***.***>  

 

 <http://www.unisys.com/> 

 

THIS COMMUNICATION MAY CONTAIN CONFIDENTIAL AND/OR OTHERWISE PROPRIETARY MATERIAL and is for use only by the intended recipient. If you received this in error, please contact the sender and delete the e-mail and its attachments from all devices.

 <http://www.linkedin.com/company/unisys>    <http://twitter.com/unisyscorp>   <http://www.youtube.com/theunisyschannel>  <http://www.facebook.com/unisyscorp>  <https://vimeo.com/unisys>  <http://blogs.unisys.com/> 

 

Outside of a dog, a book is man’s best friend.

Inside of a dog, it’s too dark to read.

-           Groucho

**Comment by bluewavenet** [comment]
@MarkVallevand 
The configuration of dnsmasq is done by a library script. You can edit the dnsmasq.conf location.

PS Replying by email seems to be making quite a mess!
