### ISSUE TITLE
Remote connection

### ISSUE THREAD

**Issue by 0l4y4** [openNDS/openNDS#223]
Hi,

Have you contemplated remote administration of openNDS in any way?

Thanks

**Comment by openwrtdiy** [comment]
The remote management function is suitable for the unified management and distribution of configuration parameters of wireless APs in multiple areas. The terminal real-time connection information of each AP can be displayed in real time.

**Comment by bluewavenet** [comment]
@openwrtdiy 
What is "The remote management function" ?
Not official OpenWrt as far as I can see, in fact I can't find it anywhere.

**Comment by bluewavenet** [comment]
@0l4y4 

> Have you contemplated remote administration of openNDS in any way?

Briefly, but then I stopped contemplating :-D

You can do everything if you can ssh to your router. You either need a fixed ip address or a site to site VPN
