### ISSUE TITLE
How can FAS know client session timeout(FAS level 3)?

### ISSUE THREAD

**Issue by Scyllaly** [openNDS/openNDS#224]
I set the config `sessiontimeout`  , when client's session time out, client will remove from auth list by `ndsctl status`, the authmon not post some data to tell FAS the client has been kick out.

**Comment by bluewavenet** [comment]
@Scyllaly 
From the default config file:
```
	# Session Timeout is the interval after which clients are forced out (a value of 0 means never)
	# Clients will be deauthenticated at the end of this period
	# Default 1200 minutes (20 hours)
	# Example: Set to 24 hours (1440 minutes)
	#option sessiontimeout '1440'
```

> the authmon not post some data to tell FAS the client has been kick out.

Why does FAS need to know? Once the client is authenticated, FAS is no longer involved.
Informing FAS when  a client times out serves no purpose.
FAS is the Forwarding Authentication Service. It is not a Client Monitoring Service.

Note also that a client could be deauthed by sessiontimeout, authidletimeout or by exceeding its Volume quota.

If you really want to inform FAS when a client is deauthenticated, you could make a binauth script send deauth information to the remote FAS server to do your Client Monitoring.
