### ISSUE TITLE
It seems that startup script have some wrong???

### ISSUE THREAD

**Issue by Scyllaly** [openNDS/openNDS#226]
By i read the script : `/etc/init.d/opennds` , i found it still use some `Not recommand` config (wifidog config style).

`/etc/config/opennds` : LINE 738
```
list trustedmac '00:00:C0:01:D0:1D'
```

`/etc/init.d/opennds`: LINE 63
```
addline "TrustedMACList $macs"
```

so, my question is: config tag `TrustedMACList` (wifidog style) still work??

❓

**Comment by Scyllaly** [comment]
confuse me 😕

**Comment by bluewavenet** [comment]
@Scyllaly 

> By i read the script : /etc/init.d/opennds , i found it still use some Not recomm[e]nd 

Who does not recommend?

> wifidog config style

openNDS has nothing to do with Wifidog. They both share common origins dating back nearly 20 years, but that is as far as it goes. Any slight similarity between the two is just that, a slight similarity.

> `list trustedmac '00:00:C0:01:D0:1D'`

Yes that will work. It is primarily intended for use with NON-client devices, ie PoS terminals, card readers, IoT devices etc.
Most up to date client devices (eg Android, Apple) regularly change mac address, so any "trustedmac" configuration for a client device will most likely be short lived in its effectiveness. 

> confuse me 

LOL :D

**Comment by Scyllaly** [comment]
i means about this:
`list trustedmac '00:00:C0:01:D0:1D'` ---> it works
`TrustedMACList 00:00:C0:01:D0:1D,00:00:C0:01:D0:1D,00:00:C0:01:D0:1D`. ---> it works too??

**Comment by bluewavenet** [comment]
@Scyllaly 

> TrustedMACList 00:00:C0:01:D0:1D,00:00:C0:01:D0:1D,00:00:C0:01:D0:1D. ---> it works too??

The old NoDogSplash style .conf file is deprecated and disabled even if present. So manually setting TrustedMACList is not valid.
