### ISSUE TITLE
what about the startup script from line 134 to line 139

### ISSUE THREAD

**Issue by Scyllaly** [openNDS/openNDS#227]
```
config_get download "$cfg" downloadlimit
  config_get upload "$cfg" uploadlimit

  if [ -n "$upload" -o -n "$download" ]; then
    addline "TrafficControl yes"
  fi
```

i can not find the config params `downloadlimit` & `uploadlimit` & `TrafficControl` in `/etc/config/opennds`

**Comment by bluewavenet** [comment]
@Scyllaly 
TrafficControl is deprecated in openNDS and replaced by rate and volume quotas.
The lines you have pointed out in the init.d file are redundant, but have been kept for now for possible future integration with SQM scripts.

Perhaps the lines should be removed if they are confusing ;-)
