### ISSUE TITLE
account login

### ISSUE THREAD

**Issue by 25khattab** [openNDS/openNDS#240]
I want to make something like the Username/Emailaddress Dynamic Login but with email and password 
but I have no idea how to it and where does the data goes and I'm having difficulty to do any thing regard I'm computer science student so I need your help please if u have time so I can access internet only with accounts 

router : archer c7 v5
openWRT : 21.02
opennds (9.4.0)

**Comment by bluewavenet** [comment]
@25khattab 
Please state:
1. Router hardware
2. Router operating system and version
3. Version of openNDS

Also I recommend in depth reading of the documentation:
https://opennds.readthedocs.io/

**Comment by 25khattab** [comment]
1- ARCHER c7 v5
2- openWRT 21.02
3- latest version

**Comment by 25khattab** [comment]
I think I have a bigger problem now when i try to enable opennds the portal doesnot appear at all and iam stuck with no internet

**Comment by bluewavenet** [comment]
@25khattab 
Please show the output of:
`ndsctl status`

**Comment by 25khattab** [comment]
@bluewavenet 

> ==================
openNDS Status
====
Version: 9.4.0
Uptime: 4s
Gateway Name: [ openNDS ]
Debug Level: [ 1 ]
Gateway FQDN: [ status.client ]
Managed interface: br-lan
Upstream gateway [ 197.52.0.1 ] via interface [ pppoe-wan ] is online
MHD Server [ version 0.9.71 ] listening on: http://192.168.1.1:2050
Maximum Html Page size is [ 10240 ] Bytes
Preemptive Authentication is Disabled
Binauth: Disabled
Preauth Script: /usr/lib/opennds/libopennds.sh
FAS: Secure Level 1, URL: http://192.168.1.1:2050/opennds_preauth/
Client Check Interval: 60s
Rate Check Window: 2 check intervals (120s)
Preauthenticated Client Idle Timeout: 30m
Authenticated Client Idle Timeout: 120m
Download rate limit (default per client): no limit
Upload rate limit (default per client): no limit
Download quota (default per client): no limit
Upload quota (default per client): no limit
Total download: 14 kByte; avg: 29.83 kbit/s
Total upload: 16 kByte; avg: 33.06 kbit/s
====
Client authentications since start: 0
Current clients: 0
====
Blocked MAC addresses: none
Allowed MAC addresses: N/A
Trusted MAC addresses: none
Walled Garden FQDNs: none
Walled Garden Ports: none
========

**Comment by 25khattab** [comment]
@bluewavenet I Had to vistit 192.168.1.1 to be able to get access

**Comment by bluewavenet** [comment]
@25khattab 
What do you get if you browse to `http://status.client`  ?

**Comment by bluewavenet** [comment]
@25khattab 
Show the output of:
`uci show opennds`

**Comment by 25khattab** [comment]
this what happen when i visit `http://status.client`
![Screenshot (269)](https://user-images.githubusercontent.com/53271078/134787272-2fbdbf9d-5887-4dfc-9770-63dbbaaf4360.png)

and this when i run `uci show opennds`

![Screenshot (270)](https://user-images.githubusercontent.com/53271078/134787294-1f893b19-fcd8-4441-825e-6fcc3d9d15c2.png)

**Comment by bluewavenet** [comment]
@25khattab 
Do:
`uci set opennds.@opennds[0].debuglevel='2'`
`service opennds restart`

Then show the output of:
`logread -e opennds`

**Comment by 25khattab** [comment]
@bluewavenet 

> Sat Sep 25 20:30:00 2021 daemon.notice opennds[7833]: openNDS Version 9.4.0 is in startup                                                                                                              Sat Sep 25 20:30:01 2021 daemon.notice opennds[7833]: MHD version is 0.9.71                                                                                                                            Sat Sep 25 20:30:01 2021 daemon.notice opennds[7833]: Attempting to Bind to interface: br-lan                                                                                                          Sat Sep 25 20:30:01 2021 daemon.notice opennds[7833]: Interface br-lan is up                                                                                                                           Sat Sep 25 20:30:01 2021 daemon.notice opennds[7833]: Interface br-lan is at 192.168.1.1 (90:9a:4a:96:96:2c)                                                                                           Sat Sep 25 20:30:01 2021 daemon.notice opennds[7833]: Upstream gateway [ 197.52.0.1 ] via interface [ pppoe-wan ] is online                                                                            Sat Sep 25 20:30:01 2021 daemon.notice opennds[7833]: Created web server on 192.168.1.1:2050                                                                                                           Sat Sep 25 20:30:01 2021 daemon.notice opennds[7833]: Maximum Html Page size is [ 10240 ] Bytes                                                                                                        Sat Sep 25 20:30:01 2021 daemon.notice opennds[7833]: Socket access at /tmp/ndsctl.sock                                                                                                                Sat Sep 25 20:30:01 2021 daemon.notice opennds[7833]: Click to Continue option is Enabled.                                                                                                             Sat Sep 25 20:30:01 2021 daemon.notice opennds[7833]: Preauth is Enabled - Overiding FAS configuration.                                                                                                Sat Sep 25 20:30:01 2021 daemon.notice opennds[7833]: sha256sum provider is available                                                                                                                  Sat Sep 25 20:30:01 2021 daemon.notice opennds[7833]: FAS URL is http://192.168.1.1:2050/opennds_preauth/                                                                                              Sat Sep 25 20:30:01 2021 daemon.notice opennds[7833]: Forwarding Authentication is Enabled.                                                                                                            Sat Sep 25 20:30:01 2021 daemon.notice opennds[7833]: Initializing firewall rules                                                                                                                      Sat Sep 25 20:30:03 2021 daemon.notice opennds[7833]: openNDS is now running.                                                                                                                          Sat Sep 25 20:30:04 2021 daemon.notice opennds[7833]: Adding 192.168.1.175 b4:2e:99:17:22:03 token 61f4a4f3 to client list                                                                             Sat Sep 25 20:31:09 2021 daemon.notice opennds[7833]: Exiting...                                                                                                                                       Sat Sep 25 21:20:25 2021 daemon.notice opennds[10295]: openNDS Version 9.4.0 is in startup                                                                                                             Sat Sep 25 21:20:26 2021 daemon.notice opennds[10295]: MHD version is 0.9.71                                                                                                                           Sat Sep 25 21:20:26 2021 daemon.notice opennds[10295]: Attempting to Bind to interface: br-lan                                                                                                         Sat Sep 25 21:20:26 2021 daemon.notice opennds[10295]: Interface br-lan is up                                                                                                                          Sat Sep 25 21:20:26 2021 daemon.notice opennds[10295]: Interface br-lan is at 192.168.1.1 (90:9a:4a:96:96:2c)                                                                                          Sat Sep 25 21:20:26 2021 daemon.notice opennds[10295]: Upstream gateway [ 197.52.0.1 ] via interface [ pppoe-wan ] is online                                                                           Sat Sep 25 21:20:26 2021 daemon.notice opennds[10295]: Created web server on 192.168.1.1:2050                                                                                                          Sat Sep 25 21:20:26 2021 daemon.notice opennds[10295]: Maximum Html Page size is [ 10240 ] Bytes                                                                                                       Sat Sep 25 21:20:26 2021 daemon.notice opennds[10295]: Socket access at /tmp/ndsctl.sock                                                                                                               Sat Sep 25 21:20:26 2021 daemon.notice opennds[10295]: Click to Continue option is Enabled.                                                                                                            Sat Sep 25 21:20:26 2021 daemon.notice opennds[10295]: Preauth is Enabled - Overiding FAS configuration.                                                                                               Sat Sep 25 21:20:26 2021 daemon.notice opennds[10295]: sha256sum provider is available                                                                                                                 Sat Sep 25 21:20:26 2021 daemon.notice opennds[10295]: FAS URL is http://192.168.1.1:2050/opennds_preauth/                                                                                             Sat Sep 25 21:20:26 2021 daemon.notice opennds[10295]: Forwarding Authentication is Enabled.                                                                                                           Sat Sep 25 21:20:26 2021 daemon.notice opennds[10295]: Initializing firewall rules                                                                                                                     Sat Sep 25 21:20:28 2021 daemon.notice opennds[10295]: openNDS is now running.                                                                                                                         Sat Sep 25 21:21:20 2021 daemon.notice opennds[10295]: Adding 192.168.1.100 da:0d:16:98:2a:c5 token b8380b88 to client list                                                                            Sat Sep 25 21:21:23 2021 daemon.notice opennds[10295]: Adding 192.168.1.190 50:01:d9:c5:72:81 token 9fe717f6 to client list                                                                            Sat Sep 25 21:21:46 2021 daemon.notice opennds[10295]: Adding 192.168.1.175 b4:2e:99:17:22:03 token 625b8c3f to client list                                                                            Sat Sep 25 21:22:18 2021 daemon.notice opennds[10295]: Adding 192.168.1.247 da:0d:16:c5:72:81 token 23cfba09 to client list                                                                            Sat Sep 25 21:23:31 2021 daemon.notice opennds[10295]: Adding 192.168.1.101 ec:89:14:98:2a:c5 token e9d9bebe to client list                                                                            Sat Sep 25 21:23:53 2021 daemon.notice opennds[10295]: Exiting...                                                                                                                                      Sat Sep 25 21:56:52 2021 daemon.notice opennds[15816]: openNDS Version 9.4.0 is in startup                                                                                                             Sat Sep 25 21:56:52 2021 daemon.err opennds[15816]: /tmp/etc/opennds_cfg01995c.conf: line 15: Bad configuration option: tcp                                                                            Sat Sep 25 21:56:52 2021 daemon.err opennds[15816]: Bad option tcp parsing FirewallRuleSet on line 15 in /tmp/etc/opennds_cfg01995c.conf                                                               Sat Sep 25 21:56:52 2021 daemon.err opennds[15816]: Exiting...                                                                                                                                         Sat Sep 25 21:56:57 2021 daemon.notice opennds[15862]: openNDS Version 9.4.0 is in startup                                                                                                             Sat Sep 25 21:56:58 2021 daemon.err opennds[15862]: /tmp/etc/opennds_cfg01995c.conf: line 15: Bad configuration option: tcp                                                                            Sat Sep 25 21:56:58 2021 daemon.err opennds[15862]: Bad option tcp parsing FirewallRuleSet on line 15 in /tmp/etc/opennds_cfg01995c.conf                                                               Sat Sep 25 21:56:58 2021 daemon.err opennds[15862]: Exiting...                                                                                                                                         Sat Sep 25 21:57:03 2021 daemon.notice opennds[15885]: openNDS Version 9.4.0 is in startup                                                                                                             Sat Sep 25 21:57:03 2021 daemon.err opennds[15885]: /tmp/etc/opennds_cfg01995c.conf: line 15: Bad configuration option: tcp                                                                            Sat Sep 25 21:57:03 2021 daemon.err opennds[15885]: Bad option tcp parsing FirewallRuleSet on line 15 in /tmp/etc/opennds_cfg01995c.conf                                                               Sat Sep 25 21:57:03 2021 daemon.err opennds[15885]: Exiting...                                                                                                                                         Sat Sep 25 21:57:08 2021 daemon.notice opennds[15895]: openNDS Version 9.4.0 is in startup                                                                                                             Sat Sep 25 21:57:08 2021 daemon.err opennds[15895]: /tmp/etc/opennds_cfg01995c.conf: line 15: Bad configuration option: tcp                                                                            Sat Sep 25 21:57:08 2021 daemon.err opennds[15895]: Bad option tcp parsing FirewallRuleSet on line 15 in /tmp/etc/opennds_cfg01995c.conf                                                               Sat Sep 25 21:57:08 2021 daemon.err opennds[15895]: Exiting...                                                                                                                                         Sat Sep 25 21:57:13 2021 daemon.notice opennds[15905]: openNDS Version 9.4.0 is in startup                                                                                                             Sat Sep 25 21:57:13 2021 daemon.err opennds[15905]: /tmp/etc/opennds_cfg01995c.conf: line 15: Bad configuration option: tcp                                                                            Sat Sep 25 21:57:13 2021 daemon.err opennds[15905]: Bad option tcp parsing FirewallRuleSet on line 15 in /tmp/etc/opennds_cfg01995c.conf                                                               Sat Sep 25 21:57:13 2021 daemon.err opennds[15905]: Exiting...                                                                                                                                         Sat Sep 25 21:57:18 2021 daemon.notice opennds[15915]: openNDS Version 9.4.0 is in startup                                                                                                             Sat Sep 25 21:57:18 2021 daemon.err opennds[15915]: /tmp/etc/opennds_cfg01995c.conf: line 15: Bad configuration option: tcp                                                                            Sat Sep 25 21:57:18 2021 daemon.err opennds[15915]: Bad option tcp parsing FirewallRuleSet on line 15 in /tmp/etc/opennds_cfg01995c.conf                                                               Sat Sep 25 21:57:18 2021 daemon.err opennds[15915]: Exiting...                                                                                                                                         Sat Sep 25 21:57:18 2021 daemon.info procd: Instance opennds::cfg01995c s in a crash loop 6 crashes, 0 seconds since last crash                                                                        Sat Sep 25 21:57:21 2021 daemon.notice opennds[15957]: openNDS Version 9.4.0 is in startup                                                                                                             Sat Sep 25 21:57:21 2021 daemon.err opennds[15957]: /tmp/etc/opennds_cfg01995c.conf: line 15: Bad configuration option: tcp                                                                            Sat Sep 25 21:57:21 2021 daemon.err opennds[15957]: Bad option tcp parsing FirewallRuleSet on line 15 in /tmp/etc/opennds_cfg01995c.conf                                                               Sat Sep 25 21:57:21 2021 daemon.err opennds[15957]: Exiting...                                                                                                                                         Sat Sep 25 21:57:21 2021 daemon.info procd: Instance opennds::cfg01995c s in a crash loop 7 crashes, 0 seconds since last crash                                                                        Sat Sep 25 21:57:47 2021 daemon.notice opennds[16065]: openNDS Version 9.4.0 is in startup                                                                                                             Sat Sep 25 21:57:47 2021 daemon.err opennds[16065]: /tmp/etc/opennds_cfg01995c.conf: line 15: Bad configuration option: tcp                                                                            Sat Sep 25 21:57:47 2021 daemon.err opennds[16065]: Bad option tcp parsing FirewallRuleSet on line 15 in /tmp/etc/opennds_cfg01995c.conf                                                               Sat Sep 25 21:57:47 2021 daemon.err opennds[16065]: Exiting...                                                                                                                                         Sat Sep 25 21:57:47 2021 daemon.info procd: Instance opennds::cfg01995c s in a crash loop 8 crashes, 1 seconds since last crash                                                                        Sat Sep 25 21:59:24 2021 daemon.notice opennds[16160]: openNDS Version 9.4.0 is in startup                                                                                                             Sat Sep 25 21:59:24 2021 daemon.notice opennds[16160]: MHD version is 0.9.71                                                                                                                           Sat Sep 25 21:59:24 2021 daemon.notice opennds[16160]: Attempting to Bind to interface: br-lan                                                                                                         Sat Sep 25 21:59:24 2021 daemon.notice opennds[16160]: Interface br-lan is up                                                                                                                          Sat Sep 25 21:59:24 2021 daemon.notice opennds[16160]: Interface br-lan is at 192.168.1.1 (90:9a:4a:96:96:2c)                                                                                          Sat Sep 25 21:59:24 2021 daemon.notice opennds[16160]: Upstream gateway [ 197.52.0.1 ] via interface [ pppoe-wan ] is online                                                                           Sat Sep 25 21:59:24 2021 daemon.notice opennds[16160]: Created web server on 192.168.1.1:2050                                                                                                          Sat Sep 25 21:59:24 2021 daemon.notice opennds[16160]: Maximum Html Page size is [ 10240 ] Bytes                                                                                                       Sat Sep 25 21:59:24 2021 daemon.notice opennds[16160]: Socket access at /tmp/ndsctl.sock                                                                                                               Sat Sep 25 21:59:24 2021 daemon.notice opennds[16160]: Click to Continue option is Enabled.                                                                                                            Sat Sep 25 21:59:24 2021 daemon.notice opennds[16160]: Preauth is Enabled - Overiding FAS configuration.                                                                                               Sat Sep 25 21:59:24 2021 daemon.notice opennds[16160]: sha256sum provider is available                                                                                                                 Sat Sep 25 21:59:24 2021 daemon.notice opennds[16160]: FAS URL is http://192.168.1.1:2050/opennds_preauth/                                                                                             Sat Sep 25 21:59:25 2021 daemon.notice opennds[16160]: Forwarding Authentication is Enabled.                                                                                                           Sat Sep 25 21:59:25 2021 daemon.notice opennds[16160]: Initializing firewall rules                                                                                                                     Sat Sep 25 21:59:26 2021 daemon.notice opennds[16160]: openNDS is now running.                                                                                                                         Sat Sep 25 21:59:28 2021 daemon.notice opennds[16160]: Upstream gateway [ 197.52.0.1 ] via interface [ pppoe-wan ] is online                                                                           Sat Sep 25 22:00:08 2021 daemon.notice opennds[16160]: Exiting...                                                                                                                                      Sat Sep 25 22:08:03 2021 daemon.notice opennds[16922]: openNDS Version 9.4.0 is in startup                                                                                                             Sat Sep 25 22:08:03 2021 daemon.notice opennds[16922]: MHD version is 0.9.71                                                                                                                           Sat Sep 25 22:08:03 2021 daemon.notice opennds[16922]: Attempting to Bind to interface: br-lan                                                                                                         Sat Sep 25 22:08:03 2021 daemon.notice opennds[16922]: Interface br-lan is up                                                                                                                          Sat Sep 25 22:08:03 2021 daemon.notice opennds[16922]: Interface br-lan is at 192.168.1.1 (90:9a:4a:96:96:2c)                                                                                          Sat Sep 25 22:08:03 2021 daemon.notice opennds[16922]: Upstream gateway [ 197.52.0.1 ] via interface [ pppoe-wan ] is online                                                                           Sat Sep 25 22:08:04 2021 daemon.notice opennds[16922]: Created web server on 192.168.1.1:2050                                                                                                          Sat Sep 25 22:08:04 2021 daemon.notice opennds[16922]: Maximum Html Page size is [ 10240 ] Bytes                                                                                                       Sat Sep 25 22:08:04 2021 daemon.notice opennds[16922]: Socket access at /tmp/ndsctl.sock                                                                                                               Sat Sep 25 22:08:04 2021 daemon.notice opennds[16922]: Click to Continue option is Enabled.                                                                                                            Sat Sep 25 22:08:04 2021 daemon.notice opennds[16922]: Preauth is Enabled - Overiding FAS configuration.                                                                                               Sat Sep 25 22:08:04 2021 daemon.notice opennds[16922]: sha256sum provider is available                                                                                                                 Sat Sep 25 22:08:04 2021 daemon.notice opennds[16922]: FAS URL is http://192.168.1.1:2050/opennds_preauth/                                                                                             Sat Sep 25 22:08:04 2021 daemon.notice opennds[16922]: Forwarding Authentication is Enabled.                                                                                                           Sat Sep 25 22:08:04 2021 daemon.notice opennds[16922]: Initializing firewall rules                                                                                                                     Sat Sep 25 22:08:05 2021 daemon.notice opennds[16922]: openNDS is now running.                                                                                                                         Sat Sep 25 22:08:30 2021 daemon.notice opennds[16922]: Upstream gateway [ 197.52.0.1 ] via interface [ pppoe-wan ] is online                                                                           Sat Sep 25 22:08:52 2021 daemon.notice opennds[16922]: Upstream gateway [ 197.52.0.1 ] via interface [ pppoe-wan ] is online                                                                           Sat Sep 25 22:09:07 2021 daemon.notice opennds[16922]: Adding 192.168.1.175 b4:2e:99:17:22:03 token c5313508 to client list                                                                            Sat Sep 25 22:09:21 2021 daemon.warn opennds[16922]: Preauth script - failed to execute: /usr/lib/opennds/libopennds.sh, Query[]                                                                       Sat Sep 25 22:09:48 2021 daemon.notice opennds[16922]: Adding 192.168.1.101 ec:89:14:98:2a:c5 token ad466a3f to client list                                                                            Sat Sep 25 22:09:58 2021 daemon.notice opennds[16922]: Authenticating 192.168.1.175 b4:2e:99:17:22:03                                                                                                  Sat Sep 25 22:18:40 2021 daemon.notice opennds[16922]: Deauthenticating 192.168.1.175 b4:2e:99:17:22:03                                                                                                Sat Sep 25 22:19:29 2021 daemon.notice opennds[16922]: Authenticating 192.168.1.175 b4:2e:99:17:22:03                                                                                                  Sat Sep 25 22:40:16 2021 daemon.notice opennds[16922]: Timeout preauthenticated idle user: 192.168.1.101 ec:89:14:98:2a:c5, inactive: 1829s                                                            Sat Sep 25 22:40:16 2021 daemon.notice opennds[16922]: Deleting 192.168.1.101 ec:89:14:98:2a:c5 token ad466a3f from client list                                                                        Sat Sep 25 22:49:07 2021 daemon.notice opennds[16922]: Adding 192.168.1.101 ec:89:14:98:2a:c5 token feb2d60a to client list                                                                            Sat Sep 25 22:57:22 2021 daemon.notice opennds[16922]: Deauthenticating 192.168.1.175 b4:2e:99:17:22:03                                                                                                Sat Sep 25 22:57:24 2021 daemon.notice opennds[16922]: Exiting...                                                                                                                                      Sat Sep 25 22:57:24 2021 daemon.notice opennds[29440]: openNDS Version 9.4.0 is in startup                                                                                                             Sat Sep 25 22:57:24 2021 daemon.info opennds[29440]: Done reading configuration file '/tmp/etc/opennds_cfg01995c.conf'                                                                                 Sat Sep 25 22:57:24 2021 daemon.info opennds[29440]: Initializing signal handlers                                                                                                                      Sat Sep 25 22:57:24 2021 daemon.info opennds[29440]: tmpfs mountpoint is [/tmp]                                                                                                                        Sat Sep 25 22:57:24 2021 daemon.notice opennds[29440]: MHD version is 0.9.71                                                                                                                           Sat Sep 25 22:57:24 2021 daemon.notice opennds[29440]: Attempting to Bind to interface: br-lan                                                                                                         Sat Sep 25 22:57:24 2021 daemon.notice opennds[29440]: Interface br-lan is up                                                                                                                          Sat Sep 25 22:57:24 2021 daemon.notice opennds[29440]: Interface br-lan is at 192.168.1.1 (90:9a:4a:96:96:2c)                                                                                          Sat Sep 25 22:57:24 2021 daemon.notice opennds[29440]: Upstream gateway [ 197.52.0.1 ] via interface [ pppoe-wan ] is online                                                                           Sat Sep 25 22:57:24 2021 daemon.info opennds[29440]: Client status Page: Configured                                                                                                                    Sat Sep 25 22:57:24 2021 daemon.info opennds[29440]: RFC8910 support is enabled                                                                                                                        Sat Sep 25 22:57:24 2021 daemon.info opennds[29440]: Dnsmasq restarted                                                                                                                                 Sat Sep 25 22:57:24 2021 daemon.info opennds[29440]: main: System Uptime is 9317 seconds                                                                                                               Sat Sep 25 22:57:24 2021 daemon.info opennds[29440]: Setting started_time                                                                                                                              Sat Sep 25 22:57:24 2021 daemon.info opennds[29440]: MHD Unescape Callback is Disabled                                                                                                                 Sat Sep 25 22:57:24 2021 daemon.info opennds[29440]: MHD Handle [4360304]                                                                                                                              Sat Sep 25 22:57:24 2021 daemon.notice opennds[29440]: Created web server on 192.168.1.1:2050                                                                                                          Sat Sep 25 22:57:24 2021 daemon.notice opennds[29440]: Maximum Html Page size is [ 10240 ] Bytes                                                                                                       Sat Sep 25 22:57:24 2021 daemon.notice opennds[29440]: Socket access at /tmp/ndsctl.sock                                                                                                               Sat Sep 25 22:57:24 2021 daemon.notice opennds[29440]: Click to Continue option is Enabled.                                                                                                            Sat Sep 25 22:57:24 2021 daemon.notice opennds[29440]: Preauth is Enabled - Overiding FAS configuration.                                                                                               Sat Sep 25 22:57:24 2021 daemon.info opennds[29440]: Preauth Script is /usr/lib/opennds/libopennds.sh                                                                                                  Sat Sep 25 22:57:24 2021 daemon.info opennds[29440]: fas_secure_enabled is set to level 1                                                                                                              Sat Sep 25 22:57:24 2021 daemon.info opennds[29440]: fasremoteip - 192.168.1.1 - is a valid IPv4 address...                                                                                            Sat Sep 25 22:57:24 2021 daemon.notice opennds[29440]: sha256sum provider is available                                                                                                                 Sat Sep 25 22:57:24 2021 daemon.notice opennds[29440]: FAS URL is http://192.168.1.1:2050/opennds_preauth/                                                                                             Sat Sep 25 22:57:24 2021 daemon.notice opennds[29440]: Forwarding Authentication is Enabled.                                                                                                           Sat Sep 25 22:57:24 2021 daemon.notice opennds[29440]: Initializing firewall rules                                                                                                                     Sat Sep 25 22:57:25 2021 daemon.notice opennds[29440]: openNDS is now running.                                                                                                                         Sat Sep 25 22:57:42 2021 daemon.notice opennds[29440]: Adding 192.168.1.175 b4:2e:99:17:22:03 token a8aaa66b to client list                                                                            Sat Sep 25 22:57:56 2021 daemon.info opennds[29440]: Network Authentication Required - page_511 html generated for [192.168.1.175]                                                                     Sat Sep 25 22:58:01 2021 daemon.info opennds[29440]: Network Authentication Required - page_511 html generated for [192.168.1.175]                                                                     Sat Sep 25 22:58:18 2021 daemon.notice opennds[29440]: Authenticating 192.168.1.175 b4:2e:99:17:22:03                                                                                                  Sat Sep 25 22:58:26 2021 daemon.info opennds[29440]: Client @ 192.168.1.175 b4:2e:99:17:22:03, quotas:                                                                                                 Sat Sep 25 22:58:26 2021 daemon.info opennds[29440]:    Download DATA quota (kBytes): 0, used: 418                                                                                                     Sat Sep 25 22:58:26 2021 daemon.info opennds[29440]:    Upload DATA quota (kBytes): 0, used: 273

**Comment by 25khattab** [comment]
@bluewavenet 
I have to access http site to make the page appear to get access 
before it would appear to me when i connect

**Comment by 25khattab** [comment]
@bluewavenet 
this happens to i don't know why
```
root@OpenWrt:~# opennds restart
[5][Sun Sep 26 00:47:18 2021][17838](src/main.c:865) openNDS Version 9.4.0 is in startup

[3][Sun Sep 26 00:47:18 2021][17838](src/conf.c:761) FATAL: Could not open configuration file '/etc/opennds/opennds.conf', exiting...
```

**Comment by bluewavenet** [comment]
@25khattab 
`opennds restart`

This command will not work. openNDS is a service daemon and should be started in OpenWrt by ProcD.

You neet to use:
`service opennds restart`

**Comment by bluewavenet** [comment]
@25khattab 
The status.client page is showing LocalZone: br-lan
Are you connected to ethernet or using an ethernet connected wireless access point?
I would have expected wlan0 or wlan1 or similar...

Are you testing with a desktop/laptop machine or a mobile device? 
Your screenshots look like Windows. Do you have captive portal detection (CPD) switched off? It is normally on by default on Windows unless you have one of the antivirus suites installed as these will often turn CPD off.

**Comment by 25khattab** [comment]
@bluewavenet 
i did it on both with my phone on wireless ap and on pc through ethernet
both don't work

**Comment by 25khattab** [comment]
@bluewavenet 
opennnds was working correctly and then it stopped showing login page on every device

**Comment by bluewavenet** [comment]
@25khattab 
It can only be something you have done to the configuration.
You can go back to default by copying /etc/opennds/config.uci to /etc/config/opennds

Then run `service opennds restart`

**Comment by 25khattab** [comment]
@bluewavenet 
still doesn't work
i tried to uninstall and install again with removing the config file but still doesnot work i donot know why at all

**Comment by bluewavenet** [comment]
@25khattab 
If you ping openwrt.org from the router, do yoi get a reply? ie does the router have internet access?

**Comment by 25khattab** [comment]
@bluewavenet 
yeah it does reply 
i did full reset for my router nothing is changed the splash page doesn't show

**Comment by bluewavenet** [comment]
@25khattab 
I suggest you do a fresh reflash of OpenWrt 21.02.0
Check all devices get Internet access.

Then install openNDS. Do not change any openNDS settings.

I just did that reflash and install process here on a test router and it works perfectly.

**Comment by 25khattab** [comment]
@bluewavenet 
i did this nothing has changed still no internet through devices

**Comment by bluewavenet** [comment]
@25khattab 

> i did this nothing has changed still no internet through devices

Then it must be tbe client devices.

The following will prevent CPD from poppong up the login page:
* A security program that forces the client to use https
* an active VPN
* ISP blocking access to the client vendor captive portal detection URLs
* DNS not working properly on the openNDS router
* possibly other things too.

Most of these things are not present on most people's devices so it works reliably usually.

**Comment by 25khattab** [comment]
@bluewavenet  turns out that my 2 devices I'm testing on have problems my bad for keeping u busy back to our first problem now 
i will delete my comments and u should too to make it easy for every one with same problem 
i will delete my comment after u delete yours again sorry for keeping u busy

**Comment by bluewavenet** [comment]
@25khattab 
Nothing needs to be deleted. It is useful for others  as it is.

**Comment by bluewavenet** [comment]
@25khattab 
If you want to discuss how to make your own themespec login sequence it is best to open a new issue.
