### ISSUE TITLE
android doesn't show login page

### ISSUE THREAD

**Issue by 25khattab** [openNDS/openNDS#241]
when i connect my phone i have to access 192.168.1.1 to get in the portal login page
Is there is a fix 

router : archer c7 v5
openWRT : 21.02
opennds (9.4.0)

**Comment by bluewavenet** [comment]
@25khattab 
Most likely you have a router configuration problem.
Please state:
1. Router hardware
2. Router operating system and version
3. Version of openNDS

Also I recommend in depth reading of the documentation:
https://opennds.readthedocs.io/

**Comment by 25khattab** [comment]
1- ARCHER c7 v5
2- openWRT 21.02
3- latest version
