### ISSUE TITLE
It would be great to add these two functions

### ISSUE THREAD

**Issue by Scyllaly** [openNDS/openNDS#242]
1.How to automatically post the upload traffic and download traffic in its session life to FAS when the device is  session timeout or deauth? 

2.Authmon listens to the data returned by FAS. If there is specified data, it can kick the specified device offline.

I don't know how to achieve it

**Comment by Scyllaly** [comment]
I found `/tmp/ndslog/binauth_log` it shows that client(device)'s tx & rx in session life when its deauth.
But i dont know how to change binauth , is it binauth is a binary program or a shell, i can not find it out. where is it?

**Comment by bluewavenet** [comment]
@Scyllaly 

> is it binauth is a binary program or a shell, i can not find it out. where is it?

It is a program - script, binary, whatever you define it as in your config.
By default it is disabled.
Looks like you have enabled it. 
`uci show opennds | grep binauth`

Almost certainly the default script, /usr/lib/opennds/binauth_log.sh

> 1.How to automatically post the upload traffic and download traffic in its session life to FAS when the device is session timeout or deauth?

Just get binauth to send its log to FAS

> 2.Authmon listens to the data returned by FAS. If there is specified data, it can kick the specified device offline.

Sure - but FAS knows nothing about what a client is doing whereas openNDS knows it all. Why send data to FAS so it can send a decision back to openNDS when openNDS can make the decision itself. 

It would be possibly be nice for FAS to know if openNDS has kicked out a client, but not in any way necessary in normal use.

**Comment by bluewavenet** [comment]
@Scyllaly 
Hint: You can call post-request.php from your BinAuth script to send the log information to the remote FAS.

**Comment by Scyllaly** [comment]
@bluewavenet If binauth is enabled, is the execution frequency of binauth executed once per second?

**Comment by Scyllaly** [comment]
I have to understand how the whole program works in order to add functions to it

**Comment by bluewavenet** [comment]
@Scyllaly 
The next version of openNDS is testing with RFC8908 support.
This requires the addition of a "re-authenticate" option along with extended authmon/binauth reporting to FAS, so it looks like your wish list of two new functions will be easy to support :-D

Have you made any progress of your own?
