### ISSUE TITLE
Disconnect log

### ISSUE THREAD

**Issue by 0l4y4** [openNDS/openNDS#244]
Hello,
Would it be possible to log the disconnection of a user on the FAS server?

**Comment by Scyllaly** [comment]
Currently not supported

**Comment by bluewavenet** [comment]
@0l4y4 @Scyllaly 
It is not directly supported as a built in function but is easily doable as part of a custom BinAuth script.
The example binauth_log.sh writes a local log of all client auths and deauths. It would be a simple matter to get it to also send the log information to a remote FAS using the existing post-request script.

It is a debatable point whether a remote FAS needs to know about client disconnections.
 -- Could you both list reasons what use this could have?

**Comment by bluewavenet** [comment]
> Could you both list reasons why you would want this?

It is a relatively simple enhancement to a fas-aes-https/binauth combination. Is it worth doing?

**Comment by 0l4y4** [comment]
> @0l4y4 @Scyllaly It is not directly supported as a built in function but is easily doable as part of a custom BinAuth script. The example binauth_log.sh writes a local log of all client auths and deauths. It would be a simple matter to get it to also send the log information to a remote FAS using the existing post-request script.
> 
> It is a debatable point whether a remote FAS needs to know about client disconnections. -- Could you both list reasons why you would want this?

I would like to be able to get metrics of how long my clients are connected, for example. Also, in the event that someone did something illicit, I would have more control

**Comment by 0l4y4** [comment]
@bluewavenet 
I was even thinking of taking that data, among others with FileBeat, to an Elasticsearch database

**Comment by bluewavenet** [comment]
@0l4y4 
The data is recorded locally in the Binauth log (if enabled).

The answer is to have BinAuth send the log entries also to your remote FAS server.
This would be very simple to do, nothing new needed, just an enhanced fas-aes-https.php/binauth-log.sh pair of files doing the job quite nicely.

Alternatively set up a vpn (or ssh tunnel) and copy the log file when running your metrics reports.

>  in the event that someone did something illicit, I would have more control

This would not help. For that you need remote access to your openNDS router.

**Comment by 0l4y4** [comment]
@bluewavenet 
That option is difficult because I do not have access to the ISP router to open the port to my router. For me, the easiest thing is to export all that data

**Comment by bluewavenet** [comment]
@0l4y4 
With sshtunnel or a vpn you don't need to open any ports but you do need something elsewhere with a fixed ip address for sshtunnel.
To monitor closely you do need remote access though.

**Comment by 0l4y4** [comment]
@bluewavenet 
It is not feasible to mount a reverse connection

**Comment by bluewavenet** [comment]
@0l4y4 

>  It is not feasible to mount a reverse connection

Why not? I do it all the time using the sshtunnel package.

**Comment by 0l4y4** [comment]
@bluewavenet 
Do you have some kind of "How to"?

**Comment by 0l4y4** [comment]
@bluewavenet 
If I am understanding you correctly, you tell me that you configure opennds as a ssh server and can you connect from outside without opening a port? it seems impossible to me

**Comment by bluewavenet** [comment]
@0l4y4 
https://openwrt.org/docs/guide-user/services/ssh/sshtunnel

I use a server on a VPS running OpenWrt and this costs £7.00 GBP per month.
It allows access to remote openNDS routers behind double NAT. From my office I can ssh to and mount sftp storage on the remote router.

**Comment by 0l4y4** [comment]
@bluewavenet 
Who is the client and who is the server?

**Comment by 0l4y4** [comment]
I need a picture :-)

**Comment by bluewavenet** [comment]
The VPS is the server.
openNDS routers are clients. I can ssh to any openNDS router  and mount router storage on my Linux laptop.

**Comment by 0l4y4** [comment]
@bluewavenet 

Ok! I thought you wanted to install the ssh server on the opennds, that's why it said that you needed to open a port on the ISP router

**Comment by 0l4y4** [comment]
@bluewavenet 

How many opennds devices do you have connected to your VPS at the same time?

**Comment by bluewavenet** [comment]
@0l4y4 
It is used commercially and not just for openNDS. It is turned on if a customer requests remote support, so the number varies.
During the lockdown/home-working peak in 2020-2021 it was "numerous". There is no technical limit to the number.

**Comment by 0l4y4** [comment]
@bluewavenet 
But I understand that you have the ssh connection launched from the client to the server automatically and permanently, right?

**Comment by 0l4y4** [comment]
Because telling a client to connect to openwrt and launch the command can be a bit chaotic, don't you think?

**Comment by bluewavenet** [comment]
They connect to the network and log in with a special enabler account. This enables and starts the sshtunnel process until it is disabled again. Yes it can be left permanently on if that is what the customer requires.

**Comment by 0l4y4** [comment]
@bluewavenet 
Can you explain this user procedure to me well?

**Comment by bluewavenet** [comment]
@0l4y4 
Sorry not in detail, it is proprietary information.
Basically there is a special set of credentials that turns it on. There are lots of ways to achieve this that you could do yourself.

**Comment by 0l4y4** [comment]
@bluewavenet 
Are you referring to an ssh connection by the user to openwrt or a login in LuCI?

**Comment by bluewavenet** [comment]
@0l4y4 
I am referring to the standard CPD login page that pops up when connecting. A special set of credentials is detected and turns on the tunnel.

**Comment by 0l4y4** [comment]
@bluewavenet 

Are we talking about FAS https?

**Comment by bluewavenet** [comment]
All types of FAS

**Comment by 0l4y4** [comment]
@bluewavenet 
And when the device has a connectivity problem, how do you solve the problem normally?

**Comment by bluewavenet** [comment]
Linux remote support is a completely separate subject.
Remote or local, as far as checking openNDS running status is concerned, there is no difference.
Remotely, sometimes you might have to ask a local person to power cycle something ;-)
