### ISSUE TITLE
[feature] config option to set different interface to get MAC from for pushing to FAS server

### ISSUE THREAD

**Issue by minhng99** [openNDS/openNDS#258]
Hi, I'm currently having some oversight and messed up my system... our server decide which ads to shown on the FAS server based on the MAC address being requested in the `&fas=`... we're currently managing all our APs using the MAC address which is printed on the label but it's different compared to `br-lan` which is usually +1.

For now I'm currently patching the `libopennds.sh` to make it get MAC from `eth0` which contains the label's MAC instead of the `br-lan` which it's using to serve LAN clients.

How about a function to set which interface which will be used to get the MAC address for the FAS feature?

**Comment by minhng99** [comment]
Maybe even a path for executing a script that returns MAC address? That will also covers the case which the intended MAC address is not present on any interface and user could do the calculation by themselves

**Comment by bluewavenet** [comment]
@minhng99 
libopennds already has a function to get gatewaymac by interface:
https://opennds.readthedocs.io/en/stable/libraries.html#gatewaymac
ie `/usr/lib/opennds/libopennds.sh gatewaymac "eth0"`

**Comment by minhng99** [comment]
Yes, I know, that file is being used by opennds to get the gateway's MAC address... but it's currently set to the interface serving clients which is br-lan, my idea is that I can use a different interface MAC address to report to the FAS server

**Comment by bluewavenet** [comment]
@minhng99 
Yes the value of the mac address printed on the label seems to depend on the hardware eg multiple physical ethernet interfaces vs one interface and a switch vs two physical with one for "wan" and the other with a built in switch for lan etc.

What appears on the label seems to depend on a random choice by the manufacturer or the creator of the OpenWrt target.

It would be possible to send both wan and lan  mac addresses to FAS.

But this brings us back to a discussion we had a long time ago about gateway identification, where "gatewayname" was designed  just for that purpose. I also understand that for large rollouts, a single reflash image is very desirable.
So a simple startup script to set the gatewayname to the mac address of the wan interface perhaps?

**Comment by minhng99** [comment]
Yeah that make sense.... it just because my FAS server is owned by a different department and they're lazy to change the code so I have to provide compatible GET parameters to whatever they're expecting to get from it... I'll patch the board.d so the br-lan will have the label MAC instead
