### ISSUE TITLE
OpenWRT install - No log file written

### ISSUE THREAD

**Issue by JoeDat** [openNDS/openNDS#260]
Fresh install of opennds on a OpenWRT 19.07.8 router.  With all settings at default, everything appears functional, except for logging.  It's just not writing a log file.  Default log location on the device should be /tmp/ndslog/ndslog.log.  However, it does exist.  I've searched the entire router for the file.  

Troubleshooting steps taken:
- Upgraded libmicrohttpd-no-ssl to the 21.02 OpenWRT version of 0.9.71-1 (despite no functional issues with the portal itself)
- Set log_mountpoint option to an alternative location
- Increased logging debug level

EDIT:  I changed the login mode to 2, and it is now logging access attempts.  I'm okay with this behavior, but based on the documentation and the default logging level, basic startup info of the service should also be logged.  I can live without this especially since that's logged in the system log.  But, leaving open in case this is unexpected.

**Comment by bluewavenet** [comment]
@JoeDat 
Which version of openNDS are you using? The current version is 9.4.0. 
The version available with OpenWrt 19.07.x is **very** outdated. You can download the OpenWrt 21.02 version as you did with MHD - it is fully compatible with 19.07.x

Note: The openNDS log is an access log. Service logging is sent to syslog. Nobody has mentioned this as an issue before, but now you have, I do see that interpretation! What you have found is correct and not unexpected ;-)

> based on the documentation

If you could point out the confusing wording, I will rewrite it.

**Comment by JoeDat** [comment]
Thanks @bluewavenet!  It's amazing how things improve significantly simply by using the latest version ;-)  I was having a problem with status.client as well, but chalked it up to my guest network FW rules.  Of course, probably because this wasn't available in the ancient 19.07 version I was using.  

Regarding logging, it's the wording in the Enable Debug Output section.  It implies that a log should be created with initial startup info.  That's initially why I thought logging wasn't working.  

https://opennds.readthedocs.io/en/stable/config.html?highlight=log#enable-debug-output-0-3
