### ISSUE TITLE
openNDS on Raspberry - Routing configuration is not valid for openNDS

### ISSUE THREAD

**Issue by voltusv** [openNDS/openNDS#261]
Hi I'm trying to start openNDS on my Raspberry Pi 4. But I'm getting the following error:

_**Routing configuration is not valid for openNDS, exiting ...**_

I'm using the latest version of openNDS (9.4.0). My Raspberry is connected to the Internet using eth0 (DHCP Client), and the access point using wlan0 with static IP and DHCP Server. 

I have installed RasAp to configure my network interfaces. I have changed as per openNDS doc, but still getting the same error.

This is my routing table

_default via 192.168.0.1 dev eth0 proto dhcp src 192.168.0.127 metric 202 
default via 10.3.141.1 dev wlan0 src 10.3.141.1 metric 303 
10.3.141.0/24 dev wlan0 proto dhcp scope link src 10.3.141.1 metric 303 
192.168.0.0/24 dev eth0 proto dhcp scope link src 192.168.0.127 metric 202_ 

Appreciate your help.

**Comment by bluewavenet** [comment]
@voltusv 
The routing table looks wrong, you seem to have two default routes.

What is the output of:
`ip -f inet route`

What operating system and os version are you running on the Pi?

**Comment by bluewavenet** [comment]
@voltusv 
The routing table looks wrong, you seem to have two default routes.

What is the output of:
`ip -f inet route`

What operating system and os version are you running on the Pi?

**Comment by voltusv** [comment]
Thanks @bluewavenet 

> ip -f inet route

_default via 192.168.0.1 dev eth0 proto dhcp src 192.168.0.127 metric 202 
default via 10.3.141.1 dev wlan0 src 10.3.141.1 metric 303 
10.3.141.0/24 dev wlan0 proto dhcp scope link src 10.3.141.1 metric 303 
192.168.0.0/24 dev eth0 proto dhcp scope link src 192.168.0.127 metric 202_ 

I'm using Rasbian OS

**Comment by bluewavenet** [comment]
@voltusv 
Having two defaults is definitely wrong, although I don't know if that is what is causing your problem. 
I would expect something like:
```
default via 192.168.0.1 dev eth0 kernel dhcp src 192.168.0.127 metric 202
10.3.141.0/24 dev wlan0 proto kernel scope link src 10.3.141.1 metric 303
192.168.0.0/24 dev eth0 proto kernel scope link src 192.168.0.127 metric 202
```
Have you made any changes to the default /etc/opennds/opennds.conf file?
For a default system with wlan0 and eth0, no changes are necessary for it to run.

**Comment by voltusv** [comment]
Thanks @bluewavenet 

You gave me the tip. Looks like my routing configurations were dupplicated. 

I did 

```
sudo ip route del default via 192.168.0.1 dev eth0 proto dhcp src 192.168.0.127 metric 202
sudo ip route del default via 10.3.141.1 dev wlan0 src 10.3.141.1 metric 30
```

**and now it is working.**

**Comment by voltusv** [comment]
@bluewavenet How can I open the default browser after the Captive Portal page?
I need to redirect to my local web page, but in a real browser (chrome, safari, etc)
Thank you

**Comment by bluewavenet** [comment]
@voltusv 

> How can I open the default browser after the Captive Portal page?

This is controlled by the client operating system and cannot be influenced externally.
Simple answer: You can't.
