### ISSUE TITLE
A diagram or example showing how FAS works

### ISSUE THREAD

**Issue by DAT4** [openNDS/openNDS#264]
I have just read your documentation and it is very nice, however it is a bit difficult for me to understand how I can set up FAS properly.

I understand that it should be possible to create a remote authentication service with its own front-/backend and database, but I don't understand how the remote server notifies the router that the client is authorized or not.

Maybe a diagram showing the flow how the different components interact.

Thank you very much for openNDS it seem very useful on OpenWRT. 

PS:
I know that there already are PHP examples. Yet if it is possible to do FAS in any language then maybe it could be nice with some extra examples for people who don't know PHP :-)

**Comment by bluewavenet** [comment]
@DAT4 

> Maybe a diagram showing the flow how the different components interact.

Yes, quite a good idea, it is just a matter of someone finding the time to do it.

> I know that there already are PHP examples. Yet if it is possible to do FAS in any language then maybe it could be nice with some extra examples for people who don't know PHP :-)

PHP is a language that is very easy for any programmer to follow even if they have no experience in it. It is also extensively used by web developer techs (but not web designers using CMS). It is also the most readily available language on hosting servers aimed at the SME business environment. This will typically be shared hosting using something like AMP (Apache MySQL PHP) where the ONLY language available is PHP.

Yes you are correct though, _any_ language can be used. In fact the openNDS "built in" FAS, AKA ThemeSpec, is written in Linux (B)ASH scripting.
If you can write examples in some other language, Pull Requests are always welcome!

**Comment by DAT4** [comment]
Thank you very much, I will share my FAS when it's done :)
