### ISSUE TITLE
How to integrate with FreeRadius in FreeBSD?

### ISSUE THREAD

**Issue by maysammortazi** [openNDS/openNDS#27]
Is it possible to integrate with FreeRadius in FreeBSD?
I have a freebsd 11.1 amd 64 that serve as radius server and other services.
I need a something like openNDS to use it as captive portal and  manage users bandwidth and quotas.
Thanks

**Comment by bluewavenet** [comment]
@maysammortazi 

> I need a something like openNDS to use it as captive portal and manage users bandwidth and quotas.

That is what openNDS does. Version 5.1.0 has built in support for Data Volume and Data Rate quotas.

openNDS FAS scripts can be written to communicate with FreeRadius.

@monelgordillo has done something like this and might comment.

**Comment by maysammortazi** [comment]
I can't make openNDS in freebsd and it has alot of error and i'm not very good to solve them.

`src/http_microhttpd_utils.h:31:10: fatal error: 'alloca.h' file not found
#include <alloca.h>
         ^~~~~~~~~~
1 error generated.`

`src/conf.c:39:10: fatal error: 'netinet/ether.h' file not found
#include <netinet/ether.h>
         ^~~~~~~~~~~~~~~~~
1 error generated.`

**Comment by bluewavenet** [comment]
@maysammortazi 
I am not sure, but I think this is just a FreeBSD thing. Try this:
 *  delete the line `#include <alloca.h>` in http_microhttpd_utils.h
 *  edit the line `#include <netinet/ether.h>` in conf.c to read `#include <netinet/if_ether.h>`

**Comment by bluewavenet** [comment]
@maysammortazi 
Did you get it to work?
