### ISSUE TITLE
Authentication failed on some device received multiple IP

### ISSUE THREAD

**Issue by minhng99** [openNDS/openNDS#270]
I'm getting some instances of this in the field:
![image](https://user-images.githubusercontent.com/14113155/143844444-bf33d30d-551e-48af-8178-69f89f3b7be8.png)

The client for some unknown reason has received multiple IP, my authentication script call the `ndsctl auth` with the device's MAC address and only one of them is Authenticated.

Any idea what might have caused this?

**Comment by bluewavenet** [comment]
No idea. Is this a device that has roamed from another instance of openNDS?
Look at the contents of /tmp/dhcp.leases to see if there is anything strange there.
Possibly dnsmasq has restarted after the client initially authenticated. Client did a dhcp request and got a different ip address?
That should not happen as dnsmasq bases assigned ip on the mac address.... It might happen if another client got the address before this client refreshed dhcp.... but would only happen if the ip pool was used up.

**Comment by bluewavenet** [comment]
Perhaps the client connected and authenticated. Then manually changed to a static ip by adding 1.
I think that might have this effect....  I'll have to try it.

**Comment by minhng99** [comment]
There is a possibility that it has roamed from another instance having the same private subnet... but I thought opennds will authenticate both? Or at least it should saw the MAC and authenticate it anyway?

The client didn't statically changed the address, it was one of our technician reported this issue... I'm still not quite sure why dnsmasq would allocate 2 IP for the same MAC, there's other clients are using this AP and it's working fine.

Guess another edge case then...

**Comment by bluewavenet** [comment]
Do you have preemptive authentication enabled or do you do your own thing during roaming?

It is not possible for dnsmasq to allocate 2 ips to the same mac. Preemptive auth requires dnsmasq to have allocated an ip for a non-preauthenticated client to be authenticated.

The issue here could possibly happen if a client is authenticated then dnsmasq restarts.  Another client jumps in and gets allocated the same ip as the first one. Then the first one does its periodic "can I still use this ip?" to find itself allocated a new ip - but it is still authed with the old ip.
I can try to simulate this when I get back to my workshop in a couple of hours.

What duration do you have set for dhcp lease?

**Comment by minhng99** [comment]
Yes, I do have preemptive auth enabled, I used my custom script which calls `ndsctl auth [mac]` as always...

I set DHCP leases for 6 hours... it wasn't a particularly busy day for that AP, at that moment there's only 9 clients connected.

**Comment by bluewavenet** [comment]
@minhng99 
A first quick look at this on my test system:
I connected and authenticated in the normal way.
I then changed the client to a static ip.
Authenticating with `ndsctl auth [mac]` fails (because the mac is already authenticated for the dhcp address).
This simulates the symptoms, I will have to look deeper for causes, ie how can a client be given a second ip address?
```
====
Client authentications since start: 1
Current clients: 2

Client 0
  Client Type: cpd_can
  IP: 10.168.1.143 MAC: 74:de:2b:b1:70:33
  Last Activity: Tue Nov 30 07:46:59 2021 (2m 56s ago)
  Session Start: Tue Nov 30 07:43:05 2021 (6m 50s ago)
  Session End:   Wed Dec 01 07:43:05 2021 (23h 53m 10s left)
  Token: 2cba7b04
  State: Authenticated
  Upload rate limit: 7 kb/s
  Download rate limit: 100 kb/s
  Upload quota: not set
  Download quota: not set
  Upload this session: 167 kB; Session avg: 3.27 kb/s
  Download this session: 744 kB; Session avg: 14.52 kb/s

Client 1
  Client Type: cpd_can
  IP: 10.168.1.144 MAC: 74:de:2b:b1:70:33
  Last Activity: Tue Nov 30 07:47:13 2021 (2m 42s ago)
  Session Start: -
  Session End:   -
  Token: 7ebd625a
  State: Preauthenticated
  Upload rate limit: not set
  Download rate limit: not set
  Upload quota: not set
  Download quota: not set
  Upload this session: 0 kB; Session avg: 0.00 kb/s
  Download this session: 0 kB; Session avg: 0.00 kb/s


```

**Comment by sicelo** [comment]
On Tue, Nov 30, 2021 at 12:15:37AM -0800, Rob White wrote:
> This simulates the symptoms, I will have to look deeper for causes, ie how can a client be given a second ip address?

MAC randomization, perhaps?

**Comment by bluewavenet** [comment]
@minhng99 
I can force this to happen as follows
1. make my laptop spoof the mac address of my phone
2. set a static ip on my laptop (using my phone's mac)
3. connect and authenticate on my laptop - no problems.
4. connect on my phone
5. attempt to manually authenticate using ndsctl auth [mac] - fails

There are probably other ways to recreate this, but this way is concerning for you as quite possibly someone is spoofing your tech support staffer's mac address.....

**Comment by bluewavenet** [comment]
@sicelo 

> MAC randomization, perhaps?

That was my first thought too, but both client instances in the client table are the same mac address.....
More likely mac spoofing?

**Comment by minhng99** [comment]
> someone is spoofing your tech support staffer's mac address

It's very unlikely, this is an public AP being installed at a coffee shop and the technician has only been there once, the MAC is from his phone

**Comment by bluewavenet** [comment]
@minhng99 
> being installed

Perhaps the Tech did something in the normal course of installing, ending up with this issue, perhaps restarting openNDS or restarting Dnsmasq or some combination of similar combined with the roaming process?

I have been able to replicate this, or at least something with a similar result, by spoofing. But as you say, in this situation it is very unlikely and would be a rather pointless exercise.

**Comment by minhng99** [comment]
> restarting openNDS or restarting Dnsmasq

No, they're not allowed and don't know the password for login into the AP, the AP has been provisioned and tested prior to installation and it's working fine, also there are other guests also testing the wifi and they're also authenticated just fine.... 

I don't know what happened with his phone neither, he says that his phone worked fine with other similar AP, running the same firmware.... at other site so I could also rule out the issue is caused by his phone.

I have seen this issue once before with another AP but I thought it just some strange glitch

**Comment by bluewavenet** [comment]
Well it is certainly a strange glitch!
If it happens again please try to get a copy of /tmp/dhcp.leases before one half of the lease time has passed (3 hours?).

**Comment by bluewavenet** [comment]
@minhng99 
Please reopen and report here if this occurs again...

**Comment by minhng99** [comment]
the same thing just happened again:
![image](https://user-images.githubusercontent.com/14113155/145960179-c106ee8c-8263-4355-8663-8d3f04994fc1.png)
![image](https://user-images.githubusercontent.com/14113155/145960201-3de9a8db-c27b-4de2-b9a8-d9dcdd479ceb.png)
![image](https://user-images.githubusercontent.com/14113155/145960238-7b4d6fd5-8e80-4da7-a145-4eeb4136949d.png)
![image](https://user-images.githubusercontent.com/14113155/145960282-a4a0e2de-b90f-4230-af42-423b00c95692.png)
![image](https://user-images.githubusercontent.com/14113155/145960407-8816ac1b-cb58-4714-964f-4cd30765777e.png)
![image](https://user-images.githubusercontent.com/14113155/145960517-ef9fd4e3-bcce-4750-9677-2b816723e3af.png)
![image](https://user-images.githubusercontent.com/14113155/145960737-97260b26-cdec-45b6-a60a-cd924427dc5f.png)

**Comment by minhng99** [comment]
@bluewavenet I can't seem to be able to reopen the issue

**Comment by bluewavenet** [comment]
@minhng99 
Interesting....
First look:
 * Client 5 is preauthenticated, so got there by triggering a redirect via its CPD. But this happened **before** client 1 was authenticated.
 * The attempted auth of client 5 happened **after** client 1 was authed and therefore failed.
 * In syslog at 08:03:29, client 1 was idle timed out and deauthed.
 * At syslog 08:04:52 client 1 was re-authed, this agrees with ndsctl status output session start time.
 * From dhcp.leases, client 5 has the correct IP address
 
My guess is the auth of 10.15.99.155 was done by the roaming functionality - now we need to figure out why....

**Comment by minhng99** [comment]
The pic #1 is the result after pic #4... which I've authenticated manually using the IP, before that both addresses are in the preauthenticated state

**Comment by bluewavenet** [comment]
It might be significant that `ip neigh` is only showing ipV6 entries for this mac address....

Is this a different site to that where this happened previously?

Is this openNDS v9.4.0?

**Comment by minhng99** [comment]
Yeah, `ip neigh` only showing ipv6 entry for that address

Yes, this is a different site, entirely different location but having the same hardware, firmware, configs...

No, v9.3.0

**Comment by bluewavenet** [comment]
9.4.0 checks the mac address is in the ipV4 arp table and 9.5.0 does more.... I'll look closer.

**Comment by bluewavenet** [comment]
@minhng99 @sicelo 
I am pretty sure I have found the cause.
When a client is deauthed, it is not removed from the client list, instead its firewall state is changed from authenticated to preauthenticated. It has always been like this and has not caused a problem - that is until pre-emptive authentication was introduced.

Now, if a client has been deauthed for any reason, then is pre-emptively re-authed (within the configured checkinterval period), it will inherit its previous details **_including its ip address_** as far as openNDS is concerned. Now if the dhcp allocated ip address is the same as before then there is no problem.

**But** if that previous ip address has been leased to some other client - we get this issue.

This is an easy fix and I will implement it and test. If all is well I will release it as v9.5.1.

**Comment by minhng99** [comment]
Nice!

**Comment by bluewavenet** [comment]
@minhng99 
https://github.com/openNDS/openNDS/releases/tag/v9.5.1
Let me know when you get a chance to try it ;-)

**Comment by minhng99** [comment]
The issue is still happening with the latest version, I'm testing it like this:

The client first joins the WiFi, received the IP `10.15.99.209` but has not tried to authenticate
![image](https://user-images.githubusercontent.com/14113155/147525336-d39a8c87-dba4-46c5-8477-9d7924fe55db.png)

The client then disconnect from WiFi, changed the IP to static with the IP `10.15.99.210` then try to authenticate
![image](https://user-images.githubusercontent.com/14113155/147525387-10393da3-6fb5-4a45-8fc7-80de72eca7f8.png)
![image](https://user-images.githubusercontent.com/14113155/147525412-d04d5f7b-496f-4c3e-a7eb-1e4393648f61.png)

In the syslog, I see that my custom authentication script has tried to authenticate with the Client's MAC address but for some reason, opennds still authenticate using the old IP address and not the new one which is the one supposed to be using:
![image](https://user-images.githubusercontent.com/14113155/147525496-f3011a52-35d5-4834-a4ba-8ab540607064.png)

And the client still does not have internet connection :(

Re-open pls @bluewavenet

**Comment by bluewavenet** [comment]
@minhng99 

> The client then disconnect from WiFi, changed the IP to static with the IP 10.15.99.210 then try to authenticate

Configuring a static ip on an already connected client will force openNDS to add the client to the preauthenticated client list for a second time, ie back to the original problem that **was** caused by pre-emptive authentication.

If you test again, this time doing a manual `ndsctl auth` instead of logging in, it should work (I hope!). Pre-emptive auth checks the arp table for the mac address and gets the active IP, deleting any preauthenticated entry in the client list before authenticating.
Should work ok then....

**Comment by minhng99** [comment]
Well... my "authentication script" is actually running `ndsctl auth [mac]`, I don't think there will be any difference.

**Comment by bluewavenet** [comment]
It is the setting of a different static IP that causes the problem in this case. If you set up the static IP **before** connecting, it would be ok.
Setting a static IP was how I first replicated the conditions that led to the initial problem. The original problem was actually caused by pre-emptive authentication not clearing any old preauthenticated entry in the client list.

**Comment by minhng99** [comment]
Yes, I did changed the IP before connecting to it, I was using my phone so set to static IP actually disconnect and reconnect the WiFi

**Comment by bluewavenet** [comment]
You can see from your `ndsctl status` output, both client 0 and client 1 are both Client Type:cpd_can
If the "static IP" client had been Client Type:preemptive, all would have been ok.

**Comment by bluewavenet** [comment]
A connection using a static IP would bypass your roaming function (it depends on dhcp triggering a preemptive auth).
It would be possible to block all static IPs from authentication.....

**Comment by minhng99** [comment]
I've tried many things and it still does not show "preemtive"

This is when I connected with the IP `10.15.99.15`, authenticated, disconnect wifi then join back with the IP `10.15.99.150`
![image](https://user-images.githubusercontent.com/14113155/147626804-7c98e1e7-d220-4f54-bb77-daec6f4ee02c.png)
![image](https://user-images.githubusercontent.com/14113155/147626820-7477c01a-4d09-4b12-b36d-b98ba23c22a9.png)
![image](https://user-images.githubusercontent.com/14113155/147626840-d83d3743-4b3a-4ad9-ace6-89f10a07f1ca.png)

I still think that this is an issue, it should not be failed to authenticate

**Comment by bluewavenet** [comment]
> I still think that this is an issue, it should not be failed to authenticate

I do see your point - But - Is it more a question of whether a static ip should be allowed and if it is, should it take precedence over a previous authentication using a dhcp allocated address? 

We maybe have two choices:
 * static ip address should be blocked
or
 * static ip should deauth all clients with same mac address before being authenticated

Either can be done, or maybe both with a config option to choose...
What do you think?
_(PS new release in the pipeline so will be good to add this in)_

**Comment by minhng99** [comment]
I think my roaming mechanism has something to do with this issue:
For example, the same building has 2 AP with the same SSID but are using a separated subnet `10.15.99.0/24`, the client first connects to the AP `A`, it received `10.15.99.100` and `Authenticated` but then it left the AP `A` and then connect to the AP `B` with the same SSID, it might have used the DHCP 50 to request its previous IP `10.15.99.100` on AP `B` but someone already occupied the IP `10.15.99.100` on AP `B`, it messed up the client list of opennds? In this case it will use whatever the IP from the new DHCP server on AP `B` allocated to it.

Ref: https://support.huawei.com/enterprise/en/doc/EDOC1100038342/660cffb7/dhcp-client-reuse-of-an-ip-address

**Comment by bluewavenet** [comment]
Yes that description is pretty much how I understand it.
You might possibly have a race condition between your roaming and the client CPD...

Perhaps a new "choice":
 * Before authentication, delete all client list entries that have the same mac, regardless of state.

**Comment by bluewavenet** [comment]
Or rather:
 *  Before authentication, delete all client list entries that have the same mac but different IP, regardless of state.

**Comment by minhng99** [comment]
> Before authentication, delete all client list entries that have the same mac but different IP, regardless of state.

Yeah that should work... no client should holding 2 ipv4 address for whatever the reason.... but I'm wondering how this could affecting ipv6? TBH I've never tried to setup ipv6 with opennds before

**Comment by bluewavenet** [comment]
> no client should holding 2 ipv4 address for whatever the reason

That is true although some IoT devices might have more than one, and it is common on some servers. It is good practice to use a different mac for every IP,  but .... I have seen bad practice :-(

For our applications though I will look at implementing:
 * Before authentication, delete all client list entries that have the same mac but different IP, regardless of state.

openNDS does not yet support ipv6. For it to work properly with ipv6, without "dirty tricks", client support for CPI (RFC8910 and RFC 8908) will have to be universally available instead of CPD. That is a long way away with very few clients currently supporting it and the RFCs only in draft.

**Comment by bluewavenet** [comment]
@minhng99 
For the next release, openNDS checks if an ip address has been allocated by dhcp and denies access if not.
This is required for RFC8910 operation.
It should also prevent this issue from occurring in future.

**Comment by bluewavenet** [comment]
@minhng99 @doctor-ox
v9.6.0 is now released and should prevent this from happening. Any feedback is welcome.
