### ISSUE TITLE
Local authentication with openNDS FAS

### ISSUE THREAD

**Issue by Moberaptor** [openNDS/openNDS#271]
Dear Team,
Thank you for a software your are developing!
Could you please help me to find how to setup a local authentication with openNDS.
I need to protect my home wi-fi access. I had setup an auth page with login and email by this steps (hope it could be useful for other users):
```
cp /usr/lib/opennds/theme_user-email-login-basic.sh /usr/lib/opennds/login.sh
chmod +x /usr/lib/opennds/login.sh
uci set opennds.@opennds[0].login_option_enabled='2'
uci set opennds.@opennds[0].themespec_path='/usr/lib/opennds/mythemespec.sh'
uci commit opennds
service opennds restart
```
So, it works fine but not really secure cause in this case openNDS accepts any login/email combinations (with logs but...). As I read openNDS has a local FAS and I don't need to setup FreeRADIUS (truth be told it will be weird and I think it is not the best way).
How to add user/pass (or user/email) local verification?
Many thanks!

Kind regards,
moberaptor

**Comment by bluewavenet** [comment]
@Moberaptor 
It looks like you are running OpenWrt, but could you please state what version, also what version of openNDS.
Also please state your target hardware.

To get the basic ThemeSpec scripts working you do not need to copy any files.

It might be worth reading the documentation, here:
https://opennds.readthedocs.io

Once you get the current version working correctly we can go through how you can add your own client validation against a database.

**Comment by Moberaptor** [comment]
Thank you for reply!
Sorry for smashing details. Yes, it is running on OpenWRT:
OpenWRT 21.02.1
openNDS 9.4.0-1
For test purposes it works on virtual machine now.

**Comment by bluewavenet** [comment]
Have you read the documentation? 
In particular you should read this:
https://opennds.readthedocs.io/en/stable/config.html#themespec-path

Then you will see what the configuration errors you have made that you need to fix before doing anything else.

You should have done this:
```
cp /usr/lib/opennds/theme_user-email-login-basic.sh /usr/lib/opennds/login.sh
chmod +x /usr/lib/opennds/login.sh
uci set opennds.@opennds[0].login_option_enabled='3'
uci set opennds.@opennds[0].themespec_path='/usr/lib/opennds/login.sh'
uci commit opennds
service opennds restart
```

This will still give the user/email login, but you will be in a position to begin making changes.
Once you have got this far, read in detail the code in your **_login.sh_** script file. See if you can follow the flow.

**Note:** ThemeSpec scripts are **_not_** stand alone scripts, they are called by openNDS and use library functions.

See if you can follow the logic until you get to landing_page()
Before library function auth_log() is called you will have to call a program or script of your own to do the required client validation against a database.
Feel free to ask questions after you have done the reading ;-)

**Note:**  Do not at this stage try to modify the html code - there are client driven restrictions you must comply with. Get it working first, then and only then make it look how you want.
Read this section:
https://opennds.readthedocs.io/en/stable/customize.html#rules-for-customised-splash-pages

**Comment by Moberaptor** [comment]
Thank you for reply!
Yes, I've read documentation multiple times and very sorry, it was a typo in the script name. I've set login_option_enabled='3' and check html code as you recommended. In general I could say that I understand general logic but I'm not a web-developer.

> Before library function auth_log() is called you will have to call a program or script of your own to do the required client validation against a database.
Does it mean that I should setup something like FreeRadius or something like this cause we should call a program or script?

How I could reset all connections? After changes above, captive portal works only by direct link:
http://10.8.0.1:2050/opennds_preauth/?fas=aGlkPTZvZWVkZTU2NmE4ODg4NWYyMTU4OTVhNGNkOTYwMWNjYWJiNTZlNjAyNWI0YzgwZDgzYTVmMDI1MmE0ZDAxODksIGNsaFjPTAwOjBjOjI5OjlhOmYwOmM1LCBnYXRld2F5bmFtZT1vcGVuTkRTLCB2ZXJzaW9uPTkuNC4wLCBnYXRld2F5YWRkcmVzcz0xMC44LjAuMToyMDUwLmLCBvcmlnaW51cmw9aHR0cCUzYSUyZiUyZnN0YXR1cy5jbGllbnQlMmYsIGNsaWVudGlmPWJyLWxhbiwgdGhlbWVzcGVjPS91c3IvbGliL29wZW5uZHMvbG9naW4uc2gsIChudWxsKShudWxsKShudWxsKShudWxsKQ==

**Comment by bluewavenet** [comment]
@Moberaptor 
You should never access the portal directly. It will not do any harm but will not work correctly.
Instead you can access http://status.client
If you want to view all connections you can run:
`ndsctl status`
or
`ndsctl json`

If you want to deauthenticate a particular connection:
`ndsctl deauth [client-ipaddress]`
or 
`ndsctl deauth [client-macaddress]`

If you want to clear ALL connections, do:
`service opennds restart`

> Does it mean that I should setup something like FreeRadius or something like this cause we should call a program or script?

Radius in my opinion is a cumbersome legacy protocol. It should only be used in large corporate environments where a radius system is pre-existing and corporate policy does not allow use of anything else.

For the purposes of an academic exercise you could set up FreeRadius but I would not recommend it for anything other than the case I mentioned above.

However you do it, you just need to call a custom program from your script.

Here is an extract from theme_user-email-login-basic.sh :
```
landing_page() {
	originurl=$(printf "${originurl//%/\\x}")

	# Add the user credentials to $userinfo for the log
	userinfo="$userinfo, user=$username, email=$emailaddress"

	# authenticate and write to the log - returns with $ndsstatus set
	auth_log

```

Modify it like this:
```
landing_page() {
	originurl=$(printf "${originurl//%/\\x}")

	# Add the user credentials to $userinfo for the log
	userinfo="$userinfo, user=$username, email=$emailaddress"

        #Validate the credentials:
        validated=$("/user/lib/opennds/moperaptor_validate $userinfo")

        if [ "$validated" = "yes" ]; then        
	        # authenticate and write to the log - returns with $ndsstatus set
	        auth_log
        else
                ndsstatus" = "denied"
        fi

```

Where `/user/lib/opennds/moperaptor_validate` is a program or script you have written to validate the client's credentials.
