### ISSUE TITLE
[Question]  DHCP option 114 as described in RFC7710bis

### ISSUE THREAD

**Issue by arky** [openNDS/openNDS#277]
Does openNDS support sending DHCP option 114 (RFC7710bis)? This feature is now adopted by both Android (https://developer.android.com/about/versions/11/features/captive-portal) and IOS. Thanks!

**Comment by arky** [comment]
Reading through the docs, I stumble upon this. Thanks! 

https://opennds.readthedocs.io/en/stable/config.html#dhcp-option-114-enable-rfc8910

**Comment by bluewavenet** [comment]
@arky 
See also:
https://opennds.readthedocs.io/en/stable/howitworks.html#captive-portal-identification-cpi-rfc-8910

Note that:

- RFC7710bis is superseded by RFC8910
- RFC8910 is supported from openNDS v9.4.0 onwards
- RFC8910/RFC8908 is supported from openNDS v9.5.0 onwards
- RFC8910/RFC8908 are both draft standards and possibly subject to change, so the openNDS support should be regarded as "experimental".

As no actual client devices with support could be identified, testing was carried out using Linux clients running custom test software.

There are issues of interpretation of the proposed RFC8910/RFC8908 standards that must be resolved to guarantee that client device vendors produce a universally useable implementation on the client side.

In addition, I am not aware of any other Captive Portals with support yet, so it is a case of _"What comes first, the chicken or the egg?"_

**Any testing you can do will be very welcome!**

**Comment by arky** [comment]
@bluewavenet Kudos for implementing this! 

I am going switch to using OpenNDS going forward on GL-iNet AR300M-Lite OpenWRT devices (mipsel_24kc) and using Android One running Android 11.

**Comment by bluewavenet** [comment]
@arky 
The AR300M-Lite is fine (but note it is mips_24kc not mipsel). Bare in mind it is no longer manufactured though and the defaults after an OpenWrt reflash mean you cannot access it, so you have to build your own image with Imagebuilder to get it working.
I now use the MT300N-V2 as it is readily available, and actually has better performance, particularly where wireless range is concerned.

**Comment by arky** [comment]
@bluewavenet Gotcha! Those devices are what I have handy for a prototype of offline digital library that I am building. 

When I have some budget I'll definitely go for newer MT300N-V2. 

BTW did offline captive portal support land in the https://github.com/openNDS/openNDS/releases/tag/v9.5.0 release?

**Comment by bluewavenet** [comment]
@arky 

> did offline captive portal support land in the https://github.com/openNDS/openNDS/releases/tag/v9.5.0 release?

Autonomous offline/online switching has been considered but has always been a low priority so no further work has been done on it. However v9.5.0 now has functioning online/offline detection so this opens the possibility of a type of "hotplug configuration" method.... might be fairly trivial to implement....

However for your application, a simple Dnsmasq config is probably good enough.
