### ISSUE TITLE
FATAL: Could not open configuration file '/etc/opennds/opennds.conf'

### ISSUE THREAD

**Issue by yassin-git** [openNDS/openNDS#281]
hello , 
i got this error FATAL: Could not open configuration file '/etc/opennds/opennds.conf' can anyone help me, please

**Comment by bluewavenet** [comment]
Can you please state:
 * hardware you are using for openNDS
 * operating system and version you are using for openNDS
 * The version of openNDS you are using

**Comment by yassin-git** [comment]
i am using openNDS (latest version ) running on OpenWRT (latest version ) on raspberry pie 3 model B

**Comment by bluewavenet** [comment]
@yassin-git 

By "latest version", I assume:
 * OpenWrt 21.02.1
 * openNDS 9.5.1

> FATAL: Could not open configuration file '/etc/opennds/opennds.conf

This error message is an indication of either an incorrect installation or an incorrect startup.
Where and when to you see it?

Please show the output of:
`uci show opennds`

**Comment by bluewavenet** [comment]
@yassin-git 
Running on OpenWrt, this error should not occur unless you have a faulty install or try to start manually.
OpenNDS must be run as a service.

Try the following:
`service opennds restart`

Then show the output of:
`logread -e opennds`

**Comment by yassin-git** [comment]
Sun Dec 19 21:12:47 2021 daemon.notice opennds[15386]: openNDS Version 9.4.0 is                                                                                         in startup
Sun Dec 19 21:12:47 2021 daemon.notice opennds[15386]: MHD version is 0.9.71
Sun Dec 19 21:12:47 2021 daemon.notice opennds[15386]: Attempting to Bind to int                                                                                        erface: br-lan
Sun Dec 19 21:12:47 2021 daemon.notice opennds[15386]: Interface br-lan is up
Sun Dec 19 21:12:47 2021 daemon.notice opennds[15386]: Interface br-lan is at 19                                                                                        2.168.1.10 (b8:27:eb:88:50:a0)
Sun Dec 19 21:12:47 2021 daemon.err opennds[15386]: Routing configuration is not                                                                                         valid for openNDS, exiting ...
Sun Dec 19 21:12:52 2021 daemon.notice opennds[15463]: openNDS Version 9.4.0 is                                                                                         in startup
Sun Dec 19 21:12:52 2021 daemon.notice opennds[15463]: MHD version is 0.9.71
Sun Dec 19 21:12:52 2021 daemon.notice opennds[15463]: Attempting to Bind to int                                                                                        erface: br-lan
Sun Dec 19 21:12:52 2021 daemon.notice opennds[15463]: Interface br-lan is up
Sun Dec 19 21:12:52 2021 daemon.notice opennds[15463]: Interface br-lan is at 19                                                                                        2.168.1.10 (b8:27:eb:88:50:a0)
Sun Dec 19 21:12:52 2021 daemon.err opennds[15463]: Routing configuration is not                                                                                         valid for openNDS, exiting ...
Sun Dec 19 21:12:55 2021 daemon.notice opennds[15550]: openNDS Version 9.4.0 is                                                                                         in startup
Sun Dec 19 21:12:55 2021 daemon.notice opennds[15550]: MHD version is 0.9.71
Sun Dec 19 21:12:55 2021 daemon.notice opennds[15550]: Attempting to Bind to int                                                                                        erface: br-lan
Sun Dec 19 21:12:55 2021 daemon.notice opennds[15550]: Interface br-lan is up
Sun Dec 19 21:12:55 2021 daemon.notice opennds[15550]: Interface br-lan is at 19                                                                                        2.168.1.10 (b8:27:eb:88:50:a0)
Sun Dec 19 21:12:55 2021 daemon.err opennds[15550]: Routing configuration is not                                                                                         valid for openNDS, exiting ...
Sun Dec 19 21:13:00 2021 daemon.notice opennds[15627]: openNDS Version 9.4.0 is                                                                                         in startup
Sun Dec 19 21:13:01 2021 daemon.notice opennds[15627]: MHD version is 0.9.71
Sun Dec 19 21:13:01 2021 daemon.notice opennds[15627]: Attempting to Bind to int                                                                                        erface: br-lan
Sun Dec 19 21:13:01 2021 daemon.notice opennds[15627]: Interface br-lan is up
Sun Dec 19 21:13:01 2021 daemon.notice opennds[15627]: Interface br-lan is at 19                                                                                        2.168.1.10 (b8:27:eb:88:50:a0)
Sun Dec 19 21:13:01 2021 daemon.err opennds[15627]: Routing configuration is not                                                                                         valid for openNDS, exiting ...
Sun Dec 19 21:13:06 2021 daemon.notice opennds[15681]: openNDS Version 9.4.0 is                                                                                         in startup
Sun Dec 19 21:13:06 2021 daemon.notice opennds[15681]: MHD version is 0.9.71
Sun Dec 19 21:13:06 2021 daemon.notice opennds[15681]: Attempting to Bind to int                                                                                        erface: br-lan
Sun Dec 19 21:13:06 2021 daemon.notice opennds[15681]: Interface br-lan is up
Sun Dec 19 21:13:06 2021 daemon.notice opennds[15681]: Interface br-lan is at 19                                                                                        2.168.1.10 (b8:27:eb:88:50:a0)
Sun Dec 19 21:13:06 2021 daemon.err opennds[15681]: Routing configuration is not                                                                                         valid for openNDS, exiting ...
Sun Dec 19 21:13:11 2021 daemon.notice opennds[15735]: openNDS Version 9.4.0 is                                                                                         in startup
Sun Dec 19 21:13:11 2021 daemon.notice opennds[15735]: MHD version is 0.9.71
Sun Dec 19 21:13:11 2021 daemon.notice opennds[15735]: Attempting to Bind to int                                                                                        erface: br-lan
Sun Dec 19 21:13:11 2021 daemon.notice opennds[15735]: Interface br-lan is up
Sun Dec 19 21:13:11 2021 daemon.notice opennds[15735]: Interface br-lan is at 19                                                                                        2.168.1.10 (b8:27:eb:88:50:a0)
Sun Dec 19 21:13:11 2021 daemon.err opennds[15735]: Routing configuration is not                                                                                         valid for openNDS, exiting ...
Sun Dec 19 21:13:11 2021 daemon.info procd: Instance opennds::cfg01995c s in a c                                                                                        rash loop 6 crashes, 0 seconds since last crash
Sun Dec 19 21:14:27 2021 daemon.notice opennds[15879]: openNDS Version 9.4.0 is                                                                                         in startup
Sun Dec 19 21:14:28 2021 daemon.notice opennds[15879]: MHD version is 0.9.71
Sun Dec 19 21:14:28 2021 daemon.notice opennds[15879]: Attempting to Bind to int                                                                                        erface: br-lan
Sun Dec 19 21:14:28 2021 daemon.notice opennds[15879]: Interface br-lan is up
Sun Dec 19 21:14:28 2021 daemon.notice opennds[15879]: Interface br-lan is at 19                                                                                        2.168.1.10 (b8:27:eb:88:50:a0)
Sun Dec 19 21:14:28 2021 daemon.err opennds[15879]: Routing configuration is not                                                                                         valid for openNDS, exiting ...
Sun Dec 19 21:14:28 2021 daemon.info procd: Instance opennds::cfg01995c s in a c                                                                                        rash loop 7 crashes, 0 seconds since last crash
Sun Dec 19 21:21:33 2021 daemon.notice opennds[16050]: openNDS Version 9.4.0 is                                                                                         in startup
Sun Dec 19 21:21:33 2021 daemon.err opennds[16050]: /tmp/etc/opennds_cfg01995c.c                                                                                        onf: line 16: Bad configuration option: tcp
Sun Dec 19 21:21:33 2021 daemon.err opennds[16050]: Bad option tcp parsing Firew                                                                                        allRuleSet on line 16 in /tmp/etc/opennds_cfg01995c.conf
Sun Dec 19 21:21:33 2021 daemon.err opennds[16050]: Exiting...
Sun Dec 19 21:21:33 2021 daemon.info procd: Instance opennds::cfg01995c s in a c                                                                                        rash loop 8 crashes, 0 seconds since last crash
Sun Dec 19 21:22:01 2021 daemon.notice opennds[16132]: openNDS Version 9.4.0 is                                                                                         in startup
Sun Dec 19 21:22:01 2021 daemon.err opennds[16132]: /tmp/etc/opennds_cfg01995c.c                                                                                        onf: line 16: Bad configuration option: tcp
Sun Dec 19 21:22:01 2021 daemon.err opennds[16132]: Bad option tcp parsing Firew                                                                                        allRuleSet on line 16 in /tmp/etc/opennds_cfg01995c.conf
Sun Dec 19 21:22:01 2021 daemon.err opennds[16132]: Exiting...
Sun Dec 19 21:22:06 2021 daemon.notice opennds[16174]: openNDS Version 9.4.0 is                                                                                         in startup
Sun Dec 19 21:22:06 2021 daemon.err opennds[16174]: /tmp/etc/opennds_cfg01995c.c                                                                                        onf: line 16: Bad configuration option: tcp
Sun Dec 19 21:22:06 2021 daemon.err opennds[16174]: Bad option tcp parsing Firew                                                                                        allRuleSet on line 16 in /tmp/etc/opennds_cfg01995c.conf
Sun Dec 19 21:22:06 2021 daemon.err opennds[16174]: Exiting...
Sun Dec 19 21:22:11 2021 daemon.notice opennds[16183]: openNDS Version 9.4.0 is                                                                                         in startup
Sun Dec 19 21:22:11 2021 daemon.err opennds[16183]: /tmp/etc/opennds_cfg01995c.c                                                                                        onf: line 16: Bad configuration option: tcp
Sun Dec 19 21:22:11 2021 daemon.err opennds[16183]: Bad option tcp parsing Firew                                                                                        allRuleSet on line 16 in /tmp/etc/opennds_cfg01995c.conf
Sun Dec 19 21:22:11 2021 daemon.err opennds[16183]: Exiting...
Sun Dec 19 21:22:16 2021 daemon.notice opennds[16192]: openNDS Version 9.4.0 is                                                                                         in startup
Sun Dec 19 21:22:16 2021 daemon.err opennds[16192]: /tmp/etc/opennds_cfg01995c.c                                                                                        onf: line 16: Bad configuration option: tcp
Sun Dec 19 21:22:16 2021 daemon.err opennds[16192]: Bad option tcp parsing Firew                                                                                        allRuleSet on line 16 in /tmp/etc/opennds_cfg01995c.conf
Sun Dec 19 21:22:16 2021 daemon.err opennds[16192]: Exiting...
Sun Dec 19 21:22:21 2021 daemon.notice opennds[16202]: openNDS Version 9.4.0 is                                                                                         in startup
Sun Dec 19 21:22:21 2021 daemon.err opennds[16202]: /tmp/etc/opennds_cfg01995c.c                                                                                        onf: line 16: Bad configuration option: tcp
Sun Dec 19 21:22:21 2021 daemon.err opennds[16202]: Bad option tcp parsing Firew                                                                                        allRuleSet on line 16 in /tmp/etc/opennds_cfg01995c.conf
Sun Dec 19 21:22:21 2021 daemon.err opennds[16202]: Exiting...
Sun Dec 19 21:22:26 2021 daemon.notice opennds[16211]: openNDS Version 9.4.0 is                                                                                         in startup
Sun Dec 19 21:22:26 2021 daemon.err opennds[16211]: /tmp/etc/opennds_cfg01995c.c                                                                                        onf: line 16: Bad configuration option: tcp
Sun Dec 19 21:22:26 2021 daemon.err opennds[16211]: Bad option tcp parsing Firew                                                                                        allRuleSet on line 16 in /tmp/etc/opennds_cfg01995c.conf
Sun Dec 19 21:22:26 2021 daemon.err opennds[16211]: Exiting...
Sun Dec 19 21:22:26 2021 daemon.info procd: Instance opennds::cfg01995c s in a c                                                                                        rash loop 6 crashes, 0 seconds since last crash
Mon Dec 20 15:11:55 2021 daemon.notice opennds[17911]: openNDS Version 9.4.0 is                                                                                         in startup
Mon Dec 20 15:11:55 2021 daemon.err opennds[17911]: /tmp/etc/opennds_cfg01995c.c                                                                                        onf: line 16: Bad configuration option: tcp
Mon Dec 20 15:11:55 2021 daemon.err opennds[17911]: Bad option tcp parsing Firew                                                                                        allRuleSet on line 16 in /tmp/etc/opennds_cfg01995c.conf
Mon Dec 20 15:11:55 2021 daemon.err opennds[17911]: Exiting...

**Comment by bluewavenet** [comment]
Did you read any of the logs?

` @Sun Dec 19 21:12:52 2021 daemon.err opennds[15463]: Routing configuration is not valid for openNDS, exiting ...`

Show the output of:
`uci show network'

**Comment by yassin-git** [comment]
yes . in fact i couldn't understand the error 
and this is the result of uci show network
root@OpenWrt:~# uci show network
network.loopback=interface
network.loopback.device='lo'
network.loopback.proto='static'
network.loopback.ipaddr='127.0.0.1'
network.loopback.netmask='255.0.0.0'
network.globals=globals
network.globals.ula_prefix='fd3d:46eb:63d4::/48'
network.@device[0]=device
network.@device[0].name='br-lan'
network.@device[0].type='bridge'
network.@device[0].ports='eth0'
network.lan=interface
network.lan.proto='static'
network.lan.netmask='255.255.255.0'
network.lan.ip6assign='60'
network.lan.gateway='192.168.1.1'
network.lan.ipaddr='192.168.1.10'
network.lan.dns='8.8.8.8' '8.8.4.4'
network.lan.device='br-lan'
network.wwan=interface
network.wwan.ipaddr='192.168.2.1'
network.wwan.netmask='255.255.255.0'
network.wwan.gateway='192.168.1.1'
network.wwan.type='bridge'
network.wwan.proto='static'
network.wwan.device='wlan0-1'
network.wwan.dns='8.8.8.8' '8.8.4.4'
network.repeater_bridge=interface
network.repeater_bridge.proto='relay'
network.repeater_bridge.network='lan' 'wwan'
network.repeater_bridge.ipaddr='192.168.1.10'
network.wwan1=interface
network.wwan1.proto='dhcp'

**Comment by yassin-git** [comment]
i am making Wi-Fi extender / repeater / bridge configuration
on my raspberry pie which is connected to my router

**Comment by yassin-git** [comment]
https://openwrt.org/docs/guide-user/network/wifi/relay_configuration

i did this configuration

**Comment by bluewavenet** [comment]
@yassin-git 

> i did this configuration

Unfortunately this type of configuration is incompatible with openNDS or any type of captive portal for that matter.

To read about the prerequisites, see here:
https://opennds.readthedocs.io/en/stable/install.html#prerequisites

I assume you want to provide a "guest" network in an extended area using the feed from your ISP router.
This is easy to achieve but you must go about it in a different way.

However a Raspberry Pi is not a good choice for this as it does not make a very good router as its network I/O is very limited. The built in wireless is very poor for a router, being aimed at "IoT" or "workstation" applications. It has low range and sensitivity. It supports only a limited set of wireless modes and does not support more than one simultaneously, ruling it out for extender/repeater wireless only operation.

For an **advanced academic** project, you could do something with a Pi, but it would never be very satisfactory in use.
I would suggest choosing a low cost OpenWrt compatible router hardware for this. It will easier to implement and in the long run will be much more reliable. 

Let me know if you want more information or some hints on implementation.

**Comment by yassin-git** [comment]
Thank you very much .
I would like to ask you about the implementation of your suggested solution because it's really an academic project.
Second, I would like to ask you if I could build my own captive portal by setting rules among the firewall to forward network packets to a specific local webpage.

**Comment by bluewavenet** [comment]
@yassin-git 

> I could build my own captive portal

A captive portal is more than just firewall settings, but yes you could theoretically "build your own". For it to work you would have to have in depth knowledge of how it all fits together and works with the standards implemented on all modern devices.
You could start by reading https://opennds.readthedocs.io/en/stable/howitworks.html#how-opennds-nds-works
It is not a trivial task to create a captive portal from scratch. 

> I would like to ask you about the implementation of your suggested solution

Do you mean using a low cost OpenWrt compatible router?

**Comment by yassin-git** [comment]
> Do you mean using a low cost OpenWrt compatible router?

yes please

**Comment by bluewavenet** [comment]
@yassin-git 
There are many good quality OpenWrt compatible routers to choose from.
You should take a look here:
https://openwrt.org/toh/start
Something with a minimum of 16MB Flash and 128MB RAM should do well at a good price.

I do not know where you are located but this one is available in most countries:
https://www.gl-inet.com/products/gl-mt300n-v2/#specs

It has 16/128MB and built in high quality multi mode class wireless.
An advantage of this one (mt300n-v2) is that it is USB powered and can be run from the USB connector found on most ISP routers. The usb on most ISP routers is designed to support an LTE dongle or usb hard drive so usually will have plenty of power reserve.

The mt300n-v2 has two ethernet ports labelled "wan" and "lan". You would connect the supplied ethernet cable from the wan port to a "lan" port on your isp router and the usb lead from "power" to the usb port on the isp router. You can then reflash with OpenWrt 21.2.1, connect your computer to the lan port, ssh to the mt300n-v2, turn on wifi, set a unique ip subnet, install openNDS, and you will be up and running in minutes.

Then you can then tune your installation however you want, such as setting up a wireless wan connection instead of the ethernet link to the isp router, customise the splash page sequence connecting guests will see etc. etc..

**Comment by yassin-git** [comment]
thank you for your advice .
Now, if i want to build my own captive portal on raspberry pie what should I do after reading how captive portal work ??

**Comment by bluewavenet** [comment]
@yassin-git 

> Now, if i want to build my own captive portal on raspberry pi

Do you mean develop your own software or do you mean customise openNDS?

As I mentioned before, do not do anything serious for captive portal on a RPi, it is not worth the effort, and if you do make the effort, the results will be sub standard unless you spend a fortune on wireless access points and managed switches.

**Comment by yassin-git** [comment]
> Do you mean develop your own software or do you mean customise openNDS?

if customizing is much better and easier  then i will go for it .
