### ISSUE TITLE
Opennds kernel error 

### ISSUE THREAD

**Issue by deivisonmoraes** [openNDS/openNDS#286]
Hi,
I am with a strange behavior in my tests, after practically finishing the router with opennds when testing in production it started to show some kernel failures causing opennds to restart.
follow the log...

root@OpenWrt:~# logread -f -e opennds
Thu Dec 23 11:06:24 2021 daemon.info opennds[1747]: Network Authentication Required - page_511 html generated for [192.168.1.147]
Thu Dec 23 11:06:24 2021 daemon.notice opennds[1747]: Adding 192.168.1.147 1e:0e:73:e6:bd:11 token 80f93cc5 to client list
Thu Dec 23 11:06:24 2021 kern.info kernel: [  694.620690] ra  = 0040ab5f in opennds[400000+19000]
Thu Dec 23 11:06:29 2021 daemon.notice opennds[4708]: openNDS Version 9.5.1 is in startup
Thu Dec 23 11:06:29 2021 daemon.info opennds[4708]: Added Walled Garden FQDN [facebook.com] to list
Thu Dec 23 11:06:29 2021 daemon.info opennds[4708]: Added Walled Garden FQDN [fbcdn.net] to list
Thu Dec 23 11:06:29 2021 daemon.info opennds[4708]: Added Walled Garden port [443] to list
Thu Dec 23 11:06:29 2021 daemon.info opennds[4708]: Done reading configuration file '/tmp/etc/opennds_cfg01995c.conf'
Thu Dec 23 11:06:29 2021 daemon.info opennds[4708]: Initializing signal handlers
Thu Dec 23 11:06:29 2021 daemon.info opennds[4708]: tmpfs mountpoint is [/tmp]

I saw that there were some open issues with something similar but I couldn't find a solution.

I'm using openwrt 21.02 image builder
opennds - 9.5.1-1
kernel 5.10.87

**Comment by bluewavenet** [comment]
@deivisonmoraes 
Can you please show:
 * The hardware are you using
 * The output of `free`
 * The output of `uci show opennds`
 
It seems to be happening just after adding a client to the client list. Do some clients get authenticated, or does this happen every time?

> I saw that there were some open issues with something similar

Which ones?

**Comment by deivisonmoraes** [comment]
@bluewavenet Hi, tks for help.

I'm Using a c20v4 
oot@OpenWrt:~# free 
              total        used        free      shared  buff/cache   available
Mem:          57140       18392       23784         272       14964       18804
Swap:             0           0           0

root@OpenWrt:~# uci show opennds
opennds.@opennds[0]=opennds
opennds.@opennds[0].enabled='1'
opennds.@opennds[0].debuglevel='2'
opennds.@opennds[0].fwhook_enabled='1'
opennds.@opennds[0].login_option_enabled='0'
opennds.@opennds[0].maxclients='250'
opennds.@opennds[0].fasport='80'
opennds.@opennds[0].fasremotefqdn='login.superzone.com.br'
opennds.@opennds[0].fasremoteip='179.107.112.11'
opennds.@opennds[0].faspath='/login'
opennds.@opennds[0].fas_secure_enabled='1'
opennds.@opennds[0].walledgarden_fqdn_list='facebook.com fbcdn.net'
opennds.@opennds[0].walledgarden_port_list='443'
opennds.@opennds[0].users_to_router='allow tcp port 53' 'allow udp port 53' 'allow udp port 67' 'allow tcp port 22' 'allow tcp port 80' 'allow tcp port 8080' 'allow tcp port 443'

Some clients connect, it usually doesn't happen with just one. A situation that I'm also investigating is that every 5 minutes I run a script to send the information from ndsctl to fas via curl in post method.

Do you think this could be a problem?
The script like this:
curl -s -X POST $URL -H 'Content-Type: application/json' -d "$(ndsctl json)"`


[]'s

**Comment by deivisonmoraes** [comment]
Thu Dec 23 13:10:59 2021 daemon.notice opennds[7087]: Adding 192.168.1.236 70:bb:e9:e9:f8:e5 token f3dd48a0 to client list
Thu Dec 23 13:11:03 2021 daemon.info opennds[7087]: Network Authentication Required - page_511 html generated for [192.168.1.236]
Thu Dec 23 13:11:12 2021 daemon.info opennds[7087]: Client @ 192.168.1.147 1e:0e:73:e6:bd:11, quotas:
Thu Dec 23 13:11:12 2021 daemon.info opennds[7087]:     Download DATA quota (kBytes): 0, used: 15887
Thu Dec 23 13:11:12 2021 daemon.info opennds[7087]:     Upload DATA quota (kBytes): 0, used: 4787
Thu Dec 23 13:11:12 2021 daemon.info opennds[7087]: Client @ 192.168.1.171 02:15:ff:62:c5:c2, quotas:
Thu Dec 23 13:11:12 2021 daemon.info opennds[7087]:     Download DATA quota (kBytes): 0, used: 42518
Thu Dec 23 13:11:12 2021 daemon.info opennds[7087]:     Upload DATA quota (kBytes): 0, used: 2332
Thu Dec 23 13:11:12 2021 daemon.info opennds[7087]:     Download RATE quota (kbits/s): 0, Current average download rate (kbits/s): 29
Thu Dec 23 13:11:12 2021 daemon.info opennds[7087]:     Upload RATE quota (kbits/s): 0, Current average upload rate (kbits/s): 5
Thu Dec 23 13:11:12 2021 daemon.info opennds[7087]: Client @ 192.168.1.243 42:04:77:6b:3f:7e, quotas:
Thu Dec 23 13:11:12 2021 daemon.info opennds[7087]:     Download DATA quota (kBytes): 0, used: 95718
Thu Dec 23 13:11:12 2021 daemon.info opennds[7087]:     Upload DATA quota (kBytes): 0, used: 42255
Thu Dec 23 13:11:12 2021 daemon.info opennds[7087]:     Download RATE quota (kbits/s): 0, Current average download rate (kbits/s): 23
Thu Dec 23 13:11:12 2021 daemon.info opennds[7087]:     Upload RATE quota (kbits/s): 0, Current average upload rate (kbits/s): 1
Thu Dec 23 13:11:12 2021 daemon.info opennds[7087]: Client @ 192.168.1.245 8e:6c:9e:9c:b7:42, quotas:
Thu Dec 23 13:11:12 2021 daemon.info opennds[7087]:     Download DATA quota (kBytes): 0, used: 247629
Thu Dec 23 13:11:12 2021 daemon.info opennds[7087]:     Upload DATA quota (kBytes): 0, used: 10914
Thu Dec 23 13:11:12 2021 daemon.info opennds[7087]:     Download RATE quota (kbits/s): 0, Current average download rate (kbits/s): 884
Thu Dec 23 13:11:12 2021 daemon.info opennds[7087]:     Upload RATE quota (kbits/s): 0, Current average upload rate (kbits/s): 59
Thu Dec 23 13:11:12 2021 daemon.info opennds[7087]: Client @ 192.168.1.216 46:14:47:b7:ed:0d, quotas:
Thu Dec 23 13:11:12 2021 daemon.info opennds[7087]:     Download DATA quota (kBytes): 0, used: 168644
Thu Dec 23 13:11:12 2021 daemon.info opennds[7087]:     Upload DATA quota (kBytes): 0, used: 8586
Thu Dec 23 13:11:12 2021 daemon.info opennds[7087]: Client @ 192.168.1.233 7a:1f:96:19:8c:df, quotas:
Thu Dec 23 13:11:12 2021 daemon.info opennds[7087]:     Download DATA quota (kBytes): 0, used: 132958
Thu Dec 23 13:11:12 2021 daemon.info opennds[7087]:     Upload DATA quota (kBytes): 0, used: 7511
Thu Dec 23 13:11:12 2021 daemon.info opennds[7087]:     Download RATE quota (kbits/s): 0, Current average download rate (kbits/s): 192
Thu Dec 23 13:11:12 2021 daemon.info opennds[7087]:     Upload RATE quota (kbits/s): 0, Current average upload rate (kbits/s): 7
Thu Dec 23 13:11:20 2021 kern.info kernel: [ 8190.422297] ra  = 0040ab5f in opennds[400000+19000]
Thu Dec 23 13:11:25 2021 daemon.notice opennds[21622]: openNDS Version 9.5.1 is in startup


I took the execution of my script and was connecting one by one each device. When it reached 7 it gave the error and restarted opendns

**Comment by bluewavenet** [comment]
@deivisonmoraes 
From the last log you posted it looks more likely the crash is happening randomly. Is it when your script runs?

How are you running the script?

..

> I took the execution of my script and was connecting one by one each device.

I don't understand what you mean by this.

..

> When it reached 7 it gave the error and restarted opendns

Do you mean the seventh time your script ran?

Does it work without problems if you do not run your script?

**Comment by deivisonmoraes** [comment]
I'm sorry I'm not running the script anymore. I did the tests with pure opennds only. The problem occurs even without running my script. It seems to me that after connecting some devices the problem happens.

**Comment by bluewavenet** [comment]
@deivisonmoraes 
If you put the example script on your server (fas-hid.php), and point to it in your test config, does the problem still occur?

**Comment by bluewavenet** [comment]
@deivisonmoraes 
I have set up fas-hid.php on my server and cannot replicate your issue so far.

It would be very useful if you could test using fas-hid.php. It would allow us to hopefully identify what is causing the problem, or at lease eliminate areas that are not the cause.

**Comment by deivisonmoraes** [comment]
Hello @bluewavenet, I did a test with the setting "login_option_enabled 1", more simple.

That way you don't use fas.
I made a connection and it only worked with the default accept to continue pages. I disconnected from the wifi, restarted opennds to change the debug and when I tried to connect again I had the same problem.

Tue Dec 28 12:45:51 2021 daemon.notice opennds[7540]: Adding 192.168.1.147 1e:0e:73:e6:bd:11 token ce43d6e7 to client list
Tue Dec 28 12:45:53 2021 daemon.info opennds[7540]: Network Authentication Required - page_511 html generated for [192.168.1.147]
Tue Dec 28 12:45:59 2021 kern.info kernel: [ 484.124155] ra = 0040ab5f in opennds[400000+19000]

I will attach the device screen image.

**Comment by deivisonmoraes** [comment]
![image](https://user-images.githubusercontent.com/5691097/147568039-4bff42c9-d7b5-47b3-82a8-9b5066e92638.png)

**Comment by deivisonmoraes** [comment]
Configuration:

oot@OpenWrt:~# cat /tmp/etc/opennds_cfg01995c.conf 
# auto-generated config file from /etc/config/opennds
debuglevel 2
maxclients 250
login_option_enabled 1
fasport 80
fasremotefqdn login.superzone.com.br
fasremoteip 179.107.112.11
faspath /login
fas_secure_enabled 1
walledgarden_fqdn_list facebook.com fbcdn.net
walledgarden_port_list 443
FirewallRuleSet authenticated-users {
}
FirewallRuleSet preauthenticated-users {
}
FirewallRuleSet users-to-router {
  FirewallRule allow tcp port 53
  FirewallRule allow udp port 53
  FirewallRule allow udp port 67
  FirewallRule allow tcp port 22
  FirewallRule allow tcp port 80
  FirewallRule allow tcp port 8080
  FirewallRule allow tcp port 443
}
FirewallRuleSet trusted-users {
}
FirewallRuleSet trusted-users-to-router {
}

**Comment by bluewavenet** [comment]
@deivisonmoraes 
I see from your client device screenshot that you have both mobile data and wifi enabled.
This will mean the device CPD will detect the Interenet via mobile data and not trigger the portal login sequence.
I assume this is why you have used the openNDS gateway either directly or via the client status url. (this is why you have the `Network Authentication Required - page_511 html generated` message in your syslog.

I am unable to replicate this issue in any way.
Have you modified in any way the file `/usr/lib/opennds/client_params.sh` ?

You might have some sort of memory failure in your router.... this could cause similar results.

Perhaps set debuglevel to 3 and see if we get any more insight into this.

**Comment by deivisonmoraes** [comment]
@bluewavenet 
I will do the new tests with the data disabled to avoid doubts. My device is new, I only updated to make this application but I will use another device to check this question. The default opennds scripts settings have not been changed.

One question, what is your test environment? Because I can create something similar for us to test in similar environments.

**Comment by bluewavenet** [comment]
@deivisonmoraes 
What do you mean by "data disabled"?
Try debuglevel 3 to see if we get any more information about what happens.

I am currently set up to test with:
 * Gl-inet MT300N-V2 (128MB Ram, 16MB Flash)
 * OpenWrt 21.2.1
 * openNDS v9.5.1 or v9.5.2beta (changed in seconds as required)
 * option login_option_enabled '1'

**Comment by deivisonmoraes** [comment]
@bluewavenet **Hi, I changed equipment, now I put a tplink 210 CPE. At first, when trying to log in with the first device, the error already occurred. But I was using method 0 with my fas. 
Logging:**


Wed Dec 29 19:17:06 2021 daemon.debug opennds[4167]: send_redirect_temp: Queueing response for 192.168.1.147, 1e:0e:73:e6:bd:11
Wed Dec 29 19:17:06 2021 daemon.debug opennds[4167]: send_redirect_temp: Response is Queued
Wed Dec 29 19:17:06 2021 daemon.debug opennds[4167]: client access: GET /generate_204
Wed Dec 29 19:17:06 2021 daemon.debug opennds[4167]: client ip address is [ 192.168.1.147 ]
Wed Dec 29 19:17:06 2021 daemon.debug opennds[4167]: Executing command: /usr/lib/opennds/libopennds.sh get_interface_by_ip "192.168.1.147"
Wed Dec 29 19:17:06 2021 daemon.debug opennds[4167]: Setting default SIGCHLD handler SIG_DFL
Wed Dec 29 19:17:06 2021 daemon.debug opennds[4167]: Reading command output
Wed Dec 29 19:17:07 2021 daemon.debug opennds[4167]: command output: [br-lan]
Wed Dec 29 19:17:07 2021 daemon.debug opennds[4167]: Interface used to route ip [192.168.1.147] is [br-lan]
Wed Dec 29 19:17:07 2021 daemon.debug opennds[4167]: Gateway Interface is [br-lan]
Wed Dec 29 19:17:07 2021 daemon.debug opennds[4167]: Client ip address [192.168.1.147] is on our subnet using interface [br-lan]
Wed Dec 29 19:17:07 2021 daemon.debug opennds[4167]: SIGCHLD handler: Trying to reap a child
Wed Dec 29 19:17:07 2021 daemon.debug opennds[4167]: SIGCHLD handler: waitpid(): No child exists now.
Wed Dec 29 19:17:07 2021 daemon.debug opennds[4167]: preauthenticated: host [connectivitycheck.gstatic.com] url [/generate_204]
Wed Dec 29 19:17:07 2021 kern.info kernel: [  763.806065] ra  = 0040ab6f in opennds[400000+19000]
Wed Dec 29 19:17:12 2021 daemon.notice opennds[4962]: openNDS Version 9.5.1 is in startup
Wed Dec 29 19:17:12 2021 daemon.debug opennds[4962]: Parsing option: maxclients, arg: 250
Wed Dec 29 19:17:12 2021 daemon.debug opennds[4962]: Parsing option: login_option_enabled, arg: 0
Wed Dec 29 19:17:12 2021 daemon.debug opennds[4962]: Parsing option: fasport, arg: 80
Wed Dec 29 19:17:12 2021 daemon.debug opennds[4962]: Parsing option: fasremotefqdn, arg: login.superzone.com.br
Wed Dec 29 19:17:12 2021 daemon.debug opennds[4962]: Parsing option: fasremoteip, arg: 179.107.112.11
Wed Dec 29 19:17:12 2021 daemon.debug opennds[4962]: Parsing option: faspath, arg: /login
Wed Dec 29 19:17:12 2021 daemon.debug opennds[4962]: Parsing option: fas_secure_enabled, arg: 1
Wed Dec 29 19:17:12 2021 daemon.debug opennds[4962]: Parsing option: walledgarden_fqdn_list, arg: facebook.com fbcdn.net
Wed Dec 29 19:17:12 2021 daemon.debug opennds[4962]: Parsing string [facebook.com fbcdn.net] for Walled Garden FQDNs to allow






**I changed the configuration of method 1, restarted opennds and did the authorization process. I made one device and it worked normally, the second device had the kernel error and the problem. Follow the log below.**


Wed Dec 29 19:28:06 2021 daemon.debug opennds[8143]: client access: GET /hotspot-detect.html
Wed Dec 29 19:28:06 2021 daemon.debug opennds[8143]: client ip address is [ 192.168.1.245 ]
Wed Dec 29 19:28:06 2021 daemon.debug opennds[8143]: Executing command: /usr/lib/opennds/libopennds.sh get_interface_by_ip "192.168.1.245"
Wed Dec 29 19:28:06 2021 daemon.debug opennds[8143]: Setting default SIGCHLD handler SIG_DFL
Wed Dec 29 19:28:06 2021 daemon.debug opennds[8143]: Reading command output
Wed Dec 29 19:28:06 2021 daemon.debug opennds[8143]: command output: [br-lan]
Wed Dec 29 19:28:06 2021 daemon.debug opennds[8143]: Interface used to route ip [192.168.1.245] is [br-lan]
Wed Dec 29 19:28:06 2021 daemon.debug opennds[8143]: Gateway Interface is [br-lan]
Wed Dec 29 19:28:06 2021 daemon.debug opennds[8143]: Client ip address [192.168.1.245] is on our subnet using interface [br-lan]
Wed Dec 29 19:28:06 2021 daemon.debug opennds[8143]: SIGCHLD handler: Trying to reap a child
Wed Dec 29 19:28:06 2021 daemon.debug opennds[8143]: SIGCHLD handler: waitpid(): No child exists now.
Wed Dec 29 19:28:06 2021 daemon.debug opennds[8143]: preauthenticated: host [captive.apple.com] url [/hotspot-detect.html]
Wed Dec 29 19:28:06 2021 kern.info kernel: [ 1423.543803] ra  = 0040ab6f in opennds[400000+19000]
Wed Dec 29 19:28:11 2021 daemon.notice opennds[9034]: openNDS Version 9.5.1 is in startup
Wed Dec 29 19:28:12 2021 daemon.debug opennds[9034]: Parsing option: maxclients, arg: 250
Wed Dec 29 19:28:12 2021 daemon.debug opennds[9034]: Parsing option: login_option_enabled, arg: 1
Wed Dec 29 19:28:12 2021 daemon.debug opennds[9034]: Parsing option: fasport, arg: 80
Wed Dec 29 19:28:12 2021 daemon.debug opennds[9034]: Parsing option: fasremotefqdn, arg: login.superzone.com.br
Wed Dec 29 19:28:12 2021 daemon.debug opennds[9034]: Parsing option: fasremoteip, arg: 179.107.112.11
Wed Dec 29 19:28:12 2021 daemon.debug opennds[9034]: Parsing option: faspath, arg: /login
Wed Dec 29 19:28:12 2021 daemon.debug opennds[9034]: Parsing option: fas_secure_enabled, arg: 1
Wed Dec 29 19:28:12 2021 daemon.debug opennds[9034]: Parsing option: walledgarden_fqdn_list, arg: facebook.com fbcdn.net
Wed Dec 29 19:28:12 2021 daemon.debug opennds[9034]: Parsing string [facebook.com fbcdn.net] for Walled Garden FQDNs to allow
Wed Dec 29 19:28:12 2021 daemon.debug opennds[9034]: URL encoded string: facebook.com, length: 12
Wed Dec 29 19:28:12 2021 daemon.debug opennds[9034]: [facebook.com] is the urlencoded FQDN
Wed Dec 29 19:28:12 2021 daemon.info opennds[9034]: Added Walled Garden FQDN [facebook.com] to list
Wed Dec 29 19:28:12 2021 daemon.debug opennds[9034]: URL encoded string: fbcdn.net, length: 9
Wed Dec 29 19:28:12 2021 daemon.debug opennds[9034]: [fbcdn.net] is the urlencoded FQDN
Wed Dec 29 19:28:12 2021 daemon.info opennds[9034]: Added Walled Garden FQDN [fbcdn.net] to list
Wed Dec 29 19:28:12 2021 daemon.debug opennds[9034]: Parsing option: walledgarden_port_list, arg: 443
Wed Dec 29 19:28:12 2021 daemon.debug opennds[9034]: Parsing string [443] for Walled Garden Ports to allow

**What do you think if I generate an image for you with my settings via image builder (I'm using it like this) and you test it in your environment with this image?**

**Comment by bluewavenet** [comment]
Does it happen always after the debug message:
`preauthenticated: host [xxxxx] url [/yyyyy]` ?

**Comment by bluewavenet** [comment]
My config (the output of `uci show opennds`)

```
opennds.@opennds[0]=opennds
opennds.@opennds[0].enabled='1'
opennds.@opennds[0].fwhook_enabled='1'
opennds.@opennds[0].maxclients='250'
opennds.@opennds[0].sessiontimeout='1440'
opennds.@opennds[0].users_to_router='allow tcp port 53' 'allow udp port 53' 'allow udp port 67' 'allow tcp port 22' 'allow tcp port 80' 'allow tcp port 443'
opennds.@opennds[0].login_option_enabled='1'
opennds.@opennds[0].debuglevel='3'

```

**Comment by bluewavenet** [comment]
> What do you think if I generate an image for you with my settings via image builder

Your hardware is different to mine, that would not work.
Providing you are set up correctly as a router then the only important thing is the openNDS config.

**Comment by deivisonmoraes** [comment]
> Does it happen always after the debug message:
preauthenticated: host [xxxxx] url [/yyyyy] ?

Apparently so from the logs. But it seems to me that this log only appears in debug 3




> > What do you think if I generate an image for you with my settings via image builder
> 
> Your hardware is different to mine, that would not work. Providing you are set up correctly as a router then the only important thing is the openNDS config.

I can generate an image for your router using the image builder follow make command:

make image PROFILE="glinet_gl-mt300n-v2" PACKAGES="jq curl opennds -dnsmasq dnsmasq-full uhttpd luci-app-firewall luci-mod-admin-full luci-base libiwinfo-lua luci-theme-bootstrap kmod-ipt-ipset ipset" FILES="files/" 

[openwrt-ramips-mt76x8-glinet_gl-mt300n-v2-squashfs-sysupgrade.bin.gz](https://github.com/openNDS/openNDS/files/7790570/openwrt-ramips-mt76x8-glinet_gl-mt300n-v2-squashfs-sysupgrade.bin.gz)

**Comment by deivisonmoraes** [comment]
Hi again, I cleaned up the settings a lot to get the ones you sent me. I took the test and it happened as in the previous report. This time I'm sending the entire log from the first attempt to make it more observable. It goes through "preauthenticated: host [xxxxx] url [/yyyyy] " several times and the problem does not occur.


https://gist.github.com/deivisonmoraes/4047211a4dd42baa3dd750ea03362635

**Comment by bluewavenet** [comment]
Your router(s) only have 64MB ram. I think the problem is libmicrohttpd failing to allocate memory (a call is made to it after the _preauthenticated:..._ message. It fails and openNDS terminates. Procd then restarts openNDS.
Each client authentication consumes memory and it adds up I guess.
A big memory consumer is dnsmasq-full particularly when ipset is enabled.

Try setting max page size:
```
uci set opennds.@opennds[0].max_page_size='2048'
service opennds restart
```
This might help a little.... worth trying....

**My test mt300n-v2 is stable at 84MB free** without dnsmasq-full, curl or ipset.

I can try installing the same packages as you do, then creating a 64MB file in /tmp to simulate your setup....

I do remember something similar with openNDS v5 on OpenWrt 19.7.xx and a Ubiquiti Nanostation. That was definitely lack of memory.

**Comment by deivisonmoraes** [comment]
I'm going to run a test by disabling dnsmasq and ipset. The "max_page_size" option did not work!

Tks

**Comment by bluewavenet** [comment]
@deivisonmoraes 
I cannot be certain that running out of memory is the problem, but the symptoms do support that theory. openNDS will try to log memory allocation failures but that in itself requires memory. The syslog is stored in memory and some oom debug messages will not be logged unfortunately. 
You could revert to OpenWrt 19.07.8, then update to libmicrohttpd and openNDS from 21.02. This will give you some more free memory...

**Comment by bluewavenet** [comment]
@deivisonmoraes 
Please reopen if you find anything new on this.
