### ISSUE TITLE
Setting up FAS to Flask app (hosted on apache)

### ISSUE THREAD

**Issue by seantanjx** [openNDS/openNDS#287]
Hi, I'm a beginner and just started out learning about what raspberry pi can do and chanced upon RaspAP as well as opennds. I'd like to set up my own captive portal to allow authenticated guests to login and use my apartment's wifi.

I currently have a flask application that authenticates the user based on the username and password they key in against a sqlite3 database. I would like to set up FAS to point the user to the splash.html on my flask app instead. I've read the documentation and most of the examples are in PHP. The apache web server is currently serving my flask app on port 80, it would be great to have some advice on how can I configure my FAS to point users to my flask landing page rather than the opennds landing page.

**Comment by bluewavenet** [comment]
@seantanjx 
First, you need to understand the prerequisites for creating a captive portal.
From the documentation:
https://opennds.readthedocs.io/en/stable/install.html#prerequisites

From this you will see that you need a full IPv4 router, not a wireless access point. The router you create can then connect somehow to an Access Point (either internally or externally).

A major point to consider is that without significant extra hardware, a **RPi is not at all good for making a router**, let alone a router with built in access point (aka Wireless Router). The built in wireless interface in all Rpi models is designed to support IoT or workstation connectivity only. It's support for AP mode is very restrictive and the wireless coverage is very limited compared to hardware specifically designed to operate as an access point.

Yes you **_can_** configure a Pi in this way, but for serious use I would not recommend it, particularly for a beginner.

To make it work reliably you have to make a deep dive into the world of vlans and purchase a managed switch and an external access point that is also vlan capable- a significant additional hardware cost.

The best way forward is to purchase a low cost "router grade" hardware (~25 - 35 USD), install OpenWrt operating system and openNDS to provide the captive portal and WiFi.
You can then choose to use your Flask/Rpi  to provide the FAS for authentication if so desired.

Not only is this the best way of learning for a beginner, it is also the most efficient and cost effective.

It is also vital to understand that a captive portal works with "standards" that are also understood by every type of client device (eg smart phones).
See here:
https://opennds.readthedocs.io/en/stable/howitworks.html#captive-portal-detection-cpd
and here:
https://opennds.readthedocs.io/en/stable/customize.html#rules-for-customised-splash-pages

Once you have digested all this, feel free to ask for more pointers ;-)

**Comment by seantanjx** [comment]
@bluewavenet Wow thats quite a lot to take in! Nevertheless, thanks for pointing me in the correct direction! Appreciate it!
