### ISSUE TITLE
Diagrams showing how FAS works

### ISSUE THREAD

**Issue by 0l4y4** [openNDS/openNDS#289]
Hi,

I'm going to try to make several diagrams of how FAS works.
Tell me if I'm on the right track!

![openNDS(1)](https://user-images.githubusercontent.com/74093652/147514741-c51a24a8-356c-4284-a9bc-74f3840e2a56.png)

**Comment by 0l4y4** [comment]
Some related things to understand how it works:

`
main.c             

// function setup_from_config(void)
// Start authmon in the background
// if (config->fas_key && config->fas_secure_enabled == 3)
safe_asprintf(&fasssl,
	"/usr/lib/opennds/authmon.sh \"%s\" \"%s\" \"%s\" &",
	config->fas_url,
	gatewayhash,
	config->fas_ssl
);



authmon.sh

#get arguments and set variables
url=$1 -------------> config->fas_url (main.c)
gatewayhash=$2 -----> hash generate from main.c
phpcli=$3 ----------> config->fas_ssl (main.c)
loopinterval=10
postrequest="/usr/lib/opennds/post-request.php"

#calls postrequest
$phpcli -f "$postrequest" "$url" "$action" "$gatewayhash" "$user_agent" "$payload"
$phpcli -f "$postrequest" "$url" "$action" "$gatewayhash" "$user_agent" "$acklist"

postrequest = "/usr/lib/opennds/post-request.php"
url = url
action = clear or view
gatewayhash = hash device openNDS
user_agent = "openNDS(authmon;NDS:$version;)"
	version = $(echo "$ndsctlout" | grep "Version" | awk '{printf $2}')
		ndsctlout = $(eval ndsctl "$ndsctlcmd")
			ndsctlcmd = "status 2>/dev/null"
payload = none
acklist = * or "$acklist $client_rhid"
	client_rhid = $(echo "$authparams" | awk '{printf($1)}')
		authparams = $(printf "${authparams_enc//%/\\x}")
			for authparams_enc in $authlist; do
				authlist = $($phpcli -f "$postrequest" "$url" "$action" "$gatewayhash" "$user_agent" "$payload")



fas-aes-https.php

$_POST["auth_get"] -----------------------> clear, list (I don't know where is used) or view
$_POST["payload"] = $acklist -------------> none or != none
$_POST["gatewayhash"] = $gatewayhash -----> hash generated through openNDS router

`

**Comment by 0l4y4** [comment]
@bluewavenet 
I am using https://draw.io is open source (opensource). If you want I can share the original file to make changes. I have some doubts because I don't have a developer profile (I am Systems Engineer). I will put them as soon as I have time

**Comment by bluewavenet** [comment]
@0l4y4 
You can save as a .svg (scaleable vector graphics) file, directly to your github account.
In github you would create a fork of openNDS then save the .svg directly to the openNDS resources folder.
Then to submit it to openNDS master you just have to create a pull request (PR).

**Comment by 0l4y4** [comment]
@bluewavenet 
I will continue doing reversing and when I solve the doubts I will do it!
Do you think it's OK?

**Comment by bluewavenet** [comment]
>  Do you think it's OK?

Yes, very good. Only a few missing minor bits or minor changes I would suggest.

This one is for level 3 (https). There are also levels 1 and 2 including Themespec (a special level 1 FAS that uses the openNDS built in web server). The complete set would go nicely into the documentation, here probably:
https://opennds.readthedocs.io/en/stable/fas.html#forwarding-authentication-service-fas

**Comment by 0l4y4** [comment]
@bluewavenet 
Exactly. I'm talking about level 3 all the time. Thanks

**Comment by 0l4y4** [comment]
The first time you start the device configured with FAS HTTPS (level 3), it should behave (until a client tries to connect) as follows:

![openNDS_1 drawio](https://user-images.githubusercontent.com/74093652/147681549-eb60c637-0831-4aec-bb44-80c336bd5924.png)

**Comment by 0l4y4** [comment]
@bluewavenet 
I would like to know how is the procedure when a client tries to connect to the Wi-Fi. What's the script for starting to look at code?

**Comment by bluewavenet** [comment]
@0l4y4 
>  I would like to know how is the procedure when a client tries to connect to the Wi-Fi. What's the script for starting to look at code?

I am not sure what you mean by this but the process is as follows:
When a client device connects, it first of all uses its built in CPD to probe the network for Internet access.
It is not authenticated so the probing triggers openNDS to send a 301 HTTP_TEMPORARY_REDIRECT response that contains the url of the remote FAS.
The client CPD restricted browser window then opens on the client displaying the FAS url.

**Comment by 0l4y4** [comment]
@bluewavenet 
>  "openNDS to send a 302 HTTP_TEMPORARY_REDIRECT response that contains the url of the remote FAS"

Maybe fw_iptables.c does it?

**Comment by bluewavenet** [comment]
@0l4y4 
Ah! You were asking where in the code ;-)
http_microhttpd.c, function `send_redirect_temp()`

**Comment by 0l4y4** [comment]
@bluewavenet 
another question:
Where is the code that sends the IP, MAC, etc. to HTTPS FAS?

**Comment by 0l4y4** [comment]
The NDS parameters: clientip, clientmac, gatewayname, client token, gatewayaddress, authdir and originurl
	are encrypted using fas_key and passed to FAS in the query string.

Where is the query on openNDS code?

**Comment by bluewavenet** [comment]
@0l4y4 

> Where is the query on openNDS code?

This is in http_microhttpd.c
Follow the code from function `redirect_to_splashpage()`

**Comment by 0l4y4** [comment]
@bluewavenet 
Thanks and sorry for asking so much!
This code (fas-aes-https.php), ¿When is executed?

```
// Service requests for remote image
if (isset($_GET["get_image"])) {
	$url=$_GET["get_image"];
	$imagetype=$_GET["imagetype"];
	get_image($url, $imagetype);
	exit(0);
}

// Get the query string components
if (isset($_GET['status'])) {
	@$redir=$_GET['redir'];
	@$redir_r=explode("fas=", $redir);
	@$fas=$redir_r[1];

	if (isset($_GET['iv'])) {
		$iv=$_GET['iv'];
	} else {
		$iv="error";
	}

} else if (isset($_GET['fas']))  {
	$fas=$_GET['fas'];

	if (isset($_GET['iv'])) {
		$iv=$_GET['iv'];
	} else {
		$iv="error";
	}
} else {
	exit(0);
}
```

**Comment by bluewavenet** [comment]
@0l4y4 

>  This code (fas-aes-https.php), ¿When is executed?

In php:
 * the function isset() tests if a variable is set, ie it has some value.
 * the variable $_GET is an array containing the query string from a "GET" request to the server.
 
 So this code gets executed depending on what is in the query string.

**Comment by 0l4y4** [comment]
@bluewavenet 
ok, a use case in particular, you have openNDS configured with level 3. You have a server www.test.com/nds/fas-aes-https.php and a user tries to access the WiFi.

1. opendNDS redirect to www.test.com/nd/fas-aes-https.php/encoded(clientip, clientmac, gatewayname, client token, gatewayaddress, authdir and originurl)
2. php force redirect to secure page
3. setup basic defaults
4. Set logpath
5. skip auth_get() because there is no post request 
6. // Service requests for remote image
if (isset($_GET["get_image"])) {
	$url=$_GET["get_image"];
	$imagetype=$_GET["imagetype"];
	get_image($url, $imagetype);
	exit(0);
}

Does this last step skip it? because there is no GET "get_image" request and same with 'fas'

**Comment by 0l4y4** [comment]
@bluewavenet 
Could you give an example of the full uncoded url when you forward the user to the server?

**Comment by bluewavenet** [comment]
@0l4y4 

> You have a server www.test.com/nds/fas-aes-https.php and a user tries to access the WiFi.

1. opendNDS redirect to `https://www.test.com/nd/fas-aes-https.php/?fas=[encrypted_fas_string]&iv=[initialisation vector]`
2. access from openNDS is already https, php will force https in case user accesses manually using http - FAS would serve an error to the requester as query string would be invalid.
3. Decrypt fas string, setup basic defaults
4. Set logpath
5. Serve first page of splash page sequence and wait for response from client

Other possible get or post requests:
1. auth_get()  post request
2. if (isset($_GET["get_image"])) {........ Download remote image if requested (this eliminates the need to install images on the server)
3. if (isset($_GET['status'])) {....... Status request for client from openNDS

**Comment by bluewavenet** [comment]
@0l4y4 

>  Could you give an example of the full uncoded url when you forward the user to the server?

The url query string is always encrypted. The format is for example:
`https://www.test.com/nd/fas-aes-https.php/?fas=[encrypted_fas_string]&iv=[initialisation vector]`
Additional query sting components my be added by FAS in response to the first page reply by the client.

**Comment by 0l4y4** [comment]
@bluewavenet 
thanks for your last clarification, it was just what I needed to understand it (I think xD)

Could this be a "normal" case when a client connects to the CPD?

![client_connect_opennds drawio](https://user-images.githubusercontent.com/74093652/147792555-5ca3a681-c5e9-4f4d-b58c-2ee1867aca65.png)

**Comment by bluewavenet** [comment]
@0l4y4 
Good work and much appreciated.
It is turning into a logic diagram  :D - but has a lot missing. For example, decisions are made depending on the input from the client and a series of pages are generated.
Here is a diagram I produced a few months ago. It shows all the stages and might help:
![opennds-cpd-mitm-redirect-based-cropped](https://user-images.githubusercontent.com/13632068/147838369-3c99cf75-c6f3-44c3-b02c-ee3a87731f29.png)

**Comment by 0l4y4** [comment]
@bluewavenet 
Firs of all, happy new year!!
I will try to continue this night because it is a very difficult day to be in front of the computer but I really want because every time I understand more pieces of the puzzle!!   
Thanks for your dedication

**Comment by 0l4y4** [comment]
@bluewavenet 
Another diagram that seems important to me for testing locally:

![query_redirect drawio](https://user-images.githubusercontent.com/74093652/147885654-e25ba27d-2c22-4fb9-b822-1afe3ba35e05.png)

**Comment by bluewavenet** [comment]
@0l4y4 

>  Another diagram that seems important to me for testing locally

Operating locally at level 3 will generate tls/certificate security errors on the client, unless the client is modified in advance. Fine for testing, but useless in production.

You must be clear, that the rhid and iv are in no way related.
 * rhid is the encrypted client token required for openNDS to allow Internet access. It is generated by FAS from the hid sent in the encrypted client information string.
 * iv is a code that is required to enable the client data to be decrypted. It is unique per client connection. Every time a client connects, the iv will be different. This makes brute force decryption pretty much impossible.

**Comment by bluewavenet** [comment]
@0l4y4 

Note:
 * hid - Hashed id - where id is the client token
 * rhid - Returned hid - the result of sha256sum of the combined hid and pre-shared-key values

**Comment by 0l4y4** [comment]
@bluewavenet 
> Operating locally at level 3 will generate tls/certificate security errors on the client, unless the client is modified in advance. Fine for testing, but useless in production.

I usually comment this for testing:
```
//force redirect to secure page
/*
if(empty($_SERVER['HTTPS']) || $_SERVER['HTTPS'] == "off"){
    $redirect = 'https://' . $_SERVER['HTTP_HOST'] . $_SERVER['REQUEST_URI'];
    header('HTTP/1.1 301 Moved Permanently');
    header('Location: ' . $redirect);
    exit(0);
}
*/
```

> You must be clear, that the rhid and iv are in no way related.

I just wanted to make a diagram with the hid and the rhid, but I still have to study how openDNS treats the rhid token sent by the FAS.
Also, I would like to ask you about your documentation, as you say the following:

> FAS will deposit client authentication variables for the Authmon daemon to use for the authentication process. These variables are as follows:
> 
>     clientip: The ip address of the client to be authenticated
>     sessionlength: length of session - minutes
>     uploadrate: maximum allowed upload data rate - kbits/sec
>     downloadrate: maximum allowed download data rate - kbits/sec
>     uploadquota: allowed upload data quota - kBytes
>     downloadquota: allowed download data quota - kBytes
>     custom: A custom data string that will be sent to BinAuth

Wouldn't clientip actually be rhid?

**Comment by bluewavenet** [comment]
@0l4y4 

> I usually comment this for testing......

This php code is only to prevent someone or some "bot" from accessing using http only. It has nothing to do with the login process.

>  I still have to study how openDNS treats the rhid token sent by the FAS.

openNDS **requires** the rhid to be sent to it for authentication.

> Wouldn't clientip actually be rhid?

Yes indeed, that is an error in the documentation! Well spotted thanks ;0)

**Comment by 0l4y4** [comment]
@bluewavenet 

> openNDS requires the rhid to be sent to it for authentication

Ok, but I need step by step in the code (for my mental health) xD I will study it!

**Comment by 0l4y4** [comment]
@bluewavenet 

> hid - Hashed id - where id is the client token

Where does the id come from (in the code) and where is the hash done?

**Comment by 0l4y4** [comment]
@bluewavenet 

> This php code is only to prevent someone or some "bot" from accessing using http only. It has nothing to do with the login process.

I only use it to do tests locally, from my workstation with the FAS (php), without opennds

**Comment by bluewavenet** [comment]
@0l4y4 
`get_client_token.sh` is deprecated as it no longer serves much purpose.

> Where does the id come from (in the code)

Function client_reset() in client_list.c

**Comment by 0l4y4** [comment]
@bluewavenet 
 Tell me if I'm on the right track!

![token_client drawio](https://user-images.githubusercontent.com/74093652/148136427-6cec0a3c-3eca-4095-b29c-98268cfceda3.png)

**Comment by bluewavenet** [comment]
@0l4y4 

>  Tell me if I'm on the right track!

You have the authmon part completely wrong.

Typically, openNDS is behind an Internet facing nat firewall and probably does not even have a fixed public ip address.
Authmon runs independently as a daemon and can talk to both FAS and openNDS. It acts as an inbound "nat traversal" mechanism for FAS to communicate with openNDS.

Next, you should study the authmon.sh code ;-)

**Comment by 0l4y4** [comment]
@bluewavenet 
I just wanted to talk about hid and rhid in this diagram, that's why I put it like this.
Better this way?

![token_client drawio(1)](https://user-images.githubusercontent.com/74093652/148208503-9933a695-673a-434b-9937-1aa14e459d7c.png)

**Comment by bluewavenet** [comment]
@0l4y4 

>  Better this way?

No. Authmon does not talk to http_microhttpd.c and it never calls try_to_authenticate(). That part of your diagram is .. just completely wrong.

Like I said, "Next, you should study the authmon.sh code ;-)"

**Comment by 0l4y4** [comment]
@bluewavenet 
But who is in charge of trying if the rhid is correct? authmon.sh?
 Ok, I will study it better!!

**Comment by DAT4** [comment]
rouge flow diagram of authmon.sh
![authmon](https://user-images.githubusercontent.com/54900752/148463579-13206c2e-e9cd-4229-a9ad-24abf3f6a472.png)

**Comment by DAT4** [comment]
> @0l4y4 Good work and much appreciated. It is turning into a logic diagram :D - but has a lot missing. For example, decisions are made depending on the input from the client and a series of pages are generated. Here is a diagram I produced a few months ago. It shows all the stages and might help: ![opennds-cpd-mitm-redirect-based-cropped](https://user-images.githubusercontent.com/13632068/147838369-3c99cf75-c6f3-44c3-b02c-ee3a87731f29.png)

In your sequence diagram row 13 you say `FAS -> OpenNDS : Authenticate` and then acceptance in row 14. However I don't see that is actually happening in the `authmon.sh` or the https php FAS

Isn't the authmon.sh just polling the FAS server all the time, and then the client will have to wait until authmon has fetched the authlist and authorized him/her?

**Comment by DAT4** [comment]
![sequence](https://user-images.githubusercontent.com/54900752/148708896-7bedea14-51fb-440b-9617-1f14960678c5.png)

Here is an example of a OAuth FAS flow how I think it would work together with OpenNDS.

**Comment by bluewavenet** [comment]
@DAT4 

> Isn't the authmon.sh just polling the FAS server all the time

In this particular implementation of authmon, yes. Doing it this way does not require any additional dependencies and does not require any non-openNDS configuration. The downside is that clients have to wait a few seconds.
An alternative would be to set up some sort of VPN between FAS and openNDS. This would eliminate the short wait time, but would mean the most common "shared web hosting" services could not be used.
Tests have been done using an SSH tunnel between openNDS and a VPS, and worked well, but the extra effort required makes a working configuration that is quite complex and outside the knowledge of a typical web designer that might be tasked to install a captive portal.

**Comment by bluewavenet** [comment]
@DAT4 

> Here is an example of a OAuth FAS flow how I think it would work together with OpenNDS.

No, that will not work.
Note:
- The client can only communicate with FAS
- The Oauth server can communicate with FAS but not openNDS and not the client
- FAS can communicate with Oauth, openNDS and the client

Point 15 in your diagram consists of FAS sending the landing page, with a "*" character sent every second until authenticated.
Point 16 is wrong, the client does not need to "try connect", once the landing page is complete the client has Internet access (the page tells the client this is so).

**Comment by 0l4y4** [comment]
@bluewavenet 
Then, authmon makes a POST request and call to ndsctl for authenticating the client, right?

**Comment by bluewavenet** [comment]
@0l4y4 
Yes ;-)

**Comment by 0l4y4** [comment]
@bluewavenet 

![autehntication drawio](https://user-images.githubusercontent.com/74093652/149643405-816c99e8-f8be-475d-a00c-79412d45ad75.png)
