### ISSUE TITLE
ipk for x86 arch ?

### ISSUE THREAD

**Issue by toxic0berliner** [openNDS/openNDS#29]
Probably not the right place to complain about this, but I was hoping to try openNDS on my alix 2d13 running an AMD geode x86 processor, but contrary to what's in the install instructions for openWRT, opkg cannot find a suitable package : 
````
root@alix:~# opkg install opennds
Unknown package 'opennds'.
Collected errors:
 * opkg_install_cmd: Cannot install package opennds.
root@alix:~# opkg find *opennds*
root@alix:~# opkg print-architecture
arch all 1
arch noarch 1
arch i386_pentium 10
root@alix:~# cat /etc/opkg/distfeeds.conf 
src/gz openwrt_core http://downloads.openwrt.org/releases/19.07.3/targets/x86/geode/packages
src/gz openwrt_base http://downloads.openwrt.org/releases/19.07.3/packages/i386_pentium/base
src/gz openwrt_luci http://downloads.openwrt.org/releases/19.07.3/packages/i386_pentium/luci
src/gz openwrt_packages http://downloads.openwrt.org/releases/19.07.3/packages/i386_pentium/packages
src/gz openwrt_routing http://downloads.openwrt.org/releases/19.07.3/packages/i386_pentium/routing
src/gz openwrt_telephony http://downloads.openwrt.org/releases/19.07.3/packages/i386_pentium/telephony
root@alix:~# cat /etc/opkg/customfeeds.conf 
# add your custom package feeds here
#
# src/gz example_feed_name http://www.example.com/path/to/files
````

Looking here in gitHub I see the release has an ipk only for mips and mipsel.
I'm very unfamiliar with these architectures but I believe they would not be compatible with my current x86...

Any chance you would build an x86 package and push it to openwrt repos ?

Thanks in advance, and sorry if this isn't the right place to ask for this ;) 
Also, maybe add in the install doc that only these 2 archs are currently supported ? (unless I'm mistaken of course)

**Comment by bluewavenet** [comment]
@toxic0berliner 
Complain, maybe not, but ask, no problem ;-) lol

Download the ipk here:
https://downloads.openwrt.org/snapshots/packages/i386_pentium/routing/opennds_5.1.0-1_i386_pentium.ipk

This is the **_stable_** version 5.1.0, despite being in "snapshots". This is because it is ready for the upcoming release of OpenWrt 20.x.x (sometime this year we all hope!).

It runs with no problem on OpenWrt 18.x.x and 19.x.x with just one minor config required due to the version of Libmicrohttpd (aka MHD).

Download from the link above and copy to /tmp on your Alix in your favourite way, then:

```
opkg update
opkg install /tmp/opennds_5.1.0-1_i386_pentium.ipk
uci opennds.@opennds[0].use_outdated_mhd='1'
uci commit opennds
service opennds restart
```

Then check it started correctly by running:
`logread | grep opennds`

and

`ndsctl status`

I think I got it right :-D

**Comment by toxic0berliner** [comment]
Thanks a lot for the very fast response !
I tried it and it seems to be working !
I was hoping it would add some kind of graphical interface in luci, or on it own webserver on port 2050, but sadly not.
I'm gonna look for some docs then to find what are the options I need, like how to tell which mac addresses don't need auth (option and probably syntax in the file...), option to tell it where it should find the users.db if I want to move it...

Also, I just founf this [readme](https://github.com/openNDS/openNDS/blob/master/openwrt/README.md) that negates my previous comment about not beeing able to build ;) Instructions are upt to date there it seems.

**Comment by toxic0berliner** [comment]
hmm... well... I'm having troubles to find the info I need..
For example, I had to look in config.c to find out that it seems there is a trustedmaclist option that seems to be parsed as a comma separated list of mac by parse_trusted_mac_list.

I did add it : 
````
uci set opennds.@opennds[0].trustedmaclist='so:me:va:li:dm:ac'
uci commit opennds
````
and even after a reboot, I get:
````
# ndsctl status
==================
openNDS Status
====
Version: 5.1.0
Uptime: 9m 20s
Gateway Name: OpenWrt openNDS
Managed interface: br-lan
Managed IP range: 0.0.0.0/0
Server listening: http://192.168.0.1:2050
Binauth: Disabled
Preauth: Disabled
FAS: Disabled
Client Check Interval: 60s
Preauth Idle Timeout: 30m
Auth Idle Timeout: 120m
Traffic control: no
Total download: 1981 kByte; avg: 28.31 kbit/s
Total upload: 6417 kByte; avg: 91.68 kbit/s
====
Client authentications since start: 1
Current clients: 6

Client 0
  IP: x.x.x.x MAC: so:me:va:li:dm:ac
  Last Activity: Mon Jul 20 00:00:51 2020 (0s ago)
  Session Start: Sun Jul 19 23:55:19 2020 (5m 32s ago)
  Session End:   Mon Jul 20 19:55:19 2020 (19h 54m 28s left)
  Token: xxx
  State: Preauthenticated
  Download: 0 kByte; avg: 0.00 kbit/s
  Upload:   0 kByte; avg: 0.00 kbit/s
...
====
Blocked MAC addresses: none
Allowed MAC addresses: N/A
Trusted MAC addresses: none
========
````
So it does not read the option in `/etc/config/opennds` at startup or on service restart...

Any help would be greatly appreciated, pointing me to a doc would be the best, but I can also describe here piece by piece what I wish to do in the end if the doc is not existing ;)

But it seems trusting a mac is one bit I wanted to do and doing it with ndsctl seems to work ! So good point here !
At this late hour, I can't refrain from complaining just a little bit : it seems it's sensitive to upper/lower case for the mac address, I come from piHole that requires mac addresses in uppercase, and here `ndsctl trust so:me:va:li:dm:ac` requires lowercase... Why can't we all agree MixEdCase is TheBeSt ;)

**Comment by bluewavenet** [comment]
@toxic0berliner 

https://github.com/openNDS/openNDS#2-documentation

I hope it is not the Dunning-Kruger effect that stops you from finding the documentation :-D

I am happy to help. Perhaps you could share more detail about your requirements.

**Comment by bluewavenet** [comment]
@toxic0berliner 
There is no standard for mac addresses as far as upper/lower case is concerned so you do have a point.
I'll put it on my TODO list ;-)

FYI I used Alix boards many years ago on projects and most have been retired now although they are still pretty good if you can pick up a cheap second hand one. Most were taken out of service with failing CF cards after a few years - something worth being aware of.

Documentation is time consuming so any help you can give is welcome, particularly in the form of a pull request!

**Comment by bluewavenet** [comment]
@toxic0berliner 
It is well worth browsing through the default config file as it has many explanatory comments:
https://github.com/openNDS/openNDS/blob/master/openwrt/opennds/files/etc/config/opennds

**Comment by bluewavenet** [comment]
@toxic0berliner 
I have updated the documentation for cross compiling, but this still needs some work.
https://opennds.readthedocs.io/en/latest/compile.html

**Comment by toxic0berliner** [comment]
Thanks a lot ! That default config file was just exactly what I needed ;) It showed me the allowedmac option instead of allowedmacadresses ;)
I'm not going to have a complex setup, just simple users.dat file, a few trusted mac, and a nice looking splash page. 
Will do a PR on doc if I find anything else. 
One I got a nice static splash with material design I'll probably also make a PR m, that one might not make it I'm aware, not an issue, proposing is always good ;)

**Comment by bluewavenet** [comment]
@toxic0berliner 
You should note in the documentation the section **_Rules for Customised Splash Pages_**
https://opennds.readthedocs.io/en/stable/customize.html#rules-for-customised-splash-pages

These rules spell out restrictions commonly found in the client CPD. It is essential to keep the splash page simple, particularly avoid javascript.

**Comment by bluewavenet** [comment]
@toxic0berliner 
The section on CPD is important to understand:
https://opennds.readthedocs.io/en/stable/howitworks.html#captive-portal-detection-cpd

In fact, the whole chapter **_How openNDS (NDS) works_** should be studied:
https://opennds.readthedocs.io/en/stable/howitworks.html#how-opennds-nds-works
