### ISSUE TITLE
fas_secure_enabled = 1 in local area network?

### ISSUE THREAD

**Issue by MadDogMayCry0** [openNDS/openNDS#290]
Hi!

1 - It is possible to get NDS - FAS to work inside local area network with out setting a "option fasremotefqdn" when [fas_secure_enabled 1] or [fas_secure_enabled 2]?
2 - Can u pls explain, how NDS getting information from FAS after authorisation process is done and user was authorised on FAS., when **[fas_secure_enabled 1]** or **[fas_secure_enabled 2]** options is setted? Through "GET" of users inputs over redirection process?

Thx.

**Comment by MadDogMayCry0** [comment]
@bluewavenet

**Comment by bluewavenet** [comment]
@MadDogMayCry0 
Holidays and timezones

**Comment by MadDogMayCry0** [comment]
> @MadDogMayCry0 Holidays and timezones
Marry Christmas and Happy New Year :)

**Comment by bluewavenet** [comment]
@MadDogMayCry0 

> [Is it] possible to get NDS - FAS to work inside local area network with out setting a "option fasremotefqdn" when [fas_secure_enabled 1] or [fas_secure_enabled 2]?

Yes.
Fasremotefqdn is only required if the remote sever running FAS is a shared server - ie hosts multiple web sites on a single IP address, or is running on a "cloud server" with multiple ip addresses for a single FQDN

> How [does] NDS get information from FAS after authorisation process is done and user was authorised on FAS .... ?

There is generally no information openNDS would need to retrieve from FAS after a client has been authenticated, so nothing has been implemented as it is not required.

**Comment by MadDogMayCry0** [comment]
> There is generally no information openNDS would need to retrieve from FAS after a client has been authenticated, so nothing has been implemented as it is not required.

But FAS have to say NDS that user has been authenticated, isn't? Or do i missunderstanding something in auth process between NDS and remote FAS?

**Comment by bluewavenet** [comment]
@MadDogMayCry0 

> I thought that in the case of [fas_secure_enabled 1] or [fas_secure_enabled 2], a GET request is used

Yes, the **client** makes a GET request to openNDS, once FAS has verified the client credentials and generated the html that contains the GET request.

Note:
 * **openNDS authenticates clients** ie grants Internet access.
 * **FAS generates a dialogue with the client, collecting credentials**, eg full name and email address in the examples, or perhaps username and password in a custom implementation.
 * **FAS verifies the client's credentials** eg checks the collected username and password against a database.
 * If the credentials are verified, **FAS generates a page containing the required GET request for openNDS to authenticate.**

Also note:
* A client can access both openNDS and FAS
* FAS can only **reply** to a client (because of inbound NAT)
* FAS cannot initiate communications with openNDS (because of inbound NAT)
* FAS cannot initiate communications with a client (because of inbound NAT)

**Comment by MadDogMayCry0** [comment]
> Yes, the **client** makes a GET request to openNDS, once FAS has verified the client credentials and generated the html that contains the GET request.

Hi. Thx, today i got it.
My cfg for fas_secure_enabled='1' scenario
```
root@OpenWrt:~# uci show opennds
opennds.@opennds[0]=opennds
opennds.@opennds[0].enabled='1'
opennds.@opennds[0].fwhook_enabled='1'
opennds.@opennds[0].login_option_enabled='0'
opennds.@opennds[0].gatewayinterface='wlan0'
opennds.@opennds[0].gatewayname='OpenWrt openNDS'
opennds.@opennds[0].maxclients='250'
opennds.@opennds[0].fasport='80'
opennds.@opennds[0].fasremoteip='192.168.1.222'
opennds.@opennds[0].faspath='/test.php'
opennds.@opennds[0].faskey='1234567890'
opennds.@opennds[0].fas_secure_enabled='1'

```

test.php source is:
```php
<?php
if (!isset($_GET["fas"]))  {
	echo "Something went wrong!";
	exit(0);
}
if (ob_get_level()){
	ob_end_clean();
}
date_default_timezone_set("UTC");

$cfg = [];
$key="1234567890";

$fas=$_GET["fas"];
$arr=explode(", ",base64_decode($fas));	

foreach ($arr as $dec) {
	$res = explode("=",$dec);
	if (isset($res[1])){
		$cfg[$res[0]] = $res[1];
	}
}

$lang = substr($_SERVER["HTTP_ACCEPT_LANGUAGE"], 0, 2);
$host=$_SERVER["HTTP_HOST"].$_SERVER["SCRIPT_NAME"];
$gateway=urldecode($cfg["gatewayname"]);
$link='http://'.$cfg["gatewayaddress"].'/opennds_auth/';
$redir='http://'.$host.'?fas='.$fas.'&landing=1';
$tok=hash("sha256", $cfg["hid"].$key);

echo '
	<!DOCTYPE html>
	<html>
	<head>
	<title>Authorisation page</title>
	</head>
	<body>
	Browser language is '.$lang.'<br>
	You are connected to '.$gateway.'<br>
	Press continue botton to get Internet connection to work"
	<form action="'.$link.'" method="get">
		<input type="hidden" name="tok" value="'.$tok.'">
		<input type="hidden" name="custom" value="">
		<input type="hidden" name="redir" value="'.$redir.'">
		<input type="submit" value="Continue">
	</form>

	</body>
	</html>
	';
flush();
```
