### ISSUE TITLE
OpenNDS doesn't work with bridged vm (Virtualbox + WiFi usb adapter)

### ISSUE THREAD

**Issue by 0x41414141-code** [openNDS/openNDS#292]
Im using: 

- Virtualbox Version 6.1.30 
- openNDS Version 9.5.1-1
- OpenWrt 21.02.1 
- TL-WN722N (USB dongle)

OpenWRT is working inside of virtual machine, usb wifi adapter is hooked to guest machine via passthrough.
Host ethernet adapter is bridged to the vm.
Here is list of interfaces I have inside of openwrt vm. 

```
br-mng    Link encap:Ethernet  HWaddr 08:00:27:E5:72:BA  
          inet addr:192.168.56.2  Bcast:192.168.56.255  Mask:255.255.255.0
          inet6 addr: fe80::a00:27ff:fee5:72ba/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:44704 errors:0 dropped:0 overruns:0 frame:0
          TX packets:42700 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:3499479 (3.3 MiB)  TX bytes:13652375 (13.0 MiB)

br-wan    Link encap:Ethernet  HWaddr 08:00:27:D2:FA:24  
          inet addr:10.0.3.15  Bcast:10.0.3.255  Mask:255.255.255.0
          inet6 addr: fe80::a00:27ff:fed2:fa24/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:2 errors:0 dropped:0 overruns:0 frame:0
          TX packets:9 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:1152 (1.1 KiB)  TX bytes:1430 (1.3 KiB)

eth0      Link encap:Ethernet  HWaddr 08:00:27:E5:72:BA  
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:44773 errors:0 dropped:0 overruns:0 frame:0
          TX packets:45139 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:4130137 (3.9 MiB)  TX bytes:13814231 (13.1 MiB)

eth1      Link encap:Ethernet  HWaddr 08:00:27:D2:FA:24  
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:4883 errors:0 dropped:0 overruns:0 frame:0
          TX packets:3762 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:4212232 (4.0 MiB)  TX bytes:570588 (557.2 KiB)

lo        Link encap:Local Loopback  
          inet addr:127.0.0.1  Mask:255.0.0.0
          inet6 addr: ::1/128 Scope:Host
          UP LOOPBACK RUNNING  MTU:65536  Metric:1
          RX packets:2272 errors:0 dropped:0 overruns:0 frame:0
          TX packets:2272 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:163411 (159.5 KiB)  TX bytes:163411 (159.5 KiB)

wlan0     Link encap:Ethernet  HWaddr F8:1A:67:08:54:87  
          UP BROADCAST MULTICAST  MTU:1500  Metric:1
          RX packets:0 errors:0 dropped:0 overruns:0 frame:0
          TX packets:0 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:0 (0.0 B)  TX bytes:0 (0.0 B)
```
When I link opennds to **wlan0** the AP doesn't associate clients because it doesn't assign ip addresses (i guess so) i get following error:
```
daemon.notice opennds[13366]: Interface: wlan0 is not yet ready - waiting...
daemon.err opennds[13366]: Could not get IP address information of wlan0, exiting...
```
When I link opennds to **br-wan** the AP does associate clients but it skips opennds as if it doesn't exist.
What am I doing wrong?

**Comment by bluewavenet** [comment]
@0x41414141-code 
The answer is in the error message:
`daemon.err opennds[13366]: Could not get IP address information of wlan0, exiting...`

OpenWrt has to be set up as an ipv4 router for openNDS.
See the documentation for the openNDs prerequisites:
https://opennds.readthedocs.io/en/stable/install.html#prerequisites

**Comment by 0x41414141-code** [comment]
br-wan already assigns ipv4 address.
From luci, Network settings: 
![slika](https://user-images.githubusercontent.com/82291696/148266908-c0bced2b-69f8-4488-ba44-30d9f78669d4.png)
Virtualbox adapter settings:
![slika](https://user-images.githubusercontent.com/82291696/148266803-6b1dfe5b-2dff-45bc-90b9-22b098fc4904.png)

**Comment by bluewavenet** [comment]
@0x41414141-code 
I say again:
See the documentation for the openNDS prerequisites.
https://opennds.readthedocs.io/en/stable/install.html#prerequisites

Better still, here it is:
openNDS is designed to run on a device configured as an IPv4 router and will have at least two network interfaces:
 1.  A WAN interface (Wide Area Network). This interface must be connected to an Internet feed:
        Either an ISP CPE (Internet Service Provider Customer Premises Equipment)
        Or another router, such as the venue ADSL router.
        It must be configured as a DHCP client, obtaining its IPv4 address and DNS server from the connected network.

 2. A LAN interface (Local Area Network). This interface MUST be configured to:
        Provide the Default IPv4 gateway in a private IPv4 subnet that is different to any private subnets between it and the ISP CPE
        Provide DHCP services to connected clients
        Provide DNS services to connected clients
        Provide Network Address Translation (NAT) for all outgoing traffic directed to the WAN interface.

If an improper routing configuration is detected, openNDS will shut down.

Clearly, as you have not configured your VM according to the pre-requisites, openNDS aborts on startup.
