### ISSUE TITLE
Where should I configure custom client based scripts? (for FAS)

### ISSUE THREAD

**Issue by DAT4** [openNDS/openNDS#294]
I am doing a school project where I am setting up a simple OAuth server (written in Go) with users who have specific roles. Then I am making an OAuth client (Also Go) which will be used as a FAS for OpenNDS on OpenWRT.

*I am implementing it and if I manage to get it to work I am more than happy to share it as an use case example here. I am also writing an article about it.*

My idea is that I will send the role as a parameter to the `authmon.sh` script and then translate the role into permissions in regards to firewall and routing etc. (Maybe traffic shaping as well, actually just any network rule possible).

And my question is if it is a correct method, to add my custom script into the `authenticated` case in the `authmon.sh` script?

**Comment by bluewavenet** [comment]
@DAT4 

> And my question is if it is a correct method, to add my custom script into the authenticated case in the authmon.sh script?

The correct way to do this would be to put the "role" into the custom string for the client. Then at the router end, this string is made available to a binauth script that is called when a client is authenticated.
A custom binauth script could then add specific firewall rules depending on the "role" (and delete them again when the client is deauthenticated).

No changes of any kind would be needed to openNDS or authmon.
