### ISSUE TITLE
ThemeSpec custom script

### ISSUE THREAD

**Issue by MadDogMayCry0** [openNDS/openNDS#301]
Hello!

I get FAS to work, and it's work great.
Now i just wanna try to use built in ThemeSpec mechanism, for example to auth user by random generated CODE.
ok, i just copy theme_click-to-continue-basic.sh and add some code to generate CODE. But what to do next?
How will opennds know that I want to check this field? In FAS, we get a variable, take a token from it, and then, after authorization, we return the user through GET request. But I can't understand how TemeSpec works. Pls Help.

additionalthemevars="username emailaddress" - how it's works, and why am I filling this out here?
Is this will be added to $FAS? If yes, then, how will OPENNDS know this variable has been inserted, and CODE is correct?
Or, if i check it at my self, then how can i let OpenNDS know - we can auth user?

@bluewavenet

**Comment by bluewavenet** [comment]
@MadDogMayCry0 
Sorry, I don't understand what you are asking.

> for example to auth user by random generated CODE

Do you mean you want to validate a user from credentials containing a random code that is associated with their account?

> we return the user through GET request

I assume you are asking how ThemeSpec authenticates a validated client.
ThemeSpec does not use a GET request to authenticate a client. Instead it uses an openNDS library function call to auth_log()

**Comment by MadDogMayCry0** [comment]
> @MadDogMayCry0 Sorry, I don't understand what you are asking.
> Do you mean you want to validate a user from credentials containing a random code that is associated with their account?
I just wanted to understand how the authorization mechanism works using ThemeSpec script. Let's say I copied the "click to continue" script and added a field to it in which the user must enter a secret code. The "code" variable is also generated in this script. When user entered this code, and code is correct, i wanna let him obtain internet connection. This is just an example to understand how to add custom authorization logic. I searched in closed issues but didn't seem to find anything.

In general, I do not understand how to proceed, where to check the code entered by the user?

**Comment by bluewavenet** [comment]
@MadDogMayCry0 
You need to define a custom variable  to generate a "Dynamically Generated Form Field" (eg for your code variable).
See:
https://opennds.readthedocs.io/en/latest/customparams.html#custom-dynamically-generated-form-fields

**Comment by bluewavenet** [comment]
@MadDogMayCry0 
And also read:
https://opennds.readthedocs.io/en/latest/themespec.html#themespec-templates

**Comment by MadDogMayCry0** [comment]
I did! Ok, i added this fields, the next steps from my side? How to check code from NDS side?

**Comment by bluewavenet** [comment]
@MadDogMayCry0 
It might be better to show you by example.
Make the following changes to your config file:

```
	option login_option_enabled '3'
	option themespec_path '/usr/lib/opennds/theme_click-to-continue-custom-placeholders.sh'
	list fas_custom_parameters_list 'logo_message=openNDS:%20Perfect%20on%20OpenWrt!'
	list fas_custom_parameters_list 'banner1_message=BlueWave%20-%20Wireless%20Network%20Specialists'
	list fas_custom_parameters_list 'banner2_message=HMS%20Pickle'
	list fas_custom_parameters_list 'banner3_message=SeaWolf%20Cruiser%20Racer'
	list fas_custom_variables_list 'input=getval:New%20Form%20Value:text'
	list fas_custom_images_list 'logo_png=https://openwrt.org/_media/logo.png'
	list fas_custom_images_list 'banner1_jpg=https://raw.githubusercontent.com/openNDS/openNDS/v9.5.0/resources/bannerbw.jpg'
	list fas_custom_images_list 'banner2_jpg=https://raw.githubusercontent.com/openNDS/openNDS/v9.5.0/resources/bannerpickle.jpg'
	list fas_custom_images_list 'banner3_jpg=https://raw.githubusercontent.com/openNDS/openNDS/v9.5.0/resources/bannerseawolf.jpg'
	list fas_custom_files_list 'advert1_htm=https://raw.githubusercontent.com/openNDS/openNDS/v9.5.0/resources/bannerpickle.htm'
```

Note the custom variables entry. It defines a new form field to be displayed.
It defines a variable "getval" to be entered by the client.
The form field has the label "New Form Value"

Save the config and restart opennds:
`service opennds restart`

Connect a client and the new login page should pop up and look similar to this:

![custom-login](https://user-images.githubusercontent.com/13632068/154510874-d4b8dcb1-58ae-441c-86d1-051e6420ae2b.jpg)

Enter some text into the new form field and click "Accept Terms of Service" and continue to log in.

Now look at the contents of /tmp/ndslog/ndslog.log
You will see in the log the text you entered on the form as getval=<......>.

This means that in the themespec file, just before auth_log() is called, the variable, defined as $getval in this case, will contain the text entered by the client.
So obviously you can add your own code at that point to do something with the entered text and maybe depending on the content, decide not to call auth_log(), thus denying access to that client.
