### ISSUE TITLE
Opennds deletes user customized entries in /etc/hosts when it starts

### ISSUE THREAD

**Issue by doctor-ox** [openNDS/openNDS#307]
After starting opennds service, I lost some updates I did in /etc/hosts .

Investigating I found openNDS/forward_authentication_service/libs/dnsconfig.sh,  host.conf setup part, has different issues:
- It does not allow to match all the gw_ip / gw_fqdn (e.g. when spaces in /etc/hosts are replaced by tabs) 
- It modifies /etc/hosts entries that are not exactly matching $gw_ip or $gw_fqdn (thus potentialy deleting wrong entries in /etc/hosts when opennds service starts)
- It deletes lines that may be used for other fqdn on the gateway IP  (i.e. if entry has 2 FQDNs like 4.3.2.1 userfqdn gwfdqn)
- It is case sensitive while fqdn in /etc/hosts are case insensitive . (so won't remove gw_fqdn with different case)
- It assumes gw_fqdn is the first fqdn in /etc/hosts record of gw_ip 

In order to fix all these at once, on my system I replaced lines 68 to 93 of openNDS/forward_authentication_service/libs/dnsconfig.sh by the following ones:
	
	 elif [ "$setconf" = "hostconf" ]; then
		gw_ip=$2
		gw_fqdn=$3
		host_entry="$gw_ip $gw_fqdn" 

		# Add record GW_IP GW_FQDN in /etc/hosts file if GW_IP does not exist
		grep -qw "^$gw_ip" /etc/hosts || (echo "$host_entry" >> /etc/hosts)

		# Add GW_FQDN as an alias to GW_IP record where GW_FDQN alias is missing
		sed -i "/^$gw_ip[[:space:]]\+/ { /[[:space:]]$gw_fqdn[[:space:]]/I! {  /[[:space:]]$gw_fqdn$/I! s/[[:space:]]*$/ $gw_fqdn/}}" /etc/hosts

		# Remove GW_FQDN from IPs different from GW_IP
		sed -i "/^$gw_ip[[:space:]]\+/! { s/\([[:space:]]\)$gw_fqdn[[:space:]]/\1/Ig;s/\([[:space:]]\)$gw_fqdn$//I}" /etc/hosts

		printf "%s" "done"
		exit 0

**Comment by bluewavenet** [comment]
@doctor-ox 
Thanks for this, the fix is much appreciated and will get tested today hopefully for incorporation into the v9.6.0 release.

I was aware of the problem but fixing was low on the ToDo list as it does not effect the majority of  installations (ie a dedicated venue CP on commodity hardware ). It did however effect some of the things I was doing enough for me to notice!

**Comment by bluewavenet** [comment]
@doctor-ox 
The only problem I can see with this is that sed rewrites or at least touches the hosts file. 
It is bad practice from a flash wear point of view to write to the flash unnecessarily, even though this will only be on a restart...
Lets see - copy hosts to tmpfs would work...

**Comment by doctor-ox** [comment]
@bluewavenet 
You are right.  I reworked the code to avoid unnecessary writes:


        gw_ip=$2
        gw_fqdn=$3
        host_entry="$gw_ip $gw_fqdn"

        # generate a tmp filename on tmpfs
        ram_hosts=$(mktemp --tmpdir=/run/tmpfiles.d)

        cp -p /etc/hosts "$ram_hosts" &&
        (
          # Add record GW_IP GW_FQDN in /etc/hosts file if GW_IP does not exist
          grep -qw "^$gw_ip" $ram_hosts || (echo "$host_entry" >> $ram_hosts)

          # Add GW_FQDN as an alias to GW_IP record where GW_FDQN alias is missing
          sed -i "/^$gw_ip[[:space:]]\+/ { /[[:space:]]$gw_fqdn[[:space:]]/I! {  /[[:space:]]$gw_fqdn$/I! s/[[:space:]]*$/ $gw_fqdn/}}" $ram_hosts

          # Remove GW_FQDN from IPs different from GW_IP
          sed -i "/^$gw_ip[[:space:]]\+/! { s/\([[:space:]]\)$gw_fqdn[[:space:]]/\1/Ig;s/\([[:space:]]\)$gw_fqdn$//I}" $ram_hosts

          # rewrite /etc/hosts file only after an update
          diff -b $ram_hosts /etc/hosts &>/dev/null ||  mv $ram_hosts /etc/hosts
        )

        # cleanup
        rm -f $ram_hosts

        printf "%s" "done"
        exit 0

**Comment by bluewavenet** [comment]
@doctor-ox 
That looks good for generic Linux, but requires the diffutils package on OpenWrt (not installed by default for space saving).
I'm looking at using uncommitted uci config for the OpenWrt case....

**Comment by bluewavenet** [comment]
@doctor-ox 

```
	gw_ip=$2
	gw_fqdn=$3

	if [ -z "$uciconfig" ]; then
		# Generic Linux
		host_entry="$gw_ip $gw_fqdn"
		# generate a tmp filename on tmpfs
		ram_hosts=$(mktemp --tmpdir=/run/tmpfiles.d)

		cp -p /etc/hosts "$ram_hosts" &&
		(
			# Add record GW_IP GW_FQDN in /etc/hosts file if GW_IP does not exist
			grep -qw "^$gw_ip" $ram_hosts || (echo "$host_entry" >> $ram_hosts)

			# Add GW_FQDN as an alias to GW_IP record where GW_FDQN alias is missing
			sed -i "/^$gw_ip[[:space:]]\+/ { /[[:space:]]$gw_fqdn[[:space:]]/I! {  /[[:space:]]$gw_fqdn$/I! s/[[:space:]]*$/ $gw_fqdn/}}" $ram_hosts

			# Remove GW_FQDN from IPs different from GW_IP
			sed -i "/^$gw_ip[[:space:]]\+/! { s/\([[:space:]]\)$gw_fqdn[[:space:]]/\1/Ig;s/\([[:space:]]\)$gw_fqdn$//I}" $ram_hosts

			# rewrite /etc/hosts file only after an update
			diff -b $ram_hosts /etc/hosts &>/dev/null ||  mv $ram_hosts /etc/hosts
		)

		# cleanup
		rm -f $ram_hosts

	else
		# OpenWrt
		# Note we do not commit here so that the config changes do NOT survive a reboot and can be reverted without writing to config files
		host_entry="/$gw_fqdn/$gw_ip"
		del_dns="del_list dhcp.@dnsmasq[0].address='$host_entry'"
		add_dns="add_list dhcp.@dnsmasq[0].address='$host_entry'"
		echo $del_dns | uci batch
		echo $add_dns | uci batch
	fi

	printf "%s" "done"
	exit 0

```

**Comment by doctor-ox** [comment]
@bluewavenet

If you want avoid extra binaries, diff can be replaced by testing temp file is newer than /etc/hosts.

So:

         diff -b $ram_hosts /etc/hosts &>/dev/null ||  mv $ram_hosts /etc/hosts

Becomes:

        if [ "$ram_hosts" -nt /etc/hosts ]; then 
                mv "$ram_hosts" /etc/hosts
        fi

**Comment by bluewavenet** [comment]
@doctor-ox 

> diff can be replaced by testing temp file is newer than /etc/hosts

Yes but the new OpenWrt section does not even touch the hosts file any more, instead, telling dnsmask to resolve it only when opennds is running, in the same way it does already with dhcp_option_force and ipset.

**Comment by bluewavenet** [comment]
@doctor-ox 
Version 9.6.0 is now released and these fixes are included.
