### ISSUE TITLE
Double Base64

### ISSUE THREAD

**Issue by dorkone** [openNDS/openNDS#308]
https://github.com/openNDS/openNDS/blob/2aa24b3621785502c967cdf377bbf40dc100cd48/src/http_microhttpd.c#L1364

[PHP](https://www.php.net/manual/en/function.openssl-encrypt.php)

The openssl_encrypt function already returns a base64 encoded string. You are then base64_encoding it again.

In order to decrypt outside of PHP (Golang for example) I must
`raw = b64decode(b64decode(fas))`

Also, you're appending a bunch of undefined values before creating the ciphertext.. ends up with a ton of garbage at the end
`b'hid=..., clientip=..., clientmac=..., client_type=..., gatewayname=..., version=9.5.1, gatewayaddress=..., gatewaymac=..., authdir=..., originurl=..., clientif=..., themespec=(null), (null)(null)(null)(null)\t\t\t\t\t\t\t\t\t'`

**Comment by bluewavenet** [comment]
@dorkone 

> In order to decrypt outside of PHP (Golang for example) I must
> raw = b64decode(b64decode(fas))

Yes. It is done this way for planned future enhancements.

> Also, you're appending a bunch of undefined values before creating the ciphertext.. ends up with a ton of garbage at the end

No. Some, from themespec onwards might be null, depending on config values eg custom parameters etc.
These are not currently used in the fas-aes examples, but will be in the future and indeed can already be used for custom FAS development.
If you are getting the values before themespec undefined, you must have something wrong as these will always be populated with actual client or gateway values, meaning you do not know anything about the client.

**Comment by dorkone** [comment]
> Yes. It is done this way for planned future enhancements.
Okay. Will just have to take your word that it's the right approach 👍 

> If you are getting the values before themespec undefined, you must have something wrong as these will always be populated with actual client or gateway values, meaning you do not know anything about the client.

No, the '...' values are populated with real data. Just found it odd that null / nonexistent values are still included. If that's by-design, it's easy enough to discard them when parsing the decrypted string.
