### ISSUE TITLE
openNDS doesn't trigger CPD popup (nodogsplash does)

### ISSUE THREAD

**Issue by Ryazbeck** [openNDS/openNDS#31]
I was using NDS with binauth, but decided to solve my problem using FAS, so I put a fresh raspbian lite buster on my SD and first thing I did was this guide:

https://opennds.readthedocs.io/en/stable/compile.html

then i setup ap0, reboot, ap0 is up, my phone is connected to it, ndsctl shows running, but CPD does not popup. 
However if I run the same config using nodogsplash the CPD triggers the "login to wifi" popup as expected

I have confirmed this using the default setup for both NDS and OpenNDS. All I changed is the gatewayinterface.
NDS triggers CPD popup while OpenNDS does not.

Logs don't show any errors.

**Comment by bluewavenet** [comment]
@Ryazbeck 
If you stop opennds, does your phone get internet access?

**Comment by Ryazbeck** [comment]
> @Ryazbeck
> If you stop opennds, does your phone get internet access?

Well, I don't have that forwarding setup, because it's not intended to browse the internet with. It's for configuring the pi through the CPD.

**Comment by bluewavenet** [comment]
@Ryazbeck 
Without  routed Internet with NAT and DNS, CPD will not work so neither openNDS nor Nodogsplash will be triggered  to display the splash page on the client CPD. The only way to make it work is to simulate an Internet feed to make the client CPD think it is blocked by the CP.

**Comment by Ryazbeck** [comment]
> @Ryazbeck
> Without routed Internet with NAT and DNS, CPD will not work so neither openNDS nor Nodogsplash will be triggered to display the splash page on the client CPD. The only way to make it work is to simulate an Internet feed to make the client CPD think it is blocked by the CP.

I forgot to put the line /#/<ap0_gateway> in `dnsmasq.conf` 

Thanks for your help

**Comment by bluewavenet** [comment]
@Ryazbeck 
Excellent, I like it when the answer is a simple one :-D

### Note:
Some more recent implementations of CPD by vendors require the resolved IP address to be in a **_PUBLIC_** range. Such a vendor implementation would not trigger if the resolved ip address was a private one.

A good address to use in dnsmasq conf would be 123.123.123.123, but anything public, chosen at random, will do

**Comment by Ryazbeck** [comment]
@bluewavenet  I'd like to revisit this.

My pi is connected:

> pi@raspberrypi:~/yarden-gnome-station/portal$ ping 8.8.8.8
> PING 8.8.8.8 (8.8.8.8) 56(84) bytes of data.
> 64 bytes from 8.8.8.8: icmp_seq=1 ttl=117 time=28.4 ms

My phone and laptop are connected to the pi's hotspot
I can reach the hosted site via gateway port 8000 in browser on phone and laptop

However, OpenNDS does not recognize the connected client

> Version: 5.1.0
> Uptime: 6m 47s
> Gateway Name: YardenGnome
> Managed interface: ap0
> Managed IP range: 0.0.0.0/0
> Server listening: http://192.168.100.1:2050
> Binauth: Disabled
> Preauth: Disabled
> FAS: Secure Level 0, URL: http://192.168.100.1:8000/
> Client Check Interval: 30s
> Preauth Idle Timeout: 10m
> Auth Idle Timeout: 120m
> Traffic control: no
> Total download: 149 kByte; avg: 2.94 kbit/s
> Total upload: 527 kByte; avg: 10.36 kbit/s
> 
> Client authentications since start: 0
> Current clients: 0
> 
> Blocked MAC addresses: none
> Allowed MAC addresses: N/A
> Trusted MAC addresses: none
> 

What else do I need to provide?

**Comment by bluewavenet** [comment]
```
FirewallRuleSet preauthenticated-users {
FirewallRule allow all
}

```
This will allow clients to bypass NDS entirely. It means "allow access to everything", CPD will never trigger the Portal.
Check the default conf file, FirewallRuleSet preauthenticated-users has no entries as none are required. Entries here are for the creation of a walled garden.

**Comment by bluewavenet** [comment]
Note also from the default opennds.conf:

```
# Option: GatewayAddress
#
# Deprecated
#
# Default: Discovered from GatewayInterface
#
# It need not and probably should not be specified.
# If set here, it must be set to the IP address of the router on
# the GatewayInterface.
#
# Setting may result in failure of openNDS to start automatically at boot time
# Setting incorrectly will result in failure of openNDS.
```

**Comment by bluewavenet** [comment]
I would also suggest (from the default conf):

```
FirewallRuleSet users-to-router {
 # openNDS automatically allows tcp to GatewayPort,
 # at GatewayAddress, to serve the splash page.
 # However you may want to open up other ports, e.g.
 # 53 for DNS and 67 for DHCP if the router itself is
 # providing these services.
    FirewallRule allow udp port 53	
    FirewallRule allow tcp port 53	
    FirewallRule allow udp port 67
 # You may want to allow ssh, http, and https to the router
 # for administration from the GatewayInterface.  If not,
 # comment these out.
   FirewallRule allow tcp port 22
   FirewallRule allow tcp port 80
   FirewallRule allow tcp port 443
}
```

**Comment by Ryazbeck** [comment]
Hey, thanks for always getting back so quick.

I started fresh with raspbian buster, compiled opennds using the guide and used the conf file below and still same thing. 
My phone is connected but reads "connected, no internet"
I can ping google from the pi
And I can see the hosted site at the pi's gateway address.

> GatewayInterface ap0
> 
> GatewayName YardenGnome
> 
> GatewayPort 2050
> 
> FirewallRuleSet authenticated-users {
>   FirewallRule allow all
> }
> 
> FirewallRuleSet preauthenticated-users {
> }
> 
> FirewallRuleSet users-to-router {
>    FirewallRule allow udp port 53	
>    FirewallRule allow tcp port 53	
>    FirewallRule allow udp port 67
>    FirewallRule allow tcp port 22
>    FirewallRule allow tcp port 80
>    FirewallRule allow tcp port 443
>    # FirewallRule allow tcp port 8000
> }
> 
> MaxClients 2
> SessionTimeout 0
> MACMechanism block
> TrafficControl no
> GatewayIPRange 0.0.0.0/0
> DebugLevel 0
> 
> fasport 8000
> faspath /
> fas_secure_enabled 0

**Comment by Ryazbeck** [comment]
I think I may be missing some configuration on the machine that forwards traffic from AP to the WLAN

This same configuration worked when I was using NDS 4.5. I used dnsmasq to point all traffic to the AP's gateway, but earlier you asked 

> If you stop opennds, does your phone get internet access?

And no, that's not the case. Maybe that's why?

**Comment by bluewavenet** [comment]
@Ryazbek
You are overthinking it now. I do see traces of the many outdated NoDogsplash tutorials that can be found out there and to be honest they are at best misleading, so not your fault, it is more that you are coming from the Rpi direction rather than the OpenWrt direction.

Lets rewind :-D

Ultimately you want to work offline (ie without an Internet connection) for your YardenGnome system...
So, rewind steps:

### Step 1. Get it working online.

**Rpi setup.** There are numerous prerequisites to put into place BEFORE installing OpenNDS, listed in the documentation:
https://opennds.readthedocs.io/en/stable/install.html#prerequisites

Test this by connecting using your phone for example. You should have open Internet access.

### Step 2. Install OpenNDS
Install and leave with all defaults apart from setting GatewayInterface
You should be able to restart using the command `service opennds restart`

Test by re-connecting your phone. This time you should get the simple templated "Click to Continue" splash page.
If not then there is something we need to fix.

### Step 3. Enable FAS
Set the config options fasport and faspath (only these, nothing else is be required). Restart openNDS.

Test by re-connecting your phone. This time you should get your FAS page.
If not then there is something we need to fix.

### Step 4. Enable Offline Mode in dnsmasq.conf
It is important that you use a random public ip4 address for this, eg:
`address=/#/123.123.123.123`

Restart both openNDS and dnsmasq (maybe even reboot) and test again.

**Comment by Ryazbeck** [comment]
@bluewavenet 

Okay, fresh install of buster

1. Wifi and AP are connected. My phone is connected to YardenGnome and can browse the internet (mobile is disabled on my phone)
2. LMH and OpenNDS installed
3. Fas enabled, here's the conf:


```
GatewayInterface ap0

GatewayName YardenGnome

GatewayPort 2050

FirewallRuleSet authenticated-users {
  FirewallRule allow all
}

FirewallRuleSet preauthenticated-users {
}

FirewallRuleSet users-to-router {
   FirewallRule allow udp port 53	
   FirewallRule allow tcp port 53	
   FirewallRule allow udp port 67
   FirewallRule allow tcp port 22
   FirewallRule allow tcp port 80
   FirewallRule allow tcp port 443
}

MaxClients 2
SessionTimeout 0
MACMechanism block
TrafficControl no
GatewayIPRange 0.0.0.0/0
DebugLevel 0

fasport 8000
faspath /
```
I hosted a local index.html on port 8000 using `python3 -m http.server 8000` 
Restart opennds
Reconnected my phone and now it says "connected, no internet" so it seems opennds is preventing browsing
However I get no CPD popup.

Just to confirm that local port 8000 is responding I did a `wget` on both `192.168.100.1:8000` and `0.0.0.0:8000` and both are successful

**Comment by bluewavenet** [comment]
What happened when you tested at my Step 2 above, ie without FAS?

Tell your phone to "forget" the wifi ssid, then reconnect. Does it work then?

Remove these for now:
```

MaxClients 2
SessionTimeout 0
MACMechanism block
TrafficControl no
GatewayIPRange 0.0.0.0/0
DebugLevel 0
```

**Comment by Ryazbeck** [comment]
> What happened when you tested at my Step 2 above, ie without FAS?

Same, "Connected, no internet", no CPD, and OpenNDS sees zero clients 

[opennds.conf.txt](https://github.com/openNDS/openNDS/files/4996068/opennds.conf.txt)

> Tell your phone to "forget" the wifi ssid, then reconnect. Does it work then?

same

**Comment by bluewavenet** [comment]
Do you have ipv6 dhcp enabled?

**Comment by bluewavenet** [comment]
Can you try with another device ie not your phone?

**Comment by bluewavenet** [comment]
The next step is to set debuglevel 3.
`ndsctl debuglevel 3`

Then try reconnecting and look at the logs.

**Comment by Ryazbeck** [comment]
> Can you try with another device ie not your phone?

Tried laptop and wife's phone. same. 
ubuntu for laptop and android for our phones

> Do you have ipv6 dhcp enabled?

I didn't, but I do now

`
pi@raspberrypi:/etc/opennds$ ping google.com
PING google.com(dfw25s25-in-x0e.1e100.net (2607:f8b0:4000:80e::200e)) 56 data bytes
64 bytes from dfw25s25-in-x0e.1e100.net (2607:f8b0:4000:80e::200e): icmp_seq=1 ttl=117 time=17.9 ms
`

> look at the logs.

You can see in the logs where I enabled debuglevel 3. Nothing happens when I connect to ap0. 

[journalctl.log](https://github.com/openNDS/openNDS/files/4996225/journalctl.log)

**Comment by scornieller** [comment]
I am following this very closely as I can't get it to work with the bare minimum as well:
-Debian 10
-Works perfectly fine as a wireless router (hostapd/dnsmasq) when opennds is stopped

GatewayInterface wlx2cb05d6b67ab

FirewallRuleSet authenticated-users {
  FirewallRule allow all
}

FirewallRuleSet preauthenticated-users {
   FirewallRule allow tcp port 53
   FirewallRule allow udp port 53
}

FirewallRuleSet users-to-router {
   FirewallRule allow udp port 53
   FirewallRule allow tcp port 53
   FirewallRule allow udp port 67
   FirewallRule allow tcp port 22
   FirewallRule allow tcp port 80
   FirewallRule allow tcp port 443
}

And nothing more to accept the defaults on opennds.conf

Does not work trigger the CPD popup.

**Comment by bluewavenet** [comment]
@Ryazbeck
Having ipv6 running is bad as some CPD implementations preferentially use it, thus preventing the trigger of the splash page.
So turn it back off.

It is worth looking at the documentation about CPD for a better understanding of how it works:
https://opennds.readthedocs.io/en/stable/howitworks.html#captive-portal-detection-cpd

Your logs show at first it was attempting to bind with the default interface "br-lan". Presumably you edited the config to use ap0 as it changes to attempting to use that.

ap0 seems to take a very long time to come up but does eventually, so all well and good, but this may indicate some sort of issue.. or not....

Can you please post the output of the command:
`ip neigh`

**Comment by Ryazbeck** [comment]
`ip neigh`

This is what it looks like whether my phone is connected or not.

`pi@raspberrypi:/etc/opennds$ ip neigh
192.168.1.24 dev wlan0 lladdr b8:08:cf:3d:cf:08 STALE
192.168.100.4 dev ap0 lladdr b8:08:cf:3d:cf:08 STALE
192.168.100.24 dev ap0  FAILED
192.168.1.1 dev wlan0 lladdr a8:9a:93:a4:70:e2 REACHABLE
192.168.100.12 dev ap0 lladdr d0:77:14:8f:4a:72 REACHABLE
fe80::aa9a:93ff:fea4:70e2 dev wlan0 lladdr a8:9a:93:a4:70:e2 router STALE
`

**Comment by bluewavenet** [comment]
As a test, try accessing a non https web site that does not support https
One of the common CPD urls is ideal. An example I use in testing is http://onboard-wifi.net

Do this after connecting of course :-D

**Comment by Ryazbeck** [comment]
> As a test, try accessing a non https web site that does not support https

That works while connected to ap0

**Comment by bluewavenet** [comment]
http://onboard-wifi.net works by forcing the splash page to appear?

Are you running on your devices, one of the "https everywhere" security apps? These disable client CPD and are not necessary with modern browsers.

**Comment by bluewavenet** [comment]
Can you also post the output of:
`ip route`

**Comment by Ryazbeck** [comment]
> http://onboard-wifi.net works by forcing the splash page to appear?

sorry. it loads the onboard-wifi.net page.

> Are you running on your devices, one of the "https everywhere" security apps? These disable client CPD and are not necessary with modern browsers.

No. CPD works fine on my laptop and phone with NDS <=4.5


> pi@raspberrypi:/etc/opennds$ ip route
> default via 192.168.1.1 dev wlan0 
> 192.168.1.0/24 dev wlan0 proto kernel scope link src 192.168.1.83 
> 192.168.100.0/24 dev ap0 proto kernel scope link src 192.168.100.1

**Comment by bluewavenet** [comment]
@scornieller
Can you also try accessing http://onboard-wifi.net with opennds running?

I have openNDS running on OpenWrt and on a headless openSUSE. No issues with multiple client types.
However I do not have an RPi or Debian machine to test on. I suspect though, more a client issue at the moment.

**Comment by bluewavenet** [comment]
@Ryazbeck

> sorry. it loads the onboard-wifi.net page.

That must mean openNDS is not running.
The current iptables code in openNDS 5.1.0 is identical to that in NoDogSplash 4.5

**Comment by Ryazbeck** [comment]
I just wanted to run it as a service. It's cleaner than nodogsplash.

**Comment by Ryazbeck** [comment]
> That must mean openNDS is not running.

I posted iptables, the machine openNDS is running. I'm not sure why it isn't recognizing anything

**Comment by bluewavenet** [comment]
@Ryazbeck
Post the output of:
`iptables -t nat -S ndsOUT`

**Comment by bluewavenet** [comment]
For example, I get:
```
17117:~# iptables -t nat -S ndsOUT
-N ndsOUT
-A ndsOUT -m mark --mark 0x20000/0x30000 -j RETURN
-A ndsOUT -m mark --mark 0x30000/0x30000 -j RETURN
-A ndsOUT -p tcp -m tcp --dport 80 -j DNAT --to-destination 10.239.1.1:2050
-A ndsOUT -j ACCEPT

```

**Comment by bluewavenet** [comment]
Do you get the openNDS logo image at http://192.168.100.1:2050/images/splash.jpg ?

**Comment by Ryazbeck** [comment]
> pi@raspberrypi:~$ sudo iptables -t nat -S ndsOUT
> -N ndsOUT
> -A ndsOUT -m mark --mark 0x20000/0x30000 -j RETURN
> -A ndsOUT -m mark --mark 0x30000/0x30000 -j RETURN
> -A ndsOUT -p tcp -m tcp --dport 80 -j DNAT --to-destination 192.168.100.1:2050
> -A ndsOUT -j ACCEPT

> Do you get the openNDS logo image at http://192.168.100.1:2050/images/splash.jpg ?

no

**Comment by bluewavenet** [comment]
Ah!! Debian Buster...
Try running:
`update-alternatives --set iptables /usr/sbin/iptables-legacy`

**Comment by bluewavenet** [comment]
If you don't get the logo image, then MHD is not working.....

**Comment by Ryazbeck** [comment]
> update-alternatives --set iptables /usr/sbin/iptables-legacy

I ran that and nothing happened. then I ran `sudo service opennds restart`

and immediately the "sign in" pops up for the CPD. When I tap it shows a blank page, and the client doesn't show up in openNDS, the openNDS logs don't show any clients, and when I return to the wifi selection screen i no longer have the option to "sign in". 

Seems like the sign in option only lasts for a moment.

**Comment by Ryazbeck** [comment]
> If you don't get the logo image, then MHD is not working.....

That would explain a lot. How can I check the status and logs of MHD?

**Comment by bluewavenet** [comment]
Which version of MHD did you install?
Set debuglevel 3 in the conf file and restart opennds.
Then post the logs again.

**Comment by Ryazbeck** [comment]
MHD 0.9.71

[journalctl.log](https://github.com/openNDS/openNDS/files/4997649/journalctl.log)

**Comment by bluewavenet** [comment]
> the "sign in" pops up for the CPD. When I tap it shows a blank page

What do you  mean by this? Are you seeing splash.html?

**Comment by Ryazbeck** [comment]
no splash.html, nothing loads. when i get the "sign in" pop up for the CPD, I tap it and it takes me to the CPD portal browser with a blank white page. Normally it would load the "continue" page on NDS 4.5

**Comment by bluewavenet** [comment]
Try  http://192.168.100.1:2050/images/splash.jpg then post the logs again.
ps your time is set to BST... are you in the UK?

**Comment by bluewavenet** [comment]
I am running MHD 0.9.70-2, I wonder if there is an issue with 0.9.71........
We're sure exploring all the possibilities ;-)

**Comment by Ryazbeck** [comment]
> Try http://192.168.100.1:2050/images/splash.jpg then post the logs again.
> ps your time is set to BST... are you in the UK?

No I'm in central time. Just didn't bother setting that up. Do you think it could be a problem?

> I am running MHD 0.9.70-2, I wonder if there is an issue with 0.9.71........

I will install fresh with that version of MHD and see what happens.

> We're sure exploring all the possibilities ;-)

I appreciate your help, I'd love to get this working as planned :)

**Comment by bluewavenet** [comment]
See my edit above - I upgraded MHD, still works fine.

**Comment by bluewavenet** [comment]
Your rpi is defaulted to UTC most likely. Time zone makes no difference.

**Comment by Ryazbeck** [comment]
I tried the splash.jpg again but nothing shows up in the logs. It's just been repeating this every 30 seconds

> Jul 29 23:21:23 raspberrypi opennds[12485]: [7][Wed Jul 29 23:21:23 2020][12659](src/auth.c:226) Rate Check Window is set to 2 period(s) of checkinterval
> Jul 29 23:21:23 raspberrypi opennds[12485]: [7][Wed Jul 29 23:21:23 2020][12659](src/fw_iptables.c:1014) Locking client list
> Jul 29 23:21:23 raspberrypi opennds[12485]: [7][Wed Jul 29 23:21:23 2020][12659](src/fw_iptables.c:1014) Client list locked
> Jul 29 23:21:23 raspberrypi opennds[12485]: [7][Wed Jul 29 23:21:23 2020][12659](src/main.c:106) SIGCHLD handler: Trying to reap a child
> Jul 29 23:21:23 raspberrypi opennds[12485]: [7][Wed Jul 29 23:21:23 2020][12659](src/main.c:120) SIGCHLD handler: Process PID 13095 exited normally, status 0
> Jul 29 23:21:23 raspberrypi opennds[12485]: [7][Wed Jul 29 23:21:23 2020][12659](src/main.c:106) SIGCHLD handler: Trying to reap a child
> Jul 29 23:21:23 raspberrypi opennds[12485]: [7][Wed Jul 29 23:21:23 2020][12659](src/main.c:120) SIGCHLD handler: Process PID 13097 exited normally, status 0
> Jul 29 23:21:23 raspberrypi opennds[12485]: [7][Wed Jul 29 23:21:23 2020][12659](src/fw_iptables.c:1093) Unlocking client list
> Jul 29 23:21:23 raspberrypi opennds[12485]: [7][Wed Jul 29 23:21:23 2020][12659](src/fw_iptables.c:1093) Client list unlocked
> Jul 29 23:21:23 raspberrypi opennds[12485]: [7][Wed Jul 29 23:21:23 2020][12659](src/auth.c:234) Locking client list
> Jul 29 23:21:23 raspberrypi opennds[12485]: [7][Wed Jul 29 23:21:23 2020][12659](src/auth.c:234) Client list locked
> Jul 29 23:21:23 raspberrypi opennds[12485]: [7][Wed Jul 29 23:21:23 2020][12659](src/auth.c:414) Unlocking client list
> Jul 29 23:21:23 raspberrypi opennds[12485]: [7][Wed Jul 29 23:21:23 2020][12659](src/auth.c:414) Client list unlocked

**Comment by bluewavenet** [comment]
Add 
`CheckInterval 300`
to the config. Then those bits will only log every 15 minutes. It will make it easier to see what is going on for the bits we are interested in.
Restart opennds then try to access http://192.168.100.1:2050/images/splash.jpg
Post the logs again.

**Comment by bluewavenet** [comment]
When I access the splash.jpg image, the logs show:
`Wed Jul 29 22:41:57 2020 daemon.debug opennds[27362]: access: GET /images/splash.jpg`

**Comment by Ryazbeck** [comment]
Did all that. Same results. Doesn't seem like the opennds page is being served by anything.

**Comment by bluewavenet** [comment]
@Ryazbeck
What do the logs say now you have done all this?

I have openNDS running on:
OpenWrt arm_cortexa7, mips_24kc, mipsel_24kc and x86-64
OpenSuse Leap x86-64

Also I am aware of people running on Rpi4 Raspian and Rpi4 Openwrt.

All this points to your config somewhere.

**Everything points to MHD not receiving requests.**

Try again and show me the logs....I just know it is going to be something so simple when we find it!
Better post the current config file as well just to make sure I have the actual one you are using.

**Comment by bluewavenet** [comment]
Are you adding/restoring any iptables entries?

**Comment by Ryazbeck** [comment]
> What do the logs say now you have done all this?

Repeats this every 5 mins

> Jul 30 21:49:30 raspberrypi opennds[2342]: [7][Thu Jul 30 21:49:30 2020][2516](src/main.c:106) SIGCHLD handler: Trying to reap a child
> Jul 30 21:49:30 raspberrypi opennds[2342]: [7][Thu Jul 30 21:49:30 2020][2516](src/main.c:120) SIGCHLD handler: Process PID 2700 exited normally, status 0
> Jul 30 21:49:30 raspberrypi opennds[2342]: [7][Thu Jul 30 21:49:30 2020][2516](src/main.c:106) SIGCHLD handler: Trying to reap a child
> Jul 30 21:49:30 raspberrypi opennds[2342]: [7][Thu Jul 30 21:49:30 2020][2516](src/main.c:120) SIGCHLD handler: Process PID 2702 exited normally, status 0
> Jul 30 21:49:30 raspberrypi opennds[2342]: [7][Thu Jul 30 21:49:30 2020][2516](src/fw_iptables.c:1093) Unlocking client list
> Jul 30 21:49:30 raspberrypi opennds[2342]: [7][Thu Jul 30 21:49:30 2020][2516](src/fw_iptables.c:1093) Client list unlocked
> Jul 30 21:49:30 raspberrypi opennds[2342]: [7][Thu Jul 30 21:49:30 2020][2516](src/auth.c:234) Locking client list
> Jul 30 21:49:30 raspberrypi opennds[2342]: [7][Thu Jul 30 21:49:30 2020][2516](src/auth.c:234) Client list locked
> Jul 30 21:49:30 raspberrypi opennds[2342]: [7][Thu Jul 30 21:49:30 2020][2516](src/auth.c:414) Unlocking client list
> Jul 30 21:49:30 raspberrypi opennds[2342]: [7][Thu Jul 30 21:49:30 2020][2516](src/auth.c:414) Client list unlocked


> All this points to your config somewhere.

I'm using the default opennds config

> Try again and show me the logs....I just know it is going to be something so simple when we find it!

I tried again, logs never show any activity from my phone or laptop when I connect to the hotspot.

> Are you adding/restoring any iptables entries?

No


[journalctl.log](https://github.com/openNDS/openNDS/files/5003749/journalctl.log)

[opennds.conf.txt](https://github.com/openNDS/openNDS/files/5003751/opennds.conf.txt)

**Comment by Ryazbeck** [comment]
I'm running a pi Zero, which is armv6. I believe pi4 is armv7 or v8. Not sure if that makes a difference.

How can i investigate the status of MHD? I don't see a service or logs or anything like that.

**Comment by bluewavenet** [comment]
@Ryazbeck
Show the output of:
`iptables -t filter -S ndsRTR`

I've ordered a piZW - they are cheap enough. I have not bothered previously as the onboard Broadcom wireless chip's  drivers are not open source thus causing limitations if used in other than STA modes. The gpio probably makes it ideal for your application though!

**Comment by Ryazbeck** [comment]
> I've ordered a piZW 

Nice!

> pi@raspberrypi:~$ sudo iptables -t filter -S ndsRTR
> -N ndsRTR
> -A ndsRTR -m mark --mark 0x10000/0x30000 -j DROP
> -A ndsRTR -m conntrack --ctstate INVALID -j DROP
> -A ndsRTR -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT
> -A ndsRTR -p tcp -m tcp ! --tcp-option 2 --tcp-flags SYN SYN -j DROP
> -A ndsRTR -p tcp -m tcp --dport 2050 -j ACCEPT
> -A ndsRTR -m mark --mark 0x20000/0x30000 -j ACCEPT
> -A ndsRTR -p udp -m udp --dport 53 -j ACCEPT
> -A ndsRTR -p tcp -m tcp --dport 53 -j ACCEPT
> -A ndsRTR -p udp -m udp --dport 67 -j ACCEPT
> -A ndsRTR -p tcp -m tcp --dport 22 -j ACCEPT
> -A ndsRTR -p tcp -m tcp --dport 80 -j ACCEPT
> -A ndsRTR -p tcp -m tcp --dport 443 -j ACCEPT
> -A ndsRTR -j REJECT --reject-with icmp-port-unreachable

**Comment by bluewavenet** [comment]
@Ryazbeck
piZW arrived and loaded up OpenWrt but as I expected the wireless drivers do not support ap and sta modes simultaneously (due to licencing reasons). Currently downloading raspios-lite.

**Comment by bluewavenet** [comment]
@Ryazbeck
Can you share your pi network/wireless config? I can then replicate what you have.

**Comment by bluewavenet** [comment]
@Ryazbeck
More hardware... usb wireless dongle and adaptor ordered.
Really, honestly, this is reinforcing my previous opinion that Raspberry Pi is not a good platform for anything involving routing. I will continue down the rabbit hole of this sunk cost fallacy just a little bit longer :-D

**Comment by scornieller** [comment]
> @Ryazbeck
> More hardware... usb wireless dongle and adaptor ordered.
> Really, honestly, this is reinforcing my previous opinion that Raspberry Pi is not a good platform for anything involving routing. I will continue down the rabbit hole of this sunk cost fallacy just a little bit longer :-D

Should have gone with the pi 3, cheaper, includes wired eth :)

I am paying a lot of a attention to this post; I've got a minimal configuration for Debian 10 (hostapd+dnsmasq), can't make it work. It runs but nothing happen when I connect to the hotspot, can't even access the webserver on port 2050. It does work as router when Opennds is stopped and `update-alternatives --set iptables /usr/sbin/iptables-legacy` does not help.

GatewayInterface wlx2cb05d6b67ab

FirewallRuleSet authenticated-users {
  FirewallRule allow all
}

FirewallRuleSet preauthenticated-users {
   FirewallRule allow tcp port 53
   FirewallRule allow udp port 53
}

FirewallRuleSet users-to-router {
   FirewallRule allow udp port 53
   FirewallRule allow tcp port 53
   FirewallRule allow udp port 67
   FirewallRule allow tcp port 22
   FirewallRule allow tcp port 80
   FirewallRule allow tcp port 443
}

GatewayName Hotspot
login_option_enabled 0

**Comment by bluewavenet** [comment]
@scornieller
Dongle and OTG adaptor have arrived so I will have a look this evening (utc+1).
I have a feeling it will be something simple :-D

**Comment by bluewavenet** [comment]
@scornieller @Ryazbeck
I get errors compiling under raspios-lite but not OpenWrt and OpenSuse and libmicrohttpd does not respond under raspios-lite.
I've not had time to investigate yet.

**Comment by bluewavenet** [comment]
@scornieller @Ryazbeck
 have updated the code to get rid of the compiler errors/warnings and updated the MHD code for the most up to date API from there.
Now on a piZW with usb wireless dongle:
 1. on raspios-lite - MHD will not respond.
 2. on OpenWrt - everything works

The obvious conclusion is an issue with raspios-lite. I will have to look closer at the issue. Something missing?.....

**Comment by scornieller** [comment]
@bluewavenet mhd not working there probably has something to do with it not working on my debian 10 config, most certainly part of the same.

**Comment by bluewavenet** [comment]
@Ryazbeck @scornieller 
I have found the cause of this issue. It is due to a duplicate setup of the MHD daemon, causing it to be unresponsive on some operating systems (not sure why only on some).
PR for fix coming asap.

**Comment by bluewavenet** [comment]
@Ryazbeck @scornieller 
I would much appreciate it if you both could download, compile and test:
https://github.com/openNDS/openNDS/archive/master.zip
Note: MHD v 0.9.71 or higher is required.

**Comment by Ryazbeck** [comment]
@bluewavenet It worked!

**Comment by bluewavenet** [comment]
I'll  be doing a new release shortly....

**Comment by scornieller** [comment]
@bluewavenet @Ryazbeck confirmed it does work on Debian 10 as well :)

**Comment by bluewavenet** [comment]
@Ryazbeck 
Version 6.0.0 is now released.
