### ISSUE TITLE
Session control (FAS)

### ISSUE THREAD

**Issue by 0l4y4** [openNDS/openNDS#313]
Hi!

for configuration in FAS HTTPS mode, opennds sends the fas and iv variables to the server and they are resent each time they are needed. 
Have you thought of any alternative to be able to store the data on the server through sessions?

**Comment by bluewavenet** [comment]
@0l4y4 

> the fas and iv variables to the server and they are resent each time they are needed.

Yes, but as you suggest there are alternative ways to achieve this.
There is no overhead sending again, rather the overhead is decrypting every time. Even so this is in most cases insignificant.

One case where it _**can**_ be significant is when the FAS is a local ThemeSpec script. Many low cost routers are resource constrained to some degree and ThemeSpec FAS does its own version of "session control", storing client data in client specific files on the router to speed up the process - in principle very similar to PHP session files.

The php script fas-aes-https.php is only an example, feel free to modify it in any way you find suitable for your purposes.
