### ISSUE TITLE
Trusted users - session information via ndsctl

### ISSUE THREAD

**Issue by dorkone** [openNDS/openNDS#314]
Is there any way to keep track of

```
      "download_this_session":"0",
      "upload_this_session":"0",
```
... for trusted users? It is always "0" for me (9.6.0)

I am trying to use ndsctl trust/untrust to support roaming between OpenNDS instances, but would still like to keep track of bandwidth consumption. I could use a hook in dnsmasq to use auth/deauth instead - but this is much more simple

**Comment by bluewavenet** [comment]
@dorkone 
Trusted users are just that, 100% trusted and therefore not tracked in any way. 
A "Trusted User" is intended to be something like a "non-human user", ie a trustable IoT device, a point of sales terminal etc.

openNDS does however support the creation of your own CP Roaming function using a dnsmasq hook as you suggest.
See:
https://opennds.readthedocs.io/en/stable/config.html#allow-preemptive-authentication

**Comment by bluewavenet** [comment]
@dorkone 
Before spending a lot of time on this, it is worth considering that there is one major problem with CP Roaming.
As most recent client devices now often use randomised mac addresses for new SSID connections, roaming may not work.

**Comment by dorkone** [comment]
That's too bad! The trust / untrust method was so simple. Sadly, bandwidth consumed is a strict requirement, so I will have to write a quick hook and polling endpoint.

Yes, the random MAC address issue has been considered. I will be using the same SSID throughout, so hopefully that negates some of that. I plan on putting a warning+instructions on the captive portal page regarding that, so users that want a seamless roam can disable it.

Thanks for all your help!

**Comment by bluewavenet** [comment]
@dorkone 
FYI - Very brief summary of my non-definitive findings from analysing opennds logs, over various devices, Apples and Androids mostly - as follows:

 * Some devices keep the same random mac for a given ssid until the device gets restarted (causes havoc when there are multiple ssids on a single CP eg for different zones, so is becoming rare as probably phased out by OTA updates).
 * Some keep the same mac for a given time interval (or a device restart), then change on the next connection regardless of the ssid (**seems currently to be the most common**)

The random mac idea is to prevent systems tracking devices from location to location - unfortunately that is just what CP roaming is trying to do.....

**Comment by dorkone** [comment]
Thanks for the info. I'd imagine there will always have to be some support for identical SSIDs, or there would be all sorts of usability issues with mesh networks. Thankfully, this should be a fairly quick hop between networks, so I'm hoping a timeout won't trigger.

https://source.android.com/devices/tech/connect/wifi-mac-randomization-behavior

At least Google seems to be aware of this.

I just hope it is only tied to SSID and not to local IP, or I'll probably have to sync DHCP servers as well!
