### ISSUE TITLE
Several access pages FAS

### ISSUE THREAD

**Issue by 0l4y4** [openNDS/openNDS#316]
Hi,

Is it possible to add several access pages before logging in in HTTPS FAS?

**Comment by bluewavenet** [comment]
@0l4y4 
Yes. Study the example script and all will be revealed ;-)

**Comment by 0l4y4** [comment]
@bluewavenet 

fas-aes-https.php?

**Comment by bluewavenet** [comment]
@0l4y4 

> fas-aes-https.php?

Yes :-D

**Comment by 0l4y4** [comment]
@bluewavenet 

I want to allow the access for example to:
 - https://example1.com/login
 - https://example1.com/register
 - https://example1.com/forget-password
 - https://example1.com

**Comment by bluewavenet** [comment]
@0l4y4 
For clarity, do you mean you want options for:

- client login
- client registration
- client password reset
- client access to everything on the FAS server

?

**Comment by 0l4y4** [comment]
@bluewavenet 

Yes, and they are different routes

**Comment by bluewavenet** [comment]
Different routes?

**Comment by 0l4y4** [comment]
@bluewavenet 

https://example1.com/login is different that https://example1.com/register

No?

If I configure opennds with:
- option fasremotefqdn 'example1.com'
- option faspath '/login'

what happens when the user goes to the registry

**Comment by bluewavenet** [comment]
You could have a login page with the following buttons:
1. login - normal login
2. register - "Not got an account" click register button
3. Reset password - logs user in and gives password reset dialogue
4. Additional buttons for other info etc as required.

**Comment by bluewavenet** [comment]
Probably better to have a "reset password" button on the thankyou page.

**Comment by 0l4y4** [comment]
@bluewavenet 

I have these buttons but when you do click go to another page, opennds allows this?

**Comment by bluewavenet** [comment]
> opennds allows this?

fasremotefqdn sets up a walled garden for the FAS server ip address(es).

faspath is the path to the web page the client is redirected to on first connecting.

**Comment by 0l4y4** [comment]
@bluewavenet 

And authentication with login?

**Comment by bluewavenet** [comment]
Authentication  with Google? 
You seem to be going off on multiple tangents  :-D

**Comment by 0l4y4** [comment]
@bluewavenet 

I would like to allow access throught login and google account. Is it weird?

**Comment by bluewavenet** [comment]
@0l4y4 
Not weird but definitely not what a growing number of people want, mainly for privacy reasons.
You would have to integrate Google Identity Services into your FAS credential verification.
https://developers.google.com/identity/gsi/web

**Comment by 0l4y4** [comment]
@bluewavenet 

I know it, but I mean about walled garden

**Comment by bluewavenet** [comment]
FAS would run on a remote server so the client does not talk to Google direct. No special walled garden should be needed.

**Comment by bluewavenet** [comment]
@0l4y4 
My diagram on #289 shows the flow for accessing a third party AAA like Google IS (lines 9 and 10)
https://user-images.githubusercontent.com/13632068/147838369-3c99cf75-c6f3-44c3-b02c-ee3a87731f29.png
