### ISSUE TITLE
How can i includ HTML file using iframe ?

### ISSUE THREAD

**Issue by Rayen-cherni** [openNDS/openNDS#319]
I need to inculde some HTML files in my captive portal using iframe balise.
I set the login_option_enabled to 3, i put my iframe in the theme_click-to-continue-custom-placeholders.sh and  i set the advert1 to be my src variable in the iframe.
But the iframe doesn't work  
I use openNDS v9.6 !
Any help please !

**Comment by bluewavenet** [comment]
@Rayen-cherni 
The client device blocks iframes as they are forbidden by the client CPD for security reasons.

**Comment by Rayen-cherni** [comment]
and if i allow the traffic between my remote server and the openNDS by add the IP address of my remote server to my opennds ?

**Comment by bluewavenet** [comment]
@Rayen-cherni 
It is the CPD browser on the client device that rejects iframes. There is nothing you can do about it.
