### ISSUE TITLE
OpenNDS can not install on openwrt 19.07.3

### ISSUE THREAD

**Issue by nongquanghuong** [openNDS/openNDS#32]
When i install with "opkg install opennds": It give me "* opkg_install_cmd: Cannot install package opennds."
When i install with ipk file, it require lib  libmicrohttpd 0.9.69 or higher, but my openwrt have 0.9.63 and i can not upgrade it becase it is not upgradeable.
Should I must do to reslove it? Thank you!

**Comment by nongquanghuong** [comment]
I find a solution at #31

**Comment by bluewavenet** [comment]
For the benefit of others:
Add the option use_outdated_mhd
eg on OpenWrt:
```
uci set opennds.@opennds[0].use_outdated_mhd='1'
uci commit opennds
service opennds restart
```
