### ISSUE TITLE
[9.6.0] dhcpcheck can sometimes return a malformed MAC

### ISSUE THREAD

**Issue by doctor-ox** [openNDS/openNDS#320]
dhcpcheck returns malformed MAC due to multiple answers to a grep and too large search.  

libopennds.sh v9.6.0

line 931
			dhcprecord=$(grep "$iptocheck " "$dhcpdb" | awk '{printf "%s", $2}')

On my device, I had two different issues:

1) same IP multiple times in a lease file

        ~# dhcpdb=/var/lib/misc/dnsmasq.leases 
        ~# iptocheck=4.3.2.109

        ~# grep "$iptocheck " /var/lib/misc/dnsmasq.leases               
        1646333675 70:f0:88:6b:ea:0d 4.3.2.109 * *
        1646333675 70:f0:88:6b:ea:0d 4.3.2.109 * *

        ~# dhcprecord=$(grep "$iptocheck " "$dhcpdb" | awk '{printf "%s", $2}')
        ~# echo $dhcprecord                                            
        70:f0:88:6b:ea:0d70:f0:88:6b:ea:0d                <==== malformed MAC

2) similarIP multiple times in a lease file

        ~# dhcpdb=/var/lib/misc/dnsmasq.leases 
        ~# iptocheck=4.3.2.10 

        ~# grep "$iptocheck " /var/lib/misc/dnsmasq.leases
        1646333675 70:f0:88:6b:ea:0d 4.3.2.10 * *
        1646333675 70:f0:88:6b:ea:0d 34.3.2.10 * *

        ~# dhcprecord=$(grep "$iptocheck " "$dhcpdb" | awk '{printf "%s", $2}')
        ~# echo $dhcprecord                                            
        70:f0:88:6b:ea:0d70:f0:88:6b:ea:0d         <==== malformed MAC

For the second issue you can code

        dhcprecord=$(grep " $iptocheck " "$dhcpdb" | awk '{printf "%s", $2}')

or

        dhcprecord=$(grep -w "$iptocheck" "$dhcpdb" | awk '{printf "%s", $2}')

For the first issue, I have no idea which record is to be prioritized: first one?  last one? other one? 
On my device I found till four times the exact same record in lease file.
Keeping only should be OK then, I guess the last one as it should be the most recent reference.

        dhcprecord=$(grep -w "$iptocheck" "$dhcpdb" | tail -1 | awk '{printf "%s", $2}')

**Comment by bluewavenet** [comment]
@doctor-ox 
More good finds thanks!
I thought we had caught all the "grep by string" occurrences that could break something.
Your examples are incorrectly edited together ip address wise, _but I do see exactly what you mean_.

In the first case, dnsmasq would not add two records for the same mac. Maybe if the leases file was configured to be on non volatile storage (not recommended), you could get two records after a reboot, but then they would have different time stamps.

I'm adding the fix. ;-)

**Comment by doctor-ox** [comment]
@bluewavenet

Yes, first case lease file changed before I saved.  I changed by hand to reproduce the issue.

Note that I found other grep ones that can be fixed by adding -w to the grep, e.g.
- get_client_token.sh 
  - 2 times in wait_for_ndsctl, that can return wrong pid and thus wrong client status, 

- client_params.sh 
  - in parse_parameters that can return wrong parameter, especially for short parameter names like "ip" and "mac": if any of the paramaters or its value contains a (sub)string "mac" or "ip", e.g. if gatewayname=Tips or gatewayname=macadam in /etc/opennds/opennds.conf, then parse_parameters returns wrong ip or mac parameters' value.

- get_client_interface.sh
  - main gets pid that could be a wrong one, e.g. if another process that contains get_client_interface in its name.
 
Also almost similar issue  because I subnetted and setup multiple ips on my gateway interface  (ip on wlan1 and wlan1:0).  These issues required the code is changed.
- util.c 
   - get_iface_ip did not return the right ip (it returned empty one)

Current code

        snprintf(cmd, sizeof(cmd), "ip address | grep -A2 ': %s' | grep '%s ' | awk '$NF == \"%s\" {print $2}' | awk -F'/' 'NR==1 {printf $1}'",  
                ifname,
                iptype,
                ifname 
        );

Proposed fix

        snprintf(cmd, sizeof(cmd), "ip address | grep ' %s$' | grep '%s ' | awk '{print $2}' | awk -F'/' 'NR==1 {printf $1}'", 
                ifname,
                iptype
        );

- libopennds.sh
  - check_gw_mac returns wrong mac_sys when my gateway IP is on wlan1:0.  

Current code

        mac_sys=$(cat "/sys/class/net/$ifname/address") 

Proposed fix

        ifn=$(echo $ifname | cut -d':' -f1)
        mac_sys=$(cat "/sys/class/net/$ifn/address")
        mac_sys=${mac_sys:0:17}

**Comment by doctor-ox** [comment]
Note I saw that in client_params.sh, parse_parameter has been updated recently to fix this but new code does not fix e.g. if gateway_name is "Tip" or "Tarmac" or "Diversion".  There is also a problem when someone gives the name of any parameter to the gateway_name...  
So gateway_name should be tested and some names forbidden (all the parameter names at least).

**Comment by bluewavenet** [comment]
@doctor-ox 
Again, thanks for your time and effort ;-)

1. get_client_token.sh is deprecated since v8.0.0, so about time it was removed.

2. client_params.sh - As it is parsing a json output  where all values are strings, a good fix would be:
 ` val=$(echo "$param_str" | grep "\"$param\":" | awk -F'"' '{printf "%s", $4}')`

3. get_client_interface.sh - The fix would be:
 `pid=$(pgrep -f "/bin/sh /usr/lib/opennds/get_client_interface.sh")`

4. libopennds.sh - As far as I am aware a ":" is invalid if used in an interface name.... If I try create an interface like "wlan1:0" on for example OpenWrt or OpenSUSE, it fails and I get an error.....

5. util.c - Is this when you have interface name "wlan0:1"?

**Comment by doctor-ox** [comment]
@bluewavenet 

4. fails because of point 5 ;-)

With the proposed fix, it works fine:

        ~# ifconfig wlan1
        wlan1: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
                inet 4.3.2.1  netmask 255.255.255.0  broadcast 4.3.2.255
        ...
        ~# ifconfig wlan1:0
        wlan1:0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
                inet 4.3.3.1  netmask 255.255.255.0  broadcast 4.3.3.255
                ether dc:a6:32:d2:1e:72  txqueuelen 1000  (Ethernet)


        ~# ndsctl status
        ==================
        openNDS Status
        ====
        Version: 9.5.2beta
        Uptime: 18s
        Gateway Name: [ XxxX ]
        Debug Level: [ 3 ]
        Gateway FQDN: [ status.client ]
        Managed interface: wlan1:0
        Upstream gateway(s) [ online:192.168.0.1,eth0  ]
        MHD Server [ version 0.9.75 ] listening on: http://4.3.3.1:2050
        Maximum Html Page size is [ 10240 ] Bytes
        Preemptive Authentication is Disabled
        Binauth Script: /usr/lib/opennds/binauth_log.sh
        Preauth Script: /usr/lib/opennds/libopennds.sh
        FAS: Secure Level 1, URL: http://4.3.3.1:2050/opennds_preauth/
        Client Check Interval: 60s
        Rate Check Window: 2 check intervals (120s)
        Preauthenticated Client Idle Timeout: 3m
        Authenticated Client Idle Timeout: 5m
        Download rate limit (default per client): no limit
        Upload rate limit (default per client): no limit
        Download quota (default per client): no limit
        Upload quota (default per client): no limit
        Total download: 0 kByte; avg: 0.00 kbit/s
        Total upload: 0 kByte; avg: 0.00 kbit/s
        ====
        Client authentications since start: 0
        Current clients: 0

**Comment by bluewavenet** [comment]
@doctor-ox 
What operating system are you using? I cannot create an interface with a ":" in it....... So I will never see this problem....

Are you using openNDS 9.5.2beta? v9.6.0 is the current release.

**Comment by bluewavenet** [comment]
@doctor-ox 
It looks like I can use only "A-Z", "a-z", "0-9", "-" and "_" in interface names.

**Comment by doctor-ox** [comment]
@bluewavenet

I'm running Raspbian, but this is a standard linux and unix feature adding an IP alias on an interface. 
In RHEL,CentOS and Raspian,  you can add it using ifconfig e.g: in my case

        ifconfig wlan1 add 4.3.3.1

On OpenWRT, maybe you need to declare wlan1.0  instead of wlan1:0, what makes my fix incorrect on OpenWRT.   

On Suse, syntax to assign alias IP may be different. I think the add is implicit so

        ifconfig wlan1:0 4.3.3.1 

Be aware this is not another interface, that is an IP alias on an existing interface.  That is the reason why you need to remove the suffix to get the interface's MAC from /sys/class.

**Comment by bluewavenet** [comment]
@doctor-ox 
If I do ` ifconfig wlan1 add 4.3.3.1`

then do `ifconfig wlan1:0`

I get `ifconfig: wlan1:0: error fetching interface information: Device not found`

on both OpenWrt and openSUSE

But `ifconfig wlan1` shows the newly added ip address (4.3.3.1).

**Comment by doctor-ox** [comment]
@bluewavenet

It is then not standard and better I keep it experimental as my AP also is.
 
Your fixes:

1) OK

2) OK     

3) OK

4)  You can give up this fix but you should prevent users from configuring gateway interface name that contains . or :

5) (util.c), yes it is when there is one or more aliases on the gateway interface.  wlan1:0, wlan1:1 etc...  It returns the ip of the first alias instead of the main ip of the interface.
E.g.  correct IP for wlan1 is 4.3.2.1 but 

        ~#  ip address
        ....
        4: wlan1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP group default qlen 1000
            link/ether dc:a6:32:d2:1e:72 brd ff:ff:ff:ff:ff:ff
            inet 4.3.4.1/24 brd 4.3.4.255 scope global wlan1:1
               valid_lft forever preferred_lft forever
            inet 4.3.2.1/24 brd 4.3.2.255 scope global noprefixroute wlan1
               valid_lft forever preferred_lft forever
        
        ~# ip address | grep -A2 ': wlan1'
        4: wlan1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP group default qlen 1000
            link/ether dc:a6:32:d2:1e:72 brd ff:ff:ff:ff:ff:ff
            inet 4.3.4.1/24 brd 4.3.4.255 scope global wlan1:1       <====  Incorrect IP

**Comment by doctor-ox** [comment]
@bluewavenet

As I can read, OpenSUSE and OpenWrt got rid of deprecated ifconfig and are recommend use of ip.

I tested adding an alias IP with command ip instead of ifconfig and the result is different: ip does not create a alias name wlan1:0 but keeps wlan1.  All the added aliases get the same interface name.

        ~# ip a  add 4.3.3.1/24  broadcast 4.3.3.255 dev wlan1
        ~# ip a
        ...
        4: wlan1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP group default qlen 1000
            link/ether dc:a6:32:d2:1e:72 brd ff:ff:ff:ff:ff:ff
            inet 4.3.2.1/24 brd 4.3.2.255 scope global noprefixroute wlan1
               valid_lft forever preferred_lft forever
            inet 4.3.3.1/24 brd 4.3.3.255 scope global wlan1           <====  No new name !!!!
               valid_lft forever preferred_lft forever

So the fix I proposed for util.c does not work and I don't see how to get the correct ip, unless the config file specifies which ip address openNDS has to bind to gateway interface (in case of multiple IP)s.

**Comment by bluewavenet** [comment]
@doctor-ox 
The problem is that ip aliasing is deprecated. Instead you should be creating a virtual interface for the additional ip address.
That is easy in OpenWrt and I am sure it is in generic Linux, _**I/we will have to have to do a bit of reading to find out**_.

Anyway, these links are useful:
https://openwrt.org/docs/guide-developer/networking/network.interfaces
https://www.kernel.org/doc/html/latest/networking/alias.html

**Comment by bluewavenet** [comment]
@doctor-ox 
It's quite straightforward. Here is a good link:
https://askubuntu.com/questions/265285/virtual-wireless-interface

**Comment by doctor-ox** [comment]
@bluewavenet
Thanks for the links. 
I tested on different wifi interfaces with different drivers. 
Unfortunately, none of these drivers' support virtual interfaces. 
I have to investigate, change drivers or cards.

**Comment by bluewavenet** [comment]
@doctor-ox 
Look for the "valid interface combinations" or "software interface modes" section (depends on distro) in the output of `iw list`
If you are using the Rpi built in wireless, then yes you are stuck....

**Comment by bluewavenet** [comment]
@doctor-ox 
I just tried a Ralink 5370 based usb adaptor in a Pi zero in RaspOS and it works fine.
Output of `iw list`:
```
	valid interface combinations:
		 * #{ AP, mesh point } <= 8,
		   total <= 8, #channels <= 1

```
so it can handle up to 8 virtual interfaces on the one phy interface in any combination of modes STA (default), AP and mesh point, but only on the same channel for all modes.

In contrast, the output for the RPi's onboard wireless:
```
	software interface modes (can always be added):
		 * AP/VLAN
		 * monitor
	interface combinations are not supported
```
This means it can be only one of STA (default), AP/VLAN or monitor.

**Comment by bluewavenet** [comment]
@doctor-ox 
Ok, fixed 1 to 3 are done.
This leaves us with the question, do we detect and block an "old fashioned" alias - and give a warning, or do we add your patch (or something like it) anyway?........

**Comment by doctor-ox** [comment]
@bluewavenet 

None of my fixes for points 4 and 5 is correct.  

For now, detect and block gateway interface name containing forbidden characters is the best solution, warning user can use virtual interfaces.
The same if gateway interface holds more than one IP.
  
Besides the pi's interface, I'm using two dongles [MT7610U] 

1)  
       Device supports configuring vdev MAC-addr on create.
       valid interface combinations:
                 * #{ IBSS } <= 1, #{ managed, AP, mesh point, P2P-client, P2P-GO } <= 2,
                   total <= 2, #channels <= 1, STA/AP BI must match

2)
       valid interface combinations:
                 * #{ managed } <= 1, #{ P2P-device } <= 1, #{ P2P-client, P2P-GO } <= 1,
                   total <= 3, #channels <= 2
                 * #{ managed } <= 1, #{ AP } <= 1, #{ P2P-client } <= 1, #{ P2P-device } <= 1,
                   total <= 4, #channels <= 1
 
The virtual interface creation finally worked on the first one.

I will try to find a way interface single name with multiple IPs to work, e.g.  add a parameter bind address in cfg file (GatewayBindAddress ?)  that will hold the IP to use when GatewayInterface is assigned multiple IPs.  
In case multiple IP on interface and no bind address in cfg file openNDS could start with the first it finds in the ip address list but has to raise a warning to the user.

**Comment by bluewavenet** [comment]
@doctor-ox 
Your second dongle can support a total of 3 virtual interfaces, but only one of any type. In your case you want, say, 2 APs, so this dongle cannot do the job. (it could however have 1 AP and 1 managed (STA), and be used to provide a wireless link to an upstream router as well as an SSID for users).

Multiple ip addresses on a single interface - this used to be called multi-homing in the dim and distant past I seem to remember.

On a server it can be useful eg multiple web servers, one to each ip address. This is how the original "www" servers back in the 1990's were configured.

But on a router it should not really be used as things can get very complicated very quickly particularly in a router with wireless, vlans and a built in managed switch... And if the multiple ip addresses are not all on the same subnet...... yikes, a not insignificant degree of malfunction would be likely.

**My current opinion is** to allow  only one ipv4 address per interface and if more than one is present - bomb out with critical config error and a suggestion to use virtual interfaces.

**Comment by doctor-ox** [comment]
@bluewavenet

Yes, as get_iface_ip is called only at startup, you can allow one and only one IPv4.

Be aware that this function belongs to util.c.
Any caller should receive the same unique IP or rejection.
E.g.  if someone add an alias IP on the gw_if after opennds has started  (only one IPv4 at that time) .
