### ISSUE TITLE
How to build FAS server?

### ISSUE THREAD

**Issue by lyt0112** [openNDS/openNDS#321]
Hi,
After reading https://opennds.readthedocs.io/en/stable/fas.html
I have some questions:

If I have two linux routers:
One linux router A: wan public IP is 100.100.100.1 LAN subnet is 192.168.1.254/24
Another linux router B: wan public IP is 200.200.200.1 LAN subnet is 192.168.2.254/24

LAN PCs(192.168.1.x) behind router A want to access internet must authenticate via openNDS captive portal.

Router B need to be FAS server , right? how to build FAS server?

Router A need to config the following config?
Edit the file /etc/config/opennds
adding the lines:
option fasport '2080'
option faspath '/nds/fas-aes.php'
option fas_secure_enabled '2'
option faskey '1234567890'
Restart NDS using the command service opennds restart

**Comment by bluewavenet** [comment]
@lyt0112 

> If I have two linux routers

**_Do you want them both to run openNDS and share a common FAS?_**

> Router B need to be FAS server , right? how to build FAS server?
> Router A need to config the following config?
> option fasport '2080'
> option faspath '/nds/fas-aes.php'
> option fas_secure_enabled '2'
> option faskey '1234567890'

This will configure openNDS on router A to point to a fas server also running on router A 
What does this have to do with router B?

**Comment by lyt0112** [comment]
@bluewavenet 
I want to build and test FAS functions...
So I prepare two linux PCs ...
Router B want to be FAS server...but I don't know how to do it.

**Comment by bluewavenet** [comment]
@lyt0112 
You don't need 2 routers for this. A FAS server can be:
1. Local - on the openNDS router
2. Local - on the LAN
3. Remote - on Internet based hosting

Setting up a FAS is fully documented here:
https://opennds.readthedocs.io/en/stable/fas.html#forwarding-authentication-service-fas

If your router is a Linux based PC, I would suggest using OpenWrt as the operating system. This will be optimised for routing functionality and make it very much easier to provide help and support.
https://downloads.openwrt.org/releases/21.02.2/targets/x86/64/
For initial testing you could make a usb boot drive for OpenWrt.

**Comment by lyt0112** [comment]
@bluewavenet 

**A FAS server can be:
Local - on the openNDS router
Local - on the LAN**

http://fasremoteip:fasport/faspath?authaction=http://gatewayaddress:gatewayport/opennds_auth/?clientip=[clientip]&gatewayname=[gatewayname]&tok=[token]&redir=[requested_url]

=>what is fasremoteip:fasport & gatewayaddress:gatewayport on my case if I only use 1 router A?

**Comment by bluewavenet** [comment]
@lyt0112 
This is fully described in the documentation, but I am happy to clarify.

When FAS is  "_**Local - on the openNDS router**_" you can choose to use libmicrohttpd (MHD) or install another web server if you want to use a scripting language such as PHP.

To use MHD (the default) you use the ThemesSpec api. ThemeSpec scripts are (b)ash scripts. Numerous preinstalled examples are provided.

The example php scripts (fas-hid, fas-aes and fas-aes-https) are PHP scripts written to be run on a web server with PHP support. 

> [http://fasremoteip:fasport/faspath?authaction=http://gatewayaddress:gatewayport/opennds_auth/?clientip=[clientip]&gatewayname=[gatewayname]&tok=[token]&redir=[requested_url]](http://fasremoteip:fasport/faspath?authaction=http://gatewayaddress:gatewayport/opennds_auth/?clientip=%5Bclientip%5D&gatewayname=%5Bgatewayname%5D&tok=%5Btoken%5D&redir=%5Brequested_url%5D)

This is a deprecated and insecure access method and should not be used.
See:
https://opennds.readthedocs.io/en/stable/fas.html#security

**I would suggest you configure to use one of the supplied FAS PHP scripts to get a feel for how it works.**
For this you must install/use a separate web server with PHP support (uhttpd with additional php packages is an example).
See:
https://opennds.readthedocs.io/en/stable/fas.html#using-the-fas-example-scripts-fas-hid-fas-aes-php-and-fas-aes-https-php

**Comment by lyt0112** [comment]
@bluewavenet 
**use MHD (the default) you use the ThemesSpec api. ThemeSpec scripts are (b)ash scripts**
Yes,I've built it and working well.
Now I want to have a splash page which support https , so I start to try the php scripts.
Is it possible to use original solution without php web and scripts?

**Comment by bluewavenet** [comment]
@lyt0112 

> Now I want to have a splash page which support https
Is it possible to use original solution without php web and scripts?

**No**. The FAS server must have valid tls certificates that are recognised by client devices.
 
For an https splash page sequence, the FAS **must** be hosted on an Internet web server.
See:
https://opennds.readthedocs.io/en/stable/fas.html#example-script-file-fas-aes-https-php

**Comment by lyt0112** [comment]
@bluewavenet 
If I use FAS , I need to put the verification process function in the /usr/lib/opennds/binauth_log.sh?
On the field:
# Exit, setting level (only effective for auth_client)
# exit 0 tells NDS it is ok to allow the client to have access.
# exit 1 would tell NDS to deny access.

**Comment by bluewavenet** [comment]
@lyt0112 

> If I use FAS , I need to put the verification process function in the /usr/lib/opennds/binauth_log.sh ....?

**No**. Binauth should never be used for verification.
For details of the use of binauth, see:
https://opennds.readthedocs.io/en/stable/binauth.html#binauth-option

Verification is done by FAS. Once a clients credentials have been verified, FAS sends a request for authentication to openNDS.

Binauth is not required. It can be used for local logging if enabled. If so desired, it is possible to write a custom binauth to override the received FAS authentication parameters based on local requirements.

**Comment by lyt0112** [comment]
@bluewavenet 
**FAS sends a request for authentication to openNDS.**
=>where should I put my authentication code on FAS structure?

**Comment by bluewavenet** [comment]
@lyt0112 
If you want an https login page, first you must set up an Internet hosted web server with valid TLS certificates and php support.
Then copy the standard fas-aes-https.php file to the Internet server and configure your openNDS config to use it.

**It MUST be an Internet hosted web server with valid TLS, otherwise it will not work.**

Check and test to make sure it is working correctly with its username/email-address login. You can check the log file created on the web server.

Once this is all working correctly, we can look at how to add your own verification. Linking to a third party verification is quite simple, as is changing or adding to the login form for collecting client credentials.

**It is essential that it is tested as working before making any changes to fas-aes-https.php**

_Let me know when you have all this working, or if you need help getting it working._

**Comment by lyt0112** [comment]
@bluewavenet 
**It MUST be an Internet hosted web server with valid TLS, otherwise it will not work.**
Is it possible to issue my certificate by openssl and then ask php code use it to do https?

**Comment by bluewavenet** [comment]
@lyt0112 

>  Is it possible to issue my certificate by openssl and then ask php code use it to do https?

No.
https has two main purposes:
1. To encrypt data in transit
2. To ensure the requested web site is the correct one and not some man in the middle imposter.

To put it simply, the certificates must be issued by a recognised "issuer" and be for the actual web site. If not the client will receive dire security warnings and openNDS will refuse authentication requests.

To prevent any confusion you should also read this:
https://opennds.readthedocs.io/en/stable/faq.html#is-an-https-splash-page-supported

and this:
https://opennds.readthedocs.io/en/stable/faq.html#is-https-capture-supported

**Comment by lyt0112** [comment]
@bluewavenet 

I don't need https capture supported, but I need https splash page.

**To put it simply, the certificates must be issued by a recognised "issuer" and be for the actual web site. If not the client will receive dire security warnings and openNDS will refuse authentication requests.**
=>I checked some network device's captive portal demo function and can support issue self certificate for https splash page.

Is it modify "post-request.php" 's context_options and then add ssl array to trust self issued certificates ?

**Comment by bluewavenet** [comment]
@lyt0112 

> Is it achieved by modif[y]ing "post-request.php" 's context_options and then add ssl array to trust self-issued certificates ?

**No**.
That would make the authentication work at the expense of compromising openNDS security, but even then **_all clients will give the users dire warning messages._**

There is no way round it, this is how https works and is intended for security. It has nothing to do with openNDS.

**You _MUST_ host your https FAS on an Internet web server.** 
Any web hosting service supporting php can be used, even the very cheapest, as the traffic requirements are very low.

**Comment by lyt0112** [comment]
@bluewavenet 
ok...thanks for the explain

**Comment by khaledmouna8** [comment]
@bluewavenet hi, i'm tryin to configure a https Fas and i want to know if there is any way to get rid of the port number in the url 
[http://fasremoteip:fasport/faspath?authaction=http://gatewayaddress:gatewayport/opennds_auth/?clientip=[clientip]&gatewayname=[gatewayname]&tok=[token]&redir=[requested_url]]
