### ISSUE TITLE
"No such file or directory" from binauth_log.sh 

### ISSUE THREAD

**Issue by doctor-ox** [openNDS/openNDS#323]
Received error message:

    Mar  9 21:25:59 raspberrypi opennds[29059]: /usr/lib/opennds/binauth_log.sh: line 255: /run/ndscids/TBmMGJhMTJhMmMyZWJmYjZkZDdiMjQzM2VjZWYyOGEzNzIwNDY1YzU0NmE0ODdiOTRmODdhMTNlZGYyNWUzNjYTU0NmZjOTFlZTM5NGI1M2FlOGM2ZGE3NTQzNGRmNzk0MTYyY2Y2MzFhYjliOThkZjY5NjhlMDZmZWRhMGVhODE: No such file or directory

Root cause 2 files for the same MAC in  /run/ndscids folder.  

    /usr/lib/opennds# ls -lrt  /run/ndscids/
    total 8
    -rw-r--r-- 1 root root 661 Mar  9 21:25 TU0NmZjOTFlZTM5NGI1M2FlOGM2ZGE3NTQzNGRmNzk0MTYyY2Y2MzFhYjliOThkZjY5NjhlMDZmZWRhMGVhODE
    -rw-r--r-- 1 root root 505 Mar  9 21:25 TBmMGJhMTJhMmMyZWJmYjZkZDdiMjQzM2VjZWYyOGEzNzIwNDY1YzU0NmE0ODdiOTRmODdhMTNlZGYyNWUzNjY
    /usr/lib/opennds# grep -r a6:62:09:c0:f0:f4 /run/ndscids  | awk -F 'ndscids/' '{print $2}' | awk -F ':' '{printf $1}'
    TBmMGJhMTJhMmMyZWJmYjZkZDdiMjQzM2VjZWYyOGEzNzIwNDY1YzU0NmE0ODdiOTRmODdhMTNlZGYyNWUzNjYTU0NmZjOTFlZTM5NGI1M2FlOGM2ZGE3NTQzNGRmNzk0MTYyY2Y2MzFhYjliOThkZjY5NjhlMDZmZWRhMGVhODE

After systemctl restart opennds, when client connected before the restart reconnects, old file is still there and new one is created => 2 files same MAC.

**Comment by bluewavenet** [comment]
@doctor-ox 

> After systemctl restart opennds, when client connected before the restart reconnects, old file is still there and new one is created

Something is lost in translation there - I don't understand what you mean.
When openNDS starts it clears any old files.....

**Comment by bluewavenet** [comment]
@doctor-ox 
I have just tested on a pi with Raspios. A `systemctl restart opennds` restarts opennds as expected and all old files are deleted.
This is with the default config after installing.

Can you show your config file?

**Comment by doctor-ox** [comment]
@bluewavenet
I did some more tests.  Restart well deletes files.  
That is when the previously authenticated device reconnects just after opennds is up again that 2 files are created.
I can reproduce so will be able to record and provide the sequence.
