### ISSUE TITLE
Authentication Processing remote FAS

### ISSUE THREAD

**Issue by Rayen-cherni** [openNDS/openNDS#331]
I have a remote FAS (based on python) get client credentials and verifies.**(Validation process)** 
Now after validation process, i need to notice the openNDS to allow the verified client to get internet access.
How can i do it? 
To any virtual URL i need to send the tok?  
**Hint:** I received the fas encoded string sent by opennds to remote FAS, i successfully decoded it and get the information such as hid, clientip,...etc.
Also i concatenate the hid and key and i hashed the entire string to send it to the opennds ( as mentioned in the docs) 
**My config:** 
Router model : Xiaomi 4A gigabit edition
OpenNDS version: 9.6.0
fas secure enabled levels: 1

**Comment by bluewavenet** [comment]
@Rayen-cherni 
See documentation at:
https://opennds.readthedocs.io/en/stable/fas.html#authentication-method-for-fas-secure-enabled-levels-0-1-and-2

openNDS sends the hid to FAS when using level 1

> Also i concatenate the hid and key and i hashed the entire string to send it to the opennds 

This is the "rhid" or "return hashed id".
For authentication on level 0, 1 and 2 , you have to send either the token or the rhid.
For security, at level 1, openNDS does not send the token but sends the hid.
What you have to do is send the value of the rhid in place of the token (that you do not have), in the url shown in the documentation link above.
