### ISSUE TITLE
b64encode & decoding

### ISSUE THREAD

**Issue by 25khattab** [openNDS/openNDS#333]
Hello hope you are fine,
the string i send to encode_custom is this "omar" but when i recieve it in binauth.sh it comes like this "b21hcg%3d%3d" but it should be like this instead "b21hcg=="

**Comment by bluewavenet** [comment]
@25khattab 
The custom string is sent to binauth via the url query string so it is **_also_** url encoded.
This means the b64encoding pad characters (if any) will appear as "%3d"

In binauth, you need to urldecode it. eg:
`custom_url_decoded=$(printf "${custom//%/\\x}")`

**Comment by 25khattab** [comment]
@bluewavenet 
thanks that was helpful.
there is another problem in currently facing when I write code in vscode and copy it to openwrt  the script doesn't run because there is always special characters included like ^M and other characters any tip how to avoid this ?

**Comment by bluewavenet** [comment]
@25khattab 

> when I write code in vscode and copy it to openwrt the script doesn't run because there is always special characters included like ^M and other characters any tip how to avoid this ?

I am not familiar with vscode, but it is not suitable for editing Linux scripts. Windows uses ctrl m (or ascii cr) at the end of lines where just about everything else uses the newline character.
There might be a setting in vscode to change this, but as I said, I am not familiar with it at all.
