### ISSUE TITLE
Add "expires" field to fas_secure_enabled >= 2

### ISSUE THREAD

**Issue by dorkone** [openNDS/openNDS#334]
As of now, the same `?fas=...&iv=...` can be used indefinitely. It would be much more secure if the messages had an optional lifespan - The FAS script can prevent re-use of the same query string.

Also - it would be neat if there was an option in http_microhttpd.c to forward every request to the FAS server with a populated query string - So the FAS server can potentially create it's own status page. I've had to create a custom statuspath script that pulls all the information that microhttpd already retrieved in order to do the same.

**Comment by dorkone** [comment]
I must have not been clear, my apologies.

I do not want to use anything besides the redirect that microhttpd uses to forward requests to the FAS. I am currently accomplishing this with a custom `client_params.sh` script that just replicates much of what happens when that redirect is performed. It just seemed redundant, and it would be a neat feature. Maybe I'll fork and PR when I have some time. It's not so much for me as I've already accomplished my goal - it's more for others that may want similar functionality. I would gain by saving a redundant call to ndsctl.

It's a very advanced use case, I know, and totally beyond what the average OpenNDS implementer would want.

Thanks for taking a look!

**Comment by bluewavenet** [comment]
@dorkone 
I do understand what you are suggesting but if you think about it, it is not very useful.

The status.client page generated by client_params.sh displays the **_current_** status of a client, not just the status at the time of logging in.
It has logout and refresh buttons along with an advanced option checkbox.

Any data sent to FAS during the login sequence can only contain data relevant to a newly logged in client and FAS already gets this in the query string or can calculate it.

![status-page](https://user-images.githubusercontent.com/13632068/160272278-3b90df2b-1656-4d19-9db7-01af263cd823.jpg)

 * IP address - sent in the query string
 * MAC address - sent in the query string
 * Session start - The time FAS requested authentication
 * Session end - Session start + pre configured `sessiontimeout` or or the override value determined by FAS on verification
 
**All other values are meaningless** for a newly authenticating client.
Without some form of inbound NAT traversal, FAS is unable to provide Logout or Refresh functionality.

**At FAS level 3 (https), NAT traversal is provided** by the openNDS authmon daemon.
If and when CPI login (RFC 8910/8908) becomes more widely used by clients, a level 3 FAS client status page will be added as suggested in the standards.

I hope this is helpful ;-)

**Comment by dorkone** [comment]
I have my own client/server that handles auth/deauth running on the FAS. The router running OpenNDS connects to the server on launch, dealing with NAT traversal.

Since AAA is done on the FAS server (we need it shared among all OpenNDS instances - so we track it externally), the only really meaningful data is the gateway and local ip / mac details - which are also provided by the FAS string.

Like I said, I've already got a script that polls `ndsctl json $ip` and turns that into a query string, and a `statuspath` script that returns an HTML page with a generated FAS query string from that data.

This would make it easier for anyone else doing similar, and save me from an ndsctl call

**Comment by bluewavenet** [comment]
@dorkone 
The thread seems to have morphed from "Add expires field" to "Display client status page using FAS", but nevertheless is interesting ;-)

Currently a very high proportion of client devices do not support CPI, but only the original CPD. 
Many implementations of CPD close the restricted CPD browser window as soon as an Internet connection is detected so the status.client page is only briefly displayed, if at all, on those clients, with no mechanism to inform the client user of the url to reopen the status page.

For clarity:
**CPD (Captive Portal Detection)** is driven by the client. The client has to probe for a valid Internet connection which results in a redirection by the Captive portal.
Whereas **CPI (Captive Portal Identification RFC8910/RFC8908)** is driven by the captive portal. When the client connects to the network, the captive portal informs the client, via DHCP, that it requires authentication to access the Internet and gives the client the url of the web site to go to log in.
Initially the client will automatically go to this url, but will also display (by for example a top of screen notification) a clickable link.

As you can see from this, the Client Status page is a fundamental component of the rfc 8910 and rfc 8908 CPI support on openNDS.

Further planned development of CPI support includes an https status page served by FAS as part of fas_secure_enabled=3 operation. Much of the supporting code already exists in openNDS and it is a relatively small amount of work that is required to fully implement.

> save me from an ndsctl call

Every time a client accesses/refreshes the status page, an ndsctl call is required, so you will only save one call, so not worth the effort.

The planned CPI update in openNDS will use the existing nat traversal mechanism to make a remote ndsctl call "on demand", thus providing a very efficient mechanism for serving an https client status page.
