### ISSUE TITLE
Client is removed from the client list after ndsctl deauth

### ISSUE THREAD

**Issue by ClydeAmazing** [openNDS/openNDS#338]
Hello openNDS Team,

I am migrating my FAS to work with the latest version of openNDS (9.7.0).
My FAS is doing ndsctl json and ndsctl deauth commands periodically as a background process to 'kick' users out of the network after a certain amount of time. However, I noticed that after the client is 'deauthed', it is automatically removed from the client list returned by ndsctl json instead of setting the status of the client to 'Preauthenticated' which is the old behavior of opennds.

Is this the desired/new behavior now? or is it a bug?

BTW I am running openNDS 9.7.0 on Armbian 22.02.1 Bullseye on Orange Pi One board.

Thanks

**Comment by bluewavenet** [comment]
@ClydeAmazing 

> after the client is 'deauthed', it is automatically removed from the client list 

This is intended. It was introduced in v9.1.0. It facilitates third party inter portal roaming applications and is also required as part of the  RFC8910/8908 CPI login support.
From the changelog:
`Add - support for Preemptive Authentication for connected client devices. [bluewavenet]`

> My FAS is doing ndsctl json and ndsctl deauth commands periodically as a background process to 'kick' users out of the network after a certain amount of time.

Why don't you set the sessiontimeout either globally or for individual clients when authenticating?

**Comment by ClydeAmazing** [comment]
@bluewavenet Thanks for your very prompt response. This project really has evolved a lot over the years.
> This is intended. It was introduced in v9.1.0. It facilitates third party inter portal roaming applications and is also required as part of the RFC8910/8908 CPI login support.

Does this mean that if the client is deauthed and wants to be re authenticated again immediately, the client has to disconnect and reconnect to the network to be 'detected' again by openNDS?

Also, does this auto-removal from the client list applies only to ndsctl deauth action or it applies to other deauthentication mechanisms as well (sessiontimeout and clients reached the rate quota)?

> Why don't you set the sessiontimeout either globally or for individual clients when authenticating?

This is probably an option, however, my project works like a wifi subscription service where clients pay to have wifi internet for days or weeks. They also have the ability to pause and resume their wifi subscription. The subscription duration information is saved on an sqlite db to survive temporary powerloss and reboot. If the client is connected to the network, it is automatically authenticated by a background process and will be deauthenticated immediately by the same background process if the subscription ends. 

I assume that if sessiontimeout is set in openNDS, the information only persists within the duration of its operation.

**Comment by bluewavenet** [comment]
@ClydeAmazing 

> Does this mean that if the client is deauthed and wants to be re authenticated again immediately, the client has to disconnect and reconnect to the network to be 'detected' again by openNDS?

Yes. They could also browse to `http://status.client` to get the RFC 8910 login screen.

You can customise this screen.
See: https://opennds.readthedocs.io/en/stable/clientstatus.html#the-client-status-error511-page

As people get new devices that support RFC 8910/8908 CPI, they will be given a "wifi login button on their screen somewhere which will take them to `http://status.client`

You might also find pre-emptive authentication useful. This allows `ndsctl auth` to work by ip or mac address without the client being in the preauthenticated state as long as they have been allocated an ip address by the gateway dhcp.
See:https://opennds.readthedocs.io/en/stable/config.html#allow-preemptive-authentication

> does this auto-removal from the client list applies only to ndsctl deauth action or it applies to other deauthentication mechanisms as well (sessiontimeout and clients reached the rate quota)?

Any type of deauthentication will remove the client from the client list entirely.

**Note on rate quotas:**
If a client reaches their rate quota they are not deauthenticated, **_they are rate limited._** (Deauth at rate quota was deprecated numerous versions ago.

**Comment by ClydeAmazing** [comment]
@bluewavenet Thanks for this very detailed response. I'll look more into the options that you suggested.
