### ISSUE TITLE
Add new field to preauth form not work

### ISSUE THREAD

**Issue by matsumotoa285** [openNDS/openNDS#34]
I add 2 new field is "phone" and "address" to form like:
`
Define a login form
login_form="
	<form action=\"/opennds_preauth/\" method=\"get\">
	<input type=\"hidden\" name=\"clientip\" value=\"$clientip\">
	<input type=\"hidden\" name=\"gatewayname\" value=\"$gatewaynamehtml\">
	<input type=\"hidden\" name=\"hid\" value=\"$hid\">
	<input type=\"hidden\" name=\"gatewayaddress\" value=\"$gatewayaddress\">
	<input type=\"hidden\" name=\"redir\" value=\"$requested\">
	<input type=\"text\" name=\"username\" value=\"$usernamehtml\" autocomplete=\"on\" ><br>Name<br><br>
	<input type=\"text\" name=\"phone\" value=\"$phone\" autocomplete=\"on\" ><br>Phone<br><br>
	<input type=\"email\" name=\"emailaddr\" value=\"$emailaddr\" autocomplete=\"on\" ><br>Email<br><br>
	<input type=\"text\" name=\"address\" value=\"$address\" autocomplete=\"on\" ><br>Address<br><br>
	<input type=\"submit\" value=\"Continue\" >
	</form><hr>
"
`
And add var to this line:
`if [ ! -z "$status_present" ]; then
  queryvarlist="clientip gatewayname gatewayaddress status"
elif [ -z "$hid_present" ]; then
  hid="0"
  gatewayaddress="0"
  queryvarlist="clientip gatewayname redir username phone emailaddr address"
else
  queryvarlist="clientip gatewayname hid gatewayaddress redir username phone emailaddr address"
fi`

And

 gatewayname=$(printf "${gatewayname//%/\\x}")
htmlentityencode "$gatewayname"
gatewaynamehtml=$entityencoded
username=$(printf "${username//%/\\x}")
htmlentityencode "$username"
usernamehtml=$entityencoded
emailaddr=$(printf "${emailaddr//%/\\x}")

phone=$(printf "${phone//%/\\x}")
address=$(printf "${address//%/\\x}")

But when I send data with curl to php website with curl:
`  code=$(curl --location --request POST '192.168.1.221/ci/api/demo/add' --form "name=$username" --form "email=$emailaddr" --form "phone=$phone" --form "address=$address")`
Data send to web is not right. 
`array(4) { ["name"]=> string(3) "Ghm" ["email"]=> string(14) "hshsh@ggan.com" ["phone"]=> string(7) "9383838" ["address"]=> string(105) "0, redir=http://connect.rom.miui.com/generate_204, username=Ghm, phone=9383838, emailaddr=hshsh@ggan.com," }
`
The field "address" is not work, why did it get redir to address?
Can you give some hint to add new field and get it easyer than?
Thank you!

**Comment by bluewavenet** [comment]
@matsumotoa285
I think your code is correct but you have found a bug!

I have fixed the problem where the query string was being parsed incorrectly.

It will be included in the next release, but for now I have a fixed version of login.sh including the extra phone and address fields. The client is forced to complete all fields and the new fields are included in the log.

Github won't let me attach it for some reason - just a moment while I figure it out...

:-D

**Comment by bluewavenet** [comment]
@matsumotoa285
I think your code is correct but you have found a bug!

I have fixed the problem where the query string was being parsed incorrectly.

It will be included in the next release, but for now I have a fixed version of login.sh including the extra phone and address fields. The client is forced to complete all fields and the new fields are included in the log.

Github won't let me attach it for some reason - just a moment while I figure it out...

:-D

**Comment by bluewavenet** [comment]
@matsumotoa285
Here is the fixed file:
https://raw.githubusercontent.com/openNDS/openNDS/master/testing/preauth-login-script/login.sh

**Comment by matsumotoa285** [comment]
> @matsumotoa285
> Here is the fixed file:
> https://raw.githubusercontent.com/openNDS/openNDS/master/testing/preauth-login-script/login.sh
Thank you very much. It worked.
I have some question for idea for deploy openNDS, can you give me contact? :smile:

**Comment by bluewavenet** [comment]
@matsumotoa285 
Feel free to ask any questions here.

**Comment by nongquanghuong** [comment]
> @matsumotoa285
> Feel free to ask any questions here.

I have a device run openwrt and I want to custom to run opennds for custom. I want create code (as a voucher), and user must be correct some info and code to access internet. I using Preauth with login.sh (https://ideone.com/RI8LrC). But some field like address and code not work, could you tell me how to add new field without error like it.
And I have one more question, my device have 8mb flash, so It have not enough to install php-cli and php-mod-openssl, have way to run FAS in my device? Because can not use FAS so I must be use Preauth and custom login.sh, but I have some problem.

**Comment by bluewavenet** [comment]
@nongquanghuong 
 1. From your link it appears you want to ask the client for **username**, **phone**, **emailaddr**, **addr** and **code**.
However, from the link you posted I see you are using curl to do a remote post request and trying to insert a meta redirect in the middle of the body section of your splash page (big html error)..... I'm not following what you are trying to do with these.

 2. The "custom" string is is a means of sending data to a BinAuth script. If you are only looking to add new login fields and then process within your Preauth script, then there is no need to use the "custom" string.

 3. PreAuth is a special case of FAS that uses the openNDS built in web server. A PreAuth script can be written in any language that is supported on the openNDS device.

4. 8MB of flash will be very restrictive. A device with such a small flash will also most likely have very limited RAM so I would not recommend using such a device for a new project as it is very much "end of life". However if you have one and want to try, using PreAuth is probably the best way forward.

**Comment by bluewavenet** [comment]
@nongquanghuong 
I have created a multi field login preauth script based in your link to show by example how to add fields.
You can download multifieldlogin.sh and splash.css from:
https://github.com/openNDS/openNDS/tree/master/testing

Delete /usr/lib/opennds/login.sh and replace with multifieldlogin.sh renamed to login.sh (flagging as executable)
Overwrite /etc/opennds/htdocs/splash.css with the version you just downloaded.

**Comment by nongquanghuong** [comment]
> @nongquanghuong
> I have created a multi field login preauth script based in your link to show by example how to add fields.
> You can download multifieldlogin.sh and splash.css from:
> https://github.com/openNDS/openNDS/tree/master/testing
> 
> Delete /usr/lib/opennds/login.sh and replace with multifieldlogin.sh renamed to login.sh (flagging as executable)
> Overwrite /etc/opennds/htdocs/splash.css with the version you just downloaded.

Thank you very much!
