### ISSUE TITLE
I cant to connect external server FAS

### ISSUE THREAD

**Issue by henok400** [openNDS/openNDS#340]
I tried to connect FAS my auth server and listen parameter but openNDS not response only blocked internet  
I set the following configuration
```
option enabled 1
option fwhook_enabled '1'
option login_option_enabled '0'
option fasremotefqdn 'wifi.cloudwifizone.com'
```
But nothing to authenticate user/pass mode or voucher mode

**Comment by bluewavenet** [comment]
@henok400 
From your forum post at:
https://forum.openwrt.org/t/wifidog-v1-3-0-6-new-release-more-than-1-session-cant-work/118412/7
I assume you are using OpenWrt 21.02.2 and openNDS 9.7.0

It looks like you do not have a complete configuration yet, so I will ask a few questions.
You can also see the documentation at:
https://opennds.readthedocs.io/en/stable/fas.html#forwarding-authentication-service-fas

I understand you will want to make use of your existing authentication service, but first it will be sensible to check you have everything installed correctly.

Firstly, if you remove the `option fasremotefqdn` line and set `option login_option_enabled '1', do you get the default "Click to continue" page sequence?

**Comment by henok400** [comment]
I checked default after long time portal page coming Accept Term of Service button then after click web page not available, no any internet access. url opendns_preauth/?..... I tried many times rebooting router the same result and very delay to start service.
i use openwrt 21.02.2 and openNDS last

**Comment by bluewavenet** [comment]
@henok400 
Unfortunately it is difficult to understand as your translation into English is not very good. Try using Google Translate, it might make things a little easier.

**Could you please state what router model you are using.**

To make sure you do not have anything wrong with your config file, in a terminal session, do the following:
`cp /etc/opennds/config.uci /etc/config/opennds`

followed by:
`service opennds restart`

After it has restarted, show the output of:
`ndsctl status`

Now connect to the wifi with a mobile device.
You should now get the "Welcome" page of the click to continue sequence, asking you to accept the terms of service. Accept the terms of service.
You should now be shown the "Thankyou" page. Click Continue.
The next page is the landing page, stating "You are now logged in.....". Click Continue.
The final page is the Client Status page ( `http://status.client` )

If there is a very long delay before seeing the first page, this means your router is slow and probably short of resources.
(As I requested earlier, please state what model router you are using).
If the router is resource limited, for now do not worry, as this mode uses a built in local FAS server. You eventually want to use your existing remote authentication server and we will work towards that next, but first it is important to do this initial testing of your system.

**Comment by henok400** [comment]
I trying all steps After welcome page It said Unable to connect server at 192.168.1.1:2050.
`http://192.168.1.1:2050/opennds_preauth/?fas=aGlkPWYyM............`
I use Gl.inet 6416 router model best to test any openwrt scripts. 
ndsctl status
```
openNDS Status
====
Version: 9.7.0
Uptime: 4m 33s
Gateway Name: [ openNDS S/N:e4956e40cd2f  ]
Debug Level: [ 1 ]
Gateway FQDN: [ status.client ]
Managed interface: br-lan
Upstream gateway(s) [ online:192.168.199.1,wlan0  ]
MHD Server [ version 0.9.71 ] listening on: http://192.168.1.1:2050
Maximum Html Page size is [ 10240 ] Bytes
Preemptive Authentication is Disabled
Binauth: Disabled
Preauth Script: /usr/lib/opennds/libopennds.sh
FAS: Secure Level 1, URL: http://192.168.1.1:2050/opennds_preauth/
Client Check Interval: 15s
Rate Check Window: 2 check intervals (30s)
Preauthenticated Client Idle Timeout: 30m
Authenticated Client Idle Timeout: 120m
Download rate limit threshold (default per client): no limit
Upload rate limit threshold (default per client): no limit
Download quota (default per client): no limit
Upload quota (default per client): no limit
Total download: 251 kByte; average: 7.53 kbit/s
Total upload: 220 kByte; average: 6.61 kbit/s
====
Client authentications since start: 0
Current clients: 1

Client 0
  Client Type: cpd_can
  IP: 192.168.1.165 MAC: 1c:bf:ce:22:3e:56
  Last Activity: Mon Apr 18 12:05:30 2022 (4m 4s ago)
  Session Start: -
  Session End:   -
  Token: a2c7b9ee
  State: Preauthenticated
  Download Rate Limit Threshold: not set
  Upload Rate Limit Threshold: not set
  Download quota: not set
  Upload quota: not set
  Download this session: 0 kB; Session average: 0.00 kb/s
  Upload this session: 0 kB; Session average: 0.00 kb/s

====
Trusted MAC addresses: none
Walled Garden FQDNs: none
Walled Garden Ports: none
========
```

**Comment by henok400** [comment]
Now captive portal successfully connected internet and getting Thank you page.
How to authenticate external server?

**Comment by bluewavenet** [comment]
> Now captive portal successfully connected internet and getting Thank you page.

Did you get past the Thankyou page to the "You are logged in" page and then on to the Client Status page ( http://status.client )?

>  How to authenticate external server?

Yes, the next step. But first some questions.
It does have valid TLS (for https), so your FAS can be https.

 * Is the server dedicated to that FQDN 
or
 * Is it shared with other web sites
or
 * Is it "cloud"  CDN?
 
Your answer will determine which step we do next.
The next step is to copy an example php script to your server and set some simple options in the openNDS config.
After we get that next step working we have to interface to your existing authentication application.

**Comment by henok400** [comment]
Yes http://status.client/ show status. 
I use share hosting with cloudflare CDN to check this openNDS http prefer now then i will test https

**Comment by bluewavenet** [comment]
@henok400 
I checked the Gl.inet 6416. It's SoC is quite slow (400MHz) and it has 16MB Flash and 64MB RAM, as I am sure you know.
The flash size is fine but the RAM is quite low for OpenWrt 21.02, so we will have to be careful - the https mode might be too much. But as you say we can test that later.

**_For CDN there are some additional dependencies_**. We will have to set up OpenWrt for an autonomous walled garden and configure openNDS to use it.
(https://opennds.readthedocs.io/en/stable/walledgarden.html#walled-garden)

**Do the following in a terminal session:**
```
opkg update
opkg install ipset
opkg remove dnsmasq
opkg install dnsmasq-full

```
**Now you must copy the example php FAS to your server** (this will be customised later to talk to the existing authentication system you were using with WifiDog).
The example file can be found at `/etc/opennds/fas-hid.php`.
Put it on your CDN server in a suitable folder such that it is accessible on the web server.
eg http://wifi.cloudwifizone.com/fas/fas-hid.php

Finally, we have to configure openNDS to use the walled garden and remote FAS (See note below).

**Do the following in a terminal session:**
```
uci add_list opennds.@opennds[0].walledgarden_fqdn_list='wifi.cloudwifizone.com'
uci add opennds.@opennds[0].fasport='80'
uci add opennds.@opennds[0].faspath='/fas/fas-hid.php'
uci add opennds.@opennds[0].fasremotefqdn='wifi.cloudwifizone.com'
uci add opennds.@opennds[0].fasremoteip='174.136.29.209'
uci add opennds.@opennds[0].fas_secure_enabled='1'
uci add opennds.@opennds[0].faskey='1234567890'
uci commit opennds
```

**_Note:_**
 * fasremoteip - must be set to one of the ip addresses used by the CDN for wifi.cloudwifizone.com (I found this one using ping)
 * faskey - we will change this to something more secure after initial testing
 * faspath - this is the path to the fas-hid.php file you copied earlier (relative to the web root, not the server's file system root)

**_Now we are ready to test, so reboot_** the device and show again the output of `ndsctl status`

**Comment by henok400** [comment]
There is many problems to use opennds that my router Gl.inet sometime work sometimes not work. I think resource issue. What kind of router recommended me. I have Tplink cpe210 and Comfast E110N, and many Glinet routers. Other configuration is complicated is there anyway quick setup and start captive portal like wifidog?

**Comment by bluewavenet** [comment]
@henok400 

> What kind of router recommended me

A Gl-iNet MT300N-V2 is perfect if you have one.

> is there anyway quick setup and start captive portal

Just install openNDS and it should just work with the simple Accept Terms/Click to continue page sequence.

Change to username/email login form by doing:

```
uci set opennds.@opennds[0].login_option_enabled='2'
uci commit opennds
service opennds restart
```

Using an external FAS server is a little more complicated, but still only 8 options to set, depending on the details of the remote FAS.

Re-utilising your existing remote authentication system that you used with WifiDog will involve some coding on the remote server, but should be fairly straightforward. You just have to emulate what WifiDog did.

**Comment by henok400** [comment]
For my clients around the world, it is not easy to set up but also need easy to use. I am currently trying to open 21.02.2 Gl.inet 6416 and most clients have a small resource model. And use time and expiration date for captive portal voucher system.

**Comment by bluewavenet** [comment]
It is likely to be possible to get it to work in your 6416 but no guarantee. It is a very old and slow device that was discontinued many years ago.
A new gl-mt300n-v2 costs only ~30$. Maybe now is the time to upgrade.

**Comment by henok400** [comment]
Gl.inet 6416 and GL-mt300n-v2 openwrt 19.xx I tried opennds everything working perfect quick captive portal. The problem is openwrt 21.02.x that cant work opennds like wifidog. Anyway i will check the system.

**Comment by bluewavenet** [comment]
> The problem is openwrt 21.02.x that cant work opennds like wifidog.

I don't understand what you mean....

**Comment by bluewavenet** [comment]
> Opennds not working openwrt 21.02.x ...

openNDS v9.7.0 has been extensively tested on OpenWrt 21.02.x with no problems.

> It work like wifidog openwrt19.xx

I am happy to help, but I have to ask if you can explain what you mean by this, please.

**Comment by henok400** [comment]
How to change login page/ status page view from external server ?

**Comment by bluewavenet** [comment]
Does this mean you now have it working with an external server?
If so, the fas-hid.php file that you copied to your external server, would be edited to change the login page.
For the status page you would edit the local file `/usr/lib/opennds/client_params.sh`

There are simple html sections to edit in each file.

**Comment by henok400** [comment]
`client_params.sh` Can i get sample own parameter manage using opennds?

**Comment by bluewavenet** [comment]
The http://status.client page is generated by `client_params.sh`, and you can customise it in any way you like.
It looks like:

![Screenshot from 2022-04-22 08-23-31](https://user-images.githubusercontent.com/13632068/164627100-8b2f4447-4454-4564-a030-4b84075bd046.png)

**Comment by henok400** [comment]
I have checking fas-hid.php generate token and successfully connect.
Now the problems are External server need
-Router online status
-each device connected stage, usage, every minutes status
And i want from external server to make disconnect each devices?

**Comment by bluewavenet** [comment]
@henok400 
Sorry, it would be much better if you used something like Google Translate to English as it is not easy to understand your questions.

> I have checking fas-hid.php generate token and successfully connect.

By this do you mean you have fas-hid working correctly on a remote server? The fas-hid example does not use the client token so I do not know what you mean by "generate token".



> -Router online status

There is no built in mechanism for a remote FAS to check the online status of an openNDS instance. It is possible to use the openNDS API to poll the remote FAS, but this would be your responsibility.

> -each device connected stage, usage, every minutes status

Do you mean you want the remote FAS to have a minute by minute status update of all clients?
Again, you could use the API to set this up. It is only of use for monitoring ongoing statistics though, as all aspects of client quotas are handled autonomously by openNDS.

> And i want from external server to make disconnect each devices?

Do you mean you want the remote FAS to be able to deauthenticate clients based on some criterion?
Client deauthentication is handled autonomously by openNDS based on what FAS tells it to do at authentication time, so this would not be very useful. Yet again, you could use the API to start your own "punitive deauth" polling daemon to check for a list of "bad" clients to immediately deauthenticate.

**Comment by henok400** [comment]
conclusion: In my understanding Opennds can not support external server centralize manage routers and each wifi users management. Only work under router. To use external server not build or not support. I'm wifidog user that fully managed 1000's routers from external server but currently openwrt v22.xx firmware upgrading  that wifidog not working anymore for-that i'm coming opennds but it is very difficult and not support external remote server. That very difficult to build own router management system. I decide stay old version of openwrt v19.xx

**Comment by bluewavenet** [comment]
@henok400 

> conclusion: In my understanding Opennds can not support external server centralize manage routers and each wifi users management. Only work under router.

openNDS FAS is designed specifically with an API to enable an Internet hosted, centrally managed captive portal network consisting of many instances of openNDS on multiple routers, with the users local to each venue being managed centrally at the FAS server.

Working and fully tested example FAS scripts are provided and, for someone with basic software skills, these examples can be customised for almost all possible requirements. Help is readily available here by opening an issue and asking for help.

My conclusions here are:
 * You have very little understanding, if any, of openNDS and seem unable to ask basic questions, possibly due to English not being your native language. You have instead chosen to ignore any attempts to help.
 * You appear to be commercially using the now defunct Wifidog software on an outdated version of OpenWrt on old resource limited hardware, but do not have the technical knowledge to update this in any way.
 * You appear to be wanting a free but bespoke solution where someone has done the development work for you for your specific application.
 *  _Your business would be better off (or even saved) if you contracted someone with the necessary skills, a relatively small investment given your supposed user base of "1000's [of] routers"._
