### ISSUE TITLE
Mechanism to disconnect client from WiFI (kick STA)

### ISSUE THREAD

**Issue by minhng99** [openNDS/openNDS#345]
Hello again,

Recently I'm observing some strange stuffs with iOS devices that they don't seems to realise that they're no longer having access to the Internet, thus no CPD are shown.

How about an optional mechanism that will forcefully disconnect WiFi client once session expired? I think OpenWrt can do this with ubus hook or something like that, I've never tried it with CLI but only LUCI. This mechanism will make sure that the user realised that the WiFi has been disconnected for some reason... and hopefully the CPD will kick in once they've connected again.

Thanks!

**Comment by minhng99** [comment]
> What version of openNDS are you using now?
9.7.0 on OpenWrt 22

Yeah, I'll find a way to kick STA from CLI...

**Comment by minhng99** [comment]
Okay, I've found the code and it does appears to work:
`ubus call hostapd.wlan1 del_client '{"addr":"8E:BB:42:56:93:F5", "reason":5, "deauth":true, "ban_time":1}'`

The reason you can pick in this table (search for `WLAN_REASON`), I'm not sure what would be the best one in this case... since I noticed that some client does not want to reconnect and will switch to another SSID if you kicked them for some specific reason.
https://w1.fi/wpa_supplicant/devel/ieee802__11__defs_8h.html

The `ban_time` is in milliseconds

**Comment by bluewavenet** [comment]
That looks promising, but ubus is OpenWrt specific and we have to cater for generic Linux distros.

What about:
`iw dev <devname> station del <MAC address> [subtype <subtype>] [reason-code <code>]`

I've not had time to try it....

**Comment by minhng99** [comment]
> What about: `iw dev <devname> station del <MAC address> [subtype <subtype>] [reason-code <code>]`

This one doesn't really work and I don't know why...
I executed `iw dev wlan1 station del 8E:BB:42:56:93:F5` and the client still showing that it's connected but it can no longer reach the AP... it's like some kind of "shadow banning" but doesn't tell the client to disconnect

**Comment by dorkone** [comment]
I've had success with
```
hostapd_cli disassociate -i wlan0 01:23:45:67:89:AB
hostapd_cli disassociate -i wlan1 01:23:45:67:89:AB
```
It has an external dependency, but it seems to be fairly available.

**Comment by minhng99** [comment]
I think we could just implement this for OpenWrt first. Maybe an alternative method for other OSes with additional dependency?

**Comment by bluewavenet** [comment]
@minhng99 

> I think we could just implement this for OpenWrt first.

We could have a new `option kick_deauthed_sta '1'`.
On startup, openNDS could check if the mechanism is present and log an error if it is not.

When a client is deauthed for any reason, it gets kicked.

The "mechanism" could be an OS or OS-package dependent script, thereby modularising the function from the viewpoint of openNDS.

However this is only relevant for built in access point radios so would be useful only for small single AP venues.
Have you looked at the usteer package? Maybe we could make use of it in some way for multi AP venues - or at least the techniques it uses.

CPI (RFC8910/8908) capable clients are starting to be seen "in the wild". If this gains momentum, the problem might be solved for us!
You can check in `ndsctl status` or `ndsctl json` for client type:

1. cpi_url -> RFC8910
2. cpi_api -> RFC8908
3. cpd_can -> Defacto_CPD

**Comment by minhng99** [comment]
I have tried running usteer in the production environment and the results are very unstable, the clients keep getting kicked back and forth between APs where there are multiple AP with the same SSID near each other, some clients even blacklisted the SSID because it keeps getting kicked and doesn't want to connect again, my guess is that it's still in the testing phase so maybe there are issues need to be fixed.

I wouldn't recommend it for now...

**Comment by bluewavenet** [comment]
@minhng99 
We need some mechanism where openNDS can tell a remote AP to kick a particular STA...

Mmmm - we need a  package that provides AP to AP comms..... I don't think there is one. Could be done though.

**Comment by bluewavenet** [comment]
@minhng99 
I've done some testing. The ubus call works, but the client immediately jumps to another SSID every time. If I tell the client to forget all SSIDs it can see except the captive portal SSID, then it does not jump away and reconnects, but it does not do a CPD test, at least not immediately. It seems to wait a 10 minutes before doing the CPD test.
If I manually disconnect and reconnect, it CPD tests immediately.

I think this is very CPD implementation dependent and as such cannot be relied upon.

Using a new Android 12 device though, once the client is deauthed by openNDS, the top bar notification changes to a login symbol superimposed over the wifi symbol within seconds. Clicking it gives the openNDS page511 rfc 89010 login.

I don't know if it is worth pursuing a kick sta mechanism.... It will be unreliable and it looks like new devices do not need it.

**Comment by minhng99** [comment]
>It will be unreliable and it looks like new devices do not need it.
Yeah, I agreed.

>  It seems to wait a 10 minutes before doing the CPD test.
You test this on an iPhone, right? iPhone always have kinda unpredicable behavior with CPD

**Comment by bluewavenet** [comment]
@minhng99 

> You test this on an iPhone, right? 

Unfortunately I do not have access to an iPhone at the moment, so no, yesterday tested with various Android devices.

However, looking at the logs of some busy venues, I can see what looks like the possible beginning of what I would expect to be an exponential increase in the number of cpi_url active devices, albeit still at very small numbers, so I guess it won't take that long for the situation to  for the better. (I would actually expect to see an S curve as rfc8910 clients are rolled out).

**note**: _RFC8910/8908 CPI has been supported by openNDS since v9.0.0. Recently it was seen that some clients were polling the CPI url at a rapid rate - a bad client side implementation. As openNDS was generating the 511 response page slower than the client was requesting it, the result was openNDS's built in web server (MHD) was becoming unresponsive and in cases where free ram was at a premium, MHD was segfaulting. **OpenNDS version9.8.0 prevents such bad implementations of CPI from causing this problem** by generating the 511 page orders of magnitude faster._
