### ISSUE TITLE
opennds crash when repeatedly authenticate/deauthenticate

### ISSUE THREAD

**Issue by minhng99** [openNDS/openNDS#348]
Hi, I'm trying to do some weird stuff with `ndsctl` and just happened to make it crash by repeatedly authenticate/deauthenticate it...

![image](https://user-images.githubusercontent.com/14113155/166876430-99deddc4-f9a7-4223-af5f-f85c2878769f.png)

I'm not sure if this actually affecting anyone IRL... but I was trying to deauthenticate a client then re-authenticate it with a different session timeout which isn't supported by `ndsctl` and wanted to make sure it's stable when doing that.

**Comment by bluewavenet** [comment]
@minhng99 

> weird stuff with ndsctl 

I need to write a guide to doing `weird stuff with ndsctl` :-D
Most likely the ndsctl thread is crashing as the Linux socket queue has overflowed as you are sending commands too fast.
"deauth" and "auth" can take a second or too to complete, depending on the hardware.
If this is the problem here, the solution to this is already used by libopennds in the form of function `do_ndsctl ()`.
To use it, make a script to do the deauth/auth sonething like:
```
#!/bin/sh
# Function to send commands to openNDS:
do_ndsctl () {
	local timeout=4

	for tic in $(seq $timeout); do
		ndsstatus="ready"
		ndsctlout=$(eval ndsctl "$ndsctlcmd")

		for keyword in $ndsctlout; do

			if [ $keyword = "locked" ]; then
				ndsstatus="busy"
				sleep 1
				break
			fi

			if [ $keyword = "Failed" ]; then
				ndsstatus="failed"
				break
			fi

			if [ $keyword = "authenticated." ]; then
				ndsstatus="authenticated"
				break
			fi

		done

		keyword=""

		if [ $tic = $timeout ] ; then
			busy_page
		fi

		if [ "$ndsstatus" = "authenticated" ]; then
			break
		fi

		if [ "$ndsstatus" = "failed" ]; then
			break
		fi

		if [ "$ndsstatus" = "ready" ]; then
			break
		fi
	done
}

ndsctlcmd="deauth <client_mac>"
do_ndsctl
ndsctlcmd="auth <client_mac>"
do_ndsctl

```
If you are really going to be pushing it hard and start sending hundreds of ndsctl commands per second you might have to do some extra error checking after the function call, but normally this is not necessary.

> I was trying to deauthenticate a client then re-authenticate it with a different session timeout which isn't supported by ndsctl

Do you mean just update the session end time? If so then you are correct, this is not supported - But:
From the output of `ndsctl -h`
```
auth mac|ip|token sessiontimeout(minutes) uploadrate(kb/s) downloadrate(kb/s) uploadquota(kB) downloadquota(kB) customstring
	Authenticate client with specified mac, ip or token

```

**Comment by minhng99** [comment]
Yeah but I think it shouldn't be crashing like this... at worst it would returning error but shouldn't crash.


> Do you mean just update the session end time? If so then you are correct, this is not supported - But:


Yes, I have some feature planned which needs increasing a currently authenticated client's `session timeout`

**Comment by bluewavenet** [comment]
> Yeah but I think it shouldn't be crashing like this

I agree. A lot of time and effort was put into the problem and the conclusion was there is most likely some sort of issue with the pthread and socket handling combination in Linux as no-one could see a problem with openNDS code (not to say there isn't something wrong somewhere).

However, the combination of socket file locking and do_ndsctl seems to mitigate the issue.

Did you try it and did it work?

**Comment by minhng99** [comment]
Yup, that does seem to work just fine

![image](https://user-images.githubusercontent.com/14113155/167233986-b1c57849-0c15-4753-b6d8-bbaa1774c557.png)

same with simply letting it sleep 0.5s between calls though... but the busy check does works better in case when there's potentially some other thread is calling `ndsctl` at the same time

**Comment by bluewavenet** [comment]
The length of sleep between calls depends on cpu load, hardware resources, other concurrent calls etc etc.
On your test system 0.5s may well have been enough, but it cannot be guaranteed this would always be the case.
