### ISSUE TITLE
update authenticated client params using ndsctl without deauthenticating first

### ISSUE THREAD

**Issue by ekowtaylor** [openNDS/openNDS#355]
Is there a way to update the parameters e.g. download_rate, quota etc. of an authenticated client via ndsctl without deauthenticating first? It shouldn't be a problem but I'd love for the token to remain same. Currently, it changes each time you deauthenticate and then authenticate again in an attempt to update the clients auth parameters.

**Comment by bluewavenet** [comment]
@ekowtaylor 

> Is there a way to update the parameters e.g. download_rate, quota etc. of an authenticated client via ndsctl without deauthenticating first?

Not at this time. It would be technically possible but a rapid deauth/auth by ip address is much cleaner and in cases where this has been done, the client does not notice. Yes, the token changes, but the token is not used directly anyway.

PS. sorry for the long delay answering ;-)
