### ISSUE TITLE
How to configure fas option

### ISSUE THREAD

**Issue by xreyc** [openNDS/openNDS#359]
Hi, how to configure FAS for external authentication.
I am running a nodejs application as authentication server running on my local server.
My nodejs application runs at 10.0.0.22 at port 80.

I want to authenticate my user via voucher on my nodejs application before granting internet access.

Is my configuration correct?

config opennds
	option enabled 1
	option fwhook_enabled '1'
	option maxclients '250'
	list users_to_router 'allow tcp port 53'
	list users_to_router 'allow udp port 53'
	list users_to_router 'allow udp port 67'
	list users_to_router 'allow tcp port 22'
	list users_to_router 'allow tcp port 80'
	list users_to_router 'allow tcp port 443'
	fasport 80
	faspath /portal
	fas_secure_enabled 1
	faskey 1234567890
	fasremoteip 10.0.0.22
	fasremotefqdn status.client

**Comment by bluewavenet** [comment]
@xreyc-developers 
If you haven't already, make sure you have read the FAS section of the documentation:
https://opennds.readthedocs.io/en/stable/fas.html#forwarding-authentication-service-fas

In your config, remove the fasremotefqdn reference.
**`status.client` will resolve to the opennds router and not your nodejs server (at 10.0.0.22)**
Presumably the opennds router is at 10.0.0.1  

I would strongly recommend that you copy the fas-hid.php example file (stored for convenience in /etc/opennds/ on the opennds router) to your server at 10.0.0.22 in the portal folder.
Now change the config such that you have `faspath /portal/fas-hid.php` and restart opennds with `service opennds restart`

Connect with a mobile device and you should get the fas-hid splash page sequence that will ask for fullname and email address.

Once you have this working - **and granting Internet access** - you can think about modifying fas-hid.php to use your node.js app for client credential validation. This is much simpler than writing your own FAS from scratch.

**Comment by xreyc-developers** [comment]
Thank you for this, I'll check this one.
I'll get back when its done.

**Comment by xreyc-developers** [comment]
I got it working now.
Next step I'll integrate fas-hid.php my nodejs auth server.
Thank you.
