### ISSUE TITLE
I am still able to access some sites even though I haven't accept the terms of service.

### ISSUE THREAD

**Issue by xreyc-developers** [openNDS/openNDS#360]
Captive portal appeared on my browser.
It was able to block many sites but not all.
I tried to open open google, youtube and facebook without accepting the terms of service
but still be able to load it.

I am running Mikrotik Rb750Gr3 with Openwrt 21.03.2.
I installed OpenNDS without changing the default configuration.
My OpenWrt ip address is 10.0.0.1

have I done something wrong?

**Comment by bluewavenet** [comment]
@xreyc-developers 

> I am running Mikrotik Rb750Gr3 with Openwrt 21.03.2.

Presumably opennds v9.7.0?

> have I done something wrong?

Without a doubt I am sure you have ;-)

Show the outputs of:
`uci show opennds`

and

`ndsctl status`

>  It was able to block many sites but not all.

You do not have to block anything, opennds blocks everything upstream apart from any Walled Garden settings.
By default, the only walled garden entry is fasremoteip.

However if your Internet feed is dual stack ipv4 and ipv6, then you must disable ipv6.

**Comment by xreyc-developers** [comment]
Heres the result

### uci show opennds

root@OpenWrt:~# uci show opennds
opennds.@opennds[0]=opennds
opennds.@opennds[0].enabled='1'
opennds.@opennds[0].fwhook_enabled='1'
opennds.@opennds[0].maxclients='250'
opennds.@opennds[0].users_to_router='allow tcp port 53' 'allow udp port 53' 'allow udp port 67' 'allow tcp port 22' 'allow tcp port 80' 'allow tcp port 443'

### ndsctl status

root@OpenWrt:~# ndsctl status
==================
openNDS Status
====
Version: 9.7.0
Uptime: 4m 2s
Gateway Name: [ openNDS S/N:dc2c6ee15a21  ]
Debug Level: [ 1 ]
Gateway FQDN: [ status.client ]
Managed interface: br-lan
All Upstream gateway(s) are offline or not connected [ offline ]
MHD Server [ version 0.9.71 ] listening on: http://192.168.1.1:2050
Maximum Html Page size is [ 10240 ] Bytes
Preemptive Authentication is Disabled
Binauth: Disabled
Preauth Script: /usr/lib/opennds/libopennds.sh
FAS: Secure Level 1, URL: http://192.168.1.1:2050/opennds_preauth/
Client Check Interval: 15s
Rate Check Window: 2 check intervals (30s)
Preauthenticated Client Idle Timeout: 30m
Authenticated Client Idle Timeout: 120m
Download rate limit threshold (default per client): no limit
Upload rate limit threshold (default per client): no limit
Download quota (default per client): no limit
Upload quota (default per client): no limit
Total download: 372 kByte; average: 12.59 kbit/s
Total upload: 232 kByte; average: 7.87 kbit/s
====
Client authentications since start: 0
Current clients: 1

Client 0
  Client Type: cpd_can
  IP: 192.168.1.218 MAC: 00:e0:4c:36:08:36
  Last Activity: Mon Aug 01 14:55:57 2022 (2m 44s ago)
  Session Start: -
  Session End:   -
  Token: 7975ad07
  State: Preauthenticated
  Download Rate Limit Threshold: not set
  Upload Rate Limit Threshold: not set
  Download quota: not set
  Upload quota: not set
  Download this session: 0 kB; Session average: 0.00 kb/s
  Upload this session: 0 kB; Session average: 0.00 kb/s

====
Trusted MAC addresses: none
Walled Garden FQDNs: none
Walled Garden Ports: none
========
root@OpenWrt:~# clear
root@OpenWrt:~# ndsctl status
==================
openNDS Status
====
Version: 9.7.0
Uptime: 4m 14s
Gateway Name: [ openNDS S/N:dc2c6ee15a21  ]
Debug Level: [ 1 ]
Gateway FQDN: [ status.client ]
Managed interface: br-lan
All Upstream gateway(s) are offline or not connected [ offline ]
MHD Server [ version 0.9.71 ] listening on: http://192.168.1.1:2050
Maximum Html Page size is [ 10240 ] Bytes
Preemptive Authentication is Disabled
Binauth: Disabled
Preauth Script: /usr/lib/opennds/libopennds.sh
FAS: Secure Level 1, URL: http://192.168.1.1:2050/opennds_preauth/
Client Check Interval: 15s
Rate Check Window: 2 check intervals (30s)
Preauthenticated Client Idle Timeout: 30m
Authenticated Client Idle Timeout: 120m
Download rate limit threshold (default per client): no limit
Upload rate limit threshold (default per client): no limit
Download quota (default per client): no limit
Upload quota (default per client): no limit
Total download: 375 kByte; average: 12.12 kbit/s
Total upload: 243 kByte; average: 7.86 kbit/s
====
Client authentications since start: 0
Current clients: 1

Client 0
  Client Type: cpd_can
  IP: 192.168.1.218 MAC: 00:e0:4c:36:08:36
  Last Activity: Mon Aug 01 14:55:57 2022 (2m 56s ago)
  Session Start: -
  Session End:   -
  Token: 7975ad07
  State: Preauthenticated
  Download Rate Limit Threshold: not set
  Upload Rate Limit Threshold: not set
  Download quota: not set
  Upload quota: not set
  Download this session: 0 kB; Session average: 0.00 kb/s
  Upload this session: 0 kB; Session average: 0.00 kb/s

====
Trusted MAC addresses: none
Walled Garden FQDNs: none
Walled Garden Ports: none
========

**Comment by xreyc-developers** [comment]
My bad the result on top might be wrong.
I just reflashed OpenWrt to it gets back to defautl 192.168.1.1.

Disabling Ipv6 actually solve my problem.
Thank you
