### ISSUE TITLE
Voucher OpenNDS login not working

### ISSUE THREAD

**Issue by lenovomen** [openNDS/openNDS#366]
Dear developer! I installed the voucher openNDS add-on file as described. The hotspot login window appears, but does not redirect to where I should enter the voucher code. What could be the reason for this? I am using the latest version of OpenWrt.

**Comment by lenovomen** [comment]
![Uploading 5B7CAD15-8785-4F12-B9EB-2DE4E76C4F98.png…]()

**Comment by lenovomen** [comment]
https://forum.openwrt.org/t/simple-hotspot-voucher/133672/15

**Comment by bluewavenet** [comment]
@lenovomen 
Sorry for the delay replying.

> I installed the voucher openNDS add-on file as described.

For the purposes of this issue, so did I. It worked perfectly first time, so there is nothing wrong with the themespec file.

My conclusion is that there must be something wrong with your configuration.

Please provide the following:

1. Router hardware
2. OpenWrt Version
3. Output of `uci show network`
4. Output of `uci show wireless`
5. Output of `uci show opennds`

When showing these outputs, copy and paste from your terminal window into the text box where you are entering your reply, then highlight the pasted text and click the <> symbol at the top of the text box.

The .png you tried to post failed to upload, but if it was a screenshot of the luci ui, it is of very little use for debugging this issue. 

> The hotspot login window appears 

Does this pop up automatically when you connect with a smart device eg a phone?
Or does it appear when you try to access luci?

**Comment by bluewavenet** [comment]
Closing as:
1. Tested and found to be working as expected
2. No response from OP
