### ISSUE TITLE
How do Deauthenticate in FAS

### ISSUE THREAD

**Issue by Nxtframe** [openNDS/openNDS#367]
In Fas-hid.php I have a logout button but how do I send the Deauth message to OpenNDS to deauthenticate with client IP.

**Comment by bluewavenet** [comment]
@Nxtframe 

>  how do I send the Deauth message to OpenNDS

Click the logout button!

Sorry, I think you will have to put your question into context.
Parameters required for openNDS to pre-emptively log a client out should be set at authentication time ie session length and volume quotas.

**Comment by Nxtframe** [comment]
Sorry, I'll put it into context in fas-hid.php In the status_page() function:-

```
function status_page() {
	$me=$_SERVER['SCRIPT_NAME'];
	$clientip=$GLOBALS["clientip"];
	$clientmac=$GLOBALS["clientmac"];
	$gatewayname=$GLOBALS["gatewayname"];
	$gatewayaddress=$GLOBALS["gatewayaddress"];
	$gatewaymac=$GLOBALS["gatewaymac"];
	$clientif=$GLOBALS["clientif"];
	$client_zone=$GLOBALS["client_zone"];
	$originurl=$GLOBALS["originurl"];
	$redir=rawurldecode($originurl);

	// Is the client already logged in?
	if ($_GET["status"] == "authenticated") {
		echo "
			<med-blue>You are connected to $client_zone</med-blue><br>
			<p><big-red>You are already logged in and have access to the Internet.</big-red></p>
			<hr>
			<p><italic-black>You can use your Browser, Email and other network Apps as you normally would.</italic-black>    Or Logout </p>

        **<form action=\"".$authaction."\" method=\"get\">
           <input type=\"hidden\" name=\"clientip\" value=\"".$clientip."\">
           <input type=\"submit\" value=\"Logout\" > //What Parameters should I send to Deauth the client
        </form>** 
		";

		read_terms();

		echo "
			<p>
			Your device originally requested <b>$redir</b>
			<br>
			Click or tap Continue to go to there.
			</p>
			<form>
				<input type=\"button\" VALUE=\"Continue\" onClick=\"location.href='".$redir."'\" >
			</form>
		";
	}
```

Am I approaching this the right way ?

**Comment by bluewavenet** [comment]
@Nxtframe 

> Am I approaching this the right way ?

No.

> //What Parameters should I send to Deauth the client

You cannot send anything to openNDS from fas-hid. You can only reply to requests from the client.

As I said above:

> Parameters required for openNDS to pre-emptively log a client out should be set at authentication time ie session length and volume quotas.

Up to date clients _should_ support rfc8910 CPI and provide a top bar indicator with a link to http://status.client
This url is the openNDS CPI status page and contains account information and a logout button.

**Comment by xreyc-developers** [comment]
Is there a way to deauthenticate user without logout button?
Is there some kind of counter sent by openNDS to fas-fid,
then fas-fid just have to respond if user it still authenticated or not?

**Comment by bluewavenet** [comment]
@xreyc-developers 

>  My users are subscribing to my promos (unlimited, no quotas)

For this you would actually set a "time quota", ie FAS would set session length according to the promo.
Fas records the time (in the log) of authentication. If the client logs out or is logged out from an inactivity timeout, but then logs back in, FAS can calculate how much of the promo is left and set session length to this new duration. If there is nothing left of the promo, then FAS would deny access.

**Comment by xreyc-developers** [comment]
I see, thank you.

**Comment by xreyc-developers** [comment]
How do I set the session expiration during login?

**Comment by Nxtframe** [comment]
> @Nxtframe
> 
> > Am I approaching this the right way ?
> 
> No.
> 
> > //What Parameters should I send to Deauth the client
> 
> You cannot send anything to openNDS from fas-hid. You can only reply to requests from the client.
> 
> As I said above:
> 
> > Parameters required for openNDS to pre-emptively log a client out should be set at authentication time ie session length and volume quotas.
> 
> Up to date clients _should_ support rfc8910 CPI and provide a top bar indicator with a link to http://status.client This url is the openNDS CPI status page and contains account information and a logout button.

Ohh thank you, I realised FAS cannot Deauth a client directly but there are other tools for it.

**Comment by bluewavenet** [comment]
@xreyc-developers 

> How do I set the session expiration during login?

Look at `function thankyou_page()` in fas-hid.php
There you will see the variable $custom being set.
You will add the session length to the string eg:
`$custom="fullname=$fullname, email=$email, session_length=$session_length";` 

The b64 encoded version of this variable is then sent to binauth for openNDS to process.

You will have to modify the binauth_log.sh script and enable it in the openNDS config.

In binauth_log.sh you will see the variable $customdata will be the b64encoded custom string sent by fas-hid.php

You will have to decode and parse this to get the value for session length and change line 275 as required.

Hint: You b64decode by calling `ndsctl b64decode $customdata` (see documentation)

**Comment by xreyc-developers** [comment]
Thank you
