### ISSUE TITLE
How to use themeSpec in remote FAS?

### ISSUE THREAD

**Issue by JackyCZJ** [openNDS/openNDS#368]
We wirte a theme_click-to-continue-xxx.sh and it work on local prefect. But we can't find a way to use themeSpec like script on remote  nginx or uhttpd service. Is there no another way instead of edit fas.php?

**Comment by JackyCZJ** [comment]
Thu Aug 11 16:27:44 2022 daemon.notice opennds[30531]: openNDS Version 9.7.0 is in startup
Thu Aug 11 16:27:44 2022 daemon.info opennds[30531]: Added ThemeSpec [/usr/lib/opennds/theme_click-to-continue-xxx.sh]
Thu Aug 11 16:27:44 2022 daemon.info opennds[30531]: Done reading configuration file '/tmp/etc/opennds_cfg01995c.conf'
Thu Aug 11 16:27:44 2022 daemon.info opennds[30531]: Initializing signal handlers
Thu Aug 11 16:27:44 2022 daemon.info opennds[30531]: Revert request sent
Thu Aug 11 16:27:44 2022 daemon.info opennds[30531]: tmpfs mountpoint is [/tmp]
Thu Aug 11 16:27:44 2022 daemon.notice opennds[30531]: MHD version is 0.9.71
Thu Aug 11 16:27:44 2022 daemon.notice opennds[30531]: Attempting to Bind to interface: guest-lan
Thu Aug 11 16:27:44 2022 daemon.notice opennds[30531]: Interface guest-lan is up
Thu Aug 11 16:27:44 2022 daemon.notice opennds[30531]: Interface guest-lan is at 172.168.1.1 (90:50:5a:9c:08:eb)
Thu Aug 11 16:27:44 2022 daemon.notice opennds[30531]: Number of Upstream gateway(s) [ 1 ]
Thu Aug 11 16:27:44 2022 daemon.notice opennds[30531]: Upstream gateway(s) [ online:10.1.2.254,eth0  ]
Thu Aug 11 16:27:44 2022 daemon.info opennds[30531]: Client status Page: Configured
Thu Aug 11 16:27:44 2022 daemon.info opennds[30531]: RFC8910 support is enabled
Thu Aug 11 16:27:44 2022 daemon.info opennds[30531]: Dnsmasq restarted
Thu Aug 11 16:27:44 2022 daemon.notice opennds[30531]: Adding Serial Number suffix [90505a9c08eb] to gatewayname
Thu Aug 11 16:27:44 2022 daemon.info opennds[30531]: main: System Uptime is 173300 seconds
Thu Aug 11 16:27:44 2022 daemon.info opennds[30531]: Setting started_time
Thu Aug 11 16:27:44 2022 daemon.info opennds[30531]: MHD Unescape Callback is Disabled
Thu Aug 11 16:27:44 2022 daemon.info opennds[30531]: MHD Handle [548214692256]
Thu Aug 11 16:27:44 2022 daemon.notice opennds[30531]: Created web server on 172.168.1.1:2050
Thu Aug 11 16:27:44 2022 daemon.notice opennds[30531]: Maximum Html Page size is [ 10240 ] Bytes
Thu Aug 11 16:27:44 2022 daemon.notice opennds[30531]: Socket access at /tmp/ndsctl.sock
Thu Aug 11 16:27:44 2022 daemon.notice opennds[30531]: FAS Enabled.
Thu Aug 11 16:27:44 2022 daemon.info opennds[30531]: fas_secure_enabled is set to level 2
Thu Aug 11 16:27:44 2022 daemon.info opennds[30531]: fasremoteip - 27.42.160.130 - is a valid IPv4 address...
Thu Aug 11 16:27:44 2022 daemon.notice opennds[30531]: sha256sum provider is available
Thu Aug 11 16:27:44 2022 daemon.notice opennds[30531]: SSL Provider is active
Thu Aug 11 16:27:44 2022 daemon.info opennds[30531]: OpenSSL module is loaded
Thu Aug 11 16:27:44 2022 daemon.notice opennds[30531]: FAS URL is http://xxoo.net:44443/fas-aes.php
Thu Aug 11 16:27:44 2022 daemon.info opennds[30531]: FAS FQDN is: unicom.esixcloud.net
Thu Aug 11 16:27:44 2022 daemon.notice opennds[30531]: Forwarding Authentication is Enabled.
Thu Aug 11 16:27:44 2022 daemon.notice opennds[30531]: Initializing firewall rules
Thu Aug 11 16:27:44 2022 daemon.notice opennds[30531]: Externals flagged with debuglevel 2.
Thu Aug 11 16:27:44 2022 daemon.notice opennds[30531]: openNDS is now running.

**Comment by bluewavenet** [comment]
@JackyCZJ 

> But we can't find a way to use themeSpec like script on remote nginx or uhttpd service.

Themespec is designed to be used with openNDS's own built in web server.

You can run a remote FAS written in any language as long as the remote web server has an interpreter for that language.
It is possible to run shell scripts using web cgi, so you could try that. Note that a standard Themespec script will most likely assume local access to ndsctl so will not work without significant reworking.

**Comment by JackyCZJ** [comment]
OK I got this, Thanks !
