### ISSUE TITLE
Difference between fas-aes.php and fas-fid.php

### ISSUE THREAD

**Issue by xreyc-developers** [openNDS/openNDS#369]
I am looking at fas-aes.php and fas-fid.php
both of them seems to work at local network.

here's my questions.
- can i run fas-fid.php without fqdn?
- does fas-fid required on port 80?
- does fas-aes runs only on the router in which the openwrt and opennds installed? (I have a separate computer hosting my application)
- why fas-aes can't use port 80?
- can I run fas-aes on a separate server(my application server) not on router(openwrt/opennds).

I am running a server on local network exposed at port 80 and I don't have fqdn.
I my server computer is connected to my router in which the openwrt and opennds are installed.
I am accessing my server via its hostname only without quilified fqdn.

**http://myserverhostname/nds/fas-fid.php**

should I use fas-aes.php or fas-fid.php?

**Comment by bluewavenet** [comment]
@xreyc-developers 

> Difference between fas-aes.php and fas-fid.php

1. fas-aes uses strong encryption for all communications between openNDS, FAS and the client. It requires some additional dependencies, so might present problems on hardware that is resource constrained

2.  fas-hid uses a "hashed id" for authentication. The hashed id (HID) is generated from a unique client token by hashing with a secret shared key known internally by both openNDS and FAS.
fas-hid does not require any additional dependencies on the router, so is ideal for router hardware that is resource constrained

3. Both fas-hid and fas-aes would normally be run on a remote server, but can also be run on the router.

4. Neither fas-aes nor fas-hid can use port 80 if run locally as port 80 is used by openNDS for redirection and for Captive Portal Identification (RFC8910/RFC8908). For example, if you enter http://status.client you will be served the openNDS page511 RFC8910 redirect.

> can i run fas-fid.php without fqdn?

Yes it is optional unless you are running FAS on a shared hosting web server or on a CDN or "Cloud" web service, in which case it is mandatory.

> should I use fas-aes.php or fas-fid.php?

This is completely up to you.

**Comment by xreyc-developers** [comment]
> Yes it is optional unless you are running FAS on a shared hosting web server or on a CDN or "Cloud" web service, in which case it is mandatory.
Great.
I am planning to move from shared hosting into my local server (mini pc)
so that performance would increase and also because of budget reason.
Thank you.
