### ISSUE TITLE
How to setup FAS?

### ISSUE THREAD

**Issue by tusharmalpani20** [openNDS/openNDS#37]
I have a freeRadius server running on a pi board.
How do I setup captive portal so that the authentication is done by the radius server.

**Comment by bluewavenet** [comment]
@tusharmalpani20 
This is fairly straightforward. But first I would suggest that radius authentication is overkill for a typical public wifi scenario.
Of course, in situations for example where a corporate database is accessed via radius or you are going through an academic or self learning exercise then all well and good.

Initially, set up a web site that allows a client to authenticate using radius. This is the "difficult" part independent of setting up the captive portal part.

Once you have this up and running, it will be time to add the openNDS API calls to the web site as demonstrated in the included fas example scripts.

This is discussed in detail in the documentation:
https://opennds.readthedocs.io/en/stable/fas.html#post-fas-processing

**Comment by tusharmalpani20** [comment]
> @tusharmalpani20
> This is fairly straightforward. But first I would suggest that radius authentication is overkill for a typical public wifi scenario.
> Of course, in situations for example where a corporate database is accessed via radius or you are going through an academic or self learning exercise then all well and good.
> 
> Initially, set up a web site that allows a client to authenticate using radius. This is the "difficult" part independent of setting up the captive portal part.
> 
> Once you have this up and running, it will be time to add the openNDS API calls to the web site as demonstrated in the included fas example scripts.
> 
> This is discussed in detail in the documentation:
> https://opennds.readthedocs.io/en/stable/fas.html#post-fas-processing

Thank you for a quick response :) 
Will follow the steps you said and if I get it working will post a complete  walk-through.
If I get stuck again.. will get back here asking more questions.

**Comment by bluewavenet** [comment]
@tusharmalpani20 
Did you get it working?
FYI v6.0.0 is now released.

**Comment by NagConnectus** [comment]
Hi Rob,
I have remote FAS server and want to use remote radius server for authentication purpose. I gone through the documentation ,but I didn't get clear idea about radius server integration with openNDS and corresponding configuration part, but I can see respective remote FAS configurations. After, remote FAS server serving the splash page to the user, user will enter the username and password ,so how that data passed down to radius server for authentication purpose and how radius server will notify the openNDS whether client is valid user or not?. Can you provide the configuration steps with remote FAS and Remote Radius Server while using with openNDS.

**Comment by stellarbnb** [comment]
Hi Rob,
I have a remote FAS server and I want to use a remote radius server for authentication purposes. I have gone through the documentation but a little confused with the setup. I can see the FAS server configuration options for openNDS in the documentation but didn't get the idea of how the radius server will notify the openNDS after validating the user credentials, since I'm not providing the radius server information to OpenNDS?. I have openWRT router is set up as a wireless access point, NDS is the captive portal, remote FAS, and RADIUS. Can you give me clarity, what configuration options,I can use to make openNDS works with remote FAS server ,remote radius server.

**Comment by bluewavenet** [comment]
@stellarbnb 
Your remote FAS would collect client credentials in the normal way but then validate them against a remote radius server using an appropriate radius API.

Once validated, the remote FAS will then do its normal callback to openNDS.

If you want to discuss radius authentication in more detail, please open a new issue.
