### ISSUE TITLE
openNDS blocks OpenWrt admin page

### ISSUE THREAD

**Issue by xreyc-developers** [openNDS/openNDS#370]
I am getting Error 404 - not found when I visit OpenWrt admin page.
My admin is at 10.0.0.1.
is there a way to allow specific ip addresses (my computer)
to access OpenWrt admin page?

**Comment by bluewavenet** [comment]
@xreyc-developers 

> I am getting Error 404 - not found when I visit OpenWrt admin page.
> My admin is at 10.0.0.1.

As mentioned in #369, port 80 is reserved for openNDS.
If you are using OpenWrt 21.02 or higher, Luci UI will be at https://10.0.0.1
If you are not using 21.02, you should upgrade as a matter of priority for other reasons, but would have to change the uhttpd config to allow Luci to be accessed.

**Comment by xreyc-developers** [comment]
https://10.0.0.1/ actually did it.
thank you.
