### ISSUE TITLE
How to configure BinAuth

### ISSUE THREAD

**Issue by xreyc-developers** [openNDS/openNDS#371]
Hello,

How do I configure Opennds to set different session_length?

My users can subscribe to promo which has a its own duration.
Promo1: 10 hours
Promo2: 1 day
Promo3: 3 days

Here's my configuration.

**OPENNDS CONFIG**
_at /etc/config/opennds_
> How do I able to enable BinAuth and necessary config, is this correct?
```
option fasport '80'
option faspath '/nds/fas-hid.php'
option fas_secure_enabled '1'
option faskey '1234567890'
option fasremoteip '10.0.0.23'
```

**PHP Server**
_at fas-hid.php_
> I am planning to pass this session_length to the binauth.
> I am planning to calculate the remaining time on users subscription here.
```
function thankyou_page() {
    $custom="fullname=$fullname, email=$email, session_length=200000";
    $custom=base64_encode($custom);
}
```

**SHELL SCRIPT**
_at /usr/lib/opennds/binauth_log.sh_
> How to I able to get the session_length sent from fas-hid.php?
```
// I beleive here is where I receive the session_length
if [ $action = "auth_client" ]; then
    log_entry="method=$1, clientmac=$2, clientip=$5, useragent=$4, token=$6, custom=$7"
else
    customdata=$8
    log_entry="method=$1, clientmac=$2, bytes_incoming=$3, bytes_outgoing=$4, session_start=$5, session_end=$6, token=$7, custom=$customdata"
fi
```
> At line 275 I am planning to put the data here and change the default from
`session_length=0`
to
`session_length=session_length_from_fas_hid`

I have very little idea how shell script works, can you help me?
Is there other configuration that I do not know?

**Comment by xreyc-developers** [comment]
I been trying to experiment on the shell script.
Is this correct?

```
if [ $action = "auth_client" ]; then
    customdata=$(ndsctl b64decode "$customdata")
    session_length_key='session_length'
    session_length_value=0
    
    # I am planning to get session_length using this script
    while read -d, -r pair;
        do
            IFS='=' read -r key val <<<"$pair"
            if [ $key == $session_length_key ]
                then session_length_value=$val
            fi
    done <<<"$customdata,"
else
    customdata=$8
fi

session_length=$session_length_value
```

> session_length_value result to these using online bash shell ide
![image](https://user-images.githubusercontent.com/25092979/184411625-9372bed6-23e4-4b96-9880-df27f61e8c99.png)

**Comment by bluewavenet** [comment]
@xreyc-developers 

>  Is this correct?

No. OpenWrt uses ASH shell, not BASH so I don't think your snippet of code will work.

Get session_length from $custom with this single line:
`session_length=$(echo $custom | awk -F"session_length=" '{printf "%d", $2}')`

Enable binauth by typing the following commands:
```
uci set opennds.@opennds[0].binauth='/usr/lib/opennds/binauth_log.sh'
uci commit opennds
service opennds restart

```

**Comment by xreyc-developers** [comment]
Here's my new config.

**CONFIG**
![image](https://user-images.githubusercontent.com/25092979/184460093-89e0763f-b5c6-442a-a988-fc422ed6cd65.png)

**BINAUTH_LOG.SH**
![image](https://user-images.githubusercontent.com/25092979/184460217-79380db3-e640-4790-85ba-470b659a8f25.png)

**FAS_HID (5mins)**
![image](https://user-images.githubusercontent.com/25092979/184460311-740d873c-8e92-4bba-845c-a4dca8ac0540.png)

But the session end did not change?
![image](https://user-images.githubusercontent.com/25092979/184460269-105f86e2-25d7-44ff-a088-3430a6584634.png)

**Comment by xreyc-developers** [comment]
Here's the status of opennds.

**/usr/bin/ndsctl status**
![image](https://user-images.githubusercontent.com/25092979/184460823-4475c385-5a1c-4b0b-b476-c0ff1aadbb99.png)

**/usr/bin/ndsctl json**
![image](https://user-images.githubusercontent.com/25092979/184460844-9ef4293e-0e9c-42a9-8b23-946c93a3f7d1.png)

**Comment by bluewavenet** [comment]
@xreyc-developers 

> Did I miss something?

No, I did. I forgot that openNDS urlencodes everything it sends to the binauth sctipt to prevent code injection (as some parameters are client user entered)

So you need to urldecode the received custom string before b64decoding it!
Also fas-hid uses the auth_client method so you need to set the $custom variable from the argument passed from opennds.

Instead of the one line of code I suggested, you need 3 lines:

> custom=$7
> custom=$(/usr/lib/opennds/unescape.sh -url $custom)
> session_length=$(echo $custom | awk -F"session_length=" '{printf "%d", $2}')

**Comment by bluewavenet** [comment]
@xreyc-developers 
So I thought I had better test it....
It seems there is a bug somewhere!
It looks like opennds ignores the binauth request to override the session length...
I'll fix it.... I have to do other things right now but I will do this asap ;-)

**Comment by xreyc-developers** [comment]
> 

Thank you for this.
I'll test it right away.

**Comment by xreyc-developers** [comment]
> custom=$7
> custom=$(/usr/lib/opennds/unescape.sh -url "$custom")
> custom=$(ndsctl b64decode "$custom")
> session_length=$(echo "$custom" | awk -F"session_length=" '{printf "%d", $2}')

This script worked!!
Thank you

Closing it for now.

**Comment by bluewavenet** [comment]
@xreyc-developers 

> This script worked!!

Excellent!

I looked at the code anyway. I was using fas-aes-https.php and that uses method ndsctl_auth so openNDS correctly ignores binauth override requests - so not a bug.

**Comment by bluewavenet** [comment]
@xreyc-developers 
Note: OpenNDS v9.8.0 is now released and the OpenWrt buildbots are working through all the architectures and should be finished soon, if not already.

9.8.0 fixes a problem when some client devices rapidly spam the CPI url (RFC 8910/8908). A bug in implementation in some flavours of Android and IoS causes the rapid spamming and can result in the openNDS web server (MHD) becoming unresponsive or even crashing.  

Backup your config and modified binauth file.
Then do:
```
opkg update
opkg install opennds

```

Restore your config and binauth file then do:
`service opennds restart`
