### ISSUE TITLE
Secured voucher URL 

### ISSUE THREAD

**Issue by lenovomen** [openNDS/openNDS#372]
Dear developer!

I would like to ask to you, how secure is the voucher URL generated by openNDS consisting of long numbers and letters? Is there any solution to hide it and shorten it? Or should I ignore it because it is safe in its default state ?

**Comment by bluewavenet** [comment]
@lenovomen 
The url generated by openNDS has nothing to do with vouchers.
The query string begins with `?fas=` and is the long string you mention.
The value of fas is a b64 encodes string that in turn contains the hashed id, generated using the secret key and the unique access token unique to the client.

There is no information at all to do with the voucher system encoded into the query string.
I do not know what you mean by "how secure is the voucher url"....

The security built into openNDS is designed to make it impossible to bypass the captive portal without logging in first.
