### ISSUE TITLE
Binauth security

### ISSUE THREAD

**Issue by xreyc-developers** [openNDS/openNDS#373]
I successfully converted the **fas-fid.php** to nodejs application.
While doing the authentication, I notice something that can be altered by user/hacker.
In my application, I have a promo subscription for the users which have it own duration dependent on  what they subscribed to.

**Ex:**
> Promo 1: 10hours
> Promo 2: 1 day
> Promo 3 3 days

During the authentication process, I am calculating the remaining time left for the user to connect to the Wi-Fi.
After the calculation, custom variable for binauth is converted to base64.

What I see as a loop hole on my authentication process is that knowledgeable user can alter the session_length
by decoding my base64 **custom** then changing the **session_length** and lastly encode it back to base64.
I think custom data should be encrypted so that user wont be able to get what is inside it.

![image](https://user-images.githubusercontent.com/25092979/184536343-d9a0b698-817f-47fa-864a-6df7108937fd.png)

on **fas-hid.php** sample
user can see the custom by inspecting the element.
```
<form action=\"".$authaction."\" method=\"get\">
	<input type=\"hidden\" name=\"tok\" value=\"".$tok."\">
	<input type=\"hidden\" name=\"custom\" value=\"$custom\">
	<input type=\"hidden\" name=\"redir\" value=\"".$redir."\"><br>
	<input type=\"submit\" value=\"Continue\" >
</form>
```

**QUESTION:**
Is **hid** unique every authentication process?
Is token can be reused on another device?
Is there a way to encrypt custom so that user won't be able to change my setup?

**Comment by bluewavenet** [comment]
@xreyc-developers 

> I think custom data should be encrypted so that user wont be able to get what is inside it.

In normal circumstances, fas-hid is used where the openNDS router is resource constrained, ie it has very little flash left for installing extra dependencies and has very little free ram for executing complex code.
The custom data is generally used only for providing user data for logging locally on the router (fas-hid.php logs on the FAS server - not necessary for FAS and openNDS to be running on the same device).

In your case, yes, a knowledgeable user could discover the session_length and change it to their advantage, particularly if they are paying for a particular session_length.

> Is hid unique every authentication process?

Yes, it is unique and it is hashed in a specific way that openNDS will be expecting for an authentication request for that client for that particular login only.

> Is token can be reused on another device?

No, see previous answer.

>  Is there a way to encrypt custom so that user won't be able to change my setup?

Of course. In fact you only need to encrypt session_length.

Even better, as each promo can be a shared secret, you could generate a unique promo code, in the same way fas-hid does for "tok" (known internally as rhid - the return hid)

You have:
Promo 1: 10hours
Promo 2: 1 day
Promo 3: 3 days

Lets assume both fas-hid and binauth know this.

Example:
For Promo 1
In fas-hid (in PHP)
```
$promo=hash('sha256', $hid.$key."promo1");
$custom="fullname=$fullname, email=$email, promo=$promo";
$custom=base64_encode($custom);
```

In binauth_log.sh:

```
custom=$7
key=$(/usr/lib/opennds/libopennds.sh get_option_from_config faskey)
promolist="promo1 promo2 promo3"
promo1="600" #10 hours
promo2="1440" #1 day
promo3="4320" #3 days

custom=$(/usr/lib/opennds/unescape.sh -url "$custom")
custom=$(ndsctl b64decode "$custom")
promo=$(echo "$custom" | awk -F"promo=" '{printf "%s", $2}' | awk -F"," '{printf "%s", $1}')

for promonum in $promolist; do
	hpromo=$(echo "$hid""$key""$promonum" | sha256sum | awk '{printf "%s", $1}')

	if [ "$hpromo" = "$promo" ]; then

		case "$promonum" in
			"promo1")
			session_duration=$promo1
			;;
			"promo2")
			session_duration=$promo2
			;;
			"promo3")
			session_duration=$promo3
			;;
		esac



		break
	fi
done

```

**Comment by xreyc-developers** [comment]
Looks great!!

Now since I am calculating the promo hour remaining left for specific user, I am planning to pass multiple hashed inputs from **fas-hid.php** then do some multiplication on binauth_log.sh.

**QUESTION:**
SHA256 is not reversible right? 

If yes, creating a table for each hash is the way to go.

on my **fas-hid.php** (will be converted to nodejs application later)
```
$day=hash('sha256', $hid.$key."d2");
$hour=hash('sha256', $hid.$key."h4");
$minute=hash('sha256', $hid.$key."m1");
$custom="fullname=$fullname, email=$email, day=$day, hour=$hour, minute=$minute";
$custom=base64_encode($custom);
```

on my **In binauth_log.sh**:
```
custom=$7
key=$(/usr/lib/opennds/libopennds.sh get_option_from_config faskey)
daylist = "d1, d2, d3, d4, d5, d6, d7, d8, d9, d10, d11, d12, d13, d14, d15, d16, d17, d18, d19, d20, d21, d22, d23, d24, d25, d26, d27, d28, d29, d30"
hourlist = "h1, h2, h3, h4, h5, h6, h7, h8, h9, h10, h11, h12, h13, h14, h15, h16, h17, h18, h19, h20, h21, h22, h23"
minutelist = "m1, m2, m3, m4, m5 ... m59"

d1=1440
..
dn=n

h1=600
..
hn=n

m1=60
..
mn=n

custom=$(/usr/lib/opennds/unescape.sh -url "$custom")
custom=$(ndsctl b64decode "$custom")
rday=$(echo "$custom" | awk -F"day=" '{printf "%s", $2}' | awk -F"," '{printf "%s", $1}')
rhour=$(echo "$custom" | awk -F"hour=" '{printf "%s", $2}' | awk -F"," '{printf "%s", $1}')
rminute=$(echo "$custom" | awk -F"minute=" '{printf "%s", $2}' | awk -F"," '{printf "%s", $1}')

for daycode in $daylist; do
	hday=$(echo "$hid""$key""$daycode" | sha256sum | awk '{printf "%s", $1}')

	if [ "$hday" = "$rday" ]; then

		case "$daycode" in
			"d1")
			dayseconds=$d1
			;;
			"d2")
			dayseconds=$d2
			;;
			"d3")
			dayseconds=$d3
			;;
		esac

		break
	fi
done

for hourcode in $hourlist; do
	hhour=$(echo "$hid""$key""$hourcode" | sha256sum | awk '{printf "%s", $1}')

	if [ "$hhour" = "$rhour" ]; then

		case "$hourcode" in
			"h1")
			hourseconds=$h1
			;;
			"h2")
			hourseconds=$h2
			;;
			"h3")
			hourseconds=$h3
			;;
		esac

		break
	fi
done

for minutecode in $minutelist; do
	hminute=$(echo "$hid""$key""$minutecode" | sha256sum | awk '{printf "%s", $1}')

	if [ "$hminute" = "$rminute" ]; then

		case "$minutecode" in
			"m1")
			minuteseconds=$m1
			;;
			"m2")
			minuteseconds=$m2
			;;
			"m3")
			minuteseconds=$m3
			;;
		esac

		break
	fi
done

totalseconds=dayseconds+hourseconds+minuteseconds
session_duration=$totalseconds
```

Is this correct?

**Comment by bluewavenet** [comment]
@xreyc-developers 

> QUESTION:
> SHA256 is not reversible right?

SHA256 is not reversible.

> Is this correct?

It looks good, but I did not test it.

> Do I have to convert totalseconds to string before assigning it to session_length?

No. The Linux shell does not care (apart from some special cases).

**So does it work for a client login?**

There is a potential problem here though.
The (B)ASH shell limits the length of a command argument. For Busybox ASH this is, I think, 1024 bytes.
The problem here is doing the `ndsctl b64decode [argument]`. The argument may be truncated when ndsctl receives it.
There are ways around this but it gets complicated.

>  I have multiple router with OpenWrt + openNDS located in many location.

**Then why did you choose to use the fas hid approach? Are the routers resource limited?**

If the routers are 128ram/16flash or better, you can run a single Internet based fas-aes-https server for ALL the routers.
Each router will have its own identity, and passing quota settings (including session length) is done directly from FAS to openNDS using NAT traversal techniques so no need for BinAuth or any of this.

**Comment by xreyc-developers** [comment]
@bluewavenet

> It looks good, but I did not test it.
I'll test it after I converted the code to nodejs.
I'll get back to you if it works.

> Then why did you choose to use the fas hid approach? Are the routers resource limited?
Right now I am using Mikrotik Rb750 Hex with 12 access point connected to the router via fiber optics.
I am planning to put 12 access points per one Mikrotik.
I am not planning to host my auth application on hosting for now, maybe later if I expand to other location where my fiber optics can no longer reach.

**Comment by xreyc-developers** [comment]
I am planning to connect to routers together so that router2 can still access the fas server (computer).
Fas server is connected to router1 then router2 just have to connect to router1 to access the fas server.
Is this possible?

**Comment by bluewavenet** [comment]
@xreyc-developers 

> Mikrotik Rb750 Hex

Isn't that eol? I can see they are still available but at very much reduced price. Aren't they 64/16 devices? Might struggle with OpenWrt 22.03.... Not enough ram.

Presumably you are using a fibre switch for the AP connections....

So you will have a separate but local FAS machine (on the same subnet)?  It looks like you are stuck with the fas-hid approach as running the dependencies for fas-aes will most likely result in ram issues.

You will therefore have to be very careful to keep the command argument length down to a minimum. You could leave out the fullname and emailaddress entries in custom b64 encoded string sent to binauth as the FAS server should be logging these.

Personally, I would look seriously at getting a more up to date router to replace the RB750. Something like a Gl-inet B1300? Similar price but very much more up to date.

> Fas server is connected to router1 then router2 just have to connect to router1 to access the fas server.
> Is this possible?

I'm not clear what you mean. Perhaps sketch a diagram, take a photo on your phone and post it here?

**Comment by xreyc-developers** [comment]
Here is my diagram..
I want to be able to access the FAS Server from Router2.
Is this possible?

![image](https://user-images.githubusercontent.com/25092979/184642690-5f704848-d547-48d8-9590-dffc608f3c6d.png)

**Comment by xreyc-developers** [comment]
> Personally, I would look seriously at getting a more up to date router to replace the RB750. Something like a Gl-inet B1300? Similar price but very much more up to date.

Looks good,
I am looking for wired only router around $50-$200.
Can you recommend best router might fit that's able to handle 250 users at the same time?

**Comment by xreyc-developers** [comment]
I've been wondering if it's possible to authenticate user on server-to-router only..
Here's my step..

1. User connects to the Wi-Fi
2. User will be captured and redirected by opennds to the fas server.
3. on the fas server, I am going to authenticate the user without doing it on the client-side(user).
(since the hid is already receive by the fas server, I am going to authenticate it without crossing the user's browser).
4. after authentication is successful I am going to redirect the user to the success page.

Is this possible?
This way I won't have to worry on my router's limit.

**Comment by bluewavenet** [comment]
@xreyc-developers 

> Here is my diagram..

It does not make sense. 

1. Is the ISP modem actually a router?
2. If it is a router, what is it's lan ip address?
3. If it is just a modem, does your ISP give you multiple Internet ip addresses?
4. Why do you have the triangle of "lan" between the isp side switch, router1, router2 and back to isp switch? Is the triangle all one ip subnet?
5. Why do you have 2 routers? To share the load? How many clients?
6. If you have to have 2 routers, the FAS server would be better off connected to the isp side switch.... Why is it connected to a port of router 1? 

> I've been wondering if it's possible to authenticate user on server-to-router only..

This is what fas-aes-https.php does, using nat traversal.

If you wanted to do this with fas-hid, the FAS server and openNDS router must not be separated by nat to start with. Then you will have to allow port forwarding to allow FAS to talk to the router and somehow run ndsctl.....

So yes it is theoretically possible but fraught with difficulties and not easy to achieve. You will most likely need more packages on the router, defeating the object of fas-hid.

If you really want to achieve this, perhaps the best way is to write a custom ThemeSpec script that uses wget to call a modified version of your FAS server only for validation and to retrieve quota value(s). This communication with your FAS would be hidden from clients and can use TLS with self signed certificates, so would be securely encrypted.
ThemeSpec scripts use the built in openNDS web server (MHD) so do not need a separate web server running a FAS server, thus saving a geat deal of ram/flash resource.
Worth a look?
https://opennds.readthedocs.io/en/stable/themespec.html#themespec-script-files

**Comment by xreyc-developers** [comment]
@bluewavenet 

> Is the ISP modem actually a router?
> If it is a router, what is it's lan ip address?
> If it is just a modem, does your ISP give you multiple Internet ip addresses?
> Why do you have the triangle of "lan" between the isp side switch, router1, router2 and back to isp switch? Is the triangle all one ip subnet?
> Why do you have 2 routers? To share the load? How many clients?
> If you have to have 2 routers, the FAS server would be better off connected to the isp side switch.... Why is it connected to a port of router 1?

Perhaps I should do it this way?
Router 1 and router 2 will access 192.168.1.22(Fas Server), is this correct?

![image](https://user-images.githubusercontent.com/25092979/184776330-8970ee77-eaed-4202-96ee-9b2811eab81d.png)

> This is what fas-aes-https.php does, using nat traversal.

Oww I see, it is possible to use non https link without fqdn like in my case that just use http://10.0.0.22?

> If you really want to achieve this, perhaps the best way is to write a custom ThemeSpec script that uses wget to call a modified version of your FAS server only for validation and to retrieve quota value(s). This communication with your FAS would be hidden from clients and can use TLS with self signed certificates, so would be securely encrypted.
> ThemeSpec scripts use the built in openNDS web server (MHD) so do not need a separate web server running a FAS server, thus saving a geat deal of ram/flash resource.
> Worth a look?

I'll read more into this, my biggest problem is that I don't know how to do some shell scripts, maybe need some more reading.

**Comment by bluewavenet** [comment]
@xreyc-developers 

> Perhaps I should do it this way?
> Router 1 and router 2 will access 192.168.1.22(Fas Server), is this correct?

Yes! That looks good and will work fine.

The speed of the router helps for multiple concurrent logins, but is less important for concurrent users.
One router could handle all 140 users at the expense of a slowish login occurring _sometimes_.
But these routers are cheap, so using two isn't a bad idea.
