### ISSUE TITLE
How to Run another script from binauth

### ISSUE THREAD

**Issue by Nxtframe** [openNDS/openNDS#376]
I've tried multiple ways to run another script from binauth but to no avail,  I've tested making script "a" to call script "b" in ash and it works but binauth doesnt,
does binauth work in a custom manner that wont allow it to run ?

**Comment by Nxtframe** [comment]
Figured it out, Running Old version of OpenWrt so OpenWrt installed an old version of opennds

**Comment by bluewavenet** [comment]
@Nxtframe 

>  does binauth work in a custom manner that wont allow it to run ?

No, the only restriction is that running `ndsctl status` or `ndsctl json` is prohibited.
You should either:
 * Start an instant of ash to run script b
 or
* run script b as an include of script a

It is not dependent on the version of openNDS.
