### ISSUE TITLE
Connect to 192.168.1.1, Error 403 - Forbidden - Access Denied to this Client!

### ISSUE THREAD

**Issue by weixing979** [openNDS/openNDS#379]
Hello,
I  have installed openNDS on my dev board.
And the dev board has one APN to connect to the Internet (APN's name is ccmni1),
and has br-lan  as the bridge.  br-lan's ip is 192.168.1.1
If openNDS is not setup, my PC access 192.168.1.1 with br-lan ,it will navigate to  http://192.168.1.1/web_whw/#/overview,
but when openNDS is  setup, PC access 192.168.1.1 will get   "Error 403 - Forbidden - Access Denied to this Client!"

Please help to check which configuration is wrong?  thanks.
Here is my dev board info.

==============================================================================
root@OpenWrt:/configs# opkg install opennds_9.8.0-1_aarch64_cortex-a55_neon-vfpv4.ipk
Installing opennds (9.8.0-1) to root...
Configuring opennds.
uci: Entry not found
Collected errors:
 * resolve_conffiles: Existing conffile /etc/config/opennds is different from the conffile in the new package. The new conffile will be placed at /etc/config/opennds-opkg.

root@OpenWrt:/configs# uci show opennds
opennds.@opennds[0]=opennds
opennds.@opennds[0].enabled='1'
opennds.@opennds[0].fwhook_enabled='1'
opennds.@opennds[0].maxclients='250'
opennds.@opennds[0].users_to_router='allow tcp port 53' 'allow udp port 53' 'allow udp port 67' 'allow tcp port 22' 'allow tcp port 80' 'allow tcp port 443'
opennds.@opennds[0].login_option_enabled='1'
opennds.@opennds[0].faskey='1234567890'
opennds.@opennds[0].allow_preemptive_authentication='1'

root@OpenWrt:/configs# iptables -V
iptables v1.8.7 (legacy)

root@OpenWrt:/configs# brctl show
bridge name     bridge id               STP enabled     interfaces
br-lan          7fff.001122320129       no              eth0
                                                        rai4
                                                        ra3
                                                        rai2
                                                        ra1
                                                        rai0
                                                        eth1
                                                        ecd0
                                                        ra4
                                                        rai3
                                                        ra2
                                                        rai1
                                                        ra0

root@OpenWrt:/configs# ifconfig br-lan
br-lan    Link encap:Ethernet  HWaddr 00:11:22:32:01:29
          inet addr:192.168.1.1  Bcast:192.168.1.255  Mask:255.255.255.0
          inet6 addr: fe80::211:22ff:fe32:129/64 Scope:Link
          inet6 addr: 2409:891f:8f45:ad8c::/64 Scope:Global
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:3987 errors:0 dropped:0 overruns:0 frame:0
          TX packets:2129 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000
          RX bytes:318664 (311.1 KiB)  TX bytes:15458685 (14.7 MiB)

root@OpenWrt:/configs#
root@OpenWrt:/configs#
root@OpenWrt:/configs#
root@OpenWrt:/configs# ifconfig ccmni1
ccmni1    Link encap:Ethernet  HWaddr 00:11:22:32:01:2B
          inet addr:10.56.54.94  Bcast:10.56.54.95  Mask:255.255.255.252
          inet6 addr: 2409:891f:8f45:ad8c:211:22ff:fe32:12b/128 Scope:Global
          UP BROADCAST RUNNING NOARP MULTICAST  MTU:1500  Metric:1
          RX packets:159 errors:0 dropped:0 overruns:0 frame:0
          TX packets:198 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000
          RX bytes:38446 (37.5 KiB)  TX bytes:22247 (21.7 KiB)

root@OpenWrt:/configs#
root@OpenWrt:/configs#
root@OpenWrt:/configs# route
Kernel IP routing table
Destination     Gateway         Genmask         Flags Metric Ref    Use Iface
default         10.56.54.93     0.0.0.0         UG    0      0        0 ccmni1
10.56.54.92     *               255.255.255.252 U     0      0        0 ccmni1
192.168.1.0     *               255.255.255.0   U     0      0        0 br-lan
root@OpenWrt:/configs#
root@OpenWrt:/configs#

root@OpenWrt:/etc# cat openwrt_release
DISTRIB_ID='OpenWrt'
DISTRIB_RELEASE='21.02.2'
DISTRIB_REVISION='r0+174-ed97d06b76'
DISTRIB_TARGET='gem6xxx/evb6890v1_64_cpe_emmc'
DISTRIB_ARCH='aarch64_cortex-a55_neon-vfpv4'
DISTRIB_DESCRIPTION='OpenWrt 21.02.2 r16495-bf0c965af0'
DISTRIB_TAINTS='no-all busybox override'

root@OpenWrt:/etc#
root@OpenWrt:/etc# iptables -t mangle -nvL|grep nds
 4260  301K ndsOUT     all  --  br-lan *       0.0.0.0/0            0.0.0.0/0
 4260  301K ndsBLK     all  --  br-lan *       0.0.0.0/0            0.0.0.0/0
 4260  301K ndsTRU     all  --  br-lan *       0.0.0.0/0            0.0.0.0/0
 2043   10M ndsINC     all  --  *      br-lan  0.0.0.0/0            0.0.0.0/0
Chain ndsALW (0 references)
Chain ndsBLK (1 references)
Chain ndsINC (1 references)
Chain ndsOUT (1 references)
Chain ndsTRU (1 references)

**Comment by bluewavenet** [comment]
@weixing979 

> If openNDS is not setup, my PC access 192.168.1.1 with br-lan ,it will navigate to http://192.168.1.1/web_whw/#/overview,
> but when openNDS is setup, PC access 192.168.1.1 will get "Error 403 - Forbidden - Access Denied to this Client!"

This shows two problems.

1. Port 80 on the gateway address is used exclusively for the openNDS built in web server. This cannot be changed as it is fundamental to how the client CPD/CPI functions. However the expected return for http://192.168.1.1/web_whw/#/overview would be **Error 404**.
If you want to run another web server, you should change the port it uses, for example to port 81, giving a url of http://192.168.1.1:81/web_whw/#/overview
2. **Error 403** is served by openNDS when access is denied, for whatever reason. The most likely reason here is your PC has a static ip address, or you have rebooted the router and the PC has not yet refreshed its DHCP configuration.

**Comment by weixing979** [comment]
@bluewavenet 
Thanks for your reply, now I have killed the lighttpd process (web server in my dev board), then I start openNDS  and access
 192.168.1.1, it still return Error 403.
and I found port 80 is not listened ,is it right?

root@OpenWrt:~# netstat -an|grep :80
tcp        0      0 192.168.1.1:8099        0.0.0.0:*               LISTEN
udp        0      0 127.0.0.1:8001          0.0.0.0:*
udp        0      0 0.0.0.0:8088            0.0.0.0:*
udp        0      0 127.0.0.1:36871         127.0.0.1:8001          ESTABLISHED

**Comment by weixing979** [comment]
Hello   bluewavenet,
Now my PC's IP is 192.168.1.152 ( Dynamic IP) ，then access 192.168.1.1 ,and my collect the log. Please help to check where is the obvious problem. Thanks.
[openNDSlog.txt](https://github.com/openNDS/openNDS/files/9450125/openNDSlog.txt)

**Comment by bluewavenet** [comment]
@weixing979 

> Now my PC's IP is 192.168.1.152 ( Dynamic IP) ，then access 192.168.1.1 ,it return Error 403

From your latest log:
`2022-08-30T05:51:41.596856+00:00 [debug] opennds 14199 Client ip address [192.168.1.152] is on our subnet using interface [br-lan]`

This shows the client (your PC) is accepted as valid, so you should not get the 403 error.
It is most likely that your browser is caching the previous error page.

What happens if you try to access http://status.client ?

**Comment by bluewavenet** [comment]
@weixing979 
Ah!!!
I just spotted this in your logs:
`2022-08-30T05:51:41.670430+00:00 [notice] opennds 14199 IP not allocated by dhcp [192.168.1.152]`

This is the problem - "IP not allocated by dhcp [192.168.1.152]"

**Comment by weixing979** [comment]
@bluewavenet 
Yes,I have found this log, 2022-08-30T05:51:41.670430+00:00 [notice] opennds 14199 IP not allocated by dhcp [192.168.1.152]
I change another PC,  the log "IP not allocated by dhcp[192.168.1.144] is still found.
maybe I should check my dev board first. 
What might have caused this? 
Thanks.

**Comment by bluewavenet** [comment]
@weixing979 

>  What might have caused this?

The dhcp server is not working correctly?

Show the output of:
`uci show dhcp`

**Comment by weixing979** [comment]
@bluewavenet 

root@OpenWrt:~# uci show dhcp
dhcp.@dnsmasq[0]=dnsmasq
dhcp.@dnsmasq[0].domainneeded='1'
dhcp.@dnsmasq[0].boguspriv='1'
dhcp.@dnsmasq[0].filterwin2k='0'
dhcp.@dnsmasq[0].localise_queries='1'
dhcp.@dnsmasq[0].rebind_protection='1'
dhcp.@dnsmasq[0].rebind_localhost='1'
dhcp.@dnsmasq[0].local='/lan/'
dhcp.@dnsmasq[0].domain='lan'
dhcp.@dnsmasq[0].expandhosts='1'
dhcp.@dnsmasq[0].nonegcache='0'
dhcp.@dnsmasq[0].authoritative='1'
dhcp.@dnsmasq[0].readethers='1'
dhcp.@dnsmasq[0].leasefile='/configs/dhcp.leases'
dhcp.@dnsmasq[0].resolvfile='/tmp/resolv.conf.auto'
dhcp.@dnsmasq[0].interface='lan' 'cni0'
dhcp.@dnsmasq[0].localservice='1'
dhcp.@dnsmasq[0].ednspacket_max='1232'
dhcp.@dnsmasq[0].localuse='1'
dhcp.@dnsmasq[0].port='53'
dhcp.@dnsmasq[0].address='/status.client/192.168.1.1'
dhcp.lan=dhcp
dhcp.lan.interface='lan'
dhcp.lan.force='1'
dhcp.lan.dhcpv6='server'
dhcp.lan.ra='server'
dhcp.lan.dhcpv4='server'
dhcp.lan.start='192.168.1.2'
dhcp.lan.limit='253'
dhcp.lan.netmask='255.255.255.0'
dhcp.lan.leasetime='86400s'
dhcp.lan.ra_management='1'
dhcp.lan.ra_preference='medium'
dhcp.lan.ra_maxinterval='600'
dhcp.lan.ra_mininterval='200'
dhcp.lan.ra_lifetime='1800'
dhcp.lan.ra_reachabletime='0'
dhcp.lan.dhcpv6_pd='0'
dhcp.lan.dns='fe80::211:22ff:fe32:129'
dhcp.lan.dhcp_option_force='114,http://status.client'
dhcp.wan=dhcp
dhcp.wan.interface='wan'
dhcp.wan.ignore='1'
dhcp.odhcpd=odhcpd
dhcp.odhcpd.maindhcp='0'
dhcp.odhcpd.leasefile='/tmp/hosts/odhcpd'
dhcp.odhcpd.leasetrigger='/usr/sbin/odhcpd-update'
root@OpenWrt:~#
root@OpenWrt:~#

and I can also view the IP address assigned by the board .
root@OpenWrt:~# cat /configs/dhcp.leases
1661929412 e4:e7:49:3c:4d:b7 192.168.1.144 wpon-HP-ProBook-430-G5 *
1661928496 48:0f:cf:29:8e:00 192.168.1.174 test-HP-ProBook-640-G1 *
1661930062 8c:8c:aa:0c:2f:e9 192.168.1.152 N-20S1PF202T8N 01:8c:8c:aa:0c:2f:e9

**Comment by weixing979** [comment]
From the log
2022-08-30T05:51:41.662786+00:00 [debug] opennds 14199 Executing command: /usr/lib/opennds/libopennds.sh dhcpcheck "192.168.1.152"
2022-08-30T05:51:41.662866+00:00 [debug] opennds 14199 Setting default SIGCHLD handler SIG_DFL
2022-08-30T05:51:41.663390+00:00 [debug] opennds 14199 Reading command output
2022-08-30T05:51:41.670266+00:00 [debug] opennds 14199 command output: []
2022-08-30T05:51:41.670430+00:00 [notice] opennds 14199 IP not allocated by dhcp [192.168.1.152]

What is the correct  print?

**Comment by bluewavenet** [comment]
@weixing979 
`dhcp.@dnsmasq[0].leasefile='/configs/dhcp.leases'`

openNDS expects the dhcp.leases file to be `/tmp/dhcp.leases`

You have not indicated anything about your hardware, but using anything other than tmpfs storage will result in rapid flash degradation and eventual failure on all but a genuine old-fashioned mechanical hard disk.

**Comment by weixing979** [comment]
@bluewavenet 
I tried to modify the file  /usr/lib/opennds/libopennds.sh, replace /tmp/dhcp.leases  to /configs/dhcp.leases , then access 192.168.1.1,  it can get splash page .   And I'll see how to  change that later.   
By the way, if I want continue access  http://192.168.1.1/web_whw/#/overview, it must be changed to  a port other than 80?
Thank you very much for your reply.

**Comment by bluewavenet** [comment]
Why do you want `dhcp.@dnsmasq[0].leasefile='/configs/dhcp.leases'`?
There is no need to change the default as dhcp.leases is purely transitory information anyway.

In addition, having `dhcp.lan.leasetime='86400s'` will cause severe problems for any system as the ip address pool will very soon be used up, particularly for a captive portal system where there is invariably a large turnover of devices.
In addition, the current trend for devices to use randomised mac addresses will make the situation much worse.

I would recommend a lease time of around 30 minutes or even less.

**Be warned:** Using non volatile storage on a router class device for frequent writes _WILL_ result in eventual flash memory failure, probably sooner than you might think.

>  By the way, if I want continue access http://192.168.1.1/web_whw/#/overview, it must be changed to a port other than 80?

Yes it must be changed. If it is something clients are expected to look at then, for convenience and user friendliness, you can add a link to the status.client page.

**Comment by weixing979** [comment]
@bluewavenet 
The position of  dhcp.leases  is modified by other colleagues，we should consider it later.
Thank you so much for your helpful advice. Thanks again.

**Comment by bluewavenet** [comment]
@weixing979 

> The position of dhcp.leases is modified by other colleagues

That is fine, as long as they are aware of the potential consequences.

Remember also that your dhcp pool currently has only 253 possible leases.
As an example, a busy coffee shop might have >200 customers in a 6 hour period. Customers returning for a second time in a day will most likely use yet another ip from the pool due to mac randomisation present on most devices these days - making the situation even worse.
So maybe after a few hours of business, no more customers will be able to connect to the wifi until some of the currently configured 24 hour leases expire.
