### ISSUE TITLE
Webpage not available error on an android device

### ISSUE THREAD

**Issue by musamaGamma** [openNDS/openNDS#381]
i am using fas with option 1, when i try to connect using the android system webview it throws with this error

![WhatsApp Image 2022-08-30 at 10 13 05 AM](https://user-images.githubusercontent.com/62172529/187386531-b72557b3-3509-4c84-8b0d-236ff5071d24.jpeg)

i

**Comment by bluewavenet** [comment]
@musamaGamma 

> i am using fas with option 1

It would be more useful if you shared the output of:
`uci show opennds`

It might not be your configuration, but we should look at it first.
Similar symptoms can occur if the mobile device already knows about another wireless network that is in range.
Initially the client connects to the captive portal network, but if the client user does not respond quick enough, the device can switch back to that other wireless network.

**Comment by musamaGamma** [comment]
`opennds.@opennds[0]=opennds
opennds.@opennds[0].enabled='1'
opennds.@opennds[0].debuglevel='3'
opennds.@opennds[0].fwhook_enabled='1'
opennds.@opennds[0].login_option_enabled='0'
opennds.@opennds[0].maxclients='250'
opennds.@opennds[0].fasport='80'
opennds.@opennds[0].fasremoteip='94.237.92.101'
opennds.@opennds[0].users_to_router='allow tcp port 53' 'allow udp port 53' 'allow udp port 67' 'allow tcp port 22' 'allow tcp port 80' 'allow tcp port 443'`
this is my configuration
it works on iphone

**Comment by musamaGamma** [comment]
thank you! the problem is solved
