### ISSUE TITLE
fas-aes-https.php setup

### ISSUE THREAD

**Issue by xreyc-developers** [openNDS/openNDS#384]
I have published my fas server at
https://linkedradius.infinityfreeapp.com/nds/fas-aes-https.php

it does run with on https after I setup the certificate..
![image](https://user-images.githubusercontent.com/25092979/188297828-9db0c05b-1f44-4756-8bd6-c1bcf3aa8493.png)

but the captive portal is not appearing..
have I done something wrong?

I am using opennds version 9.8.0-2

here's my opennds config:

```
config opennds
	option enabled 1
	option fwhook_enabled '1'
	option maxclients '250'
	list users_to_router 'allow tcp port 53'
	list users_to_router 'allow udp port 53'
	list users_to_router 'allow udp port 67'
	list users_to_router 'allow tcp port 22'
	list users_to_router 'allow tcp port 80'
	list users_to_router 'allow tcp port 443'
	option fasport '443'
	option faspath '/nds/fas-aes-https.php'
	option fas_secure_enabled '3'
	option faskey '1234567890'
	option fasremoteip '185.27.134.175'
	option fasremotefqdn 'linkedradius.infinityfreeapp.com'
```

**Comment by sicelo** [comment]
On Sat, Sep 03, 2022 at 09:47:25PM -0700, Reyco Seguma wrote:
> I have published my fas server at
> https://linkedradius.infinityfreeapp.com/nds/fas-aes-https.php
> 
> it does run with certificate..
> ![image](https://user-images.githubusercontent.com/25092979/188297828-9db0c05b-1f44-4756-8bd6-c1bcf3aa8493.png)
> 
> but the captive portal is not appearing..
> have I done something wrong?

Hi

This is not an openNDS problem. On non-paying accounts, InfinityFree
does not allow pages to be 'visited' by scripts. Only browsers can visit
pages, with Javascript and cookies. This is mentioned in their terms of
use.

You'll need to pay them, or find a different host.

**Comment by xreyc-developers** [comment]
@sicelo

I see.
I using free account for now just to test it then later convert it to nodejs application.
I am planning to figure out how this function works from **fas-aes-https.php**.

`function auth_get() {}`

I want to see its output so that I'll be able to convert it to nodejs.
I'll try to look for other hosting for now. If it won't work I think I'll try a paid one.

**Comment by xreyc-developers** [comment]
Hi @sicelo,

I tried again using paid account.
Domain name is still ongoing before it can propagate worldwide.
but I it can be access with this link.

https://xreyc-xyz.preview-domain.com/fas-aes-https.php

here's my config.
```
option fasport '443'
option faspath '/fas-aes-https.php'
option fas_secure_enabled '3'
option faskey '1234567890'
option fasremoteip '104.18.24.120'
	option fasremotefqdn 'xreyc-xyz.preview-domain.com'
```

Like my first case, still captive portal are not showing at all.

**Comment by bluewavenet** [comment]
@xreyc-developers 

**_Note: If you access your FAS server directly, you will by design, get a blank page._**

I tried your config, ie:
```
option fasport '443'
option faspath '/fas-aes-https.php'
option fas_secure_enabled '3'
option faskey '1234567890'
option fasremoteip '217.21.74.82'
option fasremotefqdn 'xreyc.xyz'
```
It works fine. You should be able to see my login in the FAS server log in ndslog/ndslog.php on the server.

![Screenshot from 2022-09-04 10-00-56](https://user-images.githubusercontent.com/13632068/188305980-5510ac1c-07d8-41e5-bbc0-ac9c21c8f1fb.png)

and

![Screenshot from 2022-09-04 10-02-20](https://user-images.githubusercontent.com/13632068/188305994-e6e5a90b-cf13-4154-9782-d411c8ef05a9.png)

**Comment by xreyc-developers** [comment]
@bluewavenet

Maybe I've done something wrong along the way..
I'll try to reflash OpenWrt then try to reinstall everything.

I am using

- openwrt-21.02 
- opennds version 9.8.0-2

Thanks

**Comment by bluewavenet** [comment]
@xreyc-developers 

>     openwrt-21.02
>     opennds version 9.8.0-2
> 

Same here.

**Comment by xreyc-developers** [comment]
I already reflashed OpenWrt and reinstalled openNDS with the same config above..
But captive portal is not showing.

I tried to run **/usr/bin/ndsctl status** but it show this:

![image](https://user-images.githubusercontent.com/25092979/188316575-83a2ffa6-d99b-4181-803f-af1b618e4cca.png)

**Comment by bluewavenet** [comment]
@xreyc-developers 
Did you install the php dependencies?
https://opennds.readthedocs.io/en/stable/fas.html#example-script-file-fas-aes-https-php

**Comment by xreyc-developers** [comment]
@bluewavenet 

It is working now..
Php dependency is my problem.
Thank you

Closing it now.
