### ISSUE TITLE
how does auth_get function works on fas-aes-https

### ISSUE THREAD

**Issue by xreyc-developers** [openNDS/openNDS#385]
I am looking at function **auth_get() {}** function on fas-aes-https.php file.

Here's my questions:
- Can this control the authenticated users?
- Does authmon sends request every period of time to validated authenticated users or it only gets trigger on user's authentication process?
- What is the difference between "list" and "view"? are they sending authenticated user or users to be deleted from the authentication list?
- Is there a documentation about sample request sent by authmon?

As looking at the fas folder it have a set of random named folder.
Are data stored in a form of a folder?

![image](https://user-images.githubusercontent.com/25092979/188337929-ce104db0-6d61-4146-99e8-0b7971f8404d.png)

**Comment by xreyc-developers** [comment]
I've been trying to get the request data..
The post request looks like this.

`https://xreyc.xyz/fas-aes-https.php?auth_get=view&gatewayhash=6b9f7c536fbd8618a4a8bacf39e3c2c6f1858497209fe08966aa61146d3a11e8&payload=Kg%3D%3D`

Heres what I get:

On **list**
ack

On **view** $acklist != "none"
ack

else
*

**Comment by xreyc-developers** [comment]
I logged the data by appending it to text, here's what I got.

```
[REQUEST] {"auth_get":"view","gatewayhash":"6b9f7c536fbd8618a4a8bacf39e3c2c6f1858497209fe08966aa61146d3a11e8","payload":"bm9uZQ=="}
[RESPONSE][viewnone] * 
[REQUEST] {"auth_get":"view","gatewayhash":"6b9f7c536fbd8618a4a8bacf39e3c2c6f1858497209fe08966aa61146d3a11e8","payload":"Kg=="}
[RESPONSE][view] ack 
[REQUEST] {"auth_get":"view","gatewayhash":"6b9f7c536fbd8618a4a8bacf39e3c2c6f1858497209fe08966aa61146d3a11e8","payload":"bm9uZQ=="}
[RESPONSE][viewnone] * 
[REQUEST] {"auth_get":"view","gatewayhash":"6b9f7c536fbd8618a4a8bacf39e3c2c6f1858497209fe08966aa61146d3a11e8","payload":"Kg=="}
[RESPONSE][view] ack 
[REQUEST] {"auth_get":"view","gatewayhash":"6b9f7c536fbd8618a4a8bacf39e3c2c6f1858497209fe08966aa61146d3a11e8","payload":"bm9uZQ=="}
[RESPONSE][viewnone] * c13f3aef4629917c386ec95faad23f8f4046a896ab6ed3e4b9888e66fd87900d%200%200%200%200%200%20ZnVsbG5hbWU9UmV5Y28lMjBTZWd1bWEsIGVtYWlsPXNlZ3VtYXJleWNvQGdtYWlsLmNvbQ%3D%3D 
[REQUEST] {"auth_get":"view","gatewayhash":"6b9f7c536fbd8618a4a8bacf39e3c2c6f1858497209fe08966aa61146d3a11e8","payload":"KiBjMTNmM2FlZjQ2Mjk5MTdjMzg2ZWM5NWZhYWQyM2Y4ZjQwNDZhODk2YWI2ZWQzZTRiOTg4OGU2NmZkODc5MDBk"}
[RESPONSE][view] ack 
[REQUEST] {"auth_get":"view","gatewayhash":"6b9f7c536fbd8618a4a8bacf39e3c2c6f1858497209fe08966aa61146d3a11e8","payload":"bm9uZQ=="}
[RESPONSE][viewnone] * 
[REQUEST] {"auth_get":"view","gatewayhash":"6b9f7c536fbd8618a4a8bacf39e3c2c6f1858497209fe08966aa61146d3a11e8","payload":"Kg=="}
[RESPONSE][view] ack 
[REQUEST] {"auth_get":"view","gatewayhash":"6b9f7c536fbd8618a4a8bacf39e3c2c6f1858497209fe08966aa61146d3a11e8","payload":"bm9uZQ=="}
[RESPONSE][viewnone] * 
[REQUEST] {"auth_get":"view","gatewayhash":"6b9f7c536fbd8618a4a8bacf39e3c2c6f1858497209fe08966aa61146d3a11e8","payload":"Kg=="}
[RESPONSE][view] ack 
[REQUEST] {"auth_get":"view","gatewayhash":"6b9f7c536fbd8618a4a8bacf39e3c2c6f1858497209fe08966aa61146d3a11e8","payload":"bm9uZQ=="}
[RESPONSE][viewnone] * 
[REQUEST] {"auth_get":"view","gatewayhash":"6b9f7c536fbd8618a4a8bacf39e3c2c6f1858497209fe08966aa61146d3a11e8","payload":"Kg=="}
[RESPONSE][view] ack 
[REQUEST] {"auth_get":"view","gatewayhash":"6b9f7c536fbd8618a4a8bacf39e3c2c6f1858497209fe08966aa61146d3a11e8","payload":"bm9uZQ=="}
[RESPONSE][viewnone] * 
[REQUEST] {"auth_get":"view","gatewayhash":"6b9f7c536fbd8618a4a8bacf39e3c2c6f1858497209fe08966aa61146d3a11e8","payload":"Kg=="}
[RESPONSE][view] ack 
[REQUEST] {"auth_get":"view","gatewayhash":"6b9f7c536fbd8618a4a8bacf39e3c2c6f1858497209fe08966aa61146d3a11e8","payload":"bm9uZQ=="}
[RESPONSE][viewnone] * 
[REQUEST] {"auth_get":"view","gatewayhash":"6b9f7c536fbd8618a4a8bacf39e3c2c6f1858497209fe08966aa61146d3a11e8","payload":"Kg=="}
[RESPONSE][view] ack 
[REQUEST] {"auth_get":"view","gatewayhash":"6b9f7c536fbd8618a4a8bacf39e3c2c6f1858497209fe08966aa61146d3a11e8","payload":"bm9uZQ=="}
[RESPONSE][viewnone] * 
[REQUEST] {"auth_get":"view","gatewayhash":"6b9f7c536fbd8618a4a8bacf39e3c2c6f1858497209fe08966aa61146d3a11e8","payload":"Kg=="}
[RESPONSE][view] ack 
[REQUEST] {"auth_get":"view","gatewayhash":"6b9f7c536fbd8618a4a8bacf39e3c2c6f1858497209fe08966aa61146d3a11e8","payload":"bm9uZQ=="}
[RESPONSE][viewnone] * 
[REQUEST] {"auth_get":"view","gatewayhash":"6b9f7c536fbd8618a4a8bacf39e3c2c6f1858497209fe08966aa61146d3a11e8","payload":"Kg=="}
[RESPONSE][view] ack 
[REQUEST] {"auth_get":"view","gatewayhash":"6b9f7c536fbd8618a4a8bacf39e3c2c6f1858497209fe08966aa61146d3a11e8","payload":"bm9uZQ=="}
[RESPONSE][viewnone] * 
[REQUEST] {"auth_get":"view","gatewayhash":"6b9f7c536fbd8618a4a8bacf39e3c2c6f1858497209fe08966aa61146d3a11e8","payload":"Kg=="}
[RESPONSE][view] ack 
[REQUEST] {"auth_get":"view","gatewayhash":"6b9f7c536fbd8618a4a8bacf39e3c2c6f1858497209fe08966aa61146d3a11e8","payload":"bm9uZQ=="}
[RESPONSE][viewnone] * 
[REQUEST] {"auth_get":"view","gatewayhash":"6b9f7c536fbd8618a4a8bacf39e3c2c6f1858497209fe08966aa61146d3a11e8","payload":"Kg=="}
[RESPONSE][view] ack 
[REQUEST] {"auth_get":"view","gatewayhash":"6b9f7c536fbd8618a4a8bacf39e3c2c6f1858497209fe08966aa61146d3a11e8","payload":"bm9uZQ=="}
[RESPONSE][viewnone] * 
[REQUEST] {"auth_get":"view","gatewayhash":"6b9f7c536fbd8618a4a8bacf39e3c2c6f1858497209fe08966aa61146d3a11e8","payload":"Kg=="}
[RESPONSE][view] ack 
[REQUEST] {"auth_get":"view","gatewayhash":"6b9f7c536fbd8618a4a8bacf39e3c2c6f1858497209fe08966aa61146d3a11e8","payload":"bm9uZQ=="}
[RESPONSE][viewnone] * 
[REQUEST] {"auth_get":"view","gatewayhash":"6b9f7c536fbd8618a4a8bacf39e3c2c6f1858497209fe08966aa61146d3a11e8","payload":"Kg=="}
[RESPONSE][view] ack 
[REQUEST] {"auth_get":"view","gatewayhash":"6b9f7c536fbd8618a4a8bacf39e3c2c6f1858497209fe08966aa61146d3a11e8","payload":"bm9uZQ=="}
[RESPONSE][viewnone] * 
[REQUEST] {"auth_get":"view","gatewayhash":"6b9f7c536fbd8618a4a8bacf39e3c2c6f1858497209fe08966aa61146d3a11e8","payload":"Kg=="}
[RESPONSE][view] ack 
[REQUEST] {"auth_get":"view","gatewayhash":"6b9f7c536fbd8618a4a8bacf39e3c2c6f1858497209fe08966aa61146d3a11e8","payload":"bm9uZQ=="}
[RESPONSE][viewnone] * 
[REQUEST] {"auth_get":"view","gatewayhash":"6b9f7c536fbd8618a4a8bacf39e3c2c6f1858497209fe08966aa61146d3a11e8","payload":"Kg=="}
[RESPONSE][view] ack 
```

**Comment by xreyc-developers** [comment]
on the **authenticate_page() {}**
this function is waiting for the **auth_get(){}** function to create folder with specific name to be created right?

In my case, I can save the auth data on database using the **auth_get(){}** function.
Then use the **authenticate_page(){}** to query the if auth data already exist in the database after a period of time. 

![image](https://user-images.githubusercontent.com/25092979/188383981-c5ab99e5-fd0f-46ac-bde0-03c9f3894e7e.png)

**Comment by bluewavenet** [comment]
@xreyc-developers 

> I am looking at function auth_get() {} function on fas-aes-https.php file.

The authmon daemon running on the openNDS router, polls FAS every 10 seconds to provide a means of nat trversal for FAS to communicate with openNDS.

For the purposes of openNDS/FAS it is useful to note the following terminology definitions:
1. **Validation** - FAS validates by some means the credentials added to the login page by the client user. If validation is successful, FAS asks openNDS to authenticate the client device.
2. **Authentication** - on request from FAS, openNDS authenticates the client device - ie it allows the device to have Internet access.

> Is there a documentation about sample request sent by authmon?

Only self documentation in authmon.sh

> As looking at the fas folder it have a set of random named folder.

Each client has a folder that contains authentication information for openNDS to use (quotas etc).
Once the client has been authenticated using this information, the file is deleted.

> It keeps growing every 10 seconds

Each entry is from the authmon daemon. It polls FAS once every 10 seconds.

> What is the difference between these 3 states?

The payload.

> In my case, I can save the auth data on database using the auth_get(){} function.

Yes you can. However using the Linux file system (the unique client folders and data files), was, after extensive testing, found to be significantly faster than a relational database, at least for this use case. This is why it is done as it is. There are live FAS servers basically the same as this that are handling many thousands of clients from dozens of openNDS gateways.

It is completely up to you how you choose to implement it.

**Comment by bluewavenet** [comment]
@xreyc-developers 

> As looking at the fas folder it have a set of random named folder.

**Comment by xreyc-developers** [comment]
@bluewavenet 

> Yes you can. However using the Linux file system (the unique client folders and data files), was, after extensive testing, found to be significantly faster than a relational database, at least for this use case. This is why it is done as it is. There are live FAS servers basically the same as this that are handling many thousands of clients from dozens of openNDS gateways.

**Comment by bluewavenet** [comment]
@xreyc-developers 
You have it correct until the waiting stage, then you have it wrong.

The client does not talk to openNDS during the login process.

The waiting stage is seen by the client as the "Landing Page" that is slowly being updated ( the PHP function flush() )
FAS **flushes** (or you could more correctly say "pushes") to the client every second (the growing row of red asterisks) whilst it waits for the next authmon poll.

That next poll will pick up a list of authentication requests from FAS (ie it can handle multiple requests at one time).

Once a client is authenticated by openNDS, authmon sends an "auth success" message to FAS on its next poll.

When the "auth success" message is received for a client, FAS deletes the client file and pushes a "You are now logged in" message to the client along with the rest of the landing page content.

Once Internet access is granted, many clients will almost immediately close the landing page only giving the user a brief glimpse of its contents, whereas other clients may keep that page open. This is entirely dependent on the client device operating system.

**Comment by xreyc-developers** [comment]
@bluewavenet 

> That next poll will pick up a list of authentication requests from FAS (ie it can handle multiple requests at one time).
This the sample of the poll.
```
[REQUEST] {"auth_get":"view","gatewayhash":"eba8a35041f824af304a94d17fb4e16dff4c3e908af036194cc883b0ef8fd0a4","payload":"bm9uZQ=="}
[RESPONSE] "* 951d2670a05117d69cfe682cc4819124ac612133e986104d1bfa9f3535c06fde%200%200%200%200%200%20ZnVsbG5hbWU9UmV5Y28lMjBTZWd1bWEsIGVtYWlsPXNlZ3VtYXJleWNvQGdtYWlsLmNvbQ%3D%3D"
```

**Comment by bluewavenet** [comment]
@xreyc-developers 
The auth success message is in the form of a list of acknowledged authentications embedded in the payload and is in the php variable $acklist. See fas-aes-https.php, function auth_get().

In your example, the payload is:
`KiA5NTFkMjY3MGEwNTExN2Q2OWNmZTY4MmNjNDgxOTEyNGFjNjEyMTMzZTk4NjEwNGQxYmZhOWYzNTM1YzA2ZmRl`
B64decoding this you get:
`* 951d2670a05117d69cfe682cc4819124ac612133e986104d1bfa9f3535c06fde`

Here the `*` is the authmon type identifier (there is currently only one type).
and the `951d2670a05117d69cfe682cc4819124ac612133e986104d1bfa9f3535c06fde` is the HID (unique hashed id) of the client.

It is also the unique filename for the client that FAS will delete upon receipt of this list.

It is a list, in this example, of only one client that has been authenticated. In a live system at a busy venue, there may well be a number of clients authenticating during one authmon polling interval.

**Comment by xreyc-developers** [comment]
@bluewavenet

> The auth success message is in the form of a list of acknowledged authentications embedded in the payload
Got it.

> It is a list, in this example, of only one client that has been authenticated. In a live system at a busy venue, there may well be a number of clients authenticating during one authmon polling interval.
Noted on this one.

I'll post my updated flowchart before closing this.
Others might find it useful.

Thank you.

**Comment by bluewavenet** [comment]
@xreyc-developers 

> I'll post my updated flowchart before closing this.
> Others might find it useful.

Excellent thankyou :+1:

**Comment by xreyc-developers** [comment]
I bit too long for more details.
I'll change something if there wrong.

![fas-aes-https flow](https://user-images.githubusercontent.com/25092979/188601047-64969678-835e-44c7-8ce6-39c9f0838ef2.png)

**Comment by bluewavenet** [comment]
@xreyc-developers 
Yes it does lack some detail but as this is intended (I assume) as a functional block diagram it does a good job of it!
Thank you for the significant work you have put into this.
