### ISSUE TITLE
Update session_length via FAS server

### ISSUE THREAD

**Issue by xreyc-developers** [openNDS/openNDS#386]
My problem is that I have many access point with its own SSID
connected to the same router. So what happens is each device have multiple IP address and mac address because they keep moving from one AP to another AP. (My current solution for this is I reduced the Ipv4 lease time to 30mins).

Second reason is that, I don't want my users share the same account.
I want to keep track of how many actual users currently using my service,
by logging in to their own account not on borrowed accounts.
(I created a mobile app, with games and others services with ads in exchange for free internet)
(or they can buy vouchers if they don't want any hassle)

**Is it possible to update the session_length of authenticated device using the FAS server?**
What I am planning is, every time the user authenticate using the same account on another
access point, I am going to create two authentication instance, one for the **old instance**
with updated session_length (30seconds) and one for **new auth instance** calculated with the remaining session_length.

**Comment by bluewavenet** [comment]
@xreyc-developers 

> Is it possible to update the session_length of authenticated device using the FAS server?

No. 

> I am going to create two authentication instance, one for the old instance
> with updated session_length (30seconds)

Just deauthenticate the old instance, as was discussed in #367

**Comment by xreyc-developers** [comment]
@bluewavenet 

Is it possible to add additional post request on authmon.sh along with the existing one?
I am planning to response  with specific list of mac address so that I can deauthenticate them using this command:
`/usr/bin/ndsctl deauth IP|MAC`

OR

modify the authmon.sh to work differently than expected.
currently authmon receives:
`* c13f3aef4629917c386ec95faad23f8f4046a896ab6ed3e4b9888e66fd87900d%200%200%200%200%200%20ZnVsbG5hbWU9UmV5Y28lMjBTZWd1bWEsIGVtYWlsPXNlZ3VtYXJleWNvQGdtYWlsLmNvbQ%3D%3D`
if a device needs to be authenticated.

**Now I am planning to response this way..**
If the device needs to be authenticated..
`AUTH * c13f3aef4629917c386ec95faad23f8f4046a896ab6ed3e4b9888e66fd87900d%200%200%200%200%200%20ZnVsbG5hbWU9UmV5Y28lMjBTZWd1bWEsIGVtYWlsPXNlZ3VtYXJleWNvQGdtYWlsLmNvbQ%3D%3D`

If the device needs to be deauthenticated..
`DEAUTH xx:xx:xx:xx:xx:xx xx:xx:xx:xx:xx:xx`

If the auth_get response starts with "AUTH"..
then it will go with the normal authentication process...
If it starts with "DEAUTH", then it will deauthenticate specific mac address...

Dauthenticating user via FAS to authmon will be a good use case for me..

**Comment by xreyc-developers** [comment]
@bluewavenet 

On current authmon.sh implementation this is what I saw..
```
authlist=$($phpcli -f "$postrequest" "$url" "$action" "$gatewayhash" "$user_agent" "$payload")

validator=${authlist:0:1}

if [ "$validator" = "*" ]; then
             /// DO AUTHENTICATION HERE
else
    for keyword in $authlist; do
        if [ $keyword = "ERROR:" ]; then
	    echo "authmon - [$authlist]" | logger -p "daemon.err" -s -t "opennds[$ndspid]"
	    echo "authmon - Check Internet connection, FAS url, and package ca-bundle installation" |
	        logger -p "daemon.err" -s -t "opennds[$ndspid]"
	    break
        fi
    done
fi
```

**Comment by bluewavenet** [comment]
@xreyc-developers 
It would be far better to use the existing binauth api to enforce only a single login at any time, using the same credentials.
As I said, this has already been discussed at length elsewhere.

**Comment by xreyc-developers** [comment]
I already have a work around for this issue.
Thanks

**Comment by xreyc-developers** [comment]
@bluewavenet 

I modified authmon.sh to kick previous instance of the same user account.
It works without any problem.
I really need this feature that's why I am pushing this approach.

```
validator=${authlist:0:1}
if [ "$validator" = "*" ]; then
      // DEFAULT AUTHENTICATION PROCESS
else
     if [ "$validator" = "D" ]; then
          // MY DEAUTHENTICATION PROCESS
          mactodeauth=${authlist:2:1024}
          macdeauth=$(ndsctl deauth "$mactodeauth");
          echo $macdeauth;
     else
          // DEFAULT ERROR PROCESS
     fi
fi
```

here's what I am doing on the FAS server:

1. Fas creates an authentication instance
2. Opennds receives the authentication intance
3. Opennds grant access to user
4. After next 10 seconds Opennds sends back the auth instance to fas server as a success message
5. Fas server deletes the auth instance
6. On next 10 seconds fas server response to authmon request with "D xx:xx:xx:xx:xx:xx"
7. Opennds deauthenticates the received mac.

**Comment by bluewavenet** [comment]
@xreyc-developers 

> I really need this feature

I disagree with the approach of modifying authmon. What you want to achieve is to restrict a user to a single login at any one time.
The binauth approach would be much more efficient with no delay between auth on one mac and deauth on another.
Binauth can also supply usage information to FAS (usage logging by FAS is included by default in the upcoming v9.9.0 release)


> `ndsctl deauth [mac|ip|token|hid]`

The existing syntax for deauth is:
`ndsctl deauth [mac|ip|token|rhid]`

Note 1: deauth accepts "rhid" and not "hid"
Note 2: deauth by token is deprecated and is scheduled to be removed in some future release.

**Comment by xreyc-developers** [comment]
@bluewavenet 

> What you want to achieve is to restrict a user to a single login at any one time.

My solution for this one is to trigger deauthentication, if there are no auth instance pending
to be authenticated by opennds so that users that trying to login wont be disturbed by the deauthentication process.

I have multiple router running opennds connected to the same fas server and I need that specific user authenticated on one router only. If I put the deauth code on the binauth, router1 won't be able to know that user gets authenticated on router2.

**Comment by xreyc-developers** [comment]
> The existing syntax for deauth is:
> ndsctl deauth [mac|ip|token|rhid

This is good for my use case, I don't want to track my users by their mac address.

**Comment by bluewavenet** [comment]
@xreyc-developers 
Ok, I see your use case, and what you are doing seems good and looks like it will work - _well done._

The structure of openNDS is designed with the hope of making specialised custom solutions easier to implement, so I guess this is an example of where this turns out to be true ;-)

However I will reiterate that this use case is aimed at a monetisation of Internet access in a market area that many years ago, ceased to exist in most countries.

Clearly you consider it still to be worthwhile in your area, at least for the time being, so I wish you the best of luck with it!

**Comment by xreyc-developers** [comment]
@bluewavenet 

> The structure of openNDS is designed with the hope of making specialized custom solutions easier to implement

Yes, it worked well for my use case.

In my area and all other area I've been to, only few can afford internet plans and on that few amount some discontinue their plans because its too expensive for them that's why I came up with this solution to give them access to internet for 1-5% of the actual price. This is my solution for now.

Actually, I already have a plan for free internet :-)
I plan to implement this on a span of a year or 2.
For now I am on early releases where I have to choose this approach.
Anyone can actually connect to my fas server where they can customize it how they want it to look.

Thank you
