### ISSUE TITLE
Walled Garden support

### ISSUE THREAD

**Issue by scornieller** [openNDS/openNDS#39]
I would like to suggest recovering the walled garden feature into OpenNDS.

The use case is to allow pre-authenticated users unrestricted access to certain websites for third party validations. These sites are often hosted in CDNs and their public IP changes very frequently so `FirewallRule allow tcp port 443 to <public_ip>` is of no use. Using domains and wildcards instead is ideal.

**Comment by bluewavenet** [comment]
@scornieller 
This functionality is already included in openNDS. It is just missing from the documentation.

From the OpenWrt UCI configuration file:
```
	# Walled Garden
	# Allow preauthenticated users to access an external IP address
	# This is commonly referred to as a Walled Garden.
	# Only IPv4 addresses can be used (not domain names)
	#list preauthenticated_users 'allow tcp port 80 to 112.122.123.124'
	#list preauthenticated_users 'allow udp port 8020 to 112.122.123.124'
	#
	# Alternatively, a preconfigured ipset can be used:
	#list preauthenticated_users 'allow tcp port [port number] ipset [ipset rule name]'
	###########################################################################################

```

This will also apply in the generic opennds.conf file for non-UCI systems - it is just missing from the example file.

Dnsmasq can be set up to dynamically populate the ipset. Depending on the Linux distro you might need dnsmasq-full version.

**Comment by scornieller** [comment]
@bluewavenet It seems that configuration file only allows specific IP addresses and not domain names (which can have many different and varying public IP address for CDNs hosted services).

Am I missing something? is that the Dnsmasq part you are referring to?

**Comment by bluewavenet** [comment]
@scornieller 
Yes, dnsmasq populates the ipset based on domain name(s).

**Comment by bluewavenet** [comment]
@scornieller 
I have updated the OpenWrt config file ( and will do the generic config as well). This will also form the basis for updated documentation. Included in the example is the configuration for Facebook.

```
	# Setting up an automated Walled Garden ipset.
	#
	# This requires the ipset and dnsmasq-full packages
	# Install by running the following commands:
	# opkg update
	# opkg install ipset
	# opkg remove dnsmasq
	# opkg install dnsmasq-full
	#
	# Configure as follows:
	# ipset create openndsset hash:ip
	#
	# Configure dnsmasq:
	# uci add_list dhcp.@dnsmasq[0].ipset='/<fqdn1>/<fqdn2>/<fqdn3>/<fqdn...>/<fqdnN>/openndsset'
	#	where <fqdn1> to <fqdnN> are the fully qualified domain names
	# 	of the URLs you want to use to populate the ipset.
	#	eg. For Facebook use facebook.com and fbcdn.net as fqdn1 and fqdn2
	# uci add_list dhcp.@dnsmasq[0].ipset='/facebook.com/fbcdn.net/openndsset'
	# uci commit dhcp
	#
	# Configure opennds by uncommenting the following two lines:
	#list preauthenticated_users 'allow tcp port 80 ipset openndsset'
	#list preauthenticated_users 'allow tcp port 443 ipset openndsset'

```
I have tested this today to ensure I have the documentation correct ;-)

**Comment by scornieller** [comment]
@bluewavenet thank you, I already tested this and it works perfectly fine! you rock!!

**Comment by bluewavenet** [comment]
@scornieller 
Version 6.0.0 is now released.

**Comment by bluewavenet** [comment]
@scornieller 
Version 7.0.1 is now released and it includes built in Walled Garden, configured by simply in the config file.

This configuration consists of a list of FQDNs an optionally a list of ports. Basically as we did manually earlier but now done automatically.
