### ISSUE TITLE
Status feedback

### ISSUE THREAD

**Issue by musamaGamma** [openNDS/openNDS#391]
I want to keep track of the user status on my remote server, how much did they consume and if they were de authenticated, how can i send feedback to the remote server?

**Comment by bluewavenet** [comment]
@musamaGamma 
This is supported on openNDS v9.9.0 and later, for `option fas_secure_enabled '3'` only.
The example scripts `fas-aes-https.php` and `binauth_log.sh` show how this works.

See:
https://opennds.readthedocs.io/en/stable/libraries.html#send-to-fas-deauthed
and
https://opennds.readthedocs.io/en/stable/libraries.html#send-to-fas-custom

**Comment by musamaGamma** [comment]
aha thank you

**Comment by musamaGamma** [comment]
so u

**Comment by bluewavenet** [comment]
@musamaGamma 
There is nothing stopping you from writing your own binauth script.
By the way, curl is going to be similar in size to php if I remember correctly.
On the other hand, it might be better to upgrade your router as it is pretty much at end of life if it is low in memory.
