### ISSUE TITLE
Why divide by `125` for average speed, `downrate` and `uprate`?

### ISSUE THREAD

**Issue by afriza** [openNDS/openNDS#392]
Hello,

I am wondering why [`125` is used](https://github.com/openNDS/openNDS/search?q=125&type=code) when converting from `bytes` to `kbit/s`.

Thank you

**Comment by bluewavenet** [comment]
@afriza 
A simple bit of algebra.
`k=Bx8/1000`
Simplifying:
`k=B/125`
Where:
k is in kilobits per second
B is in bytes per second
1 byte is 8 bits
1 kilobit is 1000 bits

**Comment by afriza** [comment]
ah.. right.. thanks..

hm.. so.. for data-usage, binary-base KiB is used (1024).. as for speed, Kbps is used..

**Comment by bluewavenet** [comment]
@afriza 

> for speed/rate, decimal-based kbps (kilobit per second) is used

This at first sight might seem counter intuitive, but lets put this into context.
1. openNDS provides "rate limiting" without needing additional dependencies, to keep the footprint as low as possible.
2. openNDS "rate limiting" is more correctly described as "rate limiting threshold", ie a threshold where if exceeded, the client is subject to bandwidth throttling using a hybrid token-bucket/sliding-window algorithm.
3. The original non-open source version of this algorithm was much more complex and consumed many more cpu cycles, but provided a very tight control over the achievable limit.
4. The open-sourced version in openNDS is very much simplified to reduce cpu load on typical router hardware at the expense of a greater short term variation in the achieved rate, while maintaining pretty much the same long term average.

The original code had a dynamically calculated factor used in working out the achieved bitrate, replaced here by the fixed value of 8/1000 (a first order approximation chosen partly for aesthetic reasons to coincide with the decimal based system) as it gives a generally good long term average result for most types of hardware.

>  uploadrate and downloadrate are the maximum allowed data rates

No, these are more correctly described as the threshold above which rate limiting is applied. The token-bucket/sliding-window algorithm allows short term bursting at full network rates (this gives a good user experience with little effect on other users). If a client is continuously streaming for example, the average rate will always exceed the configured rate, but converge on the set value in a time determined by configuration values controlled by such things as the max-bucket size, bucket ratio and rate-check-window (the default values are chosen to give generally good performance).

**Comment by bluewavenet** [comment]
@afriza 
As we saw earlier, it is the code in auth.c that calculates the average rates for a client and this calculation is a first order approximation of a very much more complicated algorithm. This approximation gives good results whilst saving a significant cpu load.
The actual value of 125 is a result of the deliberate use of the 1000 value in the calculation. Without the first order approximation, this value varies according to many factors in a bell curve fashion with a 2xsigma spread, the width and mean value dependent mostly on the hardware. For typical low cost domestic routers this is around 980 to 1020

The code in fw_iptables.c is setting up the token-bucket filters. Here we are calculating the packet rate. We do not want to apply approximations here.

**Comment by bluewavenet** [comment]
@afriza 
Your in depth study of the openNDS code is appreciated. All comments, feedback, PRs are welcome.
