### ISSUE TITLE
How to make it work in bridge mode

### ISSUE THREAD

**Issue by lanhtao** [openNDS/openNDS#394]
My device only have br interface, and it access www web site by br interface.   Now the client from br interface will not block without logging. Does the opennds can work in this kind of env.

**Comment by bluewavenet** [comment]
@lanhtao 
It is not very clear what you are asking, but I assume that as you only have a bridge interface, openNDS will refuse to start, logging an error in syslog as it MUST run on a device configured as an IPv4 router.

See the documentation:
https://opennds.readthedocs.io/en/stable/howitworks.html#how-opennds-nds-works

**Comment by lanhtao** [comment]
@bluewavenet
The device network topology is described below：
I deploy opennds on device A.The eth1, eth2, eth3, wlan0 NIC is bound to br0 on device A. My phone connects to the device A via wlan0.The device A is connected to another router through eth1, and that router can access the Wide Area Network.Is my topology not supported?

When my phone is connected, it will pop up the OpenNDS authentication page. Even though I am not logged in, my phone still has access to the Wide Area Network.

**Comment by bluewavenet** [comment]
@lanhtao 

> Is my topology not supported?

As I said in my first reply - No, bridge mode is not supported.
**I will repeat - openNDS MUST run on a device configured as an IPv4 router.**

What operating system/version and hardware are you using?
What version of openNDS are you using?

openNDS should refuse to start with what you say is your configuration.
Can you share the openNDS config and the output of `ifconfig`?

**Comment by lanhtao** [comment]
@bluewavenet, Thanks for your reply.

Version: 9.8.0
system: mipse Arch,  Linux 3.18.21
opennds.conf:
GatewayInterface br

FirewallRuleSet authenticated-users {
  FirewallRule allow all
}

FirewallRuleSet preauthenticated-users {
}


FirewallRuleSet users-to-router {
    FirewallRule allow udp port 53
    FirewallRule allow tcp port 53
    FirewallRule allow udp port 67
   FirewallRule allow tcp port 22
   FirewallRule allow tcp port 80
   FirewallRule allow tcp port 443
}

ifconfig:

br0       Link encap:Ethernet  HWaddr 3C:EE:85:E4:13:14
          inet addr:30.30.30.3  Bcast:30.30.30.255  Mask:255.255.255.0
          inet6 addr: fe80::1/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:88195 errors:0 dropped:2 overruns:0 frame:0
          TX packets:88399 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0
          RX bytes:11134841 (10.6 MiB)  TX bytes:52188696 (49.7 MiB)

eth0.1    Link encap:Ethernet  HWaddr 3C:EE:85:E4:13:11
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:23963 errors:0 dropped:4 overruns:0 frame:0
          TX packets:24681 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000
          RX bytes:20765268 (19.8 MiB)  TX bytes:4607876 (4.3 MiB)

eth0.2    Link encap:Ethernet  HWaddr 3C:EE:85:E4:13:12
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:25789 errors:0 dropped:3 overruns:0 frame:0
          TX packets:35696 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000
          RX bytes:2477695 (2.3 MiB)  TX bytes:36782242 (35.0 MiB)

eth0.3    Link encap:Ethernet  HWaddr 3C:EE:85:E4:13:13
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:0 errors:0 dropped:0 overruns:0 frame:0
          TX packets:0 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000
          RX bytes:0 (0.0 B)  TX bytes:0 (0.0 B)

ra0       Link encap:Ethernet  HWaddr 3C:EF:84:F2:23:02
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:88596 errors:627 dropped:0 overruns:0 frame:0
          TX packets:72430 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000
          RX bytes:14501531 (13.8 MiB)  TX bytes:35164681 (33.5 MiB)
          Interrupt:20

rai0      Link encap:Ethernet  HWaddr 3E:EF:84:F2:23:02
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:653 errors:0 dropped:0 overruns:0 frame:0
          TX packets:528 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000
          RX bytes:77675 (75.8 KiB)  TX bytes:289480 (282.6 KiB)

~ # brctl show
bridge name     bridge id               STP enabled     interfaces
br0             8000.3cee85e41314       no              ra0
                                                        rai0
                                                        eth0.1
                                                        eth0.2
                                                        eth0.3

**Comment by bluewavenet** [comment]
@lanhtao 
I have formatted your post. Please use the <> symbol in the top line of the text box you are typing in to correctly see pre-formatted text like command outputs and code.

You have not stated what the hardware actually is, nor what the Linux distro is.

There are various things wrong with your configs.

1. 30.30.30.3 is an invalid ip address to use for a private lan as it does not conform to rfc 1918. It will probably work but will at the very least block genuine Internet addresses in the 30.30.30.x range so should not be used.
2. openNDS must be running on a router with the following conditions:
    * it must have its own rfc1918 private ipv4 subnet for its nat lan
    * it must be the default ipv4 gateway for the lan
    * it  must be providing dhcp ip addresses for the lan
    * it must be providing dns services for the lan
    * it must have a wan port that has upstream links to an Internet stream
3. Your kernel version is 3.18.21. This is very outdated and not supported. It might work ... or might not. You should upgrade to at least kernel version 5.x for full support of openNDS
4. The current version of openNDS is 9.9.0, you should upgrade from 9.8.0
5. If you were to configure as a router (as in 2 above) then note:
    * `fasport 0` is invalid. If you do not want to specify fasport, leave it out of the config
    * `GatewayInterface br` is invalid, there is no such interface as `br`
    * `gatewayfqdn disable` will prevent rfc8910/8908 CPI from functioning, forcing legacy CPD on client devices and is not recommended.

Given your current config, openNDS should not even start. If it is starting, it is maybe due to the ancient kernel version you are using.

You can check its status by running:
`sudo ndsctl status`

Try running:
`sudo systemctl restart opennds`

followed by:
`sudo systemctl status opennds`

and for more detail:
`sudo journalctl -e`

**Comment by bluewavenet** [comment]
@lanhtao 
The simple answer is, in bridge mode, no captive portal that supports the industry standard CPD and CPI methods will work.

**Comment by lanhtao** [comment]
OK, Thanks.
