### ISSUE TITLE
Unable to Set Manual Walled Garden for TCP port 80 (default unencrypted HTTP port)

### ISSUE THREAD

**Issue by afriza** [openNDS/openNDS#396]
Hello,

From my testing, removing lines 514-515 in commit 312c779d3e0b30c6805d3662a8efce1844b0b263 has a side effect which prevents plain-HTTP Manual Walled Garden from working:

https://github.com/openNDS/openNDS/blob/7e7837f01eab79374fc5e67a360754592404aea5/linux_openwrt/opennds/files/etc/config/opennds#L780-L782

https://github.com/openNDS/openNDS/blob/7e7837f01eab79374fc5e67a360754592404aea5/docs/source/config.rst#L1109-L1111

I'm not sure how to workaround this other than running `iptables` directly after openNDS is running.

**Comment by bluewavenet** [comment]
@afriza 
I don't think this is a regression. For most Internet hosted web servers (ie shared hosting and/or CDN), you cannot access the intended web pages by ip address, you must use an FQDN.
What type of hosting are you using?

**Comment by afriza** [comment]
I believe the problem is not related to FQDN.. FQDN will later be resolved into IP anyway after DNS resolution & firewall rules check the IP & port not the FQDN..

If what you mean is "most websites are using secure HTTPS", then yes.. This only happens for plaintext HTTP..

```
*nat
:PREROUTING ACCEPT [0:0]
:INPUT ACCEPT [0:0]
:OUTPUT ACCEPT [0:0]
:POSTROUTING ACCEPT [0:0]
:ndsOUT - [0:0]
ACCEPT
-A PREROUTING -i br-lan -j ndsOUT
-A ndsOUT -p tcp -m tcp --dport 443 -m set --match-set walledgarden dst -j ACCEPT
-A ndsOUT -m mark --mark 0x20000/0x30000 -j RETURN
-A ndsOUT -m mark --mark 0x30000/0x30000 -j RETURN
-A ndsOUT -p tcp -m tcp --dport 80 -j DNAT --to-destination 192.168.1.1:2050
-A ndsOUT -j ACCEPT
COMMIT
```

The problem is because plain HTTP traffics stop at `-j DNAT --to-destination` and are not going to the `ndsNET` chain.

**Comment by bluewavenet** [comment]
@afriza 

> If what you mean is "most websites are using secure HTTPS", then yes..

No, that is not what I mean.
For example, a typical Internet hosted web server will be supporting many web sites all on the same ip address, and a CDN network will expand this to many ip addresses.
So to access a specific web site on a shared server, you must specify the fqdn as part of the url, otherwise the web server will not know which web site to serve. At best you might get an error message but more often than not you get nothing.
This applies to both http and https (ports 80 and 443) as it is of course a function of the web server rather than the protocol.

> Or.. Do you mean "Autonomous Walled Garden" is preferred and I should use it instead (by specifying FQDN & ports) ?

Yes. You need a self populating ipset. This is handled automatically by the openNDS "Autonomous Walled Garden"

**Comment by afriza** [comment]
Then, if you are okay with it, I'll make a PR removing http port 80 manual walled garden example & mentioning autonomous walled garden as required for plain http.

**Comment by bluewavenet** [comment]
@afriza 
Sorry but there is nothing wrong with it. I just tested with a web server I have running on a **_dedicated_** VPS and it works just fine.
You only need the autonomous walled garden if the web site you are trying to access is running on a shared web server or a CDN where the web site is not unique to an ip address.

If you understand why this is happening with your tests, you will see that a PR adding an additional comment would be useful.

**Comment by afriza** [comment]
@bluewavenet 
> I just tested with a web server I have running on a **_dedicated_** VPS and it works just fine.

Did you test plain HTTP with _**Manual** Walled Garden_ or  with _**Autonomous** Walled Garden_ ?

I tested with `curl 192.184.95.211/test` and `curl rn1.simpan.in/test`

From within OpenWrt
```console
# uci get opennds.@opennds[0].preauthenticated_users
'allow tcp port 80 to 192.184.95.211' 'allow udp port [redacted] to [redacted]'
# curl 192.184.95.211/test
plaintext HTTP
```

From a machine connected to `br-lan`:
```console
$ curl rn1.simpan.in/test -v
*   Trying 192.184.95.211...
* TCP_NODELAY set
* Connected to rn1.simpan.in (192.184.95.211) port 80 (#0)
> GET /test HTTP/1.1
> Host: rn1.simpan.in
> User-Agent: curl/7.64.1
> Accept: */*
>
< HTTP/1.1 307 Temporary Redirect
< Date: Thu, 03 Nov 2022 01:38:57 GMT
< Connection: close
< Location: http://192.168.1.1:2050/opennds_preauth/?fas=[redacted]
< Content-Length: 1339
<
* Closing connection 0
<html><head></head><body><a href='http://192.168.1.1:2050/opennds_preauth/?fas=[redacted]'>Click here to continue to<br>http://192.168.1.1:2050/opennds_preauth/?fas=[redacted]</a></body></html>
```

**Comment by afriza** [comment]
@bluewavenet 

Here are my [proposed changes](https://github.com/openNDS/openNDS/compare/master...afriza:manual-wg-no-http?diff=split)

**Comment by bluewavenet** [comment]
@afriza 
Sorry, I reread your posts and found I was confused by your phrase "plain http".
My confusion is compounded by your test web site `http://rn1.simpan.in/test` at it outputs the text string `plaintext HTTP`
You obviously mean "http unencrypted protocol on default port 80"

Port 80 is reserved for captive portal detection (CPD) so is not supported in the "manual" walled garden.
Yes it would be possible to reinstate this support for external web sites, but this is an unnecessary complication for something that should probably never be used for security reasons.
In your example you should use https on default port 443.
As you are aware, if you really need to use port 80, the the "autonomous walled garden" approach is available.

Yes, you are correct, the documentation needs to be updated.

As an aside:
`uci set opennds.@opennds[0].walledgarden_ip_list='192.184.95.211 1.1.1.1'`

Are you intending giving preauthenticated clients access to external DNS services (1.1.1.1)?

If you do this, any clients using the external DNS will fail rfc8910 and rfc8908 CPI and may well fail to see the login page.

**Comment by afriza** [comment]
> Are you intending giving preauthenticated clients access to external DNS services (1.1.1.1)?

Sorry.. that was not my intention.. I actually wanted to show that it is separated by space just like the fqdn version.. I just had no IP on mind to type and just typed 1.1.1.1 forgotting the consequences on DNS-stuff..

**Comment by bluewavenet** [comment]
@afriza 
I updated the title again - it is not a regression, it is intended.

Thanks for your obviously in depth investigations, much appreciated. 
Please submit your PR for the documentation updates and I will review.

**Comment by bluewavenet** [comment]
@afriza 

> and by allowing only port 443, oftentimes the browser is too smart and show the portal instead.

But that is the whole point of the captive portal.

If you want preautenticated users to access an external web site before logging in, provide a button or similar on the login page.

**Comment by bluewavenet** [comment]
@afriza 
Latest docs:
https://opennds.readthedocs.io/en/latest/config.html#manual-walled-garden-configuration
