### ISSUE TITLE
Captive portal suddenly closes on ios 16

### ISSUE THREAD

**Issue by musamaGamma** [openNDS/openNDS#405]
I have opennds running with fas level one on a remote server. It works fine on android devices but on iPhones with ios 16 the portal closes as soon as it opens. It also says the network is unsecured

**Comment by bluewavenet** [comment]
@musamaGamma 
Do you mean the portal closes before people can log in, or do you mean it closes immediately after login?

If the device is set to https only, be it ios or android, the portal will either not open at all or will pop up and immediately go away.

On Android this is enabled in Chrome browser, and in ios it is a setup option (should default to off). On either, if enabled this will block access to all captive portals as it defeats the captive portal detection.

> fas level one [.....] It [..] says the network is unsecured

Yes. Fas level 1 is insecure. That is why fas level 3 is recommended unless your router is very resource constrained.

**Comment by musamaGamma** [comment]
the wifi itself closes before the user can do anything and connects again and closes again

**Comment by bluewavenet** [comment]
@musamaGamma 

> connects again and closes again

This _can_ happen with any device with CPD. The answer is to manually select the required SSID and not rely on the device connecting to an SSID it knows about.
Whether this is what you are seeing or not, I do not know, but if what I suggested works, then it is.

**Comment by scornieller** [comment]
> I have opennds running with fas level one on a remote server. It works fine on android devices but on iPhones with ios 16 the portal closes as soon as it opens. It also says the network is unsecured

Verified it is working on iOS 16 without issues.
Forget the network, try connecting again, else, use another iOS device and verify.
iOS would tell insecure network to all SSIDs that are open (no WPA security), it is a feature not a bug.
