### ISSUE TITLE
I'm not eable to get remote FAS working

### ISSUE THREAD

**Issue by carriopablo** [openNDS/openNDS#406]
I'm not eable to get remote FAS working with openNDS. It is working as expected with `login_option_enabled='1'` showing the Splash Page with the continue button, and after hitting it I gain internet access. But if I set `login_option_enabled='0'` the client connects to internet after a while without requesting anything (No captive portal). No mater what FAS options I set.

The FAS PHP files has been copied from the repo to my server in the path `/fas`.

Could it be a problem with OpenWRT 22?

My device:
`Arch - Qualcomm Atheros QCA956X`
`OpenWrt - 22.03.2 r19803-9a599fee93`
`opennds - 9.9.0-1`
`libmicrohttpd-ssl - 0.9.75-1`

My config file `uci show opennds`

```
opennds.@opennds[0]=opennds
opennds.@opennds[0].enabled='1'
opennds.@opennds[0].fwhook_enabled='1'
opennds.@opennds[0].gatewayinterface='br-guest'
opennds.@opennds[0].maxclients='250'
opennds.@opennds[0].fasport='443'
opennds.@opennds[0].fasremotefqdn='stylecre.es'
opennds.@opennds[0].fasremoteip='51.83.52.212'
opennds.@opennds[0].faspath='/fas/fas-aes-https.php'
opennds.@opennds[0].faskey='1234567890'
opennds.@opennds[0].fas_secure_enabled='3'
opennds.@opennds[0].users_to_router='allow tcp port 53' 'allow udp port 53' 'allow udp port 67' 'allow tcp port 22' 'allow tcp port 80' 'allow tcp port 443'
```

Thanks in advance

**Comment by bluewavenet** [comment]
@carriopablo 

> Could it be a problem with OpenWRT 22?

No. It is most likely your installation/config.

Did you read the documentation?
https://opennds.readthedocs.io/en/latest/fas.html#example-script-file-fas-aes-https-php

What does the system log say?
Show the output of:
```
system opennds restart
logread -e opennds | tail -n 60
```

**Comment by carriopablo** [comment]
Okey, it seem that it isn't working with AES FAS since I forgot to `Install the packages php8-cli and php8-mod-openssl` the fas_secure_enabled = 1 is working.

I'll intall the packages and try the AES FAS again.

Thaks! I'll post the result ASAP

**Comment by carriopablo** [comment]
Okey, after installing `php8-cli and php8-mod-openssl` as explained in documentation [https://opennds.readthedocs.io/en/latest/fas.html#example-script-file-fas-aes-https-php](https://opennds.readthedocs.io/en/latest/fas.html#example-script-file-fas-aes-https-php) it works.

@bluewavenet Thakyou so much for the quick replay.
