### ISSUE TITLE
annoying  awk error

### ISSUE THREAD

**Issue by solsticedhiver** [openNDS/openNDS#409]
Compiled on an archlinux distro, running opennds or ndsctl throws a lot of line like:

    awk: cmd. line 1: warning: escpae sequence `\%` treated as plain `%`

This is fixed by changing line 600 of `openNDS-9.9.1/forward_authentication_service/libs/libopennds.sh` to

     urlencoded=$(echo "$buffer" | awk '{ gsub(/\$/, "%24"); print }'

**Comment by bluewavenet** [comment]
@solsticedhiver 
Thanks for pointing this out. In testing it does not seem to occur in OpenWrt, Opensuse or Debian, so the error reporting is most likely dependent on the version of awk included with the distro.

However on looking closely at the code, line 600 is for special handling of the "$" symbol in (b)ash.

For example, in OpenWrt:
`/usr/lib/opennds/libopennds.sh urlencode "hello$world"`
gives the result `hello`, as would be expected as (b)ash expects `$world` to be a variable.

Now if we try:
`/usr/lib/opennds/libopennds.sh urlencode "hello\$world"`
we get `hello%24world`

Now if we decode:
`/usr/lib/opennds/libopennds.sh urldecode "hello%24world"`
we get `hello$world`, but this is not the same string we encoded!
The returned string should have been `hello\$world`.

Line 600 should actually be:
`	urlencoded=$(echo "$buffer" | awk '{ gsub(/\$/, "\\%24"); print }')`

This gives the correct result of `hello\%24world` in OpwnWrt and OpenSuse. I don't have access to a Debian machine at the moment to test but expect it to work there also.

The big question is, does this work for you in your archlinux distro?

**Comment by solsticedhiver** [comment]
There are still errors in other cases. I had to make more changes. But I am not sure this is right.

I would suggest you to install a VM with whatever you want like Virtuallbox or gnome-boxes to make your tests. That should take you 5 minutes.

If you want to test an archlinux like system, you could install a manjaro which is quicker done that a tradionnal archlinux;

**Comment by bluewavenet** [comment]
@solsticedhiver 

> There are still errors in other cases. I had to make more changes.

It would be useful if you were more specific. I don't see any errors at all.

> I would suggest you to install a VM with whatever you want like Virtuallbox or gnome-boxes to make your tests. 

Yes that is a useful test environment, but I do not see any errors and no one else has reported any, so I do not see the need to do any such testing.
If the repo you are using is giving _you_ problems, then it is up to you to do your own testing and report errors properly.

> If you want to test an archlinux like system

To be honest, I can't see why I would want to. It is up to the community to test on diverse operating systems if they feel the need and report problems and proposed fixes if they find them.

**Comment by solsticedhiver** [comment]
They were more errors again with the same message about awk and escape
character. I had to change all the awk line with gsub to remove any errors.
Those new errors appeared while I was running your test command, whereas I
was simply running `ndsctl status` previously.

Archlinux just uses a standard *awk* while openwrt is using something like
busybox

**Comment by bluewavenet** [comment]
@solsticedhiver 
Yes, by default, OpenWrt uses the Busybox awk, but it has the option of the "standard" version. Neither of these give the errors you describe. Neither do the versions found in OpenSuse and Debian. This implies the problem lies with the version found in Archlinux....

But if you had read my comment, you would see:

> Line 600 should actually be:
> `urlencoded=$(echo "$buffer" | awk '{ gsub(/\$/, "\\%24"); print }')`

**Comment by solsticedhiver** [comment]
I did see your comment about line 600. And use your change. That's not the problem.

debian bulleye is using gnu awk 5.1.0. opensuse Leap 15.4 is using 5.1.1 while tumbleweed is using 5.2.0

So if changes have been introduce in the major version 5.2.0 of awk, you could except to see new errors, aren't you?

Moreover, I have run your test commands in debian bullseye, and I got:
```
$ ./usr/lib/opennds/libopennds.sh urlencode hello$world
hello
$ ./usr/lib/opennds/libopennds.sh urlencode hello\$world
hello\%24world
$ ./usr/lib/opennds/libopennds.sh urldecode "hello%24world"
hello\$world
```

They were no errors, but do note that 2nd line is not giving what you except aka. `hello\%24world` instead of `hello%24world`
This is the script libopennds.sh unmodified. Your patch changes nothing here.

So with archlinux, if I run the script with the line 600 changed, I got:
```
$ ./usr/lib/opennds/libopennds.sh urlencode hello$world ;echo
hello
$ ./usr/lib/opennds/libopennds.sh urlencode hello\$world ;echo
hello\%24world
$ ./usr/lib/opennds/libopennds.sh urldecode hello%24world ;echo
awk: cmd. line:1: warning: regexp escape sequence `\%' is not a known regexp operator
awk: cmd. line:1: warning: escape sequence `\$' treated as plain `$'
awk: cmd. line:1: warning: regexp escape sequence `\%' is not a known regexp operator
hello$world
```
So more error mesages, and the second line seems to be wrong now, like in debian.

I will **NOT** continue to help you debug your script in this github issue (this is not meant for that).
If you don't want to run and test and fix your s.... then be it

**Comment by solsticedhiver** [comment]
And if you don't like VMs, you can use containers. The tech available are almost limitless nowadays ,beggining with docker, systemd-nspawn etc ....

**Comment by bluewavenet** [comment]
@solsticedhiver 

> I will NOT continue to help you debug your script in this github issue (this is not meant for that).
> If you don't want to run and test and fix your s.... then be it

It is you that has a problem.

Thanks to your initial comment, it came to light that there was a typo on line 600 where a `\` character had been missed out.

The errors you seem to be getting can not, as far as I can see, be reproduced, except in your specific environment. In addition no such problem has been reported by anyone else.

Until further reports are received, nothing will be done, instead it will be noted as a possible future problem.

Running openNDS on Arch Linux is very much an edge case, but nevertheless valid.
However, in response to your comment - I will NOT continue to help you debug your s... environment.

**Comment by sicelo** [comment]
Debian Bookworm/Sid, with GNU Awk 5.1.0, API: 3.0 (GNU MPFR 4.1.0, GNU MP 6.2.1)

```
sicelo@tpt440p:~/Git/openNDS/forward_authentication_service/libs$  git diff
diff --git a/forward_authentication_service/libs/libopennds.sh b/forward_authentication_service/libs/libopennds.sh
index 031a7b1..46e419a 100755
--- a/forward_authentication_service/libs/libopennds.sh
+++ b/forward_authentication_service/libs/libopennds.sh
@@ -597,7 +597,8 @@ urlencode() {
                buffer=$urlencoded
        done
 
-       urlencoded=$(echo "$buffer" | awk '{ gsub(/\$/, "\%24"); print }')
+       #urlencoded=$(echo "$buffer" | awk '{ gsub(/\$/, "\%24"); print }')
+        urlencoded=$(echo "$buffer" | awk '{ gsub(/\$/, "\\%24"); print }')
 }
 
 urldecode() {


sicelo@tpt440p:~/Git/openNDS/forward_authentication_service/libs$  ./libopennds.sh urlencode "hello$world"
hello


sicelo@tpt440p:~/Git/openNDS/forward_authentication_service/libs$  ./libopennds.sh urlencode "hello\$world"
hello\%24world


sicelo@tpt440p:~/Git/openNDS/forward_authentication_service/libs$  ./libopennds.sh urldecode "hello%24world"
awk: cmd. line:1: warning: regexp escape sequence `\%' is not a known regexp operator
awk: cmd. line:1: warning: escape sequence `\$' treated as plain `$'
awk: cmd. line:1: warning: regexp escape sequence `\%' is not a known regexp operator
hello$world
```

**Comment by bluewavenet** [comment]
@sicelo 
Excellent thankyou. I see the problem.

Try this:
```
urldecode() {
	entitylist="
		s/%22/\"/g
		s/%3E/>/g
		s/%3C/</g
		s/%27/'/g
		s/%60/\`/g
		s/%25/%/g
	"
	local buffer="$1"

	for entity in $entitylist; do
		urldecoded=$(echo "$buffer" | sed "$entity")
		buffer=$urldecoded
	done

	buffer=$(echo "$buffer" | awk '{ gsub(/%24/, "$"); print }')
	urldecoded=$(echo "$buffer" | awk '{ gsub(/%20/, " "); print }')
}

```

**Comment by sicelo** [comment]
Error gone,

```
sicelo@tpt440p:~/Git/openNDS/forward_authentication_service/libs$  git diff
diff --git a/forward_authentication_service/libs/libopennds.sh b/forward_authentication_service/libs/libopennds.sh
index 031a7b1..66db623 100755
--- a/forward_authentication_service/libs/libopennds.sh
+++ b/forward_authentication_service/libs/libopennds.sh
@@ -597,7 +597,7 @@ urlencode() {
                buffer=$urlencoded
        done
 
-       urlencoded=$(echo "$buffer" | awk '{ gsub(/\$/, "\%24"); print }')
+        urlencoded=$(echo "$buffer" | awk '{ gsub(/\$/, "\\%24"); print }')
 }
 
 urldecode() {
@@ -616,11 +616,10 @@ urldecode() {
                buffer=$urldecoded
        done
 
-       buffer=$(echo "$buffer" | awk '{ gsub(/\%24/, "\$"); print }')
-       urldecoded=$(echo "$buffer" | awk '{ gsub(/\%20/, " "); print }')
+       buffer=$(echo "$buffer" | awk '{ gsub(/%24/, "$"); print }')
+       urldecoded=$(echo "$buffer" | awk '{ gsub(/%20/, " "); print }')
 }
 
-
 htmlentityencode() {
        entitylist="
                s/\"/\&quot;/g


sicelo@tpt440p:~/Git/openNDS/forward_authentication_service/libs$   ./libopennds.sh urldecode "hello%24world" 
hello$world
```

**Comment by bluewavenet** [comment]
@sicelo 

> Error gone

Superb! I will push this into 9.9.2beta.
