### ISSUE TITLE
Set param for authentication FAS

### ISSUE THREAD

**Issue by matsumotoa285** [openNDS/openNDS#41]
When use FAS, how to set duration time, upload rate, download rate, upload quota, download quota etc...? I can't find it on document.
I use FAS with secure level 1 wit fas-hid.php and with out php-cli package.
And what is the "Custom string to binauth". Is command to authentication client with custom param? Like `ndsctl_auth 30 0 0 0 0` ?

**Comment by bluewavenet** [comment]
@matsumotoa285 

> how to set duration time, upload rate, download rate, upload quota, download quota
 
I agree with you that the documentation on this subject needs improvement and this post has given me a timely reminder to update the documentation for the upcoming release of v6.0.0 ;-)

These parameters are all set globally in the config file.
https://opennds.readthedocs.io/en/stable/traffic.html

On a client by client basis it is done using either ndsctl auth or binauth. It is in this area the documentation is lacking.
I will describe it in more detail here and incorporate into the revised documentation.

> And what is the "Custom string to binauth"

Same problem with documentation...

**Comment by bluewavenet** [comment]
@matsumotoa285 
Did you get it working?
FYI Release 6.0.0 is now available.
