### ISSUE TITLE
libopennds.sh error reading configuration parameters

### ISSUE THREAD

**Issue by xes** [openNDS/openNDS#411]
Using opennds with a standard linux, it seems that the following line of libopendns.sh extracts erratic information from /etc/opennds/opennds.conf reading random information also from commented lines.

param=$(cat "/etc/opennds/opennds.conf" | awk -F"$option " '{printf("%s", $2)}')

**Comment by bluewavenet** [comment]
@xes 
You will have to be more specific with what you are trying to do, as I cannot replicate this here.

Note also that the generic opennds.conf configuration file should be considered as deprecated and will be removed in the upcoming openNDS v10, being replaced by a uci config format file as used in OpenWrt (see the file `/etc/opennds/opennds.uci`).

**Comment by xes** [comment]
@bluewavenet 
I'm running opennds inside a centos box that acts as gateway for a pretty wide mesh network.
If you try to run that shell command against a standard .conf file it is impossible that it could produce the expected output

With next v10, does it will be possible to use OpenNFS with a standard linux "non-openwrt"?

**Comment by bluewavenet** [comment]
@xes 

> I'm running opennds inside a centos box

I'm running openNDS on an OpenSuse box that is acting as the gateway on a large multi site corporate network and it works just fine.

Under what circumstances do you get this issue?
Are you using the `get-option-from-config` library call?
See:
https://opennds.readthedocs.io/en/stable/libraries.html#get-option-from-config

**Comment by xes** [comment]
I discovered it looking at the systemd journal messages, i found an error since that call was extracting part of a comment: 
in /etc/opennds/opennds.conf
"# Option faskey must be pre-shared with FAS."

2022-11-25 09:50:51 localhost opennds opennds[51720]:  /usr/lib/opennds/libopennds.sh: row 911: be: command not found
(i suppose it was searching for faskey)

I replaced the line with:
param=$(cat "/etc/opennds/opennds.conf" | grep -v ^"#" | grep "$option" | awk '{ print $2 }' )

**Comment by bluewavenet** [comment]
@xes 
This will not be fixed as the entire .conf file will be replaced in the upcoming v10 release.
Workarounds for the v9 release include the script edit mentioned above, or removing all comments from the default .conf file.

**Comment by xes** [comment]
@bluewavenet 
do you think to manage the configuration using only uci?

**Comment by bluewavenet** [comment]
@xes 
Currently there are two config file formats, the OpenWrt UCI format and the unique openNDS .conf format used in generic Linux.
It is planned to rationalise this and make openNDS read the uci style format directly in all cases.

In the case of generic Linux, the configuration will be carried out by editing the common uci format file, whereas under OpenWrt, the configuration can be achieved in the same way by directly editing the file or alternatively by using the uci utility that is part of OpenWrt.
