### ISSUE TITLE
Authentication from FAS Fails

### ISSUE THREAD

**Issue by reevester** [openNDS/openNDS#413]
Hello,

Summary: My router successfully opens the FAS page but after authentication, the browser is redirected to 

`http://opennds_auth/?tok=fde7c20c7e35b36811472ed2c3f74b92dd9e6de80edbd76b4ac13074d49a6324&custom=ZnVsbG5hbWU9UmVldmUgTHVpeiwgZW1haWw9UmVldmVsdWl6QGdtYWlsLmNvbQ%3D%3D&redir=http%3A%2F%2Fcloud.waaniwifi.com%2Fmonitor%2Ffas-hid.php%3Ffas%3DdzJRM2NndVlGNHg1QzhpUlh6MVBsSm5CZ24yYVF0ZlNVSS9SMHBFMENPcXMwWkFBL25DZURoTzVoOUVjd0pCSGx6SkZFMGw4V29hdWdFNm84ZG5vYU1Wd2t1TDdMaktsREdTWHdsT2VMdFhpd1JEMlhLY1hCZG9TSjB1cWJiRHY1ZDk0QkR4RDVoc1pKWXErbjhnblRPQ3ZraHlVSE1CdmF6M1d6bXRqWjIyUmNLTkRaaHpwVnYvc293UDI4Q0lRL01zdVhSeHpsTS9QS2szeldNY0ZTL2pNM1RnbFZVWGZzSVBQUjVpWDVzc0pZc3E4OVkwS2l6dzdCemZvNko4eUlRSy82cTJpUEJOaitjb2dKOHgvcDVQNXlJUWNUWE5pK2VWLzE1QVJHbHVBODZQUHEwT1ZlRFRLSCswbjQ0QTYwUnBZVjRKK1B5QlBYZDA4WjJqQmdJMDI3QWtnOU9HaWs4SEhDZzdnTndtSkowSjk0WlBDcVhDSXgxSUhOemlQb3hOZnExVkllcEtyaWtvclloK2xTdVVBWFp0WEZVeHNKeHVOTkpJNmpGeWlyRHdobUFnZXNibzMwTGhaVm9oL1pDV21wZGNwYjdFcHFOZkVJNko3QUhzSDIyWVFtbEtOVzQ2WXdIS0I5Y3hReGE2b0V1SWZqaGNMVjlqQ0xyRU9LSEtXMFJmczU0ZnNXRnZUbXhGdERiczJUS0crV0VCcnd6aVJOTWdSK1krQm1YQzRTa01IZVNWVkxxYUUzazVhdnVYRXB3UlhUR1VHMmNkMzRRY2VDQ1F2T0dFUEJhNzUzamNSR0JRME43b3B2enNQbW9UanhFSUtXQzNpRFc0TVVXUW9TOUJnVDRaTFRxODBjRk54UkZuMFIyVEJMMGhKN3RxakVHc3RLbWNiS2I1b0pMd2FycHBDRnJPakwvSEpTYU5CZkx3b2k0QUd4dDFXK2VacG1HcGN1aXJLSGtZK3RXOU1SZWxsaG81d0ZOZldBeUMwVW1yeE9pamVnQnYrNW1JZml4dUpDSXJTenhTUWxVVVNsd3VmaXBJbEMwUzNwNkxvbXB2eVQxeDI0UVRmdTN1U2NPbDNQdXpjVGhjdi9yUzltcUwzRFBwYjZJdHdoeDAwQmhVSllMdnd4cnIwQWNXWDZhS1h1TGd5TGVOV1NmekVXcm9aWEpmZnlXdDhHUUZoTGxaWlVWNlRhS1VSenZjRTk3dDJranVZNDArZy9jU2k4d3YvT2RnZ2dxMktLUWtLeUE3YTlhWjIzYXpNRlpVRlNtOG9Namwyc3dQUFZpa2hURmlJaUdSUE5PV1FNRWVNYWl5V0sydmg0ODlQMGIwMlpEeWtSc1RTSE9kUEo5cmlKQUErWW9NeDdwTGVyRTNxOWxnUHI1bUkzM0lCcElCN2JwM2k5a3NBNjZlUWhnenpKZ1UxOGxxL0gzUkljREJOaDZWazRFUFJhcGNTNndlREJmSVhacHdlWnhhbFBCdncxVG8vOXk5Z1hlcUMwY2xvZEhOZy9JV2NDb29ySDE1MWlmdmJSQWp6bFc5K0IwL0FNL2Eyd3JFRSt4ZC9yRDJ4NDNYT3kzalBtV3RlcjJUSVlCd3kyMjRndFNhMmxCUXJUbVVERSsvNnNValJGajIxS1JkN254Uk9JTFg4Mjc4T04ycHdKU1FiOUFMMmdJTGVvYkx5VFg5UmR6WThWRXo0d09UZ21iZ0hzek51UkZ4OE4zL3JtTWJLWnJDSThUN3F5RGV1eTlPRTNXMEZZa0F4TmlQVll3OU5yMXpubmJheHlxbDY4cStBc01rS0dOZXhiMTk3eU1IM2ZoLzhLNDdRVnVJSjBqTW4wS2pYYzJEVHV2VWZQQ3dwYzRBREdtZmxUanJBOUs3WlJGU2FSNENpNTQ1dVk5WVRIRkRKZkJwQzVWR1BuUnptUS9IQjk2MmFQWHBiMk1rWGU1QjJDUjN1MHJZclk0NzFhZmVWUytqMGVVRk9qRXFMRUkxdU51dzhFcTJRYURrWWFnZkNTTmtUOUpaRjRzczdtSW91Y0Frd1M2WlVZSzB4U0h1cGV6WlJCOUowY2x0d1dkS3BoanNtcFRtVkh4UDY3N2loWTRpT004RDVhODRucHlzb2NPV2RKL1VkVlNXb0tlZjQ2UHlLMkE9PQ%3D%3D%26landing%3D1`

and it gives an error saying "This site cannot be reached". I am using the sample fas-hid.php with fas_secure = 1

Here is my OpenNDS Setup:

`opennds.@opennds[0]=opennds
opennds.@opennds[0].enabled='1'
opennds.@opennds[0].fwhook_enabled='1'
opennds.@opennds[0].allow_preemptive_authentication='0'
opennds.@opennds[0].enable_serial_number_suffix='0'
opennds.@opennds[0].maxclients='250'
opennds.@opennds[0].fasport='80'
opennds.@opennds[0].fasremotefqdn='cloud.waaniwifi.com'
opennds.@opennds[0].fasremoteip='34.207.159.128'
opennds.@opennds[0].faspath='/monitor/fas-hid.php'
opennds.@opennds[0].fas_secure_enabled='1'
opennds.@opennds[0].walledgarden_fqdn_list='waaniwifi.com google.com cloud.waaniwifi.com'
opennds.@opennds[0].users_to_router='allow tcp port 53' 'allow udp port 53' 'allow udp port 67' 'allow tcp port 22' 'allow tcp port 80' 'allow tcp port 443'`

Router: Linksys EA8100
openNDS version 9.9.1
OpenWrt 22.03.2

LOG:

`Mon Nov 28 18:39:23 2022 daemon.notice opennds[2219]: openNDS Version 9.9.0 is in startup
Mon Nov 28 18:39:25 2022 daemon.notice opennds[2219]: MHD version is 0.9.75
Mon Nov 28 18:39:25 2022 daemon.notice opennds[2219]: Attempting to Bind to interface: br-lan
Mon Nov 28 18:39:25 2022 daemon.warn opennds[2219]: : fwhook restart request received - restarting
Mon Nov 28 18:39:27 2022 daemon.notice opennds[2219]: Exiting...
Mon Nov 28 18:39:27 2022 daemon.notice opennds[2856]: openNDS Version 9.9.0 is in startup
Mon Nov 28 18:39:28 2022 daemon.notice opennds[2856]: MHD version is 0.9.75
Mon Nov 28 18:39:28 2022 daemon.notice opennds[2856]: Attempting to Bind to interface: br-lan
Mon Nov 28 18:39:28 2022 daemon.notice opennds[2856]: Interface br-lan is up
Mon Nov 28 18:39:28 2022 daemon.notice opennds[2856]: Interface br-lan is at 192.168.1.1 (80:69:1a:08:b8:b0)
Mon Nov 28 18:39:28 2022 daemon.notice opennds[2856]: Number of Upstream gateway(s) [ 1 ]
Mon Nov 28 18:39:28 2022 daemon.warn opennds[2856]: Upstream gateway(s) [ offline ]
Mon Nov 28 18:39:28 2022 daemon.notice opennds[2856]: ipset support is available
Mon Nov 28 18:39:28 2022 daemon.notice opennds[2856]: dnsmasq ipset support is available
Mon Nov 28 18:39:28 2022 daemon.notice opennds[2856]: Created web server on 192.168.1.1:2050
Mon Nov 28 18:39:28 2022 daemon.notice opennds[2856]: Maximum Html Page size is [ 10240 ] Bytes
Mon Nov 28 18:39:28 2022 daemon.notice opennds[2856]: Socket access at /tmp/ndsctl.sock
Mon Nov 28 18:39:28 2022 daemon.notice opennds[2856]: FAS Enabled.
Mon Nov 28 18:39:28 2022 daemon.notice opennds[2856]: sha256sum provider is available
Mon Nov 28 18:39:30 2022 daemon.notice opennds[2856]: SSL Provider is active
Mon Nov 28 18:39:30 2022 daemon.notice opennds[2856]: FAS URL is http://cloud.waaniwifi.com:80/monitor/fas-hid.php
Mon Nov 28 18:39:30 2022 daemon.notice opennds[2856]: Forwarding Authentication is Enabled.
Mon Nov 28 18:39:30 2022 daemon.notice opennds[2856]: Initializing firewall rules
Mon Nov 28 18:39:31 2022 daemon.warn opennds[2856]: No Walled Garden Ports are specified - ALL ports are allowed - this may break some client CPDs.
Mon Nov 28 18:39:31 2022 daemon.warn opennds[2856]: No Walled Garden Ports are specified - eg. if apple.com is added, Apple devices will not trigger the portal.
Mon Nov 28 18:39:31 2022 daemon.warn opennds[2856]: : fwhook restart request received - restarting
Mon Nov 28 18:39:32 2022 daemon.notice opennds[2856]: Externals flagged with debuglevel 1.
Mon Nov 28 18:39:32 2022 daemon.notice opennds[2856]: openNDS is now running.
Mon Nov 28 18:39:32 2022 daemon.notice opennds[2856]: Upstream gateway(s) [ online:192.168.50.1,wan  ]
Mon Nov 28 18:39:33 2022 daemon.notice opennds[2856]: Exiting...
Mon Nov 28 18:39:33 2022 daemon.notice opennds[3592]: openNDS Version 9.9.0 is in startup
Mon Nov 28 18:39:34 2022 daemon.notice opennds[3592]: MHD version is 0.9.75
Mon Nov 28 18:39:34 2022 daemon.notice opennds[3592]: Attempting to Bind to interface: br-lan
Mon Nov 28 18:39:34 2022 daemon.notice opennds[3592]: Interface br-lan is up
Mon Nov 28 18:39:34 2022 daemon.notice opennds[3592]: Interface br-lan is at 192.168.1.1 (80:69:1a:08:b8:b0)
Mon Nov 28 18:39:34 2022 daemon.notice opennds[3592]: Number of Upstream gateway(s) [ 1 ]
Mon Nov 28 18:39:34 2022 daemon.notice opennds[3592]: Upstream gateway(s) [ online:192.168.50.1,wan  ]
Mon Nov 28 18:39:34 2022 daemon.notice opennds[3592]: ipset support is available
Mon Nov 28 18:39:34 2022 daemon.notice opennds[3592]: dnsmasq ipset support is available
Mon Nov 28 18:39:34 2022 daemon.notice opennds[3592]: Created web server on 192.168.1.1:2050
Mon Nov 28 18:39:34 2022 daemon.notice opennds[3592]: Maximum Html Page size is [ 10240 ] Bytes
Mon Nov 28 18:39:34 2022 daemon.notice opennds[3592]: Socket access at /tmp/ndsctl.sock
Mon Nov 28 18:39:34 2022 daemon.notice opennds[3592]: FAS Enabled.
Mon Nov 28 18:39:34 2022 daemon.notice opennds[3592]: sha256sum provider is available
Mon Nov 28 18:39:34 2022 daemon.notice opennds[3592]: SSL Provider is active
Mon Nov 28 18:39:35 2022 daemon.notice opennds[3592]: FAS URL is http://cloud.waaniwifi.com:80/monitor/fas-hid.php
Mon Nov 28 18:39:35 2022 daemon.notice opennds[3592]: Forwarding Authentication is Enabled.
Mon Nov 28 18:39:35 2022 daemon.notice opennds[3592]: Initializing firewall rules
Mon Nov 28 18:39:35 2022 daemon.warn opennds[3592]: No Walled Garden Ports are specified - ALL ports are allowed - this may break some client CPDs.
Mon Nov 28 18:39:35 2022 daemon.warn opennds[3592]: No Walled Garden Ports are specified - eg. if apple.com is added, Apple devices will not trigger the portal.
Mon Nov 28 18:39:38 2022 daemon.notice opennds[3592]: Externals flagged with debuglevel 1.
Mon Nov 28 18:39:38 2022 daemon.notice opennds[3592]: openNDS is now running.
Mon Nov 28 18:41:17 2022 daemon.notice opennds[3592]: Adding 192.168.1.177 90:20:3a:1c:67:3e token b9f72243 to client list
Mon Nov 28 18:42:01 2022 daemon.notice opennds[3592]: Number of Upstream gateway(s) [ 1 ]
Mon Nov 28 18:43:07 2022 daemon.notice opennds[3592]: Exiting...
Mon Nov 28 18:54:40 2022 daemon.notice opennds[8863]: openNDS Version 9.9.1 is in startup
Mon Nov 28 18:54:41 2022 daemon.notice opennds[8863]: MHD version is 0.9.75
Mon Nov 28 18:54:41 2022 daemon.notice opennds[8863]: Attempting to Bind to interface: br-lan
Mon Nov 28 18:54:41 2022 daemon.notice opennds[8863]: Interface br-lan is up
Mon Nov 28 18:54:41 2022 daemon.notice opennds[8863]: Interface br-lan is at 192.168.1.1 (80:69:1a:08:b8:b0)
Mon Nov 28 18:54:41 2022 daemon.notice opennds[8863]: Number of Upstream gateway(s) [ 1 ]
Mon Nov 28 18:54:41 2022 daemon.notice opennds[8863]: Upstream gateway(s) [ online:192.168.50.1,wan  ]
Mon Nov 28 18:54:41 2022 daemon.notice opennds[8863]: ipset support is available
Mon Nov 28 18:54:41 2022 daemon.notice opennds[8863]: dnsmasq ipset support is available
Mon Nov 28 18:54:42 2022 daemon.notice opennds[8863]: Created web server on 192.168.1.1:2050
Mon Nov 28 18:54:42 2022 daemon.notice opennds[8863]: Maximum Html Page size is [ 10240 ] Bytes
Mon Nov 28 18:54:42 2022 daemon.notice opennds[8863]: Socket access at /tmp/ndsctl.sock
Mon Nov 28 18:54:42 2022 daemon.notice opennds[8863]: FAS Enabled.
Mon Nov 28 18:54:42 2022 daemon.notice opennds[8863]: sha256sum provider is available
Mon Nov 28 18:54:42 2022 daemon.notice opennds[8863]: SSL Provider is active
Mon Nov 28 18:54:42 2022 daemon.notice opennds[8863]: FAS URL is http://cloud.waaniwifi.com:80/monitor/fas-hid.php
Mon Nov 28 18:54:42 2022 daemon.notice opennds[8863]: Forwarding Authentication is Enabled.
Mon Nov 28 18:54:42 2022 daemon.notice opennds[8863]: Initializing firewall rules
Mon Nov 28 18:54:43 2022 daemon.warn opennds[8863]: No Walled Garden Ports are specified - ALL ports are allowed - this may break some client CPDs.
Mon Nov 28 18:54:43 2022 daemon.warn opennds[8863]: No Walled Garden Ports are specified - eg. if apple.com is added, Apple devices will not trigger the portal.
Mon Nov 28 18:54:45 2022 daemon.notice opennds[8863]: Externals flagged with debuglevel 1.
Mon Nov 28 18:54:45 2022 daemon.notice opennds[8863]: openNDS is now running.
Mon Nov 28 18:54:49 2022 daemon.notice opennds[8863]: Adding 192.168.1.177 90:20:3a:1c:67:3e token 1d03f577 to client list
Mon Nov 28 19:00:32 2022 daemon.notice opennds[8863]: Exiting...`

What could the issue be? Why is the FAS unable to approve/authenticate the connection?

**Comment by bluewavenet** [comment]
@reevester 
`http://opennds_auth/?tok=fde7c......`

This is malformed for some reason.

`opennds.@opennds[0].walledgarden_fqdn_list='waaniwifi.com google.com cloud.waaniwifi.com'`

1. You need to have `waaniwifi.com` as this is the root domain for "waaniwifi" in the cloud/cdn.
2. cloud.waaniwifi.com is superfluous and should be removed.
3. google.com in the walled garden will block almost all Android devices from authenticating as it is the FQDN used for CPD.

`daemon.warn opennds[2219]: : fwhook restart request received - restarting`

You restarted the OpenWrt firewall. This in turn restarts openNDS and is normal.

`redir=http%3A%2F%2Fcloud.waaniwifi.com%2Fmonitor%2Ffas-hid.php%3Ffas%3DdzJRM2NndVlGNHg1Q`

This is a recursive query string and explains the malformed url as FAS is unable to decode and parse variables that are passed to it from openNDS.

If you are trying to connect with an Android device you will not get the CPD popup see above in `walledgarden_fqdn_list`). Are you in some way trying to manually access the portal?

**Comment by reevester** [comment]
That fixed it! Although I wasn't using an Android device, removing google.com from the walled garden definitely made it work again!

Thank you!

**Comment by reevester** [comment]
Hey Rob,

Another question. We are using FAS level 1 BUT we always see a CORS error:

`xhr.js:210 
        
       Mixed Content: The page at 'https://login.waaniwifi.com/?fas=aGlkPWJjNTk0NmIwZGFkNDI1NjdhMzA5NjA0MzliYmQ0N2M5MDlmZGU2MDA4ZWIwYWMxMWNlNGE4YmU1ZGZkZDJmNzYsIGNsaWVudGlwPTE5Mi4xNjguMS4xNzcsIGNsaWVudG1hYz05MDoyMDozYToxYzo2NzozZSwgY2xpZW50X3R5cGU9Y3BkX2NhbiwgZ2F0ZXdheW5hbWU9b3Blbk5EUywgZ2F0ZXdheXVybD1odHRwJTNhJTJmJTJmc3RhdHVzLmNsaWVudCwgdmVyc2lvbj05LjkuMSwgZ2F0ZXdheWFkZHJlc3M9MTkyLjE2OC4xLjE6MjA1MCwgZ2F0ZXdheW1hYz04MDo2OToxYTowODpiODpiMCwgb3JpZ2ludXJsPWh0dHAlM2ElMmYlMmZlZGdlLWh0dHAubWljcm9zb2Z0LmNvbSUyZmNhcHRpdmVwb3J0YWwlMmZnZW5lcmF0ZV8yMDQsIGNsaWVudGlmPWJyLWxhbiwgdGhlbWVzcGVjPShudWxsKSwgKG51bGwpKG51bGwpKG51bGwpKG51bGwp' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint 'http://192.168.1.1:2050/opennds_auth/?tok=0bf02b95b883e289534182ac1fc9ccbdb93559071157c385ca129787bcf64c94&redir=https://login.waaniwifi.com/?fas=aGlkPWJjNTk0NmIwZGFkNDI1NjdhMzA5NjA0MzliYmQ0N2M5MDlmZGU2MDA4ZWIwYWMxMWNlNGE4YmU1ZGZkZDJmNzYsIGNsaWVudGlwPTE5Mi4xNjguMS4xNzcsIGNsaWVudG1hYz05MDoyMDozYToxYzo2NzozZSwgY2xpZW50X3R5cGU9Y3BkX2NhbiwgZ2F0ZXdheW5hbWU9b3Blbk5EUywgZ2F0ZXdheXVybD1odHRwJTNhJTJmJTJmc3RhdHVzLmNsaWVudCwgdmVyc2lvbj05LjkuMSwgZ2F0ZXdheWFkZHJlc3M9MTkyLjE2OC4xLjE6MjA1MCwgZ2F0ZXdheW1hYz04MDo2OToxYTowODpiODpiMCwgb3JpZ2ludXJsPWh0dHAlM2ElMmYlMmZlZGdlLWh0dHAubWljcm9zb2Z0LmNvbSUyZmNhcHRpdmVwb3J0YWwlMmZnZW5lcmF0ZV8yMDQsIGNsaWVudGlmPWJyLWxhbiwgdGhlbWVzcGVjPShudWxsKSwgKG51bGwpKG51bGwpKG51bGwpKG51bGwp&custom=bhjbhj'. This request has been blocked; the content must be served over HTTPS.`

Any suggestions how to get around this? Or do we need to go the FAS SECURE LEVEL 3 route?

**Comment by bluewavenet** [comment]
@reevester 

`https://login.waaniwifi.com/?fas=a.....`

Https is not supported at level 1, only on level 3.
Your fas server must be redirecting to https. You should disable it on your web server.

**Comment by reevester** [comment]
Even when I switch the server to HTTP only, I get the following CORS error:

Access to XMLHttpRequest at 'http://192.168.1.1:2050/opennds_auth/?tok=483b469fe7f3906d503fda8a64d7b2cdc530f9bb010337bcebdcb0a612e94864&redir=http://view.waaniwifi.com/?fas=aGlkPWYyOTMxMmRmZWUxOWRmNDk4NTI2NmZmZWNiNDE4YTMxYjM1MDkwYjc3MjQ4Yjg5MDNmOWViNjU0NWUyOGIyN2UsIGNsaWVudGlwPTE5Mi4xNjguMS4xNzcsIGNsaWVudG1hYz05MDoyMDozYToxYzo2NzozZSwgY2xpZW50X3R5cGU9Y3BkX2NhbiwgZ2F0ZXdheW5hbWU9b3Blbk5EUywgZ2F0ZXdheXVybD1odHRwJTNhJTJmJTJmc3RhdHVzLmNsaWVudCwgdmVyc2lvbj05LjkuMSwgZ2F0ZXdheWFkZHJlc3M9MTkyLjE2OC4xLjE6MjA1MCwgZ2F0ZXdheW1hYz04MDo2OToxYTowODpiODpiMCwgb3JpZ2ludXJsPWh0dHAlM2ElMmYlMmZlZGdlLWh0dHAubWljcm9zb2Z0LmNvbSUyZmNhcHRpdmVwb3J0YWwlMmZnZW5lcmF0ZV8yMDQsIGNsaWVudGlmPWJyLWxhbiwgdGhlbWVzcGVjPShudWxsKSwgKG51bGwpKG51bGwpKG51bGwpKG51bGwp&custom=bhjbhj' from origin 'http://view.waaniwifi.com' has been blocked by CORS policy: The request client is not a secure context and the resource is in more-private address space `private`.


P.S. - We are trying to recreate the login page using ReactJS instead of PHP. Not sure if that matters but putting it out there, in case it does.

**Comment by bluewavenet** [comment]
@reevester 

> We are trying to recreate the login page using ReactJS instead of PHP

All modern devices use a built in code to produce the "popup" login screen on a restricted functionality minibrowser.

This built in code complies with the defacto standard Captive Portal Detection (CPD - aka Canary tester), and more recently the upcoming new standard, Captive Portal Information (CPI - RFC 8910 and RFC 8908).

Both of these standards specifically block all downloadable code including javascript for security reasons. A captive portal is an initially untrusted system and is very similar to a Man In The Middle (MITM) attack device, so it is essential that the MITM is prevented from downloading and executing code on the client device.

ReactJS cannot be used for any secure captive portal if the code expects downloaded js libraries, unless the javascript is executed on the FAS server (eg using something like on a NodeJS server).

Even if you attempted to implement this on FAS level 3 on an https server, CPD/CPI would still reject it on most smart devices.
