### ISSUE TITLE
Does anyone have a good solution for the issue of https/http mixed content impacting remote FAS hosted via HTTPS?

### ISSUE THREAD

**Issue by ekowtaylor** [openNDS/openNDS#419]
When a remote FAS is hosted via HTTPS but the redirect to the gateway is HTTP, some browsers throw up a "mixed content" error and block the page from loading any further. I'm thinking to start a webserver that listens for HTTP requests on port 443 then redirect to gateway at the set port. Any thoughts?

**Comment by bluewavenet** [comment]
@ekowtaylor 

> When a remote FAS is hosted via HTTPS but the redirect to the gateway is HTTP, some browsers throw up a "mixed content" error and block the page from loading any further.

This is a miss-configured system and is the correct behaviour from the browser, in fact many CPD "mini" browsers will not even show the splash page sequence.

If you want an https remote fas then you should use `option fas_secure_enabled '3'`

This is clearly described in the documentation:
https://opennds.readthedocs.io/en/stable/config.html#level-set-to-3

and is demonstrated in the example script `fas-aes-https.php`
https://opennds.readthedocs.io/en/stable/fas.html#fas-aes-https-php
