### ISSUE TITLE
authenticated but no internet

### ISSUE THREAD

**Issue by egboyguda** [openNDS/openNDS#420]
Good day DEV!

I'm currently running opennds on my orangepi pc with ubuntu

the problem is when my windows computer successfully authenticated there is no internet,
but if i manually set the dns server in my computer to 8.8.8.8 its able to access the internet

but i unable to access the status.client address

here is my dnsmasq setup

```
interface=enx00e04c361069
listen-address=127.0.0.1
bind-interfaces
server=8.8.8.8
domain=status.client
dhcp-range=10.0.0.5,10.0.0.253,12h
address=/#/123.122.123.124
dhcp-option-force=114,http://status.client
```

![cde](https://user-images.githubusercontent.com/14038474/210472563-02be910d-c49a-4306-b6a6-00f2725b9f47.PNG)

**Comment by egboyguda** [comment]
thank u for your reply. I'm still new to this dnsmasq, but i will try to search and read the docs. thank you for your tips

**Comment by bluewavenet** [comment]
@egboyguda 
You do not have to manually add anything openNDS specific to the dnsmasq config, this should be done automatically by openNDS when it starts up.

**Comment by egboyguda** [comment]
sir can you give me an useful source (site,video) how to setup dnsmasq in offline mode?

**Comment by egboyguda** [comment]
thank you mr. dev 
i already removed this line and now i can access internet
address=/#/123.122.123.124

**Comment by egboyguda** [comment]
thank you mr. dev 
i already removed this line and now i can access internet
address=/#/123.122.123.124
