### ISSUE TITLE
Issue with fas_secure_enabled=2 on OpenWRT 22.03.3

### ISSUE THREAD

**Issue by bluepuma77** [openNDS/openNDS#422]
I installed openNDS on a TP-Link Archer C7 with latest OpenWRT 22.03.3. I configured `/etc/config/opennds` and it's working fine with `option fas_secure_enabled '1'`. I can start openNDS with `service opennds start`, it will forward a mobile device to FAS, I can stop it with `service opennds stop`.

As soon as I change it to `option fas_secure_enabled '2'`, the captive portal is not working anymore, the mobile device gets immediate Internet access. `service opennds status`shows `running`.

I suspect that openNDS has an issue with the encryption of the parameters, but where would I see such error log? Even though I have set `option log_mountpoint '/tmp'` and `option debuglevel '3'`, there is no file after reboot. There was one before but it's gone after reboot and never written again.

```
# uci show opennds
opennds.@opennds[0]=opennds
opennds.@opennds[0].enabled='1'
opennds.@opennds[0].debuglevel='3'
opennds.@opennds[0].max_log_entries='1000'
opennds.@opennds[0].maxclients='250'
opennds.@opennds[0].binauth='/usr/lib/opennds/binauth_log.sh'
opennds.@opennds[0].fasport='80'
opennds.@opennds[0].fasremotefqdn='example.com'
opennds.@opennds[0].fasremoteip='1.2.3.4'
opennds.@opennds[0].faspath='/fas'
opennds.@opennds[0].fas_secure_enabled='2'
opennds.@opennds[0].users_to_router='allow tcp port 53' 'allow udp port 53' 'allow udp port 67' 'allow tcp port 22' 'allow tcp port 80' 'allow tcp port 443'
opennds.@opennds[0].log_mountpoint='/tmp'
```

----------

Okay, did a full reset of OpenWRT 22.03.3, for whatever reason there is no log:

```
# opkg update
# opkg install opennds 
# uci show opennds
opennds.@opennds[0]=opennds
opennds.@opennds[0].enabled='1'
opennds.@opennds[0].fwhook_enabled='1'
opennds.@opennds[0].maxclients='250'
opennds.@opennds[0].users_to_router='allow tcp port 53' 'allow udp port 53' 'allow udp port 67' 'allow tcp port 22' 'allow tcp port 80' 'allow tcp port 443'

# service opennds start && sleep 5 && cat /tmp/ndslog/ndslog.log ; service opennds stop
cat: can't open '/tmp/ndslog/ndslog.log': No such file or directory

uci set opennds.@opennds[0].debuglevel='3'
uci set opennds.@opennds[0].log_mountpoint='/tmp'
uci set opennds.@opennds[0].max_log_entries='1000'
uci set opennds.@opennds[0].binauth='/usr/lib/opennds/binauth_log.sh'
uci commit opennds

# service opennds start && sleep 5 && cat /tmp/ndslog/ndslog.log ; service opennds stop
cat: can't open '/tmp/ndslog/ndslog.log': No such file or directory
```
There is a file `/tmp/ndsdebuglevel`, but no log file.

**Comment by bluepuma77** [comment]
Seems I found two hints:

1. To read the logs, use command `logread`. Still don't know what happened to the file. "PHP packages PHP CLI and PHP OpenSSL are required" and "Exiting...". Strange that `service opennds status`still shows `running`.
2. Docs also clearly state "The “php-cli” package and the “php-openssl” module must both be installed for fas_secure level 2.". I thought it's for the php server example, but it's meant for the router. Sadly OpenWRT 22.03.3 does not have those packages available.

**Comment by bluewavenet** [comment]
@bluepuma77 

> As soon as I change it to option fas_secure_enabled '2', the captive portal is not working anymore

I thought you said you were reading the documentation! 
https://opennds.readthedocs.io/en/stable/fas.html#example-script-file-fas-aes-php

OpenNDS requires the php cli and php openssl modules for levels 2 and 3.
OpenWrt 22.03.0 onwards has php8 available (earlier versions had php7).

From my documentation link above:

>  * Install the packages php8-cli and php8-mod-openssl

**Comment by bluewavenet** [comment]
@bluepuma77 
`option log_mountpoint '/tmp'`
This is the default so does not need to be added to the config.
See:
https://opennds.readthedocs.io/en/stable/config.html#local-log-mountpoint

The openNDS local log is an operational log, not an error log.
It logs all client authentications, by default to the /tmp mountpoint.
/tmp is a "ramdisk" and the contents do not survive a reboot.

All error logs are sent to syslog.

**Comment by bluewavenet** [comment]
@bluepuma77 

> Strange that service opennds status still shows running

Not really if openNDS is aborting startup because the procd daemon will retry startup numerous times before eventually timing out.

**Comment by bluepuma77** [comment]
> From my documentation link above:
> > * Install the packages php8-cli and php8-mod-openssl

Thanks @bluewavenet. I read the documentation, the section about [security modes](https://opennds.readthedocs.io/en/stable/fas.html#security) only states:
```
The “php-cli” package and the “php-openssl” module must both be installed for fas_secure level 2.
```

**Comment by bluewavenet** [comment]
@bluepuma77 
The section on security modes is a generic description. It is possible to run openNDS on any Linux distribution.

The module names in OpenWrt 22.03 and later are "php8-cli and php8-mod-openssl".
In other distributions the actual packages may well have different names or could be incorporated into one big package.

> Sadly OpenWRT 22.03.3 does not have php-cli and php-openssl packages available.

The moral to the story is to do a little thinking and a little research before jumping to hasty conclusions.

**Comment by bluepuma77** [comment]
@bluewavenet 
I support another open source project and have written about 500 replies in their community.

My learnings:
1. Some users are just idiots
2. Documentation can always be improved

**Comment by bluewavenet** [comment]
@bluepuma77 

> My learnings:

I certainly agree with both of those :-D
