### ISSUE TITLE
How to use fas_secure_enabled=1 ?

### ISSUE THREAD

**Issue by bluepuma77** [openNDS/openNDS#423]
Working for hours to get openNDS up and running. Somehow the documentation for the authentication is not clear to me.

"The FAS must return the hash of the concatenated hid value and the value of faskey identified in the query string as “tok”." ([source](https://opennds.readthedocs.io/en/stable/fas.html#example-fas-query-strings))

"FAS must return the sha256sum of the concatenation of hid(the hashed original token), and faskey to be used by NDS for client authentication" ([source](https://github.com/openNDS/openNDS/blob/master/linux_openwrt/opennds/files/etc/config/opennds))

The `fas` parameter base64 encoded string sent to the FAS server has multiple variables:
```
hid: '7292caecabf11b361cc0a279174c467a2e0b4691986f5d08664d623786bb3342',
clientip: '192.168.1.126',
clientmac: 'aa:4f:7c:b1:70:46',
client_type: 'cpi_url',
gatewayname: 'openNDS%20Node%3aa46e0e36bfc2%20',
gatewayurl: 'http://status.client', // decoded
version: '9.9.1',
gatewayaddress: '192.168.1.1:2050',
gatewaymac: 'a4:6e:0e:36:bf:c2',
originurl: 'http://captive.apple.com/hotspot-detect.html', // decoded
clientif: 'wlan1',
themespec: '(null)',
```

**What is the return URL from FAS to authenticate the user with openNDS?**

1. After FAS authentication I send the client browser back to the router, right?
2. Should I use `gatewayurl` or `gatewayaddress` as router host? 
3. What is the URL `path` to use, if any? `authdir`?
4. The only required URL query parameter it `tok`? 
5. Value of `tok` is the sha256sum of concatenated string of hid (from above) + faskey (secret)?
6. `redir` query parameter is optional, device will probably close the captive portal window anyway, right?

**Comment by bluewavenet** [comment]
@bluepuma77 
FAS level 1 is designed for use on routers with very limited resources.
You stated elsewhere that you want to roll out to many sites with a remote FAS server, so level 3 would be more realistic for commercial use with its https splash page sequence.

You have a TP-Link Archer C7 and this is a 16/128 device so is not resource limited (unless it is the original version with only 8MB flash, in which case you will not be able to run OpenWrt 22.03 anyway.

It would be more sensible to go back to a basic install of openNDS and check that it is working before moving on to trying the FAS example php scripts, one by one, verifying they work on your remote FAS server.

Finally you will end up with the level 3 fas-aes-https.php script working correctly.

Then and only then, you should start developing a custom version.
https://opennds.readthedocs.io/en/stable/fas.html#forwarding-authentication-service-fas

The example scripts are designed to make it easy to change the look and feel of the splash page sequence, so once you have arrived at this stage you should find it fairly easy to customise. 

> What is the return URL from FAS to authenticate the user with openNDS?

FAS level 3 does not use a return url method of authentication, instead it uses the built in nat traversal daemon to communicate directly with the local instance of openNDS.
https://opennds.readthedocs.io/en/stable/fas.html#authentication-method-for-fas-secure-enabled-level-3-authmon-daemon

**Comment by bluewavenet** [comment]
@bluepuma77 
To answer your original question, to configure for the example script, fas-hid.php, see:
https://opennds.readthedocs.io/en/stable/fas.html#example-script-file-fas-hid-php

Once you have it running you can study the php code and you will find it is fairly well self documented.
There is no reason to change the authentication code. But you can change the look and feel very easily.

**Comment by bluepuma77** [comment]
@bluewavenet So here is the secret: `opennds_auth`. Plain and simple: **opennds_auth**

Use "opennds_auth" as path for the return URL to openNDS.
```
// NodeJS implementation of auth URL
const faskey = '1234567890' // same as on openNDS device
const tok = crypto.createHash('sha256').update(data.hid + faskey).digest('hex');
const redir = encodeURIComponent('http://example.com/fas')
const url = data.gatewayurl + '/opennds_auth/?tok=' + tok + '&redir=' + redir
```

**PLEASE** put this clearly in the documentation, so others do not waste hours trying to get this to work.
