### ISSUE TITLE
change splash page to my fas

### ISSUE THREAD

**Issue by egboyguda** [openNDS/openNDS#425]
good day dev!
 i want to replace this(below picture) default splash page to my fas

`
![Capture](https://user-images.githubusercontent.com/14038474/213362374-de3ac39c-3ff6-4f4d-aa90-d13ae7a60c8d.PNG)

i already configure the  opennds to fasport 3000 where my fas server is running

the problem is that when i go to 10.0.0.1 still need to click the button before it can direct me to my fas.

i want to make it, when user go to 10.0.0.1 it automatically redirect to my fas no need to click the continue  button

**Comment by bluewavenet** [comment]
@egboyguda 
The user should never need to manually go to the gateway address (10.0.0.1 in this case).
Almost all modern devices support the de-facto Captive Portal Detection (CPD) standard and most of the latest clients also support the upcoming Captive Portal Identification (CPI) standard.

CPD is driven by the client operating system, giving an automatic popup of the splash page sequence.
CPI is driven by the captive portal, informing clients that they are restricted and require to log in. In this case the client operating system gives an appropriate CP notification, giving a link or icon to click to get the splash page sequence.

For more in depth information see:
https://opennds.readthedocs.io/en/stable/howitworks.html#how-opennds-nds-works
