### ISSUE TITLE
"/usr/bin/ndsctl auth <MAC>" does not work for expired clients

### ISSUE THREAD

**Issue by bluepuma77** [openNDS/openNDS#428]
I have set up openNDS 9.9.1 on OpenWrt 22.03.3. The timeout of 5 minutes works, but I am unable to do the auth again after the 5 minutes have expired. Is that intended behaviour?

```
# client connects to router, I can manually authenticate and enable Internet
root@xyz:~# /usr/bin/ndsctl auth ab:8f:3c:bb:e6:12
Client ab:8f:3c:bb:e6:12 authenticated.

# after 5 minutes are over, I can not authenticate the client again
root@xyz:~# /usr/bin/ndsctl auth ab:8f:3c:bb:e6:12
Failed to authenticate client ab:8f:3c:bb:e6:12.
```

My openNDS settings:
```
uci set opennds.@opennds[0].fas_secure_enabled='1'
uci set opennds.@opennds[0].faskey='xyz'
uci set opennds.@opennds[0].fasremotefqdn='example.com'
uci set opennds.@opennds[0].fasremoteip='1.2.3.4'
uci set opennds.@opennds[0].fasport='80'
uci set opennds.@opennds[0].faspath='/fas'
uci set opennds.@opennds[0].sessiontimeout='5'
uci set opennds.@opennds[0].debuglevel='3'
uci set opennds.@opennds[0].max_log_entries='1000'
uci set opennds.@opennds[0].gatewayname='xyz'
uci set opennds.@opennds[0].enable_serial_number_suffix='0'
```

**Comment by bluewavenet** [comment]
@bluepuma77 

> I am unable to do the auth again after the 5 minutes have expired. Is that intended behaviour?

Yes this is the default behaviour. An expired client is removed from the client list (and by default they need to reconnect to get back onto the client list).

**Note:**
On connection or re-connection, clients are automatically put onto the client list in the pre-authenticated state.
The CPD or CPI processes are responsible for this.
A client can be manually entered directly into the client list in the authenticated state using ndsctl as long as pre-emptive authentication is enabled and the client is still connected to the network.

See:
https://opennds.readthedocs.io/en/stable/config.html#allow-preemptive-authentication

I have a few questions:
- Why do you want the session timeout so short? 
- Why do you want to manually re-authenticate expired clients? 
- Why don't you let them re-authenticate themselves in the normal way?
- If you intend to immediately re-authenticate an expired client, why not make the timeout longer?

**Comment by bluepuma77** [comment]
My client was a Mac and the last days the captive portal was not shown when connecting. I just wanted a quick hack to enable it. But if it's intended, that's fine, just thought I might have found a bug.

**Comment by bluewavenet** [comment]
@bluepuma77 

> thought I might have found a bug

Thanks for reporting it anyway ;-)

Pre-emptive authentication is quite useful in some cases, for example roaming between instances of openNDS, or for authentication service for IoT devices where it is more secure than adding a list of trusted mac addresses.
