### ISSUE TITLE
How to install version 6.x?

### ISSUE THREAD

**Issue by mrbluecoat** [openNDS/openNDS#43]
https://opennds.readthedocs.io/en/stable/compile.html says:

> The version number for MHD must not exceed 0.9.70 for versions of openNDS less than 6.0.0

and https://opennds.readthedocs.io/en/stable/install.html says:

> openNDS v6.0.0 or higher requires libmicrohttpd 0.9.71 or higher

I'd like to install openNDS v6.x but there are no releases and git trunk still says version 5.2.0.

**Comment by mrbluecoat** [comment]
Ah, I didn't realize I was on the cusp of the bleeding edge. Thanks, and cool project by the way!

**Comment by bluewavenet** [comment]
@mrbluecoat 
6.0.0 now released:
https://github.com/openNDS/openNDS/releases/tag/v6.0.0
PR for OpenWrt next.....
