### ISSUE TITLE
Configuration question and "Error 403 - Forbidden - Access Denied to this Client!" in 9.7.0

### ISSUE THREAD

**Issue by brett90063** [openNDS/openNDS#432]
Hello OpenNDS team, I'm a new user of OpenNDS.

I'm using **OpenWrt 21.02.1** and **OpenNDS 9.4.0**.

Here are some questions:

1. After **Authenticated Client Idle Timeout**, the client's status will change from "Authenticated" to "Preauthenticated". Why is "preauthenticated" necessary? The client still needs to authenticate again.

2. In the configuration, there have settings for **data quota** and **rate limit**, and I noticed that `ndsctl status` provides session information. I'm wondering if there is also an option to set a **session limit** in the configuration?.

3. In `opennds.@opennds[0].gatewayinterface`, does this configuration support multiple interfaces, like `opennds.@opennds[0].gatewayinterface='eth0.1, eth0.2'`?

4. After authentication, OpenNDS will try to go to the original URL. Is there a way to configure a custom landing page URL or IP address after authentication? or just original URL right now. 
(I'm not sure if I have a good explanation for this question. For example, instead of redirecting to the user's original URL after authentication, I want to redirect them to "www.yahoo.com".)

6. When I access `192.168.1.1`(router's admin page) before being authenticated, OpenNDS will redirect to the login page at `192.168.1.1:2050` by iptables rule. After logging in, the original URL changes to `192.168.1.1:2050` instead of `192.168.1.1`. How can I fix this issue?

7. I haven't reached this stage yet, so this might be a stupid question: If the router has its own login page, how to link it to OpenNDS? (This seems like what FAS is doing?)

---

Another problem is that I have seen **"CPI"** in a document, says it will automatically pops out instead of intercepting port 80. I want to test the CPI feature, which requires version 9.5.0 or later, so I upgraded OpenNDS from **9.4.0** to **9.7.0.**, which is the latest version supported as of 21.02. 

However, after configuring it in the same way, I receive an **"Error 403 - Forbidden - Access Denied to this Client!"** message when trying to access either 192.168.1.1 or 192.168.1.1:2050 (**9.4.0** is doing well). I have noticed that version 9.7.0 doesn't have the 
`iptables -t nat -I ndsOUT -p tcp --destination 192.168.1.1 --dport 80 -j REDIRECT --to-port 2050` 
rule, but even after adding it, it still doesn't work. :(

Here's my configuration:
`ifconfig`:
```
ae_wan    Link encap:Ethernet  HWaddr 00:1D:AA:22:33:44
          inet addr:192.168.123.62  Bcast:192.168.123.255  Mask:255.255.255.0
          UP BROADCAST MULTICAST  MTU:1500  Metric:1
          RX packets:964 errors:0 dropped:213 overruns:0 frame:0
          TX packets:239 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:98638 (96.3 KiB)  TX bytes:23934 (23.3 KiB)

br-lan    Link encap:Ethernet  HWaddr 00:1D:AA:22:33:44
          inet addr:192.168.1.1  Bcast:192.168.1.255  Mask:255.255.255.0
          inet6 addr: fe80::1/64 Scope:Link
          inet6 addr: fdea:e111:ce6b::1/60 Scope:Global
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:1639 errors:0 dropped:0 overruns:0 frame:0
          TX packets:998 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:143334 (139.9 KiB)  TX bytes:118662 (115.8 KiB)
```

`uci show opennds`:
```
opennds.@opennds[0]=opennds
opennds.@opennds[0].enabled='1'
opennds.@opennds[0].fwhook_enabled='1'
opennds.@opennds[0].maxclients='250'
opennds.@opennds[0].users_to_router='allow tcp port 53' 'allow udp port 53' 'allow udp port 67' 'allow tcp port 22' 'allow tcp port 80' 'allow tcp port 443'
opennds.@opennds[0].debuglevel='3'
opennds.@opennds[0].binauth='/usr/lib/opennds/binauth_log.sh'
opennds.@opennds[0].gatewayfqdn='disable'
```

`ndsctl status`:
```
==================
openNDS Status
====
Version: 9.7.0
Uptime: 10m 15s
Gateway Name: [ openNDS S/N:001daa223344  ]
Debug Level: [ 3 ]
Gateway FQDN: [ disable ]
Managed interface: br-lan
All Upstream gateway(s) are offline or not connected [ offline ]
MHD Server [ version 0.9.71 ] listening on: http://192.168.1.1:2050
Maximum Html Page size is [ 10240 ] Bytes
Preemptive Authentication is Disabled
Binauth Script: /usr/lib/opennds/binauth_log.sh
Preauth Script: /usr/lib/opennds/libopennds.sh
FAS: Secure Level 1, URL: http://192.168.1.1:2050/opennds_preauth/
Client Check Interval: 15s
Rate Check Window: 2 check intervals (30s)
Preauthenticated Client Idle Timeout: 30m
Authenticated Client Idle Timeout: 120m
Download rate limit threshold (default per client): no limit
Upload rate limit threshold (default per client): no limit
Download quota (default per client): no limit
Upload quota (default per client): no limit
Total download: 11 kByte; average: 0.15 kbit/s
Total upload: 5 kByte; average: 0.07 kbit/s
====
Client authentications since start: 0
Current clients: 0
====
Trusted MAC addresses: none
Walled Garden FQDNs: none
Walled Garden Ports: none
========
```

`logread -e opennds`:
[openNDS_9.7.0_log.txt](https://github.com/openNDS/openNDS/files/10789054/openNDS_9.7.0_log.txt)

---

English is not my primary language, so I apologize in advance if I come across as impolite or unclear in my comments or questions.

**Comment by bluewavenet** [comment]
@brett90063 

> I'm using OpenWrt 21.02.1 and OpenNDS 9.4.0.

These are both outdated and no longer supported.
I suggest you reflash to OpenWrt 22.03.x where the current version of opennds is 9.10.0.

I also suggest you study the documentation at:
https://opennds.readthedocs.io
Here you will find most of the answers to your questions.

> **"Error 403 - Forbidden - Access Denied to this Client!"**

This means the client is not managed by the router's dhcp server. This is mandatory for RFC 8910 support (CPI).

> have noticed that version 9.7.0 doesn't have the
> iptables -t nat -I ndsOUT -p tcp --destination 192.168.1.1 --dport 80 -j REDIRECT --to-port 2050
> rule, but even after adding it, it still doesn't work. :(

You have it disabled in your config (`opennds.@opennds[0].gatewayfqdn='disable'`).

**Comment by brett90063** [comment]
Hi, bluewavenet 
Thank you for the reply.
>I suggest you reflash to OpenWrt 22.03.x where the current version of opennds is 9.10.0.

It's other department's decision to decide the OpenWrt version, so that is unfortunate. If some of my questions have already been fixed in a later version, please let me know. Thank you.


After studying the openNDS document, I will try to answer the question myself, If you have the time, any hints or tips you could provide would be greatly appreciated. Thank you

---

> 1. After **Authenticated Client Idle Timeout**, the client's status will change from "Authenticated" to "Preauthenticated". Why is "preauthenticated" necessary? The client still needs to authenticate again.

Setting **Authenticated user** for block/allow/passthrough
`opennds.@opennds[0].authenticated_users='block to 123.2.3.4'`
`opennds.@opennds[0].authenticated_users='allow tcp port 80'`
`opennds.@opennds[0].authenticated_users='passthrough all'`

**Preauthenticated user** can access walled garden fqdn
support RFC8910 and walled garden
`opennds.@opennds[0].walledgarden_fqdn_list='facebook.com fbcdn.net'`
`opennds.@opennds[0].walledgarden_port_list='443'`

---

> 2. In the configuration, there have settings for **data quota** and **rate limit**, and I noticed that `ndsctl status` provides session information. I'm wondering if there is also an option to set a **session limit** in the configuration?.

only **volume quotas**
`opennds.@opennds[0].uploadquota='1000'`
`opennds.@opennds[0].downloadquota='10000'`
and **rate quotas**
`opennds.@opennds[0].uploadrate='200'`
`opennds.@opennds[0].downloadrate='800'`
no session limit yet

---

>3. In `opennds.@opennds[0].gatewayinterface`, does this configuration support multiple interfaces, like `opennds.@opennds[0].gatewayinterface='eth0.1, eth0.2'`?

**The value may be an interface section in /etc/config/network or a device name such as br-lan**
Can support multiple, `'A B'` insted of `'A, B'`
`opennds.@opennds[0].gatewayinterface='eth0.1 eth0.2'`
`Interface: eth0.1 eth0.2 is not yet ready - waiting...`

---

>4. After authentication, OpenNDS will try to go to the original URL. Is there a way to configure a custom landing page URL or IP address after authentication? or just original URL right now. 
(I'm not sure if I have a good explanation for this question. For example, instead of redirecting to the user's original URL after authentication, I want to redirect them to "www.yahoo.com".)


**This virtual URL has the following format: 
`http://[nds_ip]:[nds_port]/[authdir]/?tok=[token]&redir=[landing_page_url]&custom=`**
However, I cannot find the `landing_page_url` parameter in any location. I noticed the `landing_page()` function in the theme, but I couldn't find any configuration option to set the landing URL. My guess is that I can add a new parameter like 'landingurl' and replace the 'originurl' or 'gatewayurl' parameters with it?
Needs some hints >.<

---

>5. When I access `192.168.1.1`(router's admin page) before being authenticated, OpenNDS will redirect to the login page at `192.168.1.1:2050` by iptables rule. After logging in, the original URL changes to `192.168.1.1:2050` instead of `192.168.1.1`. How can I fix this issue?

In my test (9.4.0), any traffic on port 80 is redirected to 192.168.1.1:2050 by using an iptables DNAT rule, and the original URL is always changed to 192.168.1.1:2050. Seems like there is nothing I can do, this is how DNAT works, right?

---
>6. I haven't reached this stage yet, so this might be a stupid question: If the router has its own login page, how to link it to OpenNDS? (This seems like what FAS is doing?)

Skip this question, I will study more FAS :)

---

>"Error 403 - Forbidden - Access Denied to this Client!"
>>This means the client is not managed by the router's dhcp server. This is mandatory for RFC 8910 support (CPI).

Thanks for the hints!! But after I disabled DHCP option 114, it still shows a ERROR 403.
```
uci set opennds.@opennds[0].dhcp_default_url_enabled='0'
uci commit opennds
service opennds restart
```
Is there something I missed?

**Comment by bluewavenet** [comment]
@brett90063 

>  no session limit yet

https://opennds.readthedocs.io/en/stable/config.html#session-timeout

> In opennds.@opennds[0].gatewayinterface, does this configuration support multiple interfaces

Multiple interfaces are supported but must all be on the same ipv4 subnet, ie they must be bridged into a single logical interface.

If you want multiple subnets with different captive portal splash page sequences, the correct way to implement this is to have local router configurations with unique openNDS instances, either working independently or feeding back to a central FAS server.

> I cannot find the landing_page_url parameter

It no longer exists. It was made ineffective a long time ago by developments in CPD technology implemented on all device operating systems. Almost all "smart" clients immediately close the CPD browser as soon as the client is authenticated.
A config option for setting a "landing page" was deprecated by client CPD implementations and has long since been removed from the code base of openNDS.
_This is a function of the client device operating system and there is nothing openNDS can do about it._

> When I access 192.168.1.1(router's admin page) before being authenticated, OpenNDS will redirect to the login page at 192.168.1.1:2050 by iptables rule

Yes, that is how dnat works. Note that as port 80 is the "capture port", by default, access to Luci on port 80 is disabled entirely when opennds is running.
Access to Luci should be achieved via https on port 443.


>  it still shows a ERROR 403.

This is correct if the client is not managed by the router dhcp.
I should reword my statement:
**openNDS requires all clients to use the router's dhcp server - this is mandatory.**

It was introduced:
1. for security reasons
2. to facilitate rfc 8910 support

> It's other department's decision to decide the OpenWrt version

They should be aware that OpenWrt 21.02.5 is nearing end of life and is currently only receiving limited security and bug fixes until the next major release of OpenWrt, probably later this year.

Also, as current versions of openNDS have, amongst other changes, migrated from iptables to nftables, there is no guarantee that any development you do on this old version will be useable when you finally upgrade.

**Comment by brett90063** [comment]
Hi bluewavenet
>there is no guarantee that any development you do on this old version

Now I have to figure out how to translate from iptables to nftable, because our firewall is using nftables, god bless me ;)

Anyway, many thanks for your reply. It was very helpful, thank you!

**Comment by brett90063** [comment]
Hi @bluewavenet 

In the document's login option section:
https://opennds.readthedocs.io/en/stable/config.html?highlight=login_option_enabled#login-option
In Mode 0, it says:
`If FAS is not enabled, then this functions as mode 1`
Does this mean that I need to set `login_option_enabled='0'` when using FAS?

Another question is that I want to set my router's login page to OpenNDS login system (that means I wish to use my login page and transfer user data to openNDS for all other functions except login page). The options Gatewayfqdn, Themespec, and PreAuth don't seem suitable for this case. 

I'm still very confused because the documentation says that `openNDS (NDS) has the ability to forward requests to a third party authentication service (FAS).` In this case, my router's login page could be a third-party authentication service, right? But `fas-aes.php` already offer a complete login system. 
I can't see a relationship between FAS and the router's login page. Or maybe I have a huge mistake in understanding what FAS is?

Also, there is a typo in the documentation.
https://opennds.readthedocs.io/en/stable/customize.html#custom-dynamic-themespec-pages
`option themespecpath '/path/to/themespec_script'` maybe is 
`option themespec_path '/path/to/themespec_script'`? 
I can't find `themespecpath` in opennds config file.

**Comment by brett90063** [comment]
Wait... Does FAS means deploying login page(`fas-xxx.php`) in different locations (such as local, remote, etc.), not involving third-party services like Google, Facebook, SMS, or RADIUS? If so, my router's login page can not use for sure, I can only change `fas-aes.php` to being my login page, right?

**Comment by bluewavenet** [comment]
@brett90063 

> Does this mean that I need to set login_option_enabled='0' when using FAS?

Yes but why not try it and see?

> Another question is that I want to set my router's login page to OpenNDS login system

What is the router's login page? Do you mean Luci?

> I can't see a relationship between FAS and the router's login page

There is no relationship. Luci cannot be used to manage openNDS, if that is what you are asking.

> Or maybe I have a huge mistake in understanding what FAS is?

Yes I think you do.

FAS and Luci have entirely different functions and have no connection whatsoever.

**FAS** (Forward Authentication Service) is a remote authentication service for openNDS, allowing user credential verification for people using your captive portal controlled public network.

**Luci** is the OpenWrt router management GUI and is for administration use in managing your router.

> my router's login page could be a third-party authentication service, right? But fas-aes.php already offer a complete login system.

Yes. I but don't understand what are you asking. The fas-aes.php script is provided as an example.

> Also, there is a typo in the documentation.

In the link you provided, yes there does indeed seem to be a typo.

Look here though:
https://opennds.readthedocs.io/en/stable/config.html#themespec-path

Note however that themespec_path is only used when login_option_enabled is set to ‘3’

**Comment by bluewavenet** [comment]
@brett90063 

> third-party services like Google, Facebook, SMS, or RADIUS?

FAS provides the dynamically generated html login sequence that the client user sees.
FAS is responsible for validating any credentials the user may provide and can chain onwards to third party services if required.
This is not included in the example fas scripts. It would be entirely your responsibility to provide the code for this.

**Comment by brett90063** [comment]
@bluewavenet 

Thanks for reply.

>Yes but why not try it and see?

My bad, I'm survey opensource in portal, don't have openwrt to test now, configure question will ask when I have openwrt

>my router's login page could be a third-party authentication service, right? But fas-aes.php already offer a complete login system.
>>Yes. I but don't understand what are you asking. The fas-aes.php script is provided as an example.

Oops, sorry for unclear question, actually `my router's login page` means the independent login page for portal (like `fas-aes.php` in openNDS), not router's login page. I was wondering if I can replace `fas-aes.php` to my login page for portal.

I think I can do it in the right way now, thank you bluewavenet.
