### ISSUE TITLE
Changing ?fas and ?iv parameter in the query 

### ISSUE THREAD

**Issue by d1stox** [openNDS/openNDS#435]
Hello , I read the documentation but I still have no clue if there is a way to change the "fas" and "iv" parameter in the query string. 
I want to rename them to prevent reconnaissance of the service.

**Comment by bluewavenet** [comment]
@d1stox 
There is no way to change the naming convention in the configuration.
FYI - 
1. iv is unique for every query string ie it is different in every query string
2. fas is encrypted using the aes-256-cbc cypher

"reconnaissance of the service" will be of little use to anyone.

**Comment by d1stox** [comment]
thank you appreciate your response

**Comment by da4nyy** [comment]
Hello, I had the same question and I wanted to confirm if there is any possibility to rename the "fas" parameter in level 3 . For instance, could we change "https://test.example.com/?fas=..&iv=.. " to https://test.example.com/?arg1=..&arg2=..? If it's possible, which file is responsible for making this change ?

**Comment by da4nyy** [comment]
Honestly, I am new to OpenNDS . I am using it now with a remote FAS in a project and I want to secure the network  ( I have already put a configured firewall in place and other things . this step is the last thing that I need to do ) . The only reason I can think of for now is to prevent the identification of the service running (Maybe other ones will come later). Anyone can identify easily the service just by typing in google "FAS captive portal" . that's my concern !

**Comment by bluewavenet** [comment]
@da4nyy 

> I have already put a configured firewall in place and other things

You do realise that OpenNDS **IS** a firewall? Of course it will co-exist with the operating system firewall as well, but is designed to enable full control within the openNDS config, so rarely is anything else required.

The rfc8910 and rfc8908 standards (CPI) and the de-facto standard canary test (CPD)  for captive portals are specifically designed to identify the presence of a captive portal to client devices, so why bother to obfuscate the query string?

Hiding the captive portal implies you are more interested in setting up a man in the middle attack system.....
