### ISSUE TITLE
TCP packets are not redirected to 2050 with DNAT rule

### ISSUE THREAD

**Issue by chaitu-tk** [openNDS/openNDS#436]
I am testing openNDS in Linux and followed the instructions, but `ndsctl status` doesn't report any clients blocking internet, looking at iptables rules, I can see that the NAT prerouting (`ndsOUT`) just accepts the packet instead of DNAT, so, it is being treated as forwarded packet and dropped by `ndsNET` in filter table.

See below output, those 18 packets in DNAT are not related to the client. All TCP SYN from client on port 80 are returned ICMP not reachable.

```
$ sudo iptables -v  -L ndsOUT -t nat 
# Warning: iptables-legacy tables present, use iptables-legacy to see them
Chain ndsOUT (1 references)
 pkts bytes target     prot opt in     out     source               destination         
    0     0 REDIRECT   tcp  --  any    any     anywhere             status.client        tcp dpt:http redir ports 2050
    0     0 RETURN     all  --  any    any     anywhere             anywhere             mark match 0x20000/0x30000
    0     0 RETURN     all  --  any    any     anywhere             anywhere             mark match 0x30000/0x30000
   18  1080 DNAT       tcp  --  any    any     anywhere             anywhere             tcp dpt:http to:172.16.0.1:2050
  304 50042 ACCEPT     all  --  any    any     anywhere             anywhere            
```

Any ideas what I am doing wrong? Just doing `systemctl stop opennds.service` client is able to access internet, so, basic routing works. This is similar to https://github.com/openNDS/openNDS/issues/170 but for online mode.

**Comment by bluewavenet** [comment]
@chaitu-tk 
To look at this properly we need to know what Linux you are using and what hardware it is running on.
Very important also is the version of openNDS you are using.

**Note**: _the last few versions have been slowly migrating away from using legacy iptables, so full functionality is not guaranteed on all Linux distributions as it depends on the degree of support for migration on the distro used.
The next major release will be fully migrated._

`# Warning: iptables-legacy tables present, use iptables-legacy to see them`

**This _possibly_ indicates you are on a distro that does not support the version of openNDS you are using.**

> This is similar to https://github.com/openNDS/openNDS/issues/170 but for online mode

The OP there seemed to find the basics of ip routing somewhat hard to grasp.....

**Comment by chaitu-tk** [comment]
Sorry, should have shared version info.

```
$ opennds -v
This is openNDS version 9.8.0

$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 22.04 LTS
Release:	22.04
Codename:	jammy

11th Gen Intel(R) Core(TM) i3-1115G4E @ 3.00GHz

$ sudo ndsctl status
==================
openNDS Status
====
Version: 9.8.0
Uptime: 11h 33m 59s
Gateway Name: [ openNDS S/N:82f1f1a2567b  ]
Debug Level: [ 1 ]
Gateway FQDN: [ status.client ]
Managed interface: "br-cap"
Upstream gateway(s) [ online:192.168.0.1,eno1 online:192.168.0.1,eno1  ]
MHD Server [ version 0.9.71 ] listening on: http://172.16.0.1:2050
Maximum Html Page size is [ 10240 ] Bytes
Preemptive Authentication is Disabled
Binauth: Disabled
Preauth Script: /usr/lib/opennds/libopennds.sh
FAS: Secure Level 1, URL: http://172.16.0.1:2050/opennds_preauth/
Client Check Interval: 15s
Rate Check Window: 2 check intervals (30s)
Preauthenticated Client Idle Timeout: 30m
Authenticated Client Idle Timeout: 120m
Download rate limit threshold (default per client): no limit
Upload rate limit threshold (default per client): no limit
Download quota (default per client): no limit
Upload quota (default per client): no limit
Total download: 10 kByte; average: 0.00 kbit/s
Total upload: 7 kByte; average: 0.00 kbit/s
====
Client authentications since start: 0
Current clients: 0
====
Trusted MAC addresses: none
Walled Garden FQDNs: none
Walled Garden Ports: none
========

```
I have tried to disable `iptables-legacy` by blacklisting the modules, but it didn't work properly.

**Comment by bluewavenet** [comment]
@chaitu-tk 

> I have tried to disable iptables-legacy

You should uninstall iptables-legacy and replace it with iptables-nft

> openNDS version 9.8.0

This is quite old and outdated. Have you chosen to use an old version for any particular reason?

Can you  show the output of `ip address` ?

**Comment by chaitu-tk** [comment]
> @chaitu-tk
> 
> > I have tried to disable iptables-legacy
> 
> You should uninstall iptables-legacy and replace it with iptables-nft
Yes, but the same debian package `iptables` offers them both, so, only way is to blacklist, I will check again to fix blacklisting.
> 
> > openNDS version 9.8.0
> 
> This is quite old and outdated. Have you chosen to use an old version for any particular reason?
Just followed https://opennds.readthedocs.io/en/stable/compile.html
> 
> Can you show the output of `ip address` ?
```
$ ip a
3: eno1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq_codel state UP group default qlen 1000
    link/ether d8:5e:d3:e3:8f:cc brd ff:ff:ff:ff:ff:ff
    altname enp0s31f6
    inet 192.168.0.109/24 brd 192.168.0.255 scope global dynamic noprefixroute eno1
       valid_lft 5207sec preferred_lft 5207sec
    inet6 fe80::8306:bfea:afe5:e80d/64 scope link noprefixroute 
       valid_lft forever preferred_lft forever
14: br-cap: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc noqueue state DOWN group default qlen 1000
    link/ether 82:f1:f1:a2:56:7b brd ff:ff:ff:ff:ff:ff
    inet 172.16.0.1/24 brd 172.16.0.255 scope global br-cap
       valid_lft forever preferred_lft forever
    inet6 fe80::80f1:f1ff:fea2:567b/64 scope link 
       valid_lft forever preferred_lft forever
15: br-lan: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc noqueue state DOWN group default qlen 1000
    link/ether aa:f6:78:88:08:46 brd ff:ff:ff:ff:ff:ff
    inet 172.17.0.1/24 brd 172.17.0.255 scope global br-lan
       valid_lft forever preferred_lft forever
    inet6 fe80::a8f6:78ff:fe88:846/64 scope link 
       valid_lft forever preferred_lft forever
       
$ brctl show
bridge name	bridge id		STP enabled	interfaces
br-cap		8000.82f1f1a2567b	no		wifi0_public
							wifi1_public
br-lan		8000.aaf678880846	no		enp175s0
							wifi0_personal
							wifi1_hidden
							wifi1_personal
```

**Comment by bluewavenet** [comment]
@chaitu-tk 

> Just followed https://opennds.readthedocs.io/en/stable/compile.html

Yes, it says:

> You can find a release version number for openNDS at https://github.com/openNDS/openNDS/releases

and

> “9.8.0” is the openNDS version we are using in this example.

The current version is 9.10.0.

> Yes, but the same debian package iptables offers them both, so, only way is to blacklist, I will check again to fix blacklisting. 

Does that mean it defaults to iptables-legacy?
That's not good. 

What does `iptables -V` show?
and what does `nft -v` show?

**Comment by chaitu-tk** [comment]
> @chaitu-tk
> 
> > Just followed https://opennds.readthedocs.io/en/stable/compile.html
> 
> Yes, it says:
> 
> > You can find a release version number for openNDS at https://github.com/openNDS/openNDS/releases
> 
> and
> 
> > “9.8.0” is the openNDS version we are using in this example.
> 
> The current version is 9.10.0.
I have upgraded both MHD and OpenNDS to `0.9.10`, it still doesn't work but now see a new issue, looks like some rule is causing this https://git.netfilter.org/iptables/commit/?id=4318961230bce82958df82b57f1796143bf2f421 
```
$ sudo iptables -v  -L 
# Warning: iptables-legacy tables present, use iptables-legacy to see them
free(): double free detected in tcache 2
Aborted
```
> 
> > Yes, but the same debian package iptables offers them both, so, only way is to blacklist, I will check again to fix blacklisting.
> 
> Does that mean it defaults to iptables-legacy? That's not good.
No, it uses both, default command `iptables` is based on `nft` hence the warning.
> 
> What does `iptables -V` show? and what does `nft -v` show?

```
 $ nft -V
nftables v1.0.2 (Lester Gooch)
  cli:		editline
  json:		yes
  minigmp:	no
  libxtables:	yes
 $ iptables -V
iptables v1.8.7 (nf_tables)
 $
```

**Comment by chaitu-tk** [comment]
FYI, I have found a way to properly blacklist `iptables-legacy` and now it seems to work, but still seeing issues with splash page, but that might just be my config, will update, thanks.

**Comment by chaitu-tk** [comment]
For anyone else stumbling on this, below works for blacklisting (standard `blacklist` doesn't work, as if some dependent modules calls the module will be loaded).

```
$ cat /etc/modprobe.d/blacklist-iptables-legacy.conf 
 install iptable_filter /bin/false
 install iptable_nat /bin/false
 install iptable_mangle /bin/false
 install iptable_raw /bin/false
 install iptable_security /bin/false
```

**Comment by chaitu-tk** [comment]
It seems to work fine now, at least my phone is detecting captive portal and opens splash page (not fully), so, closing the ticket, thanks for your help @bluewavenet .

**Comment by bluewavenet** [comment]
@chaitu-tk 
Note: As I mentioned earlier, the next major release of openNDS (v10.0.0) will not use iptables at all.
