### ISSUE TITLE
Decoding fas in javascript

### ISSUE THREAD

**Issue by leocrawford** [openNDS/openNDS#438]
I am trying to parse the `fas` field provided as a HTTP GET param when running an external FAS, using option 3 (TLS).

The decryption seems to work, but I'm getting some result which I don't expect. For example i receive.

`¡»Ø4Ùh\Q[8d6726f290fee3dc9ffc3f4984f153bb99c392c6af7899f9a92b, clientip=192.168.8.237, clientmac=00:e0:4c:53:44:58, client_type=cpd_can, gatewayname=openNDS%20Node%3ae4956e46559d%20, gatewayurl=http%3a%2f%2fstatus.client, version=9.10.0, gatewayaddress=192.168.8.1:2050, gatewaymac=e4956e46559d, authdir=opennds_auth, originurl=http%3a%2f%2fping.manjaro.org%2fcheck_network_status.txt, clientif=br-lan, themespec=(null), (null)(null)(null)(null)
`
This seems to indicate decryption is going well, but:

* The first few bytes appear to be garbage
* Then I have a hex string enconded as text. What is it? `hid`?
* The final part of the entry `(null)` repeated 4 times is not what I expect from the spec. Did I miss something?

I'd be grateful for any thoughts on what I am doing wrong, or how I should decode this? I'm also unclear from the spec where I should get `hid` from? Should it be one of the value= paramters in this section i decode? What format does it take?

For testing purposes the code runs client-side now (I know it needs to be moved server-side so that 'key' isn't exposed). This is what I do.

```
const fas_raw = urlParams.get('fas')
const iv_raw = urlParams.get('iv')

var passphrase = CryptoJS.enc.Utf8.parse("sausage".padEnd(32, '\0')); 

// Convert the IV to a WordArray 
var iv = CryptoJS.enc.Hex.parse(iv_raw); 

// Decrypt the ciphertext using the passphrase and IV 
var decrypted = CryptoJS.AES.decrypt(atob(fas_raw), passphrase, { iv: iv, keySize:256, mode: CryptoJS.mode.CBC,}); 

var plaintext = decrypted.toString(CryptoJS.enc.Latin1); 
console.log(plaintext);
```

**Comment by bluewavenet** [comment]
@leocrawford 

> Decoding fas in javascript

That is outside the scope of openNDS. It is more of an issue with JavaScript programming.
Decoding is a standard that should work in any language, but obviously the quirks of individual languages need to be taken into account.

`¡»�Ø4Ù�h��\Q[��8d6726f290fee3dc9ffc3f4984f153bb99c392c6af7899f9a92b`

Yes, garbage. It probably means you used the wrong starting point to decode the string.....

> Then I have a hex string encoded as text. What is it? hid?

Probably part of the hid string..... but it begins with garbage....

> (null) repeated 4 times

If you have not set the optional themespec parameter then null is expected.

"Hashed ID" or "hid" is the sha256 hash of the concatenation of the openNDS generated client token and the shared key.
It is encrypted into the query string as the parameter "hid".

> For testing purposes the code runs client-side

This means you will not be able to test it properly as most CPD implementations will block execution for security reasons.

Doing this in JS is fine and I know of a few implementations using node. However I would recommend sticking with PHP as it is universally available on any web server.

**Comment by leocrawford** [comment]
Thank you for the explanation. I now see that I should have decoded iv using Utf8.
