### ISSUE TITLE
Connection difference between iOS and Android

### ISSUE THREAD

**Issue by cormacstrain** [openNDS/openNDS#440]
Hi Rob

I have an instance of opennds running on an archer A7 with openwrt.  On android there are no problems connecting.  On iPhone, sporadically it will not connect telling me there is no internet connection.  There is an internet connection. The result is I dont get to the login page.

I have 'forgot' the network, restarted the iOS device, tried different iOS devices, restarted the wi-fi and the results are that sometimes I get through to the login page, in other occasions I don't.  When i don't, I get the no internet connection error. I never seem to have any such issue when testing on an android device.

I am using the walled garden and have the system locked down to two sites.  even though it tells me that there is no internet connection and doesnt direct me to the login page, it does let me access those two sites (only) if I try to surf the web.

Is there anything specific in the settings I should be looking at that might solve this?  Is this something you have heard of before or is it probably an ID10T error on my side? (most likely option)

Thanks

Cormac

**Comment by bluewavenet** [comment]
@cormacstrain 
There are no special config options for iOS. The Apple operating systems all fully comply with the CPD standards as do just about all others.

If you have the fqdn "apple.com" defined in your walled garden, this WILL break CPD as iOS uses an apple.com canary test in CPD, but other than that you should get the same result as everyone else, ie it just works. 

For your "10T" error, you might need to look closely at the iPhone in question..... The most common cause of _never_ seeing the splash page sequence is a setting to force https access at all times. But you are seeing this intermittently......

**Comment by cormacstrain** [comment]
thanks Rob. I have a second router set up so I will also try that for testing.  I've tried two iPhones and get the same kind of issue, though every once in a while they work.  So far its working on an ipad so it might be the version of iOS - maybe Ive a config error somewhere or just gremlins in this particular router. Thanks for such great software btw
