### ISSUE TITLE
AppStore FDQN Not Working ?

### ISSUE THREAD

**Issue by manar-mani** [openNDS/openNDS#444]
i have a problem regarding the FQDN of the AppStore , i added the FQDN "apps.apple.com" to the walled garden so i can have an access to the AppStore even though i don't have internet access ,it worked perfectly on Android devices and it didn't work on iOS devices. 
Those are the lines i added: 
uci add_list opennds.@opennds[0].walledgarden_fqdn_list='apps.apple.com'
uci add_list opennds.@opennds[0].walledgarden_port_list='433'

**Comment by bluewavenet** [comment]
@manar-mani 
Unfortunately the url `apps.apple.com` is an alias for `www.apple.com/ios/app-store/`.
This means that the root FQDN for the app store is `apple.com`, not `apps.apple.com`.

However the iOS CPD also uses the root FQDN `apple.com`. This means that adding `apple.com` to the walled garden will not work. This is nothing to do with openNDS, it is a problem with iOS.
