### ISSUE TITLE
How the Forwarding Authentication Service works

### ISSUE THREAD

**Issue by WenisOK** [openNDS/openNDS#445]
Hi,
This seems to be an issue during use.
The document mentions the Forwarding Authentication Service.
But I didn't understand the meaning of the document. When Captive Portal Detecti redirected to the predefined fasremotefdqn, I had already performed a secondary verification operation based on the passed parameters. How do I tell the openNDS service that a client has logged in? Is it requesting a rest API or redirecting to a certain path of the openNDS service.
<hr>
但我不明白这文档的意思。当Captive Portal Detecti重定向到预定义的fasremotefdqn时，我已经根据传递的参数执行了二次验证操作。如何告诉openNDS服务客户端已经登录？是请求rest API还是重定向到openNDS服务的某个路径。

**Comment by bluewavenet** [comment]
@WenisOK 

> How do I tell the openNDS service that a client has logged in?

There are two methods, depending on which level of FAS you are using.

You can see an example of the "redirecting to a certain path of the openNDS service" in the file `fas-hid.php`

The second method is implemented by NAT traversal allowing the remote FAS to communicate directly with the openNDS service. An example of this can be seen in the file `fas-aes-https.php`.

You can see documentation here:
https://opennds.readthedocs.io/en/stable/fas.html#overview

**Comment by bluewavenet** [comment]
@WenisOK 
Yes, line 146 defines "authaction".
It is used at line 171, ie:

```
		<form action=\"".$authaction."\" method=\"get\">
			<input type=\"hidden\" name=\"tok\" value=\"".$tok."\">
			<input type=\"hidden\" name=\"custom\" value=\"$custom\">
			<input type=\"hidden\" name=\"redir\" value=\"".$redir."\"><br>
			<input type=\"submit\" value=\"Continue\" >
		</form>

```

This form creates the "Continue" button the client user clicks to get authenticated.

**Comment by WenisOK** [comment]
Sorry I’m not php developer, I didn't understrand php syntax. I'm using node.js with express module as FAS server.
My think is that:
1. User connected ssid then CPD redirect user to FAS server
2. User typing form, such as email and password. 
3. FAS server verity user form.
4. FAS server request openNDS Auth Server.
5. openNDS Auth Server response user's login status is succuess or failed.
If is right, I saw document https://opennds.readthedocs.io/en/stable/binauth.html#binauth-command-methods.
 Is it an argument to the command line? Does it have a method such as REST API?

**Comment by WenisOK** [comment]
https://opennds.readthedocs.io/en/stable/fas.html#binauth-post-fas-processing
FAS and BinAuth are also mentioned here, but there is no specific mention of how to implement it. What I don't understand has always been in this place.

**Comment by bluewavenet** [comment]
@WenisOK 
**FAS** is a process that happens on the remote FAS server. It does validation of any credentials a client passes to it before requesting openNDS to authenticate the client.

**BinAuth** is an _optional_ post-authentication process that runs on the openNDS router. It is used typically, but not exclusively, for setting client specific quotas.

**Comment by WenisOK** [comment]
OK, In setp 4: fas server how to informs to opennds the client can authenicate? My isseus is this.

**Comment by bluewavenet** [comment]
@WenisOK 

I pointed out the code that does this earlier, it is just a simple html "get" form.
Here it is again:

> Yes, line 146 defines "authaction".
> It is used at line 171, ie:
> 
> ```
> 		<form action=\"".$authaction."\" method=\"get\">
> 			<input type=\"hidden\" name=\"tok\" value=\"".$tok."\">
> 			<input type=\"hidden\" name=\"custom\" value=\"$custom\">
> 			<input type=\"hidden\" name=\"redir\" value=\"".$redir."\"><br>
> 			<input type=\"submit\" value=\"Continue\" >
> 		</form>
> 
> ```
> 
> This form creates the "Continue" button the client user clicks to get authenticated.

The variable $authaction contains the "action" that requests the authentication.
The variables $tok, $custom and $redir contain the other required information.

The html is explained here:
https://www.w3schools.com/tags/att_form_action.asp

**Comment by bluewavenet** [comment]
@WenisOK 
If you require further help please reopen this.
