### ISSUE TITLE
Google Play Link Not Working ?

### ISSUE THREAD

**Issue by manar-mani** [openNDS/openNDS#447]
I want to redirect my consumer to the google play store to install a specific application, so i tried this link as an example: https://play.google.com/store/apps/details?id=com.facebook.katana&hl=en&gl=TN
The problem is with the devices that has Android 11 and higher the link don't redirect the user to the mobile application of google play as expected. can you help me with this ? 

Also i tried this link : "market://details?id=com.facebook.katana&hl=en&gl=TN" but this link require an internet connection, and i want my consumer to accede to the google play store even though he hasn't internet connection. so i wanna know if this link has FQDN or not or there's another link i can use to solve this problem.

**Comment by bluewavenet** [comment]
@manar-mani 
This is very similar to #444 and occurs for the same reason, I think.

See:
https://opennds.readthedocs.io/en/stable/howitworks.html#captive-portal-detection-cpd

It is a deliberate strategy by the producers of the smart device operating systems, put in place for security reasons.
