### ISSUE TITLE
MHD-single segfault

### ISSUE THREAD

**Issue by vigeruno** [openNDS/openNDS#448]
`I preferred to open a new discussion for MHD`

Data 06/04/2023 Ore 05:04:00 OpenNds Nuovo PID 1882                               <------ start openNDS
Data 06/04/2023 Ore 05:11:00 OpenNds Clienti Recuperati xx:xx:xx:xx:xx:xx  `<------ smatphone iphon 5 he is the culprit`
Data 06/04/2023 Ore 05:11:00 OpenNds Clienti Recuperati yy:yy:yy:yy:yy:yy
Data 06/04/2023 Ore 05:11:00 OpenNds Nuovo PID 17974

The crash occurred when I pressed from the smatphone  `---------> ACCEPT TERMS OF SERVICE <----------`

`Kernel registry:`
[  426.363638] MHD-single[4219]: segfault at 2 ip 00007f3d94e44260 sp 00007f3d94df5178 error 4 in libc.so[7f3d94e41000+4b000]
[  426.374738] Code: 40 00 39 c8 74 0d 49 83 c4 01 41 0f b6 04 24 84 c0 75 ef 4c 89 e0 41 5c c3 90 67 e8 5a 03 00 00 49 01 c4 4c 89 e0 41 5c c3 90 <0f> b6 17 0f b6 0e b8 01 00 00 00 38 d1 74 1a eb 27 0f 1f 80 00 00

`registry:`
Thu Apr  6 05:09:40 2023 daemon.info dnsmasq-dhcp[1]: DHCPDISCOVER(br-lan) xx:xx:xx:xx:xx:xx
Thu Apr  6 05:09:40 2023 daemon.info dnsmasq-dhcp[1]: DHCPOFFER(br-lan) 192.168.254.254 xx:xx:xx:xx:xx:xx
Thu Apr  6 05:09:40 2023 daemon.info dnsmasq-dhcp[1]: DHCPDISCOVER(br-lan) xx:xx:xx:xx:xx:xx
Thu Apr  6 05:09:40 2023 daemon.info dnsmasq-dhcp[1]: DHCPOFFER(br-lan) 192.168.254.254 xx:xx:xx:xx:xx:xx
Thu Apr  6 05:09:41 2023 daemon.info dnsmasq-dhcp[1]: DHCPREQUEST(br-lan) 192.168.254.254 xx:xx:xx:xx:xx:xx
Thu Apr  6 05:09:41 2023 daemon.info dnsmasq-dhcp[1]: DHCPACK(br-lan) 192.168.254.254 xx:xx:xx:xx:xx:xx iPhone5diFranco
Thu Apr  6 05:09:41 2023 daemon.warn odhcpd[2587]: A default route is present but there is no public prefix on lan thus we don't announce a default route!
Thu Apr  6 05:09:43 2023 daemon.notice opennds[1882]: Adding 192.168.254.254 xx:xx:xx:xx:xx:xx token 776ca9a3 to client list
Thu Apr  6 05:09:45 2023 daemon.warn odhcpd[2587]: A default route is present but there is no public prefix on lan thus we don't announce a default route!
Thu Apr  6 05:10:00 2023 cron.err crond[2687]: USER root pid 16236 cmd /etc/config/mac_clients.sh
Thu Apr  6 05:10:00 2023 daemon.notice opennds[1882]: Number of Upstream gateway(s) [ 1 ]
Thu Apr  6 05:10:00 2023 daemon.notice opennds[1882]: Number of Upstream gateway(s) [ 1 ]
Thu Apr  6 05:10:08 2023 daemon.warn odhcpd[2587]: A default route is present but there is no public prefix on lan thus we don't announce a default route!
Thu Apr  6 05:10:11 2023 daemon.info dnsmasq-dhcp[1]: DHCPDISCOVER(br-lan) yy:yy:yy:yy:yy:yy
Thu Apr  6 05:10:11 2023 daemon.info dnsmasq-dhcp[1]: DHCPOFFER(br-lan) 192.168.249.78 yy:yy:yy:yy:yy:yy
Thu Apr  6 05:10:11 2023 daemon.info dnsmasq-dhcp[1]: DHCPDISCOVER(br-lan) yy:yy:yy:yy:yy:yy
Thu Apr  6 05:10:11 2023 daemon.info dnsmasq-dhcp[1]: DHCPOFFER(br-lan) 192.168.249.78 yy:yy:yy:yy:yy:yy
Thu Apr  6 05:10:12 2023 daemon.info dnsmasq-dhcp[1]: DHCPREQUEST(br-lan) 192.168.249.78 yy:yy:yy:yy:yy:yy
Thu Apr  6 05:10:12 2023 daemon.info dnsmasq-dhcp[1]: DHCPACK(br-lan) 192.168.249.78 yy:yy:yy:yy:yy:yy
Thu Apr  6 05:10:14 2023 daemon.notice opennds[1882]: Adding 192.168.249.78 yy:yy:yy:yy:yy:yy token 81ca6ec1 to client list
Thu Apr  6 05:10:20 2023 daemon.notice opennds[1882]: Number of Upstream gateway(s) [ 1 ]
Thu Apr  6 05:10:36 2023 daemon.notice opennds[1882]: Authenticating 192.168.254.254 xx:xx:xx:xx:xx:xx
Thu Apr  6 05:10:36 2023 kern.info kernel: [  426.363638] MHD-single[4219]: segfault at 2 ip 00007f3d94e44260 sp 00007f3d94df5178 error 4 in libc.so[7f3d94e41000+4b000]
Thu Apr  6 05:10:36 2023 kern.info kernel: [  426.374738] Code: 40 00 39 c8 74 0d 49 83 c4 01 41 0f b6 04 24 84 c0 75 ef 4c 89 e0 41 5c c3 90 67 e8 5a 03 00 00 49 01 c4 4c 89 e0 41 5c c3 90 <0f> b6 17 0f b6 0e b8 01 00 00 00 38 d1 74 1a eb 27 0f 1f 80 00 00
Thu Apr  6 05:10:41 2023 daemon.notice opennds[17974]: openNDS Version 10.0.0beta is in startup

**Comment by vigeruno** [comment]
Here the loading stopped midway.

![photo_2023-04-06_10-30-27](https://user-images.githubusercontent.com/22787199/230321684-4857fc7f-1aed-44ed-b890-c79d1876e565.jpg)

**Comment by bluewavenet** [comment]
@vigeruno 
Thanks again for this.
Does this happen every time with this iphone? ie is this repeatable?

> Here the loading stopped midway.

Probably because MHD crashed...

**Comment by vigeruno** [comment]
> @vigeruno Thanks again for this. Does this happen every time with this iphone? ie is this repeatable?
> 
> > Here the loading stopped midway.
> 
> Probably because MHD crashed...

At home I managed to create the problem twice......In fact the log is from early this morning.
But I've been seeing this error often for several months.

**Comment by bluewavenet** [comment]
@vigeruno 

> Here the loading stopped midway.

Has this been fixed with the latest beta?

**Comment by vigeruno** [comment]
> @vigeruno
> 
> > Here the loading stopped midway.
> 
> Has this been fixed with the latest beta?

So far there have been no problems ...... But it's too early to tell. I keep testing.....

**Comment by bluewavenet** [comment]
I'll close this for now, we can reopen if necessary.
