### ISSUE TITLE
Script for reauthenticating users in case OpenNDS/MHD crashes

### ISSUE THREAD

**Issue by doremifajb** [openNDS/openNDS#454]
I am not supposed to hijack the thread about "traps" with this topic.  I'm interested in this script by @vigeruno. 
https://github.com/openNDS/openNDS/issues/442#issuecomment-1495615290

This line 
/usr/bin/ndsctl status | grep IP:| awk -F" "  '{print $4}' > /tmp/mac_clients

creates the list of Mac addresses of authenticated and preauthenticated users, and with the script, they will be all authenticated. @vigeruno, is that what you intended? 

I wonder if it's possible to differentiate authenticated users and preauthenticated users. That would be nice. 

              > @vigeruno
> 
> > testing the beta version at home with 4 devices and so far it hasn't given me any problems
> 
> Sounds good.
> 
> **From your pre-emptive auth script:**
> 
> ```
> if [ "$VAR1" != "$VAR2" ]; then
>    for mac in $(cat /tmp/mac_clients);
> do
> 	/usr/bin/ndsctl auth $mac
> 	logger "OpenNds Clienti Recuperati [$mac]:"
> 	echo $data OpenNds Clienti Recuperati $mac >> /etc/config/nds.log
> done
> fi
> ```
> 
> Running `ndsctl auth` from a script in a tight loop can cause a deadlock. This is a result of the way socket communications are implemented in OpenWrt and occurs when the limited queue of socket writes fills up. Instead of running ndsctl directly, an openNDS library call can be used to prevent this: https://opennds.readthedocs.io/en/stable/libraries.html#startdaemon It starts a new instance of ash for each ndsctl command, thus getting round the problem.
> 
> Something like:
> 
> ```
> if [ "$VAR1" != "$VAR2" ]; then
>    for mac in $(cat /tmp/mac_clients);
> do
> 	commandstring="/usr/bin/ndsctl auth $mac"
>         b64commandstring=$(ndsctl b64encode "$commandstring")
>        /usr/lib/opennds/libopennds.sh startdaemon "$b64commandstring"
> 
> 	logger "OpenNds Clienti Recuperati [$mac]:"
> 	echo $data OpenNds Clienti Recuperati $mac >> /etc/config/nds.log
> done
> fi
> ```
> 
> You should see in syslog, something like: `opennds[xxxxx]: libopennds - [daemon ran to termination]`
> 
> Note: The b64encode command does not use socket communications so is safe.
> 
> If you want to check if openNDS is still running you should look at the file `/tmp/ndscids/heartbeat` This contains a timestamp that is updated every "checkinterval" seconds by openNDS.

OK thank you

_Originally posted by @vigeruno in https://github.com/openNDS/openNDS/issues/442#issuecomment-1495945084_

**Comment by bluewavenet** [comment]
@doremifajb @vigeruno

This is something that a binauth script could be used for. The example script writes a log for every authenticated client.
When openNDS starts up it could look for an existing log, scan for ip addresses or mac addresses and re-authenticate them.
This would not work after a reboot because the log file is by default on /tmp, but it could be saved onto an (expendable) usb stick, if the router has a usb port.....

**Comment by vigeruno** [comment]
> I am not supposed to hijack the thread about "traps" with this topic. I'm interested in this script by @vigeruno. [#442 (comment)](https://github.com/openNDS/openNDS/issues/442#issuecomment-1495615290)
> 
> This line /usr/bin/ndsctl status | grep IP:| awk -F" " '{print $4}' > /tmp/mac_clients
> 
> creates the list of Mac addresses of authenticated and preauthenticated users, and with the script, they will be all authenticated. @vigeruno, is that what you intended?
> 
> I wonder if it's possible to differentiate authenticated users and preauthenticated users. That would be nice.
> 
> ```
>           > @vigeruno
> ```
> 
> > > testing the beta version at home with 4 devices and so far it hasn't given me any problems
> > 
> > 
> > Sounds good.
> > **From your pre-emptive auth script:**
> > ```
> > if [ "$VAR1" != "$VAR2" ]; then
> >    for mac in $(cat /tmp/mac_clients);
> > do
> > 	/usr/bin/ndsctl auth $mac
> > 	logger "OpenNds Clienti Recuperati [$mac]:"
> > 	echo $data OpenNds Clienti Recuperati $mac >> /etc/config/nds.log
> > done
> > fi
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Running `ndsctl auth` from a script in a tight loop can cause a deadlock. This is a result of the way socket communications are implemented in OpenWrt and occurs when the limited queue of socket writes fills up. Instead of running ndsctl directly, an openNDS library call can be used to prevent this: https://opennds.readthedocs.io/en/stable/libraries.html#startdaemon It starts a new instance of ash for each ndsctl command, thus getting round the problem.
> > Something like:
> > ```
> > if [ "$VAR1" != "$VAR2" ]; then
> >    for mac in $(cat /tmp/mac_clients);
> > do
> > 	commandstring="/usr/bin/ndsctl auth $mac"
> >         b64commandstring=$(ndsctl b64encode "$commandstring")
> >        /usr/lib/opennds/libopennds.sh startdaemon "$b64commandstring"
> > 
> > 	logger "OpenNds Clienti Recuperati [$mac]:"
> > 	echo $data OpenNds Clienti Recuperati $mac >> /etc/config/nds.log
> > done
> > fi
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > You should see in syslog, something like: `opennds[xxxxx]: libopennds - [daemon ran to termination]`
> > Note: The b64encode command does not use socket communications so is safe.
> > If you want to check if openNDS is still running you should look at the file `/tmp/ndscids/heartbeat` This contains a timestamp that is updated every "checkinterval" seconds by openNDS.
> 
> OK thank you
> 
> _Originally posted by @vigeruno in [#442 (comment)](https://github.com/openNDS/openNDS/issues/442#issuecomment-1495945084)_

I think it is possible to reauthenticate only ex authenticates....... That script reauthenticates all.

**Comment by vigeruno** [comment]
New Script..........

`The script deals with the start of openNDS and reloads registered and unregistered users. In the event of a crash and in the event of a failed restart, it will reload everything in 2 minutes .........Users will not notice anything because access will be free for the first two minutes and then re-authenticate automatically.... Totally transparent.`

```
#!/bin/sh
###############################################################################
#Write to rc.local
#echo 2 > /tmp/life
#
#on crond
#*/1 * * * * /etc/config/mac_clients.sh
#
#on /etc/config/mac_clients.sh permissions 777
#filename mac_clients.sh
#disable from startup openNDS......The script takes care of the startup
###############################################################################

###############################################################################
VAR1=$(pidof opennds);
VAR2=$(cat /tmp/pidofnds);
data=$(date +"Data %d/%m/%Y Ore %T")
LIFEE=$(cat /tmp/life | awk -F" "  '{print $1}');
################################################################################
if [ "$VAR1" = "" ]; then
	logger "Pid Null:"
	VAR2=$VAR1;
	LIFE=$(cat /tmp/life | awk -F" "  '{print $1 - 1}');
	echo $LIFE > /tmp/life
	fi
################################################################################	
if [ "$LIFEE" -le 0 ]; then
	echo 2 > /tmp/life
	sync; echo 3 > /proc/sys/vm/drop_caches
	/etc/init.d/opennds start
	echo $data Restart OpenNDS >> /etc/config/nds.log
	sleep 5
	VAR1=$(pidof opennds);
	echo $VAR1 > /tmp/pidofnds
	VAR2=$VAR1;
	logger "OpenNds Nuovo PID [$VAR1]:"
	echo $data OpenNds Nuovo PID $VAR1 >> /etc/config/nds.log
	mac_clients=$(cat /tmp/dhcp.leases | awk -F" "  '{print $2}' > /tmp/mac_clients);
	sleep 5
	for mac in $(cat /tmp/mac_clients);
do
	/usr/bin/ndsctl auth $mac
	logger "OpenNds Clienti Recuperati [$mac]:"
	echo $data OpenNds Clienti Recuperati $mac >> /etc/config/nds.log
	sleep 1
done
fi
#################################################################################

#################################################################################
if [ "$VAR1" != "$VAR2" ]; then
	echo $VAR1 > /tmp/pidofnds
	logger "OpenNds Nuovo PID [$VAR1]:"
	echo $data OpenNds Nuovo PID $VAR1 >> /etc/config/nds.log
	mac_clients=$(cat /tmp/dhcp.leases | awk -F" "  '{print $2}' > /tmp/mac_clients);
	sleep 5
	for mac in $(cat /tmp/mac_clients);
do
	/usr/bin/ndsctl auth $mac
	logger "OpenNds Clienti Recuperati [$mac]:"
	echo $data OpenNds Clienti Recuperati $mac >> /etc/config/nds.log
	sleep 1
done
fi
#################################################################################
exit

```

**Comment by bluewavenet** [comment]
@vigeruno @doremifajb 
Here is the log after the client logged out:
```
Tue Apr 11 11:30:26 UTC 2023, New log file created
Tue Apr 11 11:30:26 UTC 2023, method=ndsctl_auth, clientmac=b4:8c:9d:ea:26:21, bytes_incoming=0, bytes_outgoing=0, session_start=1681212626, session_end=1681299025, token=316131cb, custom=Zmlyc3RuYW1lPVJvYiwgbGFzdG5hbWU9V2hpdGUsIGVtYWlsPXJvYkBibHVlLXdhdmUubmV0, client_zone=LocalZone:phy0-ap0
Tue Apr 11 11:42:48 UTC 2023, method=client_deauth, clientmac=b4:8c:9d:ea:26:21, bytes_incoming=248458, bytes_outgoing=114260, session_start=1681212625, session_end=1681213365, token=316131cb, custom=Zmlyc3RuYW1lPVJvYiwgbGFzdG5hbWU9V2hpdGUsIGVtYWlsPXJvYkBibHVlLXdhdmUubmV0, client_zone=LocalZone:phy0-ap0

```

**Comment by bluewavenet** [comment]
@doremifajb @vigeruno 
beta-8 has automatic reauthentication on restart.
The clients inherit the remaining session time from the previous login.
This works after a restart of opennds, but does not work after a reboot because the database is stored on /tmp.

https://github.com/openNDS/openNDS/tree/master/community/testing/10.0.0-beta

It is enabled by default, and enables preemptive authentication.
Settting  `option allow_preemptive_authentication '0'` will disable it.

**Comment by doremifajb** [comment]
That's cool! But it would be better if it doesn't restart at all on its own! (But when I want to restart manually, it's useful) 
For now beta 6 is running non-stop for 4 days, and I want to see how long it runs! Today about 3 people got authenticated. 
It looks like you skipped beta-7 ? 

Preemptive enabled by default is also useful.

**Comment by bluewavenet** [comment]
@doremifajb beta-7 was the first with this re-auth thing I used for testing. Beta-8 was the finished version.
There are no other changes/fixes over beta 6 as far as the old crashes are concerned.

**Comment by bluewavenet** [comment]
@doremifajb @vigeruno 
This is an open sourced version of pre-existing proprietary code that was developed for a private project, and does not have anything to do with the crashing bugs - it just fits the title of this issue.....
