### ISSUE TITLE
Error: libopennds - [Cannot find dhcp database.]

### ISSUE THREAD

**Issue by annagat** [openNDS/openNDS#458]
Hello,

Newbie here. I am having an error "libopennds - [Cannot find dhcp database.]" and the splash page did not show up. I have only changed the GatewayInterface and GatewayName in the opennds.conf file. Please see below of the details of my setup.

Hardware: Raspberry Pi 3 B+
OS : 2023-02-21-raspios-bullseye-armhf
openNDS version: v10.0.00
libmicrohttpd version: 0.9.76

Status:
`scibiz@raspberrypi:~ $ sudo systemctl status opennds
● opennds.service - openNDS Captive Portal
     Loaded: loaded (/etc/systemd/system/opennds.service; enabled; vendor preset: enabled)
     Active: active (running) since Thu 2023-04-20 16:33:33 PST; 1min 32s ago
    Process: 523 ExecStart=/usr/bin/opennds $OPTIONS (code=exited, status=0/SUCCESS)
   Main PID: 587 (opennds)
      Tasks: 4 (limit: 1595)
        CPU: 9.214s
     CGroup: /system.slice/opennds.service
             └─587 /usr/bin/opennds

Apr 20 16:34:44 raspberrypi opennds[587]: [5][Thu Apr 20 16:34:44 2023][587](src/client_list.c:232) IP not allocated by dhcp >
Apr 20 16:34:53 raspberrypi opennds[2423]: libopennds - [Cannot find dhcp database.]
Apr 20 16:34:53 raspberrypi opennds[2423]: <28>Apr 20 16:34:53 opennds[]: libopennds - [Cannot find dhcp database.]
Apr 20 16:34:53 raspberrypi opennds[587]: [5][Thu Apr 20 16:34:53 2023][587](src/client_list.c:232) IP not allocated by dhcp >
Apr 20 16:35:00 raspberrypi opennds[2613]: libopennds - [Cannot find dhcp database.]
Apr 20 16:35:00 raspberrypi opennds[2613]: <28>Apr 20 16:35:00 opennds[]: libopennds - [Cannot find dhcp database.]
Apr 20 16:35:00 raspberrypi opennds[587]: [5][Thu Apr 20 16:35:00 2023][587](src/client_list.c:232) IP not allocated by dhcp >
Apr 20 16:35:04 raspberrypi opennds[2663]: libopennds - [Cannot find dhcp database.]
Apr 20 16:35:04 raspberrypi opennds[2663]: <28>Apr 20 16:35:04 opennds[]: libopennds - [Cannot find dhcp database.]
Apr 20 16:35:04 raspberrypi opennds[587]: [5][Thu Apr 20 16:35:04 2023][587](src/client_list.c:232) IP not allocated by dhcp >
Apr 20 16:35:08 raspberrypi opennds[2716]: libopennds - [Cannot find dhcp database.]
Apr 20 16:35:08 raspberrypi opennds[2716]: <28>Apr 20 16:35:08 opennds[]: libopennds - [Cannot find dhcp database.]
Apr 20 16:35:08 raspberrypi opennds[587]: [5][Thu Apr 20 16:35:08 2023][587](src/client_list.c:232) IP not allocated by dhcp >
lines 1-23/23 (END)`

What am I missing here?

**Comment by annagat** [comment]
By the way, I have used the following tutorial to setup the RPi as access point.
[https://www.tomshardware.com/how-to/raspberry-pi-access-point](url)

**Comment by bluewavenet** [comment]
@annagat 

> What am I missing here?

Did you read the system logs you posted? The answer is there.
ie `Cannot find dhcp database`

That tutorial is mostly irrelevant as it only deals with how to turn on the wireless in AP mode.
**_openNDS requires configuration as an ipv4 router._** with dnsmasq dhcp/dns.
See:
https://opennds.readthedocs.io/en/stable/install.html#prerequisites

A Raspberry Pi is a very bad choice for configuration as a router as it has extremely poor network hardware designed more for workstation/iot use than for router use.

For your project I would recommend a simple "travel router" hardware that will be vey cheap to buy and give vastly better performance.

**Comment by annagat** [comment]
@bluewavenet 

Thanks for the quick response. I have another server running at different port on same RPi I thought I could also run openNDS together. 

I will consider your recommendation to use a real router best suited for openNDS.

Thanks again.
