### ISSUE TITLE
splash page not showing non english character 

### ISSUE THREAD

**Issue by ManabBala** [openNDS/openNDS#461]
- both used legacy splash page also current method.
-  I have sentences in my native language. which are not showing in my CP. instead all character are being replaced by '?'.

this is the line i am using in html  or .sh file:
```
<p>(ইন্টারনেট পাওয়ার জন্য নিচে 'Continue' চাপুন)</p>
```
CP is showing me(not exact):-
```
(??????? ????? ??? ???? 'Continue' ????)
```

Tried this but no result:
```
<!DOCTYPE html>
<html lang="en">
<head>
<meta http-equiv="Content-Type" 
      content="text/html; charset=utf-8">
```

**Comment by bluewavenet** [comment]
@ManabBala 
The problem is most likely the code page.
By default utf-8 is set and this works for all languages we have tested including Chinese, Korean and Japanese.

What language are you using?

**Comment by ManabBala** [comment]
Bangla

**Comment by bluewavenet** [comment]
@ManabBala 
utf-8 is the correct code page to use. However, the editor you are using also needs to be set to save in utf-8 otherwise it will save characters the browser cannot interpret.
