### ISSUE TITLE
raspberry pi iptables

### ISSUE THREAD

**Issue by merkhabha** [openNDS/openNDS#462]
Hello,

opennds is running :

pi@raspberrypi:~/openNDS-9.10.0 $ sudo systemctl status opennds
● opennds.service - openNDS Captive Portal
     Loaded: loaded (/etc/systemd/system/opennds.service; disabled; vendor preset: enabled)
     Active: active (running) since Sat 2023-04-29 12:20:03 EDT; 5s ago
    Process: 5045 ExecStart=/usr/bin/opennds $OPTIONS (code=exited, status=0/SUCCESS)
   Main PID: 5082 (opennds)
      Tasks: 4 (limit: 3933)
        CPU: 1.896s
     CGroup: /system.slice/opennds.service
             └─5082 /usr/bin/opennds

Apr 29 12:20:04 raspberrypi opennds[5082]: [5][Sat Apr 29 12:20:04 2023][5082](src/main.c:653) Maximum Html Page size is [ 10240 ] Bytes
Apr 29 12:20:04 raspberrypi opennds[5082]: [5][Sat Apr 29 12:20:04 2023][5082](src/main.c:662) Socket access at /run/ndsctl.sock
Apr 29 12:20:04 raspberrypi opennds[5082]: [5][Sat Apr 29 12:20:04 2023][5082](src/main.c:669) Click to Continue option is Enabled.
Apr 29 12:20:04 raspberrypi opennds[5082]: [5][Sat Apr 29 12:20:04 2023][5082](src/main.c:681) Preauth is Enabled - Overriding FAS configuration.
Apr 29 12:20:04 raspberrypi opennds[5082]: [5][Sat Apr 29 12:20:04 2023][5082](src/main.c:734) sha256sum provider is available
Apr 29 12:20:04 raspberrypi opennds[5082]: [5][Sat Apr 29 12:20:04 2023][5082](src/main.c:809) FAS URL is http://192.168.4.1:2050/opennds_preauth/
Apr 29 12:20:04 raspberrypi opennds[5082]: [5][Sat Apr 29 12:20:04 2023][5082](src/main.c:882) Forwarding Authentication is Enabled.
Apr 29 12:20:04 raspberrypi opennds[5082]: [5][Sat Apr 29 12:20:04 2023][5082](src/fw_iptables.c:390) Initializing firewall rules
Apr 29 12:20:07 raspberrypi opennds[5082]: [5][Sat Apr 29 12:20:07 2023][5082](src/main.c:922) Externals flagged with debuglevel 1.
Apr 29 12:20:07 raspberrypi opennds[5082]: [5][Sat Apr 29 12:20:07 2023][5082](src/main.c:934) openNDS is now running.

But when i try to check iptables ::

pi@raspberrypi:~/openNDS-9.10.0 $ sudo iptables -L -v
free(): double free detected in tcache 2
Aborted

It is a fresh install both OS and OpenNDS

Regards

**Comment by merkhabha** [comment]
maybe because of the use of nft table ?

**Comment by bluewavenet** [comment]
@merkhabha 

> maybe because of the use of nft table ?

Correct. V9.10.0 does not use iptables.
