### ISSUE TITLE
Configuration file /etc/opennds/opennds.conf

### ISSUE THREAD

**Issue by merkhabha** [openNDS/openNDS#463]
Hello,

The file etc/opennds/opennds.conf states 
- It is deprecated and will be replaced by the UCI style configuration file as used in OpenWrt in a future release

I am using raspbian and does it mean that i won't be able to use opennds anymore ?

I cannot find "uci" tool on raspbian.

Regards

**Comment by bluewavenet** [comment]
@merkhabha 
For generic Linux support, a uci utility will be provided.

However, a Rpi is a VERY bad choice where any network routing is involved. It's designed for general purpose iot and "workstation like" uses and just does not have the required hardware to do what is required of a router if any performance is required.

I would suggest you consider using a dedicated router hardware for your project.

For example a high quality mini router supporting OpenWrt might cost less than 20% of a typical Rpi hardware kitofparts
