### ISSUE TITLE
verify username/password when FAS

### ISSUE THREAD

**Issue by brett90063** [openNDS/openNDS#468]
Hello,

I want to verify user's info, but I noticed that the option to verify the username/password has already been removed in binauth. 

Additionally, the preauth setting is not available when using FAS. Therefore, I am curious about where is the best place to verify user's info?

And what's the problem/issue when verify in binauth?

**Comment by bluewavenet** [comment]
@brett90063 
The proper place to verify username/password id in FAS.

Why do you want to verify in binauth?

You could get FAS to send a custom string containing the login credentials to binauth and have binauth verify, but then you will have to maintain a user database on the router and then **_you will get into flash wear issues as well as problems accessing the router remotely_**, so there is little point in doing this (this is why it was removed from binauth).

The example FAS scripts do a simpe "accept anything" validation, but it simple to add some validation as required.
Then the user database will be on the FAS server, eliminating the access and flash wear issues of using binauth.
