### ISSUE TITLE
opennds crashes on snapshot 

### ISSUE THREAD

**Issue by ashkanj** [openNDS/openNDS#469]
I'm getting this error on Snapshot version : 
Sun May 21 18:43:16 2023 daemon.notice opennds[7974]: ipset support is available
Sun May 21 18:43:16 2023 daemon.debug opennds[7974]: Executing command: dnsmasq --version | grep ' ipset '
Sun May 21 18:43:16 2023 daemon.debug opennds[7974]: Reading command output
Sun May 21 18:43:16 2023 daemon.debug opennds[7974]: command output: []
Sun May 21 18:43:16 2023 daemon.err opennds[7974]: Please install dnsmasq full version with ipset compile option
Sun May 21 18:43:16 2023 daemon.err opennds[7974]: Exiting...

I think this is what broke the opennds
https://github.com/openwrt/openwrt/commit/d7f378796f985c902ff7906767c275c40a15347f

```
OpenWrt SNAPSHOT r22962-cf19fd0cb5
root@OpenWrt:~# opkg list-installed dnsmasq*
dnsmasq-full - 2.89-4
root@OpenWrt:~# dnsmasq --version
Dnsmasq version 2.89  Copyright (c) 2000-2022 Simon Kelley
Compile time options: IPv6 GNU-getopt no-DBus UBus no-i18n no-IDN DHCP DHCPv6 no-Lua TFTP conntrack no-ipset nftset auth cryptohash DNSSEC no-ID loop-detect inotify dumpfile

This software comes with ABSOLUTELY NO WARRANTY.
Dnsmasq is free software, and you are welcome to redistribute it
under the terms of the GNU General Public License, version 2 or 3.
root@OpenWrt:~# 

```

**Comment by bluewavenet** [comment]
@ashkanj 
Yes, and you are probably correct with what broke it, at least that is one of the things that broke it.
This is the way of Snapshots ;-)

You will have to wait for the upcoming openNDS v10.1.0 where all these things are fixed.

v10.1.0 is fully migrated to nftables and nftsets. It should be released in the next week or two
