### ISSUE TITLE
How can I make openNDS work for individual interfaces in br-lan

### ISSUE THREAD

**Issue by stellarbnb** [openNDS/openNDS#47]
Hi, 
In my case openNDS(captive portal) currently working at bridge level(br-lan), i have three interfaces under br-lan. I want to make captive portal work for each interface.
thank you,

**Comment by bluewavenet** [comment]
@stellarbnb 
This is fully supported and you will find the documentation at:
https://opennds.readthedocs.io/en/stable/fas.html#network-zones-determining-the-interface-the-client-is-connected-to

The included fas-aes.php and login.sh scripts are working examples so worth trying out.

Do please reply here if you have any questions.

**Comment by stellarbnb** [comment]
Hi, here i'm trying with click to continue default splash page and binauth_sitewide.sh for splash_sitewide.html with login_option_enabled '0'. I want to make click to continue splash page and splash_sitewide.html pages pop up for individual interfaces in br-lan , please look at the logs I've provided above.

**Comment by bluewavenet** [comment]
@stellarbnb 
Your edit providing the logs had not shown up for my first reply! I see it now though :-D

The switch settings for wlan0, 1 and 2 are incorrect and in fact not needed at all.
openNDS can only bind to a single interface and this is usually br-lan. It does know however what interface is being used within the bridge. 

There is however no means of using this with the simple templated splash page. Instead you must use FAS or PreAuth.

Please post the output of:
`uci show opennds`
and
`uci show wireless`

Once we get these and the network config set up correctly I would suggest you first set login_option to 1. You will then see the interface in use by the client displayed on the login page.
It would be a simple matter to modify login.sh to display a different dialogue to clients on different interfaces.

**Comment by stellarbnb** [comment]
uci show opennds:
opennds.wlan0=opennds
opennds.wlan0.fwhook_enabled='1'
opennds.wlan0.use_outdated_mhd='1'
opennds.wlan0.unescape_callback_enabled='0'
opennds.wlan0.gatewayinterface='br-lan'
opennds.wlan0.maxclients='250'
opennds.wlan0.preauthidletimeout='30'
opennds.wlan0.authidletimeout='120'
opennds.wlan0.checkinterval='60'
opennds.wlan0.uploadrate='0'
opennds.wlan0.downloadrate='0'
opennds.wlan0.ratecheckwindow='2'
opennds.wlan0.uploadquota='0'
opennds.wlan0.downloadquota='0'
opennds.wlan0.authenticated_users='allow all'
opennds.wlan0.users_to_router='allow tcp port 53' 'allow udp port 53' 'allow udp port 67' 'allow tcp port 22' 'allow tcp port 23' 'allow tcp port 80' 'allow tcp port 443'
opennds.wlan0.enabled='1'
opennds.wlan0.login_option_enabled='0'
opennds.wlan0.authentication='None'
opennds.wlan0.splashpage='splash.html'
opennds.wlan0.webroot='/etc/opennds/htdocs/wlan0/'
opennds.wlan0.sessiontimeout='0'
opennds.wlan1=opennds
opennds.wlan1.fwhook_enabled='1'
opennds.wlan1.use_outdated_mhd='1'
opennds.wlan1.unescape_callback_enabled='0'
opennds.wlan1.maxclients='250'
opennds.wlan1.gatewayinterface='wlan1'
opennds.wlan1.preauthidletimeout='30'
opennds.wlan1.authidletimeout='120'
opennds.wlan1.checkinterval='60'
opennds.wlan1.uploadrate='0'
opennds.wlan1.downloadrate='0'
opennds.wlan1.ratecheckwindow='2'
opennds.wlan1.uploadquota='0'
opennds.wlan1.downloadquota='0'
opennds.wlan1.authenticated_users='allow all'
opennds.wlan1.users_to_router='allow tcp port 53' 'allow udp port 53' 'allow udp port 67' 'allow tcp port 22' 'allow tcp port 23' 'allow tcp port 80' 'allow tcp port 443'
opennds.wlan1.sessiontimeout='0'
opennds.wlan1.enabled='1'
opennds.wlan1.webroot='/etc/opennds/htdocs/wlan1/'
opennds.wlan2=opennds
opennds.wlan2.fwhook_enabled='1'
opennds.wlan2.use_outdated_mhd='1'
opennds.wlan2.unescape_callback_enabled='0'
opennds.wlan2.maxclients='250'
opennds.wlan2.preauthidletimeout='30'
opennds.wlan2.gatewayinterface='wlan2'
opennds.wlan2.checkinterval='60'
opennds.wlan2.uploadrate='0'
opennds.wlan2.downloadrate='0'
opennds.wlan2.ratecheckwindow='2'
opennds.wlan2.uploadquota='0'
opennds.wlan2.downloadquota='0'
opennds.wlan2.authenticated_users='allow all'
opennds.wlan2.users_to_router='allow tcp port 53' 'allow udp port 53' 'allow udp port 67' 'allow tcp port 22' 'allow tcp port 23' 'allow tcp port 80' 'allow tcp port 443'
opennds.wlan2.sessiontimeout='0'
opennds.wlan2.enabled='1'
opennds.wlan2.webroot='/etc/opennds/htdocs/wlan2/'

**Comment by stellarbnb** [comment]
uci show wireless:
wireless.wlan1=wifi-iface
wireless.wlan1.device='radio1'
wireless.wlan1.ifname='wlan1'
wireless.wlan1.mode='ap'
wireless.wlan1.ssid='Default-2g'
wireless.wlan1.encryption='psk-mixed'
wireless.wlan1.key='default'
wireless.wlan1.disabled='0'
wireless.wlan1.hidden='0'
wireless.wlan1.isolate='0'
wireless.wlan1.network='wan'
wireless.wlan1.vlan_id='1'
wireless.wlan2=wifi-iface
wireless.wlan2.device='radio2'
wireless.wlan2.ifname='wlan2'
wireless.wlan2.mode='ap'
wireless.wlan2.ssid='Default-5gl'
wireless.wlan2.encryption='psk-mixed'
wireless.wlan2.key='default'
wireless.wlan2.disabled='0'
wireless.wlan2.hidden='0'
wireless.wlan2.isolate='0'
wireless.wlan2.network='wan'
wireless.wlan2.vlan_id='1'
wireless.wlan0=wifi-iface
wireless.wlan0.device='radio0'
wireless.wlan0.ifname='wlan0'
wireless.wlan0.mode='ap'
wireless.wlan0.ssid='Defaul123-5gu'
wireless.wlan0.encryption='psk-mixed'
wireless.wlan0.key='defaukt'
wireless.wlan0.disabled='0'
wireless.wlan0.hidden='0'
wireless.wlan0.isolate='0'
wireless.wlan0.network='wan'
wireless.wlan0.ieee80211r='0'
wireless.wlan0.ieee80211w='1'
wireless.wlan0.uapsd='1'
wireless.wlan0.vlan_id='1'

**Comment by bluewavenet** [comment]
@stellarbnb 
The opennds config is completely wrong. It can only bind to one (1) interface. This should be br-lan.
It would be sensible to go back to the original default to get things going.

Your wireless config is also completely wrong. It does not support vlan. Your radios are associated with the wan firewall zone. You have no country, channel or power information, and no hardware path. In addition, for a captive portal it makes no sense to have encryption enabled as clients must in advance know the key.
A typical output for `uci show wireless` for a single radio would look something like:
```
wireless.radio0=wifi-device
wireless.radio0.type='mac80211'
wireless.radio0.hwmode='11g'
wireless.radio0.path='platform/10300000.wmac'
wireless.radio0.htmode='HT20'
wireless.radio0.country='GB'
wireless.radio0.channel='10'
wireless.radio0.txpower='28'
wireless.radio0.disabled='0'
wireless.default_radio0=wifi-iface
wireless.default_radio0.device='radio0'
wireless.default_radio0.network='lan'
wireless.default_radio0.mode='ap'
wireless.default_radio0.encryption='none'
wireless.default_radio0.ifname='wlan0'
wireless.default_radio0.ssid='My WiFi'
wireless.default_radio0.disabled='0'
```

In addition the network config should not contain wireless switch entries as they are meaningless.

Going back to basics would be sensible at this stage. ie getting the radios working first then installing openNDS and getting it working. Then finally modifying your FAS/Preauth to respond according to the radio connected to.

**Comment by stellarbnb** [comment]
> @stellarbnb
> Your edit providing the logs had not shown up for my first reply! I see it now though :-D
> 
> The switch settings for wlan0, 1 and 2 are incorrect and in fact not needed at all.
> openNDS can only bind to a single interface and this is usually br-lan. It does know however what interface is being used within the bridge.
> 
> There is however no means of using this with the simple templated splash page. Instead you must use FAS or PreAuth.
> 
> Please post the output of:
> `uci show opennds`
> and
> `uci show wireless`
> 
> Once we get these and the network config set up correctly I would suggest you first set login_option to 1. You will then see the interface in use by the client displayed on the login page.
> It would be a simple matter to modify login.sh to display a different dialogue to clients on different interfaces.

I have 3 interfaces under br-lan, after OpenNDS bind to br-lan, will it serve splash pages for each interface under br-lan , when client try to connect those interface to access the internet. If yes , please provide the corresponding option do I need to use(preauth, fas, binauth)
thank you

**Comment by stellarbnb** [comment]
> @stellarbnb
> The opennds config is completely wrong. It can only bind to one (1) interface. This should be br-lan.
> It would be sensible to go back to the original default to get things going.
> 
> Your wireless config is also completely wrong. It does not support vlan. Your radios are associated with the wan firewall zone. You have no country, channel or power information, and no hardware path. In addition, for a captive portal it makes no sense to have encryption enabled as clients must in advance know the key.
> A typical output for `uci show wireless` for a single radio would look something like:
> 
> ```
> wireless.radio0=wifi-device
> wireless.radio0.type='mac80211'
> wireless.radio0.hwmode='11g'
> wireless.radio0.path='platform/10300000.wmac'
> wireless.radio0.htmode='HT20'
> wireless.radio0.country='GB'
> wireless.radio0.channel='10'
> wireless.radio0.txpower='28'
> wireless.radio0.disabled='0'
> wireless.default_radio0=wifi-iface
> wireless.default_radio0.device='radio0'
> wireless.default_radio0.network='lan'
> wireless.default_radio0.mode='ap'
> wireless.default_radio0.encryption='none'
> wireless.default_radio0.ifname='wlan0'
> wireless.default_radio0.ssid='My WiFi'
> wireless.default_radio0.disabled='0'
> ```
> 
> In addition the network config should not contain wireless switch entries as they are meaningless.
> 
> Going back to basics would be sensible at this stage. ie getting the radios working first then installing openNDS and getting it working. Then finally modifying your FAS/Preauth to respond according to the radio connected to.
Hi, I copied wrongly some info: Please check the actual info below

config wifi-device 'radio0'
        option type 'mac80211'
        option hwmode '11a'
        option path 'soc/40000000.pci/pci0000:00/0000:00:00.0/0000:01:00.0'
        option htmode 'VHT80'
        option channel '149'
        option disabled '0'
config wifi-iface 'wlan1'
        option device 'radio1'
        option ifname 'wlan1'
        option mode 'ap'
        option ssid 'Default-2g'
        option encryption 'psk-mixed'
        option key 'default'
        option disabled '0'
        option hidden '0'
        option isolate '0'
        option network 'wan'
        option ieee80211r '0'
        option ieee80211w '1'
        option uapsd '1'
        option vlan_id '1'
        option vid '0'  option ieee80211v '1'
        option bss_transition '1'
        option wpa_disable_eapol_key_retries '1'
        option beacon_rate '0'
        option rssi_reject_assoc_rssi '0'

**Comment by bluewavenet** [comment]
@stellarbnb 
FAS (Forward Authentication Service) is an API for programming dynamic splash pages. PreAuth is a special case of FAS that uses the openNDS built in web server for the FAS, rather than a separate web server.

BinAuth can be used in all cases and is a local post authentication processor.

Most likely, in your case you could simply use a modified version if the login.sh PreAuth script (enabled by setting login_option to 1).

It is well worth while reading the documentation in depth:
https://opennds.readthedocs.io

I am happy to help though :-D

**Comment by bluewavenet** [comment]
@stellarbnb 

> Hi, I copied wrongly some info: Please check the actual info below

Sorry, it's still nonsense. eg You have device radio0 defined but refer to radio1 etc.

**Comment by bluewavenet** [comment]
@stellarbnb 
Why are you trying to configure 802.11 wireless into an ethernet switch?

**Comment by bluewavenet** [comment]
@stellarbnb 
Why are you associating wlan1 with the wan firewall zone?

**Comment by stellarbnb** [comment]
> @stellarbnb
> 
> > Hi, I copied wrongly some info: Please check the actual info below
> 
> Sorry, it's still nonsense. eg You have device radio0 defined but refer to radio1 etc.

sorry, the device here is radio1:
config wifi-device 'radio1'    
        option type 'mac80211'
        option hwmode '11g'
        option path 'platform/soc/a000000.wifi'
        option htmode 'HT20'
        option channel '6'
        option disabled '0'

**Comment by stellarbnb** [comment]
> @stellarbnb
> Why are you associating wlan1 with the wan firewall zone?
My all interfaces are under br-wan, Is my interfaces should be under br-lan?.  As I'm using br-lan as default interface for openNDS

**Comment by bluewavenet** [comment]
@stellarbnb 
Go back to basics and get the wireless interfaces working on your router without openNDS.
Then install openNDS without changing anything and it should just work.  Then start building your portal.
You have been overthinking the problem.

**Comment by stellarbnb** [comment]
sure, i'll try that. thank you

**Comment by stellarbnb** [comment]
Hi Rob,
I have 2 requirements, the first one is i need to provide click to continue splash page(splash.html) to all clients whoever try to connect to interfaces under br-lan and second one is to provide username and password splash page(splash_sitewide.html) to the clients who try to connect interfaces under br-lan. i'm enabling appropriate configuration options in opennds conf file.
can i achieve my requirement with the method i'm following(please check the config file options below), if not please suggest me how can i achieve samething with other methods.
example : 
for simple click to continue splash page:
        option login_option_enabled '0'
        option gatewayinterface 'br-lan'
        option fwhook_enabled '1'
        option use_outdated_mhd '1'
        option unescape_callback_enabled '0'
        option maxclients '250'
        option preauthidletimeout '30'
        option authidletimeout '120'
        option checkinterval '60'
        option uploadrate '0'
        option downloadrate '0'
        option ratecheckwindow '2'
        option uploadquota '0'
        option downloadquota '0'
        list authenticated_users 'allow all'
        list users_to_router 'allow tcp port 53'
        list users_to_router 'allow udp port 53'
        list users_to_router 'allow udp port 67'
        list users_to_router 'allow tcp port 22'
        list users_to_router 'allow tcp port 23'
        list users_to_router 'allow tcp port 80'
        list users_to_router 'allow tcp port 443'
        option enabled '1'
        option webroot '/etc/opennds/htdocs/'
        option sessiontimeout '1200'

 for simple click to username and password(splash_sitewide.html) page: 
         option login_option_enabled '0'
        option gatewayinterface 'br-lan'
        option fwhook_enabled '1'
        option use_outdated_mhd '1'
        option unescape_callback_enabled '0'
        option maxclients '250'
        option preauthidletimeout '30'
        option authidletimeout '120'
        option checkinterval '60'
        option uploadrate '0'
        option downloadrate '0'
        option ratecheckwindow '2'
        option uploadquota '0'
        option downloadquota '0'
        list authenticated_users 'allow all'
        list users_to_router 'allow tcp port 53'
        list users_to_router 'allow udp port 53'
        list users_to_router 'allow udp port 67'
        list users_to_router 'allow tcp port 22'
        list users_to_router 'allow tcp port 23'
        list users_to_router 'allow tcp port 80'
        list users_to_router 'allow tcp port 443'
        option enabled '1'
        option webroot '/etc/opennds/htdocs/'
        option sessiontimeout '1200'
        option splashpage 'splash_sitewide.html'
        option binauth '/usr/lib/opennds/binauth_sitewide.sh'

**Comment by bluewavenet** [comment]
@stellarbnb 
It is not clear, based on your previous posts, what you want to achieve.

**Firstly, can you confirm that with openNDS stopped, clients can connect to any of your 3 wireless radios and access the Internet?**

Both these configurations look correct. 
The first will give the very basic click to continue templated splash page.
The second will give the standard username/password login templated splash page.

**However you cannot have both of these at the same time.**

You can use FAS to have the equivalent of both your configurations, for example, click to continue on wlan0 and username password on wlan1. Is this what you want to achieve?

**Comment by stellarbnb** [comment]
Yes, I can see simple click to continue splash page and splash_sitewide.html pages on all interfaces but one at a time , as you said. Yes, I want to have equivalent pages with FAS and want to use different splash page images on each interface with different content and different walled garden. And if I use login_option_enabled =1, I'm getting a splash page with username and email, but I want to have a username and password. How can I attain this functionality with OpenDNS, can you provide me some insights.

**Comment by bluewavenet** [comment]
@stellarbnb 
ok, set login_option_enabled =1
Restart openNDS.

Now connect to the first SSID but do not log in. The login page should display the wireless interface being used.
Now connect to the second SSID. The login page should now display the new wireless interface.

If you see this then you are configured correctly and can move on to the next step which will be modifying the login script, login.sh.
This is an ash shell script.

Here is an example login on my test system here:

![preauth](https://user-images.githubusercontent.com/13632068/91345714-b5110d80-e7d7-11ea-9918-35e71fac2d79.jpg)

**Comment by stellarbnb** [comment]
Yes, I can see that. But how come OpenNDS provide different types of splash pages(click to continue,username and password) with different format on different interfaces? do i need to mention any respective configurations in opennds config file?.


![IMG_85A679DD5BA2-1](https://user-images.githubusercontent.com/70211030/91348886-74eb6400-e7b2-11ea-9b6c-f167fd213796.jpeg)

**Comment by bluewavenet** [comment]
@stellarbnb 

>  But how come OpenNDS provide different types of splash pages

Do you mean "But how **can** OpenNDS provide..."?

The login script detects the interface the client is using and displays it. You can modify the login script to display different splash pages depending on the interface detected. 
Read the script and see if you understand it:
`/usr/lib/opennds/login.sh`

**Comment by stellarbnb** [comment]
yes, i'll do that. thank you so much rob.

**Comment by bluewavenet** [comment]
@stellarbnb 
A quick crash course in (b)ash programming ;-)

**Comment by bluewavenet** [comment]
@stellarbnb 
Which version of openNDS are you running? (See the bottom of my login page image)
Also what is the hardware and OpenWrt version?

**Comment by stellarbnb** [comment]
openNDS :5.1.0
openwrt: 19.07

**Comment by bluewavenet** [comment]
@stellarbnb  would advise upgrading to openNDS 5.2.0 as it fixes a few bugs (now backported to OpenWrt 19.07):
```
opkg update
opkg install opennds
```

**Comment by stellarbnb** [comment]
sure, I'll do that.
thank you Rob.

**Comment by bluewavenet** [comment]
@stellarbnb 
If you have modified login.sh, back it up first as it will be overwritten with a new version.

**Comment by stellarbnb** [comment]
Sure Rob, very helpful suggestion. Thank you so much for your quick responses. talk with you soon, if I get any doubts.

**Comment by bluewavenet** [comment]
@stellarbnb 
Is this for a b&b by any chance?

**Comment by stellarbnb** [comment]
@bluewavenet Sorry, I didn't get your question
 You mean this project is for b&b? if that is the case no, bnb is my name(:

**Comment by bluewavenet** [comment]
There are a few b&bs called "Stellar" 2+2=5 :-D rofl

**Comment by stellarbnb** [comment]
Hi,
I set the sessiontimeout =300, but after connecting to one of the interfaces under br-lan. The client device is not de-authenticating after the session timeout duration(5min). I'm able to access the internet more than session time duration(indefinitely I can say?). and it's not serving splash page as expected.

**Comment by bluewavenet** [comment]
@stellarbnb 
For your current configuration, show the **full** output of:
`uci show opennds`

**Comment by stellarbnb** [comment]
opennds.opennds=opennds
opennds.opennds.fwhook_enabled='1'
opennds.opennds.use_outdated_mhd='1'
opennds.opennds.unescape_callback_enabled='0'
opennds.opennds.gatewayinterface='br-lan'
opennds.opennds.maxclients='250'
opennds.opennds.preauthidletimeout='30'
opennds.opennds.authidletimeout='120'
opennds.opennds.checkinterval='60'
opennds.opennds.uploadrate='0'
opennds.opennds.downloadrate='0'
opennds.opennds.ratecheckwindow='2'
opennds.opennds.uploadquota='0'
opennds.opennds.downloadquota='0'
opennds.opennds.authenticated_users='allow all'
opennds.opennds.users_to_router='allow tcp port 53' 'allow udp port 53' 'allow udp port 67' 'allow tcp port 22' 'allow tcp port 23' 'allow tcp port 80' 'allow tcp port 443'
opennds.opennds.enabled='1'
opennds.opennds.webroot='/etc/opennds/htdocs/'
opennds.opennds.login_option_enabled='0'
opennds.opennds.splashpage='splash_sitewide.html'
opennds.opennds.binauth='/usr/lib/opennds/binauth_sitewide.sh'
opennds.opennds.sessiontimeout='300'

**Comment by bluewavenet** [comment]
@stellarbnb 
`opennds.opennds.binauth='/usr/lib/opennds/binauth_sitewide.sh'`

This enables binauth and by default binauth_sitewide.sh overrides the config sessiontimeout with whatever is in userlist.dat for the username chosen.

By the way, you **must** use FAS or PreAuth in some form or another to get a dynamic splash page depending upon the interface the client is using. Templated authentication does not support this.

**Comment by stellarbnb** [comment]
can you share some examples to me, with pre-auth(login_option_enabled=1) method, I want to generate click to continue and a username and password splash pages instead of default username and email splash page currently in login.sh for all interfaces. And for now, I want to have the same splash page on all interfaces. In the future , I'll make different splash pages for different interfaces.

**Comment by bluewavenet** [comment]
@stellarbnb 
As I mentioned previously, /usr/lib/opennds/login.sh is an example. It is easy to modify to produce a dynamic page dependent on the interface the client is using. Changing from email to password is a trivial change in the login form html.
It is, as I mentioned, an exercise in ash programming.
If you are content with a static username/password templated page then stick with splash_sitewide.html/binauth_sitewide.sh/userlist.dat

I am happy to help you understand, but you must first at least try to get to grips with the code in login.sh

**Comment by stellarbnb** [comment]
Changing from email to password is a trivial change in the login form html.

sure, but after changing the email to password , I want it to validate the username and password that client provided with the userlist.dat. I'm getting the doubt here that how can I enable post-authentication if I use preauth method to achieve my requirement(Username and Password). What are the configuration do I need to add to opennds config file.

**Comment by bluewavenet** [comment]
@stellarbnb 
You can either:
 1. Validate against userlist.dat in the PreAuth code and not use BinAuth. or
 2. Collect username and password in PreAuth and pass to BinAuth on the query string sent by PreAuth in the auth_client call.

I say again, try to get to grips with the code in login.sh. All will be revealed. I am happy to help with concepts, but I cannot write it for you ;-)

**Comment by stellarbnb** [comment]
> 1. Validate against userlist.dat in the PreAuth code and not use BinAuth. or
> 2. Collect username and password in PreAuth and pass to BinAuth on the query string sent by PreAuth in the auth_client call.

sure rob, thank you

**Comment by stellarbnb** [comment]
Hi Rob, I'm using FAS(preauth) and I'm trying to customize my splash page, for that I'm passing my parameters through query string. When i'm accessing them in my login.sh script i'm able see the infor for title and termsandconditions correctly, but for gatewayname and successmessage i'm seeing accumulated information:

**my actual parameters are**
title=captive portal
termsandconditions: No warranty
gatewayname=Use as guest
succesmessage: Welcome to Network.

**parameters i'm getting when i'm accessing in login.sh script**
gatewayname: Use as guest,title=captive portal,termsandconditions= No warranty,succesmessage-=Welcome to Network.
successmessage:Welcome to Network.,hid=0,gatewayaddress=0,redir=https://github.com/
termsandconditions: No warranty
title=captive portal

**i want to know whether i'm using correct format while passing my parameters in querystring? please check the format below:**
snprintf(querystr, QUERYMAXLEN," ?       clientip=%s&gatewayname=%s&title=%s&termsandconditions=%s&successmessage=%s",client->ip,
 config->url_encoded_gw_name, config->page_title, config->policy, config->success_message);

**Comment by bluewavenet** [comment]
@stellarbnb 
```
snprintf(querystr, QUERYMAXLEN," ? clientip=%s&gatewayname=%s&title=%s&termsandconditions=%s&successmessage=%s",client->ip,
config->url_encoded_gw_name, config->page_title, config->policy, config->success_message);
```
What is this? Looks like C language. You are supposed to be editing login.sh
You are using Preauth, so to customise, you only need to edit the PreAuth script. login.sh **IS** the PreAuth script.
> successmessage:Welcome to Network.
> termsandconditions: No warranty
> title=captive portal
> 
These should be constants in login.sh, no need to pass them around.

From your previous posts, you said you wanted to change the email field to a password field. That is a trivial edit to login.sh.
Then once you have the user entered password you just need a new section in login.sh to open the userlist.dat file and see if there is a match.
What you are doing now makes no sense.

**Comment by stellarbnb** [comment]
currently, I'm making a click to continue splash page and the user will pass those parameters I mentioned above from the cloud , so I'm sending those parameters through query string from c code of http_microhtppd.c file(authenticated function) those parameters will change based on user choice. So I'm passing them directly and accessing those dynamically on login.sh while making preauth splash page. Instead of declaring them as constants.

**Comment by bluewavenet** [comment]
@stellarbnb 
FAS is specifically designed to do what you are now saying you want to do without having to change the source code in any way.

Do you want to differentiate between interfaces or do you want to add functionality that already exists?

You unfortunately seem to be attempting to "Reinvent the Wheel", without an understanding of how openNDS and the FAS API work.

It sounds to me like you need an external FAS residing on an Internet server. Such an external FAS can easily connect to any Internet resource and embed information it receives from your "cloud" into the splash pages served by it to the client device.

There is a fully functional example here:
/etc/opennds/fas-aes-https.php 

You should read the documentation for this:
https://opennds.readthedocs.io/en/stable/fas.html#example-script-file-fas-aes-https-php

I would advice also reading the full FAS documentation:
https://opennds.readthedocs.io/en/stable/fas.html#forwarding-authentication-service-fas

In fact it would be very sensible to read **all** the documentation:
https://opennds.readthedocs.io

I am sorry to be dismissive of your efforts, but you are currently wasting both your time and mine.

I am still happy to help with genuine questions, but you really must read both the documentation, and my replies to you.
If you find either difficult to understand, that is not a problem, as, in helping, it makes it easier for me to improve the documentation.

**Comment by NagConnectus** [comment]
@bluewavenet 
I don't want to use external web server for now. I want to use local web server with preauth method and want to produce click to continue and username,password splash pages as we discussed earlier, I'm aware that by using login.sh script I can make difference between interfaces by serving different splash pages. if i understand your question correctly**(Do you want to differentiate between interfaces or do you want to add functionality that already exists?)**. I want to make some modifications to source code according to my requirement. I didn't explain to you clearly what I'm doing and how I'm using opennds, may be that's the reason of confusion. I'm going through the documentation, I need to understand some sensible information very clearly. Thank you rob, by discussing these concepts with you I'm getting things in a better way than documentation.

**Comment by bluewavenet** [comment]
@NagConnectus

>  I want to use local web server with preauth method and want to produce click to continue and username,password splash pages

This has, as you say, been discussed at length with @stellarbnb. It is a trivial change to the existing login.sh preauth script and can simply support a unique splash page for each interface. This is the subject of this issue.

> do you want to add functionality that already exists?

Outside the scope of the current issue, @stellarbnb appears to be attempting to modify the source code to add functionality that is **ALREADY** a part of the FAS API.

> I didn't explain to you clearly what I'm doing and how I'm using opennds

No, neither of you have. I have had to search for what you are doing myself. Now, I am aware of your project.

**Please open a new issue when you have a new subject.**

I suggest the title of your next issue would be something like:
"Can I dynamically customise a PreAuth script using Opensync data in a TIP environment?"
