### ISSUE TITLE
Cannot find dhcp database

### ISSUE THREAD

**Issue by merkhabha** [openNDS/openNDS#470]
Hello,

*** Raspberry pi ::
- Linux raspberrypi 6.1.21-v8+ #1642 SMP PREEMPT Mon Apr  3 17:24:16 BST 2023 aarch64 GNU/Linux
- Description:    Debian GNU/Linux 11 (bullseye)

*** config ::
```
GatewayInterface wlan0
login_option_enabled 3
themespec_path /usr/lib/opennds/theme_click-to-continue-basic-customized.sh
maxclients 3
preauthidletimeout 3
authidletimeout 3
sessiontimeout 3


FirewallRuleSet authenticated-users {
  FirewallRule passthrough all
}

FirewallRuleSet preauthenticated-users {
}

FirewallRuleSet users-to-router {
    FirewallRule allow udp port 53
    FirewallRule allow tcp port 53
    FirewallRule allow udp port 67
}
 ```
***
Difficult to troubleshoot, but it is like the first time a station connects to ssid on wlan0, the portal displays pages normally and the last page shows an incomplete page, it is like css is not loaded, after that page there is no internet connection for the client, after a hostapd stop / start it works perfectly.

I looked at the syslog and i see this :
```

May 24 21:09:37 raspberrypi opennds[]: libopennds - [Cannot find dhcp database.]
May 24 21:09:37 raspberrypi opennds[48178]: <28>May 24 21:09:37 opennds[]: libopennds - [Cannot find dhcp database.]

```
The code shows this ::

```
dhcp_check() {
	dhcpdblocations="/tmp/dhcp.leases /var/lib/misc/dnsmasq.leases /var/db/dnsmasq.leases"
```

the file location is ok on the host ::
```

root@raspberrypi:~# ls -l /var/lib/misc/dnsmasq.leases
-rw-r--r-- 1 root root 0 May 24 21:33 /var/lib/misc/dnsmasq.leases
```

Sorry for the poor information provided, let me know how to provide more.

Regards

**Comment by merkhabha** [comment]
Hello,

Issue has been renamed as "Cannot find dhcp database".

So why do i get this message in syslog thought the file indeed exists :

# cat /var/lib/misc/dnsmasq.leases
1685016218 da:f7:0f:43:de:02 192.168.4.3 Takeshi 01:da:f7:0f:43:de:02

syslog :
May 25 07:58:38 stationalpha opennds[]: libopennds - [Cannot find dhcp database.]
May 25 07:58:38 stationalpha opennds[35125]: <28>May 25 07:58:38 opennds[]: libopennds - [Cannot find dhcp database.]

Regards

**Comment by bluewavenet** [comment]
@merkhabha 

> So why do i get this message in syslog?

v9.10.0 is known to fail on later versions of Debian or similar due to iptables-nft, nftables and dnsmasq compatibility.

This has been fixed in the upcoming openNDS v10.1.0, due for release very soon.

You could wait, or compile the beta version to be found in master here on Github.

**Comment by merkhabha** [comment]
Using the master i get ::

May 25 20:05:45 stationomega systemd[1]: Starting openNDS Captive Portal...
May 25 20:05:45 stationomega opennds[7403]: [5][Thu May 25 20:05:45 2023][7403](src/main.c:936) openNDS Version 10.1.0beta is in startup
May 25 20:05:45 stationomega opennds[7403]: [5][Thu May 25 20:05:45 2023][7403](src/conf.c:359) /etc/opennds/opennds.conf: line 1: Found configuration option: GatewayInterface
May 25 20:05:45 stationomega opennds[7403]: [5][Thu May 25 20:05:45 2023][7403](src/conf.c:359) /etc/opennds/opennds.conf: line 2: Found configuration option: login_option_enabled
May 25 20:05:45 stationomega opennds[7403]: [5][Thu May 25 20:05:45 2023][7403](src/conf.c:359) /etc/opennds/opennds.conf: line 3: Found configuration option: themespec_path
May 25 20:05:45 stationomega opennds[7403]: [5][Thu May 25 20:05:45 2023][7403](src/conf.c:359) /etc/opennds/opennds.conf: line 4: Found configuration option: maxclients
May 25 20:05:45 stationomega opennds[7403]: [5][Thu May 25 20:05:45 2023][7403](src/conf.c:359) /etc/opennds/opennds.conf: line 5: Found configuration option: preauthidletimeout
May 25 20:05:45 stationomega opennds[7403]: [5][Thu May 25 20:05:45 2023][7403](src/conf.c:359) /etc/opennds/opennds.conf: line 6: Found configuration option: authidletimeout
May 25 20:05:45 stationomega opennds[7403]: [5][Thu May 25 20:05:45 2023][7403](src/conf.c:359) /etc/opennds/opennds.conf: line 7: Found configuration option: sessiontimeout
May 25 20:05:45 stationomega opennds[7403]: [5][Thu May 25 20:05:45 2023][7403](src/conf.c:359) /etc/opennds/opennds.conf: line 8: Found configuration option: FirewallRuleSet
May 25 20:05:45 stationomega opennds[7403]: [5][Thu May 25 20:05:45 2023][7403](src/conf.c:359) /etc/opennds/opennds.conf: line 9: Found configuration option: FirewallRule
May 25 20:05:45 stationomega opennds[7403]: [5][Thu May 25 20:05:45 2023][7403](src/conf.c:359) /etc/opennds/opennds.conf: line 10: Found configuration option: FirewallRule
May 25 20:05:45 stationomega opennds[7403]: [5][Thu May 25 20:05:45 2023][7403](src/conf.c:359) /etc/opennds/opennds.conf: line 11: Found configuration option: FirewallRule
May 25 20:05:45 stationomega opennds[7403]: [5][Thu May 25 20:05:45 2023][7403](src/conf.c:359) /etc/opennds/opennds.conf: line 13: Found configuration option: FirewallRuleSet
May 25 20:05:45 stationomega opennds[7403]: [5][Thu May 25 20:05:45 2023][7403](src/conf.c:359) /etc/opennds/opennds.conf: line 15: Found configuration option: FirewallRuleSet
May 25 20:05:45 stationomega opennds[7403]: [5][Thu May 25 20:05:45 2023][7403](src/conf.c:359) /etc/opennds/opennds.conf: line 16: Found configuration option: FirewallRule
May 25 20:05:45 stationomega opennds[7403]: [5][Thu May 25 20:05:45 2023][7403](src/conf.c:359) /etc/opennds/opennds.conf: line 17: Found configuration option: FirewallRule
May 25 20:05:45 stationomega opennds[7403]: [5][Thu May 25 20:05:45 2023][7403](src/conf.c:359) /etc/opennds/opennds.conf: line 18: Found configuration option: FirewallRule
May 25 20:05:45 stationomega opennds[7403]: [5][Thu May 25 20:05:45 2023][7403](src/main.c:950) Starting as daemon, forking to background
May 25 20:05:45 stationomega systemd[1]: Started openNDS Captive Portal.
May 25 20:05:46 stationomega opennds[7442]: [5][Thu May 25 20:05:46 2023][7442](src/main.c:359) MHD version is 0.9.72
May 25 20:05:46 stationomega opennds[7442]: [5][Thu May 25 20:05:46 2023][7442](src/util.c:615) Attempting to Bind to interface: wlan0
May 25 20:05:46 stationomega opennds[7442]: [3][Thu May 25 20:05:46 2023][7442](src/main.c:391) Could not get IP address information of wlan0, exiting...
May 25 20:05:46 stationomega systemd[1]: opennds.service: Main process exited, code=exited, status=1/FAILURE
May 25 20:05:46 stationomega systemd[1]: opennds.service: Failed with result 'exit-code'.
May 25 20:05:46 stationomega dhcpcd[510]: wlan0: using static address 192.168.4.1/24
May 25 20:05:46 stationomega avahi-daemon[383]: Joining mDNS multicast group on interface wlan0.IPv4 with address 192.168.4.1.
May 25 20:05:46 stationomega avahi-daemon[383]: New relevant interface wlan0.IPv4 for mDNS.
May 25 20:05:46 stationomega avahi-daemon[383]: Registering new address record for 192.168.4.1 on wlan0.IPv4.

My python script starts and stop hostapd on demand by user interaction.

Regards

**Comment by bluewavenet** [comment]
@merkhabha 

> hostapd is not "enabled" (does not start at boot)

Then openNDS will not start if it is bound to wlan0 (as you have found out).

> My python script starts and stop hostapd on demand by user interaction

How can users connect and interact if wlan0 is down?

I would recommend that you start with a basic RaspOS install, enable wlan0 and routing, then see if openNDS works correctly.

Then you can start adding your "other" software and find out what breaks openNDS.

**Comment by bluewavenet** [comment]
@merkhabha 
Please use the "<>" symbol on the top bar of the text box when pasting unformatted text. I have updated your posts to make your example outputs readable. 

Paste in the text, highlight it and click <>.

**Comment by merkhabha** [comment]
- I installed the master version
- the behavior seen here is not seen in v9.10.0

**------------------- At boot : -------------------**

```
pi@raspberrypi:~` $ ./check_opennds
● opennds.service - openNDS Captive Portal
     Loaded: loaded (/etc/systemd/system/opennds.service; disabled; vendor preset: enabled)
     Active: active (running) since Fri 2023-05-26 08:27:20 EDT; 9s ago
    Process: 2844 ExecStart=/usr/bin/opennds $OPTIONS (code=exited, status=0/SUCCESS)
   Main PID: 2883 (opennds)
      Tasks: 4 (limit: 3933)
        CPU: 1.049s
     CGroup: /system.slice/opennds.service
             ├─2883 /usr/bin/opennds
             ├─3026 sh -c /usr/lib/opennds/libopennds.sh gatewayip "wlan0" "inet"
             ├─3027 /bin/bash /usr/lib/opennds/libopennds.sh gatewayip wlan0 inet
             └─3453 sleep 1

May 26 08:27:20 raspberrypi opennds[2844]: [5][Fri May 26 08:27:20 2023][2844](src/conf.c:359) /etc/opennds/opennds.conf: line 11: Found configuration option: FirewallRule
May 26 08:27:20 raspberrypi opennds[2844]: [5][Fri May 26 08:27:20 2023][2844](src/conf.c:359) /etc/opennds/opennds.conf: line 13: Found configuration option: FirewallRuleSet
May 26 08:27:20 raspberrypi opennds[2844]: [5][Fri May 26 08:27:20 2023][2844](src/conf.c:359) /etc/opennds/opennds.conf: line 15: Found configuration option: FirewallRuleSet
May 26 08:27:20 raspberrypi opennds[2844]: [5][Fri May 26 08:27:20 2023][2844](src/conf.c:359) /etc/opennds/opennds.conf: line 16: Found configuration option: FirewallRule
May 26 08:27:20 raspberrypi opennds[2844]: [5][Fri May 26 08:27:20 2023][2844](src/conf.c:359) /etc/opennds/opennds.conf: line 17: Found configuration option: FirewallRule
May 26 08:27:20 raspberrypi opennds[2844]: [5][Fri May 26 08:27:20 2023][2844](src/conf.c:359) /etc/opennds/opennds.conf: line 18: Found configuration option: FirewallRule
May 26 08:27:20 raspberrypi opennds[2844]: [5][Fri May 26 08:27:20 2023][2844](src/main.c:950) Starting as daemon, forking to background
May 26 08:27:20 raspberrypi systemd[1]: Started openNDS Captive Portal.
May 26 08:27:21 raspberrypi opennds[2883]: [5][Fri May 26 08:27:21 2023][2883](src/main.c:359) MHD version is 0.9.72
May 26 08:27:21 raspberrypi opennds[2883]: [5][Fri May 26 08:27:21 2023][2883](src/util.c:615) Attempting to Bind to interface: wlan0
```


```
pi@raspberrypi:~ $ ./check_wifi
● hostapd.service - Access point and authentication server for Wi-Fi and Ethernet
     Loaded: loaded (/lib/systemd/system/hostapd.service; disabled; vendor preset: enabled)
     Active: inactive (dead)
       Docs: man:hostapd(8)
```

```
pi@raspberrypi:~ $ ip a
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP group default qlen 1000
    link/ether d8:3a:dd:16:b7:5b brd ff:ff:ff:ff:ff:ff
    inet 192.168.1.123/24 brd 192.168.1.255 scope global noprefixroute eth0
       valid_lft forever preferred_lft forever
3: wlan0: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc pfifo_fast state DOWN group default qlen 1000
    link/ether d8:3a:dd:16:b7:5c brd ff:ff:ff:ff:ff:ff
```


**------------------- User starts python script (which fires up hostapd service) : -------------------**
-> wlan0 gets an IP address 

```
pi@raspberrypi:~ $ ip a
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP group default qlen 1000
    link/ether d8:3a:dd:16:b7:5b brd ff:ff:ff:ff:ff:ff
    inet 192.168.1.123/24 brd 192.168.1.255 scope global noprefixroute eth0
       valid_lft forever preferred_lft forever
3: wlan0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP group default qlen 1000
    link/ether d8:3a:dd:16:b7:5c brd ff:ff:ff:ff:ff:ff
    inet 192.168.4.1/24 brd 192.168.4.255 scope global noprefixroute wlan0
       valid_lft forever preferred_lft forever
```

-> wifi is up
```
pi@raspberrypi:~ $ ./check_wifi
● hostapd.service - Access point and authentication server for Wi-Fi and Ethernet
     Loaded: loaded (/lib/systemd/system/hostapd.service; disabled; vendor preset: enabled)
     Active: active (running) since Fri 2023-05-26 08:28:40 EDT; 8s ago
       Docs: man:hostapd(8)
    Process: 5259 ExecStart=/usr/sbin/hostapd -B -P /run/hostapd.pid -B $DAEMON_OPTS ${DAEMON_CONF} (code=exited, status=0/SUCCESS)
   Main PID: 5265 (hostapd)
      Tasks: 1 (limit: 3933)
        CPU: 26ms
     CGroup: /system.slice/hostapd.service
             └─5265 /usr/sbin/hostapd -B -P /run/hostapd.pid -B /etc/hostapd/hostapd.conf

May 26 08:28:40 raspberrypi systemd[1]: Starting Access point and authentication server for Wi-Fi and Ethernet...
May 26 08:28:40 raspberrypi hostapd[5259]: Configuration file: /etc/hostapd/hostapd.conf
May 26 08:28:40 raspberrypi hostapd[5259]: wlan0: interface state UNINITIALIZED->COUNTRY_UPDATE
May 26 08:28:40 raspberrypi hostapd[5259]: Using interface wlan0 with hwaddr d8:3a:dd:16:b7:5c and ssid "TESTSSID"
May 26 08:28:40 raspberrypi hostapd[5259]: wlan0: interface state COUNTRY_UPDATE->ENABLED
May 26 08:28:40 raspberrypi hostapd[5259]: wlan0: AP-ENABLED
May 26 08:28:40 raspberrypi systemd[1]: Started Access point and authentication server for Wi-Fi and Ethernet.
```

->opennds failed to retrieve wlan0's ip (Could not get IP address information of wlan0, exiting...)
```
pi@raspberrypi:~ $ ./check_opennds
● opennds.service - openNDS Captive Portal
     Loaded: loaded (/etc/systemd/system/opennds.service; disabled; vendor preset: enabled)
     Active: failed (Result: exit-code) since Fri 2023-05-26 08:28:46 EDT; 29s ago
    Process: 5855 ExecStart=/usr/bin/opennds $OPTIONS (code=exited, status=0/SUCCESS)
   Main PID: 5894 (code=exited, status=1/FAILURE)
        CPU: 820ms

May 26 08:28:46 raspberrypi systemd[1]: opennds.service: Scheduled restart job, restart counter is at 18.
May 26 08:28:46 raspberrypi systemd[1]: Stopped openNDS Captive Portal.
May 26 08:28:46 raspberrypi systemd[1]: opennds.service: Start request repeated too quickly.
May 26 08:28:46 raspberrypi systemd[1]: opennds.service: Failed with result 'exit-code'.
May 26 08:28:46 raspberrypi systemd[1]: Failed to start openNDS Captive Portal.
```

-> /var/log/syslog
```
May 26 08:28:44 raspberrypi opennds[5701]: [5][Fri May 26 08:28:44 2023][5701](src/main.c:359) MHD version is 0.9.72
May 26 08:28:44 raspberrypi opennds[5701]: [5][Fri May 26 08:28:44 2023][5701](src/util.c:615) Attempting to Bind to interface: wlan0
May 26 08:28:44 raspberrypi opennds[5701]: [3][Fri May 26 08:28:44 2023][5701](src/main.c:391) Could not get IP address information of wlan0, exiting...
May 26 08:28:44 raspberrypi systemd[1]: opennds.service: Main process exited, code=exited, status=1/FAILURE
May 26 08:28:44 raspberrypi systemd[1]: opennds.service: Failed with result 'exit-code'.
May 26 08:28:45 raspberrypi systemd[1]: opennds.service: Scheduled restart job, restart counter is at 17.
May 26 08:28:45 raspberrypi opennds[5855]: [5][Fri May 26 08:28:45 2023][5855](src/main.c:936) openNDS Version 10.1.0beta is in startup
May 26 08:28:45 raspberrypi opennds[5855]: [5][Fri May 26 08:28:45 2023][5855](src/conf.c:359) /etc/opennds/opennds.conf: line 1: Found configuration option: GatewayInterface
May 26 08:28:45 raspberrypi opennds[5855]: [5][Fri May 26 08:28:45 2023][5855](src/conf.c:359) /etc/opennds/opennds.conf: line 2: Found configuration option: login_option_enabled
May 26 08:28:45 raspberrypi opennds[5855]: [5][Fri May 26 08:28:45 2023][5855](src/conf.c:359) /etc/opennds/opennds.conf: line 3: Found configuration option: themespec_path
May 26 08:28:45 raspberrypi opennds[5855]: [5][Fri May 26 08:28:45 2023][5855](src/conf.c:359) /etc/opennds/opennds.conf: line 4: Found configuration option: maxclients
May 26 08:28:45 raspberrypi opennds[5855]: [5][Fri May 26 08:28:45 2023][5855](src/conf.c:359) /etc/opennds/opennds.conf: line 5: Found configuration option: preauthidletimeout
May 26 08:28:45 raspberrypi opennds[5855]: [5][Fri May 26 08:28:45 2023][5855](src/conf.c:359) /etc/opennds/opennds.conf: line 6: Found configuration option: authidletimeout
May 26 08:28:45 raspberrypi opennds[5855]: [5][Fri May 26 08:28:45 2023][5855](src/conf.c:359) /etc/opennds/opennds.conf: line 7: Found configuration option: sessiontimeout
May 26 08:28:45 raspberrypi opennds[5855]: [5][Fri May 26 08:28:45 2023][5855](src/conf.c:359) /etc/opennds/opennds.conf: line 8: Found configuration option: FirewallRuleSet
May 26 08:28:45 raspberrypi opennds[5855]: [5][Fri May 26 08:28:45 2023][5855](src/conf.c:359) /etc/opennds/opennds.conf: line 9: Found configuration option: FirewallRule
May 26 08:28:45 raspberrypi opennds[5855]: [5][Fri May 26 08:28:45 2023][5855](src/conf.c:359) /etc/opennds/opennds.conf: line 10: Found configuration option: FirewallRule
May 26 08:28:45 raspberrypi opennds[5855]: [5][Fri May 26 08:28:45 2023][5855](src/conf.c:359) /etc/opennds/opennds.conf: line 11: Found configuration option: FirewallRule
May 26 08:28:45 raspberrypi opennds[5855]: [5][Fri May 26 08:28:45 2023][5855](src/conf.c:359) /etc/opennds/opennds.conf: line 13: Found configuration option: FirewallRuleSet
May 26 08:28:45 raspberrypi opennds[5855]: [5][Fri May 26 08:28:45 2023][5855](src/conf.c:359) /etc/opennds/opennds.conf: line 15: Found configuration option: FirewallRuleSet
May 26 08:28:45 raspberrypi opennds[5855]: [5][Fri May 26 08:28:45 2023][5855](src/conf.c:359) /etc/opennds/opennds.conf: line 16: Found configuration option: FirewallRule
May 26 08:28:45 raspberrypi opennds[5855]: [5][Fri May 26 08:28:45 2023][5855](src/conf.c:359) /etc/opennds/opennds.conf: line 17: Found configuration option: FirewallRule
May 26 08:28:45 raspberrypi opennds[5855]: [5][Fri May 26 08:28:45 2023][5855](src/conf.c:359) /etc/opennds/opennds.conf: line 18: Found configuration option: FirewallRule
May 26 08:28:45 raspberrypi opennds[5855]: [5][Fri May 26 08:28:45 2023][5855](src/main.c:950) Starting as daemon, forking to background
May 26 08:28:45 raspberrypi opennds[5894]: [5][Fri May 26 08:28:45 2023][5894](src/main.c:359) MHD version is 0.9.72
May 26 08:28:45 raspberrypi opennds[5894]: [5][Fri May 26 08:28:45 2023][5894](src/util.c:615) Attempting to Bind to interface: wlan0
May 26 08:28:45 raspberrypi opennds[5894]: [3][Fri May 26 08:28:45 2023][5894](src/main.c:391) Could not get IP address information of wlan0, exiting...
May 26 08:28:45 raspberrypi systemd[1]: opennds.service: Main process exited, code=exited, status=1/FAILURE
May 26 08:28:45 raspberrypi systemd[1]: opennds.service: Failed with result 'exit-code'.
May 26 08:28:46 raspberrypi systemd[1]: opennds.service: Scheduled restart job, restart counter is at 18.
May 26 08:28:46 raspberrypi systemd[1]: opennds.service: Start request repeated too quickly.
May 26 08:28:46 raspberrypi systemd[1]: opennds.service: Failed with result 'exit-code'.
```

**Comment by merkhabha** [comment]
I think i found the source of the problem, i remember i disabled "slaac private" option on /etc/dhcpcd.conf (willing to disable all ipv6 tuff on the raspberry pi), when this option is commented we see the failure showed on the previous post.

I did the test many times (enabling it and disabling it) to validate the behaviour.

It is now working, i saw one error one time thought (in the working scenatio "slaac private" enabled) : 

`May 26 08:59:50 raspberrypi opennds[2665]: [4][Fri May 26 08:59:50 2023][2665](src/http_microhttpd.c:1025) Preauth script - failed to execute: /usr/lib/opennds/libopennds.sh, Query[?fas=aGlkPTQ4YzdhYzI0Mzc0MzVhMzcxNGNmZDZhN2Y3NTZkZjI2N>
`
but just once.

Regards.

**Comment by bluewavenet** [comment]
@merkhabha 

The current release at this moment in time is v10.1.0. See here:
https://github.com/openNDS/openNDS/releases/tag/v10.1.0
