### ISSUE TITLE
Error 403 - Forbidden - Access Denied to this Client!

### ISSUE THREAD

**Issue by nazarii-muliak** [openNDS/openNDS#471]
Hello, I have an issue with opennds package. Ive tried to set up a captive portal on the virtual machine, using standard OpenWrt configuration and all documentation available in official resources. But seems that after the installation and configuration process was performed, opennds just blocked access to my luci web interface. The version of the openWRT is 19.07. Ive tried to change the configuration and fix the bug or issue, but seems it doesn`t help. Maybe you know how this can be solved. Thank you.

**Comment by nazarii-muliak** [comment]
![Screenshot_5](https://github.com/openNDS/openNDS/assets/127757480/0c124dc2-1ab9-4c5b-926e-2c7d87ac2560)

**Comment by nazarii-muliak** [comment]
And also captive portal splash page is not showing at all. Maybe there are some intercourse issues between luci and opennds packages?

**Comment by nazarii-muliak** [comment]
Ifconfig
![image](https://github.com/openNDS/openNDS/assets/127757480/59d97efd-4e49-408d-a8cd-d71cb3d6dd7f)

**Comment by nazarii-muliak** [comment]
uci show opennds
![image](https://github.com/openNDS/openNDS/assets/127757480/01eee024-19be-40a0-bb25-b9d85b55a8f5)

**Comment by bluewavenet** [comment]
@nazarii-muliak 

> openWRT is 19.07

**This is VERY old and totally unsupported. I suggest you upgrade.** 

> opennds just blocked access to my luci web interface

Yes, it does and this is intended as port 80 is exclusively used by opennds. Luci should be available on port 443, although this is the default on recent versions of OpenWrt, on the very old and outdated 19.07.x, you may have to configure Luci to use https on 443.

> Error 403

This usually means the client has not been allocated a dhcp lease by the openNDS router. There are also other less likely reasons for this to happen.

> uci show opennds

You appear to be using options that are not supported by the very old version of openNDS available for OppenWrt 19.07.x.
Obviously these options will not work.
