### ISSUE TITLE
Ports blocked

### ISSUE THREAD

**Issue by cormacstrain** [openNDS/openNDS#474]
Hi - I am using OpenNDS is a strange way for the project I am working on in that I am by-passing the splash login page and directing it straight to a locally hosted server.  It works fine - I connect to the wi-fi, opennds grabs it and directs it straight to the server.

I realise that as I am not setting anyone up as an authenticated user, internet access is blocked.  This though is perfectly fine as the server is running in a local restaurant, providing only access to local data on the local server. The server itself though needs access to the internet in order to authentic plugins etc etc.

I want to avoid people having to click their way through a splash page because at present when they connect to the wi-fi, openNDS serves up the restaurant menu - which is exactly how we want it.

When I turn off openNDS, everything works perfectly.  When I turn on openNDS, as expected there is limited internet access.  I only need to give the server internet access to connect properly to the web.  Is there anywhere in the config where i can give the webserver authenticated access without anything being blocked -the same kind of access it gets if openNDS is off?

thank you and I do realise this isnt exactly the way you had intended the software to work so my apologies if my question is a bit different.

Cormac

**Comment by cormacstrain** [comment]
in particular, this is an error I get:

stream_socket_client(): unable to connect to ssl://[domain name removed].com:443 (Connection refused)

i set up ipset and put that domain in the walled garden, but it didnt resolve the connection issue

**Comment by bluewavenet** [comment]
@cormacstrain 

> this isnt exactly the way you had intended the software to work

That is not actually true.
Operating with remote web servers is the most common mode. Not actually logging in clients can have some unexpected side effects but that is another matter for discussion.

First of all though, please provide some basic information:
1. The hardware model of your router
2. The operating system running on your router
3.  The version of openNDS you are running

**Comment by cormacstrain** [comment]
hi rob

Archer AC1750
OpenWRT
19.07.3

**Comment by bluewavenet** [comment]
@cormacstrain 
OpenWrt 19.07.3 is very outdated and the version of openNDS is very old and no longer supported (version 5 I think).

FYI - The current version (released today) is version 10.1.0 and is VERY different in how it works internally compared with v5.x

If your AC1750 is v2 or higher then it will be fine, if it is v1, it does not have enough ram so cannot sensibly be used.

I would very strongly suggest that you upgrade to OpenWrt 22.03.5 or higher before doing any more development.

**Comment by cormacstrain** [comment]
The ac1750 is V5.  I'll upgrade and see where I am then - thanks!

**Comment by bluewavenet** [comment]
Version 10.1.0 will be available through opkg or luci in a few days (the OpenWrt build system is currently partially broken so we will have to wait for it to be fixed so it can build the new version).

**Comment by cormacstrain** [comment]
@bluewavenet  - Ive updated to OpenWRT 22.03.5 and opennds 9.10.0-1.  The config seems to be my old config (i done an upgrade and asked it to keep the settings etc).  What do you suggest I do now in order to give the server the web access it needs as I am getting the same error?

**Comment by bluewavenet** [comment]
@cormacstrain 
You should upgrade to 10.1.0 as soon as it becomes available.

Post the output of `uci export opennds`

**Comment by cormacstrain** [comment]
@bluewavenet 
I will indeed.  heres the output of the command

config opennds
	option enabled '1'
	option fwhook_enabled '1'
	option login_option_enabled '0'
	option use_outdated_mhd '1'
	option unescape_callback_enabled '0'
	option gatewayinterface 'br-lan'
	option gatewayname 'Wi-Foo'
	option maxclients '250'
	option preauthidletimeout '30'
	option authidletimeout '120'
	option sessiontimeout '1200'
	option checkinterval '60'
	option uploadrate '0'
	option downloadrate '0'
	option ratecheckwindow '2'
	option uploadquota '0'
	option downloadquota '0'
	option fasport '80'
	option fasremotefqdn 'pimento.local'
	option fasremoteip '192.168.2.100'
	option faspath '/wordpress'
	list authenticated_users 'allow all'
	list users_to_router 'allow tcp port 53'
	list users_to_router 'allow udp port 53'
	list users_to_router 'allow udp port 67'
	list users_to_router 'allow tcp port 22'
	list users_to_router 'allow tcp port 23'
	list users_to_router 'allow tcp port 80'
	list users_to_router 'allow tcp port 443'

**Comment by cormacstrain** [comment]
it all runs fine, except when I activate that one plugin which seems to want to connect externally.  On android, it still lets me to the site, on an iphone it doesn't even go there.  once I switch off the plugin, everything works again so I am assuming its the fact the plugin can't connect that is stalling the iphone connection

**Comment by cormacstrain** [comment]
at present Im not using ssl, but I will be when i have the rest running

**Comment by bluewavenet** [comment]
@cormacstrain 
There are various non-critical issues with your config, but that is just a matter of tidying up later.

By ssl, I assume you mean tls and https access to your web server.
You will only be able to do that is the web server is hosted in the Internet, otherwise customers will get dire warnings when they connect - not good for inspiring confidence.

Try this:
1. Make a note of the mac address of the web server
2.  Run `ndsctl trust <server_mac>`

Now see if it works....

**Comment by cormacstrain** [comment]
it works as I can now surf the web on the local server (so it has web access), but I must have a dodgy plugin as - though i no longer get that error and the plugin activates ok etc, it still blocks the iphone from connecting whenever the plugin is active.  Fingers crossed its a dodgy plugin as I can replace that -  you've solved a lot of issues there for me in one swoop!

Could you give me a few pointers on the issues with the config?

many thanks - you've saved me a lot of headaches

**Comment by cormacstrain** [comment]
one more question - if there is no internet access, opennds doesnt seem to operate as in the wi-fi doesnt pick up the server etc (even though its local). When I plug in the external network, it works fine.  Is there a setting I can change were it will work regardless if it has a live internet connection or not?  It would make a handy redundancy option if it would still run internally if the internet went on a client.

**Comment by cormacstrain** [comment]
hi @bluewavenet 

i put the 'ndsctl trust ' info into the local startup, but it didnt take and I had to put it in manually once it had booted - works fine when I do that but how do I get it to start automatically?

I also cant seem to connect to paypal payments for some reason through the payments (woocommerce on wordpress) section on the server.  i can though, on the same server directly go to paypal - Im assuming thats an https issue - though its just a link to paypal itself.  no card info etc is taken until the user logs into paypal.

sorry for all the questions and thank you very much for your help

**Comment by bluewavenet** [comment]
@cormacstrain 
As you are doing some development over the default installation, **_it would be sensible to at least browse through the online documentation._** Most of your questions will be answered there and it might give you some new ideas too....

> how do I get it to start automatically?

It's all in the documentation......
https://opennds.readthedocs.io/en/stable/config.html#trusted-clients

> I also cant seem to connect to paypal payments

For access to Paypal:
https://opennds.readthedocs.io/en/stable/config.html#add-paypal-to-the-walled-garden

For walled garden support, you must first install the dnsmasq-full and ipset packages (uninstalling the default dnsmasq)
**Note**: After 22.03.x, ipset is no longer required.

Remember to restart opennds after the changes to activate.

> if there is no internet access, opennds doesnt seem to operate

That is correct. I hate to say this but **_it is in the documentation...._**
https://opennds.readthedocs.io/en/stable/howitworks.html#captive-portal-detection-cpd

It is possible to make dnsmasq setting changes to force a form of "offline operation", but this is an all or nothing hack that does not necessarily work well for all clients, so should really be avoided if possible.

**Comment by cormacstrain** [comment]
Thank you. I apologise about not reading the manual.  that'll be my first port of call from now on.  

I still can't connect to paypal though - thats the final issue Im having.   

Is this config correct and if it is, can you think of any reason why the paypal link just doesnt come through (its trying to load something and its just not happening).

i have ipset and dnsmasq-full installed, dnsmasq removed, restarted the router completely and used developer tools to find all the sources and added them to the config.  Sorry for being such a pain with this.

config opennds
	option enabled '1'
	option fwhook_enabled '1'
	option login_option_enabled '0'
	option use_outdated_mhd '1'
	option unescape_callback_enabled '0'
	list trustedmac '74:46:A0:BE:90:85'
	option gatewayinterface 'br-lan'
	option gatewayname 'Wi-Foo'
	option maxclients '250'
	option preauthidletimeout '30'
	option authidletimeout '120'
	option sessiontimeout '1200'
	option checkinterval '60'
	option uploadrate '0'
	option downloadrate '0'
	option ratecheckwindow '2'
	option uploadquota '0'
	option downloadquota '0'
	option fasport '80'
	option fasremotefqdn 'pimento.local'
	option fasremoteip '192.168.2.100'
	option faspath '/index.html'
	list authenticated_users 'allow all'
	list walledgarden_fqdn_list 'paypal.com paypalobjects.com sandbox.paypal.com c.paypal.com c.sandbox.paypal.com www.sandbox.paypal.com gstatic.com fonts.gstatic.com googleapis.com fonts.googleapis.com'
	list walledgarden_port_list '443'
	list users_to_router 'allow tcp port 53'
	list users_to_router 'allow udp port 53'
	list users_to_router 'allow udp port 67'
	list users_to_router 'allow tcp port 22'
	list users_to_router 'allow tcp port 23'
	list users_to_router 'allow tcp port 80'
	list users_to_router 'allow tcp port 443'

**Comment by cormacstrain** [comment]
Note:  on the server itself all works fine.  The issue is happening when I log on tot eh wi-fi on a phone and connect.  It redirects me fine and all works, up until payment.  

If you are wondering why theres a 'index.html' in the config when Wordpress runs on php files, its a quick workaround for an issue Im having with iphones ( it redirects to the wordpress installation)

**Comment by cormacstrain** [comment]
i reinstalled everything from scratch and it all seems to be working now- thanks!

**Comment by cormacstrain** [comment]
I'll give that a whirl and see how it goes - many thanks!

**Comment by cormacstrain** [comment]
_I think if you had option faspath '/wordpress/' it would work....._

unfortunately it gives me 'no internet connection' - which I know is down to a plugin that I purchased and that has a registration (its the only one).  I even tried adding 'index.php' to point it directly to the index file.  If i turn off that plugin, I have no problem (its an essential one unfortunately so I cant do without it)

If I use a page to redirect to the wordpress directory it works fine.  I might try adding the domain of the plugin creator in to the walled garden as it was the plugin originally giving me the 'stream_socket_client(): unable to connect to ssl://[domain name removed].com:443 (Connection refused)' error

**Comment by cormacstrain** [comment]
for the record that didnt work either - but the issue isnt with openNDS, its with this particular plugin.  The redirect workaround does the job fine.  Adds 20 secs or so but thats the only downside.  thats again for all your help Rob.  really appreciated.  If you are ever in ireland, give me a shout and I'll buy you some beers

**Comment by bluewavenet** [comment]
@cormacstrain 

If your "plugin" is trying to download javascript to the client, then the client's CPD will block it. The 20 seconds is a typical timeout before wordpress gives up trying to send javascript and sends plain html.
See:
https://opennds.readthedocs.io/en/stable/customize.html?highlight=javascript#rules-for-customised-splash-pages

I think you need to think of another way of doing things so you can get rid of the plugin.....

>  If you are ever in ireland

Well I can see Northern Ireland from my office window - I'm in Kintyre so the Antrim coast is about 15 Km away - but I guess that doesn't count :-D

**Comment by bluewavenet** [comment]
CPD deliberately blocks javascript library downloads for security reasons.

Just think of the fun and games that could be had if, as a user connects their device to a wifi network, executable code could be injected immediately into the device and run at will.

You can tell "those that need to be convinced" that on a captive portal, Google and Apple are blocking it on devices running their operating systems because it leverages a potential severe security vulnerability.

**Comment by cormacstrain** [comment]
youve answered my question - its on the message bar of the phone.  That offer of a pint (or whatever your choice) will always be valid in case you're ever over this way.  you've been a massive help.  thanks!

**Comment by bluewavenet** [comment]
Try opening the browser on your phone.
Then go to http://status.client

This is the client status page.

You could change in the config the url, from `status.client` to `our.menu` or something similar.

The page you see has a login/logout button and useful info, but this is easy to change for perhaps a meta redirect to your webserver.....

**Comment by cormacstrain** [comment]
Hi rob - Im pretty certain this is my own dns issue here, but I thought I'd run it by you.  My server lies behind two routers which I have successfully managed to route the domain to.  that end all works fine.  

my issue appears when i use the local domaine (pimento.local) and local ip address in the config.  When i do that I get an error that it cant be resolved if connecting through openNDS.  

If i change the IP in the config to my external IP, it all works well. Im not expecting you to resolve this as its not an openNDS issue - Im asking on the off-chance you;d had this kind of experience yourself and might now the answer. 

I have tried using the main domain name in the config, but it gives me 'too many redirects' - I have a dynamic IP and I am using a third party to keep the domain linked to my dynamic ip - which I assume is causing some kind of loop.

 Im currently googling how to make sure openwrt can link my internal ip and server name to the external domain.   time to go to bed though I think

**Comment by bluewavenet** [comment]
When the sun rises, I wake up - It is like we are on different time zones ;-)

Firstly, the top level domain `.local` is reserved for multicast DNS and should not be used (See RFC 6762). It might work with some systems but is generally problematic.
Note: the default "local domain" in OpenWrt (and most other non-Microsoft operating systems) is `.lan`  

> my issue appears when i use the local domaine (pimento.local) and local ip address in the config

Which config, dnsmasq?

Is this Pimento in Carlow? The domain `pimento.ie` is in pending delete/redemption so dns gives no response. If this is you, you need to contact https://weare.ie immediately.

It is not clear what you are trying to do with your dns, it seems like you are making a simple task very complicated (and failing with it).

If your web server is also to be accessed from outside, using a dynamic ip address is going to be very problematic, most ISPs will severely throttle consistent Internet originated traffic to protect other customers on their domestic/business network.  Dynamic dns is really only intended to allow remote "admin" type of access with single point origin and not for general hosting use.

Full Internet web hosting or even a VPS is so cheap these days (<10 Euros per month) that there is no reason not to go for it for business use.

**Comment by cormacstrain** [comment]
failing is my middle name ;-). Yes it is Pimento in Carlow alright but its not pimento.ie i'm using as a domain - its a different one (I dont want to list the domain here on the web as its a test server).  I understand about dynamic IPs, but places like Pimento wont have static IPs - and the site itself works perfectly as a website. theres no problem with that part.  It will only be accessed internally by customers - its the like of the woocommerce app the staff would being using and a few bits that require me to have a domain at all, otherwise I'd just run it like an intranet. As I say though, the site itself is fine and as it will be local there wont be any speed issues.  I cant see it sending a massive amount of external traffic - though if it gets to issues like that then externally hosted it shall be.

I was using external hosting, but some restaurants require split printing (food to one printer, beverages to another etc) and the only way I can find to do that is have a device on the network taking in the orders and printing them to the receipt printers.  I have a Star receipt printer that will print from the web (the only one I could find that does so) but it is controlled by a plugin, rather than accepting email receipts, and doesnt offer split printing.  At the minute I have a notifications plugin than sends receipts to the server which then auto prints them to the receipt printer.

I mentioned DNS as no when I use the local IP in the openNDS config, it goes nowhere.  Once I put in the actual external address, openDNS works perfectly, so I can only assume for some reason it doesnt match the external IP with the internal IP of the server.  The domain etc does though .... it finds its way to my external IP, through the two routers and to the server.  I was just trying to figure out how openDNS doesn't.  

I need to include it in the ipset my brain just whispered to me .... if thats correct then it just shows what typing something out can do compared to sitting up all night 

When I was connecting through one router on the network, I had no problems at all connecting through openDNS -  Its the openDNS config where I was putting pimento.local.

**Comment by cormacstrain** [comment]
man, I am such an idiot.  works perfectly now Ive added it to the walled garden.  i commented out the local address as well.  RTFM i can hear you shout from here ;-)

many, many, many thanks for your help and patience Rob!
