### ISSUE TITLE
Cant get it to work on localhost

### ISSUE THREAD

**Issue by shivaa4256** [openNDS/openNDS#477]
Hello. I moved my FAS pages to the same device (rasp 4) as where OpenNDS is installed. So now all is on 1 device (before this i used 2 devices; one hosted the FAS, another hosted OpenNDS. I try to reconfigure my conf files but I can get the splash page working anymore. When the splash page is hosted on a different device it still works fine, but not with the new setup.

These are my conf files

opennds:

```
option gatewayinterface 'wlan0'
option fasport '80'
option faspath '/fas/fas.php'
option fasremoteip '192.168.68.120'
option faskey 'mysecret'
option fas_secure_enabled '0'
option fasremotefqdn 'fas.local'
##to activate the default click to continue mode:
#option login_option_enabled '1'
```
dnsmasq:

The FAS server
```
address=/fas.lan/192.168.68.120

dhcp-option-force=114,http://status.client/
```

ifconfig:

```
eth0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST> mtu 1500
inet 192.168.68.120 netmask 255.255.255.0 broadcast 192.168.68.255
inet6 fe80::ec77:58b:5f0c:78f6 prefixlen 64 scopeid 0x20
ether dc:a6:32:45:3a:cf txqueuelen 1000 (Ethernet)
RX packets 5389 bytes 714536 (697.7 KiB)
RX errors 0 dropped 0 overruns 0 frame 0
TX packets 8352 bytes 8416856 (8.0 MiB)
TX errors 0 dropped 0 overruns 0 carrier 0 collisions 0

lo: flags=73<UP,LOOPBACK,RUNNING> mtu 65536
inet 127.0.0.1 netmask 255.0.0.0
inet6 ::1 prefixlen 128 scopeid 0x10
loop txqueuelen 1000 (Local Loopback)
RX packets 823 bytes 70683 (69.0 KiB)
RX errors 0 dropped 0 overruns 0 frame 0
TX packets 823 bytes 70683 (69.0 KiB)
TX errors 0 dropped 0 overruns 0 carrier 0 collisions 0

wlan0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST> mtu 1500
inet 192.168.220.1 netmask 255.255.255.0 broadcast 192.168.220.255
inet6 fe80::77be:eb16:56b4:7f27 prefixlen 64 scopeid 0x20
ether dc:a6:32:45:3a:d0 txqueuelen 1000 (Ethernet)
RX packets 162 bytes 20186 (19.7 KiB)
RX errors 0 dropped 0 overruns 0 frame 0
TX packets 199 bytes 88260 (86.1 KiB)
TX errors 0 dropped 0 overruns 0 carrier 0 collisions 0

wlan1: flags=4163<UP,BROADCAST,RUNNING,MULTICAST> mtu 1500
inet 192.168.68.118 netmask 255.255.255.0 broadcast 192.168.68.255
inet6 fe80::d68:365f:6602:7d43 prefixlen 64 scopeid 0x20
ether 06:da:35:e0:aa:39 txqueuelen 1000 (Ethernet)
RX packets 2434 bytes 616764 (602.3 KiB)
RX errors 0 dropped 0 overruns 0 frame 0
TX packets 103 bytes 14765 (14.4 KiB)
TX errors 0 dropped 0 overruns 0 carrier 0 collisions 0
```
**_EDIT: Please use the <> symbol on the top line of the text box when entering preformatted text such as the output of commands, code etc._**

**Comment by bluewavenet** [comment]
@shivaa4256 
You do not show your network configuration. 

I would expect eth0 to be the "wan", ie the port connecting upstream to the Internet via your isp.
The address for this is 192.168.68.120. This would normally be a dhcp address allocated by the isp router so looks possibly correct.

wlan0 is configured as the openNDS gatewayinterface, and it has the address 192.168.220.1. This looks good and you must have dnsmasq serving both dhcp and dns to the wlan0 network.
This subnet must also be routed using NAT to the "wan" interface.

wlan1 looks very odd. It has the address 192.168.68.116 which is the same subnet as the "wan" interface. This will likely cause routing errors as this will be interpreted as two routes to the isp router. Additional wireless interfaces will normally be bridged to either "wan" or "lan" so that only one route to the isp router will exist.

**But the real problem here is the following line:**
`option fasport '80'`

Port 80 cannot be used as it is already in use by openNDS

You should reconfigure to use a different port, such as "4480" that is unlikely to be used by anything else.
Change it in both the openNDS and web server configs.

**Comment by shivaa4256** [comment]
Thanks for the reply. I removed wlan1 and reconfigured to port 4480 like you said. 
For now the splash page does not appear, also neverssl.com is not accessible. When i click my SSID, i need to go to neverssl.com and then it goes to fas.lan/fas.php and then it does not open the page because server can not make connection.


Digging in my conf files:

opennds

config opennds

	option gatewayinterface 'wlan0'
	option fasport '4480'
	option faspath '/fas/fas.php'
	option fasremoteip '192.168.68.120'
	option faskey 'mysecret'
	option fas_secure_enabled '0'
	option fasremotefqdn 'fas.lan'

-------------------------------------------------------

dnsmasq

# Use interface wlan0
interface=wlan0

# Use Cloudflare DNS
server=1.1.1.1

# IP range and lease time
dhcp-range=192.168.220.50,192.168.220.150,12h

# Force the clients to use the splash page URL

# Map FAS server domain name to the IP address
address=/fas.lan/192.168.68.120


dhcp-option-force=114,http://status.client

ifconfig

eth0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 192.168.68.120  netmask 255.255.255.0  broadcast 192.168.68.255
        inet6 fe80::ec77:58b:5f0c:78f6  prefixlen 64  scopeid 0x20<link>
        ether dc:a6:32:45:3a:cf  txqueuelen 1000  (Ethernet)
        RX packets 2151  bytes 634269 (619.4 KiB)
        RX errors 0  dropped 1  overruns 0  frame 0
        TX packets 3375  bytes 2439702 (2.3 MiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

lo: flags=73<UP,LOOPBACK,RUNNING>  mtu 65536
        inet 127.0.0.1  netmask 255.0.0.0
        inet6 ::1  prefixlen 128  scopeid 0x10<host>
        loop  txqueuelen 1000  (Local Loopback)
        RX packets 147  bytes 13797 (13.4 KiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 147  bytes 13797 (13.4 KiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

wlan0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 192.168.220.1  netmask 255.255.255.0  broadcast 192.168.220.255
        inet6 fe80::77be:eb16:56b4:7f27  prefixlen 64  scopeid 0x20<link>
        ether dc:a6:32:45:3a:d0  txqueuelen 1000  (Ethernet)
        RX packets 319  bytes 29465 (28.7 KiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 140  bytes 21277 (20.7 KiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

**Comment by bluewavenet** [comment]
@shivaa4256 
**_Please use the <> symbol on the top line of the text box when entering preformatted text such as the output of commands, code etc._**

I have edited your posts to make them readable.

**Comment by bluewavenet** [comment]
@shivaa4256 

You are using the wrong ip address for your FAS.
It should be on the openNDS managed interface. ie 192.168.220.1:4480
The wan interface will by default be inaccessible.


Note also, you have:

```
# Force the clients to use the splash page URL

```
This is **NOT** to force the clients to use the splash page url...
It is to work around a bug that requires the fasremotefqdn to be defined, where strictly it is not necessary in this case.

**Comment by shivaa4256** [comment]
Thanks again so much for helping out so fast. Its working perfectly now. Have a great day!

**Comment by shivaa4256** [comment]
Thanks for your help again.

Our splash page has a login form which saves to a database , hosted on the same device. But we get a connection refused on the database connection.

$servername = "192.168.68.120";
$username = "myusername";
$password = "mypassword";
$dbname = "fasdb";

Setting the port to 4480 in servername 
$servername = "192.168.68.120:4480"; 
doesnt help.

**Comment by shivaa4256** [comment]
Its working like a charm! Thanks so much.

**Comment by bluewavenet** [comment]
@shivaa4256 

> Its working perfectly now

Followed by:

> But we get a connection refused 

And finally:

> Its working like a charm!

So is it working or not?

**Comment by shivaa4256** [comment]
Yes its working fine. Thanks so much for helping!
