### ISSUE TITLE
Version 10.1.0 status.client

### ISSUE THREAD

**Issue by doremifajb** [openNDS/openNDS#479]
@bluewavenet

now the guests are all gone so I updated OpenNDS to 10.1.0 :) I was testing a few things. I realized that, on the smartphone (chrome) I can't open status.client at all, regardless of whether I'm authenticated or not: I was expecting that, if I'm not authenticated, then T of S page should show up, but it doesn't. And, if I'm authenticated, then the real "status" should show up, it doesn't either :)

I just installed firefox on my galaxy: On Firefox it's weirder: before authentication, it's the same as chrome: status.client doesn't do anything. Now, when I'm authenticated, status.clients wants me to take to luci, after "accepting risk and proceed". (but login does not work, because of my firewall)

Everything is working fine on my laptop. What am I doing wrong? On dnsmasq

```
list address '/status.client/192.168.4.1'
list address '/status.client/192.168.2.1'

```
and
`list dhcp_option_force '114,http://status.client/'`

are relevant to OpenNDS. On uhttpd,

```
list listen_http '0.0.0.0:81'
list listen_https '0.0.0.0:443'
list listen_https '[::]:443'
option redirect_https '0'
option home '/www'
option rfc1918_filter '1'
```

seem relevant. Is there anything else to look? O, config: 
`opennds.@opennds[0].users_to_router='allow tcp port 53' 'allow udp port 53' 'allow udp port 67' 'allow udp port 68' 'allow tcp port 81' 
`
My ToS lives under www/tos. 

I don't remember how it was before, but I think status.client was working. Because I helped someone whose smartphone didn't automatically show the login page. So I typed http://status.client/, then it did come.

I think I did have similar issues repeatedly, and I thought I know by now what/where can be wrong... but I couldn't figure it out. On my laptop, everything is fine.

I will appreciate your help! I started writing an email, but then I thought may be it's interesting for the others.

**Comment by bluewavenet** [comment]
@doremifajb 
Ah! I had forgotten you were using uhttpd as well.
Can you also post your opennds config please?

```
list address '/status.client/192.168.4.1'
list address '/status.client/192.168.2.1'
```
This is wrong, you have it set to two separate ip subnets. The correct one will be the one with the opennds subnet, but you should never set these yourself, they are set and unset by opennds.

Can you show the output of:
`uci export dhcp`

and

`cat /etc/config/dhcp`

When opennds is running, the uci and cat outputs should be different.

We might just need to clean up things from when you were having crashes....

**Comment by doremifajb** [comment]
OK, first` uci export dhcp: `
```

config dnsmasq
	option domainneeded '1'
	option localise_queries '1'
	option rebind_protection '1'
	option rebind_localhost '1'
	option local '/lan/'
	option domain 'lan'
	option expandhosts '1'
	option authoritative '1'
	option readethers '1'
	option leasefile '/tmp/dhcp.leases'
	option resolvfile '/tmp/resolv.conf.d/resolv.conf.auto'
	option localservice '1'
	option ednspacket_max '1232'
	list address '/status.client/192.168.4.1'
	list address '/status.client/192.168.2.1'
	list server '1.1.1.3'
	list server '1.0.0.3'

config dhcp 'lan'
	option interface 'lan'
	option start '100'
	option limit '150'
	option leasetime '12h'
	option dhcpv4 'server'
	option dhcpv6 'server'
	option ra 'server'
	list ra_flags 'managed-config'
	list ra_flags 'other-config'
	list dhcp_option_force '114,http://status.client'

config dhcp 'wan'
	option interface 'wan'
	option ignore '1'

config odhcpd 'odhcpd'
	option maindhcp '0'
	option leasefile '/tmp/hosts/odhcpd'
	option leasetrigger '/usr/sbin/odhcpd-update'
	option loglevel '4'

```
The rest is the fixed lease of various devices so I omit that part. 
```

root@OpenWrt-erx:~# cat /etc/config/dhcp

config dnsmasq
	option domainneeded '1'
	option localise_queries '1'
	option rebind_protection '1'
	option rebind_localhost '1'
	option local '/lan/'
	option domain 'lan'
	option expandhosts '1'
	option authoritative '1'
	option readethers '1'
	option leasefile '/tmp/dhcp.leases'
	option resolvfile '/tmp/resolv.conf.d/resolv.conf.auto'
	option localservice '1'
	option ednspacket_max '1232'
	list address '/status.client/192.168.4.1'
	list address '/status.client/192.168.2.1'
	list server '1.1.1.3'
	list server '1.0.0.3'

config dhcp 'lan'
	option interface 'lan'
	option start '100'
	option limit '150'
	option leasetime '12h'
	option dhcpv4 'server'
	option dhcpv6 'server'
	option ra 'server'
	list ra_flags 'managed-config'
	list ra_flags 'other-config'
	list dhcp_option_force '114,http://status.client'

config dhcp 'wan'
	option interface 'wan'
	option ignore '1'

config odhcpd 'odhcpd'
	option maindhcp '0'
	option leasefile '/tmp/hosts/odhcpd'
	option leasetrigger '/usr/sbin/odhcpd-update'
	option loglevel '4'

```

They seem to look the same, but my eyes are not catching things well... 
The address 192.168.4.1 is used when I have OpenNDS on br-lan.12: I do it to check the appearance of various things without bothering the users. 

Another thing: I have `opennds.@opennds[0].authidletimeout='600'` in config, but `ndsctl status` shows 
`Authenticated Client Idle Timeout: 120m`
and in reality, the authenticated users do disappear quickly....

**Comment by doremifajb** [comment]
Ah, and config:
```

root@OpenWrt-erx:~# uci show opennds
opennds.@opennds[0]=opennds
opennds.@opennds[0].enabled='1'
opennds.@opennds[0].fwhook_enabled='1'
opennds.@opennds[0].maxclients='250'
opennds.@opennds[0].users_to_router='allow tcp port 53' 'allow udp port 53' 'allow udp port 67' 'allow udp port 68' 'allow tcp port 81'
opennds.@opennds[0].max_download_bucket_size='1000'
opennds.@opennds[0].max_upload_bucket_size='1000'
opennds.@opennds[0].sessiontimeout='0'
opennds.@opennds[0].upload_unrestricted_bursting='1'
opennds.@opennds[0].download_unrestricted_bursting='1'
opennds.@opennds[0].debuglevel='2'
opennds.@opennds[0].allow_preemptive_authentication='1'
opennds.@opennds[0].authidletimeout='600'
opennds.@opennds[0].gatewayinterface='br-lan.11'
```

**Comment by doremifajb** [comment]
Now, I restarted OpenNDS to see if authidletimeout will be set properly, but it didn't work, so I reinstalled beta again: I don't want people to force clicking agree so often! Interestingly, the clients that the newer version kicked out got reauthenticated !

**Comment by doremifajb** [comment]
Since I brought it back to beta, I tried the test with smartphone again: actually, the problem seems to be the same: I mean status.client doesn't work on smartphone. With that particular user, where CPD wasn't working, http://status.client did help: I was able to authenticate his device. But then OpenNDS crashed.... Oh, this means, it was before beta, when OpenNDS kept crashing. I think it must have been 9.x.x. Anyway, back then, status.client worked on smartphone. I guess with 10.x.x it stopped working somehow.   

Next week, another guest whose windows laptop crashed OpenNDS about a year ago is going to come again. I'm curious what would happen....

**Comment by bluewavenet** [comment]
@doremifajb 
Your opennds config confirms you are only using uhttpd for serving your ToS and not for anything else.

> They seem to look the same, but my eyes are not catching things well...

**They are the same - And that is the problem, they should not be.** At some stage you must have run a "uci commit" while opennds was running or crashed.

We should also check `/etc/hosts` in case we added anything there while we were beta testing, **so please show `cat /etc/hosts`**

Currently, when you try to go to http://status.client dnsmasq is trying to resolve the ip address, but there are two separate entries in the config. I am not sure what happens, I think for the standard dnsmasq package, no ip address is returned and for dnsmasq-full the two ip addresses are returned on a round robin basis - not sure. But this is why it does not work.

**_You need to clean up `/etc/config/dhcp` manually while opennds is stopped._**

Open `/etc/config/dhcp` in a text editor and make it look like this (or overwrite with a file containing this):

```
config dnsmasq
	option domainneeded '1'
	option localise_queries '1'
	option rebind_protection '1'
	option rebind_localhost '1'
	option local '/lan/'
	option domain 'lan'
	option expandhosts '1'
	option authoritative '1'
	option readethers '1'
	option leasefile '/tmp/dhcp.leases'
	option resolvfile '/tmp/resolv.conf.d/resolv.conf.auto'
	option localservice '1'
	option ednspacket_max '1232'
	list server '1.1.1.3'
	list server '1.0.0.3'

config dhcp 'lan'
	option interface 'lan'
	option start '100'
	option limit '150'
	option leasetime '12h'
	option dhcpv4 'server'
	option dhcpv6 'server'
	option ra 'server'
	list ra_flags 'managed-config'
	list ra_flags 'other-config'

config dhcp 'wan'
	option interface 'wan'
	option ignore '1'

config odhcpd 'odhcpd'
	option maindhcp '0'
	option leasefile '/tmp/hosts/odhcpd'
	option leasetrigger '/usr/sbin/odhcpd-update'
	option loglevel '4'


```

Then restart dnsmasq with `service dnsmasq restart`

Finally start opennds again etc.

**Comment by bluewavenet** [comment]
@doremifajb 
```
Another thing: I have
`opennds.@opennds[0].authidletimeout='600'`
in config, but ndsctl status shows
`Authenticated Client Idle Timeout: 120m`
```
Ah yes, this is an omission in the config refactoring for 10.1.0.
"authidletimeout" has always been "auth_idle_timeout" internally and a translation was not added to the config processing.

To make it work, change the config setting from:
`    option authidletimeout '600'`

to

`    option auth_idle_timeout '600'`

The question is, should this be corrected as a bug in the release, or should it be made "official"?

Note: The same applies to preauthidletimeout, this will now be preauth_idle_timeout in the config.

Let me know your thoughts on this.
I think it should be made official!

**Comment by doremifajb** [comment]
ooooh, that's right, I had forgotten that I had this problem earlier, doing `uci commit` while OpenNDS is running and something goes wrong!

On the other hand, it shouldn't be.... because as a routine, you are supposed to do `uci set xxxx`, then `uci commit opennds`, and `service opennds restart`, so one would think that it's normal to do `uci commit` while opennds is running !
I edited dhcp and restarted dnsmasq, this came out: 
```
root@OpenWrt-erx:~# service dnsmasq restart
udhcpc: started, v1.35.0
udhcpc: broadcasting discover
udhcpc: no lease, failing
```
This many times. Is it normal? 

Now I uninstalled beta, then this message came... I wonder if it's OK. 
Command failed: ubus call service delete { "name": "opennds" } (Not found)

Anyway, now the newer version is running, with correct authidletimeout  with _ _ . But status.client on smartphone doesn't seem to work yet.... I realized that on my firewall, I allowed extra ports like 2050, because at some point you had a version, where it was assumed that the firewall for the interface for OpenNDS is "neutral". Now I made it my standard guests rules: 53 67 68. Now smartphone will not try to open luci over status.client, which is good. But it doesn't get to the proper place, before or after authentication.  

That's not super important, though, as long as people are getting to the portal. Nobody wants to check his status or log out. 

As for authidletimeout, I think it is better if it works without manually translating it, i.e. if you implement translation, so that people can keep using old config file. In your documentation it's without _. I think, if there is no downside in keeping it, it can stay that way..... but as long as you can make sure that everybody knows that it doesn't work without _ anymore, then it doesn't matter much.

**Comment by bluewavenet** [comment]
@doremifajb 

>  as a routine, you are supposed to do uci set xxxx, then uci commit 

No, only if you want the changes to be permanent and you want to write the changes to /etc/config/ and have them activated on reboot.
The uci functionality is specially designed to minimise writes to the flash memory (because flash wears out if you write to it too much). Uci keeps its "active" configs in ram/ramdisk.

`udhcpc: no lease, failing`

udhcpd is the dhcp client that is running on the wan interface. It is trying to get an ip address from your isp router, and failing. udhcp gets restarted when dnsmasq restarts.
When it fails, udhcpd will continue to use the ip address it was given previously until it actually expires. This implies the isp router's dhcp server is not responding for some reason.

`Command failed: ubus call service delete { "name": "opennds" } (Not found)`

This means something/someone issued a ubus call to shutdown opennds. This is not normal. Maybe it is opkg when you do `opkg remove opennds`......

> But status.client on smartphone doesn't seem to work yet.

This might be caching on the smartphone.
Test it by doing, on the router, `ping status.client`

If that works then the problem is almost certainly caching, so reboot the smartphone and try again.

> Now I made it my standard guests rules: 53 67 68.

OpenNDS has higher priority in nftables than OpenWrt's FW4 because openNDS is a dynamic firewall daemon, whereas FW4 is a static nftables configuration utility and not a daemon. This means any rules you might set in FW4 for access to the router must be and will be bypassed and ignored, otherwise the nft ruleset will be dependent on the load order of openNDS/FW4 which can change depending on all sorts of things. 

> as long as you can make sure that everybody knows that it doesn't work without _ anymore

Yes of course, the documentation needs to be updated....

**Comment by doremifajb** [comment]
Just to be sure: this

`opennds.@opennds[0].users_to_router='allow tcp port 53' 'allow udp port 53' 'allow udp port 67' 'allow udp port 68' 'allow tcp port 81'`

is for the authenticated users, right? 

Now I cleared cache and restarted the smartphone. Indeed, it's working now ! Both on chrome and firefox :) 

As for

> It is trying to get an ip address from your isp router

Do you mean WAN side address of ERX given by my ISP router, or you meant public IP address? WAN address is shown in the list of the interfaces (on luci), so I suppose ERX knows its WAN address.... Do I really need udhcpd to be working well? 

As for "_", I also have
`opennds.@opennds[0].sessiontimeout='0'`

Does that also have to be session_timeout ? Or is it working ? I can't see what's in effect, because `ndsctl status` doesn't show it. 
I think, if authidletimeout has to be auth_idle_timeout, then all the "put together" terms have to be broken into existing English words, separated by "_", otherwise you can't remember which ones are separated and which ones are not. debug_level, gateway_interface, max_clients, etc. But then it's too much change. Besides, people seem to be using smartphone a lot for a lot of things, then getting "_" is quite a bit more troublesome than it is on a computer. I think it will be nicer if you make it so that "_" wont be necessary. 
I personally cannot stand using smartphone for typing. It drives me crazy. I like normal keyboard. I hope it's not going to disappear, with advancement of AI and all.

**Comment by bluewavenet** [comment]
@doremifajb 

> is for the authenticated users, right?

No, it is for any access to the router, not_yet_preauthenticated, preauthenticated and authenticated. ie any device connected to the network.



>     It is trying to get an ip address from your isp router

I mean it is trying to get an ip address for its wan interface from the isp's router. This is not the public ip.

> "put together" terms

sessiontimeout is ok.

There is already a mix of "put together" and "underscored". So maybe the next release should rationalise and go either all put together or all underscored.

It is, after the refactoring of the config processing for 10.1.0, very easy to change one way or another (whereas before it was very convoluted).

We have your ease of typing against my ease of reading so far :-D

> I like normal keyboard. I hope it's not going to disappear, with advancement of AI and all.

HaHa! Once you get your NeuroLink implant you will just have to think of the text you want and it will be done ;-)

https://neuralink.com/

**Comment by bluewavenet** [comment]
@doremifajb 
Well thinking about it:

> maybe the next release should rationalise and go either all put together or all underscored.

Or return to as it was with v9.
All 3 options are the same amount of work and it is trivial. I am leaning towards returning to as it was... not sure.
More feedback needed ;-)

**Comment by doremifajb** [comment]
I think leaving things as they are is better, as long as nobody had problem with it. Otherwise, someone like me is going to get freak out and say "I did it right, but it didn't work!" 

It's amazing about neurallink ! I hope the CPU is going to be enough for my ever-wandering thinking !  Stephen Hawking would have benefited a lot, though it seems like he did get what he needed. That was amazing enough.

**Comment by bluewavenet** [comment]
@doremifajb 
You mean return to as it was with v9  or leave it as it is now in v10?

**Comment by doremifajb** [comment]
I meant return to as it was with v9. Basically so that the config file will be usable. Well, that's the only point, so as long as you can make it so that either way, auth_idle_timeout or authidletimeout works, that's also OK.

**Comment by bluewavenet** [comment]
@doremifajb 
Ok, reverted to how it was with v9, so we will get 10.1.1 soon ;-)

**Comment by doremifajb** [comment]
Is auth_idle_timeout going to work as well ? Just because I already rewrote that part....

**Comment by bluewavenet** [comment]
@doremifajb 

> Is auth_idle_timeout going to work as well ?

Errm - no. I thought you did not like it.  :-D

I suppose it could accept both, but then it gets to be a but of a faff.....

**Comment by doremifajb** [comment]
Yeah I mean, I would have liked if authidletimeout worked right away. If it's complicated to make both two work, then it's alright, it still better if authidletimeout is kept, because I'm most likely looking at older config often. I will just put both of them in the current config, so that one of them should work. I hope I'm not going to screw anything up.... the one that doesn't work will be simply ignored, right? This way, when I update, the right version is already there.

**Comment by bluewavenet** [comment]
Oh yes, cool, the one not recognised will indeed be ignored :-D
