### ISSUE TITLE
Version: 10.1.0beta to 10.1.0-1

### ISSUE THREAD

**Issue by vigeruno** [openNDS/openNDS#480]
I've been using the beta version compiled by me for a while and so far I haven't encountered any malfunctions......... What has changed with 10.1.0-1?

**Comment by bluewavenet** [comment]
@vigeruno 
I don't know at which stage you compiled the beta, but it was iterating fairly rapidly until the release.
See:
https://github.com/openNDS/openNDS/blob/master/ChangeLog
