### ISSUE TITLE
Multiple instances of Opennds in one openwrt

### ISSUE THREAD

**Issue by SergioDG-YCC** [openNDS/openNDS#482]
Multiple instances of Opennds in one openwrt

Hello bluewavenet. I need to consult, is it possible to run two instances of Opennds within the same Openwrt router? in different nets obviously.
I explain my circumstance:
  - I use hotspot 1 to serve clients on the net 10.10.10.0/24 through FAS (Passenger viewing streaming) working very well.
  - I want to create another net, eg: 20.20.20.0/24 for another Wi-Fi signal, which serves hostesses, and provide them with a hostspot where they can view remote control, calls, etc.
Can I get 2 different hotspots, or 2 separate opennds processes? How would you do it?
I tried to use Chilli along with Opennds but it was very dramatic and prevented the normal opennds process. I didn't try Nodogsplash because I imagine they use the same or similar names and resources.

Hardware is a Xiaomi 4a gigabit edition

Update: Is there a way to recognize a certain IP range, and allocate a certain FAS address, and another FAS address to another IP range?

**Comment by bluewavenet** [comment]
@SergioDG-YCC 
Sorry, no, multiple instances are not supported.

However, openNDS  generally knows which interface the client is coming into the router on and this can be used to differentiate between two "wifi signals".

This works particularly well with an 802.11s mesh. Alternatively the FAS login can have a "staff" mode that uses a different login sequence for staff compared to guests/passengers. You can allocate session, data and rate quotas for each type of login (staff or passenger).

Chilli, NoDogSplash, WiFiDog and openNDS all have the same origins in the dim and distant past, so they have very little prospect of ever working together.

**_The simplest way of all that is guaranteed to work_** is to have a separate router for staff and passengers. A high quality, low cost router able to support tens to hundreds of users is available for as little as $50....  I have personally done it this way on numerous occasions.
