### ISSUE TITLE
vouchers wiped after reboot

### ISSUE THREAD

**Issue by Neoslyke** [openNDS/openNDS#483]
Is there anyway to make it not wiped out after openwrt router reboot? I'm using the voucher and vouchers.txt are wiped after reboot.

**Comment by bluewavenet** [comment]
See:
https://github.com/openNDS/openNDS/blob/master/community/themespec/theme_voucher/README.md

And:
https://opennds.readthedocs.io/en/stable/config.html#local-log-mountpoint
