### ISSUE TITLE
Is there a way to stop opennds service after a condition is met?

### ISSUE THREAD

**Issue by diogohvo** [openNDS/openNDS#488]
As the title says, I want to stop the opennds service as soon as two clients are authenticated, for example. Is this possible?

I am running openwrt 22.03, opennds 10.1.0
I tried to limit the number of clients in opennds settings, but that leaves the rest without internet access and that is not viable for me.

**Comment by bluewavenet** [comment]
@diogohvo 
This is a very odd request and it makes no sense as far as I can see -  would you like to elaborate?

There is certainly nothing built in to do this, but both an external FAS or a local ThemeSpec could be programmed to do it...

**Comment by diogohvo** [comment]
So a local ThemeSpec could terminate this service? How so? I am not familiar with ThemeSpec implementation, I would have to read up on it.
But the reasoning behind this request is that I am only insterested in the capturing part of opennds, not the authentication, and after the first few redirects, I no longer have a need for this service, thus I would like to shut it down

**Comment by diogohvo** [comment]
Could I achieve the desired outcome if I used, for example, crontask in openwrt?

**Comment by diogohvo** [comment]
Indeed, you can use CronTask to terminate this service! Problem solved!
