### ISSUE TITLE
I want to allow only by only mac address not ip address

### ISSUE THREAD

**Issue by nrjdalal** [openNDS/openNDS#496]
current -
```
Client 0
  Client Type: cpi_url
  IP: 192.168.1.161 MAC: 5c:e9:1e:c3:5a:11
```
want -
```
Client 0
  Client Type: cpi_url
  MAC: 5c:e9:1e:c3:5a:11
```

**Comment by bluewavenet** [comment]
@nrjdalal 
```
Client 0
  Client Type: cpi_url
  IP: 192.168.1.161 MAC: 5c:e9:1e:c3:5a:11
```
This is a snippet of the output of `ndsctl status`, it is showing the current ip and mac of the client.

openNDS identifies the client only by mac address, but collects a lot of other information.

**Comment by nrjdalal** [comment]
what happens after ip changes, the ndsctl updates the new ip and discard previous one?

**Comment by bluewavenet** [comment]
@nrjdalal 
Why would the ip address change while the client is active? 
Internet access is a layer 3 routing function and depends on the ip address, obviously. Access is granted in the nftables ruleset by ip address at the time of authentication.

> what happens after ip changes [..]?

If the client is still active, the ip address will not change. If the client is idle (for a configurable period), it will be de-authenticated.

If the ip address is allocated to another client then there is something wrong with your dhcp server.

**Comment by nrjdalal** [comment]
thank you @bluewavenet
