### ISSUE TITLE
FAS help

### ISSUE THREAD

**Issue by snothub** [openNDS/openNDS#499]
I'm trying to deploy a custom written FAS app (in reactjs), running on the router, keeping it as simple as possible

This is my config:
```
	option gatewayinterface 'br-guests'
	option gatewayname 'vinwifi'
	option enabled '1'
	option sessiontimeout '120'
	option fasport '4234'
	option faspath '/'
	option fas_secure_enabled '1'
	option faskey 'bb224b82-7e38-4fcf-877b-9b31dc2eb545'
	option login_option_enabled '0'
```
When connected to the interface, I'm able to see the app open on http://192.168.66.1:4234/ which does look right. From here, I can't for the life of me figure out what documentation wants me to do:

> Once FAS has verified the client credentials, authentication is achieved by accessing NDS at a special virtual URL.
> 
> This virtual URL is of the form:
> 
> http://[nds_ip]:[nds_port]/[authdir]/?tok=[token]&redir=[landing_page_url]&custom=
> 
> This is most commonly achieved using an html form of method GET. The parameter redir can be the client’s originally requested URL sent by NDS, or more usefully, the URL of a suitable landing page.
> 

So I'm thinking I should have an html form, method GET, but is the IP and port the same as FAS here, or different? What about `[authdir]`? I'm just getting 404 on all attempts at port 4234 or 2050 on this IP. Is there something I'm missing here?

/etc/board.json
```
{
        "model": {
                "id": "glinet,mt3000-snand",
                "name": "GL.iNet GL-MT3000"
        },
        "system": {
                "hostname": "GL-MT3000"
        },
        "network": {
                "lan": {
                        "device": "eth1",
                        "protocol": "static",
                        "macaddr": "94:83:c4:27:94:9b",
                        "ipaddr": "192.168.8.1"
                },
                "wan": {
                        "device": "eth0",
                        "protocol": "dhcp",
                        "macaddr": "94:83:c4:27:94:9a"
                }
        }
}
```

**Comment by bluewavenet** [comment]
@snothub 
What version of OpenWrt is this and what version of openNDS are you using?

**Comment by snothub** [comment]
Sorry, my bad.

Openwrt DISTRIB_RELEASE='21.02-SNAPSHOT'

:~# opkg info opennds
Package: opennds
Version: 9.8.0-2

**Comment by snothub** [comment]
So I've upgraded to Dynalink DL-WRX36 and installed OpenWrt 23.05.0-rc3 r23389-5deed175a5 / LuCI openwrt-23.05, which should put me in a better position. 

Although I haven't gotten around to test it yet, I think the same question will be valid.

**Comment by bluewavenet** [comment]
@snothub 

> custom written FAS app (in reactjs), running on the router,

If it runs on the router and serves html to the client then yes it will work.

If it serves javascript to the client to download and run then it will not work on CPD or CPI compliant captive portals.
Clients block the download and running of javascript for security reasons. This is built into mobile operating systems such as iOS and Android. There is nothing a captive portal can do about it, so if this is what you mean then you are wasting your time.

**Comment by snothub** [comment]
> If it serves javascript to the client to download and run then it will not work on CPD or CPI compliant captive portals.
> Clients block the download and running of javascript for security reasons. This is built into mobile operating systems such as iOS and Android. There is nothing a captive portal can do about it, so if this is what you mean then you are wasting your time.

@bluewavenet as things stand, I'm able to connect to the NDS interface, the phone prompts me to authenticate and the reactjs app is opened and javascript is very much executing. 

But the original question still remains - given that FAS is running on, say http://192.168.66.1:4234/, what are the `[nds_ip]`,`[nds_port]` and `[authdir]` values mentioned in the documentation?

:~# opkg info opennds
Package: opennds
Version: 10.1.3-1

Model	Dynalink DL-WRX36
Architecture	ARMv8 Processor rev 4
Target Platform	ipq807x/generic
Firmware Version	OpenWrt 23.05.0-rc4 r23482-7fe85ce1f2
Kernel Version	5.15.132

**Comment by bluewavenet** [comment]
@snothub 
If the javascript is being run on the remote fas then there should be no problem. If the javascript is intended for execution on the client, it will be blocked by most clients in the built in CPD/CPI browser.

> [nds_ip],[nds_port] and [authdir] values mentioned in the documentation?

If you are running at level 1, you can see what is required by looking at the code in fas-hid.php and converting the relevant part into javascript.
