### ISSUE TITLE
Using BinAuth with fas.hid

### ISSUE THREAD

**Issue by KiereA** [openNDS/openNDS#505]
I was a bit confused by the documentation, can binauth be used to set client specific quotas when using fas.hid and if so, how do I set it up?

**Comment by KiereA** [comment]
Figured it out. Forgot these commands:
```shell
uci set opennds.@opennds[0].binauth='/usr/lib/opennds/binauth_log.sh'
uci commit opennds
service opennds restart
```

**Comment by bluewavenet** [comment]
@KiereA 
In version 10.x.x onwards, binauth is configured by default and handled somewhat differently and cannot be disabled.
See:
https://opennds.readthedocs.io/en/stable/binauth.html#binauth-option
Any extensions should be added to `/usr/lib/opennds/custombinauth.sh`

**Comment by KiereA** [comment]
Thanks, I later realized the problem I was experiencing was that $custom was set to $8 instead of $7 for auth_client.
