### ISSUE TITLE
How do I open links?

### ISSUE THREAD

**Issue by KiereA** [openNDS/openNDS#508]
I'm trying to set up communication between my remote fas server and nds using client_params.sh and binauth, in which quotas used can be synchronized and updated after a number of minutes. My idea was to open the fas page from the status page when the time has passed which would then update and in turn load the binauth status page but I realized that opennds is written in ash shell not bash and can't use solutions like xdg-open to load links.
        So my question is, how do I open links using ash shell and what url can I use to open my fas server and pass all the current client values to it?

**Comment by bluewavenet** [comment]
@KiereA 

> but I realized that opennds is written in ash shell not bash

It is written in C and uses ash/bash compatible scripts for some things.

> I'm trying to set up communication between my remote fas server

You could use bash on your remote FAS server, using the cgi scripting support most web servers support.
Usually though, FAS is written in PHP or some other "web" programming language.

> communication between my remote fas server and nds using client_params.sh and binauth,

Why? 

"client_params.sh" runs on the openNDS router and is responsible for generating the rfc 8910 response page (also known as page_511)

"binauth" is a post authentication processor system. There is no such thing as "the binauth status page".

> My idea was to open the fas page from the status page 

If you are not logged in, that is what the status page does (ie, by default http://status.client ).

> quotas used can be synchronized and updated after a number of minutes

There is nothing to synchronise. If you are logged in http://status.client gives you the instantaneous quota information.
Sure, you can customise the format to suit your requirements if you wish by editing the script.

> How do I open links

Links for what purpose?

**Comment by KiereA** [comment]
I'm sorry, I wasn't clear. Actually, the issue is with the session length option. In the system I'm designing, a user can pay for a given amount of time, let's say an hour, to access the internet. 
      So the router has to communicate often with the remote fas how much time has been used. The reason is to allow the user, if he either pauses connection or loses connection for some reason, after logging in to the system again, can continue were he left off.
      Also, I'm not sure how nds normally tells the remote server that a user has finished his session. I'm setting up a custom fas code on the server that checks the users data on the fas site database and based on that authenticates the user but as it is now, the user can login again at any point in the session and his session length will restart.
      
      Also, because of limited router resources I'm using fas.hid.

**Comment by bluewavenet** [comment]
@KiereA 
It is not possible to tell how much of an allocated time has been used.
What is the difference between the client being connected and not doing anything and being disconnected?
There is only a difference if the client actually logs out. As rfc8910/8908 is not universally supported, a client has no means of logging out unless they remember http://status.client as there is no way of automatically getting there.

Yes if the client logs out and then back in again there might be something that could be done, but this is all very complicated.

Much simpler is to sell a volume of data to be used before an expiry date - like mobile phone companies do.

The ability for FAS to track client usage is built in to fas-aes-https as it uses inbound nat traversal to get information from openNDS.

You could build the same functionality from scratch but you will end up with an equivalent to fas-aes-https.


> because of limited router resources

What hardware do you have? And what operating system are you using?

If this is a commercial project, specify a better router.

If this is an academic exercise then you will have to be very clever to get anywhere.

**Comment by KiereA** [comment]
> What is the difference between:
> 
> 1. the client being connected and not doing anything
> 
> and
> 
> 2. the client being being disconnected?

If my idea worked, the difference would be, if the user was disconnected, the users device would not be able to communicate with the remote server anymore, thus his session would get paused.
 

> Much simpler is to sell a volume of data to be used before an expiry date - like mobile phone companies do.
Just curious, can this be done with fas.hid?
 



> What hardware do you have? And what operating system are you using?
I'm using a TP-Link mr3420 with OpenWRT installed and my operating system is Windows 10. 
I think I'll just get a better router instead of trying to create new functionality from scratch.

**Comment by bluewavenet** [comment]
@KiereA 

> Just curious, can this be done with fas.hid?

If it is a remote FAS, then no.

> my operating system is Windows 10

That's fine, but I meant what operating system are you using on your router?
Yes for a TP-link it will be OpenWrt, but the version would have been important, but yes, please do get a better router.
16MB Flash and 128Mb RAM is the minimum specification.

**Comment by KiereA** [comment]
Thanks for the advice, I will probably get a better router but I realized that there is actually no need for the remote fas to reauthenticate the client after receiving the information, was able to get the equivalent of what I needed done by embedding javascript into the code.
