### ISSUE TITLE
Must i change fasremoteip in router when i change the host ip ？

### ISSUE THREAD

**Issue by boluojiang521** [openNDS/openNDS#51]
i just see the introduction of FAS at https://nodogsplash.readthedocs.io/en/v4.5.1/fas.html,
I see that i must make the fasremoteip 、 fasremotefqdn ，If someday, i must change the ip but keep the domain, must i change the fasremoteip? thanks a lot my great guy ~  ths~~~~

**Comment by bluewavenet** [comment]
@boluojiang521 
Welcome to openNDS ;-)

You should refer to the openNDS documentation at:
https://opennds.readthedocs.io

> If someday, i must change the ip but keep the domain, must i change the fasremoteip?

**Yes**
fasremoteip is the ip address of the remote FAS server, it must match the ip address assigned in DNS to fasremotefqdn.

It should be possible, as a future development, to implement automatic setting of fasremoteip in the case of fasremotefqdn being supplied.
The solution will have to be be dynamic, meaning openNDS should periodically resolve fasremoteip from fasremotefqdn and update iptables accordingly - hopefully without additional dependencies and being operating system independent. Should not be too difficult :-D

**Comment by boluojiang521** [comment]
nodogsplash is a  great program! like it  so  mouch!  lots of program use  CDN you  know, CDN has many  ip behind the program  really ip,
 i  have a  second question,  i found that NDS cannot protal when i open https web, so  how cloud  i solve it,  thank you bluewavenet

**Comment by bluewavenet** [comment]
@boluojiang521 

> CDN has many ip

Yes, and for this reason a CDN accessed web server is not always suitable as a FAS server.
CDN could be supported by making use of an ipset.
https://opennds.readthedocs.io/en/stable/walledgarden.html#walled-garden

The purpose of fasremotefqdn and fasremoteip is primarily to allow the use of shared hosting servers.

> i have a second question

Please open a new issue for a new topic. This makes browsing old issues more useful for others.
