### ISSUE TITLE
Facing Error 403 - Forbidden - Access Denied to this Client! with OpenNDS v10.03 

### ISSUE THREAD

**Issue by taimoor-mirza** [openNDS/openNDS#510]
Hi, I am trying to run **OpenNDS v10.03 version on Virtualbox using OpenWRT v23 Linux OS**. Host OS is based on Ubuntu 20.04 LTS. The VM has 2 bridge networks linked with host's network interface and also has DHCP enabled. I am able to install the OpenNDS without any problem. The issue arises when I access the login page of OpenWRT.  Browser gets the error 403 like this:

![image](https://github.com/openNDS/openNDS/assets/114381468/4f6be0db-51f9-4119-b957-8ce280680ea4)
 Here are my OpenNDS settings:

```
root@OpenWrt:/tmp# uci show network
network.loopback=interface
network.loopback.device='lo'
network.loopback.proto='static'
network.loopback.ipaddr='127.0.0.1'
network.loopback.netmask='255.0.0.0'
network.globals=globals
network.globals.ula_prefix='fda2:e789:be97::/48'
network.@device[0]=device
network.@device[0].name='br-lan'
network.@device[0].type='bridge'
network.@device[0].ports='eth0'
network.lan=interface
network.lan.device='br-lan'
network.lan.proto='static'
network.lan.netmask='255.255.255.0'
network.lan.ip6assign='60'
network.lan.ipaddr='192.168.18.36'
network.wan=interface
network.wan.device='eth1'
network.wan.proto='dhcp'
network.wan6=interface
network.wan6.device='eth1'
network.wan6.proto='dhcpv6'
```

```
dhcp.@dnsmasq[0]=dnsmasq
dhcp.@dnsmasq[0].domainneeded='1'
dhcp.@dnsmasq[0].boguspriv='1'
dhcp.@dnsmasq[0].filterwin2k='0'
dhcp.@dnsmasq[0].localise_queries='1'
dhcp.@dnsmasq[0].rebind_protection='1'
dhcp.@dnsmasq[0].rebind_localhost='1'
dhcp.@dnsmasq[0].local='/lan/'
dhcp.@dnsmasq[0].domain='lan'
dhcp.@dnsmasq[0].expandhosts='1'
dhcp.@dnsmasq[0].nonegcache='0'
dhcp.@dnsmasq[0].authoritative='1'
dhcp.@dnsmasq[0].readethers='1'
dhcp.@dnsmasq[0].leasefile='/tmp/dhcp.leases'
dhcp.@dnsmasq[0].resolvfile='/tmp/resolv.conf.d/resolv.conf.auto'
dhcp.@dnsmasq[0].nonwildcard='1'
dhcp.@dnsmasq[0].localservice='1'
dhcp.@dnsmasq[0].ednspacket_max='1232'
dhcp.@dnsmasq[0].address='/status.client/192.168.18.36'
dhcp.lan=dhcp
dhcp.lan.interface='lan'
dhcp.lan.start='100'
dhcp.lan.limit='150'
dhcp.lan.leasetime='12h'
dhcp.lan.dhcpv4='server'
dhcp.lan.dhcpv6='server'
dhcp.lan.ra='server'
dhcp.lan.ra_slaac='1'
dhcp.lan.ra_flags='managed-config' 'other-config'
dhcp.lan.dhcp_option_force='114,http://status.client'
dhcp.wan=dhcp
dhcp.wan.interface='wan'
dhcp.wan.ignore='1'
dhcp.odhcpd=odhcpd
dhcp.odhcpd.maindhcp='0'
dhcp.odhcpd.leasefile='/tmp/hosts/odhcpd'
dhcp.odhcpd.leasetrigger='/usr/sbin/odhcpd-update'
dhcp.odhcpd.loglevel='4'
```

I've gone through similar issues reported on Github but I am not getting anywhere? What can be the issue.

**Comment by bluewavenet** [comment]
@taimoor-mirza 
"Access denied to this client" is usually a result of the client not being allocated an ip address by the opennds router's dhcp.
This is mandatory.

Does the client have a static ip address?
Or perhaps did you reboot the opennds router (vm in this case) while the client was connected?

**Comment by taimoor-mirza** [comment]
@bluewavenet I didn't reboot the router (OpenNDS VM). Client i.e host machine (Ubuntu) is connected with the corporate office's WiFi device. IP is always the `192.168.18.33` whenever I run `ifconfig`:

```
wlp5s0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 192.168.18.33  netmask 255.255.255.0  broadcast 192.168.18.255
        inet6 2407:aa80:116:7de6::3  prefixlen 128  scopeid 0x0<global>
        inet6 fe80::78f3:4ed7:7566:7e47  prefixlen 64  scopeid 0x20<link>
        inet6 2407:aa80:116:7de6:11c9:ae66:f857:98d7  prefixlen 64  scopeid 0x0<global>
        inet6 2407:aa80:116:7de6:1749:8698:ff24:a98a  prefixlen 64  scopeid 0x0<global>
        ether 0c:dd:24:ec:58:33  txqueuelen 1000  (Ethernet)
        RX packets 1798255  bytes 1944733518 (1.9 GB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 774108  bytes 383596701 (383.5 MB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
```

**Comment by bluewavenet** [comment]
@taimoor-mirza 

> Client i.e host machine 

The VM host cannot be a client on the openNDS network.
A valid client MUST be allocated an ip address by the dhcp server on the openNDS router (or its VM in this case).

Also, I see the openNDS ip address is set in the config as 192.168.18.36. This is VERY unusual as the ip address is usually auto-detected and MUST be the default gateway for the openNDS subnet. In this case it is not necessarily incorrect, but does imply something is quite likely wrong with your VM setup and it is most likely incompatible with openNDS
