### ISSUE TITLE
can't not get opennds to work on ubuntu 22.04 with hotspot

### ISSUE THREAD

**Issue by cjcdev** [openNDS/openNDS#511]
I can't get opennds configured properly to show me a simple CPD longin screen.  I was able to get nodogpslash to work.  I'm trying v10.1.3 of opennds.  Anyone tried getting this to work recently?

**Comment by bluewavenet** [comment]
@cjcdev 
It has not been officially tested on Ubuntu but has been on Debian and OpenSuse, so apart from potential minor setup differences, there should not be a problem.

Nothing special is required.

Please show the contents of your `/etc/config/opennds` file.

FYI For prerequisites, you can look at the relevant documentation page:
https://opennds.readthedocs.io/en/stable/install.html#prerequisites
