### ISSUE TITLE
add Javascript file to htdocs

### ISSUE THREAD

**Issue by moukir-link** [openNDS/openNDS#513]
hi everyone i hope you're all well.
i want to add a QR code reader to my voucher form so the client can scan the voucher and get the characters easily.but  i fail to compile the Javascript with the voucher_themspec.sh and the big problem is i put the Javascript file in htdocs folder but i don't know how to define it's source in voucher_themspec.sh.
my question is.is it possible to use Javascript in openNDS?
and which location i have to put this Javascript file?
and how can i define this location using src="......"
i appreciate your help ,thank you all
![Screenshot_20230910-211832](https://github.com/openNDS/openNDS/assets/116383312/c846049b-23ef-46f5-904b-ee3892516942)

**Comment by bluewavenet** [comment]
@moukir-link 

**_The brief answer is no, you cannot do this with javascript._**

It is not a limitation with openNDS, but a security measure built into the client device's operating system, specifically the Captive Portal Detection (CPD).

Automatically downloading executable code to a client device just by connecting to a wireless network could be a very severe security vulnerability, so the client's CPD blocks it.

See the documentation here:
https://opennds.readthedocs.io/en/stable/customize.html?highlight=javascript#rules-for-customised-splash-pages

**Comment by moukir-link** [comment]
unfortunately ,so no way to use QR reader with another language code?

**Comment by bluewavenet** [comment]
@moukir-link 
There is no way to embed **any** code that has to run on the client device.

Assuming most mobile devices already have a qr code reader, all is not lost. You can print  your paper voucher with a qr code that has a url that passes the voucher code to openNDS.

This is not supported in the community provided voucher themespec so you would have to write some extensions.....

**Comment by moukir-link** [comment]
i understand you,but the option you recommended me is not possible because i have to set every voucher with its url?
that's what you mean?

**Comment by bluewavenet** [comment]
@moukir-link 

>  not possible because i have to set every voucher with its url?

You were going to set every voucher with the voucher code anyway.
For this you just have to have a link qr code with the voucher code as the query string instead of a qr code with just the voucher code.....
Why is it impossible for you?

**Comment by moukir-link** [comment]
do you mean the URL of the success connected session?
the solution that i use now is scanning the voucher qr code with qr reader that redirecting me to https://status.client:2050

**Comment by bluewavenet** [comment]
@moukir-link 
I have not tried the following but it should work:
If a given voucher code is 1234-abcd, then encode the qr code as a link(url) type with the url:
`http://status.client/login?voucher=1234-abcd`

Now in the theme_voucher.sh script, look for the `voucher_form()` function.

At this point you should have the variable "originurl" containing the string `http://status.client/login?voucher=1234-abcd`
It should be a simple matter to strip out the voucher code from this string and put the value into the html form.

**Comment by moukir-link** [comment]
i will try it now and i will post the result,thanks a lot

**Comment by moukir-link** [comment]
unfortunately it's not working.

**Comment by bluewavenet** [comment]
@moukir-link 

Here is an example of the landing page of a test system, showing that $originurl **is** passed to the themespec.
It is up to you to write some code to make use of it.
![Screenshot from 2023-09-12 08-10-34](https://github.com/openNDS/openNDS/assets/13632068/2c021de7-b0bb-4edf-829f-d2ca0a3b2332)

**Comment by bluewavenet** [comment]
@moukir-link 
This thread is no longer about javascript.
If you want to discuss how to pass a voucher code to theme_voucher using a qr code, please open a new issue.
