### ISSUE TITLE
How to change the POST authmon url manually?

### ISSUE THREAD

**Issue by darknblack** [openNDS/openNDS#514]
Hi, I have the faspath with the following value:
opennds.@opennds[0].faspath='/'

The router is unable to process POST requests to the root path (/). These requests must be made to the /api path instead. How can I achieve this?

Maybe we could also add this as one of the config options. 

Thanks!

**Comment by bluewavenet** [comment]
@darknblack 
The problem here is that you need to set faspath correctly.
Your FAS only works at all because you have renamed fas-aes-https.php (or your own script) to index.php.

Give your script a proper name and put this into faspath config.

**Comment by darknblack** [comment]
Could you please elaborate on your answer? Just to clarify, I'm using a custom FAS written in Node.js (Next.js). I can access the FAS homepage correctly. However, making POST requests to `some-fas-service.com/` is not possible with my current setup due to the nature of Next.js (version 13.4+). Therefore, I had to redirect it to another page (/api).

To achieve this, I replaced /usr/lib/opennds/authmon.sh:88 where url=$1 with url="$1/api/", and it seems to have resolved the issue. However, I'm uncertain if this is the correct approach.

**Comment by bluewavenet** [comment]
@darknblack 

> Could you please elaborate on your answer?

I thought I was very clear. However what you have is a problem with your setup/next.js.

It seems you have found a workaround by modifying code on the router.

It would be better to have whatever you have at "/" be able to process POST requests.
You seem to have it processing GET requests, otherwise you would not see your login page.

**Comment by darknblack** [comment]
Yes, I can do `GET` requests on /, but with Next.js (version 13.4+), you cannot have both `GET` and `POST` requests handled on the same page at the root path (/). You have to choose one or the other.

Anyway, I'll close the ticket as the workaround seems to do the job. Thanks :)
