### ISSUE TITLE
pass a voucher code to theme_voucher using QR

### ISSUE THREAD

**Issue by moukir-link** [openNDS/openNDS#515]
![_20230912_084522](https://github.com/openNDS/openNDS/assets/116383312/c1767848-29e5-4d36-a6fb-a6ba6ef2de8d)
i think you miss a forward slash here.so i will try it again

**Comment by bluewavenet** [comment]
@moukir-link 
The forward slash is not needed as the "?" is the querystring delimiter.

**Comment by moukir-link** [comment]
#Example URL: https://secure.na1.adobesign.com/public/esignWidget?wid=CBF2s*
#The start of the parameters are identified by adding a hash (pound, #) symbol at the end of the web form URL.
#Then add the parameters in the format of  {field_name}={value}
#Example URL with one parameter
#https://secure.na1.adobesign.com/public/esignWidget?wid=CBF2s*#Branch_Office=San Jose #621

i find this exemple in a web site,does this will help me?

**Comment by bluewavenet** [comment]
@moukir-link 
Your example web site does not help you at all.

In the theme_voucher.sh ThemeSpec script you will find the function `voucher_form()`
The variable string $originurl is defined by openNDS and passed to the ThemeSpec.

All you have to do is extract the voucher code and insert it into the form.

Extracting is a simple bit of Ash coding:

`voucher_code=$(echo "$originurl" | awk -F "voucher=" '{printf "%s", $2}')`

Now it is a simple matter to insert this into the form.

Find the line:
`			Voucher #: <input type=\"text\" name=\"voucher\" value=\"\" required><br>`

and change it to:
`			Voucher #: <input type=\"text\" name=\"voucher\" value=\"$voucher_code\" required><br>`


So the function `voucher_form()` will look like this:

```

voucher_form() {
	# Define a click to Continue form
        voucher_code=$(echo "$originurl" | awk -F "voucher=" '{printf "%s", $2}')

	echo "
		<med-blue>
			Welcome!
		</med-blue><br>
		<hr>
		Your IP: $clientip <br>
		Your MAC: $clientmac <br>
		<hr>
		<form action=\"/opennds_preauth/\" method=\"get\">
			<input type=\"hidden\" name=\"fas\" value=\"$fas\"> 
			<input type=\"checkbox\" name=\"tos\" value=\"accepted\" required> I accept the Terms of Service<br>
			Voucher #: <input type=\"text\" name=\"voucher\" value=\"$voucher_code\" required><br>
			<input type=\"submit\" value=\"Connect\" >
		</form>
		<br>
	"

	read_terms
	footer
}


```

**Comment by moukir-link** [comment]
sorry for being late to reply,no nothing changed,i changed the theme_voucher as you said and when i put this url in my browser it redirect me to the splash page
![Uploading nothing changed.jpg…]()

**Comment by moukir-link** [comment]
![verified](https://github.com/openNDS/openNDS/assets/116383312/64ddebd7-c4c9-4f40-aa4c-c631b1631681)
but when i verified splash page i find that the value doesn't changed

**Comment by bluewavenet** [comment]
@moukir-link 
Ah! My mistake, I forgot, `$originurl` is url-encoded.

The line that is:
`voucher_code=$(echo "$originurl" | awk -F "voucher=" '{printf "%s", $2}')`

change it to:
`voucher_code=$(echo "$originurl" | awk -F "voucher%3d" '{printf "%s", $2}')` 

Now try again.....

**Comment by moukir-link** [comment]
ok many thanks Sir.i will try it as soon as i return to home

**Comment by moukir-link** [comment]
![failed](https://github.com/openNDS/openNDS/assets/116383312/52f42fd1-0554-48dd-8675-f42829a864b0)
it always printed the last voucher i have used to login even if i refresh the page

**Comment by bluewavenet** [comment]
@moukir-link 
I don't understand what you mean.
If you are logged in and refresh the page it will always show the same code.
You have to log out first at http://status.client

You should get this page and click logout:
![image](https://github.com/openNDS/openNDS/assets/13632068/28d82a63-b36b-4f14-8f88-11c4c659681a)

**Comment by moukir-link** [comment]
no i don't log in yet.i just type this url : http://status.client/login?voucher=my voucher and i get the splash with the last voucher filled in the form

**Comment by bluewavenet** [comment]
@moukir-link 
It seems to be working consistently here with the query string being passed to ThemeSpec (but I am not using the theme-voucher script, although that should not in principle make a difference).

**Are you sure you are scanning the correct QR code?**

There are edge cases where it might give a completely different result, particularly if the client CPD retries as a result of the user delaying clicking "Connect". But this is not what you are seeing.

I am adding code to the underlying openNDS system to prevent this and make passing parameters from status.client a generic API function. This will be in release 10.2.0.

I don't recall if you mentioned what your openNDS router type was.
You could perhaps test the beta of the new release.

**Comment by moukir-link** [comment]
I'm using openwrt routeur vodafone hg556a with opennds release 10.1.2
i should upgrade it to 10.2.0?

**Comment by bluewavenet** [comment]
@moukir-link 
10.2.0 is not released yet. I would have to build 10.2.0beta for that hardware. Maybe I'll have time later today.
I doubt if it is the problem though, more like some caching issue.

Have you tried connecting with a different device?

**Comment by moukir-link** [comment]
ok so the beta will be released soon،thank you so much for your efforts .
yes i tried connecting with my laptop and my phone as well
