### ISSUE TITLE
Quota are not persistent

### ISSUE THREAD

**Issue by peterdedecker83** [openNDS/openNDS#516]
The quota usage doesn't seem to be persistent over different sessions with the same voucher. We noticed this behaviour:
- voucher configured with 1 day validity and 100 MB data quota
- user logs in, uses voucher to start session and starts downloading/streaming
- after 100 MB, the user gets blocked and the session terminated due to quota exceed
- after disconnecting and reconnecting again, using the same voucher, the system correctly gives the remaining time for this voucher, but gives the user another 100 MB to use

As the quota usage has been exceeded, we should expect the user gets this message and his session with this voucher is no longer allowed.

Thanks.

**Comment by peterdedecker83** [comment]
Additionally: where can the remaining data quota be retrieved? Can we also include this in the message the user gets when logging in, showing the remaining quota next to the remaining time? Thanks.

**Comment by bluewavenet** [comment]
@peterdedecker83 

> The quota usage doesn't seem to be persistent over different sessions with the same voucher.

This is probably not implemented in the simple, community written Voucher ThemeSpec.

The ThemeSpec is designed to be customised to your requirements, so I suggest you look closely at it to see where you need to make changes.
If you get such an enhancement working, contributing to the Community via a PR will be very welcome.

@fservida - FYI

**Comment by peterdedecker83** [comment]
Tx for your reply.

I don't see the purpose of having individual data quota if you can simply circumvent this by logging in again...

I checked the code of the ThemeSpec, which is used to pass the quota and rate settings on to the system and checks whether the session end time is not exceeded when starting the session. Unfortunately, I don't see a possibility to check how many data already has been used when logging in again. I guess it must be somewhere in the main source code where the session is terminated (voluntary or after exceeding the quota) that some callback function should be implemented to save the used data volume. This saved information could be parsed by the ThemeSpec upon logging in again. I'ld be happy to contribute to the ThemeSpec if you could explain me how to have access to such kind of used data volume information.

**Comment by bluewavenet** [comment]
@peterdedecker83 

> I don't see the purpose of having individual data quota if you can simply circumvent this by logging in again...

I don't see the purpose of a voucher system other than to monetise what should be a free service provided by venues.
Some 20 years ago, Internet data was expensive and there was an argument for voucher systems. But that has long since changed forever. Now, venues provide free Internet access as a tool to attract customers.

In some very few countries that have a late developing Internet infrastructure, costs of Internet are being kept artificially high by many third parties persisting in directly attempting to monetise Internet access.

For this reason, voucher systems are not officially supported by the openNDS project.
Theme-voucher has been provided by members of the community simply as an open source example of what can be done.

**Comment by peterdedecker83** [comment]
In most venues, internet is indeed that cheap that you shouldn't impose quota. In offshore worlds however, internet access comes with a rather high price, even today with Starlink.

**Comment by bluewavenet** [comment]
@peterdedecker83 

> In offshore worlds however, internet access comes with a rather high price, even today with Starlink.

If it is Starlink, it will not be a "rather high price" unless someone is trying to monetise it.

In a working offshore environment you might want to limit access to off duty times, and that is easily supported, but a voucher system is not necessary to achieve that.
Typically, an up to date roster database is maintained and this can be used to provide the required user access information, including data rate limits to give priority to essential traffic on the Starlink feed.

**Comment by peterdedecker83** [comment]
If you say 15.000$/month is not a high price when quota are exceeded... A voucher system is the most equal solution in this environment for everyone.

The described possibilities of the voucher system were the maim reason to opt for OpenNDS for us :-)

**Comment by bluewavenet** [comment]
@peterdedecker83 
You definitely need to change to Starlink.
A business account costs 1050EUR per 6TB per month.
A maritime premium account costs 5640EUR per 5TB per month for unlimited ocean roaming.

Small change for a working oil platform...

> The described possibilities of the voucher system

They are just that, possibilities.
For your commercial development, I suggest you employ the paid services of a software engineer capable of reading the source code and writing a FAS to meet your requirements.

**Comment by peterdedecker83** [comment]
Well, 5TB would be fine, but if users are going over 15TB, you're talking different numbers which are no small change, especially if you're not on a productive oil platform.
