### ISSUE TITLE
Memoryleak in microhttpd.c ?

### ISSUE THREAD

**Issue by BobHollywood** [openNDS/openNDS#518]
It looks like a memoryleak in microhttpd.c, line 157, where local variable 'custom', which has just been safe_calloc'd, is immediately overwritten by the returnvalue from MHD_lookup_connection. And if it is not a bug, it is not free'd at the end of the function, so still a memory leak. And in case of adding the 'free', see at line 159 where custom is pointing to a static string, so better don't 'free' it.

So summarizing, think that the safe_calloc at line 155 can be best removed without having adversary affects.

**Comment by bluewavenet** [comment]
@BobHollywood 
Thank you for your obviously in depth study of the code, this is always appreciated.

This issue though has been brought up before but is not a memory leak.

As "custom" is `const char *`,  the pointer is always the same and the memory allocation cannot be freed.
`safe_calloc()` reinitialises the same memory block each time and MHD does not overwrite the pointer.
This can be confirmed by monitoring the pointer before and after the calls to `MHD_lookup_connection`

The same applies elsewhere whenever `MHD_lookup_connection` is called.

For reference, see:
https://git.gnunet.org/libmicrohttpd.git/tree/src/include/microhttpd.h

So, as I said, thank you for your efforts and if you see anything else, do not hesitate to raise it as an issue.

**Comment by BobHollywood** [comment]
It's some time ago, but due to being busy elsewhere had little time to reflect on your answer: "As "custom" is const char *, the pointer is always the same and the memory allocation cannot be freed."

In C as I know it, a "const char *" is a pointer to a constant piece of memory; the variable "custom" can be changed at will (otherwise code it as a char *const). And indeed it happens in the code. It does not make sense to calloc a piece of memory when you can't change that memory. But that is not needed, as a little bit later "custom" is overwritten, and that's the memory leak I pointed at. 

Also, your comment that the pointer cannot be overwritten; how can the execution inside safe_calloc know that it should always return the same memory area? There is no history mechanism there.

I could easily verify this with VStudio, confirming my assumption.

Perhaps the leak does not occur in your situation, likely a compiler optimization 'sees' that the pointer is immediately overwritten, and then doesn't call safe_calloc at all. In that case, you're lucky. But the correct execution of code should not depend on a compiler optimization on a certain platform, it should _always_ work correctly. It is little effort to code it right?

**Comment by bluewavenet** [comment]
@BobHollywood 
Thanks for your continued interest.
This is indeed a potential issue as it seems the same block of memory is used every time and MHD did not reinitialise it resulting in corruption of returned values if the latest string was shorter than the previous.
The safe_calloc was a successful workaround, but as you point out, there is no guarantee it will work in all compiler environments.
However this seems to have been fixed in MHD at some time prior to v0.9.75, so the workaround is no longer required and has been removed in the upcoming v10.2.0 release of openNDS.

Again, thank you for your continued interest!
