### ISSUE TITLE
Lock voucher to one Mac address

### ISSUE THREAD

**Issue by DavidNingthou** [openNDS/openNDS#522]
I'm using the voucher system with expire time system but one thing I noticed is if I share the voucher than many clients can login using the same voucher. How do I make it so that the voucher can be used only by one device?  Like locking the voucher with the first device that logged in with?

**Comment by bluewavenet** [comment]
@DavidNingthou 
The voucher ThemeSpec has been developed as an example by a member of the community and is not officially supported, neither is it intended for it to be used in production.

I suggest you look in detail at the script, particularly the voucher validation logic and modify the code to suit your requirements.

**Comment by DavidNingthou** [comment]
Sorry I'm new, but why does it not have any css? Is it correct?  

![Screenshot_2023-09-21-19-11-57-022_com google android captiveportallogin](https://github.com/openNDS/openNDS/assets/126403967/f0e0a23e-a951-4174-97ac-4bd36dffa8e9)

**Comment by bluewavenet** [comment]
@DavidNingthou 
This is really a new issue....
Missing css was a known bug with an older version.
The latest version is here:
https://github.com/openNDS/openNDS/tree/master/community/themespec/theme_voucher

**Comment by DavidNingthou** [comment]
In which version it got fixed? Because I installed only few days ago

**Comment by DavidNingthou** [comment]
hello, i downloaded it but still css missing. please help me!

**Comment by bluewavenet** [comment]
@DavidNingthou 
A reminder:

> The voucher ThemeSpec [....] is not officially supported

So, you say:

> i need it fixed so that i can customize it.

You are in no position to demand that anything is fixed. It is written in Linux Ash shell script. If you are unable to read the script and find what is wrong, you will not be able to customise it either.

You could ask Sindam Technologies LLC, who are apparently illegally claiming the Copyright....

If you have an issue with css in this ThemeSpec script, (and Sindam won't help you), I suggest you open an issue specifically for the problem.
