### ISSUE TITLE
can i get the openwrt router mac through openNDS code?

### ISSUE THREAD

**Issue by boluojiang521** [openNDS/openNDS#53]
hey great  NDS
  i just see a method to get clientmac by splash.html,  but  i  want to  get openwrt router mac , so can i?
 thank you  again with my best wish to NDS~~

**Comment by bluewavenet** [comment]
@boluojiang521 
I will ask the question of why do you need the gateway mac? openNDS does know what it is, but does not use it anywhere.
If you are thinking of using the mac address to identify the openNDS gateway, then the parameter gatewayname is provided for this purpose.

Let me know the reasoning and I can see what we can do :-D

**Comment by boluojiang521** [comment]
due to some  reason cannot use FAS，i  want to get router mac or sth unique in spalsh.html, then i  can sent the mac or sth unique to the host, so  that i can know which router is it,and make different response to different router to splash.html，thanks~

**Comment by bluewavenet** [comment]
@boluojiang521 

> cannot use FAS

Why?

> then i can sent the mac or sth unique to the host

Which host?

> so that i can know which router it is

Gatewayname tells you which router it is.

> so that i can know which router is it,and make different response to different router

That is what an external FAS is designed to do.

**Please explain what it is you are trying to do**. I think you are overthinking and making it very difficult for yourself.
For example, some modes of FAS require very little if any extra memory over the simple splash page.

FAS can be:
 *  local and using the built in openNDS web server
 *  local and using a separate web server like lighttpd, nginx, apache etc
 *  remote on an http web server
 *  remote on an https web server

Each type of fas has different requirements but all can run on a basic openwrt router with enough resources.

**Comment by boluojiang521** [comment]
because

> @boluojiang521
> 
> > cannot use FAS
> 
> Why?
>   due to the time is to be limited for the first version;
> > then i can sent the mac or sth unique to the host
> 
> Which host?
> our alibaba clould server  by php
> > so that i can know which router it is
> 
> Gatewayname tells you which router it is.
>  Gatewanname is like OpenwrtWiFi_2.4G ? its unique one different from other router?,   i  just see the $gatewaymac, but,i receive 404 page through splash.html

**Comment by bluewavenet** [comment]
@boluojiang521 
I think we need to go back to basics.

Before we start going round in circles, please let me know the following:

 * Your OpenWrt Version
 * The version of openNDS you are using (if you are using NoDogSplash you must remove it and install openNDS)
 * The output of the command `uci show opennds`
 * The make and model of router you are using

> our alibaba cloud server by php

To access an external server, FAS is required.

> cannot use FAS due to the time is to be limited for the first version

The basic splash.html page is a static html only page. php, or any other scripting language is NOT supported.
If you want to access a remote server using php, use of FAS is required.
Using FAS will be MUCH faster to develop than having to rewrite C code to replicate the FAS functionality that is already in place.
openNDS comes complete with numerous fully functional example scripts for use with FAS. These are fairly trivial to modify for your own requirements, particularly if you want a system up and running very quickly. For example, setting up a Username/Emailaddress login page running on a remote https server will take just a few minutes. 
Take a look at fas-aes-https.php. After installing openNDS you will find it stored in /etc/opennds, ready to be copied to your remote FAS.
https://opennds.readthedocs.io/en/stable/fas.html#example-script-file-fas-aes-https-php

> Which host?
> our alibaba clould server by php

You possibly will have to set up a Walled Garden for this. Just a few commands required to do this.
https://opennds.readthedocs.io/en/stable/walledgarden.html#openwrt-walled-garden

> Gatewayname is like OpenwrtWiFi_2.4G ?

This is set in the openNDS config file. It can be any text string. Usually people will set this to reflect the location. eg "Coffee Shop Boluojiang" 

>  i just see the $gatewaymac, but,i receive 404 page through splash.html

If you access splash.html directly, this will indeed be the result. openNDS must be triggered by the client CPD or an attempt to access a remote http(port 80) web page

**Comment by boluojiang521** [comment]
OP  version:  OpenWrt R20.8.27

**Comment by bluewavenet** [comment]
@boluojiang521 

> OpenWrt R20.8.27

You should not be using OpenWrt 20.08.x. It is just a work in progress and not even an official snapshot.

> so you mean its so easy to set up FAS server?

Yes

> just copy file from openNDS to our php server,and install the php environment into opennds?

Yes

> can Walled Garden + domain support CDN domain?

Yes

You can find details in the documentation:
https://opennds.readthedocs.io

**Comment by bluewavenet** [comment]
@boluojiang521 
You can see a long discussion about Walled Garden at #48

**Comment by bluewavenet** [comment]
@boluojiang521 

> can i get the openwrt router mac through openNDS code?

This is built in to version 7.0.1 onwards. It is added to the query string for level 1 and passed as a comma spaced parameter in the encrypted query string in levels 2 and 3.
