### ISSUE TITLE
Data volume undertracked on Rut906

### ISSUE THREAD

**Issue by Bucket-Bucket-Bucket** [openNDS/openNDS#530]
Hello.
I'm working on creating a wifi hotspot solution using OpenNDS and the Teltonika RUT955, which has been working well so far.
I recently had to port the solution to the RUT906 as well where I noticed that the reported upload/download data amount is much lower than it should be, only in the range of kilobytes even after using dozens of megabytes, meaning users are never deauthenticated for going over their data budget.

Both the 955 and 906 run a slightly modified OpenWrt v21.02, by way of Teltonika. 
I have been using OpenNDS v9.3.0, which I know is an older version, but it is what's available in Teltonika's preconfigured package feeds. 
I have tried upgrading to OpenNDS v9.8.0, which is the latest available in OpenWrt's v21.02 package feeds, but the problem persists.

Please let me know what more information I can provide.

**Comment by bluewavenet** [comment]
@Bucket-Bucket-Bucket 

> I have been using OpenNDS v9.3.0

This is VERY old and has not been supported for a considerable time.
The current version is v10.1.3 (with v10.2.0 in beta testing).

>  OpenWrt v21.02

This is also very old and unsupported even by OpenWrt.

I suggest you upgrade to official OpenWrt, at least version 22.03.5 where openNDS v10.1.3 is available.
https://downloads.openwrt.org/releases/22.03.5/targets/ath79/generic/

**Comment by bluewavenet** [comment]
@Bucket-Bucket-Bucket 
Closing. Please post here if you have any further questions on this topic, or open a new issue.
