### ISSUE TITLE
How to enable FAS using fasremotefqdn without fasremoteip

### ISSUE THREAD

**Issue by darknblack** [openNDS/openNDS#532]
Hello, 

Is there a way to enable FAS using fasremotefqdn without fasremoteip? My use case is if I want to change my IP/VPS server to another company. Changing server from different company means I won't be able to retain the IP address but I can retain the domain name.

**Comment by bluewavenet** [comment]
@darknblack 
Yes, I think the following should work (at least it does in the soon to be released v10.2.0 - I just tested it).

1. Remove the `fasremoteip` entry altogether.
2. Add the following, substituting your values for _port_ and _fqdn_:
        `	list preauthenticated_users 'allow tcp port 443 to blue-wave.net'`

**Comment by darknblack** [comment]
Woahh that's nice! looking forward to it. Thank you 🥳🎉👏

**Comment by bluewavenet** [comment]
@darknblack 

> Add the following, substituting your values for port and fqdn

You won't need to do this on v10.2.0 as it is now fully automated as long as the fqdn resolves to a single ip address ie a standard web site.

However, if the web site is on a CDN ie resolves to a number of ip addresses, you will still have to set up a walled garden in the opennds config.
