### ISSUE TITLE
Captive portal is not coming after installing the opennds

### ISSUE THREAD

**Issue by rd7597** [openNDS/openNDS#537]
i am using raspberry pi 4b with 8GB RAM 64bit and i flashed the latest version of OpenWrt23.05 on it and using desktop support to see the output and logs. in /etc/config/network i have changed ip address as 192.168.68.4 for the raspberrypi and 192.168.68.1 for the gateway. defined the DNS provided by the ISP. after that i connected to OpenWrt2 wifi and logged in to LUCI using 192.168.68.4 on browser and then set password for root. In network>> interfaces>> i have lan interface named br-lan only. then in network >>wireless >> i enabled the wireless interface and Voila i am now receiving internet on the OpenWrt Wifi. 

Now in System>> Software >> i have updated the package list and then installed the OpenNDS package and after that when the refreshed the page  openwrt terminal is not getting the access as well as LUCI it is saying >>>>>>>>>>>>"Error 403 No access to this client">>>>>>>>>>>> any soultion for this?

i want to implement a captive portal for my wifi "OpenWrt2" using user login or sms otp authentication, after the authentication only the internet access should be given to the user. 

i am new to this concept of captive portal and networking so can someone help me for the configuration file setup in /etc/config/opennds and other changes that are required for captive portal implementation. we can start with the basic click and continue kind of captive portal. 

![Screenshot from 2023-10-26 12-34-14](https://github.com/openNDS/openNDS/assets/115134186/85922c74-3762-4735-92c7-38e70478a1a2)
![Screenshot from 2023-10-26 12-34-23](https://github.com/openNDS/openNDS/assets/115134186/0bd6c760-dc0c-4f2a-bc13-b025f09b0d90)
![Screenshot from 2023-10-26 12-34-32](https://github.com/openNDS/openNDS/assets/115134186/d1990291-accc-4f4c-b8ba-b3e9cf883cad)
![Screenshot from 2023-10-26 12-34-36](https://github.com/openNDS/openNDS/assets/115134186/ebe09544-c37e-4ca9-82a3-69a1c9e5f8ae)
![Screenshot from 2023-10-26 12-34-59](https://github.com/openNDS/openNDS/assets/115134186/5ceb3f0c-9d1b-416b-a5d8-c848633b81bd)

**Comment by bluewavenet** [comment]
@rd7597 

You do not have a wan interface. The rpi MUST be configured as a router for a CP.

See the documentation here:
https://opennds.readthedocs.io/en/stable/howitworks.html#how-opennds-nds-works

and specifically:
https://opennds.readthedocs.io/en/stable/install.html#prerequisites

**Comment by rd7597** [comment]
@bluewavenet sir, can you please help me in setting up the RPI as a router and the wan interface. what should i do to setup that? like which protocol for WAN network and interface should i choose??

**Comment by bluewavenet** [comment]
@rd7597 
As far as I am aware, the default firmware image will be set up as a router (this is OpenWrt after all), but I could be wrong.
I would normally expect the default to be eth0 as the wan connection and the wireless interface disabled but configured as the local area network.

_As an aside, be aware that the built in wireless interface on a pi is designed for use as a station, not an access point and works very badly in access point mode. Usually the performance will be very poor and only 2 or 3 users will be able to connect._  

> please help me in setting up the RPI as a router

This is more of an OpenWrt question. As I do not have a pi to try things out on, I cannot really help.

I would suggest you ask for help on "Configuring a Raspberry Pi as a Basic Router" on the OpenWrt support forum:
https://forum.openwrt.org/

You could mention you want to ultimately run openNDS on it, but this is irrelevant as far as the basic router configuration is concerned.

Once you have it working as a router, come back here if necessary for openNDS help.

**Comment by rd7597** [comment]
i have setup a wan interface with DHCP client protocol and and wan6 interface with DHCPv6 client protocol. i have attached the screenshots of the current setup and Ip address for connected interfaces. kindly look into that and one more thing i want to mention that i am able to use pi as a basic router as it is hosting the OpenWrt2 wifi and i am getting the internet but after installing opennds, internet access denied to Luci and openwrt root terminal. i am not aware of the interface wan and wan6 how they are used in the setup. if you can help me in that that would be the greatest help.

**Comment by bluewavenet** [comment]
@rd7597 
Did you mean to close this issue?

> i am not aware of the interface wan and wan6 how they are used in the setup. if you can help me in that that would be the greatest help.

As I said previously:

> This is more of an OpenWrt question. As I do not have a pi to try things out on, I cannot really help.
> 
> I would suggest you ask for help on "Configuring a Raspberry Pi as a Basic Router" on the OpenWrt support forum:
> https://forum.openwrt.org/

openNDS is telling you:
`All upstream gateway(s) are offline or not connected`

Does this not mean anything to you?
Have you connected the upstream gateway (aka the isp router)?

**Comment by rd7597** [comment]
i have shared my issues on Openwrt forum also with my issue. i understand the issue but i am asking for the solution that after creating WAN interface what else i need to setup so that i can get the access  and get connected to upstream gateway. i am getting internet on the Pi based OpenWrt2 Wifi rpi is working as a router only. still this is showing not connected to Upstream gateways.

**Comment by bluewavenet** [comment]
@rd7597 
**_You do not seem to be reading my replies._**

Previously I said:

> openNDS is telling you:
> All upstream gateway(s) are offline or not connected
> 
> Does this not mean anything to you?
> Have you connected the upstream gateway (aka the isp router)?

Your screenshot shows the lan ip address of the rpi is 192.168.68.5
This is the subnet 192.168.68.x
Previously you stated the subnet of your isp router was 192.168.68.x
Have you changed the ips router subnet?

Your wan interface has not received an ip address from the isp router - **_Have you connected the pi ethernet to a port on your isp router?_**

> LUCI it is saying >>>>>>>>>>>>"Error 403 No access to this client">>>>>>>>>>>>

By default, Luci is available via https on port 443
It is also available by default via http on port 80, BUT port 80 is reserved for openNDS for rfc8910 captive portal information. So when openNDS is running Luci is only available as https.
