### ISSUE TITLE
How to editing Post-authentication rules or firewall

### ISSUE THREAD

**Issue by dev-rld** [openNDS/openNDS#539]
How can i block the following URLs: 

- android.clients.google.com
- connectivitycheck.android.com
- connectivitycheck.gstatic.com

On the post-authentication rules or firewall using openNDS?

**Comment by bluewavenet** [comment]
@dev-rld 
Why would you want to block these? At best it would do nothing, at worst it would make some android devices think they needed to authenticate again...

**Comment by dev-rld** [comment]
@bluewavenet This domain names will prevent closing of Captive Portal on Android after Authentication

**Comment by bluewavenet** [comment]
@dev-rld 
The portal splash pages are displayed on the built in CPD "mini-browser", very specifically for security reasons (**mainly to prevent mitm attacks**). One such security feature is to close the mini browser as soon as Internet connectivity is detected.

Blocking those particular domain names may prevent **_some_** android devices from closing the splash pages, but _there are many many other canary test urls in use depending on the vendor of the android device._

An innocent reason for wanting the splash page to stay open is for advertising or information.
This is handled by openNDS by providing the Thankyou page, after client verification , but before authentication.

Your advertising and/or information should be placed there.

**Comment by dev-rld** [comment]
There is all the following domain names i need to add:
- http://clients4.google.com/
- http://clients3.google.com/
- http://clients2.google.com/
- http://clients1.google.com/
- http://android.clients.google.com/
- http://connectivitycheck.android.com/
- http://connectivitycheck.gstatic.com/

Additionally, I require a specific feature. After the user views the advertising/information spot, we need to redirect them to a specific website. However, with the current Android's CPD behavior, the portal closes automatically, and the redirection doesn't always appear.

**Comment by bluewavenet** [comment]
@dev-rld 

> There is all the following domain names i need to add:

There are MANY more than that. Recent Android releases are aware of attempted blocking and cycle round a list of canary test urls that is quite extensive.

> we need to redirect them to a specific website.

Links are also specifically blocked by many CPD implementations, again for security reasons.

Redirecting users to a web site they do not want to go to, possibly even without them noticing, is indistinguishable from a mitm attack.
