### ISSUE TITLE
Openwrt + Openclash + Opennds

### ISSUE THREAD

**Issue by lexavey** [openNDS/openNDS#540]
this is my current configuration :
`uci show opennds` :
```
opennds.@opennds[0]=opennds
opennds.@opennds[0].debuglevel='3'
opennds.@opennds[0].fwhook_enabled='1'
opennds.@opennds[0].log_mountpoint='/tmp/log'
opennds.@opennds[0].login_option_enabled='1'
opennds.@opennds[0].allow_preemptive_authentication='1'
opennds.@opennds[0].users_to_router='allow udp port 53' 'allow udp port 67' 'allow tcp port 22' 'allow tcp port 443'
```

with this configuration, users when after logged in cannot access internet.

when I try to modify like this in `/etc/config/opennds` : 
```
    list users_to_router 'allow tcp port 9090'
    list users_to_router 'allow tcp port 7893'
    list users_to_router 'allow tcp port 7895'
    list users_to_router 'allow tcp port 7892'
    list users_to_router 'allow tcp port 7891'
    list users_to_router 'allow tcp port 7890'
    list users_to_router 'allow tcp port 7874'
```

user can access internet without login because im allowing to access the proxy port, here Openclash logs : 
```
2023-10-28 18:33:52 level=info msg="[TUN] Tun adapter listening at: utun([198.18.0.1/30],[]), mtu: 9000, auto route: false, ip stack: gVisor"
2023-10-28 18:33:52 level=info msg="Mixed(http+socks) proxy listening at: [::]:7893"
2023-10-28 18:33:52 level=info msg="TProxy server listening at: [::]:7895"
2023-10-28 18:33:52 level=info msg="Redirect proxy listening at: [::]:7892"
2023-10-28 18:33:52 level=info msg="SOCKS proxy listening at: [::]:7891"
2023-10-28 18:33:52 level=info msg="HTTP proxy listening at: [::]:7890"
2023-10-28 18:33:52 level=info msg="DNS server listening at: [::]:7874"
2023-10-28 18:33:52 level=info msg="Use tcp concurrent"
2023-10-28 18:33:52 level=info msg="Sniffer is loaded and working"
2023-10-28 18:33:52 level=info msg="RESTful API listening at: [::]:9090"
2023-10-28 18:33:52 level=info msg="Initial configuration complete, total time: 16ms"
```
so I try to block access while unauthenticated with :

```
    list preauthenticated_users 'block tcp port 9090 to 192.168.1.1'
    list preauthenticated_users 'block tcp port 7893 to 192.168.1.1'
    list preauthenticated_users 'block tcp port 7895 to 192.168.1.1'
    list preauthenticated_users 'block tcp port 7892 to 192.168.1.1'
    list preauthenticated_users 'block tcp port 7891 to 192.168.1.1'
    list preauthenticated_users 'block tcp port 7890 to 192.168.1.1'
    list preauthenticated_users 'block tcp port 7874 to 192.168.1.1'
```

but the problem is user still can connect to internet without login.

**Comment by bluewavenet** [comment]
@lexavey 
What is Openclash? It is not an official OpenWrt package, so we can't really help as we do not even know what it is supposed to do....

**Comment by bluewavenet** [comment]
@lexavey 
Sorry, I don't speak Chinese, so it still means nothing to me. It looks though that OpenClash depends upon iptables, so therefore I would expect, with the lack of any other information, for it to be incompatible with openNDS in numerous ways. You could try blocking that port in fw4 maybe...

**Comment by bluewavenet** [comment]
@lexavey 

> How to do it ?

`    list preauthenticated_users 'block tcp port 7893 to 192.168.1.1'`

but you tried that already, so this supports my expectations that openNDS and Openclash are incompatible.

If Openclash was not dependent on iptables and was an officially recognised OpenWrt package, it would be worth investing time into seeing what is wrong, but unfortunately this is not the case.
