### ISSUE TITLE
Need help

### ISSUE THREAD

**Issue by tuna2134** [openNDS/openNDS#541]
In FAS, I need permission to google to authenticate with Google oauth2.

**Comment by bluewavenet** [comment]
@tuna2134 
Sorry, I don't understand what you mean.

It is possible for a remote, Internet hosted FAS, to validate using Google, but this would require the remote FAS to be running something like node.js and accessing the Google API.

This is a Google API/ Node.js issue and is not supported here in any of the example FAS scripts.

If you could give a fairly detailed outline of what you want to achieve, someone in the community may have done something similar and be willing to help.....

**Comment by tuna2134** [comment]
> @tuna2134 Sorry, I don't understand what you mean.
> 
> It is possible for a remote, Internet hosted FAS, to validate using Google, but this would require the remote FAS to be running something like node.js and accessing the Google API.
> 
> This is a Google API/ Node.js issue and is not supported here in any of the example FAS scripts.
> 
> If you could give a fairly detailed outline of what you want to achieve, someone in the community may have done something similar and be willing to help.....

I want to use google oauth2 at FAS, well i think NDS will block google

**Comment by bluewavenet** [comment]
@tuna2134 
It will be the FAS that talks to Google, not openNDS. The FAS will be hosted on the Internet somewhere.

The flow would go like this:
1. The client connects and the CPD/CPI login page comes up. This page is generated by the Internet hosted FAS server.
2. The FAS server gets the client user's login details from the form the user filled in.
3. The FAS contacts Google
4. Google replies to the FAS
5. The FAS and Google exchange whatever is required by the Google API
6. If necessary, FAS asks the client user for more information via another form page or pages.
7. Google verifies the client user credentials
8. FAS serves the "Thankyou" page to the client user (containing any information or advertising you might want).
9. The user clicks continue and FAS tells openNDS to authenticate the user's device.

**Comment by tuna2134** [comment]
> @tuna2134 It will be the FAS that talks to Google, not openNDS or the client user. The FAS will be hosted on the Internet somewhere.
> 
> The flow would go like this:
> 
> 1. The client connects and the CPD/CPI login page comes up. This page is generated by the Internet hosted FAS server.
> 2. The FAS server gets the client user's login details from the form the user filled in.
> 3. The FAS contacts Google
> 4. Google replies to the FAS
> 5. The FAS and Google exchange whatever is required by the Google API
> 6. If necessary, FAS asks the client user for more information via another form page or pages.
> 7. Google verifies the client user credentials
> 8. FAS serves the "Thankyou" page to the client user (containing any information or advertising you might want).
> 9. The user clicks continue and FAS tells openNDS to authenticate the user's device.

Is the fasremoteip a link to the API server made to do google oauth2?

**Comment by bluewavenet** [comment]
@tuna2134 
fasremoteip, along with fasremotefqnd are pointers to your Internet hosted FAS server.
It is possible to program an Internet hosted FAS server to use the Google API, but it is not supported by any of the openNDS examples.  This would be your responsibility.

**Comment by tuna2134** [comment]
> @tuna2134 fasremoteip, along with fasremotefqnd are pointers to your Internet hosted FAS server. It is possible to program an Internet hosted FAS server to use the Google API, but it is not supported by any of the openNDS examples. This would be your responsibility.

Okay, I’ll try it
