### ISSUE TITLE
Captive portal not loading with FAS setup

### ISSUE THREAD

**Issue by karam** [openNDS/openNDS#542]
Hello, 
First off, let me say how much I appreciate this project, its really well documented and is fun to use.
I have however, run into some trouble while setting up the captive portal with FAS on an x86 machine running ubuntu 22.04.

@bluewavenet — any help would be deeply appreciated! I run an ISP for a few thousand customers and would love to use opennds for all our customer logins. 

Issues:
1. The captive portal does not load
2. The walled garden does not seem to work either. When I connect to the wifi, I successfully get an ip address and I am able to ping the router (an x86 machine) - however I cannot ping the remote FAS IP.

Below is my configuration:

```
config opennds
	
	option allow_preemptive_authentication '1'
	option gatewayinterface 'enp174s0'
	option fasport '2080'
	option faspath '/'
	option fasremoteip '128.199.13.149'
	option fasremotefqdn 'wdlgn.com'
	option fas_secure_enabled '0'
	
	list walledgarden_fqdn_list 'wdlgn.com'
	list walledgarden_port_list '2080'
	
	option gatewayfqdn 'disable'
	option maxclients '250'
	option preauthidletimeout '30'
	option authidletimeout '120'
	option checkinterval '15'
	
	list users_to_router 'allow udp port 53'
	list users_to_router 'allow tcp port 53'
	list users_to_router 'allow udp port 67'
	list users_to_router 'allow tcp port 22'
	list users_to_router 'allow tcp port 80'
	list users_to_router 'allow tcp port 443'
	
```
	
Below is the output of ndsctl status:
```

==================
openNDS Status
====
Version: 10.1.3
Uptime: 10m 17s
Gateway Name: [ openNDS Node:d85ed3e38fcb  ]
Debug Level: [ 1 ]
Gateway FQDN: [ disable ]
Managed interface: enp174s0
Upstream gateway(s) [ online:192.168.0.1,eno1  ]
MHD Server [ version 0.9.75 ] listening on: http://192.168.174.1:2050
Maximum Html Page size is [ 10240 ] Bytes
Preemptive Authentication is Enabled
Binauth Script: /usr/lib/opennds/binauth_log.sh
Preauth: Disabled
FAS: Secure Level 0, URL: http://wdlgn.com:2080/
Client Check Interval: 15s
Rate Check Window: 2 check intervals (30s)
Preauthenticated Client Idle Timeout: 30m
Authenticated Client Idle Timeout: 120m
Download rate limit threshold (default per client): no limit
Upload rate limit threshold (default per client): no limit
Download quota (default per client): no limit
Upload quota (default per client): no limit
Total download: 37 kByte; average: 0.49 kbit/s
Total upload: 201 kByte; average: 2.68 kbit/s
====
Client authentications since start: 0
Current clients: 1

Client 0
  Client Type: cpd_can
  IP: 192.168.174.174 MAC: xx:xxx:xxx:xx:
  Last Activity: Thu Nov 02 20:08:24 2023 (10m 7s ago)
  Session Start: -
  Session End:   -
  Token: b35c2d09
  State: Preauthenticated
  Download Rate Limit Threshold: not set
  Upload Rate Limit Threshold: not set
  Download quota: not set
  Upload quota: not set
  Download this session: 0 kB; Session average: 0.00 kb/s
  Upload this session: 0 kB; Session average: 0.00 kb/s

====
Trusted MAC addresses: none
Walled Garden FQDNs:
  wdlgn.com
Walled Garden Ports:
  2080
========


```

**Comment by karam** [comment]
Output of service opennds status
```

● opennds.service - openNDS Captive Portal
     Loaded: loaded (/etc/systemd/system/opennds.service; enabled; vendor preset: enabled)
     Active: active (running) since Fri 2023-11-03 15:02:13 IST; 7min ago
   Main PID: 19394 (opennds)
      Tasks: 4 (limit: 9099)
     Memory: 1.2M
        CPU: 4.628s
     CGroup: /system.slice/opennds.service
             └─19394 /usr/bin/opennds -b

Nov 03 15:02:20 myhome opennds[19394]: Externals flagged with debuglevel 1.
Nov 03 15:02:20 myhome opennds[19394]: [5][Fri Nov 03 15:02:20 2023][19394](src/main.c:898) openNDS is now running.
Nov 03 15:02:20 myhome opennds[19394]: openNDS is now running.
Nov 03 15:02:20 myhome opennds[19394]: [5][Fri Nov 03 15:02:20 2023][19394](src/util.c:315) Number of Upstream gateway(s) [ 1 ]
Nov 03 15:02:20 myhome opennds[19394]: Number of Upstream gateway(s) [ 1 ]
Nov 03 15:04:01 myhome opennds[23107]: sh: 1: null: not found
Nov 03 15:04:01 myhome opennds[19394]: [5][Fri Nov 03 15:04:01 2023][19394](src/client_list.c:134) Adding 192.168.174.174 6c:7e:67:b7:f6:0f token 470f3585 to client list
Nov 03 15:04:01 myhome opennds[19394]: Adding 192.168.174.174 xx:xxx:xx:xxx f token 470f3585 to client list
Nov 03 15:04:54 myhome opennds[19394]: [5][Fri Nov 03 15:04:54 2023][19394](src/util.c:315) Number of Upstream gateway(s) [ 1 ]
Nov 03 15:04:54 myhome opennds[19394]: Number of Upstream gateway(s) [ 1 ]

```

**Comment by bluewavenet** [comment]
@karam 

> ```
> ==================
> openNDS Status
> ====
> Version: 10.1.3
> Uptime: 10m 17s
> ```

This indicates openNDS is running.

> The captive portal does not load

By this, I assume you mean the login page does not appear.

Your config has numerous problems:

`	option fas_secure_enabled '0'`

This has been deprecated for some time as insecure - it was never intended for use on an Internet hosted FAS server. It may not even work on such a server.

You should be using level 1 or above.

Levels 1 and 2 support an https FAS server hosted anywhere.

Level 3 supports an https FAS server hosted on the Internet. (the upcoming openNDS v 10.2.0 also supports level 4, a FAS type for routers with limited resources where an https Internet hosted FAS is required.)

Walledgarden support is not required if the FAS server only has a single ip address (ie it is _not_ hosted on a CDN).

`	option gatewayfqdn 'disable'`

Why have you disabled this? The ability to disable it is for edge cases and would not normally be done.

```
list users_to_router 'allow udp port 53'
	list users_to_router 'allow tcp port 53'
	list users_to_router 'allow udp port 67'
	list users_to_router 'allow tcp port 22'
	list users_to_router 'allow tcp port 80'
	list users_to_router 'allow tcp port 443'
	
```

These entries are the defaults and to not need to be present.

`	option fasport '2080'`
Normally an Internet hosted FAS will be port 80 for http (levels 1 and 2), or port 443 for https (level 3). 2080 is not necessarily incorrect if this was your intention. 

I would expect your config to look _something_ like this:
```
config opennds
	
	option gatewayinterface 'enp174s0'
	option fasport '2080'
	option faspath '/'
	option fasremoteip '128.199.13.149'
	option fasremotefqdn 'wdlgn.com'
	option fas_secure_enabled '2'
```

**What is your remote FAS running?**

Example php scripts are provided to get you started.
These are fas-hid.php (http protocol, level 1), fas-aes.php (both http protocol, level 2) and fas-aes-https.php (https protocol, level 3).
I would suggest you start with one of these before moving on to your own customisation.

`Nov 03 15:04:01 myhome opennds[23107]: sh: 1: null: not found`

This, I think, is a cosmetic output generated by some implementations of BASH and is not an issue. openNDS starts ok anyway.

**Comment by karam** [comment]
@bluewavenet 
Thank you for taking the time for the detailed response!
I will try the notes you suggested and get back shortly. 

In the interim, I wanted to enquire- would you be open to supporting opennds commercially for my company ?
We would like to get opennds up and running on our systems as soon as possible and would be happy to pay for support if necessary.

**Comment by bluewavenet** [comment]
@karam 
Feel free to email me with any commercial enquiries.

**Comment by karam** [comment]
Great, emailing you at the address mentioned in the releases page
