### ISSUE TITLE
Captive portal login page

### ISSUE THREAD

**Issue by davidpiedrarojas** [openNDS/openNDS#543]
I installed opennds on a  openwrt. I´m trying to change the default splash page. Change de configuration to use simple a login, set the option login_option_enabled '2' and option login_option_enabled '3', then I've changed every file in /usr/lib/opennds but still the same splash page.

Are the files that should be changed in other location?

Thanks

**Comment by davidpiedrarojas** [comment]
Hello, thanks for your answer. The opennds is in a Openwrt version OpenWrt 22.03.5 r20134-5f15225c1e.

> I'm surprised it works at all if you have changed "every file" ;-)

I changed one at a time, not all at once :-)

> You could, for example, make a copy of theme_user-email-login-basic.sh and name the copy "my_test_themespec.sh" and configure themespec_path accordingly.

I have been doing this, I've used option 2 and 3 but still haven't seen the changes on the landing page, I also restarted the service everytime I made any change. All changes have been small, just change the title to see if it works.

**Comment by bluewavenet** [comment]
@davidpiedrarojas 
If your working file is named "my_test_themespec.sh", then add the following to the config file:

```
option themespec_path '/usr/lib/opennds/my_test_themespec.sh'
option login_option_enabled '3'
```

Then restart opennds:
`service opennds restart`

This should now respond as the original ThemeSpec script did, such as the "Click to Continue" script.

Once this is working you can try editing your custom script.

Look for the function `header()`

You will find this contains some html.
Try adding a comment to it.
eg The last line of html is : 
`		<div class=\"insert\" style=\"max-width:100%;\">`

Insert the following line just after it:
`		<br>Hello World<br>`

Now reconnect and you should see the text you added on the login page.
