### ISSUE TITLE
PHP FAS?

### ISSUE THREAD

**Issue by katexu7** [openNDS/openNDS#55]
Hi,

I've tried following all the instructions to get a local PHP page hosted through nodogsplash captive portal. Everything works when I just use splash.html as the captive portal. However, when I try to change it to PHP by following the instructions for FAS (within the fas-aes.php file), it redirects the user to download the actual PHP file. This leads me to think that there is no Apache/lighttpd running the PHP file? Are there instructions anywhere detailing this? Do I need to host it in a different directory like /var/www/html/index.php to get it up and running? I'm a little confused because the instructions specify that the faspath has to be relative to the /etc/nodogsplash/htocs directory.

I've changed the following in nodogsplash.conf

option fasport '2050' (Should this be the same as the gateway port for locally hosted FAS?)
option faskey '1234567890'
option faspath '/fas-aes.php

Everything else is default (fas_secure_enabled set at default 1) / same as non-FAS captive portal.

And I read other sources that says nodogsplash does not support PHP. I assume this just means it can't be done directly as splash.php? Otherwise it's a little confusing why fas-aes.php be written in PHP?

I have also installed cli-php7.3 (or whatever it was called) as well as apache2 & lighttpd with the same problem persisting.

Given that NDS has now been split into openNDS, could you explain what the main difference is? Is there a separate package I need to install (sudo apt-get install)?

Hardware: Raspberry Pi 2 / RPi Zero WiFi

OS: Raspbian Buster

Thanks and advance.

**Comment by bluewavenet** [comment]
@katexu7 

The following assumes you have configured your pi correctly as a NAT router with its own unique ip4 subnet served with dhcp on the wifi and you can connect to the wifi and access the Internet feed connected to your ethernet port (A pi zero w must use a second usb network interface).
 
First you should un-install/delete NoDogSplash.
The download openNDS and compile.
Full instructions are in the documentation:
https://opennds.readthedocs.io/en/stable/compile.html#how-to-compile-opennds

The latest release of MHD is 0.9.71 and is the minimum version you require for the current release of openNDS.
The latest version of openNDS is  v6.0.0
Substitute these version numbers in the instructions where appropriate.

Once openNDS is installed you must edit /etc/opennds/opennds.conf
Set GatewayInterface to reflect the interface name you previously gave to the pi's wifi.
**Do NOT make any other changed at this stage.**
Save opennds.conf

Start openNDS:
`systemctl start opennds`

Check the status of openNDS with the commands:
`systemctl status opennds`
and
`ndsctl status`

Before making any changes, make sure openNDS is running correctly by connecting to the wifi with your phone or something similar. You should get the basic splash.htm splash page.

Once you are at this stage we can move on to setting up FAS.
FAS documentation:
https://opennds.readthedocs.io/en/stable/fas.html

**Comment by katexu7** [comment]
ndsctl: opennds probably not started (Error: No such file or directory)?

PS. It's interesting that the versioning has to be exact with wget rather than something like git clone.

**Comment by katexu7** [comment]
Using versions 0.9.70 and 5.2.0 as per example.

**Comment by bluewavenet** [comment]
@katexu7 

> It's interesting that the versioning has to be exact with wget rather than something like git clone

**wget** with **version number** allows you to specify a valid (and tested) release version.

**git clone** gives you a snapshot of the current state of the development environment with no guarantee it will work at the particular time you do the git clone.

**Comment by bluewavenet** [comment]
@katexu7 
As I mentioned earlier, check the status with:
`systemctl status opennds`

I also mentioned:

> Set GatewayInterface to reflect the **interface name** you previously gave to the pi's wifi.

Note this is the **interface name** and NOT the SSID

You can list the interfaces by running:
`ip addr`

> Do I need to specify IP address or anything?

**No**. Note my comment - do not change anything else yet.

Note also that the many online "nodogsplash" tutorials for rpi are all very **outdated** and some are also **incorrect**. Pay little or no attention to them as they invariably lead people down dead end rabbit holes resulting in much confusion.

**Comment by katexu7** [comment]
Awesome. Got it working to get the OpenNDS gas.php up and running. Thanks for your help!  Next I'll just need to figure out which parts I could discard vs need to keep. Will have a play around with it.

**Comment by bluewavenet** [comment]
@katexu7 

> Got it working to get the OpenNDS gas.php up and running

I'm not sure what you mean. :-D
You have it working with fas-aes.php?
What web server did you choose for the FAS?
Is it local or remote?

Perhaps you meant:

> Got it working. Now to get the OpenNDS fas-aes.php up and running.

**Comment by katexu7** [comment]
Fas-aes.php autocorrect these days...

**Comment by bluewavenet** [comment]
@katexu7 
Excellent. Is it all running on the pi, or is the FAS remote?
What web server are you using? Just for interest.

**Comment by katexu7** [comment]
It's running on the pi, not remote. I want to build a locally hosted server but ideally accessed through a captive portal instead of typing some ip in the browser. But it seems really fragile. I changed a thing or two and its not working again... its making me download the fas-aes.php instead of heading to that page now.. so I've done a complete clean re-install and repeated all previous steps up to the opennds fas example page. 

I guess the next question is - how do I change from fas.php to a php  page i want to host? 

e.g. <?php echo "hello" ?>

Do I have to get all the details from fas.php "submitted" before I could forward onto my own PHP pages? or do I just modify the content of fas.php to whatever I want - e.g. echo "hello"; and ignore all the $iv, $string, $fas etc?

Is lighttpd as a web server sufficient for running php pages in general? If not, do I need something more traditional? like using apache2 or nginx..

**Comment by katexu7** [comment]
Ran into issue again when using versions 6.0.0 and 0.9.71.... guess I'll have to uninstall it and reinstall 0.9.70.

**Comment by bluewavenet** [comment]
@katexu7 
You are chasing your tail :-D
I don't mean this in a bad way but I suggest you read and digest the documentation as you seem to have very little idea of how it works. I want to encourage, not discourage, but please read it:
https://opennds.readthedocs.io

I am happy to help, but you really must make some effort to understand as much as possible from the documentation.

Think of openNDS as the "engine" that captures clients, and FAS as the portal that serves the login dialogue.

To run php web pages you MUST have a web server that supports php (of course).
eg Lighttpd is very fast and robust, but Ngnix and Apache are of course very good too. All 3 of these will run a php FAS with no problem at all. My personal preference is Lighttpd as it is fast and compact as well as fully functional.

Having read ALL the documentation, go back and read this bit again:
https://opennds.readthedocs.io/en/stable/fas.html#forwarding-authentication-service-fas

> Do I have to get all the details from fas.php "submitted" before I could forward onto my own PHP pages? or do I just modify the content of fas.php to whatever I want - e.g. echo "hello"; and ignore all the $iv, $string, $fas etc?

I reiterate: Read the documentation. openNDS and fas-aes.php communicate using encrypted query strings.
Yes, the simplest way is to modify fas-aes for your own requirements. Have you read (and understood) the php code in fas-aes.php? Do you have any experience in php?
The code in fas-aes.php is structured to make it easy to modify the login page dialogue, easy to change or add fields of user entered data etc.

**Comment by katexu7** [comment]
Ok. I think I got a bit confused earlier. I thought the new splash.html page (opennds compared to nodogsplash) was the fas-aes.php page. 

So I think I'm back where I started in terms of fas-aes.php being downloaded instead of loading... Is it because I don't have some other server? I think that means I need to make some separate webserver for the php - like to install lighttpd/apache2?

So if I just want a captive portal with PHP / SQL scripts running, I don't really need FAS do I (not intending for guests to browse the internet after)? I just need to install some other server to host it?

TBH, I don't have much idea about networks & linux although I do have some knowledge of php & python. I usually just blindly following instructions to set up servers and then code PHP from there.

**Comment by bluewavenet** [comment]
@katexu7 
fas-aes.php needs a web server to run on, yes.
It can either be local or remote or remote on the Internet.
(you still haven't read the documentation have you? :-D )

If you don't want guests to browse the internet after, then don't give them a login page and don't send authentication to openNDS

It all depends on what information you want to give your guests on this web site. You can instead write the FAS in linux script, Python, PHP-CLI or even write a compiled C program. openNDS can be configured to call whatever you write and serve the output to the client.

There is a live and fully functional example pre-installed.
Give it a try.
Edit the /etc/opennds/opennds.conf file and change the line:

`login_option_enabled 0`

to read

`login_option_enabled 1`

Then
`systemctl restart opennds`

Now try connecting with your phone.

This is being generated by the file `/usr/lib/opennds/login.sh`

**Comment by katexu7** [comment]
To be fully frank with you, I've read over it many times over. It is just that I find it quite hard to relate to because its all to do with authorizing users, security protocols / hashing etc which is going off on a tangent of the typical captive portal for internet access route. 

I read the nodogsplash one many times over, and also opennds one many times.. but I think I have come to the conclusion that I don't need the FAS at all, and the reason why my splash php is not working is not because I do not have a FAS, but because I have not installed the server to manage it. 

Will go back to doing that with some trial & error to hopefully get it to work. There is just so few documentations on captive portals in general, and even less if it isn't to provide internet access.

**Comment by bluewavenet** [comment]
@katexu7 
Perhaps I should have asked what you were trying to do!

If you don't want anyone to use your system for unrestricted Internet access, it is really simple.
Really, try this quick hack -
Edit /etc/opennds/opennds.conf and set the following lines:
```
fasport 443
faspath /
fasremoteip 139.59.209.225
fasremotefqdn openwrt.org
```

This will then send clients to the OpenWrt web site. But they will not be able to access anything else, nor will they be able to log in. (dont forget to restart opennds after saving the config)

**Comment by katexu7** [comment]
Exactly what I was looking for. Single page, nothing else. Cheers!
