### ISSUE TITLE
Not possible deny access via binauth script. 

### ISSUE THREAD

**Issue by CDwrt** [openNDS/openNDS#551]
If binauth script is called with method auth_client and exits with return code other than 0 then NDS is supposed to deny access to the client requesting authentication. However that doesn't happen. 
Debug log shows the following:
```
daemon.debug opennds[]: Executing command: /usr/lib/opennds/binauth.sh auth_client '99:e7:2c:29:ff:a4' '' '<UserAgent>' '192.168.128.119' 'e5c7a6c9' 'bmE%3d'
daemon.debug opennds[]: Reading command output
daemon.info opennds[]: binauth.sh invoked
daemon.debug opennds[]: command output: []
daemon.debug opennds[]: BinAuth returned arguments:
daemon.debug opennds[]: BinAuth script failed to execute
daemon.debug opennds[]: Locking client list
daemon.debug opennds[]: Client list locked
daemon.notice opennds[]: Authenticating 192.168.128.119 99:e7:2c:29:ff:a4 
```
"BinAuth script failed to execute" message is misleading. I'm able to validate that it executes with exit code 1. 

The following code in do_binauth()  (http_microhttpd.c line 209) seems to be the culprit:
```
	if (rc != 0) {
		debug(LOG_DEBUG, "BinAuth script failed to execute");
		free(msg);
		return 0;
	}
```
When do_binauth() is called from authenticate_client() it can only return 0 back regardless of the actual exit code on binauth script, so authenticate_client() always continues to authenticate the client.

**Comment by bluewavenet** [comment]
@CDwrt 

> with return code other than 0 then NDS is supposed to deny access to the client requesting authentication

This was deprecated with the initial release of version 9 and removed with the initial release of version 10.
Returning a non zero exit value is intended to indicate that binauth terminated with an error.

**All client validation should be done by FAS (or ThemeSpec).**

Perhaps the debug message should be "BinAuth script terminated with an error code".

The only artefact I can see of the deprecated use of exit code is a comment at the end of `binauth_log.sh`.

**Comment by bluewavenet** [comment]
@CDwrt 

> If this was an intentional change of functionality 

It was.

I do not see any mention of denying access in the documentation for binauth, where did you find it?

Docs:
https://opennds.readthedocs.io/en/stable/binauth.html#binauth-option

As I stated:

> The only artefact I can see of the deprecated use of exit code is a comment at the end of binauth_log.sh.

This will be edited.

> is there a way to include client MAC address into the client validation via ThemeSpec?

Yes.
Presumably you wrote some code intending to run it from binauth? You would do it the same way in ThemeSpec.

When a ThemeSpec script is called by openNDS, it is passed a list of variables, as follows:
```
hid
clientip
clientmac
client_type
cpi_query
gatewayname
gatewayurl
version
gatewayaddress
gatewaymac
originurl
clientif

```

A good place to add your code would be in `landing_page ()`, before `auth_log` is called but it depends on what you want to achieve.

**Comment by CDwrt** [comment]
@bluewavenet 
> I do not see any mention of denying access in the documentation for binauth, where did you find it?
https://opennds.readthedocs.io/en/stable/howitworks.html at the bottom of the "The Thing That Provides the Portal (FAS, PreAuth, Themespec)" section: "Typically, BinAuth is used to provide a local log of authenticated clients. In addition the BinAuth script can override client authentication if required."

Also there is a code section in authenticate_client()  (http_microhttpd.c lines 642-660) that checks do_binauth() return code and has following comments:
```
if (rc != 0) {
			/*BinAuth denies access so redirect client back to login/splash page where they can try again.
				If FAS is enabled, this will cause nesting of the contents of redirect_url,
				FAS should account for this if used with BinAuth.
			*/
```
That entire if(){} statement seems like a dead code now that do_binauth() always returns 0 regardless of binauth script exit code.

> A good place to add your code would be in landing_page (), before auth_log is called
Thank you for the advice, I'll attempt to add my code there.
