### ISSUE TITLE
Scalability Concern

### ISSUE THREAD

**Issue by kardiff7** [openNDS/openNDS#552]
Hi,
I have been playing around with OpenNDS and have found a potential scalability issue. When multiple users are performing actions against OpenNDS (connect, disconnect, check balance) I found it easy to hit a limit in ndsctl, receiving the below error :

`ndsctl thread is busy, please try later`

My understanding is that clicking on "Connect" (auth), "Disconnect" (deauth) or "Refresh" (status) uses ndsctl, which in turn seems to be single-threaded. How can I ensure scalability for multiple concurrent users?
Thank you

**Comment by bluewavenet** [comment]
@kardiff7 
Please specify the version of openNDS, the operating system and the hardware it is running on.

> I found it easy to hit a limit in ndsctl,

In previous testing it has proven very difficult to hit this limit and there are known systems with many hundreds of concurrent users that are not exhibiting this issue as far as I know.

> check balance

What is `check balance`?

**Comment by kardiff7** [comment]
@bluewavenet 
I am using 10.1.3 inside an Ubuntu jammy container, running on a x64 host (Intel Atom C). The "check balance" is my attempt to describe the stats shown on the NDS splash page. 
I managed to get that issue with only 2 users refreshing the NDS page concurrently and I can consistently reproduce it by running 

`watch -n 1 ndsctl status`

and refreshing the page eventually gets me this

![image](https://github.com/openNDS/openNDS/assets/138241367/28ac1a39-17c3-4e8e-a4ac-ad19c638506a)

Thank you

**Comment by bluewavenet** [comment]
@kardiff7 
First of all, the current version of openNDS is v10.2.0, you should consider upgrading as the version you are using is EOL.

> I can consistently reproduce it

I am sure you can if you are running ndsctl once per second with `watch`.
openNDS runs its own queueing system for ndsctl but you are defeating it by running watch. All you have achieved is triggering a lock on ndsctl designed to prevent runaway memory consumption if someone does what you have done.

> Ubuntu jammy container, running on a x64 host (Intel Atom C)

This is likely to result in a relatively slow response from ndsctl, compounding the issue.

**Comment by kardiff7** [comment]
@bluewavenet 
Understood and I have just tested it with v10.2.0. as well. The issue I am reporting was observed with only 2  users connected to system. I am only using watch to reproduce it independently. In any case, is receiving more than 1 request per second beyond the limit of ndsctl?

> This is likely to result in a relatively slow response from ndsctl, compounding the issue.

Which of these conditions would affect the performance of ndsctl: Running in a container, running on Ubuntu, running on Atom C?

**Comment by kardiff7** [comment]
I have also tried the provided testing utility in community/testing/ndsctl-testing
 
Results:
 
```test# ./ndsctltest.sh

Iteration 0 forked:

Iteration 1 forked:

Iteration 2 forked:

Iteration 3 forked:

Iteration: 1, Return Code: 4, Return Value: busy

Iteration 4 forked:

Iteration: 2, Return Code: 4, Return Value: busy

Iteration 5 forked:

Iteration: 3, Return Code: 4, Return Value: busy

Iteration 6 forked:

Iteration: 4, Return Code: 4, Return Value: busy

Iteration 7 forked:

Iteration: 5, Return Code: 4, Return Value: busy

Iteration 8 forked:

Iteration: 6, Return Code: 4, Return Value: busy

Iteration 9 forked:

Iteration: 7, Return Code: 4, Return Value: busy

Iteration 10 forked:

Iteration: 8, Return Code: 4, Return Value: busy

Iteration 11 forked:

Iteration: 9, Return Code: 4, Return Value: busy

Iteration 12 forked:

Iteration: 10, Return Code: 4, Return Value: busy

Iteration 13 forked:

Iteration: 11, Return Code: 4, Return Value: busy

Iteration 14 forked:

Iteration: 12, Return Code: 4, Return Value: busy

Iteration 15 forked:

Iteration: 13, Return Code: 4, Return Value: busy

Iteration: 0, Return Code: 0, Return Value: Version: 10.2.0

Iteration 16 forked:

Iteration: 14, Return Code: 4, Return Value: busy

Iteration: 16, Return Code: 0, Return Value: Version: 10.2.0

Iteration 17 forked:

Iteration: 15, Return Code: 4, Return Value: busy

Iteration: 17, Return Code: 0, Return Value: Version: 10.2.0

Iteration 18 forked:

Iteration: 18, Return Code: 0, Return Value: Version: 10.2.0

Iteration 19 forked:

Iteration 20 forked:

Iteration 21 forked:

Iteration 22 forked:

Iteration: 20, Return Code: 4, Return Value: busy

Iteration 23 forked:

Iteration: 21, Return Code: 4, Return Value: busy

Iteration 24 forked:

Iteration: 22, Return Code: 4, Return Value: busy

Iteration 25 forked:

Iteration: 23, Return Code: 4, Return Value: busy

Iteration 26 forked:

Iteration: 24, Return Code: 4, Return Value: busy

Iteration 27 forked:

Iteration: 25, Return Code: 4, Return Value: busy

Iteration 28 forked:

Iteration: 26, Return Code: 4, Return Value: busy

Iteration 29 forked:

Iteration: 27, Return Code: 4, Return Value: busy
Iteration: 28, Return Code: 4, Return Value: busy

Iteration: 29, Return Code: 4, Return Value: busy
Iteration: 19, Return Code: 0, Return Value: Version: 10.2.0
```[2:05 PM] Anastasis Gryponisiotis
I have also tried the provided testing utility in community/testing/ndsctl-testing
 
Results:
 
```test# ./ndsctltest.sh

Iteration 0 forked:

Iteration 1 forked:

Iteration 2 forked:

Iteration 3 forked:

Iteration: 1, Return Code: 4, Return Value: busy

Iteration 4 forked:

Iteration: 2, Return Code: 4, Return Value: busy

Iteration 5 forked:

Iteration: 3, Return Code: 4, Return Value: busy

Iteration 6 forked:

Iteration: 4, Return Code: 4, Return Value: busy

Iteration 7 forked:

Iteration: 5, Return Code: 4, Return Value: busy

Iteration 8 forked:

Iteration: 6, Return Code: 4, Return Value: busy

Iteration 9 forked:

Iteration: 7, Return Code: 4, Return Value: busy

Iteration 10 forked:

Iteration: 8, Return Code: 4, Return Value: busy

Iteration 11 forked:

Iteration: 9, Return Code: 4, Return Value: busy

Iteration 12 forked:

Iteration: 10, Return Code: 4, Return Value: busy

Iteration 13 forked:

Iteration: 11, Return Code: 4, Return Value: busy

Iteration 14 forked:

Iteration: 12, Return Code: 4, Return Value: busy

Iteration 15 forked:

Iteration: 13, Return Code: 4, Return Value: busy

Iteration: 0, Return Code: 0, Return Value: Version: 10.2.0

Iteration 16 forked:

Iteration: 14, Return Code: 4, Return Value: busy

Iteration: 16, Return Code: 0, Return Value: Version: 10.2.0

Iteration 17 forked:

Iteration: 15, Return Code: 4, Return Value: busy

Iteration: 17, Return Code: 0, Return Value: Version: 10.2.0

Iteration 18 forked:

Iteration: 18, Return Code: 0, Return Value: Version: 10.2.0

Iteration 19 forked:

Iteration 20 forked:

Iteration 21 forked:

Iteration 22 forked:

Iteration: 20, Return Code: 4, Return Value: busy

Iteration 23 forked:

Iteration: 21, Return Code: 4, Return Value: busy

Iteration 24 forked:

Iteration: 22, Return Code: 4, Return Value: busy

Iteration 25 forked:

Iteration: 23, Return Code: 4, Return Value: busy

Iteration 26 forked:

Iteration: 24, Return Code: 4, Return Value: busy

Iteration 27 forked:

Iteration: 25, Return Code: 4, Return Value: busy

Iteration 28 forked:

Iteration: 26, Return Code: 4, Return Value: busy

Iteration 29 forked:

Iteration: 27, Return Code: 4, Return Value: busy
Iteration: 28, Return Code: 4, Return Value: busy

Iteration: 29, Return Code: 4, Return Value: busy
Iteration: 19, Return Code: 0, Return Value: Version: 10.2.0
```

**Comment by bluewavenet** [comment]
@kardiff7 
openNDS has an ndsctl queue timeout of 16 seconds. This means if an ndsctl request is not fulfilled within this interval, the request will be dropped. If the client status page encounters a dropped request, the result will be as you posted.
This however is very unlikely to occur under normal circumstances and if it does it usually indicates problems outside openNDS such as OOM issues or cpu congestion.

There are numerous systems that I am aware of that support many hundreds of concurrent users with zero reports of this issue. These are running on ranges of hardware from standard dedicated router hardware running OpenWrt through to dedicated corporate data centre servers running OpenSuse and other flavours of Linux.

This leads me to suspect the issue lies somewhere with your particular setup. 

> In any case, is receiving more than 1 request per second beyond the limit of ndsctl?

This depends entirely on your hardware. For example, on a system running OpenWrt on an MT7621 based router hardware with sometimes over 200 concurrent users, there have been no reports of this issue. There are currently 53 users on that system, and running `ndsctl status` is taking approximately 0.75 seconds on average.

> testing utility in community/testing/ndsctl-testing

This utility was designed to look for segfaults and oom issues caused by concurrent ndsctl calls in an early version of openNDS. Clearly you are not seeing crashes so the ndsctl locking mechanism is working as intended.

The test utility has only a 2 second queue length and in your output you can see iteration 1 fails, meaning the iteration 0 ndsctl command is taking longer than 2 seconds to complete. My guess is your "container" is running very slowly.
