### ISSUE TITLE
Skip fasremoteip

### ISSUE THREAD

**Issue by 0l4y4** [openNDS/openNDS#554]
Hello,

I have my openNDS FAS 3 connected to my login webpage and I want to change my webpage to another hosting in the future, then I was wondering if is enought  with the option "option fasremotefqdn" without fasremoteip.

Thanks

**Comment by bluewavenet** [comment]
@0l4y4 

> if is enought with the option "option fasremotefqdn" without fasremoteip.

Yes, for openNDS version 10.2.0 onwards, if you have `option fasremotefqdn`, you can remove `option fasremoteip`.

**Comment by 0l4y4** [comment]
That's perfect! Thanks @bluewavenet
