### ISSUE TITLE
memory issue in config and client structure

### ISSUE THREAD

**Issue by brett90063** [openNDS/openNDS#555]
Hi, I downloaded the openNDS code today, and I noticed there are many occurrences of `safe_strdup()` in the `config` and `client` structure.
I'm curious why the values obtained from `safe_strdup()` don't need to be freed.
For example, `client_list.c:118, client->ip = safe_strdup(ip);` there is no corresponding `free(client->ip);` in the `_client_list_free_node` function.

In the config part, I'm also confused because it seems like none of the structures in the `config` are being freed.

According to the [strdup() man page](https://man7.org/linux/man-pages/man3/strdup.3.html)
`The strdup() function returns a pointer to a new string which is a duplicate of the string s. Memory for the new string is obtained with malloc(3), and can be freed with free(3).`, Using `strdup()` should free memory because it's obtain by `malloc`, right?
or am I missing something?

**Comment by bluewavenet** [comment]
@brett90063 

> For example, client_list.c:118, client->ip = safe_strdup(ip); there is no corresponding free(client->ip); in the _client_list_free_node function.

You are probably correct, everything to do with a specific client that is strdup-ed should be specifically freed.... 

> none of the structures in the config are being freed.

None of the configs should ever be freed while the daemon is running as the configs are static, whereas clients can come and go.

**Comment by brett90063** [comment]
> None of the configs should ever be freed while the daemon is running as the configs are static, whereas clients can come and go.

but "if" any possible to let opennds stop like MHD crash or `service opennds restart` etc.
all config obtain by malloc might mem leak

**Comment by bluewavenet** [comment]
@brett90063 

> but "if" some reason cause opennds stop 

If a process terminates, the OS gets all the memory back.
If a process crashes, same.
If a process locks up in a tight loop and you have to manually kill it, same.

Sure, it would be possible to read the config file every time a config value is required but this would not be very efficient and is not required for static config values.

OpenNDS can in fact read _some_ config values whenever needed, but this is only done where those values need to to be dynamic.

Two questions for you:
 1. Did you suspect you had seen a memory leak and then looked for it in the code?
 2. or did you look at the code and thought you could see the potential for a memory leak?

**Comment by brett90063** [comment]
> If a process terminates, the OS gets all the memory back.
> If a process crashes, same.
> If a process locks up in a tight loop and you have to manually kill it, same.

wow this very helpful, I've learned from it, thanks.

---

> Did you suspect you had seen a memory leak and then looked for it in the code?

no
> or did you look at the code and thought you could see the potential for a memory leak?

might yes, I just try to figure out openNDS code, and found strdup issue, but im not sure it's correct or not, so I came here to ask

**Comment by bluewavenet** [comment]
@brett90063 

> I just try to figure out openNDS code

Excellent - _please continue!_
This leads to discussion and at the very least generates new ideas ;-)

> and found strdup issue, but im not sure it's correct

I think it is correct. It is insignificant in the short term but is of course cumulative, so in a busy system up for many months it might become noticeable.

Feedback and discussion is always welcome and can be very constructive - so thank you for your efforts.

**Comment by bluewavenet** [comment]
@brett90063 
I have flagged this as a bug as a reminder to check the code base for missing free()s on hidden malloc()s created by strdup()

**Comment by bluewavenet** [comment]
@brett90063 
This is fixed by commit https://github.com/openNDS/openNDS/pull/561/commits/ca9b3dba9866477bae14e30e9e1e8b0b9d3bcbd1

**Comment by bluewavenet** [comment]
@brett90063 
Thanks again for your efforts ;-)
