### ISSUE TITLE
Error initializing firewall rules

### ISSUE THREAD

**Issue by rafaelfelix** [openNDS/openNDS#556]
Similar issue: https://github.com/openNDS/openNDS/issues/429, opening a new issue as requested by @bluewavenet.

Running OpenWRT 23.05.2 and OpenNDS v10.2.0 running on a Linksys EA4500 v2.

Logs: [opennds.log](https://github.com/openNDS/openNDS/files/13801268/opennds.log)

Additional info:

```bash
root@OpenWrt:~# cat /etc/openwrt_release
DISTRIB_ID='OpenWrt'
DISTRIB_RELEASE='23.05.2'
DISTRIB_REVISION='r23630-842932a63d'
DISTRIB_TARGET='kirkwood/generic'
DISTRIB_ARCH='arm_xscale'
DISTRIB_DESCRIPTION='OpenWrt 23.05.2 r23630-842932a63d'
DISTRIB_TAINTS=''
```

The log lines that caught my attention were:

```
Sun Dec 31 13:21:13 2023 daemon.debug opennds[24586]: Executing command: nft add rule ip nds_nat ndsOUT ip daddr status.client tcp dport 2050 counter accept
Sun Dec 31 13:21:13 2023 daemon.debug opennds[24586]: nftables command [ add rule ip nds_nat ndsOUT ip daddr status.client tcp dport 2050 counter accept ], iteration [ 0 ]return code [ 1 ]
...
Sun Dec 31 13:21:14 2023 daemon.debug opennds[24586]: restart command [ /usr/lib/opennds/dnsconfig.sh "restart_only" & ]
Sun Dec 31 13:21:14 2023 daemon.debug opennds[24586]: SIGCHLD handler: Process PID 27138 exited normally, status 0
Sun Dec 31 13:21:14 2023 daemon.info opennds[24586]: Dnsmasq restarted
Sun Dec 31 13:21:14 2023 daemon.err opennds[24586]: Error initializing firewall rules! Cleaning up
Sun Dec 31 13:21:14 2023 daemon.debug opennds[24586]: Destroying our nftables entries
Sun Dec 31 13:21:14 2023 daemon.debug opennds[24586]: Executing command: /usr/lib/opennds/libopennds.sh "delete_chains"
Sun Dec 31 13:21:14 2023 daemon.debug opennds[24586]: Reading command output
Sun Dec 31 13:21:14 2023 daemon.debug opennds[24586]: command output: []
Sun Dec 31 13:21:14 2023 daemon.info opennds[24586]: Chain delete request sent
Sun Dec 31 13:21:14 2023 daemon.err opennds[24586]: Exiting because of error initializing firewall rules
```

**Comment by bluewavenet** [comment]
@rafaelfelix 
This is almost certainly a race condition caused by dnsmasq taking a considerable time to restart - it has been seen before.

We can do a quick test. Run the following command:
`date; service dnsmasq restart; logread -f -e dnsmasq`

From this we can see how long dnsmasq takes to restart. Normally it would take around 1 second.
In another case it was taking 18 seconds ( @doremifajb ).

A workaround is to patch the file /usr/lib/opennds/dnsconfig.sh as follows:

Line 60 reads:
`/etc/init.d/dnsmasq restart &`

Change it to:
`service dnsmasq restart ; sleep 20`

This will force dnsconfig.sh to wait until dnsmasq has restarted, rather than running the init.d restart in the background without waiting.

After editing, make sure the file is still executable.

Now restart openNDS:
`service opennds restart`

Does it work?

**Comment by rafaelfelix** [comment]
it works! thanks. I had to install `dnsmasq-full`, to leave it as reference if people run into this as well.

**Comment by doremifajb** [comment]
@rafaelfelix 
Do you mean that, after installing `dnsmasq-full`, your dnsmasq takes less time upon startup ? I am interested in your
`date; service dnsmasq restart; logread -f -e dnsmasq`
Did you check that before installing `dnsmasq-full` ? How was it, and how is it after installing `dnsmasq-full `?

**Comment by rafaelfelix** [comment]
@doremifajb
>Do you mean that, after installing dnsmasq-full, your dnsmasq takes less time upon startup?
Not really. Right after I applied the suggested fix, I got some log messages from opennds (which I unfortunately didn't retain) asking for `dnsmasq-full`. Once I installed it, everything worked perfectly (log messages disappeared as well).

**Comment by bluewavenet** [comment]
@rafaelfelix 

> dnsmasq-full

This is only required if you are using walledgarden and/or blocklists, otherwise the normal version is just fine.

**Comment by ganganrobert** [comment]
I replaced the content in usr/lib/opennds/dnsconfig.sh with the new one, but I got the same error.

**Comment by bluewavenet** [comment]
@ganganrobert 

> I replaced the content

Do you mean you edited line 60, or do you mean you overwrote dnsconfig.sh with the version on master?

_**The version of dnsconfig.sh on master will not work with opennds v 10.2.0, it is for the next release.**_ Sorry if I did not make that clear.

**Comment by ganganrobert** [comment]
@bluewavenet 
I did both things : First I added lines to the file and tried testing - got the same error. Then I copied the new code and pasted it into the config.

I also did some tests.
I completely reset the router (openwrt 23.05.2), installed opennds on the br-lan interface - it worked. As soon as I change the interface and add guestzone to firewall opennds gives this error.
Thank you for your quick response!

**Comment by bluewavenet** [comment]
@ganganrobert 

> on the br-lan interface - it worked

Although you seem to be seeing similar symptoms, I think you are getting an entirely unrelated problem.

Please open a new issue and there, show the outputs of:
`uci export opennds`

`uci export network`

and 

`uci export firewall`
