### ISSUE TITLE
Please add real world examples

### ISSUE THREAD

**Issue by sinancetinkaya** [openNDS/openNDS#558]
I just tried to use opennds in openwrt, but I literally gave up.
First, it breaks luci because by default it's enabled and intercepts `br-lan` which makes luci inaccessible.
Second, there has to be an interface added for opennds.

I began to think that the documentation is for network admins who already know what they are doing?
Google search doesn't return anything useful, all I see error reports from people who don't know how to set it up.

I'm pretty sure you spent a good amount of time for this project. Don't you want it to be used by more people?
Some video tutorials of real world examples would be significantly useful.
Thanks

**Comment by bluewavenet** [comment]
@sinancetinkaya 
Am I correct that you are bahtsiz_bedevi on the OpenWrt forum?

As I mentioned on the forum, openNDS is designed to work "out of the box", as long as you are installing on an operational router.

FYI: The pre-requisites for running openNDS can be found here:
https://opennds.readthedocs.io/en/stable/install.html#prerequisites

If you want a real world example, read this:
https://github.com/openNDS/openNDS/issues/509

>  Some video tutorials of real world examples would be significantly useful.

Sure, feel free to create them. This is open source software created by volunteers - contributions are always welcome.

**Comment by sinancetinkaya** [comment]
> Sure, feel free to create them.
I would if I could. A video tutorial from someone who doesn't know how to use opennds won't help anyone.

**Comment by bluewavenet** [comment]
Once you get it working you could at least write something - it would be good feedback at least.

Start by reading #509

**Comment by sinancetinkaya** [comment]
I was using snapshot version with Luci installed. `https://192.168.1.1` is not working in snapshot OpenWRT. Installed stable version and `https://192.168.1.1` is working with OpenNDS with default configuration
