### ISSUE TITLE
Upload/Download Quota Management - How to Keep Last Download/Upload Statistics

### ISSUE THREAD

**Issue by sicelo** [openNDS/openNDS#56]
Amazing piece of software!

I am using openNDS to setup a WiFi hotspot with quotas. The idea is to provide different packages users can subscribe to (in a php FAS application running in the router), and hopefully set those quotas using BinAuth.

When a client gets deauthenticated (e.g. because of sessiontimeout), the statistics for download/upload, as reported by ndsctl, are reset to 0. This means I not able to tell how much of their quota is still available to be restored future sessions (I intend to save this in a simple SQLite database).

As I was writing this issue, I noticed that in the logs, for example, it does show this info:
```Session end time reached, deauthenticating: 192.168.1.135 aa:bb:cc:dd:ee:ff, connected: 15, in: 0kB, out: 0kB```

I don't know how efficient grepping logs would be (OpenWrt is running on x86 machine with 1GB RAM, so we actually can do it without issues, I believe). Regardless, what suggestion would you have regarding the above scenario? When I think about it, perhaps at deauth, openNDS could leave the last upload/download statistics untouched instead of resetting them, and only reset  them when the client's state changes from Preauthenticated to Authenticated.

EDIT: I guess the BinAuth script can take care of this for me, since it gets called at deauth, and has the info available in arg[3] and arg[4] for the deauth methods :-)

Leaving this open for a while in case someone has a better suggestion

**Comment by sicelo** [comment]
Closing. BinAuth is sufficient when used correctly

**Comment by bluewavenet** [comment]
@sicelo 
Yes indeed :-D

**Comment by bluewavenet** [comment]
@sicelo 

> Amazing piece of software!

Thanks on behalf of all the contributors!
