### ISSUE TITLE
Compatibility with OpenWrt 18.06

### ISSUE THREAD

**Issue by davrontb** [openNDS/openNDS#560]
Hello everyone

I have a Tp-link Archer c60 v3 router. OpenWrt 18.06 has been installed on it. I would like to implement Forwarding Authentication Service API (FAS) on the router. But I have a problem with openNDS and OpenWrt 18.06 compatibility. Is it possible to install openNDS to OpenWrt 18.06?

**Comment by bluewavenet** [comment]
@davrontb 
OpenNDS requires nftables but OpenWrt 18.06 does not support it.

You will have to reflash to OpenWrt 23.05.2 or higher before installing openNDS.

**Comment by davrontb** [comment]
Thank you

**Comment by Alialsufayan** [comment]
first thank you for your effort, and what about implementing the voucher authentication system in my linksys WRT32000 router using the producers in your github page. Which OpenWrt version should i stick with to not encounter any problem hopefully ?
Tanke you again. @bluewavenet

**Comment by bluewavenet** [comment]
@Alialsufayan 

> WRT32000

Do you mean WRT3200ACM?

**Comment by Alialsufayan** [comment]
Yes, that is my router model.

**Comment by bluewavenet** [comment]
@Alialsufayan 
OpenWrt 23.05.2 is the current stable version (Jan 2024)
https://firmware-selector.openwrt.org/
