### ISSUE TITLE
openNDS Starts and then immediately Fails with light log trace

### ISSUE THREAD

**Issue by dtbayles** [openNDS/openNDS#565]
I am working on installing openNDS on a R-Pi (RACHEL server running Linux). I have followed all the [steps here](https://opennds.readthedocs.io/en/stable/compile.html) and have gotten the same result both times. I tried again a third time with a more up-to-date version of `libmicrohttpd-0.9.77`.

Everything `make`'s just fine. When I get to the last bit and do:

```
sudo systemctl enable opennds
sudo systemctl start opennds
sudo ndsctl status
```

I get this:

`ndsctl: opennds probably not yet started (Error: No such file or directory)
`

When I run `sudo systemctl status opennds`, I get this:

```
opennds.service - openNDS Captive Portal
   Loaded: loaded (/etc/systemd/system/opennds.service; enabled; vendor preset: enabled)
   Active: activating (auto-restart) (Result: exit-code) since Fri 2024-02-09 01:42:42 GMT; 1s ago
  Process: 22370 ExecStart=/usr/bin/opennds -b (code=exited, status=0/SUCCESS)
 Main PID: 22446 (code=exited, status=1/FAILURE)
```

And when I run `sudo journalctl -e`, here is the output:

```
Jan 28 06:24:19 rachel systemd[1]: opennds.service: Main process exited, code=exited, status=1/FAILURE
Jan 28 06:24:19 rachel systemd[1]: opennds.service: Failed with result 'exit-code'.
Jan 28 06:24:39 rachel systemd[1]: opennds.service: Service RestartSec=20s expired, scheduling restart.
Jan 28 06:24:39 rachel systemd[1]: opennds.service: Scheduled restart job, restart counter is at 493.
Jan 28 06:24:39 rachel systemd[1]: Stopped openNDS Captive Portal.
Jan 28 06:24:39 rachel systemd[1]: Starting openNDS Captive Portal...
Jan 28 06:24:40 rachel systemd[1]: Started openNDS Captive Portal.
Jan 28 06:24:40 rachel systemd[1]: opennds.service: Main process exited, code=exited, status=1/FAILURE
Jan 28 06:24:40 rachel systemd[1]: opennds.service: Failed with result 'exit-code'.
Jan 28 06:25:00 rachel systemd[1]: opennds.service: Service RestartSec=20s expired, scheduling restart.
Jan 28 06:25:00 rachel systemd[1]: opennds.service: Scheduled restart job, restart counter is at 494.
Jan 28 06:25:00 rachel systemd[1]: Stopped openNDS Captive Portal.
Jan 28 06:25:00 rachel systemd[1]: Starting openNDS Captive Portal...
Jan 28 06:25:00 rachel systemd[1]: Started openNDS Captive Portal.
Jan 28 06:25:00 rachel systemd[1]: opennds.service: Main process exited, code=exited, status=1/FAILURE
Jan 28 06:25:00 rachel systemd[1]: opennds.service: Failed with result 'exit-code'.
```

I verified the following in `/etc/config/opennds`

```
config opennds
	option enabled 1
	option debuglevel '3'
```

Any ideas what might be going on? I was able to run nodogsplash on this device, perhaps I missed something when tearing that down?

**Comment by dtbayles** [comment]
^^ noticed my datetime was off by a few days. I updated it and nothing changed

**Comment by bluewavenet** [comment]
@dtbayles 
Which version of opennds did you install?
`opennds -v`

Setting debuglevel to 3 should produce loads of output in journalctl.

Try:
`sudo service opennds restart; journalctl -f`

You should see opennds trying to start up and an error message of some kind as it shuts down again.

Also show the output of:
`sudo nft list ruleset`

and

`sudo ip addr`

> I verified the following in /etc/config/opennds

There is no setting for  gatewayinterface. This defaults to br-lan, the common name for the lan bridge device, but in your case is probably different.
See:
https://opennds.readthedocs.io/en/stable/config.html#set-the-gatewayinterface

**Comment by dtbayles** [comment]
@bluewavenet thanks for responding so quick and helping here as well as in `nodogsplash`. I'm learning from you!

> Which version of opennds did you install?

```
opennds -v
This is openNDS version 10.2.0
```

> Try:
`sudo service opennds restart; journalctl -f`

```
pi@rachel:~ $ sudo service opennds restart; journalctl -f
-- Logs begin at Thu 2019-02-14 10:12:00 GMT. --
Feb 09 15:33:58 rachel systemd[1]: Starting openNDS Captive Portal...
Feb 09 15:33:59 rachel systemd[1]: Started openNDS Captive Portal.
Feb 09 15:33:59 rachel systemd[1]: opennds.service: Main process exited, code=exited, status=1/FAILURE
Feb 09 15:33:59 rachel systemd[1]: opennds.service: Failed with result 'exit-code'.
Feb 09 15:34:03 rachel sudo[24095]:       pi : TTY=pts/0 ; PWD=/home/pi ; USER=root ; COMMAND=/usr/sbin/service opennds restart
Feb 09 15:34:03 rachel sudo[24095]: pam_unix(sudo:session): session opened for user root by pi(uid=0)
Feb 09 15:34:03 rachel systemd[1]: Stopped openNDS Captive Portal.
Feb 09 15:34:03 rachel systemd[1]: Starting openNDS Captive Portal...
Feb 09 15:34:03 rachel systemd[1]: Started openNDS Captive Portal.
Feb 09 15:34:03 rachel sudo[24095]: pam_unix(sudo:session): session closed for user root
Feb 09 15:34:03 rachel systemd[1]: opennds.service: Main process exited, code=exited, status=1/FAILURE
Feb 09 15:34:03 rachel systemd[1]: opennds.service: Failed with result 'exit-code'.
Feb 09 15:34:23 rachel systemd[1]: opennds.service: Service RestartSec=20s expired, scheduling restart.
Feb 09 15:34:23 rachel systemd[1]: opennds.service: Scheduled restart job, restart counter is at 2559.
Feb 09 15:34:23 rachel systemd[1]: Stopped openNDS Captive Portal.
Feb 09 15:34:23 rachel systemd[1]: Starting openNDS Captive Portal...
Feb 09 15:34:24 rachel systemd[1]: Started openNDS Captive Portal.
Feb 09 15:34:24 rachel systemd[1]: opennds.service: Main process exited, code=exited, status=1/FAILURE
Feb 09 15:34:24 rachel systemd[1]: opennds.service: Failed with result 'exit-code'.
Feb 09 15:34:44 rachel systemd[1]: opennds.service: Service RestartSec=20s expired, scheduling restart.
Feb 09 15:34:44 rachel systemd[1]: opennds.service: Scheduled restart job, restart counter is at 2560.
Feb 09 15:34:44 rachel systemd[1]: Stopped openNDS Captive Portal.
Feb 09 15:34:44 rachel systemd[1]: Starting openNDS Captive Portal...
Feb 09 15:34:44 rachel systemd[1]: Started openNDS Captive Portal.
Feb 09 15:34:44 rachel systemd[1]: opennds.service: Main process exited, code=exited, status=1/FAILURE
Feb 09 15:34:44 rachel systemd[1]: opennds.service: Failed with result 'exit-code'.
Feb 09 15:35:04 rachel systemd[1]: opennds.service: Service RestartSec=20s expired, scheduling restart.
Feb 09 15:35:04 rachel systemd[1]: opennds.service: Scheduled restart job, restart counter is at 2561.
Feb 09 15:35:04 rachel systemd[1]: Stopped openNDS Captive Portal.
Feb 09 15:35:04 rachel systemd[1]: Starting openNDS Captive Portal...
Feb 09 15:35:05 rachel systemd[1]: Started openNDS Captive Portal.
Feb 09 15:35:05 rachel systemd[1]: opennds.service: Main process exited, code=exited, status=1/FAILURE
Feb 09 15:35:05 rachel systemd[1]: opennds.service: Failed with result 'exit-code'.
Feb 09 15:35:25 rachel systemd[1]: opennds.service: Service RestartSec=20s expired, scheduling restart.
Feb 09 15:35:25 rachel systemd[1]: opennds.service: Scheduled restart job, restart counter is at 2562.
Feb 09 15:35:25 rachel systemd[1]: Stopped openNDS Captive Portal.
Feb 09 15:35:25 rachel systemd[1]: Starting openNDS Captive Portal...
Feb 09 15:35:25 rachel systemd[1]: Started openNDS Captive Portal.
Feb 09 15:35:25 rachel systemd[1]: opennds.service: Main process exited, code=exited, status=1/FAILURE
Feb 09 15:35:25 rachel systemd[1]: opennds.service: Failed with result 'exit-code'.
```
Strange that it just jumps to `exit-code`. Haven't been able to find other issues or forum posts with this specific set of logs 🤔

> Also show the output of:
`sudo nft list ruleset`

I realized now that I missed a prereq, installing the nftables (nft) package. I did just install that and here's the output of `sudo nft list ruleset`:

```
table inet filter {
	chain input {
		type filter hook input priority filter; policy accept;
	}

	chain forward {
		type filter hook forward priority filter; policy accept;
	}

	chain output {
		type filter hook output priority filter; policy accept;
	}
}
```

I did try and reinstall openNDS now that I have the nftables prereq, everything appeared to behave the same as before and it is still starting and stopping with no logs. 


> and
`sudo ip addr`

```
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host 
       valid_lft forever preferred_lft forever
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP group default qlen 1000
    link/ether e4:5f:01:6f:a5:83 brd ff:ff:ff:ff:ff:ff
    inet 192.168.8.123/24 brd 192.168.8.255 scope global dynamic noprefixroute eth0
       valid_lft 31170sec preferred_lft 23622sec
    inet6 fe80::9a7f:4185:25af:6c8e/64 scope link 
       valid_lft forever preferred_lft forever
3: wlan0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP group default qlen 1000
    link/ether e4:5f:01:6f:a5:84 brd ff:ff:ff:ff:ff:ff
    inet 10.10.10.10/24 brd 10.10.10.255 scope global noprefixroute wlan0
       valid_lft forever preferred_lft forever
    inet6 fe80::78fa:702f:1e3c:1fd2/64 scope link 
       valid_lft forever preferred_lft forever
4: ztosifnmh2: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 2800 qdisc pfifo_fast state UNKNOWN group default qlen 1000
    link/ether be:d6:b4:2c:03:06 brd ff:ff:ff:ff:ff:ff
    inet 192.168.191.112/24 brd 192.168.191.255 scope global ztosifnmh2
       valid_lft forever preferred_lft forever
    inet6 fe80::bcd6:b4ff:fe2c:306/64 scope link 
       valid_lft forever preferred_lft forever
```

> There is no setting for gatewayinterface. This defaults to br-lan, the common name for the lan bridge device, but in your case is probably different.

Oh yeah I realized that I omitted the fact that I had already also changed this in `/etc/config/opennds`

`	option gatewayinterface 'wlan0'
`

**Comment by bluewavenet** [comment]
@dtbayles 
You do not have any nftables rules at all - therefore routing is not configured either.
Pre-requisites:
https://opennds.readthedocs.io/en/stable/install.html#prerequisites

What is the operating system?
RaspiOS comes with the system logger package pre-installed but it looks like you do not have it as there are only systemd logs in the journal.....

**Comment by dtbayles** [comment]
@bluewavenet 
> What is the operating system?

OS is: Raspbian GNU/Linux 10 (buster)

> RaspiOS comes with the system logger package pre-installed

Right. I just verified that `rsyslog` is installed already

Oh yes, this comment at the bottom of the Linux prereqs seems to be happening:
"If an improper routing configuration is detected, openNDS will shut down."

I'll work on the nftables rules and see if I can get it working. If you have anything on-hand to help me set these rules quicker, that would be appreciated.

**Comment by bluewavenet** [comment]
@dtbayles 

> Right. I just verified that rsyslog is installed already

It is usually called `logger` and lives in `/usr/bin` on most Linux distros including RaspiOS last time I tested openNDS on it (an earlier version maybe...)
Also, nftables is the default on all distros too, at least all I have seen.

Was this preconfigured for RACHEL? Perhaps that is the difference.

Another question - if this is for a RACHEL system, normally running offline, what do you want openNDS for?

**Comment by dtbayles** [comment]
@bluewavenet 

I do see a file at `/usr/bin/logger`. I'm honestly sure why the `nftables` wasn't installed. I honestly might have accidentally deleted it when uninstalling `nodogsplash` (haven't been familiar with that package before lol). 

Yeah we used to use the World Possible RACHEL Plus hardware but then moved to RACHEL-Pi's. Our current image was (IIRC) originally a World Possible RACHEL Pi image and we've spun off and added our own interface and some other features (like ZeroTier VPN so we can remotely access our devices). 

The use-case: we have RACHELs currently throughout West Africa (mainly Ghana at the moment). Our end goal is to be able to make the Captive Portal solution work for optimal UX (especially for users who might not be so literate or tech savvy). Rather than telling them an IP/URL to type in or having them scan a QR code, we'd like the portal to just open and serve them our php interface. Of course if they want to download content then they have to go the browser. We also have a use-case at a local museum -- Captive Portal here would help make the tour more seamless. Our solution is also php for this. 

We are experimenting with putting SIM cards in our Raspberry Pi's (likely via USB Modem) so they are always online as far as the VPN and Captive Portal are concerned. We won't allow any users to authenticate and access the internet.

**Comment by bluewavenet** [comment]
@dtbayles 
This might help:
https://wiki.gentoo.org/wiki/Nftables/Examples
The "Basic NAT" example is probably what you want....

**Comment by bluewavenet** [comment]
@dtbayles 
Did you make progress?

**Comment by dtbayles** [comment]
@bluewavenet no progress regarding getting openNDS to run on the R-Pi. I tried the nftables rules with no luck and logs are still not coming in even tho it seems they should. 

Ended up converting our web app to React JS and it is showing up and working just fine with nodogsplash so we'll be going forward with that solution.

**Comment by bluewavenet** [comment]
@dtbayles 
Glad you got something working. Best of luck with the project!
