### ISSUE TITLE
Question:  USDZ files

### ISSUE THREAD

**Issue by cormacstrain** [openNDS/openNDS#567]
Hi folks

I have OpenNds installed on am AC1750 router.  It works wonderfully as is.  I have everything set that the user bypasses having to log into the system, so when they connect to wi-fi it goes straight to a website.  

This means everything is blocked by default and I use IPTables to allow access to sites.  Im not sure if thats the right way to do it - i basically just put the url and IP into the settings.  I also have fast secure set to 3. As I say, this works fine at present this way.

First question - If I want people to connect to the wi-fi and instead of being directed to the login page, get directed automatically to another website without using the splash page or registering the user - whats the best way of going about that?

My main question involves being redirected to Web Augmented Reality sites.  I have the router set up that if I switch off opennds and access an Web AR website through the router, it works fine.  When I turn on opennds, it goes to the site etc, but instead of displaying the Augmented Reality, it displays the USDZ file - which contains the augmented reality data - rather than processing it like it would normally. 

Im not sure why it doesnt read it as it normally would.  The site has access to everything it needs access to. Second question therefore is how do I use OpenNDS but still be able to view a website using Web AR?

To expand on this - Is there a way I can allow a website to act as it normally would (a bit like using the MAC address in the config file) while still using OpenNDS without having people login etc to authenticate.  I suppose what Im asking is there a way for people to get access using opennds without having to use the login splashpage etc.  I just want them to connect to the wi-fi and then have access to the web without the whole router being locked down.

As I say, I can do that at present but Im assuming something required to make the USDZ file work is blocked when OpenNDS is on, so Im assuming if I could use OpenNDS and let users be automatically authenticated then that might solve the issue.

I am testing using an iPhone as USDZ files seem to only work on iphones at present

many thanks

Cormac.

**Comment by cormacstrain** [comment]
in https://opennds.readthedocs.io/en/stable/config.html it mentions 'Allow Preemptive Authentication'.  I've tried setting that to 1 but it doesnt seem to have made a difference.

**Comment by bluewavenet** [comment]
@cormacstrain 
Did you mean to close this issue?

> This means everything is blocked by default 

Yes, that is correct.

> I use IPTables to allow access to sites

OpenNDS does not use iptables, neither does OpenWrt 23.5.x onwards.
You can install iptables but it will almost certainly clash with both the OpenWrt firewall and openNDS, most likely with random and unstable results. You might get away with it... but best not to even try because openNDS has built in config options to allow access to sites. See:
https://opennds.readthedocs.io/en/stable/walledgarden.html#walled-garden-and-block-lists

> When I turn on opennds, it goes to the site etc, but instead of displaying the Augmented Reality, it displays the USDZ file

This is built in to all client devices, eg iphones etc for security reasons. Anything but pure html5 is blocked by the device's operating system. Downloading files, executable code, scripts etc is prohibited.

>  I just want them to connect to the wi-fi and then have access to the web without the whole router being locked down.

Why do you want openNDS then?

**Comment by cormacstrain** [comment]
Sorry - ipset in the walled garden is what Im using - doh!

I think my issue is that the default browser wont let it download the required file.  

_Why do you want openNDS then?_

Im using OpenNDS as a way for people to connect directly just by connecting to the wi-fi connection itself.

**Comment by bluewavenet** [comment]
@cormacstrain 

> ipset

FYI openNDS has not used ipsets for the walled garden since version 9. It now uses nftsets, a functionality built into nftables.
