### ISSUE TITLE
Default ipset entries on OpenWRT 23.05.2 prevent saving in LuCI

### ISSUE THREAD

**Issue by JoeDat** [openNDS/openNDS#569]
Noticed an issue now that OpenNDS is using ipsets for Walled Garden and Blocklists.  In dhcp settings, default ipsets for the two features are created, missing an FQDN entry.  When trying to save unrelated changes in 'DNS and DHCP' in LuCI, LuCI returns 'option FQDN must not be empty.'   I can work around the issue by removing the entries from the dhcp config, but they eventually return.   I have no explicitly defined Walled Garden or Blocklist settings in my OpenNDS config.

OpenNDS 10.2.0
OpenWRT 23.05.2

![image](https://github.com/openNDS/openNDS/assets/8648894/4e55d340-6839-4db3-b463-6ccc97f81b09)

**Comment by bluewavenet** [comment]
@JoeDat 
openNDS does not use ipsets as it has been migrated entirely to nftables.
The walled garden settings must be made in the opennds config. See here:
https://opennds.readthedocs.io/en/stable/config.html#autonomous-walled-garden-configuration

_**The openNDS config cannot me managed by Luci.**_

The "ipsets" section in Luci is extremely confusing as it is not related to legacy ipsets at all, what it does is allow the creation of nftsets within the ruleset of the OpenWrt Firewall (fw4).
The fw4 nftables ruleset takes effect ONLY after the openNDS ruleset.

openNDS is a firewall in its own right and takes higher priority than anything that might be defined within fw4.

**Comment by JoeDat** [comment]
@bluewavenet 
Maybe a misunderstanding.  I'm actually not trying to manage walledgarden and blocklist settings in LuCI.  Quite the contrary.  I'm not using these features in openNDS at all.  The 'nds_filter' name suggests they're coming from openNDS.  I have no walledgarden or blocklist entries configured.  The impact is seen when making other changes in DNS and DHCP in LuCI, as I cannot save because the ipset configuration being written (seemingly by openNDS) is 'incomplete' when LuCI checks validity.  

Export of my used uci settings....hiding the values as they aren't relevant. 

```
opennds.cp=opennds
opennds.cp.enabled
opennds.cp.fwhook_enabled
opennds.cp.maxclients
opennds.cp.users_to_router
opennds.cp.login_option_enabled
opennds.cp.themespec_path
opennds.cp.log_mountpoint
opennds.cp.allow_preemptive_authentication
opennds.cp.gateway
opennds.cp.trustedmac
opennds.cp.faskey
opennds.cp.fw_mark_trusted
```

**Comment by bluewavenet** [comment]
@JoeDat 

> Export of my used uci settings....hiding the values as they aren't relevant.

They may not be relevant but this is meaningless.  Is it supposed to be the output of `uci export opennds` ?
If it is, it is an incorrect format.

> in LuCI, as I cannot save because the ipset configuration being written (seemingly by openNDS) is 'incomplete' when LuCI checks validity.

Neither OpenWrt 23.5.x, dnsmasq nor openNDS support the legacy iptables ipset.
Fw4 does a half baked emulation of iptables-ipset, so perhaps the problem lies there.

Please show the output of:
`uci export dhcp`

**Comment by JoeDat** [comment]
@bluewavenet 
> Is it supposed to be the output of uci export opennds ?

It was simply `uci show opennds`.  Here it is as `uci export opennds`.  Point I was trying to make was that there are no walled garden or blocklist settings.  Leaving a few more values this time, but again redacting others as I see them as irrelevant,

The dhcp export below shows the two ipset settings.  When I clear those two sections, they return when I restart openNDS.  

```
package opennds

config opennds 'cp'
	option enabled '1'
	option fwhook_enabled '1'
	option maxclients '250'
	list users_to_router  REDACTED
	option login_option_enabled '3'
	option themespec_path '/data/openwrt/mythemespec.sh'
	option log_mountpoint '/data'
	option allow_preemptive_authentication '1'
	option gatewayinterface 'br-lan.162'
	list trustedmac REDACTED
	option faskey REDACTED
	option fw_mark_trusted '40000'

```
`uci export dhcp`
```
package dhcp

config dnsmasq
	option domainneeded '1'
	option localise_queries '1'
	option rebind_protection '1'
	option rebind_localhost '1'
	option local '/lan/'
	option expandhosts '1'
	option authoritative '1'
	option readethers '1'
	option leasefile '/tmp/dhcp.leases'
	option localservice '1'
	option ednspacket_max '1232'
	list server '127.0.0.1#5053'
	list server '127.0.0.1#5054'
	list address '/status.client/172.20.162.1'

config dhcp 'lan'
	option interface 'lan'
	option start '100'
	option limit '102'
	option leasetime '12h'
	option dhcpv4 'server'
	option dhcpv6 'server'
	option ra 'server'
	list ra_flags 'managed-config'
	list ra_flags 'other-config'
	list dhcp_option_force '114,http://status.client'

config dhcp 'wan'
	option interface 'wan'
	option ignore '1'

config odhcpd 'odhcpd'
	option maindhcp '0'
	option leasefile '/tmp/hosts/odhcpd'
	option leasetrigger '/usr/sbin/odhcpd-update'
	option loglevel '4'

config dhcp 'IOT'
	option interface 'IOT'
	option start '100'
	option leasetime '12h'
	option limit '50'
	list dhcp_option '6,172.20.152.72,172.20.152.1'
	option ra 'server'
	option dhcpv6 'server'

config dhcp 'Guest'
	option interface 'Guest'
	option start '100'
	option leasetime '12h'
	option limit '20'
	list dhcp_option '6,172.20.152.72,172.20.162.1'

config dhcp 'pxe'
	option interface 'pxe'
	option start '100'
	option leasetime '12h'
	option limit '5'

config dhcp 'user'
	option interface 'user'
	option start '100'
	option leasetime '12h'
	option limit '10'
	list dhcp_option '6,172.20.152.72,172.20.152.1'
	option ra 'server'
	option dhcpv6 'server'

config ipset 'nds_walledgarden'
	list name 'walledgarden'
	option table 'nds_filter'
	option table_family 'ip'

config ipset 'nds_blocklist'
	list name 'blocklist'
	option table 'nds_filter'
	option table_family 'ip'
```

**Comment by JoeDat** [comment]
@bluewavenet 
I took a spare router I had lying around.  I installed OpenWRT 23.5.2 with all stock configuration and openNDS.  Did not see the problem occur. However, once I installed dnsmasq-full and restarted openNDS, the two ipset entries seen in the export above appeared.  Issue does not appear linked to my configuration.

**Comment by bluewavenet** [comment]
@JoeDat 
We need to find out what Luci thinks is wrong. From the point of view of dnsmasq, openNDS and fw4, there is nothing wrong as far as I can see. Everything but Luci works anyway.
What does it mean by `Option "FQDN" must not be empty`?

**Comment by JoeDat** [comment]
@bluewavenet 
In my first screenshot, the FQDN field next to each set name is empty.  It's complaining about that.  If I fill those fields in with something, it creates `list domain` entries in each section in `dhcp`

This could arguably be a bug in LuCI and perhaps that's where I should go? 

```
config ipset 'nds_walledgarden'
	list name 'walledgarden'
	option table 'nds_filter'
	option table_family 'ip'
	list domain 'blah.blah'

config ipset 'nds_blocklist'
	list name 'blocklist'
	option table 'nds_filter'
	option table_family 'ip'
	list domain 'blah.blah'
```

**Comment by bluewavenet** [comment]
@JoeDat 

> This could arguably be a bug in LuCI and perhaps that's where I should go?

Not so much a bug, more like very short sighted development by the dev that insisted on making luci/fw4 emulate the legacy iptables ipset. This is another example of the issues it created. Currently the mwan3 package is broken because of it, so are a number of other packages - anything that has internal iptables/ipset dependency.

In this case, openNDS is fully nftables compliant and, so it seems, breaks Luci ;-)
You will be totally wasting your time bringing this up as a bug with Luci as the dev is totally intransigent. Everyone else (including the wider Linux world) is wrong in his eyes. I spent far too long trying to convince him.

A workaround you could try is to add to the opennds config:
`list walledgarden_fqdn_list 'status.client'`

Restart opennds and see if it works.
If it does we can make this the default when dnsmasq-full is installed - in the next release.

Thanks for your efforts!

**Comment by bluewavenet** [comment]
@JoeDat 
I forgot the blocklist:
`list blocklist_fqdn_list 'blocked.client'

and edited the walled garden entry:
 list walledgarden_fqdn_list 'allowed.client'

**Comment by JoeDat** [comment]
@bluewavenet
No doubt it pains you to put silly workarounds in like this!  Nevertheless, confirm that it works.  Here's the resultant output.  Added each entry via uci add_list

`uci export opennds`
```
<...>
list blocklist_fqdn_list 'blocked.client'
list walledgarden_fqdn_list 'allowed.client'
```
`uci export dhcp`
```
<...>
config ipset 'nds_walledgarden'
	option table 'nds_filter'
	option table_family 'ip'
	list domain 'allowed.client'
	list name 'walledgarden'

config ipset 'nds_blocklist'
	option table 'nds_filter'
	option table_family 'ip'
	list domain 'blocked.client'
	list name 'blocklist'
```
![image](https://github.com/openNDS/openNDS/assets/8648894/de6269a4-c6e5-4c5d-9136-12cfcf28b8a4)


And LuCI is happy again.  Thanks for sticking with me on this one!

**Comment by bluewavenet** [comment]
@JoeDat 
Eventually another Dev will re-do this bit of Lucy (probably with Fw5) then all the fixes everyone had to do to make things work will be left in limbo for a software archaeologist to find one day :-D
 
Thanks again - see you with the next one ;-)
