### ISSUE TITLE
Openwrt device cannot ping client after Opennds started

### ISSUE THREAD

**Issue by Jeff-PM** [openNDS/openNDS#570]
Dear Sir,

We find that the Openwrt device cannot ping client and the client cannot ping the Openwrt device after Opennds started. Our situation is as below:
1. There are 2 devices for the case: Openwrt device (192.168.1.1) and a client device (192.168.1.2)
2. When the Opennds stopped, the Openwrt device (192.168.1.1) can ping the client device (192.168.1.2) and the client device (192.168.1.2) also can ping the  Openwrt device (192.168.1.1)
3. I config the client device (192.168.1.2) as trustedmac in the Opennds in the Openwrt device (192.168.1.1) and then start Opennds. The client device (192.168.1.2) can access internet.
4. But the Openwrt device (192.168.1.1) cannot ping the client device (192.168.1.2) and the client device (192.168.1.2) also cannot ping the  Openwrt device (192.168.1.1)

Would you please give me advice to let both device can ping another?

Thank you

**Comment by Jeff-PM** [comment]
The client device that run server application for the Openwrt device.

**Comment by bluewavenet** [comment]
@Jeff-PM 

> server application for the Openwrt device.

I take it you mean the local FAS server?
If so, the required access is handled by the openNDS config.

Please show the output of:
`uci show opennds`

**Comment by Jeff-PM** [comment]
Sorry, it is not FAS server.

```
root@OpenWrt:~# uci show opennds
opennds.@opennds[0]=opennds
opennds.@opennds[0].enabled='1'
opennds.@opennds[0].users_to_router='allow tcp port 53' 'allow udp port 53' 'allow udp port 67' 'allow tcp port 22' 'allow tcp port 60443'
opennds.@opennds[0].trustedmac='3c:6a:48:5d:ca:ee' '00:12:43:3f:28:2e' '00:12:43:3f:28:1c' 'C4:83:72:10:69:25'
opennds.@opennds[0].faskey='XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX'
```

**Comment by bluewavenet** [comment]
@Jeff-PM 

> it is not FAS server

Then it is not a "server application for the Openwrt device". Other lan based services are blocked for security reasons.

It would be better if you explained what it is you are trying to do....

**Comment by Jeff-PM** [comment]
It is only a server application install on client device that should be communication with the Openwrt device.

Would you please give me some advices? 

Thank you

**Comment by bluewavenet** [comment]
@Jeff-PM 

> Would you please give me some advices?

As you are unwilling to describe your use case, I can only assume you are attempting to use a captive portal for some man-in-the-middle attack device. OpenNDS is designed to prevent such attempts. So my advice to you is not to attempt to breach security.
