### ISSUE TITLE
fasremotefqdn and fasremoteip config 

### ISSUE THREAD

**Issue by pierrejoye** [openNDS/openNDS#574]
os: openwrt 23.05
opennds: opennds - 10.2.0-1 (opkg)

I am not sure why but here is the config and what is set once opennds starts.

I suppose it is due to the IP of the fasremotefqdn but it matches what I get using nslookup on the openwrt. security level gets downgraded to lvl1 and the gateway IP is used (status domain and port).

```
opennds.@opennds[0]=opennds
opennds.@opennds[0].debuglevel='3'
opennds.@opennds[0].allow_preemptive_authentication='0'
opennds.@opennds[0].gatewayinterface='br-guest'
opennds.@opennds[0].fasremoteip='138.201.126.72'
opennds.@opennds[0].fasremotefqdn='aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa.loophole.site'
opennds.@opennds[0].fas_secure_enabled='3'
opennds.@opennds[0].faspath='/fas/fas-aes-https.php'
opennds.@opennds[0].faskey='1234567890123456789012345678901234567890123456789012345678901234'
root@OpenWrt:~# ndsctl status
==================
openNDS Status
====
Version: 10.2.0
Uptime: 10m 20s
Gateway Name: [ openNDS Node:e6fac460dedc  ]
Debug Level: [ 3 ]
Gateway FQDN: [ status.client ]
Managed interface: br-guest
Upstream gateway(s) [ online:192.168.1.1,wan  ]
MHD Server [ version 0.9.75 ] listening on: http://192.168.3.1:2050
Maximum Html Page size is [ 10240 ] Bytes
Preemptive Authentication is Disabled
Binauth Script: /usr/lib/opennds/binauth_log.sh
ThemeSpec Core Library: /usr/lib/opennds/libopennds.sh
FAS: Secure Level 1, URL: http://status.client:2050/opennds_preauth/
Client Check Interval: 15s
Rate Check Window: 2 check intervals (30s)
Preauthenticated Client Idle Timeout: 30m
Authenticated Client Idle Timeout: 120m
Download rate limit threshold (default per client): no limit
Upload rate limit threshold (default per client): no limit
Download quota (default per client): no limit
Upload quota (default per client): no limit
Total download: 0 kByte; average: 0.00 kbit/s
Total upload: 28 kByte; average: 0.38 kbit/s
====
```

nslookup:

```
root@OpenWrt:~# nslookup aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa.loophole.site
Server:         127.0.0.1
Address:        127.0.0.1:53

Non-authoritative answer:
Name:   5c0a6d7f3cb59d522b8922cf92d4c0dc.loophole.site
Address: 138.201.126.72

Non-authoritative answer:

```

Any idea?

What I am trying to do is to get the FAS on my laptop during test/dev time. I tried setting only the IP using my lan IP and secure level 1 (to start with) but it cannot be reached from the client device (a mobile phone in my case) connected to the guest wifi. I am not sure if setting only the IP is supported so I tried using that service to provide a public available domain name (which forces me to use https too).

I also tried using an actual fqdn on my server, the same happens.

sidenote (I will do some PR to the doc too once I am done), by using level 3 security, it seems the key is automatically re generated and added to the config if the provided key is too short, which added a bit of debugging until I realized it was added at the very end of the config file :)

**Comment by pierrejoye** [comment]
Ok, without changing anything, it seems to work now. It suddenly shows an error about missing php. And it finally works.

![image](https://github.com/openNDS/openNDS/assets/282408/e93f080e-e9b4-4f4b-b568-de3ca94d644a)

sidenote: If you don't mind, I will clean a bit the php too to make it easier to use or customize/understand, and add some safety checks so that errors won't show up (it seems php default setting use display_errors on)

**Comment by bluewavenet** [comment]
@pierrejoye 

> What I am trying to do is to get the FAS on my laptop during test/dev time. I tried setting only the IP using my lan IP 

This is specifically blocked by openNDS for security reasons, otherwise it would be possible for the ip address to be hijacked and a spoof fas introduced.
It is possible that the documentation implies you can do this, so any doc fixes would be welcome. 

>  is fas_ssl supported? 

I am not sure what you mean by this.
If you want an Internet hosted https fas, then this is automatically configured by `fas_secure_enabled='3'` and is mandatory for that level.

> security level gets downgraded to lvl1 and the gateway IP is used (status domain and port).

See:
https://opennds.readthedocs.io/en/stable/config.html#mode-0

By default, openNDS will use its built in web server to deliver the themespec login sequence.

`opennds.@opennds[0].allow_preemptive_authentication='0'`

Why have you set this to zero?  This setting will disable significant functionality and is intended only for advanced use.

```
opennds.@opennds[0].fasremoteip='138.201.126.72'
opennds.@opennds[0].fasremotefqdn='aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa.loophole.site'


```

You can have both of these, but from v10 onwards it is advisable to use fqdn only as access will fail a proportion of the time if the fas server is hosted on CDS, as the ipaddress may change at any time.

**Comment by pierrejoye** [comment]
> @pierrejoye
>

Thanks for your reply!

> > What I am trying to do is to get the FAS on my laptop during test/dev time. I tried setting only the IP using my lan IP
> 
> This is specifically blocked by openNDS for security reasons, otherwise it would be possible for the ip address to be hijacked and a spoof fas introduced. It is possible that the documentation implies you can do this, so any doc fixes would be welcome.

Ah that explains it. Would it be possible to consider to allow it for dev purposes? With a big warning if that option is enabled?

It would make local dev much smoother (outside the router that is).

> > is fas_ssl supported?
> 
> I am not sure what you mean by this.

I saw it while debugging the above and did not see it in the doc as an option. As wget is most likely always available, it could be use instead of post-request.php, as long as the data is in the form of k=v&l=m (which is what php's http_build_query does).

>  If you want an Internet hosted https fas, then this is automatically configured by `fas_secure_enabled='3'` and is mandatory for that level.
> 
> > security level gets downgraded to lvl1 and the gateway IP is used (status domain and port).
> 
> See: https://opennds.readthedocs.io/en/stable/config.html#mode-0
> 
> By default, openNDS will use its built in web server to deliver the themespec login sequence.
> 
> `opennds.@opennds[0].allow_preemptive_authentication='0'`
> 
> Why have you set this to zero? This setting will disable significant functionality and is intended only for advanced use.

It was  an attempt to figure out why it did not work :)
 
> ```
> opennds.@opennds[0].fasremoteip='138.201.126.72'
> opennds.@opennds[0].fasremotefqdn='aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa.loophole.site'
> ```
> 
> You can have both of these, but from v10 onwards it is advisable to use fqdn only as access will fail a proportion of the time if the fas server is hosted on CDS, as the ipaddress may change at any time.

Very good :)

**Comment by bluewavenet** [comment]
@pierrejoye 

> As wget is most likely always available, it could be use instead of post-request.php,

This is already the way that fas-hid-https.php works.
https://opennds.readthedocs.io/en/stable/fas.html#fas-hid-https-php

The advantage of fas-hid is that it does not need php to be available on the router, so is good for devices with resource limitations.
The disadvantage is that fas-hid is not as secure as it does not have the same level of encryption.

> Would it be possible to consider to allow it for dev purposes?

No.
It was restricted very specifically to prevent the described man-in-the-middle attacks.
You can however run a php web server on the router.
I do this all the time, not just for development but also for stand alone production systems.

You can use the standard uhttpd web server for this with no issues, particularly for development, or even small venues.

I most often use the lighttpd package as web server, a tight fit ram wise in a 16rom/64ram device if you have lots of users, but no problem at all for a 16/128.

https://openwrt.org/docs/guide-user/services/webserver/lighttpd

**Comment by pierrejoye** [comment]
On Sun, Mar 3, 2024, 8:10 PM Rob White ***@***.***> wrote:

> @pierrejoye <https://github.com/pierrejoye>
>
> As wget is most likely always available, it could be use instead of
> post-request.php,
>
> This is already the way that fas-hid-https.php works.
> https://opennds.readthedocs.io/en/stable/fas.html#fas-hid-https-php
>
> The advantage of fas-hid is that it does not need php to be available on
> the router, so is good for devices with resource limitations.
> The disadvantage is that fas-hid is not as secure as it does not have the
> same level of encryption.
>
thanks,  it is what I use now for dev then switch mode for testing with
fas-aes. I realized the php dep later on.

Would it be possible to consider to allow it for dev purposes?
>
> No.
> It was restricted very specifically to prevent the described
> man-in-the-middle attacks.
>
it makes totally sense, no biggie  :)

> You can however run a php web server on the router.
> I do this all the time, not just for development but also for stand alone
> production systems.
>
> You can use the standard uhttpd web server for this with no issues,
> particularly for development, or even small venues.
>
> I most often use the lighttpd package as web server, a tight fit ram wise
> in a 16rom/64ram device if you have lots of users, but no problem at all
> for a 16/128.
>
> https://openwrt.org/docs/guide-user/services/webserver/lighttpd
>
I used it a lot too with php as well, since its early days, I kept meaning
the author at variousevents,  he convinced me very early :)

I will close the issue. Thanks again!
