### ISSUE TITLE
There is a memory leak defect at line 838 of the file /openNDS/src/http_microhttpd.c

### ISSUE THREAD

**Issue by LuMingYinDetect** [openNDS/openNDS#575]
Hello! I apologize for bothering you again after a few weeks. Recently, I've used my static analysis tool to discover several suspected memory leak defects in openNDS. Below is the link to the specific descriptions of these defects:https://github.com/LuMingYinDetect/openNDS_defects/blob/main/openNDS_detect_2.md

**Comment by bluewavenet** [comment]
@LuMingYinDetect 

>  I apologize for bothering you again after a few weeks

Excellent work, no need to apologise - thank you for your efforts!
I will look into these as soon as possible.

**Comment by LuMingYinDetect** [comment]
Thank you for your prompt reply. I'm glad to be able to contribute to the open-source project! Since static analysis may have false positive issues, I would appreciate your help in confirming.

**Comment by bluewavenet** [comment]
@LuMingYinDetect 
Fixed in PR #581
