### ISSUE TITLE
Question for nftables priority

### ISSUE THREAD

**Issue by brett90063** [openNDS/openNDS#579]
Hi @bluewavenet 
Im curious about nftables priority
in libopennds.sh:1301
```
	nft add chain ip nds_nat ndsPRE "{ type nat hook prerouting priority -100 ; }"
	nft add chain ip nds_mangle ndsPRE "{ type filter hook prerouting priority -100 ; }"
```
it using same hook and same priority
I know that
the chain of `nds_mangle ndsPRE` is for auth rule/trust rule etc.
the chain of `nds_nat ndsPRE` is for redirect to :2050 into MHD.
so nds_mangle should do first.
but according to
https://wiki.nftables.org/wiki-nftables/index.php/Configuring_chains
says that
`It's possible to give two base chains the same priority, but there is no guaranteed evaluation order of base chains with identical priority that are attached to the same hook location.`
Why it can ensure nds_mangle will run first?

---

Im testing with rule
```
nft add rule ip nds_mangle ndsPRE ip saddr 192.168.1.14 ip daddr 3.3.3.3 counter log prefix \"[from nds_mangle]\" level debug
nft add rule ip nds_nat ndsPRE ip saddr 192.168.1.14 ip daddr 3.3.3.3 counter log prefix \"[from nds_nat]\" level debug
```
and the `dmesg` shows `nds_mangle` always do first
```
[ 9153.996998] [from nds_mangle]IN=br-lan OUT= MAC=xxx SRC=192.168.1.14 DST=3.3.3.3 ... MARK=0x3
[ 9153.997031] [from nds_nat]IN=br-lan OUT= MAC=xxx SRC=192.168.1.14 DST=3.3.3.3 ... MARK=0x30003
[ 9153.996998] [from nds_mangle]IN=br-lan OUT= MAC=xxx SRC=192.168.1.14 DST=3.3.3.3 ... MARK=0x3
[ 9153.997031] [from nds_nat]IN=br-lan OUT= MAC=xxx SRC=192.168.1.14 DST=3.3.3.3 ... MARK=0x30003
```

**Comment by bluewavenet** [comment]
The chains are in different tables so are not "attached to the same hook location".
The priority is set to be "higher" than any system firewall (fw4 in OpenWrt for example) which would normally have a priority of 0.

**Comment by brett90063** [comment]
[Netfilter](https://wiki.nftables.org/wiki-nftables/index.php/Netfilter_hooks), tables don't seem to affect the packet's flow; it only sees the chain's hook and priority.
What confuses me is that `ip nds_mangle ndsPRE` and `ip nds_nat ndsPRE` two chains are using the same hook and priority. The packet's flow should be random on these two chains.

[Note] It's not an openNDS issue, because it always works fine, this question just for learning purpose.
when I create two chains into same table like
```
nft add chain ip FORWARD test_nat '{type nat hook prerouting priority -100;}'
nft add chain ip FORWARD test_mangle '{type filter hook prerouting priority -100;}'
nft add rule ip FORWARD test_nat ip saddr 192.168.1.14 ip daddr 3.3.3.3 log prefix \"test_nat\" level debug counter
nft add rule ip FORWARD test_mangle ip saddr 192.168.1.14 ip daddr 3.3.3.3 log prefix \"test_mangle\" level debug counter
```
even use `nft monitor trace` shows ip FORWARD test_mangle always do first
```
trace id 7b1f7af9 ip FORWARD test_mangle packet: iif "br-lan" ip saddr 192.168.1.14 ip daddr 3.3.3.3 ip dscp cs0 ip ecn not-ect ip ttl 64 ip id 21407  
trace id 7b1f7af9 ip FORWARD test_mangle rule ip saddr 192.168.1.14 ip daddr 3.3.3.3 log prefix "test_mangle" level debug counter packets 0 bytes 0 (verdict continue)
trace id 7b1f7af9 ip FORWARD test_mangle verdict continue meta mark 0x00000003 
trace id 7b1f7af9 ip FORWARD test_mangle policy accept meta mark 0x00000003 
trace id 7b1f7af9 ip FORWARD test_nat packet: iif "br-lan"  ip saddr 192.168.1.14 ip daddr 3.3.3.3 ip dscp cs0 ip ecn not-ect ip ttl 64 ip id 21407 ip  
trace id 7b1f7af9 ip FORWARD test_nat rule ip saddr 192.168.1.14 ip daddr 3.3.3.3 log prefix "test_nat" level debug counter packets 7 bytes 420 (verdict continue)
trace id 7b1f7af9 ip FORWARD test_nat verdict continue meta mark 0x00000003 
trace id 7b1f7af9 ip FORWARD test_nat policy accept meta mark 0x00000003
```
seems like I need to survey netfilter hook code, thank you @bluewavenet

**Comment by bluewavenet** [comment]
@brett90063 
Your 2 chains are different types.  Network Address Translation (nat) is always the last thing to happen.

Put simply, there is ordering within types and priority within hooks.

There is a good description of hooks here:
https://wiki.nftables.org/wiki-nftables/index.php/Netfilter_hooks
