### ISSUE TITLE
Port 80 question

### ISSUE THREAD

**Issue by cormacstrain** [openNDS/openNDS#580]
Hi Rob

I once again require your help.  The manual says:
"As soon as this initial port 80 request is received on the default gateway interface, NDS will “Capture” "

I have a page set up using port 8080 which I am running on LightTPS, that I had wanted for admin purposes to be available regardless if OpenNDS is on or off.  I had assumed that being a different port that OpenNDS won't affect it, but when I have OpenNDS on, I cant access the page at port 8080.  When its off I can access it without any issue.  Luci is running under port 80 in Uhttpd and works fine.  I experimented with it as well by changing its web port number and also couldnt access Luci when OpenNDS was running regardless which port I had Luci running under.

Is there a way I can have a page that is accessible regardless of OpenNDS being on or off?

I appreciate your time 

many thanks

Cormac

**Comment by bluewavenet** [comment]
@cormacstrain 

>  Luci is running under port 80 in Uhttpd and works fine.

By default, Luci is only available on https port 443. Port 80 is used by openNDS very specifically for CPI support (Captive Portal Information RFC8910).
If Luci is working on port 80, then you have an unusual config, or something wrong with your config.

> I cant access the page at port 8080

Is lighttpd running on the openNDS router?

Please show the output of:
`uci show opennds`

**Comment by cormacstrain** [comment]
my apologies - i am incorrect about Luci on port 80 - it basically works as it should so I  should have said that instead.

I no longer have it running at present, but at the time, yes, lighttpd was running on the same router, just pointing at a different port.

root@CNX:~# uci show opennds
opennds.@opennds[0]=opennds
opennds.@opennds[0].enabled='1'
opennds.@opennds[0].fwhook_enabled='1'
opennds.@opennds[0].login_option_enabled='0'
opennds.@opennds[0].use_outdated_mhd='1'
opennds.@opennds[0].unescape_callback_enabled='0'
opennds.@opennds[0].gatewayinterface='br-lan'
opennds.@opennds[0].gatewayname='CNX'
opennds.@opennds[0].maxclients='250'
opennds.@opennds[0].preauthidletimeout='30'
opennds.@opennds[0].authidletimeout='120'
opennds.@opennds[0].sessiontimeout='1200'
opennds.@opennds[0].checkinterval='60'
opennds.@opennds[0].uploadrate='0'
opennds.@opennds[0].downloadrate='0'
opennds.@opennds[0].ratecheckwindow='2'
opennds.@opennds[0].uploadquota='0'
opennds.@opennds[0].downloadquota='0'
opennds.@opennds[0].fasport='443'
opennds.@opennds[0].fasremotefqdn='[xxxxxxx.ie](http://xxxxxxx.ie/)'
opennds.@opennds[0].fasremoteip='xxx.xxx.xxx.xxx'
opennds.@opennds[0].faspath='/'
opennds.@opennds[0].faskey='1234567890'
opennds.@opennds[0].fas_secure_enabled='3'
opennds.@opennds[0].authenticated_users='allow all'
opennds.@opennds[0].preauthenticated_users='allow tcp port 80 ipset openndsset' 'allow tcp port 443 ipset openndsset'
opennds.@opennds[0].users_to_router='allow tcp port 53' 'allow udp port 53' 'allow udp port 67' 'allow tcp port 22' 'allow tcp port 23' 'allow tcp port 80' 'allow tcp port 443'

**Comment by cormacstrain** [comment]
just doubled checked - I get a 'refused to connect' when I try to use port 443 with luci - so thats good.

**Comment by bluewavenet** [comment]
@cormacstrain 
When adding preformatted text (eg a command output or some code etc) use the <> button on the bat at the top of the text box to retain the formatting.....

**Comment by bluewavenet** [comment]
@cormacstrain 
What is the version of openNDS?

Show the output of:
`ndsctl status`

There are some outdated entries as well as some incorrect ones in your config....

**Comment by cormacstrain** [comment]
version 5.2 - Im still using openwrt 19 something on this router.  

openNDS Status
====
Version: 5.2.0
Uptime: 2s
Gateway Name: CNX
Managed interface: br-lan
Managed IP range: 0.0.0.0/0
Server listening: http://192.168.1.1:2050/
Binauth: Disabled
Preauth: Disabled
FAS: Secure Level 3, URL: https:/[mywebsiteinfohere.ie:443/directoryinfohere/](http://mywebsiteinfohere.ie:443/directoryinfohere/)
Client Check Interval: 60s
Preauth Idle Timeout: 30m
Auth Idle Timeout: 120m
Traffic control: no
Total download: 0 kByte; avg: 1.06 kbit/s
Total upload: 0 kByte; avg: 1.34 kbit/s
====
Client authentications since start: 0
Current clients: 0
====
Blocked MAC addresses: none
Allowed MAC addresses: N/A
Trusted MAC addresses: none
========

**Comment by bluewavenet** [comment]
@cormacstrain 
Oy! Use the <> button to format correctly...

I'll fix it again...

**Comment by cormacstrain** [comment]
thats what I was trying to do - sorry!

**Comment by bluewavenet** [comment]
You can do it old school by enclosing blocks of text with pairs of 3 backtics.

**Comment by bluewavenet** [comment]
OpenWrt 19 and openNDS 5.2 are both very outdated, unsupported, and have numerous security vulnerabilities.

The current version of openNDS is v10.2.0. You are 5 major versions out of date.

**Comment by cormacstrain** [comment]
to be fair this is really only for me to experiment with - its never publicly used.  I have an idea but it would mean being able to access a router page whilst openNDS is still running, which is why I was trying a different port

**Comment by bluewavenet** [comment]
Much has changed since v5, but you could try adding `allow tcp port 8080` to `preauthenticated_users`.

**Comment by cormacstrain** [comment]
cheers rob - will do!

**Comment by bluewavenet** [comment]
Make that `users_to_router`...

**Comment by cormacstrain** [comment]
thanks Rob - thats fixed it!

**Comment by cormacstrain** [comment]
thanks Rob - I'll definitely upgrade
