### ISSUE TITLE
Modify voucher theme

### ISSUE THREAD

**Issue by ganganrobert** [openNDS/openNDS#583]
Hi! I found interesting theme https://github.com/openNDS/openNDS/tree/master/community/themespec/theme_voucher 
I want to modify - add picture, some information on start page and so on... How can I do this?

**Comment by bluewavenet** [comment]
@ganganrobert 
Theme_voucher is not officially supported as it is a community effort.
You could ask the community developer to help....
see:
https://github.com/openNDS/openNDS/pull/300

However, adding custom images is supported by way of a config option.
See:
https://opennds.readthedocs.io/en/stable/customparams.html#custom-images

**Comment by ganganrobert** [comment]
@bluewavenet 
Thanks. I'll try.
