### ISSUE TITLE
Adding credentials for verification extra verification 

### ISSUE THREAD

**Issue by Alialsufayan** [openNDS/openNDS#584]
Hi,

First, thank you for your efforts in maintaining this project; it's been invaluable to me. I'm trying to add new credential fields, like last name and room number, in the captive portal. However, I've encountered challenges while modifying the theme_voucher.sh script. Could you provide some guidance or suggest a way to achieve this? Any help would be greatly appreciated.

Thanks again,

**Comment by bluewavenet** [comment]
@Alialsufayan 
Theme_voucher is not officially supported as it is a community effort.
You could ask the community developer to help....
see:
https://github.com/openNDS/openNDS/pull/300

However openNDS does support the addition of custom fields by way of simple configuration options.
See:
https://opennds.readthedocs.io/en/stable/customparams.html#custom-dynamically-generated-form-fields
