### ISSUE TITLE
Wireless device does not display authentication interface

### ISSUE THREAD

**Issue by 3157696** [openNDS/openNDS#586]
HELLO

Teams and all
My route os is openwrt-23.05.3
opennds is 10.2.0

When connected to a wireless network, the wireless device can jump to the URL of the authentication page, but cannot display the authentication content normally.

Cannot telnet port 2050/22/80/443 when connected use wireless。

**This problem will appear when I set the wifi properties to guest
Normal when set to employee**

There is no problem using pfsense cp

network
openwrt / pfsense ->br-lan -----ap   )))))    wireless device

**Comment by bluewavenet** [comment]
@3157696 
I'm sorry but it seems a lot of information is lost in translation.
Please post in English AND your native language - I will try translation at this end and see if it helps.

**Comment by 3157696** [comment]
> @3157696 I'm sorry but it seems a lot of information is lost in translation. Please post in English AND your native language - I will try translation at this end and see if it helps.

HaHaHa
sorry 
But this has been translated to English  using google
It seems that the problem has been solved, it is my AP problem
in addition,
1: How to set a Voucher Roll to only be used on one device?
2: How to modify the content of "Read Terms of Service"
3:Is it possible to add a description column to Voucher Roll?
for example
voucher code, 0, 0, 0, 0, 0, 0, who used this code (commented by the administrator)
4：How to invalidate a code
Thanks for your reply!!

**Comment by bluewavenet** [comment]
@3157696 

> the problem has been solved

Good! Other questions should really be asked by opening a new issue.

> Voucher Roll 

The voucher themespec was provided by a community user as an example of what can be done.
However it is not officially supported.

If you want to make modifications then you should read the themespec script and figure out what to do.

Feel free though to ask general questions can be asked about themespec in a new issue.
