### ISSUE TITLE
Parse error: syntax error, unexpected '$custom' 

### ISSUE THREAD

**Issue by boluojiang521** [openNDS/openNDS#59]
Parse error: syntax error, unexpected '$custom' (T_VARIABLE), expecting ',' or ')' in /www/wwwroot/testfas2.35.keeleo.com/nds/fas-hid.php on line 153,
what kind of problem is it？    i use the  "fas-hid.php" at my host"testfas2.35.keeleo.com" with php7.2

**Comment by sicelo** [comment]
On Fri, Oct 02, 2020 at 05:11:43AM -0700, boluojiang521 wrote:
> Parse error: syntax error, unexpected '$custom' (T_VARIABLE), expecting ',' or ')' in /www/wwwroot/tests.35.keeleo.com/nds/fas-hid.php on line 153,
> what kind of problem is it？    i use the  "fas-hid.php" at my host"tests.35.keeleo.com"

Looks like a typo in the file. Sorry.

Add a `,` after `$redir`

**Comment by boluojiang521** [comment]
thanks my great OPENDNS!

**Comment by boluojiang521** [comment]
it worked，thanks again!

**Comment by bluewavenet** [comment]
Ooops ;-)

**Comment by bluewavenet** [comment]
@sicelo 
Thanks and well spotted. This will be fixed in the upcoming 6.1.0 release.
