### ISSUE TITLE
nft add rule: Could not resolve hostname (v10.2.1beta)

### ISSUE THREAD

**Issue by billz** [openNDS/openNDS#591]
Testing v10.2.1beta branch. Compiled and installed per generic Linux docs on Debian 12.

```
$ uname -a
Linux rpi3 6.6.28+rpt-rpi-v8 #1 SMP PREEMPT Debian 1:6.6.28-1+rpt1 (2024-04-22) aarch64 GNU/Linux
```

I've used `grep -v '^\s*#' /etc/config/opennds | grep -v '^\s*$'` to summarize my config:
```
config opennds
	option debuglevel '3'
	option gatewayinterface 'wlan0'
	option fasport '2080'
	option faspath '/fas/fas-aes.php'
	option fas_secure_enabled '2'
```
Debug service output:

```
opennds[473578]: option gatewayfqdn is [ status.client ]
opennds[473578]: Executing command: /usr/lib/opennds/libopennds.sh write ndsinfo '/run' 'gatewayfqdn="status.client"'
opennds[473578]: Executing command: /usr/lib/opennds/libopennds.sh write ndsinfo '/run' 'version=10.2.1beta'
--snip--
opennds[473578]: nftables command [ add rule ip nds_filter ndsNET ip daddr disabled tcp dport 2080 counter accept ], iteration [ 3 ]return code [ 1 ]
opennds[473578]: Executing command: nft add rule ip nds_filter ndsNET ip daddr disabled tcp dport 2080 counter accept
opennds[476075]: Error: Could not resolve hostname: Name or service not known
opennds[476075]: add rule ip nds_filter ndsNET ip daddr disabled tcp dport 2080 counter accept
opennds[476075]:                                        ^^^^^^^^
--snip--
opennds[473578]: Error initializing firewall rules! Cleaning up
opennds[473578]: Destroying our nftables entries
opennds[473578]: Exiting because of error initializing firewall rules
```

Per this [comment](https://github.com/openNDS/openNDS/pull/589#issuecomment-2094919519) I confirmed that the default gatewayfqdn value is set (see above).

Not exhibited on latest release version.
Glad to provide any other details.

**Comment by bluewavenet** [comment]
@billz 
It should work if you add to the config:
`	option fasremotefqdn 'status.client'`

Let me know if it does!

This is an issue with the documentation as it stands, but it could be made automatic for a router based fas, so I will flag as a bug.

I'll do the fix later today if time allows.

**Comment by billz** [comment]
Confirmed that explicitly adding the above resolves it. Thanks

**Comment by bluewavenet** [comment]
@billz 
Should be fixed with commit https://github.com/openNDS/openNDS/commit/55bacca796a3c8c9bcbd37fbad977b61e6875c8d

**Comment by billz** [comment]
@bluewavenet confirmed fixed with same config (as above), thanks.
