### ISSUE TITLE
OpenNDS Captive portal slowness?

### ISSUE THREAD

**Issue by luke-meshii** [openNDS/openNDS#594]
OpenNDS is setup on our OpenWRT router and is attached to an interface only accessible by a 'guest' WLAN.

From here, users are greeted with our captive portal through FAS at level 3; they authenticate using Auth0 and are then given access; all traffic from this interface then tunnels via a Wireguard VPN server.

Our issue is that the captive portal Is slow to both load the login screen, and then authenticate before allowing access.

The whole process, from connecting to the captive portal network and authenticating, can take upwards of 1 minute.

Is there anything we can check i.e. logs to see why and where things are getting held up?  devices are being given a DHCP 2-3 seconds after joining Wi-Fi, so it cannot be this; we have tested this across 3 different hardware also, with 1 of them being a BPIR4, so we know this hold-up is not hardware related as such either.

Any input would be appreciated, thanks!

**Comment by bluewavenet** [comment]
@luke-meshii 
You have not shared any details about versions or configs so there is very little we can do.

Auth0 is a third party, closed source system, so it might be worth eliminating it and testing openNDS without it by doing:

```
service opennds stop
opennds.@opennds[0].login_option_enabled='1'
uci commit opennds
service opennds start

```

This should give you the default "Click to Continue" splash page. How long does it take to come up?
