### ISSUE TITLE
Question: OpenNDS with FAS and react

### ISSUE THREAD

**Issue by AdityaC4** [openNDS/openNDS#595]
I am new to capture portals and webdev. I am trying to figure out if I have a webapp built with react, hosted on a cloud server that does authentication using web3auth, will OpenNDS be able to support that webapp as the splash page/capture portal for the authentication using FAS? The documentation gives examples of php, so I was wondering if it would work with my setup?
Any help is appreciated, thank you!!

**Comment by bluewavenet** [comment]
@AdityaC4 
Any captive portal is governed by the client based CPD component of the mobile device.

openNDS neither knows nor cares about webdav, react, web3auth or any other remote service.

As long as the generated splash page sequence complies with the rules of CPD, it should work.
See:
https://opennds.readthedocs.io/en/stable/customize.html#rules-for-customised-splash-pages

Before you do ANY development, I would suggest you install one of the supplied php scripts on your cloud server, 
`fas-aes-https.php`
would be the best one, and get it working.

Then study the inner workings to make sure you understand how it all works before moving on to anything like react.
