### ISSUE TITLE
Need installation guide for implementing openNDS captive portal solution with OpenWrt router

### ISSUE THREAD

**Issue by SohailAsghar236** [openNDS/openNDS#597]
Hi. I have installed the openNDS service on my OpenWRT router and I have created a splash.html page on a virtual Ubuntu server machine to act as a FAS server. Now I have added the IP of this VM in config file for openNDS and tried to connect to internet on this router but I get internet without any blockage. I need a kind of guide on how to set it up. Can you please help me with @bluewavenet ?

**Comment by bluewavenet** [comment]
@SohailAsghar236 
I suggest you read the documentation here:
https://opennds.readthedocs.io

> I have created a splash.html page on a virtual Ubuntu server machine to act as a FAS server. Now I have added the IP of this VM in config file for openNDS 

Note that for security reasons, running a FAS on the lan is now blocked for security reasons. Unfortunately this is not yet reflected in the documentation.
Your VM FAS will have to be on a separate ip subnet or, ideally, on an Internet hosted web sever.

**Comment by SohailAsghar236** [comment]
I have thoroughly checked the documentation for installing OpenNDS. I have installed it the package on an OpenWRT router but whenever I connect to wireless LAN of this router I get internet without being blocked. When I run the command **ndsctl status** I get this:

`openNDS Status
====
Version: 10.2.0
Uptime: 49s
Gateway Name: [ openNDS Node:3460f9b1fc9f  ]
Debug Level: [ 3 ]
Gateway FQDN: [ status.client ]
Managed interface: br-lan
All Upstream gateway(s) are offline or not connected [  ]
MHD Server [ version 0.9.75 ] listening on: http://192.168.74.50:2050
Maximum Html Page size is [ 10240 ] Bytes
Preemptive Authentication is Enabled
Binauth Script: /usr/lib/opennds/binauth_log.sh
ThemeSpec Core Library: /usr/lib/opennds/libopennds.sh
FAS: Secure Level 1, URL: http://status.client:2050/opennds_preauth/
Client Check Interval: 15s
Rate Check Window: 2 check intervals (30s)
Preauthenticated Client Idle Timeout: 30m
Authenticated Client Idle Timeout: 120m
Download rate limit threshold (default per client): no limit
Upload rate limit threshold (default per client): no limit
Download quota (default per client): no limit
Upload quota (default per client): no limit
Total download: 0 kByte; average: 0.00 kbit/s
Total upload: 23 kByte; average: 4.00 kbit/s
====
Client authentications since start: 0
Current clients: 0
====
Trusted MAC addresses:
none
====
Walledgarden FQDNs:
none

Walledgarden Ports:
all
====
Blocklist FQDNs:
none

Blocklist Ports:
all
========`

All I have done so far is installed the package opennds using opkg command in OpenWRT and I have a br-lan interface. Do I need to add a firewall setting in config?

Please let me know.

**Comment by bluewavenet** [comment]
@SohailAsghar236 

Please enclose any pre-formatted text, for example the output of `ndsctl status`, within pairs of tree backtics. You can check formatting of posts by clicking the Preview tab.
I have edited your last post accordingly.

> I have thoroughly checked the documentation

I am pretty sure you have not....

Read this section:
https://opennds.readthedocs.io/en/stable/install.html#prerequisites

Some clues to help you find out what is going on:
```
All Upstream gateway(s) are offline or not connected [  ]
MHD Server [ version 0.9.75 ] listening on: http://192.168.74.50:2050
```

An important question to ask yourself is "what is the ipv4 gateway address?".

**Comment by SohailAsghar236** [comment]
Thank you @bluewavenet. I will check this link you provided and try the solution. I want to ask one more thing, whenever the opennds status is **running**, I get this error when trying to load router admin page:

Error 403 - Forbidden - Access Denied to this Client!

**Comment by bluewavenet** [comment]
@SohailAsghar236 
From the documentation link I provided, you will see that the openNDS router must:

> Provide DHCP services to connected clients

If the client device (in this case you - ".. when trying to load router admin page") cannot be found by openNDS in the ipv4 dhcp database then all access is denied.

**Comment by SohailAsghar236** [comment]
Thank you for your help. I wanted to share a screenshot of my router interface setting so you might point out the problem in the setting.

![Uploading OpenWRT_Router_Interface.png…]()

**Comment by bluewavenet** [comment]
@SohailAsghar236 
That screenshot does not show what is wrong but gives the same clues as `ndsctl status` does.
 1. The lan interface has an ip address that is uncoventional (and by implication incorrect) ip address.
 2. The wan interface does not have an ip address at all.
 
You will get a better view by looking at the output of:
`uci export network`

**Comment by SohailAsghar236** [comment]
This is what I get from **uci export network** command:

```
uci export network
package network

config interface 'loopback'
        option device 'lo'
        option proto 'static'
        option ipaddr '127.0.0.1'
        option netmask '255.0.0.0'

config globals 'globals'
        option ula_prefix 'fdfa:2747:960f::/48'
        option packet_steering '1'

config device
        option name 'br-lan'
        option type 'bridge'
        option ipv6 '0'
        list ports 'eth0'
        list ports 'lan1'
        list ports 'lan2'
        list ports 'lan3'
        list ports 'lan4'
        list ports 'wan'

config interface 'lan'
        option device 'br-lan'
        option proto 'static'
        option ipaddr '192.168.74.50'
        option netmask '255.255.255.0'
        option ip6assign '60'
        list dns '8.8.8.8'
        list dns '8.8.4.4'
        option delegate '0'
        option gateway '192.168.74.1'
        option broadcast '192.168.74.255'

config interface 'wan'
        option device 'eth0'
        option proto 'dhcp'
        option peerdns '0'
        list dns '8.8.8.8'
        list dns '8.8.4.4'
        option broadcast '1'
        option delegate '0'

config interface 'wan6'
        option device 'wan'
        option proto 'dhcpv6'```

**Comment by bluewavenet** [comment]
@SohailAsghar236 
You have eth0 in both lan and wan.
I am guessing, but eth0 is probably the switch device so should not be included anywhere.
Most likely, currently, eth0 is being allocated an ip address from upstream but it is being applied to br-lan because of this miss-configuration.
I have no idea how your vm is configured, that is outside the scope of openNDS, you will have to work out that side of it for yourself.

**Hint-1**: The VM MUST emulate a physical router. ie wan connected to upstream Internet feed and lan providing connectivity to clients.
**Hint-2**: The VM lan must have its own ip subnet, different to the upstream subnet

**Comment by SohailAsghar236** [comment]
@bluewavenet The screenshot and command output I sent you are from ssh connection to an actual physical router and not a VM. There is no VM involved as of right now as I removed FAS. The router is a physical device upon which I have installed the openNDS package. According to this, are my settings are interface configuration still incorrect?

**Comment by bluewavenet** [comment]
@SohailAsghar236 

> are my settings are interface configuration still incorrect?

Yes. You must have changed configs from the default quite significantly. By default routing will be pre-configured for you. All that you would need to do is enable wireless.

**Comment by SohailAsghar236** [comment]
@bluewavenet Thank you for timely response. You have been very helpful. I am able to run OpenNDS in the most basic form with default configuration on my physical OpenWRT router. I want to keep this thread open so I can ask more questions if I get stuck.

**Comment by bluewavenet** [comment]
@SohailAsghar236 

Did you even read the logs you posted?
`Thu May 23 07:42:11 2024 daemon.err opennds[26796]: PHP packages PHP CLI and PHP OpenSSL are required`


> Followed this portion:
> ...
> ...
> ...
> **_Install the packages php8-cli and php8-mod-openssl_**
> ...


I don't think you did follow the documentation.... Please don't waste my time.

**Comment by SohailAsghar236** [comment]
@bluewavenet

I did read the logs but I just want to ask that these packages need to be installed on router or my FAS server?

**Comment by bluewavenet** [comment]
@SohailAsghar236 
Ask yourself what produced the error. Was it the openNDS router or your FAS server?

**Comment by SohailAsghar236** [comment]
@bluewavenet 

The error is produced by the openNDS router but as rotuer is a lightweight device and I was a bit doubtful to install these packages on router. I have installed them now using opkg command. Thank you for your support.

**Comment by bluewavenet** [comment]
@SohailAsghar236 
I see you also have:
` option fasremoteip '192.168.74.37'`

You are attempting to run a FAS server on the openNDS router's lan. For security reasons this is prohibited.

> You can run the FAS example script, fas-aes.php, locally **_on the same device that is running NDS_** (A minimum of 64MB of ram may be sufficient, but 128MB is recommended), _**or remotely on an Internet based FAS server.**_

https://opennds.readthedocs.io/en/stable/fas.html#using-the-fas-example-scripts-fas-hid-fas-aes-php-fas-hid-https-php-and-fas-aes-https-php

**Comment by SohailAsghar236** [comment]
@bluewavenet 

Thank you for pointing this out. I will move the the FAS to a remote server.

**Comment by SohailAsghar236** [comment]
@bluewavenet 

I am getting another error when trying to restart opennds service:

Command: **service opennds restart; logread | grep "opennds"**

```
Thu May 23 09:47:43 2024 daemon.notice opennds[5176]: Initializing firewall rules
Thu May 23 09:47:44 2024 daemon.err opennds[5176]: Error initializing firewall rules! Cleaning up
Thu May 23 09:47:45 2024 daemon.err opennds[5176]: Exiting because of error initializing firewall rules
Thu May 23 09:47:55 2024 daemon.notice opennds[7960]: openNDS Version 10.2.0 is in startup
Thu May 23 09:47:55 2024 daemon.info opennds[7960]: openNDS Version 10.2.0 is in startup - Please wait....
Thu May 23 09:47:55 2024 daemon.notice opennds[7960]: The name of this gateway is openNDS
Thu May 23 09:48:04 2024 daemon.notice opennds[7960]: Attempting to Bind to interface: br-lan
Thu May 23 09:48:04 2024 daemon.notice opennds[7960]: Interface br-lan is up
Thu May 23 09:48:04 2024 daemon.notice opennds[7960]: Interface br-lan is at 192.168.1.1 (3460f9b1fc9f)
Thu May 23 09:48:04 2024 daemon.notice opennds[7960]: MHD version is 0.9.75
Thu May 23 09:48:04 2024 daemon.notice opennds[7960]: Number of Upstream gateway(s) [ 1 ]
Thu May 23 09:48:04 2024 daemon.notice opennds[7960]: Upstream gateway(s) [ online:192.168.74.1,wan  ]
Thu May 23 09:48:04 2024 daemon.notice opennds[7960]: Preemptive authentication is enabled
Thu May 23 09:48:06 2024 daemon.notice opennds[7960]: Adding Serial Number suffix [3460f9b1fc9f] to gatewayname
Thu May 23 09:48:06 2024 daemon.notice opennds[7960]: Created web server on 192.168.1.1:2050
Thu May 23 09:48:06 2024 daemon.notice opennds[7960]: Maximum Html Page size is [ 10240 ] Bytes
Thu May 23 09:48:06 2024 daemon.notice opennds[7960]: Socket access at /tmp/ndsctl.sock
Thu May 23 09:48:06 2024 daemon.notice opennds[7960]: FAS Enabled.
Thu May 23 09:48:06 2024 daemon.notice opennds[7960]: sha256sum provider is available
Thu May 23 09:48:06 2024 daemon.notice opennds[7960]: SSL Provider is active
Thu May 23 09:48:06 2024 daemon.notice opennds[7960]: Forwarding Authentication is Enabled.
Thu May 23 09:48:06 2024 daemon.notice opennds[7960]: Binauth is Enabled.
Thu May 23 09:48:08 2024 daemon.notice opennds[7960]: Externals flagged with debuglevel 1.
Thu May 23 09:48:08 2024 daemon.notice opennds[7960]: Initializing firewall rules
Thu May 23 09:48:09 2024 daemon.err opennds[7960]: Error initializing firewall rules! Cleaning up
Thu May 23 09:48:09 2024 daemon.err opennds[7960]: Exiting because of error initializing firewall rules
```

**Comment by bluewavenet** [comment]
@SohailAsghar236 

> Is this related to remote IP of FAS being on openNDS router LAN?

I thought you moved the FAS to a remote server?

Please show the current output of:
`uci show opennds`

**Comment by SohailAsghar236** [comment]
@bluewavenet 

Current output of **uci show opennds**:

```
opennds.@opennds[0]=opennds
opennds.@opennds[0].fasport='2080'
opennds.@opennds[0].fasremotefqdn='freerad'
opennds.@opennds[0].fasremoteip='192.168.74.37'
opennds.@opennds[0].faspath='/nds/fas-aes.php'
opennds.@opennds[0].fas_secure_enabled='2'
opennds.@opennds[0].faskey='c559fed769641d723660e4a5ffa7eb3fc180e15dfb007363378337f44f3326ae'
```

**Comment by bluewavenet** [comment]
@SohailAsghar236 
`freerad` is not a valid fqdn.
`192.168.74.37` is not a public ip.

Once more, from the documentation:

> or remotely on an _**Internet based FAS server**_

**Comment by SohailAsghar236** [comment]
@bluewavenet 

Thank you. Let me move FAS to a remote server and try again.

**Comment by SohailAsghar236** [comment]
@bluewavenet 

I have moved the fas-aes.php file to remote server and it worked. Thank you for guidance.

**Comment by SohailAsghar236** [comment]
@bluewavenet 

The fas-aes.php file can be changed to any script language? Can I use any other language other than PHP to implement same piece of code?

Also, The demo file provided email address and name fields only. Can I implement email address and password along with registration capability for FAS. Can I connect OpenNDS with OpenWISP?

**Comment by bluewavenet** [comment]
@SohailAsghar236 

> Can I use any other language other than PHP to implement same piece of code?

Yes of course, as long as it responds in exactly the same way.

> The demo file provided email address and name fields only

You can add whatever fields you like. FAS is only concerned with credential validation. It is openNDS that does "authentication", where "authentication" means granting Internet access.

> Can I connect OpenNDS with OpenWISP?

What would you hope to  achieve?
If you are asking that question, then I am afraid you have little or no understanding of either openNDS or OpenWisP.

**Comment by bluewavenet** [comment]
@SohailAsghar236 
There are many who have a pretentious attitude and are clearly being dishonest in much of what they say, but you do not seem to be either. So please disregard my sometimes brutal comments ;-)
I am happy to help where I can.

**Comment by SohailAsghar236** [comment]
@bluewavenet 

I have a question and I am not really sure if it's related to this thread.

I have registered my OpenWRT AP (opennds service installed and running) using OpenWISP. Can I modify the opennds config file via OpenWISP? I want a solution to modify or update the FAS path URL using a UI or admin dashboard.

**Comment by bluewavenet** [comment]
@SohailAsghar236 

> Can I modify the opennds config file via OpenWISP? 

You will have to ask OpenWisp about that. Note also that as far as official OpenWrt is concerned, OpenWisp has been unmaintained for 2 years and even then the OpenWrt feeds have a version that OpenWisp never released.
In my opinion I would approach this with a great deal of caution....

It is up to you of course, but, if I may ask, **_why_** would you want to do this?

FYI: Standard openNDS FAS has built in ability to autonomously provide localised splash page sequences controlled by the remote FAS server.

**Comment by SohailAsghar236** [comment]
@bluewavenet 

> It is up to you of course, but, if I may ask, **_why_** would you want to do this?

I have to build an admin dashboard or UI to be able to create and update templates for captive portal or splash pages for different WiFi HotSpots. I am trying to use OpenWISP to manage my APs and need a way to deploy these templates. So far the simplest thing that I tried was to update the FAS path for openNDS config file using a configuration template in OpenWISP but that was a failure. I hope I am making a bit of sense.

> FYI: Standard openNDS FAS has built in ability to autonomously provide localised splash page sequences controlled by the remote FAS server.

How can I achieve this? Can you give me some pointers about this?

**Comment by bluewavenet** [comment]
@SohailAsghar236 
You do not need to "create and update templates and deploy them".
It seems you are missing the point of having a central Internet hosted FAS server. A FAS server is just a web site that responds adaptively to requests from openNDS routers installed in the field.
By default, every openNDS instance has a unique identifier, so it is a simple task for the FAS to generate content based on this identifier.

> Can you please give me some pointers about this?

Yes. Install the fas-aes-https example script on an Internet hosted web-server and get to grips with how it works by looking at the php code.

Your "admin dashboard" will be nothing more than a CMS that feeds into your eventual version of the FAS code.
As a web developer, you should find that part easy.

**Comment by SohailAsghar236** [comment]
@bluewavenet 

Thank you for your help! You have guided me well to understand the structure and concepts of openNDS.
