### ISSUE TITLE
Question about using walled garden for authentication

### ISSUE THREAD

**Issue by AdityaC4** [openNDS/openNDS#598]
Hello,
After the preauth using the default openNDS captive portal, would I be able to use a walled garden to restrict the user to my webapp (because I need to use javascript) which does the authentication. Can I then allow the specific user full access to the internet? or do walled not support this functionality. 
Also how do I edit the default captive portal or do I have to use the themespec page?
Thank You 😄

**Comment by bluewavenet** [comment]
@AdityaC4 

>  I need to use javascript

Javascript (amongst many other things) 
is prohibited in the CPD (Captive Portal Detection) functionality of operating systems, for security reasons.

**_This is a function of the client device and not the captive portal._**

To simply explain this, consider, a captive portal could be carefully crafted as a "man-in-the-middle" attack engine. For example it could monitor what clients are doing and when an online banking web site is requested, the portal could spoof the actual banking web site. So many security processes are implemented in the client's CPD to prevent this.

Looking at javascript in particular, downloading and executing code on the client device when that device is "captured" by the unknown MITM, would be very dangerous.

However, _**if a remote FAS server was running the javascript, then this is a different story**_ as it would not be any different to any other dynamically generated web site.

**Comment by AdityaC4** [comment]
So an OAuth login page like in the image would not work because of the API calls oauth makes to google and others. I was trying to get around this by giving the user access to only the authentication website after the default click to continue page, when the user authenticates, my server will tell the router to grant full access to the authenticated user. 
Would that work without risking MITM. The wifi is already secured with WPA2
![image](https://github.com/openNDS/openNDS/assets/98672108/57b363c2-b823-4ca1-9f2c-7d17e05f4ba8)

**Comment by bluewavenet** [comment]
@AdityaC4 
If any of the javascript is intended to be run on the client device, then CPD will block it.
It is perfectly possible to run the client portion of the api calls on a remote server ie an Internet hosted FAS server. Support for this is not "built in" to openNDS, but there is nothing to stop you developing such a FAS, many others have.

>  The wifi is already secured with WPA2

This is irrelevant. Any "user" given the wifi code will have the theoretical capability of setting up a MITMA. That is why CPD is concerned with the client's security.

Captive portals for public venues will always have open networks, anything else is pointless as every visitor to the venue will have to be given the code. Encrypting traffic on the air is automatically done these days by all websites, email clients etc etc. A wifi code is useful to restrict use of a private network but is just a very inconvenient administrative overhead for a public network.

**Comment by bluewavenet** [comment]
@AdityaC4 

> Okayy, so I should be looking into Server Side Rendered FAS? 

Yes, this is mandatory.

**Comment by AdityaC4** [comment]
Thank you for the clarification! Also, is there a way to push a webpage to the user after the authentication is completed using the FAS. Would I do that in the BinAuth script?

**Comment by bluewavenet** [comment]
@AdityaC4 

>  is there a way to push a webpage to the user after the authentication is completed 

No. The client operating system CPD will close automatically after authentication has occurred, at least in most cases. Again, this is for security purposes.

**Comment by bluewavenet** [comment]
@AdityaC4 

> BinAuth script

The binauth script is purely for post authentication processing and has no input whatsoever on what is displayed on the client device. The binauth script is called by openNDS immediately after authentication. It in turn calls the `/usr/lib/opennds/custombinauth.sh` script where custom post authentication processing can be added.
See:
https://opennds.readthedocs.io/en/stable/binauth.html#binauth-option
