### ISSUE TITLE
How do I use an HTTPS FAS server?

### ISSUE THREAD

**Issue by boluojiang521** [openNDS/openNDS#60]
great opennds：
  How can I set the router's 443 HTTPS to be redirected to the SSL service of my FAS server? Although the certificate error will be prompted, the user can authenticate the Internet after clicking continue，

**Comment by bluewavenet** [comment]
@boluojiang521 
Please keep the titles of issues as short as possible whilst indicating what the issue is about of course :-D

If you want to use an HTTPS FAS, you must use option fas_secure_enabled '3'.
This will work on a local HTTPS FAS but you are correct, it will indeed result in a certificate error on the client CPD.
In my opinion it is _**very**_ much better to use HTTP than it is to have certificate errors. Certificate errors are telling clients **not to trust your captive portal**.

Normally, an HTTPS FAS would be on an external web server with valid certificates.

openNDS uses its Authmon daemon for authentication, allowing FAS to effectively tunnel inbound NAT. This means your FAS must authenticate in a different way (note the difference between client credential validation and openNDS authentication).
See `fas-aes-https.php` for details.

**Comment by boluojiang521** [comment]
Thank you very much great opennds:
I will follow your instructions to use the HTTPS of Fas. What I would like to ask is that once the HTTPS of my FAS is successful, for example, my SSL is https://testfas2.abc.com , then the user clicks on the mobile phone https://www.google.com If the user clicks continue, then it will arrive https://testfas2.abc.com/nds/fas-aes-https.php On the authentication interface?

**Comment by boluojiang521** [comment]
This is a remedy for users who can't get the pop-up portal page, because almost 100% of the mainstream websites use HTTPS

**Comment by bluewavenet** [comment]
@boluojiang521 
It is important to understand the difference between: 

1. an https FAS (with valid certificates)
2. a captive portal that attempts to redirect https requests

**An https FAS** with valid certificates presents a secure environment (**_with no security warnings_**), for clients to login. _This is a very good thing._

**A captive portal that attempts to redirect https requests** is a very severe security problem and is nothing less than a "man in the middle" attack. _This is a VERY BAD thing._

**The https protocol** is specifically designed to provide secure access to web sites, ensuring the web site is actually the one that was requested, and providing encryption to prevent snooping by third parties.

> almost 100% of the mainstream websites use HTTPS

**This is true and gives the public confidence** in the security of those web sites, particularly where personal information is entered or online purchases are made. **_Dire security warnings from browsers are there for a reason. That reason it to inform the user that something bad is happening._**

**CPD (Captive Portal Detection)** is a protocol implemented as a process on all mainstream operating systems and web browsers. **_CPD runs on the client device_**.

**CPD is a standard** that has evolved over many years to allow client devices to securely connect to Captive Portals. It uses a dedicated, Internet based, port 80, http web page. All vendors have their own such page. For more information, see:
https://opennds.readthedocs.io/en/stable/howitworks.html#captive-portal-detection-cpd

Attempting to break https security to redirect to a captive portal is a very bad thing and doomed to failure.

Having an https FAS is a very good thing as it gives confidence to users that all is well - but there MUST be no certificate/security warnings.

Some people choose to install mobile apps or browser plugins that force all web requests to use https. This is unnecessary as it bypasses all the built in safeguards present in modern browsers. All these apps/plugins achieve is muting of security warnings. They do however block the client from accessing any legitimate captive portals.

**Comment by boluojiang521** [comment]
I have now implemented the HTTPS communication between the router and Fas. Because users have reported that some mobile phones can't get the portal page, or the access speed of the portal page is very slow. Therefore, they would like to prompt the user to open the browser and click Google to obtain the authentication page. Therefore, they hope that the HTTPS will be redirected to the portal, that is, SSL reports an error, but it doesn't matter , the store waiter will tell the user that this is secure, but the authentication page is helpless now, so how can I redirect the user's visited HTTPS to the Fas's HTTPS?

**Comment by bluewavenet** [comment]
@boluojiang521 

> the store waiter will tell the user that this is secure

That is what any con-man/criminal would tell you!

> how can I redirect the user's visited HTTPS to the Fas's HTTPS?

You cannot and must not as it breaks https protocol. CPD does not support it and therefore openNDS does not support it either.

> users have reported that some mobile phones can't get the portal page

1. If users have installed an app to force all web requests to https, then all legitimate captive portals will also be blocked. This is the users choice and nothing we can do about it.
3. For battery saving purposes, some client device CPD implementations stop polling the conncheck urls once they detect an active Internet connection. This means the portal page may not be triggered at a later time whilst in that state. The "store waiter" should inform users with this problem to disconnect from the wifi, then reconnect. This should restart the CPD polling.

> access speed of the portal page is very slow

This can happen for many reasons, the most common being the router running openNDS is slow and/or running out of RAM, or more often than not, a configuration problem.

All modern operating systems are dual stack and give priority to IPv6 if available. The CPD will retry IPv6 repeatedly before timing out and moving on to IPv4. 
This is only a problem if the device retry interval is rather long. _Some_  (not all) versions of iOS and Samsung Android show this problem. 
The issue can be resolved by ensuring the router is NOT providing DNS services on IPv6.

**_Also, make sure you have read and understood my previous comment about the difference between "https FAS" and "https redirection"._**

**Comment by boluojiang521** [comment]
thanks bluewavenet
