### ISSUE TITLE
A Recognition

### ISSUE THREAD

**Issue by 25khattab** [openNDS/openNDS#602]
Hi I'm not sure whether you will remember me or not, Im the one who wanted to create a username password login with a qouta for each user.

I have to really thank you as this was the first project I opened an Issue in and you have helped me a lot and made a better developer, I'm now working as a software engineer for DXC, I just wanted to thank you from bottom of my heart and sorry for making a new issue to say that yo you 😅, but this time its not an issue.

**Comment by bluewavenet** [comment]
@25khattab 
It sounded familiar, so looked up your issues. Back in ~2021.

Good luck in your new job! ;-)
