### ISSUE TITLE
Bucket value - wrong computing

### ISSUE THREAD

**Issue by rdpmc** [openNDS/openNDS#603]
look at src//fw_iptables.c - bucket computing code in 494 - 496 lines.
If you are trying to compute percentage of overcoming packet above packet_limit - this code is wrong, because bucket will be always = 0 until packet is 2 times more then  packet_limit.

You should use double or float for bucket var and packet,packet_limit

**Comment by bluewavenet** [comment]
@rdpmc 

> bucket will be always = 0 until packet is 2 times more then packet_limit.

No, because the minimum bucket size is set to 5.

**Comment by rdpmc** [comment]
5? Why may be not 6?)))
Any way your code in 494-496 is not  have any sense. 
For what reason you compute (packet-packet_limit)/packet there -i have no idea..

**Comment by bluewavenet** [comment]
@rdpmc 

>  Any way your code in 494-496 is not have any sense.

It looks self-explanatory to me.... but I will explain below....

> For what reason you compute (packet-packet_limit)/packet there -i have no idea..

It is calculating the approximate number of packets the bucket needs to hold for a given rate before dropping any packets. It is never less than 5, the nft default.

> Why may be not 6

It can be any number greater than 4. It is not something you set, it is calculated based on current data rate found by averaging over a set time window. It is a compromise between dropped packets and memory consumption per client.
