### ISSUE TITLE
Question about fas_secure_enabled level 3

### ISSUE THREAD

**Issue by maoudia-via** [openNDS/openNDS#606]
Hello, 

The documentations says the following about post-fas processing in the level 3 case:
`When fas_secure_enabled level 3 or 4 is used (https protocol), post verification authentication is achieved by the openNDS Authmon daemon.

Authmon is started by openNDS to facilitate NAT traversal and allow a remote https FAS to communicate with the local openNDS.

FAS will deposit client authentication variables for the Authmon daemon to use for the authentication process.`

Looking at the php FAS [example](https://github.com/openNDS/openNDS/blob/d411966216019cd75fcf21a9e0c737c9a46e2101/forward_authentication_service/fas-aes/fas-aes-https.php#L542), it looks like the FAS is writing a log entry to a file which is located where OpenNDS authmon daemon has access. 

I am not sure how a **remote** FAS can have access to this file system.  A clarification of how FAS informs openNDS that authentication was successful would be great !

**Comment by maoudia-via** [comment]
An additional clarifying comment for the question: I see that binauth_log.sh seems to be reading the logs and authenticating clients with opennds but it is unclear how that can be done remotely (the script [uses](https://github.com/openNDS/openNDS/blob/d411966216019cd75fcf21a9e0c737c9a46e2101/forward_authentication_service/binauth/binauth_log.sh#L262C11-L262C17) ndsctl)

**Comment by bluewavenet** [comment]
@maoudia-via 

If I clarify some of the terminology used in openNDS, it might help.

 1. Authentication - the action of an openNDS instance when it allows a client access to the Internet
 2. Credential Verification - the action of a FAS when it verifies the credentials that a user enters on the screen of their device.
 
A user enters their credentials in the form presented to them. The FAS verifies this information in some way, eg checks email address against an account database.

If the credentials are verified, the FAS notifies openNDS, via the authmon nat traversal path, that the client may be granted Internet access.

Authmon receives this notification and in turn requests openNDS to authenticate the client device.

The nat traversal is achieved by authmon by opening a channel to the remote FAS, through which the FAS can send data to authmon.
