### ISSUE TITLE
Disconnecting user using FAS after a time limit

### ISSUE THREAD

**Issue by SohailAsghar236** [openNDS/openNDS#609]
Hi @bluewavenet 

I have a question related to openNDS used as a service in openWRT AP. I have configured openNDS to use a FAS with secure_enabled level 2. FAS is hosted on a hosting site. Using a PHP script, on FAS, I am checking user credentials againt a freeradius database that I have setup on same hosting as FAS. A user is only authenticated if the user credentials match against freeradius database entry.

To implement user policy or a group policy, I want to disconnect a user and deny internet after a set time limit. How can I achieve this using FAS? Can FAS send a request to openNDS service to disconnect user?

I apologize in advance if this is a stupid question.

**Comment by bluewavenet** [comment]
@SohailAsghar236 

> I want to disconnect a user and deny internet after a set time limit. How can I achieve this using FAS?

As you are running a level 2 FAS, this will be based on fas-aes.php.

Look at line 199 in fas-aes.php.
Here a custom string is sent to openNDS.
If you add sessionlength to this string, openNDS will deauth the client when this value is reached.

Line199 is currently:
`	$custom="fullname=$fullname, email=$email";`

To set the sessionlength for the client to, say 2 hours (120 minutes), change line 199 to:
`	$custom="fullname=$fullname, email=$email, session_length=120";`

You will have to do an equivalent in your FAS script of course.

**Comment by bluewavenet** [comment]
@SohailAsghar236 

> Should I check my binauth.sh file? 

You have changed it from the original? If you have you will have most likely broken things. If you want to add something to the binauth functionality you should add that code to the `/usr/lib/opennds/custombinauth.sh` script.
See: 
https://opennds.readthedocs.io/en/stable/binauth.html#custom-binauth-script

**Comment by SohailAsghar236** [comment]
@bluewavenet 

I haven't changed the **binauth.sh** yet. I just wanted to check it. What could be the reason that **session_length** didn't work in my **FAS** code?

**Comment by bluewavenet** [comment]
@SohailAsghar236 

> I tried above mentioned solution exactly but it didn't deauthenticate the client and internet didn't stop.

To be clear, this does not deauthenticate the client. It authenticates with a session_length that overrides the value (if any) set in the config.

I have no idea how your fas script differs from the example script, but perhaps the custom string is not being passed?

**Comment by SohailAsghar236** [comment]
@bluewavenet 

I also think that custom string is not getting passed.

**Comment by bluewavenet** [comment]
@SohailAsghar236 
Look in `/tmp/ndslog/binauthlog.log`
This should have the received custom string in b64encoded form.

**Comment by SohailAsghar236** [comment]
@bluewavenet 

Thank you! I forgot to check the ndslog. That should have been my first step.

**Comment by bluewavenet** [comment]
@SohailAsghar236 
The parsing for session_length is a bit simple minded, so the value must be at the end of the custom string just like my example.

**Comment by SohailAsghar236** [comment]
Hi @bluewavenet 

In my **FAS** PHP script, I have added these lines to custom to send for authaction:
$username = $request->input('username');
$password = $request->input('password');
$session_length = 65;

$custom = "username=$username, password=$password, session_length=$session_length";
$custom = base64_encode($custom);

I checked my **binauthlog.log** file if sessiontimeout is overwritten but it neever is. It is still using the default openNDS config value of 1440 minutes.

Also, I tried decoding the custom string in **custombinauth.sh** file and echo the values to a debug.log file but everytime I get session_light as 6 instead of 65. It keeps skipping second digit and it never applies it to the client.

**custombinauth.sh**
`# Debugging output
echo "Custom Binauth Script Called" >> /tmp/ndslog/debug.log
echo "Custom Data: $custom" >> /tmp/ndslog/debug.log

# Since custom data is already decoded by binauth_log.sh, no need to decode again
# Debugging output
echo "Received Custom Data: $custom" >> /tmp/ndslog/debug.log

# Extract session_length from custom data
custom_session_length=$(echo "$custom" | awk -F"session_length=" '{print $2}' | awk -F"," '{print $1}')

# Debugging output
echo "Extracted Session Length (Raw): $custom_session_length" >> /tmp/ndslog/debug.log

if [ ! -z "$custom_session_length" ]; then
    sessiontimeout=$custom_session_length
fi

# Debugging output
echo "Final Session Length: $session_length" >> /tmp/ndslog/debug.log
`

**debug.log**
`Custom Data: username=*****, password=*****, session_length=6
Received Custom Data: username=*****, password=*****, session_length=6`

Can you please let me know what I am doing wrong or what I have missed? Thank you.

**Comment by SohailAsghar236** [comment]
@bluewavenet 

**custombinauth.sh** code:
`custom_data_decoded=$(ndsctl b64decode "$customdata")

session_length=$(echo "$custom_data_decoded" | awk -F"session_length=" '{printf "%d", $2}')

echo "---------------------------" >> /tmp/ndslog/debug.log
echo "Custom Data: $custom_data_decoded" >> /tmp/ndslog/debug.log
echo "Session Length: $session_length" >> /tmp/ndslog/debug.log
echo "---------------------------" >> /tmp/ndslog/debug.log`

**debug.log** output:
Custom Data: username=*****, password=*****, session_length=1
Session Length: 1
---------------------------
---------------------------
Custom Data: 
Session Length: 0
---------------------------
---------------------------
Custom Data: username=*****, password=*****, session_length=1
Session Length: 1
---------------------------
---------------------------
Custom Data: username=*****, password=*****, session_length=1
Session Length: 1
---------------------------
---------------------------
Custom Data: 
Session Length: 0
---------------------------
---------------------------
Custom Data: username=*****, password=*****, session_length='120��7���
Session Length: 0
---------------------------

My **FAS** script code:

$custom = "username=$username, password=$password, session_length=120";
$custom = base64_encode($custom);

**Comment by SohailAsghar236** [comment]
@bluewavenet 

I ran a few tests, so debug.log file has multiple entries. Also, it keeps logging twice or keeps running the custombinauth.sh file twice I think.

**Comment by bluewavenet** [comment]
@SohailAsghar236 
**_Note: Please use triple backtics to mark blocks of preformatted text - I edited your posts to make it easier to read._**

The openNDS NAT Traversal system removes any "=" characters in b64encoded strings, as these will cause errors. These characters often found on the end of the encoded string are used as padding.

So, the line in your custombinauth script:
`custom_data_decoded=$(ndsctl b64decode "$customdata")`

should read:
`custom_data_decoded=$(ndsctl b64decode "$customdata""==")`

This adds padding back to the encoded string. It does not matter if needed or not.

**Comment by SohailAsghar236** [comment]
@bluewavenet 

_**I will use triple backtics. Thank you.**_

I  updated the custombinauth script:
```custom_data_decoded=$(ndsctl b64decode "$customdata""==")
session_length=$(echo "$custom_data_decoded" | awk -F"session_length=" '{printf "%d", $2}')
echo "---------------------------" >> /tmp/ndslog/debug.log
echo "Custom Data: $custom_data_decoded" >> /tmp/ndslog/debug.log
echo "Session Length: $session_length" >> /tmp/ndslog/debug.log
echo "---------------------------" >> /tmp/ndslog/debug.log```

My debug.log output:
```Custom Data: 
Session Length: 0
---------------------------
---------------------------
Custom Data: username=sorab, password=admin, session_length=1��
Session Length: 1
---------------------------```

Still no change. I still get 24 hours time for session when I run **ndsctl status** for the authenticated client.

Am I missing something? I am using fas_secure_enabled level 2 and with that fas-aes.php script code.

**Comment by bluewavenet** [comment]
@SohailAsghar236 
Put the triple backtics on separate lines ;-)

Add this line so we can see what your php is sending:
`echo "Custom Data Raw: $customdata" >> /tmp/ndslog/debug.log`

**Comment by SohailAsghar236** [comment]
@bluewavenet 

In my fas-aes.php script code, I added a comma at the end of the custom string:

`$custom = "username=$username, password=$password, session_length=120,";

$custom = base64_encode($custom);`

My **debug.log** after adding comma:
```
Custom Data: 
Session Length: 0
---------------------------
What is PHP sending:
Custom Data Raw: 
---------------------------
Custom Data: username=sorab, password=admin, session_length=120,
Session Length: 120
---------------------------
What is PHP sending:
Custom Data Raw: dXNlcm5hbWU9c29yYWIsIHBhc3N3b3JkPWFkbWluLCBzZXNzaW9uX2xlbmd0aD0xMjAs
```

One more thing I want to mention:
The MAC address of this client that I am sending you data for is in openNDS trusted MAC addresses list. Can that be an issue?

All I want is for the FAS sent session_length value to work and disconnect user after session timeout. I think the session_length is getting ignored.

**Comment by SohailAsghar236** [comment]
@bluewavenet 

I tried to login using a mobile device and removed the comma from fas-aes.php script code.

**debug.log** file:

```
Custom Data: 
Session Length: 0
---------------------------
What is PHP sending:
Custom Data Raw: 
---------------------------
Custom Data: username=Sorab, password=admin, session_length=1��
Session Length: 1
---------------------------
What is PHP sending:
Custom Data Raw: dXNlcm5hbWU9U29yYWIsIHBhc3N3b3JkPWFkbWluLCBzZXNzaW9uX2xlbmd0aD0xMjA%3d
```
Nothing so far has worked. What could be the issue?

Please help me on this.

**Comment by SohailAsghar236** [comment]
@bluewavenet 

Thank you. Let me try this solution.

I wanted to ask if I should add == padding in my FAS script code when encoding the custom string? Or I should add it when when decoding it in **custombinauth**?

**Comment by bluewavenet** [comment]
@SohailAsghar236 

> I wanted to ask if I should add == padding

No, I forgot this was changed in a previous version, because adding padding can in some circumstances result in incorrect decoding. Also do not add it in the custombinauth script. Instead do the urldecode to restore the correct padding.

**Comment by SohailAsghar236** [comment]
@bluewavenet 

My code for **custombinauth** script:

```
customdata=$(echo "$customdata" | sed s/%3d/=/g)
custom_data_decoded=$(ndsctl b64decode "$customdata")
session_length=$(echo "$custom_data_decoded" | awk -F"session_length=" '{printf "%d", $2}')

echo "---------------------------" >> /tmp/ndslog/debug.log
echo "Custom Data: $custom_data_decoded" >> /tmp/ndslog/debug.log
echo "Session Length: $session_length" >> /tmp/ndslog/debug.log
echo "---------------------------" >> /tmp/ndslog/debug.log
echo "What is PHP sending:" >> /tmp/ndslog/debug.log
echo "Custom Data Raw: $customdata" >> /tmp/ndslog/debug.log
```

**FAS script** code:
```
$custom = "username=$username, password=$password, session_length=120";
$custom = base64_encode($custom);
```

I removed padding and added the line before decoding as you mentioned. Should I add urldecode too?

Even if all this works and outputs session_length=120 in debug.log but I don't see it's affect for the client. It keeps showing 24 hours session. Could this be because sessiontimeout is commented in opennds config file. Do I need to uncomment it to be overwritten?

Thank you in advance! You are a big help as always.

**Comment by bluewavenet** [comment]
@SohailAsghar236 

> Should I add urldecode too?

The sed command is the urldecode.

> Even if all this works and outputs session_length=120 in debug.log

It should do, show the logs and lets see.

> I don't see it's affect for the client.

Lets get it working in your logs first, then we can look at the next problem - if it still exists!

**Comment by bluewavenet** [comment]
@SohailAsghar236 
To get the values sent in the custom string, do:
`eval $(echo "$custom_data_decoded" | sed s/,/\;/g)`

After this $username, $password and $session_timeout will be populated.

The binauth_log.sh script will then send the following to openNDS:
`$session_length $upload_rate $download_rate $upload_quota $download_quota`

`$session_length` is set by custombinauth, overriding the config value, or at least that is what is supposed to happen ;-)

**Comment by SohailAsghar236** [comment]
@bluewavenet 

Thank you for these solutions. I will try these and post the results here.

Please do not close this thread yet.

**Comment by SohailAsghar236** [comment]
Hi @bluewavenet 

I followed the above mentioned steps.

My **custombinauth.sh** code:

```
customdata=$(echo "$customdata" | sed s/%3d/=/g)
custom_data_decoded=$(ndsctl b64decode "$customdata")
eval $(echo "$custom_data_decoded" | sed s/,/\;/g)

session_length=$(echo "$custom_data_decoded" | awk -F"session_length=" '{printf "%d", $2}')

echo "---------------------------" >> /tmp/ndslog/debug.log
echo "Custom Data: $custom_data_decoded" >> /tmp/ndslog/debug.log
echo "Session Length: $session_length" >> /tmp/ndslog/debug.log
echo "---------------------------" >> /tmp/ndslog/debug.log
echo "What is PHP sending:" >> /tmp/ndslog/debug.log
echo "Custom Data Raw: $customdata" >> /tmp/ndslog/debug.log
```

My **debug.log** output:

```
---------------------------
Custom Data: 
Session Length: 0
---------------------------
What is PHP sending:
Custom Data Raw: 
---------------------------
Custom Data: username=Sorab, password=admin, session_length=120
Session Length: 120
---------------------------
What is PHP sending:
Custom Data Raw: dXNlcm5hbWU9U29yYWIsIHBhc3N3b3JkPWFkbWluLCBzZXNzaW9uX2xlbmd0aD0xMjA=
---------------------------
Custom Data: 
Session Length: 0
---------------------------
What is PHP sending:
Custom Data Raw: 
---------------------------
Custom Data: username=Sorab, password=admin, session_length=120
Session Length: 120
---------------------------
What is PHP sending:
Custom Data Raw: dXNlcm5hbWU9U29yYWIsIHBhc3N3b3JkPWFkbWluLCBzZXNzaW9uX2xlbmd0aD0xMjA=
---------------------------
Custom Data: 
Session Length: 0
---------------------------
What is PHP sending:
Custom Data Raw: 
---------------------------
Custom Data: 
Session Length: 0
---------------------------
What is PHP sending:
Custom Data Raw: 
---------------------------
Custom Data: 
Session Length: 0
---------------------------
What is PHP sending:
Custom Data Raw: 
---------------------------
Custom Data: username=Sorab, password=admin, session_length=120
Session Length: 120
---------------------------
What is PHP sending:
Custom Data Raw: dXNlcm5hbWU9U29yYWIsIHBhc3N3b3JkPWFkbWluLCBzZXNzaW9uX2xlbmd0aD0xMjA=
```

I think the order of **custombinauth.sh** lines is not correct.

I want to mention that in **opennds config** file, **sessiontimeout** is commented and default value is used and it is never overriden by session_length.

**Comment by SohailAsghar236** [comment]
@bluewavenet 

Just for the sake of testing and debugging, I added a line to my **binauthlog.sh** after it calls **custombinaut.sh**:

```
custombinauthpath="/usr/lib/opennds/custombinauth.sh"

if [ -e "$custombinauthpath" ]; then
	. $custombinauthpath
fi

# Finally before exiting, output the session length, upload rate, download rate, upload quota and download quota (only effective for auth_client).
# The custom binauth script migh change these values
echo "$session_length $upload_rate $download_rate $upload_quota $download_quota"
# Added below line for testing and debugging purposes only
echo "All these parameters: $session_length $upload_rate $download_rate $upload_quota $download_quota" >> /tmp/ndslog/debug.log
```

**debug.log** output:

```
Custom Data: username=sorab, password=admin, session_length=120
Session Length: 120
---------------------------
What is PHP sending:
Custom Data Raw: dXNlcm5hbWU9c29yYWIsIHBhc3N3b3JkPWFkbWluLCBzZXNzaW9uX2xlbmd0aD0xMjA=
All these parameters: 120 0 0 0 0
```

session_length is getting sent but it is not being applied.

**Comment by bluewavenet** [comment]
@SohailAsghar236 
`All these parameters: 120 0 0 0 0`

Yes! So now that is working.

> session_length is getting sent but it is not being applied.

Our next issue to fix. It is possible that this is also a bug. Level 2 is little used as levels 3 and 4 have pretty much replaced it, so setting session_length by binauth might not have been tested in the current version... I will have to look into it.

Is there a reason you have to stick with level 2? Its usual usage is when the fas server is not Internet hosted....

I have to work at the paid job for the rest of the day, so will look this evening, my time (utc +1).

**Comment by bluewavenet** [comment]
@SohailAsghar236 
Levels 3 and 4 do not use custom binauth string for setting per user session_length, instead it is overridden from config by sending directly to opennds in the authentication request through the inbound nat traversal "tunnel".

See `function authenticate_page()` in fas-aes-https.php

You can still use binauth custom (but we think that does not work), but it is not needed.

See lines 534- 536
ie:
```
	# Construct the client authentication string or "log"
	# Note: override values set earlier if required, for example by testing clientif 
	$log="$rhid $sessionlength $uploadrate $downloadrate $uploadquota $downloadquota $custom \n";
```

**Comment by SohailAsghar236** [comment]
@bluewavenet 

Thank you. I will look throughly into fas-aes-http.php.

**Comment by SohailAsghar236** [comment]
@bluewavenet 

I implemented the fas_secure_level 3 with fas-aes-https.php and sessionlength worked out fine.

![NDS_Status_Snap](https://github.com/user-attachments/assets/ba4ff121-747d-423a-95c2-532d2aee3444)

![Deauth_Snap](https://github.com/user-attachments/assets/4260c24a-0b42-44e5-83b9-6f7e23675b77)

I changed the sessionlength value for both clients (20 first and then 15) in fas-aes-https.php file.

I think custombinauth.sh has nothing to do with this now. Am I correct? I should clean up that file.

Thank you so much for your help.

**Comment by bluewavenet** [comment]
@SohailAsghar236 

> I think custombinauth.sh has nothing to do with this now. Am I correct? 

Yes, correct, levels 3 and 4 do not need custombinauth to set session_length. It can however be used for other things if so desired.

> with fas-aes-https.php and sessionlength worked out fine.

Excellent!

Thank you for your continued efforts, including uncovering a bug in binauth processing - fixing it is now on my todo list ;-)

**Comment by SohailAsghar236** [comment]
@bluewavenet 

Thank you for your support and guidance.

I have just two last questions (I hope):

1. With level 3 and 4, what can custombinauth be used for? Can you give me an example or hint? It might come handy later.
2. Along with sessionlength, I can also send data rates (upload and download) from FAS?

**Comment by bluewavenet** [comment]
@SohailAsghar236 

> With level 3 and 4, what can custombinauth be used for?

With levels 3 and 4, custombinauth can be used to send any data from fas to opennds, usually, but not exclusively, something to do with the client. For example you might want to add or remove the client to/from the pre-emptive clients list.
A pre-emptive client is similar to a trusted client, but is subject to any configured or per-client quotas/rates.
See: https://opennds.readthedocs.io/en/stable/config.html#pre-emptive-clients

In answer to question 2, I mentioned this in my previous comment about `function authenticate_page()`

> See lines 534- 536
> ie:
> 
> ```
> 	# Construct the client authentication string or "log"
> 	# Note: override values set earlier if required, for example by testing clientif 
> 	$log="$rhid $sessionlength $uploadrate $downloadrate $uploadquota $downloadquota $custom \n";
> ```

**Comment by SohailAsghar236** [comment]
@bluewavenet 

This sums it up very well. Very useful.

Thank you so much.

**Comment by SohailAsghar236** [comment]
@bluewavenet 

With level 3, I am getting a log in my console:

Thu Aug  8 14:13:02 2024 daemon.err authmon[30634]:  in /usr/lib/opennds/post-request.php on line 38

Are the details logged anywhere for this? Where can I find the error detail for this.

**Comment by bluewavenet** [comment]
@SohailAsghar236 
`Thu Aug 8 14:13:02 2024 daemon.err authmon[30634]: in /usr/lib/opennds/post-request.php on line 38`

> Are the details logged anywhere for this? Where can I find the error detail for this.

This is the authmon daemon logging in syslog a standard php error.

Line 38 is:
`	$fp = fopen($remote_url, 'r', false, $context);`

Here, the error is generated if `fopen` fails.
This means that authmon cannot connect to the remote fas server.

This is seen, most commonly, when the Internet feed is down, or the fas server is not responding.

Can I assume everything was working just fine after this?

**Comment by SohailAsghar236** [comment]
@bluewavenet 

> Can I assume everything was working just fine after this?

Everything was working fine when I was using fas-aes-https.php but now I have converted that file into a Laravel framework code. The initial route **/fas** works fine and login screen is shown, once I accept terms and I want to load the authenticate page, the page keeps loading **** and it shows me the the portal has timed out form view. I think the issue is caused when OpenNDS sends a POST request for **auth_get()** function. I created a /fas POST route for it but I think that is causing issue. It might be that my Laravel installation is faulty and this problem is caused by CSRF token.

I hope I am able to explain my issue clearly.

**Comment by SohailAsghar236** [comment]
@bluewavenet 

In my post-request.php file, I tried to print the fopen related error in a debug.log file and I got this:

```
fopen(https://fas.appcraftr.com:443/fas): Failed to open stream: HTTP request failed! HTTP/1.1 419 proxy reauthentication required
```

**Comment by bluewavenet** [comment]
@SohailAsghar236 
`HTTP request failed! HTTP/1.1 419 proxy reauthentication required`

The question is, why are you going through a proxy? This is an issue with the hosting you are using for your fas server.

**Comment by SohailAsghar236** [comment]
@bluewavenet 

> The question is, why are you going through a proxy? This is an issue with the hosting you are using for your fas server.

I searched and found the same issue, the server issue. I have to revisit the settings for the server firewall or proxy as the fas-aes-http.php file was working fine on same server and domain name, the issue occurred after I installed Laravel framework.

**Comment by bluewavenet** [comment]
@SohailAsghar236 

>  the issue occurred after I installed Laravel framework.

My only experience of Laravel is that it produces bloatware. I cannot imagine why you would need the added complexity for a fas server. It is very much not suitable for captive portals.
Be warned: Do not use ANY js downloads in your fas server. The built in CPD of all client OS specifically block downloaded js (and any other executables) for security reasons.

**Comment by bluewavenet** [comment]
@SohailAsghar236 

>  the settings for the server firewall or proxy

It is very difficult and unreliable to use a proxy with https as it violates one of the principles of https, ie to guarantee you are connected to what you think you are connected to....

**Comment by SohailAsghar236** [comment]
@bluewavenet 

> My only experience of Laravel is that it produces bloatware.

Ouch! Laravel was a team decision and a requirement for a few reasons, nevertheless, we are back to using fas-aes-https.php and got rid of Laravel for FAS. Everything is working fine once again. I added some functionality to the fas-aes-https.php file but it's working fine without any issue. If there was any issue, I think it's related to the hosting.

I noted the **"Do not use ANY js downloads in your fas server."** point and once again, I thank you.

For a recap, I wanted to mention this:

My secure_enabled level in opennds config file is **3**.
I am using **fas-aes-https.php** on a hosted server.
Session length and quota related fields are sent via FAS and they work perfectly.

Thank you.

**Comment by SohailAsghar236** [comment]
@bluewavenet 

I have a question.

Is is possible to get the current connected client list or data to be sent from openNDS to FAS script file?

For example:

The command **ndsctl status** is very useful to see list of total and current clients and their various details.

Can I send this information to my FAS?

**Comment by bluewavenet** [comment]
@SohailAsghar236 

> Can I send this information to my FAS?

No need, FAS already has this information.
It logs when a client is authenticated AND when it is deauthenticated.

See function auth_get_deauthed() in fas-aes-https.php.

**Comment by SohailAsghar236** [comment]
@bluewavenet 

Great!

Now I remember that their is a folder created for ndslog. Sorry I overlooked this.

Thank you for your timely response.
