### ISSUE TITLE
Is openNDS waiting anything?

### ISSUE THREAD

**Issue by javierolaya-tech** [openNDS/openNDS#613]
Hello @bluewavenet 

I have my FAS almost working. When I answer authmon with the list  - `echo trim("$authlist");` my phone is waiting something but it never gets to connect. However, if I disable the WiFi on my phone and try to connect again I get the connected status (without going to my FAS). Is openNDS waiting, once I sent the authlist, anything else?

Thanks

**Comment by bluewavenet** [comment]
@javierolaya-tech 

>  my phone is waiting something but it never gets to connect. However, if I disable the WiFi on my phone and try to connect again I get the connected status (without going to my FAS). Is openNDS waiting, once I sent the authlist

No it is not waiting for anything. clearly the phone did get authenticated. Are you checking the authmon ack and serving the landing page? Depending on the phone's CPD, it may be waiting for the landing page after which it would say it was connected - depends on phone operating system. Eventually the phone's CPD should time out but this could be 300 seconds or even more.

You can check the opennds logs again to see if it gives any clues.

You could of course briefly revert back to the example php script just to check opennds/authmon is working correctly.
If that works, then obviously it is your fas that needs a little more work.

**Comment by bluewavenet** [comment]
@javierolaya-tech 

> it was quicker than now using the GL-MT300N-V2 router.

As you are using an external fas to do all the work, then the router speed does not really come into it significantly.
Everything will have grown somewhat as in inevitable. 

We use the mt300n-v2 quite a bit with a custom php script on a remote fas and have not seen any difference between latest versions and 2 years ago.

You could revert to the example fas php script and compare speed.

If it is still slow, then we can look ad details of the router end configs.

**Comment by javierolaya-tech** [comment]
@bluewavenet 

Then I have to check the openWRT system because maybe I have some configuration wrong (actually it  is the last version, everything by default, running opennds according the documentation). 

Thanks again for your time

**Comment by bluewavenet** [comment]
@javierolaya-tech 
What was the result of testing with the example fas php script?
Is it slow too?

> actually it is the last version

What do you mean by this? Do you mean OpenWrt is the version before the current one?
The current version is 23.05.3

**Comment by javierolaya-tech** [comment]
@bluewavenet 

> Is it slow too?

In fact, I can't connect with your script, I am authenticated (according to the webpage) but I always have the question mark above the wifi signal.

> The current version is 23.05.3

I mean, I have that version installed without touching any configuration except opennds things

**Comment by bluewavenet** [comment]
@javierolaya-tech 
If it does not work with the example script then you have something very wrong somewhere.

Lets start by looking at the output of:
`uci show opennds`

**Comment by javierolaya-tech** [comment]
@bluewavenet 

Here you go:

```
opennds.@opennds[0]=opennds
opennds.@opennds[0].fasport='443'
opennds.@opennds[0].fasremotefqdn='doublesecurityofficial.com'
opennds.@opennds[0].faspath='/fas-aes-https.php'
opennds.@opennds[0].fas_secure_enabled='3'
opennds.@opennds[0].faskey='mypassword'
```

**Comment by bluewavenet** [comment]
@javierolaya-tech 
I tried your config on my test system and it gives an almost instantaneous response "Encryption Error Access Forbidden" presumably because your faskey is not actually "mypassword".
Can you set a real value I can test with?

**Comment by javierolaya-tech** [comment]
@bluewavenet 

Ah sorry, I didn't know you went go to try directly. Try again with `mypassword`

**Comment by bluewavenet** [comment]
@javierolaya-tech 
The quickest way to see if it works ;-)

**Comment by bluewavenet** [comment]
@javierolaya-tech
`mypassword` still gives "Encryption Error Access Forbidden" .
Can you set it to `8870fb272659020607ac2ea8b8e72f809b55e02d4649123ea6e8ef8685dec1f4`

This is the value openNDS generated on my system if I comment out faskey in the config.

**Comment by bluewavenet** [comment]
@javierolaya-tech 
On your fas it says it has logged in, but in fact it has not. Your fas does not seem to be sending the auth request to authmon.

On my test server, it all works.
I will double check my server has the up to date version ....

Have you made any changes to fas-aes-https.php apart from the faskey?

**Comment by javierolaya-tech** [comment]
No

**Comment by javierolaya-tech** [comment]
I changed the owner to www-data, just in case...

**Comment by bluewavenet** [comment]
@javierolaya-tech 

The script need to be able to create and write its database files.
It creates a folder for each openNDS instance (a 64 char hash as the directory name), and a ndslog folder.

**Comment by javierolaya-tech** [comment]
@bluewavenet 

Yes, that's why I put `755`. I think it's enough, isn't it?

**Comment by bluewavenet** [comment]
@javierolaya-tech 

> Yes, that's why I put 755. I think it's enough, isn't it?

Should be. I missed your "owner" comment.
I'll switch back to your fas server..... I'm still on mine.

**Comment by bluewavenet** [comment]
@javierolaya-tech 
Nope. Your fas is not sending the authlist to authmon.

On my fas server I get:
```
Fri Jun 28 14:34:39 2024 daemon.debug authmon[29726]: authmon - authlist *
Fri Jun 28 14:34:39 2024 daemon.debug authmon[29726]: authmon - remote FAS response [ack]
Fri Jun 28 14:34:45 2024 daemon.debug authmon[29726]: authmon - authlist *
Fri Jun 28 14:34:45 2024 daemon.debug authmon[29726]: authmon - remote FAS response [ack]
Fri Jun 28 14:34:51 2024 daemon.debug authmon[29726]: authmon - authlist * 6b7e021caa5f2ce5dab4848f47817374c7134bf4a3304a284d9530866913a225%200%200%200%200%200%20ZnVsbG5hbWU9cm9iLCBlbWFpbD1yb2JAYmx1ZS13YXZlLm5ldA%3D%3D
Fri Jun 28 14:34:51 2024 daemon.info authmon[29726]: authmon - authentication parameters 6b7e021caa5f2ce5dab4848f47817374c7134bf4a3304a284d9530866913a225 0 0 0 0 0 ZnVsbG5hbWU9cm9iLCBlbWFpbD1yb2JAYmx1ZS13YXZlLm5ldA==

```

And on yours I get:
```
Fri Jun 28 14:48:50 2024 daemon.debug authmon[26679]: authmon - authlist
Fri Jun 28 14:48:51 2024 daemon.debug authmon[26679]: authmon - remote FAS response []
Fri Jun 28 14:48:56 2024 daemon.debug authmon[26679]: authmon - authlist
Fri Jun 28 14:48:56 2024 daemon.debug authmon[26679]: authmon - remote FAS response []
Fri Jun 28 14:49:02 2024 daemon.debug authmon[26679]: authmon - authlist
Fri Jun 28 14:49:02 2024 daemon.debug authmon[26679]: authmon - remote FAS response []

```

**Comment by javierolaya-tech** [comment]
@bluewavenet 

Then it has to be something about privileges... So, I was working on my Laravel project, to try your script I put it in my public folder and gave it permissions, any idea?

**Comment by bluewavenet** [comment]
@javierolaya-tech 
Do you have an old version of the script?
Here is what I am using:
https://github.com/openNDS/openNDS/blob/master/forward_authentication_service/fas-aes/fas-aes-https.php

**Comment by bluewavenet** [comment]
@javierolaya-tech 
Is your fas creating the instance and ndslog folders?

**Comment by javierolaya-tech** [comment]
@bluewavenet 

> Do you have an old version of the script?

The last one in the master branch.

> Is your fas creating the instance and ndslog folders?

With my app yes, with your script no. I am totally sure it is something about privileges

**Comment by javierolaya-tech** [comment]
@bluewavenet 

Can u try again?

**Comment by bluewavenet** [comment]
@javierolaya-tech 
`-rwxr-xr-x  1 www-data www-data 34348 Jun 28 14:05 fas-aes-https.php*`

That is setting the rights of www-data to the script file, not the rights of the php script to create and write

**Comment by javierolaya-tech** [comment]
@bluewavenet 

The folder folder has the same

**Comment by bluewavenet** [comment]
@javierolaya-tech 
Yay!
```
Fri Jun 28 15:08:09 2024 daemon.debug authmon[23501]: authmon - authlist *
Fri Jun 28 15:08:10 2024 daemon.debug authmon[23501]: authmon - remote FAS response [ack]
Fri Jun 28 15:08:15 2024 daemon.debug authmon[23501]: authmon - authlist *
Fri Jun 28 15:08:15 2024 daemon.debug authmon[23501]: authmon - remote FAS response [ack]
Fri Jun 28 15:08:21 2024 daemon.debug authmon[23501]: authmon - authlist * 004f1c31ec3e3a00bcef0a2731d8f1e01db1bf19af190022595ce325cdd363d3%200%200%200%200%200%20ZnVsbG5hbWU9cm9iLCBlbWFpbD1yb2JAYmx1ZS13YXZlLm5ldA%3D%3D
Fri Jun 28 15:08:21 2024 daemon.info authmon[23501]: authmon - authentication parameters 004f1c31ec3e3a00bcef0a2731d8f1e01db1bf19af190022595ce325cdd363d3 0 0 0 0 0 ZnVsbG5hbWU9cm9iLCBlbWFpbD1yb2JAYmx1ZS13YXZlLm5ldA==
Fri Jun 28 15:08:22 2024 daemon.debug authmon[23501]: authmon - remote FAS response [ack]

```

Whatever you did, it fixed it.

**Comment by javierolaya-tech** [comment]
@bluewavenet 

> Whatever you did, it fixed it.

Something dangerous! ha ha

**Comment by bluewavenet** [comment]
@javierolaya-tech 
It would be the same for your app would it not?

Anyway, the login pages came up almost instantaneously.
The very last page might take up to the option nat_traversal_poll_interval setting (default 5 seconds) for authentication to occur.

**Comment by javierolaya-tech** [comment]
@bluewavenet 

For me it is like 20 seconds after login. The thing is, even when I edit the `/etc/config/opennds`, I notice it lates too much time. That's why I think is something about openWRT or the router itself.

I have another router, I am going to try it with this one

**Comment by bluewavenet** [comment]
This is what I get:
![Screenshot from 2024-06-28 15-09-41](https://github.com/openNDS/openNDS/assets/13632068/55d1ec40-095f-41a0-9993-b5717a46612d)

Note the red star under "Waiting for link to establish..." 
There will be one every second if I remember correctly, until authmon returns the auth acknowledge.

Do you see 20 or so???

**Comment by javierolaya-tech** [comment]
@bluewavenet 

It's not 20 of those, but several... I am trying with my old app and it's the same, so it's likely my phone! I will try it with another one, but I don't have any available right now. I was trying with my laptop, but I don't know why the process isn't automatic, and the browser never opens for me to log in

**Comment by bluewavenet** [comment]
@javierolaya-tech 

> I was trying with my laptop

Android, Apple and Linux have CPD enabled by default.

Windows, I think has it off by default, not sure, I have not used it for years.

Firefox and Chrome "desktop" browsers also have CPD enabled by default.

On your laptop, how long does it take for http://status.client to come up in your browser?

**Comment by javierolaya-tech** [comment]
@bluewavenet 

I only needed to restart my computer :-)

This is the waiting on my laptop

![photo_2024-06-28_19-59-19](https://github.com/openNDS/openNDS/assets/169676090/7d6c448d-4472-4d7c-8795-31c317c9e168)

**Comment by bluewavenet** [comment]
@javierolaya-tech 
You could try:
`ndsctl debuglevel 3; logread -f -e authmon`

Then try connecting while watching the output.
It might give some hints at what is happening.
