### ISSUE TITLE
Reset openwrt/opennds

### ISSUE THREAD

**Issue by geedsen** [openNDS/openNDS#615]
Hi Bluewavenet,

You helped me out  a lot here: https://github.com/openNDS/openNDS/issues/587
Now I am in Zambia and have a problem. The code I made validates the voucher against a url.
That all worked well, but I forgot the url is hardcoded in the theme_voucher.sh, And currently is my home pc. And not running....
So I cannot access the router and can not login. What would be the easiest way to access it again? I can press the reset button, but dont really know if that would help and where it brings me. I would not mind doing the whole configuration from scratch.  Help appreciated. 

Ben

**Comment by bluewavenet** [comment]
@geedsen 
While powered on, press and hold the reset button for at least 15 seconds will usually return the router to the default state it was in when reflashed.
The leds usually flash in a pattern depending in the model.....

The default state is usually with wifi disabled and the 192.168.1.x subnet.

I hope this helps!
