### ISSUE TITLE
Theme_voucher quota down

### ISSUE THREAD

**Issue by amsteen** [openNDS/openNDS#616]
I setup

https://github.com/openNDS/openNDS/tree/master/community/themespec/theme_voucher

And it is working in general.
I need to know how to set max download size to 100MB so that
when client a client exceeds 100mb it should be
deauthenticated and voucher code should becomes invalid.

what I do

at vouchers.txt file I set values for test as ==> 8YAN-PSY9,1024 ,1024 ,10000 ,8000 ,1440 ,0 I notice that when I consumes 10mb the client logged out but voucher code still valid and you can login again with it.

I change Fair Usage Policy Throttle Rate in configuration file : to
option fup_upload_throttle_rate '0'
option fup_download_throttle_rate '0'
so that a client exceeds 10mb should be deauthenticated
but nothing changed

What I need
set quota down value so that If a client exceeds 10mb should be deauthenticated and voucher code should becomes invalid

**Comment by amsteen** [comment]
yes
Do you mean that the client does get logged out when the quota is used, but the voucher is still valid?
and you can login again wit same voucher

**Comment by bluewavenet** [comment]
@amsteen 
I am not familiar with the details of theme_voucher, but it seems you need to add some code to expire the voucher when the quota is used up.
You will have to look to see how voucher validity is defined. Once you know how to do this you can expire the voucher using the `/usr/lib/opennds/custombinauth.sh ` script that will be called by opennds when it deauthenticates the client.

https://opennds.readthedocs.io/en/stable/binauth.html#custom-binauth-script
