### ISSUE TITLE
Router constantly gets stuck

### ISSUE THREAD

**Issue by geedsen** [openNDS/openNDS#617]
On the 6th of June  I did a reset of the Xiaomi AX3000T and installed this image [[xiaomi_mi-router-ax3000t-ubootmod-squashfs-sysupgrade.itb]]
And then I installed luci and openNDS on top of it. I changed the lan ip address to 192.168.2.1 as the wan actually is a starlink router that uses 192.168.1.1. 
But since then I only found that the system is constantly not working. Sometimes I login via the openNDS page, I then open the luci interface. And while going through this , Iuci becomes unavailable. I get an ERR_CONNECTION_REFUSED. I can still SSH to it.

And while typing this my Starlink connection failed  and it connected to openWRT. It showed the openNDS "continue" page, I can fill out the user and email address, accept the terms but the next page is an error page "DNS_PROBE_FINISHED_NXDOMAIN"
So everything is highly unstable. Any ideas?

**Comment by geedsen** [comment]
I did another sysupgrade, with todays image.  Reinstalled opennds and luci. Looked like it was all working.  Then I added traffic rulesto allow SSH and Luci from the WAN.  I rebooted.  Connected. I go through the openNDS "accept terms" screens, but once I am connected, I lost the resolving of status,client. Si I cannot go back to either the openNDS screens or Luci.

**Comment by bluewavenet** [comment]
@geedsen 
Is this for the system in the coffee shop we talked about before?

> Xiaomi AX3000T

Not a good choice for a serious system just yet as it is only available on the potentially unstable OpenWrt daily snapshots...

The first thing to check is  Internet connectivity **_without_** 0penNDS.

Make sure it is not running:
`service opennds stop`

If the router is actually working properly you should get an ip address in the 192.168.2.x range and get Internet.

So far so good?

Now show the outputs of the following:

`uci show network`

`uci show wireless`

`uci show opennds`


Another thing:

> Then I added traffic rules to allow SSH and Luci from the WAN.

This won't work as  Starlink is not giving you a public ip address. For remote access you will need to set up a nat traversal tunnel of some kind, but we can go into that later. I think you have more fundamental problems to solve first.

**Comment by geedsen** [comment]
Yes. It is the Zambian system. And I am there now.   I am typing this on my phone connected to the system. And on the phone everything seems to be normal.  Status.client is working. Both for openNDS as for Luci.  So I need to check this again on the windows laptop. The problem only seems to happen there. About the SSH from the WAN, the WAN side of the openWRT router, is the LAN side of the starlink router. So if my PC is connected to  Starlink I should be able to use SSH to the Xiaomi.

**Comment by geedsen** [comment]
And if the router is indeed not powerful enough we will get another one. But it should hopefully be good enough to check out the concept. As you know I extended the voucher system with an App to generate the voucher code. Thiss works with an Android app, that communicates via an api . And I modified the voucher code to use that api as well.  But that api is now running on my laptop and it will need to run here locally. I was hoping to have it running on a raspberry pi  here, If possible I would like to run openwrt on it too and use some other routers just as access points.if possible. The pi 5 should be powerful enough.

**Comment by bluewavenet** [comment]
@geedsen 

> And if the router is indeed not powerful enough 

It should be more than powerful enough. I am just saying it is not yet in stable release of OpenWrt.
It is probably just fine as long as you do not try to add any packages after 24 hours as another build will have overwritten the previous one. 

> "DNS_PROBE_FINISHED_NXDOMAIN"

Is this an error on your laptop? I do not recognise it from OpenWrt.

>  on the phone everything seems to be normal. Status.client is working. Both for openNDS as for Luci. 

Does your laptop have a fixed dns config? For security, openNDS _**REQUIRES**_ that all clients use the OpenWrt dns server as supplied by dhcp.

> As you know I extended the voucher system with an App to generate the voucher code

Sounds good, but i have previously expressed my view on voucher systems ;-)

You should be able to run the api code on the router itself, but you will have to use the OpenWrt SDK to cross compile for the Filogic target (same goes for a Pi5 if you are running OpenWrt).

It is easy enough to do, but is just one more complexity required for the voucher system........

**Comment by geedsen** [comment]
DNS_PROBE_FINISHED_NXDOMAIN is indeed on my laptop. So why it is not getting the 192.168.2.1 as a dns server is unknown to me. I certainly have no fixed dns set.

**Comment by geedsen** [comment]
I checked my network properties on the laptop. It says it should use 127.0.0.1 and not DHCP. 
![image](https://github.com/user-attachments/assets/17ceb0ab-fa4e-49c9-a145-02be00063647)
So I changed it to use DHCP. 
![image](https://github.com/user-attachments/assets/24aa4a8a-7a36-4453-9a08-19f5475a4bf0)
I then renew my lease and checked again:

![image](https://github.com/user-attachments/assets/18897470-c4dd-41f2-8bc2-01e1bab69df9)
It is again set to 127.0.0.1

So I then change this 127.0.0.1 to 192.168.2.1 to use the router explicitly. And renew the lease, And again after this it is set to 127.0.0.1
I even tried specifying the second dns server to the router, but that disappears after the dhcp renew.

**Comment by bluewavenet** [comment]
@geedsen 

> It is again set to 127.0.0.1

That's windows for you. I stopped using it over 15 years ago because of things like this ;-)

Someone I had to help had this problem a couple of years ago. Then the solution was to disable networking, save, reboot.
Then do the network setup from scratch, reboot, then it was working. I think that was windows 10...
Worth a try?
Other than that, maybe look at some of the windows forums....

**Comment by geedsen** [comment]
Strange enough maybe, but I love windows. I started on IBM then  I did VMS, probably the most friendly operating system ever made. Then I had to move to unix and I hated it :).  Then Windows NT came out and it was so much like VMS (not surprising, it came from the same architect, Dave Cutler)...and I am still enjoying windows.

Anyway, after long googling I may have found the reason. I am traveling with my corporate laptop. And that does not allow me to visit certain sites(...). So it most probably has a local program running on my laptop to check for blacklisted hostnames. So somewhere it makes sure that dns entries are resolved locally.

But I slved the issue by adding "status.client 192.168.2.1" in my hosts file.

**Comment by geedsen** [comment]
So back to the issue of SSH from the wan, I requested the wan address:
![image](https://github.com/user-attachments/assets/09083d01-c147-4426-921b-7bc4891fac51)
And added the traffic rule:
![image](https://github.com/user-attachments/assets/15e53ab2-49be-4697-88a1-ad51f7925882)
Then connected to Starlink, so I get an ip in the same range as the openwrt wan ip. But connecting I get: 
![image](https://github.com/user-attachments/assets/a1cd3482-fc11-4852-b15a-2dca158db04c)

**Comment by bluewavenet** [comment]
@geedsen 

> Strange enough maybe, but I love windows

I have somewhat of a dislike for it - each to his own ;-)

Re firewall:
As you are behind the Starlink router with a private ipv4 address, it is safe to set the wan zone input to ACCEPT.

**Comment by geedsen** [comment]
If I set to WAN zone to ACCEPT, does that basically imply no firewall?
I would prefer to use the firewall to allow SSH from the WAN. But it just does not work. I changed the Allow-Ping rule to reject and rebooted just to make sure these settings are used. And I can still ping the device from the LAN side of Starlink.

**Comment by bluewavenet** [comment]
@geedsen 

> If I set to WAN zone to ACCEPT, does that basically imply no firewall?

This is a function of the firewall, not disabling it.
Set wan zone _**INPUT**_ to accept. This would only allow traffic from the private Starlink lan subnet ie your laptop to access the router from the wan side. Access to your router's lan from its wan will still be blocked.

If your router's wan had a PUBLIC ip address from Starlink then no, you would not want to do this.

> Is it just possible that these point to bugs in the version for the Xiaomi?

No. To allow just ssh you would have to set up a port forward. As I said, this is not necessary as the router wan is secured against access from the Internet by the Starlink router's nat.
This is just a very quick shortcut to give you access, yet is pretty much just as secure in this case.

**Comment by geedsen** [comment]
Still cannot access SSH via the WAND:
![image](https://github.com/user-attachments/assets/f406da29-bf43-495b-a671-d860d1bca2b8)

![image](https://github.com/user-attachments/assets/2b87152e-ddbf-409f-8f28-18f191192809)

**Comment by geedsen** [comment]
Still does not work:
![image](https://github.com/user-attachments/assets/71125c65-be2b-409e-bc7e-a4254e05efd9)

![image](https://github.com/user-attachments/assets/3c0f4fec-3bb4-49ee-9c78-3e806b552a3a)

**Comment by geedsen** [comment]
Got in! Thanks
