### ISSUE TITLE
opennds for old openwrt router

### ISSUE THREAD

**Issue by amsteen** [openNDS/openNDS#619]
I have old TP-Link TL-MR3420 v1 with latest openwrt 17 
I want to install opennds on it
After update 
I try to install opennds on it but fail

root@LEDE:~# opkg install opennds
Unknown package 'opennds'.
Collected errors:
 * opkg_install_cmd: Cannot install package opennds.
 
is there opennds ver works for old openwrt 17 ??

**Comment by bluewavenet** [comment]
@amsteen 

> I have old TP-Link TL-MR3420 v1 with latest openwrt 17

That is so old and outdated and has been discontinued for many years. It only has 4Mb Flash 32Mb ram so there is no chance whatsoever of using it.

If you want a very low budget solution, try something like the GL-iNet mt300n-v2, it can run OpenWrt 23.05.3 and the latest release of openNDS very well.
See:
https://github.com/openNDS/openNDS/issues/509

**Comment by amsteen** [comment]
Ok Thanks
I have linksys e900 ==>ram: 32mb - flash: 8mb
Is it Ok for opennds ??

**Comment by bluewavenet** [comment]
For openNDS on OpenWrt, you need:
  1. OpenWrt 23.05.4 or higher
  2. A router with a minimum of 16MB Flash and 128MB ram.
