### ISSUE TITLE
When the wan port has no network connection, no pop-up window will appear

### ISSUE THREAD

**Issue by TakinaNoa** [openNDS/openNDS#620]
The router works in routing mode, and the computer can obtain the IP address normally after connecting. However, when the wan port of the router has no network connection, no pop-up window will appear. When the wan port has a network connection, a pop-up window will appear. What can be set to allow the pop-up window to appear normally when the wan port has no network connection?

**Comment by bluewavenet** [comment]
@TakinaNoa 

>  when the wan port of the router has no network connection, no pop-up window will appear.

This is normal and expected.

The "popup" is driven by the client device. All modern client devices have a built in function called CPD (Captive Portal Detection).
On connecting, clients try to access a special web page. If there is Internet connectivity, the special web page sends pre-determined content. If the client sees some other content, it will assume it is behind a captive portal and open a stripped down browser to allow the user to log in.

Now, if the Internet is not connected, the url of the test web site will not be resolved into an ip address, so nothing happens.

> What can be set to allow the pop-up window to appear normally when the wan port has no network connection?

Nothing useful really. If you think about it, if there is no Internet, there is no point in logging in.

It is possible to configure Dnsmasq to resolve an ip address without an Internet connection. This will give you an "offline mode", forcing the portal page to appear. But this is all or nothing, even with an Internet feed, clients will not be able to access it.

Some people have tried to use this offline mode in places like museums or art galleries, but the CPD browser is deliberately restricted, so it does not work well at all. It is better to provide a normal captive portal and QR codes on the exhibits.

**Comment by TakinaNoa** [comment]
> @TakinaNoa
> 
> > when the wan port of the router has no network connection, no pop-up window will appear.
> 
> This is normal and expected.
> 
> The "popup" is driven by the client device. All modern client devices have a built in function called CPD (Captive Portal Detection). On connecting, clients try to access a special web page. If there is Internet connectivity, the special web page sends pre-determined content. If the client sees some other content, it will assume it is behind a captive portal and open a stripped down browser to allow the user to log in.
> 
> Now, if the Internet is not connected, the url of the test web site will not be resolved into an ip address, so nothing happens.
> 
> > What can be set to allow the pop-up window to appear normally when the wan port has no network connection?
> 
> Nothing useful really. If you think about it, if there is no Internet, there is no point in logging in.
> 
> It is possible to configure Dnsmasq to resolve an ip address without an Internet connection. This will give you an "offline mode", forcing the portal page to appear. But this is all or nothing, even with an Internet feed, clients will not be able to access it.
> 
> Some people have tried to use this offline mode in places like museums or art galleries, but the CPD browser is deliberately restricted, so it does not work well at all. It is better to provide a normal captive portal and QR codes on the exhibits.

Thank you for your answer
