### ISSUE TITLE
Global (opennds conf file) bandwidht control don´t work

### ISSUE THREAD

**Issue by JaimeNuup** [openNDS/openNDS#622]
I use in OpenWrt with:

My vouchers are set with ´0', so the global configuration must be the one that prevails:
`download_rate="0"
upload_quota="0"`

root@e-Nuup:~# uci show opennds
opennds.@opennds[0]=opennds
opennds.@opennds[0].faskey='3ea07ca3ba62ee634e95409134c4742e172975c8dfd9b9d56679432321ad23e8'
opennds.@opennds[0].login_option_enabled='3'
opennds.@opennds[0].themespec_path='/usr/lib/opennds/theme_voucher.sh'
opennds.@opennds[0].maxclients='200'
opennds.@opennds[0].preauthidletimeout='10'
opennds.@opennds[0].authidletimeout='1440'
opennds.@opennds[0].uploadrate='3000'
opennds.@opennds[0].downloadrate='5000'
opennds.@opennds[0].upload_bucket_ratio='1'
opennds.@opennds[0].download_bucket_ratio='5'
opennds.@opennds[0].max_download_bucket_size='50'
opennds.@opennds[0].max_upload_bucket_size='50'
opennds.@opennds[0].download_unrestricted_bursting='0'
opennds.@opennds[0].upload_unrestricted_bursting='0'
opennds.@opennds[0].ratecheckwindow='3'

But when I perform a speed test it reaches very high or very low limits in an unpredictable way.
I test set bandwidth by user in the voucher but without success.
What can I do wrong?

**Comment by bluewavenet** [comment]
@JaimeNuup 
First of all, `theme_voucher.sh` is not officially supported, and was created by a member of the community a few years ago, so there is no guarantee that it still works as intended. That said I have not heard anything about it recently.

To reiterate what was said on the OpenWrt forum, the documentation for data quotas and traffic shaping is here:
https://opennds.readthedocs.io/en/stable/traffic.html#data-quotas-and-traffic-shaping

The relevant part is also shown here:

> **Data Rate Quota Threshold**
>
> Both upload and download data rate quotas are a threshold above which traffic is rate limited using a dynamic bucket filter.
> 
> There are no additional packages required or further dependencies.
> 
> The client data rate is calculated using a moving average.
> 
> If the client’s average rate exceeds the set quota, packets will be queued using a dynamic bucket filter. This allows clients to burst at a rate exceeding the set quota for a short interval thus improving the user experience compared with a fixed ceiling rate limit.
> 
> Upload and download rate limiting is provided independently for upload and download traffic.
> 
> The configured rate quotas can be overridden on a client by client basis according to criteria determined by the FAS.
> 
> The moving average window size is equal to ratecheckwindow times checkinterval (seconds).
> 
> The default value of ratecheckwindow is 2 and is a good working setting. Increasing the value allows a longer period of bursting. Setting to 0 disables all Data Rate Quotas.
> 
> Data Rate Quotas are ideal for allowing opening of web pages and emails etc in the fastest way possible, yet preventing an individual client from monopolizing all the available bandwidth by streaming or transferring large files. 

Unlike traditional traffic shaping where if a rate ceiling is exceeded, packets will be dropped, the openNDS shaping is a **_threshold_**, above which a limited number of packets will be allowed to "burst" at the maximum possible rate before being buffered by a dynamic bucket filter. Only when the bucket filter overflows will packets be dropped.

This gives a much improved user experience, where initial traffic, such as looking at emails, loading a web page is allowed as fast as possible for a few seconds without the danger of effecting other users.

> But when I perform a speed test it reaches very high or very low limits in an unpredictable way.

Yes, the openNDS data rate quota is incompatible with and confuses traditional speed tests as it allows initial rapid bursting, followed by bucket filter buffering for rate reduction.

To monitor the achieved bandwidth you can run the `ndsctl status` command where you can see the current average data rates for individual clients as well as the entire system.

Over a period of continuous use, the average client rate will converge on the configured rate threshold.

You can also activate a fair usage policy, where if a client exceeds a set volume of traffic, their rate threshold will be reduced to a lower pre-set value.

**Comment by bluewavenet** [comment]
@JaimeNuup 
Your original question on the OpenWrt forum ie captive portal working for you with Starlink - Does openNDS work with it?
It does for numerous people that I know are using Starlink..... So you should not have a problem.
