### ISSUE TITLE
Needing something about the openNDS

### ISSUE THREAD

**Issue by Mestresdocassino** [openNDS/openNDS#626]
Hello my friend!

Let em ask you...could you install and setup for me the openNDS on my server?
I can pay you.
Thank you and waiting your feedback.

**Comment by bluewavenet** [comment]
@Mestresdocassino 
For commercial work, please submit your official "Request for Quotation", providing a detailed description of the actual service that you require.

Contact details can be found here:
https://blue-wave.net/index.php?menuselect=Contact%20Us

**Comment by Mestresdocassino** [comment]
I didnt understood how may I contact you from the link you send. Is this a whatsapp contact?
