### ISSUE TITLE
flow offload @ndsftINC counter

### ISSUE THREAD

**Issue by egboyguda** [openNDS/openNDS#628]
Error: Could not process rule: No such file or directory
Oct 02 09:00:17 rpi4b opennds[4864]: add rule ip nds_mangle nds_ft_INC meta l4proto { tcp, udp } flow offload @ndsftINC counter
Oct 02 09:00:17 rpi4b opennds[4864]:                                                             ^^^^^^^^^^^^^^^^^^^^^^
Oct 02 09:00:24 rpi4b opennds[1204]: Adding 10.0.0.95 ba:de:8c:22:a3:42 token a7554466 to client list
Oct 02 09:00:32 rpi4b opennds[5444]: Error: Could not process rule: No such file or directory
Oct 02 09:00:32 rpi4b opennds[5444]: add rule ip nds_mangle nds_ft_INC meta l4proto { tcp, udp } flow offload @ndsftINC counter
Oct 02 09:00:32 rpi4b opennds[5444]:                                                             ^^^^^^^^^^^^^^^^^^^^^^
Oct 02 09:00:47 rpi4b opennds[6313]: Error: Could not process rule: No such file or directory
Oct 02 09:00:47 rpi4b opennds[6313]: add rule ip nds_mangle nds_ft_INC meta l4proto { tcp, udp } flow offload @ndsftINC counter
Oct 02 09:00:47 rpi4b opennds[6313]:                                                             ^^^^^^^^^^^^^^^^^^^^^^
 
 
 The error message indicates that there was an attempt to add a rule in the OpenNDS service on the Raspberry Pi (rpi4b), but it failed due to a missing file or directory. This issue occurred multiple times during the log events, specifically when processing the command to add an IP rule for TCP and UDP protocols, suggesting a persistent problem with the configuration or file system related to the nds_mangle table or the nds_ft_INC rule.

**Comment by bluewavenet** [comment]
@egboyguda 
Please state the operating system and operating system version you are running on the pi.

Also state the version of openNDS you are using.

Please also show the output of `nft list ruleset`

**Comment by bluewavenet** [comment]
@egboyguda 
No response - so closing.
