### ISSUE TITLE
OpenWrt: gatewayinterface option and interface name

### ISSUE THREAD

**Issue by metaphys** [openNDS/openNDS#629]
Hi everyone and thanks you for your work! I’m running OpenWrt:
```
# opennds -v
This is openNDS version 10.3.0
# cat /etc/openwrt_release
DISTRIB_ID='OpenWrt'
DISTRIB_RELEASE='23.05.4'
DISTRIB_REVISION='r24012-d8dd03c46f'
DISTRIB_TARGET='x86/64'
DISTRIB_ARCH='x86_64'
DISTRIB_DESCRIPTION='OpenWrt 23.05.4 r24012-d8dd03c46f'
DISTRIB_TAINTS=''
```
My network interface for openNDS is configured so:
```
[…]
config interface 'jeunes'
    option device 'eth6'
    option proto 'static'
    option ipaddr '10.12.6.254'
    option netmask '255.255.255.0'
    option ipv6 '0'
    option delegate '0'
[…]
```
it is configured properly and gets an IP
```
# ip addr
[…]
8: eth6: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq_codel state UP group default qlen 1000
    link/ether bc:24:11:a6:93:1d brd ff:ff:ff:ff:ff:ff
    inet 10.12.6.254/24 brd 10.12.6.255 scope global eth6
       valid_lft forever preferred_lft forever
[…]
```
the /etc/config/opennds file states as comment to gatewayinterface option:
```
# The value may be an interface section in /etc/config/network or a device name such as br-lan.
```
I understand that I can set either jeunes or eth6 so I set:
```
option gatewayinterface 'jeunes'
```
any other option left commented
I get the following error:
```
Sat Oct  5 14:18:46 2024 daemon.notice opennds[26921]: Attempting to Bind to interface: jeunes
Sat Oct  5 14:18:56 2024 daemon.warn opennds[26921]: libopennds - [jeunes is not up - giving up for now.]
Sat Oct  5 14:18:56 2024 daemon.err opennds[26921]: Could not get IP address information of jeunes, exiting...
Sat Oct  5 14:18:56 2024 daemon.info procd: Instance opennds::instance1 s in a crash loop 11 crashes, 11 seconds since last crash
```
if i set the option to eth6 instead, it works. Am I missing something?

**Comment by bluewavenet** [comment]
@metaphys 

> I understand that I can set either jeunes or eth6 so I set:
> 
> `option gatewayinterface 'jeunes'`
> 

Your understanding is incorrect.
openNDS requires either a bridge device or a physical non-wireless interface.

Your syslog output tells you that "jeunes" does not exist.

Your `ip addr` output confirms this.

Your network config names the uci **_section_** as "jeunes", this is not the same as the interface or device name.

The default OpenWrt config would have worked with `option gatewayinterface 'br-lan'`

What are you trying to achieve?

**Comment by metaphys** [comment]
As to what I was trying to achieve: I was using the provided theme_user-email-login-basic.sh for connection. I noticed the `<med-blue>You are connected to <br>$client_zone</med-blue>` message. In my case this translated to "You are connected to eth6" so I thought it would be more informative to give nice name to my interface. But I understood when I so the `ip link` commands in the code that it wouldn’t work. 
I did understood it wrong but I think that `may be an interface section in /etc/config/network or a device name` is ambiguous because the section name in the network file is only the same as the device in the case of a bridge section. In other case (ie normal interface) it is just a way to have a nice name for a network that you can reuse in other configuration file (firewall, mwan3 and so on). So this is why it brought confusion in my case.

**Comment by metaphys** [comment]
the alternative would be to modify the file directly which I’m trying to avoid to keep things clean or to set a bridge for one interface only (openwrt in my case will just by a router for several access point behind it, this is why I don’t need a bridge).
so my suggestion would be that the comment for the option should say that it has to be a device name or that it has to be a bridge section name.

**Comment by bluewavenet** [comment]
@metaphys 

> I think that may be an interface section in /etc/config/network or a device name is ambiguous because the section name in the network file is only the same as the device in the case of a bridge section.

But that is the way it is with OpenWrt. Please feel free to bring it up this the devs there if you feel strongly enough about it.

> openwrt in my case will just by a router for several access point behind it, this is why I don’t need a bridge

You do not _**need**_ a bridge, and indeed it works just fine without one. But that is not how a standard default config in OpenWrt works.  Changing it is fine but a knock on effect is you loose the nice device name that Openwrt provides.

A consequence of this is:
> "You are connected to eth6"
