### ISSUE TITLE
How can I get the router's mac address in a remote FAS?

### ISSUE THREAD

**Issue by boluojiang521** [openNDS/openNDS#63]
dear openNDS：
       how can i get the router,s mac address in  fas-aes-https.php of remote FAS ？
  i  just notice this ：
  // Parse for variables
	foreach ($dec_r as $dec) {
		list($name,$value)=explode("=",$dec);
		if ($name == "clientip") {$clientip=$value;}
		if ($name == "clientmac") {$clientmac=$value;}
		if ($name == "gatewayname") {$gatewayname=$value;}
		if ($name == "tok") {$tok=$value;}
		if ($name == "gatewayaddress") {$gatewayaddress=$value;}
		if ($name == "authdir") {$authdir=$value;}
		if ($name == "originurl") {$originurl=$value;}
		if ($name == "clientif") {$clientif=$value;}
i need to display different results with different router‘s mac，

  thanks openNDS~！

**Comment by boluojiang521** [comment]
which value is the  touter's mac? is clientmac?

**Comment by boluojiang521** [comment]
this is my remote FAS’s response ：
https://xxxxx.com/nds/fas-aes-https.php?fas=cmRXbFFQU0RGQXRuTHZhME8yOXExZUdtK1lsWllKNm5tN0NTRVFkKzJidFdYNmU4ZGUrekxQZk1KVy9ibDFmYnZyMEVWK1ladURpd3hTUFNuaU95aWQyZWd2MUFab0Q5YXU1ODR3WlB6R0g1ekdqSTZFYXZ1ZnBNNk1WL1FkRW1qL3E2MXFNZzRRWjZBTzVOWDR4dGFUVGRIMTZhS1ZOU0Y4di8xL0tBNWp2MmVOdUh2c01uZ3ZSNExEWEFQSzZ1b1RPZkk3ZFhIMnRnclpWR3lpaEh1WnkrYVl5QmNHbXQvVVRUUWR3dFhNcnRyR2hIaUd3WEZZT0g0RTZTQWFKcVVuYWE4NytsTHNvYlVTTXgzakNCVjc1bXEra0daSnI5L3NTVXd5aS9GdWMvSmhMNUx3M2NpcnNwdHd1R0gySkU=&iv=69182ad984c14f87

**Comment by bluewavenet** [comment]
@boluojiang521 

> How can I get the router's mac address in a remote FAS?

You can't as it is not sent to the FAS. FAS does not need to know the the router mac address to verify the credentials of a client, and as most routers have at least 2 mac addresses, which one would be sent?

> i need to display different results with different router[s]

The variable "gatewayname" is provided so the FAS can identify the requesting gateway.
Typically, gatewayname will be configured with an identifier string, eg the location. _This is done in the openNDS config._

For example if gatewayname is set to "Bar Boluojiang - Main Street - MyTown", the FAS will know to serve the login pages for Boluojiang's Bar on Main Street.

The variable "gatewayname" can be set to anything you like. This is much more flexible than using a router mac for identification. For example, groups of openNDS gateways can be identified using your chosen gatewayname format.

> which value is .. clientmac?

clientmac is the mac address of the client device that is trying to log in. eg the mac address of your phone.

**Comment by boluojiang521** [comment]
thanks for your help；

   i have notice this in local splash.html:

Available variables:
	error_msg: $error_msg
	gatewayname: $gatewayname
	tok: $tok
	redir: $redir
	authaction: $authaction
	denyaction: $denyaction
	authtarget: $authtarget
	clientip: $clientip
	clientmac: $clientmac
	clientupload: $clientupload
	clientdownload: $clientdownload
	gatewaymac: $gatewaymac
	nclients: $nclients
	maxclients: $maxclients
	uptime: $uptime
, i have notice $gatewaymac, this is my want。

If I can get a fixed MAC address of the router through remote FAS, it means that I can directly read out the MAC address and use it directly. Is the gateway name you said does not need to be manually set to belong to the original fixed router?

**Comment by boluojiang521** [comment]
So, how can I get router identification code in remote Fas without manual setting?

**Comment by bluewavenet** [comment]
@boluojiang521 

> can i get $gatewaymac at remote FAS

As I mentioned above - No, not directly.

> I want to get router identification code in remote Fas without manual setting

You could write a simple bash script that runs on the first boot of the router - install this at the same time as you install openNDS.
This script would generate an identity code based on a mac address and place it in the openNDS config (using uci on OpenWrt or sed on generic Linux).

Alternatively I _could_ add gatewaymac to the data sent to FAS for the next version (coming soon). _**Convince me ;-)**_

> splash.html JS code

As we have discussed previously, it is the client CPD that triggers captive portals.
It is the standard for CPD to prohibit most javascript code, as, on a captive portal, it is regarded as a severe security risk.
There is no guarantee that any js code you embed in the splash page will be able run correctly or even run at all. Whatever result you get will also depend very much on the vendor implementation of the CPD. So this approach is not feasible.

**Comment by bluewavenet** [comment]
@boluojiang521 
In version 7.0.0beta, gatewaymac is now added to the encrypted query string for fas_secure_enabled levels 2 and 3
Version 7.0.0 release will follow in a few days.

**Comment by boluojiang521** [comment]
thanks bluewavenet

**Comment by bluewavenet** [comment]
@boluojiang521 
v7.0.1 is now released.

**Comment by bluewavenet** [comment]
@boluojiang521 
The 7.0.1 versions of fas-aes and fas-aes-https both show how to retrieve the gateway mac address.
