### ISSUE TITLE
OpenWrt: Dnsmasq reload failed!

### ISSUE THREAD

**Issue by metaphys** [openNDS/openNDS#630]
Hello everyone and thank you for this software!
each time I start or restart opennds it complains in the log with: `Dnsmasq reload failed!`
but dnsmasq configuration works when restarted alone or after restarted by opennds. and so does the captive portal. Is that normal?

I’m working with a minimal change to opennds config:
```
opennds.@opennds[0]=opennds
opennds.@opennds[0].login_option_enabled='3'
opennds.@opennds[0].themespec_path='/usr/lib/opennds/theme_click-to-continue-basic.sh'
opennds.@opennds[0].dhcp_leases_file='/tmp/dhcp.leases.jeunes'
opennds.@opennds[0].gatewayinterface='eth6'
opennds.@opennds[0].faskey='987……81d'
```
and minimal dnsmasq (that’s before starting opennds):
```
dhcp.@dnsmasq[0]=dnsmasq
dhcp.@dnsmasq[0].domainneeded='1'
dhcp.@dnsmasq[0].leasefile='/tmp/dhcp.leases.jeunes'
dhcp.@dnsmasq[0].address='/status.client/10.12.6.254'
dhcp.jeunes=dhcp
dhcp.jeunes.interface='jeunes'
dhcp.jeunes.start='100'
dhcp.jeunes.limit='150'
dhcp.jeunes.leasetime='12h'
```

**Comment by bluewavenet** [comment]
@metaphys 
You will have to share your network and firewall configs for this.

Note that "interface" in dnsmasq relates to the OpenWrt firewall zone, so unless you have defined a jeunes zone in the firewall, you should expect dnsmasq to error on startup......

**Comment by metaphys** [comment]
I do have jeunes zone in firewall and jeunes section in network.
Let me go back to you on that I want to set up a test environment to get rid of all specific settings
