### ISSUE TITLE
I want to proxy authenticated traffic to access the Internet. How do I change the nftable rule?

### ISSUE THREAD

**Issue by bf30075** [openNDS/openNDS#631]
Where should I start, I see rules like nds_mangle table ndsOUT
`chain ndsOUT {
		ip saddr 192.168.8.104 ether saddr 4e:78:ca:2a:8f:29 counter packets 1839 bytes 222085 meta mark set meta mark | 0x00030000
	}`
 I have a working proxy working on 127.0.0.1:12345. 
I was trying to proxy the traffic using something like tproxy, but it doesn't work.

**Comment by bf30075** [comment]
Here's what I did.

ip rule add fwmark 99 table 100 
ip route add local 0.0.0.0/0 dev lo table 100
nft add chain ip nds_mangle Proxy
nft add rule ip nds_mangle Proxy ip daddr 127.0.0.1 counter return
nft add rule ip nds_mangle Proxy ip daddr 224.0.0.0/4 counter return
nft add rule ip nds_mangle Proxy ip daddr 255.255.255.255 counter return
nft add rule ip nds_mangle Proxy meta mark 0x30000 udp dport 12345 counter tproxy to 127.0.0.1:12345 mark set 99
nft add rule ip nds_mangle Proxy meta mark 0x30000 tcp dport 12345 counter tproxy to 127.0.0.1:12345 mark set 99
nft add rule ip nds_mangle ndsPRE counter jump Proxy

**Comment by bluewavenet** [comment]
@bf30075 
Support for proxy in openNDS is deliberately not included as it can be used to violate the privacy of users, contrary to law in most countries.
