### ISSUE TITLE
OpenNDS on multiple VLANs

### ISSUE THREAD

**Issue by AdithyaVarmaG** [openNDS/openNDS#636]
I am running openNDS on a VM which is acting as a router. This VM is configured with multiple VLANs with each VLAN having separate Gateway and Subnet. openNDS configuration is allowing only single gateway interface option. To work with multiple VLANs/ multiple gateways, what is the best solution? 

1. Can we run multiple instances of openNDS by having separate config file? Is it a simple modification in the code (or) will it add more complexity?
2. How about Containerization of openNDS? Is this a clean solution assuming there is no resource constraint?

Or is there any alternate way to achieve this?

Thank you!

**Comment by bluewavenet** [comment]
@AdithyaVarmaG 

> openNDS configuration is allowing only single gateway interface option

Only one instance of openNDS is allowed. OpenNDS is a dynamic firewall. Supporting multiple instances would be unnecessarily complex so has not been implemented.

> Containerization of openNDS?

You would need a separate VM for each instance of openNDS. This is of course doable but is, once again, very complex and possibly will result in numerous unknown issues, so would not be recommended.

> Or is there any alternate way to achieve this?

The question I ask is why are you even bothering with a VM in the first place?

The obvious, simple, reliable and low cost solution is to buy a number of dedicated router hardware boxes and put OpenWrt/openNDS on each one.

You can purchase these for as little as $30 each. Then there will be no constraints or limitations at all with a very simple configuration. In addition, a single Internet hosted FAS server can handle hundreds of these over many locations if required.

**Comment by AdithyaVarmaG** [comment]
Thanks for the quick response. Appreciate it.

> The question I ask is why are you even bothering with a VM in the first place?

We cannot install the openNDS in each wifi router. So, the requirement is to run it in the central place and listen on all interfaces.

**Comment by bluewavenet** [comment]
@AdithyaVarmaG 

> We cannot install the openNDS in each wifi router.

What do you mean by a "wifi router"? Do you mean a "router style" device configured as a cable connected access point with only bridging between wireless and ethernet?

My current understanding of your requirement does not make sense. It looks like you are using your central server as a lever to justify having unnecessary vlans connecting to access points but now find you cannot run openNDS on either the access points or central server's vlans.

You are going about this in a way that maximises complexity and have now encountered an unsolvable technical issue. 

**Step back for a minute. Describe what you are trying to do as an overview.** 

Is this an academic exercise, or is it for development of a real system providing public wireless?

**Comment by AdithyaVarmaG** [comment]
Hi @bluewavenet By wifi router, I am referring to the WAP. May be I conveyed it wrong. The openNDS can be installed on the central Server. The goal is to have a public Wi-Fi network (likely in a community setting) where different user groups can connect to the network, authenticate via this portal and access the internet. I may have over complicated the VLAN thing. But the idea is to differentiate user groups. I got your point on having a simple hardware and get openNDS installed on it. 

You can close this ticket for now.
