### ISSUE TITLE
Improve Error reporting when remote FAS is fails during auth_get command

### ISSUE THREAD

**Issue by d1dee** [openNDS/openNDS#638]
### **Description**

Current libopennds.sh implementation does not explicitly handle reporting errors returned by remote FAS server during auth_get. As a result, any issues during execution, such as timeouts or network failures, may go unnoticed or be difficult to debug. I propose enhancing the script to capture and handle errors effectively, providing clearer diagnostics and improving its robustness.

### **Current Implementation**

The current script assigns the output of the uclient-fetch command to a variable and checks the exit status. However, error details from uclient-fetch are not captured or displayed:

```
retval=$($wret -O - -U "\"$user_agent\"" "$url?auth_get=$action&gatewayhash=$gatewayhash&payload=$payload")
status=$?

```
## **Proposed Fix**

Modify the script to capture both standard output and error messages from uclient-fetch using 2>&1. Explicitly check the exit status and display error details when the command fails:

```
retval=$($wret -O - -U "\"$user_agent\"" "$url?auth_get=$action&gatewayhash=$gatewayhash&payload=$payload" 2>&1)
status=$?

if [ $status -ne 0 ]; then
    echo "Error: FAS fetch failed with status $status."
fi

```

**Comment by bluewavenet** [comment]
@d1dee 
That was the original intention and is still a good idea. The error message should be sent to syslog though.
See function write_to_syslog().

Do feel free to open a PR where it can be reviewed properly.

**Comment by d1dee** [comment]
I have opened a PR with the suggested changes, kindly review.
