### ISSUE TITLE
FAS Secure 3 not working

### ISSUE THREAD

**Issue by mrbluecoat** [openNDS/openNDS#64]
I have a working openNDS installation using the default setup (click button to access Internet).

I then enabled FAS Secure 3 with these settings:

```
cat >> /etc/opennds/opennds.conf <<EOF
fasport 2050
faspath /fas-aes-https.php
fasremoteip 10.20.30.40
fas_secure_enabled 3
faskey 1234567890
EOF
```
PHP Version => 7.3.19-1~deb10u1
OpenSSL Library Version => OpenSSL 1.1.1d  10 Sep 2019
Native OpenSSL support => enabled

Chrome gave me the generic "This site can’t be reached" and I got this notice in the log

```
PHP Notice:  Undefined variable: response in /usr/lib/opennds/post-request.php on line 35
```

As well as this log:

```
NDS-Library[7249]: iw utility not available
NDS-Library[]: iw utility not available
[7035](src/util.c:94) Failed to get client connections - client probably offline
```

I'm planning to use OpenNDS for a wired network (no Wi-Fi) so perhaps this mode isn't supported?

**Comment by mrbluecoat** [comment]
An `apt install iw` gets me a step closer but now getting `nl80211 not found`

**Comment by bluewavenet** [comment]
@mrbluecoat 
I'm on UTC +1 tome zone and don't have time this evening to look at this so will look at it tomorrow.
However be aware FAS level 3 is not supported on private ip address ranges as it depends upon valid https certificates being available on the FAS server.

**Comment by mrbluecoat** [comment]
I changed `/usr/lib/opennds/get_client_interface.sh` and `/root/openNDS-6.0.0/forward_authentication_service/libs/get_client_interface.sh` to:

```
#!/bin/sh
echo "eth0 eth1"
exit 0
```
and rebooted. Here's the OpenNDS status:

```
systemctl status opennds
[476](src/util.c:235) Attempting to Bind to interface: eth1
[476](src/util.c:242) Interface: eth1 is not yet ready - waiting...
[476](src/main.c:322) Interface eth1 is up
[476](src/main.c:337) Interface eth1 is at 10.20.30.40 (3a:9f:59:3d:ad:d1)
[476](src/main.c:377) Created web server on 10.20.30.40:2050
[476](src/main.c:378) Handle [-465505456]
[476](src/main.c:457) SSL Provider is active
[476](src/main.c:504) FAS URL is https://10.20.30.40:2050/fas-aes-https.php
[476](src/main.c:576) Forwarding Authentication is Enabled.
[476](src/fw_iptables.c:374) Initializing firewall rules
```
Browser message:
```
This site can’t be reached http://example.com/ is unreachable.
ERR_ADDRESS_UNREACHABLE
```
No errors in the journalctl or PHP logs.  Thoughts?

**Comment by mrbluecoat** [comment]
Just saw your note. Thanks. I'll close and review other options.

**Comment by bluewavenet** [comment]
@mrbluecoat 
To clarify: Level 3 enforces https protocol so requires valid FAS server TLS certificates, but with a private ip address range you will either have self signed certs. or an ip address mismatch, resulting in dire security errors/notifications in browsers. It will function but scare away most users.

Potential problems with your config (other than the https errors):

**Problem 1**
`[476](src/main.c:337) Interface eth1 is at 10.20.30.40 (3a:9f:59:3d:ad:d1)`

In my experience of helping rpi users on raspbian/debian, many inexperienced people have not configured their pi correctly as a router. This is usually indicated by a lan address not being x.x.x.1 or x.x.x.254. This is only a convention but any other address is a red flag to me. Your address of 10.22.30.40 could be perfectly ok but worth checking you have met the prerequisites, here - https://opennds.readthedocs.io/en/stable/install.html#prerequisites

**Problem 2**
`[476](src/main.c:377) Created web server on 10.20.30.40:2050`

This is the openNDS libmicrohttpd web server starting up on the gateway address and default port.
But:
`[476](src/main.c:504) FAS URL is https://10.20.30.40:2050/fas-aes-https.php`

This is using the same ip/port as openNDS/libmicrohttpd _http_ web server, so is invalid. FAS at any level (except the special case of Preauth), requires a separate web server supporting php-cgi.

**Comment by bluewavenet** [comment]
@mrbluecoat 
The iw issue and php notice could be Linux version compatiblity issues (most testing is done on OpenWrt).
I will look into this. Thankyou for the logs!

**Comment by bluewavenet** [comment]
@mrbluecoat 
iw and php notice both fixed in upcoming new release.

**Comment by mrbluecoat** [comment]
Thanks @bluewavenet 

You are correct - our use case is using self-signed certs

10.20.30.40 is purposely chosen as a gateway with a corresponding DHCP range from 10.20.30.50 to 10.20.30.200 but you're right *.1 is most typical.

I'll check on **Problem 2**, good lead
