### ISSUE TITLE
Question: Client Deauthentication Based on External Factors (FAS 3 and 4) possible?

### ISSUE THREAD

**Issue by d1dee** [openNDS/openNDS#640]
Is there a way to trigger a notification to AuthMon when a device needs to be deauthenticated as part of FAS 3 and 4 functionality? I’m aware of the existing methods that rely on usage and time limits, but I am looking for a solution that triggers deauthentication based on external factors, beyond just usage metrics.

I’m currently working on a client controller and need a way to dynamically deauthenticate clients, regardless of their usage

**Comment by bluewavenet** [comment]
@d1dee 
A fas should be able to send a deauth at any time, perhaps triggered by an admin command.
But I do not see why you would want to.
Can you give some reasoning?

**Comment by d1dee** [comment]
A good example would be to maintain usage quotas over multiple devices. This would require a way for FAS to notify nds about such and trigger deauth when necessary.

**Comment by bluewavenet** [comment]
@d1dee 
But usage quotas are already maintained over multiple devices...
Fas sets those quotas when the client logs in and it can be different for every client, determined by the fas using any criteria you choose to code in, such as previous usage etc.
I'm just trying to understand your usage case.

**Comment by d1dee** [comment]
While it is true that usage quotas and other policies can be set at the time of user authentication, the specific use case I am working on requires the ability to deauthenticate clients based on factors that may arise after authentication and could not have been anticipated at login.

In such cases, the FAS would need to notify openNDS to trigger deauthentication dynamically, regardless of the predefined quotas or policies at the time of login. 

Does openNDS currently have a mechanism to support such dynamic notifications from FAS, or would this require a new extension to the system?

Thank you for your continued support @bluewavenet

**Comment by bluewavenet** [comment]
@d1dee 

> the ability to deauthenticate clients based on factors that may arise after authentication and could not have been anticipated at login.

And an example of these factors would be....?

> Does openNDS currently have a mechanism to support such dynamic notifications from FAS

Yes.

> would this require a new extension to the system?

No.

I cannot think of a need but you would tell fas to tell opennds through an admin page on the fas server perhaps.

Maybe what you want is already there, but you have still not indicated what the requirement actually is.

**Comment by d1dee** [comment]
My use case is to set a usage limit that spans multiple devices. For example, a user with 20 GB should be able to use it across a laptop (e.g., watching a movie) and a phone (e.g., basic browsing). Since usage varies by device, I want the ability to deauthorize users based on their combined device usage (e.g 18 GB on the laptop and 2 GB on a smartphone which would add up to 20GB ).

And for clarification by FAS I meant a remote FAS server

**Comment by bluewavenet** [comment]
@d1dee 
This does imply that you are charging for the service, for your own financial gain either directly or indirectly. If so it is up to you entirely to figure this out for yourself, or pay someone else to do it for you.

Normally, where data volumes detract from other users, you would configure the opennds fair usage policy.
https://opennds.readthedocs.io/en/stable/config.html#set-fair-usage-policy-throttle-rate

**Comment by d1dee** [comment]
I wanted to confirm if this feature is already implemented before I begin working on it. Additionally, would a pull request introducing tighter coupling with a remote FAS server be acceptable?

**Comment by bluewavenet** [comment]
@d1dee 
PRs are always welcome for review and consideration.

**Comment by d1dee** [comment]
Thank you I'll proceed with exploring the implementation and submit a PR.
