### ISSUE TITLE
Run OpenNDS without dnsmasq

### ISSUE THREAD

**Issue by PrasadKosanam** [openNDS/openNDS#642]
Hi @bluewavenet 

I am trying to migrate from nodogsplash to opennds. I see that there is a dependency on the dnsmasq library. So, the question "Can we run openNDS without dnsmasq installed on the device?" I wanted it to run independent to dhcp server. 

Thankyou!

**Comment by bluewavenet** [comment]
@PrasadKosanam 

> "Can we run openNDS without dnsmasq installed on the device?"

No.

OpenNDS _**requires**_ the Dnsmasq dhcp server to be running on the openNDS router and is closely integrated with it.

It does this for security reasons. For example, a rogue dhcp server could be used as part of a MITM attack.
