### ISSUE TITLE
session start issue

### ISSUE THREAD

**Issue by diegotg97** [openNDS/openNDS#8]
hi, hope you all doing well!
im facing a wierd issue using NDS on GL-MT300N-V2

binauth is enable, the script is getting the parameters but those are really out of sight

eg.
`Sun May 10 00:03:09 2020 Executing command: /root/run.sh idle_deauth 48:4b:aa:92:fb:af 499504 62102 6825301027524656607 `18613409008320512`

as you may notice, session start and session end are not correct, the correct input will something like "1588731573" or some similar values.
FYI, in my rpi i have the same set up and it works normal.

actual set up:
ROUTER: GL-MT300N-V2
VERSION: OpenNDS 5.0.1

config:
  config OpenNDS
   #Set to 0 to disable OpenNDS
  option enabled 1

  #This hook is needed as a restart of Firewall overwrites OpenNDS iptables entries.
  option fwhook_enabled '1'
 
  option gatewayinterface 'br-lan'
  option maxclients '250'

  option fasremoteip xx.xx.xx.xx.xx
  option fasport 80
  option fasremotefqdn fqdn.com
  option fas_secure_enabled 2
  option gatewayname xxx-xxxx-x
  option RedirectUrl google.com
  option faskey 1234567890
  option binauth '/root/run.sh'
  option redirecturl 'https://www.google.com/'
  option authidletimeout '22'
  option use_outdated_mhd '1'

  option preauthidletimeout '30'
  option sessiontimeout '1200'
  option checkinterval '600' 

i just put the relevant things

thanks in advance!

**Comment by bluewavenet** [comment]
@diegotg97 @richyxi
I installed on an MT300N-v2 with BinAuth and found the same issue.
The problem was a bug introduced way back when v3.0.0 was released. session_start and session_end are obviously not often used until now!
It is now fixed in master as v5.0.2beta and will be released soon.
I can upload a beta .ipk if it would be useful for you.

**Comment by richyxi** [comment]
yeah, it will be very usefull!
thanks for the support!

**Comment by diegotg97** [comment]
Thank you Rob!!

**Comment by bluewavenet** [comment]
@richyxi @diegotg97 
The beta .ipk can be downloaded here:
https://github.com/openNDS/openNDS/blob/master/testing/2020-05-14-07:18/opennds_5.0.2beta-1_mipsel_24kc.ipk

**Comment by diegotg97** [comment]
Thank you very much wise Rob!!!!!!!! @bluewavenet

**Comment by bluewavenet** [comment]
@diegotg97 
Never mind the compliments, get testing! ;-)

**Comment by bluewavenet** [comment]
@diegotg97 
This is fixed in v5.1.0beta
New release to follow as soon as I update the documentation! ;-)

**Comment by bluewavenet** [comment]
@diegotg97 @richyxi 
Version 5.1.0 is now released.
https://github.com/openNDS/openNDS/releases/tag/v5.1.0

The OpenWrt build system is working its way through all the platforms as I write - it usually takes a couple of days to complete.
However you can download the ipk for the Gl-iNet MT300N-v2 here:
https://github.com/openNDS/openNDS/releases/download/v5.1.0/opennds_5.1.0-1_mipsel_24kc.ipk

**Comment by richyxi** [comment]
Thank you very much Rob, we highly appreciate!
thank you for your time!!
