### ISSUE TITLE
How to Access Remote Resources from Preauth

### ISSUE THREAD

**Issue by stellarbnb** [openNDS/openNDS#81]
Hi Rob,
I have a question, using preauth method is validating the users using the radius server instead of using the local database(userlist.dat file) possible?. This is my requirement next

**Comment by bluewavenet** [comment]
@stellarbnb 
As you are probably aware, PreAuth is a local implementation of FAS that uses the openNDS built in web server (MHD) to serve the login page to the client.

PreAuth calls a local program or script to dynamically generate html for MHD to serve. The default local program is actually the login.sh "bash" script.

Although the client does not initially have access to the Internet, the router that openNDS is running on does.

**Therefore it follows that any external resources available to the router are also available to PreAuth.**

If you can write a "bash script" "compiled C program" "PHP script" "Python script" etc etc to access your remote Radius server, then the answer to your question is yes, it is possible for PreAuth to access a radius server.

However you have stated elsewhere that you do not want to install any extra packages on your router, so you are limited to a bash script or compiled executable.

**PreAuth accessing a radius server will be insecure** as  client credentials are passed from the client to PreAuth in clear text in a manner that can easily be snooped.

As I have stated before, you will be much better off using an Internet hosted **https** FAS web server where openNDS enforces encryption on all client/FAS communication.

**Comment by stellarbnb** [comment]
Hi Rob, 
Sure rob, I still need to accomplish captive portal working this remote webserver and radius server. I'll choose appropriate resources to attacin security based on the requirements and the captive portal will be used inside the corporate enterprise network. I did user validation previously with the local database(user list). Currently, I'm looking to validate the users from my preauth script (login.sh) against the free radius serve. Can you suggest to me some resources to achieve this radius authentication part from my preauth script?

**Comment by bluewavenet** [comment]
@stellarbnb 
In my opinion, radius is really a legacy "system" and I would be very reluctant to create a new system using it. Sure, if you are forced to because of the existence of a corporate radius, but otherwise I cannot see any advantage in going that way.
This is my opinion developed over many years and I could be wrong - you will have to do your own research.

libradcli library might be of use. It is available as an OpenWrt package but I know nothing about it.

**Comment by stellarbnb** [comment]
Okay rob, thank you.

**Comment by NagConnectus** [comment]
Hi Rob,
Is opennds webserver serve splash pages over https? I'm using preauth method with customized login.sh with username and password, so is there any chance to sniff username and password over air?. Since captive portal managed network will be open network.

**Comment by stellarbnb** [comment]
Hi Rob,
Is opennds webserver serve splash pages over https? I'm using preauth method with customized login.sh with username and password, so is there any chance to sniff username and password over air?. Since captive portal managed network will be open network.

**Comment by bluewavenet** [comment]
@stellarbnb 

> [Can] opennds webserver serve splash pages over https?

**NO!**

> using preauth method .....is there any chance to sniff username and password over air?

**YES!**

Please re-read this comment I made on 23rd October:
https://github.com/openNDS/openNDS/issues/66#issuecomment-715247792

I am always willing to help - but **_this question has been discussed on numerous occasions_**. 

**_Level 3 is REQUIRED for a FULLY SECURE system._** 

Levels 1 and 2 are intended for stand alone captive portals at public venues (Free WiFi) where user contact information and acceptance of terms of service are legally required. The credentials, if any, collected at a Public Free WiFi generally do not need to be secured, but the captive portal must not be bypass-able.
