### ISSUE TITLE
Opennds FAS with external FAS issues

### ISSUE THREAD

**Issue by DheerajTecheureka** [openNDS/openNDS#83]
I wanted to work on raspberry pi 3b+ and its my first project on raspberry. I am using my raspberry as a hotspot and have connected my airtel router via data cable to my raspberry for Internet access. I wanted to create a captive portal using nodogsplash or opennds. I don't want only continue button. I want to verify my client mobile number before authentication. Where my verification process is located remotely on http server and which is in php language. Is it possible ir not?
I wanted to replace opennds_preauth with my remote server. Please guide me what changes i need to do with my .conf file and splash page or any another changes i need to do. Please answer me.

**Comment by DheerajTecheureka** [comment]
I need to change router setting in openwrt if yes then plz give me steps what changes i need to do.
I have try this with nodogsolash several time bt it has not possible then simply i called the iframe and collect the mobile number bt it is not professional and for this process i have to provide authentication first bt my maine moto to provide internet to client is collecting verify mobile number.my old mobile is giving success msg after authentication.before this i istalled opennds insted of nodogsplash bt i am not getting what changes i need to do with

**Comment by sicelo** [comment]
> Is it possible ir not?

Yes it is possible. You can follow the FAS chapter in the documentation, and ask here if you run into issues

**Comment by bluewavenet** [comment]
@DheerajTecheureka 
Please state:

 1. The operating system you are using (eg Rasbian, OpenWrt etc)
 2. The operating system version
 3. The version of openNDS you are using.

The documentation is here:
https://opennds.readthedocs.io

> my verification process is located remotely on http server and which is in php language

It will be a simple matter of adding a custom FAS php script, but first it is sensible to make sure the basic openNDS system is working correctly.

**Comment by DheerajTecheureka** [comment]
I am using raspbian version 5.4 and openNDS version 7.0.1
OpenNDS not giving any error bt i am unable to connect internet i got client mac address and token and ip in terminal bt i am not getting authentication msg on terminal.

**Comment by bluewavenet** [comment]
@DheerajTecheureka 
You can see the current status of openNDS with the command:
`sudo ndsctl status`

You can view the service logging using the command:
`sudo systemctl status opennds`

And you can see any error logs using the command:
`sudo journalctl -e`

> i got client mac address and token and ip in terminal

Where did you see this? Nothing should be reported directly in a terminal.

> i am not getting authentication msg on terminal.

You will not see any message on a terminal. You need to use the commands I mentioned above.

I am assuming you followed the instructions in the documentation:
https://opennds.readthedocs.io/en/stable/compile.html#linux-unix-compile-in-place-on-target-hardware

Note however that if you had previously installed NoDogSplash, you must remove it first.

**Comment by DheerajTecheureka** [comment]
I took plain os raspbian5.4.79 then
 i have created access point then 
untar the libmicrihttpd source file0.9.71 then download opennds v7.0.1
Change opennds.conf file faspath /opennds/fas.aes.php
GatewayInterface wlan0
GatewayAddress 192.168.4.1
Then
Login option enabled 0
Faspath /opennds/fas-aes.php
GatewayInterface wlan0
Gateway adress 192.*.*.*

Terminal response after sudo opennds

Created web server on192.*.*.*
Fas url is http://static ip:2050/nodog/fas.php
Forwarding authentication is enable
initialization firewall ruleS
Adding client ip address
 Client mac adrees theb token

**Comment by bluewavenet** [comment]
@DheerajTecheureka 
Unfortunately you are misinterpreting the documentation.

> Terminal response after sudo opennds

This is not the correct way to start openNDS.
Instead use (as in the documentation):
`sudo systemctl start opennds`

Another problem:
>  GatewayAddress 192.168.4.1

GatewayAddress is found automatically by openNDS and should not be set in the config file. (**you seem to be following an online tutorial** ... I did say most of these are outdated and incorrect)

Here is an extract from the opennds.conf file:
```
# Option: GatewayAddress
#
# Deprecated
#
# Default: Discovered from GatewayInterface
#
# It need not and probably should not be specified.
# If set here, it must be set to the IP address of the router on
# the GatewayInterface.
#
# Setting may result in failure of openNDS to start automatically at boot time
# Setting incorrectly will result in failure of openNDS.
#
###########################################################################################


```

Apart from openNDS probably not starting correctly you have set "faspath" without any of the other required parameters.
> faspath /opennds/fas.aes.php

In addition, you do not say if you have installed the additional dependencies required for running fas-aes.

I do understand there my be a language difficulty here, but you must read the documentation.
For running fas-aes on either a local or remote FAS server, see:
https://opennds.readthedocs.io/en/stable/fas.html#example-script-file-fas-aes-php

**The best approach** is to first get openNDS working in its default mode, that is, just a click to continue.
Then move on to configuring your FAS server.

Let me know how it goes ;-)

**Comment by DheerajTecheureka** [comment]
Sir can you share me a link for creation of access point on raspberry pi 3b+ because i have tried it several times bt it not working if i not entered gateway address in .conf file i am getting popup box of no internet and if i set gateway address then i got continue button page bt not getting connectivity. 
Sir i am referring https://opennds.readthedocs.io
For installation of opennds

**Comment by bluewavenet** [comment]
@DheerajTecheureka 
Your pi 3b+ needs to be configured as a wireless router and not configured as a wireless access point.

As a wireless router, the wireless interface will be the local area network (LAN) gateway.

The wireless interface will be the default IP gateway for the LAN and will provide DHCP and DNS for client devices.

The ethernet port will provide the wide area network (WAN) connection and will be an DHCP client, obtaining its IP address from the upstream (Internet feed) router.

The IP address subnet for the LAN must be different to the IP address subnet of the WAN.

I do not have any information on how to configure Raspbian for this on a pi 3b+ as i do not have one.

> i am referring https://opennds.readthedocs.io for installation of opennds

If this is the case, after a reboot, please show me the output of:
` sudo systemctl status opennds`

and

`sudo ndsctl status`

**Comment by DheerajTecheureka** [comment]
Sry sir bt i dont want LAN connection i have separate 4g router simple airtel router i want to create my raspberry as access point. I will share you my opennds status at evening.

**Comment by sicelo** [comment]
The 4G router is the WAN. The network through which your other devices connect to the RPi is the LAN

**Comment by bluewavenet** [comment]
@DheerajTecheureka 

openNDS is designed to run on a device configured as an IPv4 router.
**Please read the documentation!** 
https://opennds.readthedocs.io/en/stable/install.html#prerequisites

It is quite simple to configure the Pi as a router but I cannot help you with the specifics for a Pi 3b+ as I do not have one.
You will need to do a little research to find out. 
Once you have the pi running correctly as a router you can progress to openNDS configuration.

**Comment by DheerajTecheureka** [comment]
Thanks sir i have done with my project. Can you share me a one thing how can run opennds and node.js both at boot time

**Comment by DheerajTecheureka** [comment]
Sry i wanted to run 3 different platform files at boot time can i call them in rc.local if yes then how? Files are .js second is .py and third is opennds

**Comment by bluewavenet** [comment]
@DheerajTecheureka 
If you had **_followed the documentation_** then you would find openNDS is started at boot time!

To clarify some basics:
1. openNDS is designed to run in the background as an operating system service.
2. node.js and Python are script interpretor libraries that are installed once to be always available. They both run only when called.

If you want to run a Javascript or Python program at boot time then adding something to rc.local would work. You would need to **_read the Node and Python documentation_** to find out how.

**Comment by DheerajTecheureka** [comment]
K sir
