### ISSUE TITLE
Traffic control always "no"

### ISSUE THREAD

**Issue by sicelo** [openNDS/openNDS#84]
Hi

I wonder about openNDS always showing "Traffic control: no". I have enabled SQM following instructions in the documentation. 

```
==================
openNDS Status
====
Version: 5.2.0
Uptime: 8h 26m 29s
Gateway Name: myWifi
Managed interface: br-lan
Managed IP range: 0.0.0.0/0
Server listening: http://192.168.1.1:2050
Binauth Script: /www/nds/v2/binauth_log.sh
Preauth: Disabled
FAS: Secure Level 2, URL: http://192.168.1.1:2080/nds/v2/home.php
Client Check Interval: 2s
Preauth Idle Timeout: 10m
Auth Idle Timeout: 60m
Traffic control: no
...
```
sqm config:
```
root@OpenWrt:~# cat /etc/config/sqm 

config queue 'eth1'
        option qdisc_advanced '0'
        option enabled '1'
        option interface 'br-lan'
        option download '1000'
        option upload '3000'
        option debug_logging '0'
        option verbosity '5'
        option qdisc 'cake'
        option script 'piece_of_cake.qos'
        option linklayer 'atm'
        option overhead '44'
```
Perhaps there is something I misunderstood, and will be happy to be nudged in the right direction.

**Comment by bluewavenet** [comment]
@sicelo 
Well spotted :-D
This was carried forward from the broken traffic control of NoDogSplash on the basis it would be reinstated one day.
This was done in version 7.0.1, when global and client quotas were introduced.
A typical output from `ndsctl status` now begins with:

```
==================
openNDS Status
====
Version: 7.1.0beta
Uptime: 7s
Gateway Name: openNDS on OpenWrt
Managed interface: br-lan
Managed IP range: 0.0.0.0/0
Server listening: http://10.248.1.1:2050
Binauth: Disabled
Preauth: Disabled
FAS: Secure Level 1, URL: http://10.248.1.1:5080/cp/fas-hid.php
Client Check Interval: 600s
Rate Check Window: 2 check intervals (1200s)
Preauthenticated Client Idle Timeout: 30m
Authenticated Client Idle Timeout: 120m
Download rate limit (default per client): no limit
Upload rate limit (default per client): no limit
Download quota (default per client): no limit
Upload quota (default per client): no limit
Total download: 1 kByte; avg: 1.41 kbit/s
Total upload: 1 kByte; avg: 2.24 kbit/s
====
Client authentications since start: 0
Current clients: 0
====
Blocked MAC addresses: none
Allowed MAC addresses: N/A
Trusted MAC addresses: none
Walled Garden FQDNs:
  fbcdn.net
  facebook.com
Walled Garden Ports: none
========
   .
   .
   .
```
openNDS quotas do not replace the use of SQM, but work with it if available.

**Quotas/Limits are session based**, temporarily blocking or deauthing a client when they exceed a quota.
Different quotas can be set for each client, overriding the global quotas.

The new openNDS _upload and download rate limits_ allow "bursting" for short intervals at high rates, with the instantaneous burst rate being limited by SQM. This enables much better performance on a system with a limited Internet feed without compromising the overall system "fair usage".

The new _upload and download quotas_ provide a hard limit for upload and download data amounts, if exceeded the client is deauthenticated. 

**SQM** continues to provide bandwidth throttling and queue management to enhance performance.
