### ISSUE TITLE
opennds webserver vs uhttpd

### ISSUE THREAD

**Issue by laoshaw** [openNDS/openNDS#89]
running 7.0.1 on openwrt.

1. enable port 2080 in /etc/config/opennds
2. added port 2080  to /etc/config/uhttpd with wwwroot to /etc/opennds
3. set 'option faspath /nodog/x.html' and create a simple x.html for testing
4. restart both uhttpd and opennds

Now CPD still always redirect to http://192.168.1.1:2050 which is opennds's internal webserver.

how can I disable opennds's internal webserver(at port 2050?) and use uhttpd to serve PreAuth page? this way the PreAuth can leverage all the CSS etc from /www which is for uhttpd, or there is no way to disable the internet webserver at port 2050?

**Comment by bluewavenet** [comment]
@laoshaw 
The internal webserver of openNDS (MHD) is a fundamental part of how openNDS works, but you do not have to use it for serving the "splash" page triggered by the client CPD (captive portal detection).

Looking at your list, it seems you are very much misunderstanding how to use the FAS API.
Before we go into any detail, it would be sensible for you to read the documentation at:
https://opennds.readthedocs.io/en/stable/

Yes you can use uhttpd as a web host for FAS scripts. The examples included with the installation are mostly written in PHP, which is fully supported by uhttpd.

**Comment by laoshaw** [comment]
Thanks. I read that doc a couple of times, I could see fas page now, however the log always showed 'Created web server on 192.168.1.1:2050', it looks like no matter how I change config files 2050 is always running with opennds's internal webserver?

**Comment by bluewavenet** [comment]
@laoshaw 

> no matter how I change config files

Which config files and what did you change?

I would recommend reading this section of the documentation:
https://opennds.readthedocs.io/en/stable/fas.html#using-the-fas-example-scripts-fas-hid-fas-aes-php-and-fas-aes-https-php

**Comment by laoshaw** [comment]
is 2050 port supposed to be off when fas is running? I tried those fas options in /etc/config/opennds and while fas is running, 2050 is always open(though fas uses 2080). Thanks a lot for the help.

**Comment by bluewavenet** [comment]
@laoshaw 

> is 2050 port supposed to be off when fas is running?

No.

The port FAS uses is the port the "splash" page is served from.

Please read this section:
https://opennds.readthedocs.io/en/stable/howitworks.html#how-opennds-nds-works

**Comment by bluewavenet** [comment]
@laoshaw 
The openNDS port (usually 2050) is the "capture" port that clients are redirected to. openNDS then enters the client into its database and hands over to FAS (wherever it is) where the dynamic login dialogue is generated.

**Comment by sicelo** [comment]
To put it a bit differently, 2050 is NDS' port. Your FAS at 2080 cannot do anything on its own. Rather, after processing, it needs to talk to NDS via 2050, instructing it do auth or deauth the client. So, 2050 will always be working

**Comment by laoshaw** [comment]
Got it. Thanks again!!

**Comment by bluewavenet** [comment]
@laoshaw 
Do please let us know how you get on and don't hesitate to ask if you have any questions.
