### ISSUE TITLE
OpenNDS crashes after running for a while

### ISSUE THREAD

**Issue by minhng99** [openNDS/openNDS#96]
Hi,
OpenNDS crashed on my device after a few days of running, I don't know exactly when it is crashed and the syslog has overflow so I don't know what went wrong with it.
When attempt to restart the openNDS service then the error below appear:

```
Mon Jan 11 02:01:44 2021 daemon.notice opennds[19778]: openNDS Version 7.0.1
Mon Jan 11 02:01:44 2021 daemon.notice opennds[19778]: ipset support is available
Mon Jan 11 02:01:44 2021 daemon.notice opennds[19778]: dnsmasq ipset support is available
Mon Jan 11 02:01:44 2021 daemon.err opennds[19778]: Failed to create Walled Garden
Mon Jan 11 02:01:44 2021 daemon.err opennds[19778]: Exiting...
```
I've found that the `ipset` and `iptables` rules is still there, normally after I gently stop the openNDS process it will delete the `iptables` and `ipset` rules, I've manually deleted those and it's able to start again.

My theory is that there was something that make OpenNDS crashed which doesn't let it clear the rules before shutdown, when it's trying to start again to this line here https://github.com/openNDS/openNDS/blob/master/src/main.c#L387 it can't do `ipset destroy walledgarden` because `iptables` still using this rule and resulted in `Set cannot be destroyed: it is in use by a kernel component`

I'm currently create a workaround this by flushing the iptables rule before the service restart, I wonder if is there a more proper way to do this?

**Comment by minhng99** [comment]
Oh, I was using the `v7.0.1`, apparently `v8.0.0` has fixed this?
`  * Fix - On startup, call iptables_fw_destroy before doing any other setup [bluewavenet]`

**Comment by bluewavenet** [comment]
@minhng99 
Thankyou for reporting and yes v8.0.0 now calls iptables_fw_destroy at the correct time!

This does leave the unanswered question of why it crashed for you in the first place....

The new release has implemented a "wait for ndsctl if busy" check that prevents lockups/crashes. The probability of a crash was low in normal operations but did increase rapidly with the number of clients connecting. Perhaps this is what you saw.
