### ISSUE TITLE
How do i running PHP/Python file through NDS? do version 8.0.0 have redirect function?

### ISSUE THREAD

**Issue by andy-yeung** [openNDS/openNDS#99]
**The version of the operating system:**
 RaspberryPi 3B
 
 **Consequences:**
If i want to run other type file such as .html .php .py, how do i set the opennds.conf?
![IMG-6790](https://user-images.githubusercontent.com/62322681/105322361-bcf8a080-5c03-11eb-8185-6f6637eb7bc4.jpg)
It only shows the text-content...

Another question is how do I make the redirectURL function? there is no web site show up after the authentication, despite I have set the path 192.168.50.1/xxx.php
![image](https://user-images.githubusercontent.com/62322681/105323171-cb938780-5c04-11eb-9f59-e50a949e3103.png)

Thank you for your help!! :-D

**Comment by bluewavenet** [comment]
@andy-yeung 
First, you need to understand the fundamentals of how openNDS works.

The series of "splash pages" a client sees while logging in are dynamic html generated by the Forwarding Authentication Service (FAS) and served to the client by either openNDS itself or a separate web server.

The content the client receives will vary depending on the responses entered by the client.

**By default**, openNDS uses its own built in web server to send html to the client. This html is dynamically generated by a bash script (login.sh)

The openNDS FAS API can be used to customise openNDS, allowing use of any program or interpreted script to generate the required html code and serve it with a web server. This web server can be one of the following:

 * The built in openNDS web server
 * A separate web server running on the same device as openNDS
 * A separate web server running on a device located on the same local area network as the openNDS device
 * An Internet based web hosting service
 
See the FAS documentation:
https://opennds.readthedocs.io/en/stable/fas.html#forwarding-authentication-service-fas

**Comment by bluewavenet** [comment]
@andy-yeung 
Note from the opennds.conf (as shown in your screenshot):
```
# Option: RedirectURL
# Default: Deprecated
#
# NOTE: RedirectURL has been removed from version 7.0.0 onwards.
#	As most CPD implementations immediately close the "splash" page
#	as soon as NDS authenticates, RedirectURL would not be shown.
#
#	This functionality, ie displaying a particular web page as a final "Landing Page"
#	is reliably achieved using FAS.
```
**_RedirectURL has been removed from version 7.0.0 onwards_**  -  This means you cannot use it, and if you could, it would most likely not work anyway as most clients will block it as a security hazard.

It has been replaced by functionality built into FAS.

**Comment by bluewavenet** [comment]
@andy-yeung 
Feel free to reopen this if you need any help.
